### ISSUE TITLE
since 20.09, breeze-qt is broken, breaking KGPG, KMail, Kontact ...

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#102361]
**Describe the bug**
Since 20.09, when i try to use KGPG (`nix-shell -p kgpg`), KMail (`nix-shell -p kmail`) or Kontact (`nix-shell -p kontact`)

I get

```
error: Package ‘breeze-qt5-5.18.5’ in /nix/store/fvik248l0i6x4y1kln813fqhh7cdj4cq-nixos-20.09.1500.edb26126d98/nixos/pkgs/desktops/plasma-5/default.nix:96 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**To Reproduce**
1. `nix-shell -p kgpg`

**Expected behavior**
Applications should work

**Additional context**
I don't know if i should report in new issue (like this) or in this issue https://github.com/NixOS/nixpkgs/issues/102340

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(pinage404): `"home-manager-20.09, nixos-20.09.1500.edb26126d98, nixos-unstable-21.03pre249162.1dc37370c48"`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/101369

**Comment by doronbehar** [comment]
I made #102347 fix this issue.

**Comment by jonringer** [comment]
This at least builds now #102347

I was able to launch kmail. But I don't have plasma running, so it was still having some issues
