### ISSUE TITLE
redshift-gtk

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10280]
```
$ redshift-gtk
ERROR:root:Could not find any typelib for Gtk
Traceback (most recent call last):
  File "/nix/store/zinn3vapx188l4mx4m6q79barxwqa371-redshift-1.10/bin/.redshift-gtk-wrapped", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/nix/store/zinn3vapx188l4mx4m6q79barxwqa371-redshift-1.10/lib/python3.4/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    from gi.repository import Gtk, GLib, GObject
ImportError: cannot import name 'Gtk'
```

**Comment by domenkozar** [comment]
fixed in 19f2be45233fe8556d7d5291efdd7bbe5ffa9cf2

**Comment by Pitometsu** [comment]
No. Still the same even after `nixos-rebuild switch --upgrade`.

**Comment by vcunat** [comment]
That command wouldn't get such new commits. See  https://nixos.org/wiki/FAQ#What_are_channels_and_how_they_get_updated.3F

**Comment by Pitometsu** [comment]
@vcunat why so?
```
$  nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```

**Comment by vcunat** [comment]
Because channels lag behind the branch they track, as is explained in that link.

**Comment by Pitometsu** [comment]
ok, thanks, it work after switching to
```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```
