### ISSUE TITLE
zathura cannot load libpdf-mupdf.so

### ISSUE THREAD

**Issue by sumnerevans** [NixOS/nixpkgs#103723]
**Describe the bug**

Zathura fails to open PDFs with the following error:

```
$ zathura resources-for-statistical-methods-supporting-googles-ad-business.pdf
error: Could not load plugin '/nix/store/59pdfd8z2k672n9dviclq600k13gadjq-zathura-with-plugins-0.4.5/lib/zathura/libpdf-mupdf.so' (/nix/store/59pdfd8z2k672n9dviclq600k13gadjq-zathura-with-plugins-0.4.5/lib/zathura/libpdf-mupdf.so: undefined symbol: jpeg_resync_to_restart).
```

**To Reproduce**
1. Try to open a PDF

**Expected behavior**
It should load the PDF.

**Screenshots**
N/A

**Additional context**

**Notify maintainers**
@grwlf @globin @TethysSvensson

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.8, NixOS, 21.03pre251971.a371c107116 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre251971.a371c107116"`
 - channels(sumner): `"nixos-21.03pre251971.a371c107116, nixpkgs-21.03pre251971.a371c107116"`
 - nixpkgs: `/home/sumner/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Please let me know if you need additional information!

**Comment by Technical27** [comment]
as a temporary fix you can add 
`zathura = super.zathura.override { useMupdf = false };`
as an overlay

**Comment by emmanuelrosa** [comment]
The issue was caused by e13120bb098f25ac552570c2f9ea5908ef102a50

libjpeg, jbig2dec, and libopenjpeg2 are no longer being linked to the zathura libpdf-mupdf.so library.

**Comment by emmanuelrosa** [comment]
libmupdf is not being linked either, which is probably the real culprit since mupdf is able to open PDFs without this issue.

**Comment by wamserma** [comment]
@sumnerevans @emmanuelrosa sorry for breaking things, and thanks @jonringer for fixing this in https://github.com/NixOS/nixpkgs/pull/103727

**Comment by jonringer** [comment]
oh yea, this was lready fixed

**Comment by emmanuelrosa** [comment]
It's fixed for me.

**Comment by jonringer** [comment]
closing as this was fixed

**Comment by sumnerevans** [comment]
I just did a `nixos-rebuild switch --upgrade` after removing the temporary fix mentioned here: https://github.com/NixOS/nixpkgs/issues/103723#issuecomment-727094901 and this issue still exists.

**Comment by jonringer** [comment]
@sumnerevans this is a channel issue, the channel is still stuck at 2deeb58f49480f468adca6b08291322de4dbce6b , which doesn't include the fix

**Comment by jonringer** [comment]
I restarted the blocking job, which failed from a flakey test, hopefully everything else passes
