### ISSUE TITLE
x2goserver does not function: missing dependency?

### ISSUE THREAD

**Issue by roybatty2019** [NixOS/nixpkgs#104266]
I just install nixos for the first time.

I added x2goserver to environment.systemPackages in /etc/nixos/desktop.nix and ran "nixos-rebuild switch"

This completed apparently successfully, however attempting to connect to the x2goserver failed with an error: "Connection failed. bash: x2golistdesktops: command not found"

As a test I ran x2golistdesktops locally on the nixos system. It fails like this:
[robb@novena:~]$ x2golistdesktops
unknown backend  at /nix/store/65x7c4dnd8yzn5i37knhiwqxfa95jyv8-perl-5.32.0-env/lib/perl5/site_perl/5.32.0/X2Go/Server/DB.pm line 63.
Compilation failed in require at /nix/store/lhp2ip489v8qm8mcpf31hm6rgkjdbkdz-x2goserver-4.1.0.3/bin/.x2golistsessions-wrapped line 26.
BEGIN failed--compilation aborted at /nix/store/lhp2ip489v8qm8mcpf31hm6rgkjdbkdz-x2goserver-4.1.0.3/bin/.x2golistsessions-wrapped line 26.

It seems that some Perl database backend access module is expected but not found.
This may also be the cause of the failure to connect.

**Notify maintainers**

Not sure what the above means, I should send email or what? Doesn't the defect tracking system contact them automatically? According to a nixos package search the maintainer is:
averelld <averell+nixos@rxd4.com>

This is on an ARM architecture system (novena laptop), as you can see below.

nix-shell -p nix-info --run "nix-info -m"
 - system: `"armv7l-linux"`
 - host os: `Linux 5.7.0-rc2, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

FYI "nix-channel --list" returns:
nixos https://nixos.org/channels/nixos-unstable

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mkg20001** [comment]
I've pushed some changes to unstable that should fix a perl issue with x2goserver, also the command not found has been fixed some time ago.

Please try again.

**Comment by nezumi1503** [comment]
Still a problem, even with an unstable channel:
`unknown backend  at /nix/store/k10b2dj6nh8kzv15wyhq2cvnjlv1dcry-perl-5.34.0-env/lib/perl5/site_perl/5.34.0/X2Go/Server/DB.pm line 63.

Compilation failed in require at /nix/store/cvydmsck3hvj94ymjkn6azl01fl4wlxs-x2goserver-4.1.0.3/bin/.x2golistsessions-wrapped line 26.

BEGIN failed--compilation aborted at /nix/store/cvydmsck3hvj94ymjkn6azl01fl4wlxs-x2goserver-4.1.0.3/bin/.x2golistsessions-wrapped line 26.`

**Comment by Artturin** [comment]
you have to use the module so that the wrapper in /run/wrappers/bin/ is created

the package expr has
```
      substituteInPlace X2Go/Server/DB.pm \
        --replace '$x2go_lib_path/libx2go-server-db-sqlite3-wrapper' \
                  '/run/wrappers/bin/x2gosqliteWrapper'
```

**Comment by nezumi1503** [comment]
OK, now I get that x2goserver has to be installed as a service. [The wiki article on remote desktops](https://nixos.wiki/wiki/Remote_Desktop) needs un update:
put
 `services.x2goserver.enable = true;
`
into configuration.nix.
