### ISSUE TITLE
darwin stdenv can't bootstrap on macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixpkgs#104580]
Initial support for builds on Big Sur was added in https://github.com/NixOS/nixpkgs/pull/98541 but the initial bootstrapping stages in the stdenv still link against the libSystem library that's part of bootstrap tools. This means builds depend on having a cached stdenv built by 11.15 or earlier available.

```
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-ICU-osx-10.10.5.drv-7/ICU-531.48/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
./runConfigureICU: ./configure failed
make: *** [makefile:964: /private/tmp/nix-build-ICU-osx-10.10.5.drv-7/ICU-531.48/build/Makefile] Error 1
```

```
configure:2913: checking whether the C compiler works
configure:2935: cc -DU_SHOW_CPLUSPLUS_API=1 -DU_SHOW_INTERNAL_API=1 -DU_TIMEZONE=timezone -DICU_DATA_DIR="\"/usr/share/icu/\""   -g -Os -Wglobal-constructors -fno-exceptions -fvisibility=hidden   -O2  -DSTD_INSPIRED -DMAC_OS_X_VERSION_MIN_REQUIRED=1070    conftest.c  >&5
ld: warning: passed two min versions (10.12.0, 10.12) for platform macOS. Using 10.12.
ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**

On macOS 11.0 run
```
nix-build -A stdenv.__bootPackages.stdenv.__bootPackages.stdenv.__bootPackages.darwin.ICU
nix-build -A stdenv.__bootPackages.stdenv.__bootPackages.stdenv.__bootPackages.darwin.ICU --check
```

**Comment by LnL7** [comment]
These changes are enough to work around this and link against a tbd libSystem in the first bootstrap stages, however using fetchurl for github archives is not stable so we'll need a separate release archive for this.

https://gist.github.com/LnL7/a17a042dd21258b957279637bb6be627

**Comment by LnL7** [comment]
There's another issue in stage2 with `Security/boot.nix` which gets referenced by configd.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Security/boot.nix#L18-L19

**Comment by thefloweringash** [comment]
> There's another issue in stage2 with `Security/boot.nix` which gets referenced by configd.
> 
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Security/boot.nix#L18-L19

For what it's worth, those referenced files do exist on Big Sur. Still not good for purity though.

**Comment by LnL7** [comment]
As I misread what it was symlinking.

**Comment by edude03** [comment]
@LnL7 on a clean install of Big Sur 11.0.1 on x86_64 I installed nix, cloned nixpkgs master, applied your patch and used it to try and build ICU using `-I nixpkgs=/path/to/patched/nixpkgs` but I'm still running into this issue. Is that expected?

**Comment by thefloweringash** [comment]
> These changes are enough to work around this and link against a tbd libSystem in the first bootstrap stages, however using fetchurl for github archives is not stable so we'll need a separate release archive for this.

We've added an archive for tagged releases via github actions (https://github.com/NixOS/darwin-stubs/pull/4). We should add any missing libraries and tag a release to make the tarball available.

**Comment by KolesnichenkoDS** [comment]
can anyone please elaborate on how to workaround this?
i tried the same thing @edude03 described and it didn't work for me too
i also tried switching to staging/unstable channels and that didn't work either
is there a workaround except downgrading to catalina for now?

**Comment by LnL7** [comment]
@edude03  @KolesnichenkoDS Unless you're building staging or another mass rebuild this issue won't be relevant to your problem.

**Comment by zupo** [comment]
@LnL7: I am using nix-shell for my Python projects, pinned to latest nixos-20.09 and master of https://github.com/nix-community/poetry2nix. I am definitely affected by this, most of the time nix-shell building fails on my Big Sur and I have to wait for our CI (still on Catalina) to build and upload derivations to cache.

**Comment by LnL7** [comment]
That error has nothing to do with the issue described here, firstly none of the initial compatibility changes have been backported to 20.09. Secondly if it doesn't work on master either there's a good chance this is something something specific to upstream python or the python infrastructure. In that case please report it in a separate issue.

**Comment by remi-gelinas** [comment]
Is there a workaround for those looking to build staging on Big Sur specifically for flake support?

Or is it more worth it to just downgrade or copy the cache over for now?

**Comment by rodfersou** [comment]
> That error has nothing to do with the issue described here, firstly none of the initial compatibility changes have been backported to 20.09. Secondly if it doesn't work on master either there's a good chance this is something something specific to upstream python or the python infrastructure. In that case please report it in a separate issue.

I disagree that the problem is not related with nix, but with Python.  I'm waiting for a fix for a long time, yesterday did my second Big Sur upgrade hopping that this issue would be gone, but still is not working.

is it possible (please) to have someone from nix team to check what is going on in a Big Sur machine?

**Comment by nasyxx** [comment]
In fact, what we need is to completely build nix and nixpkgs from source without any bin caches.

**Comment by jerbaroo** [comment]
Running into `ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64` [here](https://github.com/reflex-frp/reflex-platform/issues/714), is this the same issue?

**Comment by LnL7** [comment]
@jerbaroo No, that's not an stdenv build.

**Comment by zupo** [comment]
Hey @LnL7, I've prepared a minimal `shell.nix` with a Poetry-based Python environment that showcase the problem I have: https://github.com/niteoweb/big-sur-poetry-test

Running `nix-shell` in this test repo:
* passes on Linux:  https://app.circleci.com/pipelines/github/niteoweb/big-sur-poetry-test/3/workflows/37c9b3ec-5d5d-4d60-b6f2-d007342e1c81/jobs/6
* passes on Catalina: https://app.circleci.com/pipelines/github/niteoweb/big-sur-poetry-test/4/workflows/e52f2f5f-66b9-4681-9d09-b91431fefaef/jobs/7
* fails on my local Big Sur: `configure: error: C compiler cannot create executables`

<details>
  <summary>full dump</summary>


```
➜  big-sur-poetry-test git:(main) ✗ nix-shell
these derivations will be built:
  /nix/store/20hcj04mgb8z8z13w2z810nrxrv6a0sd-coreutils-8.31.drv
  /nix/store/visd0f4x0dfrzh5pix31j4imzqi4yhv2-openssl-1.1.1i.drv
  /nix/store/4isfj8x4pjk9dars93y0hqjmwpinvj1p-nghttp2-1.41.0.drv
  /nix/store/v4qa1dm72qmfk1zz4yfjsakx3z8gg6q2-libssh2-1.9.0.drv
  /nix/store/56bl8il7kzh8qy5p7a5hn2d82pdaxpf8-curl-7.74.0.drv
  /nix/store/kdlaj6mzji9cpmqlh8pifk2jji6dh9zf-mirrors-list.drv
  /nix/store/cfamfb2j5np1dm2ql8rrydj3ifh5l8xp-psutil-5.8.0.tar.gz.drv
  /nix/store/di45klx5x9gg08qz7wlnrawgmim9r9hb-builder.pl.drv
  /nix/store/rlpg5rsdvdsmfyg416cc9pacrw0zvshs-python3.8-psutil-5.8.0.drv
  /nix/store/hxk1287cw4kriz692233mrjdffx62yn9-python3-3.8.5-env.drv
these paths will be fetched (57.45 MiB download, 193.07 MiB unpacked):
  /nix/store/2ws9cmamvr7xyvdg4d2nnd1bmr1zjrrq-bootstrap-tools
  /nix/store/37izqb2hkl6hkkzmy1wavhksmidp0j68-openssl-1.1.1i
  /nix/store/4i4mbi6gyilm62vj0kxasy7cmw8c5dzg-bootstrap-stage3-binutils-wrapper-
  /nix/store/4lzc3ww4ychns7xdpx1almfmlzg5cv2n-expand-response-params
  /nix/store/5203gm0m1s3jk4nzr78w18i9hily5mvj-libxml2-2.9.10
  /nix/store/6p0fj0mf1mmcdl140p326m63drrq6ir5-pip-build-hook.sh
  /nix/store/79vvclchw1d1i4qa3zg6qyhvd3p8vp7l-libssh2-1.9.0
  /nix/store/7nik2w4x628l7m7jh9rzkkf4hhdnf3sm-hook
  /nix/store/7yjb5kcnlrha9cjp4q77qbzl46qd646c-fixup-hook.sh
  /nix/store/9h92gyn9a2d61yz1gvw8gx4nfqrjvx4x-swift-corefoundation
  /nix/store/a6gqbyaxzd91mz9snl5f83f55pij5qgh-stdenv-darwin
  /nix/store/aahj38cir7776m69k69ki4r6lfiwixb7-curl-7.74.0.tar.bz2
  /nix/store/arhdawk39c48pfh663wka9f301by4v0f-hook
  /nix/store/blv5xmwps8mmbbgd6wrcg8vlrlvp0adp-python-recompile-bytecode-hook
  /nix/store/bpzbb024gbi1arlxmc80rp7fvjdvkia3-libev-4.33
  /nix/store/c289f30an35yp2mj1b4i3ffhldfviy50-python-catch-conflicts-hook
  /nix/store/f18m26x5d7xywdx12ni631j79d5k1kjw-perl-5.32.0
  /nix/store/f3f6fzdi59rqrclnfik3vzq33i1an2x0-python3.8-setuptools_scm-4.1.2
  /nix/store/fmvjni9mbba8v2ixaxdz19fij8fbya1d-xz-5.2.5-bin
  /nix/store/fwq6c962lrnx8al2r9aqdqskprhqqvw5-nghttp2-1.41.0.tar.bz2
  /nix/store/gz5mznlkshaifgp4wwyip8dqy2jzdzwi-python-namespaces-hook.sh
  /nix/store/h3f0zl7zjgf9741alzm1cq75ma970rfm-pkg-config-0.29.2
  /nix/store/hik1ncyfcprr8108vba67myw18nhlxrs-openssl-1.1.1i.tar.gz
  /nix/store/i1hay70lgwydg7wwh6h6la4r3kis4k74-libkrb5-1.18
  /nix/store/iddks9pzzsvarxgs0g8s0lx55vxwhrf7-bootstrap-stage3-clang-wrapper-
  /nix/store/ixa7ljbrdv81qnxgxqwhd26vbfk65d4z-zlib-1.2.11
  /nix/store/kbp52dlzaxf3l2drhzk715y3cbh8jg4c-pkg-config-wrapper-0.29.2
  /nix/store/l32pamj51f1v6b6vmqd3rgmcpg2bnnbg-coreutils-8.31.tar.xz
  /nix/store/lcqp8qpz5l69v293yfwa2l910grdz1ij-python-imports-check-hook.sh
  /nix/store/li772ck934jsvqlnw6j765j57kf46z2m-c-ares-1.15.0
  /nix/store/md2gdihqwsyiyfvpvqs9q0xks20vw4di-ICU-osx-10.10.5
  /nix/store/mg8rm13dx2bl00nx9i43xzmfr5n81sf2-libssh2-1.9.0.tar.gz
  /nix/store/p7xympcmjynp7yjv82shbgyb5irg0a8m-nghttp2-1.41.0-lib
  /nix/store/pq30g5z5w49vjnagwd4xp4fmaw78b1k4-hook
  /nix/store/pyywr1521pp89a013qqcbi9p58s59v85-pip-install-hook
  /nix/store/q8rw9q2jsijh5413ja5krycqnfdf6q8f-hook
  /nix/store/rc8rva2adbgvgcjnzf4fbsjbjl604cwb-bootstrap-stage3-stdenv-darwin
  /nix/store/slh3ygpd3sm8ym8xxr5czzl69fh91kkj-python-remove-tests-dir-hook
  /nix/store/sw38s28vb8v7f8anm9hxr24idg9qpbdm-curl-7.74.0
  /nix/store/w2c46a7d928dn5av633dmg0k2lkghl3q-remove-path-dependencies.sh
  /nix/store/xp8vnq4v1dhx3xp2cajdx9kass3ap8lr-python-remove-bin-bytecode-hook
  /nix/store/xzx4za3j0vr4fs2282747p6ljhiw4wix-yj-4.0.0
  /nix/store/yq5lf5q6wd8x9yk4lhnra8ikw48d32dc-xz-5.2.5
copying path '/nix/store/q8rw9q2jsijh5413ja5krycqnfdf6q8f-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/f18m26x5d7xywdx12ni631j79d5k1kjw-perl-5.32.0' from 'https://cache.nixos.org'...
copying path '/nix/store/a6gqbyaxzd91mz9snl5f83f55pij5qgh-stdenv-darwin' from 'https://cache.nixos.org'...
copying path '/nix/store/gz5mznlkshaifgp4wwyip8dqy2jzdzwi-python-namespaces-hook.sh' from 'https://cache.nixos.org'...
copying path '/nix/store/7yjb5kcnlrha9cjp4q77qbzl46qd646c-fixup-hook.sh' from 'https://cache.nixos.org'...
copying path '/nix/store/xp8vnq4v1dhx3xp2cajdx9kass3ap8lr-python-remove-bin-bytecode-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/slh3ygpd3sm8ym8xxr5czzl69fh91kkj-python-remove-tests-dir-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/xzx4za3j0vr4fs2282747p6ljhiw4wix-yj-4.0.0' from 'https://cache.nixos.org'...
copying path '/nix/store/2ws9cmamvr7xyvdg4d2nnd1bmr1zjrrq-bootstrap-tools' from 'https://cache.nixos.org'...
copying path '/nix/store/li772ck934jsvqlnw6j765j57kf46z2m-c-ares-1.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/l32pamj51f1v6b6vmqd3rgmcpg2bnnbg-coreutils-8.31.tar.xz' from 'https://cache.nixos.org'...
copying path '/nix/store/aahj38cir7776m69k69ki4r6lfiwixb7-curl-7.74.0.tar.bz2' from 'https://cache.nixos.org'...
copying path '/nix/store/4lzc3ww4ychns7xdpx1almfmlzg5cv2n-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/arhdawk39c48pfh663wka9f301by4v0f-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/pq30g5z5w49vjnagwd4xp4fmaw78b1k4-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/bpzbb024gbi1arlxmc80rp7fvjdvkia3-libev-4.33' from 'https://cache.nixos.org'...
copying path '/nix/store/7nik2w4x628l7m7jh9rzkkf4hhdnf3sm-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/mg8rm13dx2bl00nx9i43xzmfr5n81sf2-libssh2-1.9.0.tar.gz' from 'https://cache.nixos.org'...
copying path '/nix/store/fwq6c962lrnx8al2r9aqdqskprhqqvw5-nghttp2-1.41.0.tar.bz2' from 'https://cache.nixos.org'...
copying path '/nix/store/hik1ncyfcprr8108vba67myw18nhlxrs-openssl-1.1.1i.tar.gz' from 'https://cache.nixos.org'...
copying path '/nix/store/6p0fj0mf1mmcdl140p326m63drrq6ir5-pip-build-hook.sh' from 'https://cache.nixos.org'...
copying path '/nix/store/pyywr1521pp89a013qqcbi9p58s59v85-pip-install-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/h3f0zl7zjgf9741alzm1cq75ma970rfm-pkg-config-0.29.2' from 'https://cache.nixos.org'...
copying path '/nix/store/c289f30an35yp2mj1b4i3ffhldfviy50-python-catch-conflicts-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/kbp52dlzaxf3l2drhzk715y3cbh8jg4c-pkg-config-wrapper-0.29.2' from 'https://cache.nixos.org'...
copying path '/nix/store/lcqp8qpz5l69v293yfwa2l910grdz1ij-python-imports-check-hook.sh' from 'https://cache.nixos.org'...
copying path '/nix/store/blv5xmwps8mmbbgd6wrcg8vlrlvp0adp-python-recompile-bytecode-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/f3f6fzdi59rqrclnfik3vzq33i1an2x0-python3.8-setuptools_scm-4.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/w2c46a7d928dn5av633dmg0k2lkghl3q-remove-path-dependencies.sh' from 'https://cache.nixos.org'...
building '/nix/store/di45klx5x9gg08qz7wlnrawgmim9r9hb-builder.pl.drv'...
building '/nix/store/kdlaj6mzji9cpmqlh8pifk2jji6dh9zf-mirrors-list.drv'...
copying path '/nix/store/md2gdihqwsyiyfvpvqs9q0xks20vw4di-ICU-osx-10.10.5' from 'https://cache.nixos.org'...
copying path '/nix/store/4i4mbi6gyilm62vj0kxasy7cmw8c5dzg-bootstrap-stage3-binutils-wrapper-' from 'https://cache.nixos.org'...
copying path '/nix/store/i1hay70lgwydg7wwh6h6la4r3kis4k74-libkrb5-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/p7xympcmjynp7yjv82shbgyb5irg0a8m-nghttp2-1.41.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/37izqb2hkl6hkkzmy1wavhksmidp0j68-openssl-1.1.1i' from 'https://cache.nixos.org'...
copying path '/nix/store/yq5lf5q6wd8x9yk4lhnra8ikw48d32dc-xz-5.2.5' from 'https://cache.nixos.org'...
copying path '/nix/store/ixa7ljbrdv81qnxgxqwhd26vbfk65d4z-zlib-1.2.11' from 'https://cache.nixos.org'...
copying path '/nix/store/fmvjni9mbba8v2ixaxdz19fij8fbya1d-xz-5.2.5-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/iddks9pzzsvarxgs0g8s0lx55vxwhrf7-bootstrap-stage3-clang-wrapper-' from 'https://cache.nixos.org'...
copying path '/nix/store/5203gm0m1s3jk4nzr78w18i9hily5mvj-libxml2-2.9.10' from 'https://cache.nixos.org'...
copying path '/nix/store/79vvclchw1d1i4qa3zg6qyhvd3p8vp7l-libssh2-1.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/sw38s28vb8v7f8anm9hxr24idg9qpbdm-curl-7.74.0' from 'https://cache.nixos.org'...
copying path '/nix/store/9h92gyn9a2d61yz1gvw8gx4nfqrjvx4x-swift-corefoundation' from 'https://cache.nixos.org'...
copying path '/nix/store/rc8rva2adbgvgcjnzf4fbsjbjl604cwb-bootstrap-stage3-stdenv-darwin' from 'https://cache.nixos.org'...
building '/nix/store/20hcj04mgb8z8z13w2z810nrxrv6a0sd-coreutils-8.31.drv'...
unpacking sources
unpacking source archive /nix/store/l32pamj51f1v6b6vmqd3rgmcpg2bnnbg-coreutils-8.31.tar.xz
source root is coreutils-8.31
setting SOURCE_DATE_EPOCH to timestamp 1552262874 of file coreutils-8.31/doc/coreutils.info
patching sources
applying patch /nix/store/i9vf1pxv8kfihrpp9pcbis14y26wrdca-coreutils-8.31-android-cross.patch
patching file lib/strtod.c
configuring
configure flags: --disable-dependency-tracking --prefix=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31 --bindir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/bin --sbindir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/sbin --includedir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/include --oldincludedir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/include --mandir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/share/man --infodir=/nix/store/6mrsgrhdv7s0f41g0gci69y5vc9k2ng5-coreutils-8.31-info/share/info --docdir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/share/doc/coreutils --libdir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/lib --libexecdir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/libexec --localedir=/nix/store/i5k8wzvhmmsmp5g4mcwyqvn1zszbva2f-coreutils-8.31/share/locale --with-packager=https://NixOS.org --enable-single-binary=symlinks
checking for a BSD-compatible install... /nix/store/2ws9cmamvr7xyvdg4d2nnd1bmr1zjrrq-bootstrap-tools/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/2ws9cmamvr7xyvdg4d2nnd1bmr1zjrrq-bootstrap-tools/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-coreutils-8.31.drv-0/coreutils-8.31':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for '/nix/store/20hcj04mgb8z8z13w2z810nrxrv6a0sd-coreutils-8.31.drv' failed with exit code 77
cannot build derivation '/nix/store/visd0f4x0dfrzh5pix31j4imzqi4yhv2-openssl-1.1.1i.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/56bl8il7kzh8qy5p7a5hn2d82pdaxpf8-curl-7.74.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/cfamfb2j5np1dm2ql8rrydj3ifh5l8xp-psutil-5.8.0.tar.gz.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/rlpg5rsdvdsmfyg416cc9pacrw0zvshs-python3.8-psutil-5.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hxk1287cw4kriz692233mrjdffx62yn9-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hxk1287cw4kriz692233mrjdffx62yn9-python3-3.8.5-env.drv' failed
```
</details>

Should I move this to a new issue? If yes, to which repo, https://github.com/nixOS/nixpkgs, https://github.com/LnL7/nix-darwin or https://github.com/nix-community/poetry2nix? 

Finally, thank you for all your hard work keeping Nix running on Macs!

**Comment by Infinisil** [comment]
@zupo Opening a PR to the `release-20.09` branch with the commit(s) you'd like backported cherry-picked (with `-x`) is the way to go. See also https://nixos.org/manual/nixpkgs/stable/#submitting-changes-stable-release-branches.

**Comment by kirelagin** [comment]
Is this now resolved by the merge of #107013?

**Comment by zupo** [comment]
I tried pinning https://github.com/niteoweb/big-sur-poetry-test to latest nixos-20.09 commit (`41dddb1283733c4993cb6be9573d5cef937c1375`), but got the same error as always. How can I try staging? I don't see any staging channel on https://status.nixos.org/?

**Comment by edude03** [comment]
@zupo https://github.com/NixOS/nixpkgs/pull/107013 was merged into staging but I don't think (I'm not sure if) it was merged into 20.09 - so to confirm I'd try using the latest commit from staging.

**Comment by taku0** [comment]
Maybe related: https://github.com/NixOS/nixpkgs/pull/104150#pullrequestreview-579892668.

`nix-build -I nixpkgs=. -A pkgs.pypy` on `staging` fails with `Cannot find C library, ctypes.util.find_library('c') returned None`.

It also shows following errors:

```
[platform:WARNING] ld: warning: directory not found for option '-L/nix/store/0gm1wsc6q4sii8py1kf83isx8aaq03mj-xlibs-wrapper/lib'
[platform:WARNING] ld: warning: directory not found for option '-L/nix/store/pslgzws8yag8fp0srcfk83ky1zxf62mz-apple-framework-Security/lib'
```

**Comment by rb2k** [comment]
I just ran into something similar so I thought I'd comment:

Apple removed the /usr/lib/libc.dylib from disk on macOS Big Sur and only has it available in the linker cache now.
The API calls still work, but things that actually look for the file do not.

This was the patch that fixed it for Python: https://bugs.python.org/issue41100
Any chance that is related?

**Comment by thefloweringash** [comment]
> Is this now resolved by the merge of #107013?

I believe it is. I'll tentatively close this issue since the exact bug that it represents has been fixed. I don't mean to cut off the conversation, and if there are still bootstrapping problems on Big Sur with `master` / `nixpkgs-unstable` feel free to reopen.

For the python ctypes issue, there's a ticket for tracking that at https://github.com/NixOS/nixpkgs/issues/105038

**Comment by ldeck** [comment]
@thefloweringash @LnL7 I see this was closed as fixed, but I'm still seeing issues (on a fresh Big Sur 11.4 install) with `ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64`

Am I missing some work-around?


```
% nix-shell --run "niv update"
...
building '/nix/store/nh146kfyhf0lra9nry12z2n44m59zszg-niv-0.2.18.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/s6mfg7bn91sh22pkqsqj2246wrl52v4b-ghc-8.8.4.
unpacking sources
unpacking source archive /nix/store/gayb02fj8nss712krr1j798ynxxxldvc-niv-0.2.18.tar.gz
source root is niv-0.2.18
setting SOURCE_DATE_EPOCH to timestamp 1600342311 of file niv-0.2.18/src/Niv/Update/Test.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/tmp/nix-build-niv-0.2.18.drv-0/setup-package.conf.d -j16 -threaded -rtsopts
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-niv-0.2.18.drv-0/Main.o )
Linking Setup ...
ld: warning: passed two min versions (10.12.0, 10.12) for platform macOS. Using 10.12.
ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
builder for '/nix/store/nh146kfyhf0lra9nry12z2n44m59zszg-niv-0.2.18.drv' failed with exit code 1
error: build of '/nix/store/nh146kfyhf0lra9nry12z2n44m59zszg-niv-0.2.18.drv' failed
```

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/xycwyp06s3hjafaiplh1f87jsn36mwps-nix-info
  /nix/store/yca7h9lyacs16sk44jsw987jhrdqsdmr-DarwinTools-1
copying path '/nix/store/yca7h9lyacs16sk44jsw987jhrdqsdmr-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/xycwyp06s3hjafaiplh1f87jsn36mwps-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(ldeck): `"nixpkgs-21.11pre300283.f930ea227ce"`
 - nixpkgs: `/Users/ldeck/.nix-defexpr/channels/nixpkgs`
```

**Comment by edude03** [comment]
Niv is likely pinning an older version of nixpkgs without this issue fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
