### ISSUE TITLE
microcodeIntel update makes ASUS UX305CA unbootable

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#105172]
**Describe the bug**
Computer shows GRUB boot menu, upon selection of NixOS entry, the screen stays blank indefinitely.

**To Reproduce**
1. Buy ASUS UX305CA laptop
2. Update to NixOS 20.09 (any commit since c89ffdc56d3f8147305ad628745f7c0ef2356c20) *OR* NixOS unstable (any commit since a79902f23e9c84a0b6c389f75a91f103e1ef0e5e)
3. Reboot

**Expected behavior**
The OS should be able to boot

**Additional context**
I spent a bit of time reducing this to a single commit. I have this issue on `master` and `release-20.09`.
The Intel microcode updates in the above commits seem to cause the issue.

**Notify maintainers**
@mweinelt 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - microcodeIntel
# a list of nixos modules affected by the problem
module:
```

**Comment by mweinelt** [comment]
There was a regression, which should be fixed with microcodeIntel 20201118. I forgot to backport them to 20.03 and 20.09, I did that just now. https://github.com/NixOS/nixpkgs/pull/104303#issuecomment-734969279

> Buy ASUS UX305CA laptop

:smile:

**Comment by NeQuissimus** [comment]
:smile: 

I had already tried cherry-picking onto 20.09, does not seem to help.
I'd say we keep this issue open and I'll report back at some point.
For now, I am trying my luck with an overlay that uses `20200616`

**Comment by Shados** [comment]
Oh, *this* is why my laptop won't boot... `20201118` does not fix it, I am able to boot fine with `20200616`.

**Comment by NeQuissimus** [comment]
I believe the upstream issue to be https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/31 btw (https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/31#issuecomment-642367404 mentions the m3 CPU specifically)

**Comment by mweinelt** [comment]
This is just sad. I wonder whether we should revert to 20200616 then.

Can you check for open issues over at
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues?

**Comment by NeQuissimus** [comment]
And for others, that come across this issue, here is an overlay that downgrades the derivation:

https://github.com/NeQuissimus/DevSetup/blob/8803c4443ea0ff76b333f76796cbc60c4bc1b708/ux305c.nix#L37-L39
https://github.com/NeQuissimus/DevSetup/blob/8803c4443ea0ff76b333f76796cbc60c4bc1b708/ux305c-overlay.nix

**Comment by mweinelt** [comment]
> I believe the upstream issue to be [intel/Intel-Linux-Processor-Microcode-Data-Files#31](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/31) btw ([intel/Intel-Linux-Processor-Microcode-Data-Files#31 (comment)](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/31#issuecomment-642367404) mentions the m3 CPU specifically)

Though that comment is from June and does not feel actionable to me. Better to create something new relating to the november series of microcode releases.

**Comment by Shados** [comment]
Still matters to me. I'll test whether or not the current, more recent microcode (`20210216`) still breaks booting on this laptop, though.

**Comment by Shados** [comment]
Yeah, still broken with `20210216`. I might do some digging and see if I can narrow things down any.

**Comment by Shados** [comment]
Boots OK with the even-newer `microcode-20210608` files.

**Comment by NeQuissimus** [comment]
@Shados Awesome, I can confirm my laptop boots with `20210608`. I created #126888 to update the version in nixpkgs

**Comment by mweinelt** [comment]
Fixed in #126291. Backports to release branches will be up soon.
