### ISSUE TITLE
Allowing NixOS VM's to be run on macOS

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs#108984]
People using macOS currently can't _interactively_ run NixOS VM's as described e.g. [here](https://www.haskellforall.com/2020/11/how-to-use-nixos-for-lightweight.html), even with a remote Linux builder. In this issue I'm describing some ways in how that could be made to work. Note that speed is important as well, so `kvm`/`hvf` and co. should be used if possible.

Relevant issue is https://github.com/NixOS/nixpkgs/issues/64578. Ping @zupo @matthewbauer @nmattia @roberth. Any pointers/help with this is appreciated.

This issue is sponsored by [Niteo](https://niteo.co/) :)

## Using qemu directly (doesn't work)

With [this change](https://github.com/Infinisil/nixpkgs/commit/4d244410ee0f3e3ece5494533217bbafbd95d9b3) it's possible to build a NixOS VM run script that is executable on macOS (note that this requires a remote Linux builder)

```
$ nix-build '<nixpkgs/nixos>' \
  --argstr system x86_64-linux \
  --arg configuration '{ virtualisation.qemu.pkgs = import <nixpkgs> { system = "x86_64-darwin"; }; }' \
  -A vm \
  -I nixpkgs=https://github.com/infinisil/nixpkgs/archive/4d244410ee0f3e3ece5494533217bbafbd95d9b3.tar.gz
/nix/store/2a7cbyp9xp12ddc4lxb4h93dxa5yfndy-nixos-vm
```

However running the VM doesn't actually work:
```
$ result/bin/run-nixos-vm                                                          
qemu-system-x86_64: -virtfs local,path=/nix/store,security_model=none,mount_tag=store: There is no option group 'virtfs'
qemu-system-x86_64: -virtfs local,path=/nix/store,security_model=none,mount_tag=store: virtfs support is disabled
```

This is because qemu doesn't support virtfs on macOS.

It [was suggested](https://github.com/NixOS/nixpkgs/issues/64578#issuecomment-668102681) that [this patch](https://patchwork.kernel.org/patch/10468143/) could be used to make it support virtfs. This was attempted [here](https://github.com/Infinisil/nixpkgs/commit/57562282ab34fc44a492f32a13939d77e29d0d9b), however the build doesn't succeed:

```
$ nix-build https://github.com/infinisil/nixpkgs/archive/57562282ab34fc44a492f32a13939d77e29d0d9b.tar.gz -A qemu
[...]
fsdev/virtfs-proxy-helper.c:16:10: fatal error: 'sys/fsuid.h' file not found
#include <sys/fsuid.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [/private/var/folders/l6/7v9ppmg12q90382m246y3g5c0000gn/T/nix-build-qemu-5.1.0.drv-0/qemu-5.1.0/rules.mak:69: fsdev/virtfs-proxy-helper.o] Error 1
make: *** Waiting for unfinished jobs....
builder for '/nix/store/z8mkhjvaz3r7dixv94c1jprwx8gvl0gh-qemu-5.1.0.drv' failed with exit code 2
error: build of '/nix/store/z8mkhjvaz3r7dixv94c1jprwx8gvl0gh-qemu-5.1.0.drv' failed
```

Attempting to remove all the missing header files from `virtfs-proxy-helper.c`, including `<sys/fsuid.h>`, `<sys/vfs.h>`, `<linux/fs.h>` and `<cap-ng.h>` just leads to compilation errors, seemingly indicating that this is a Linux-only functionality.

[This page](https://wiki.qemu.org/Documentation/9psetup#Starting_the_Guest_directly) however mentions that:

> FSDRIVER: Either "local", "proxy" or "synth". This option specifies the filesystem driver backend to use. In short: you want to use "local". In detail:
> - local: Simply lets QEMU call the individual VFS functions (more or less) directly on host.
> - proxy: this driver was supposed to dispatch the VFS functions to be called from a separate process (by virtfs-proxy-helper), however the "proxy" driver is currently not considered to be production grade.

And indeed, the `run-nixos-vm` script only uses `local`, quoting the script:
```
-virtfs local,path=/nix/store,security_model=none,mount_tag=store \
-virtfs local,path=$TMPDIR/xchg,security_model=none,mount_tag=xchg \
-virtfs local,path=${SHARED_DIR:-$TMPDIR/xchg},security_model=none,mount_tag=shared \
```

Attempting to not compile that tool with [this commit](https://github.com/Infinisil/nixpkgs/commit/5ed493ed6ae957aa510d5292eb373b8b1f4a3db1) however also doesn't work, failing again on seemingly Linux-specific headers:
```
$ nix-build https://github.com/infinisil/nixpkgs/archive/5ed493ed6ae957aa510d5292eb373b8b1f4a3db1.tar.gz -A qemu
[...]
/private/var/folders/l6/7v9ppmg12q90382m246y3g5c0000gn/T/nix-build-qemu-5.1.0.drv-0/qemu-5.1.0/fsdev/file-op-9p.h:19:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [/private/var/folders/l6/7v9ppmg12q90382m246y3g5c0000gn/T/nix-build-qemu-5.1.0.drv-0/qemu-5.1.0/rules.mak:69: fsdev/qemu-fsdev.o] Error 1
builder for '/nix/store/zfnmaj3jh16x2qlryzyf3m2gy3zcww53-qemu-5.1.0.drv' failed with exit code 2
error: build of '/nix/store/zfnmaj3jh16x2qlryzyf3m2gy3zcww53-qemu-5.1.0.drv' failed
```

So it seems that qemu just doesn't support virtfs on macOS.

## Using libvirt (might work)

Above qemu documentation also has [this section](https://wiki.qemu.org/Documentation/9psetup#Starting_the_Guest_using_libvirt), which describes how the same can be achieved with [`libvirt`](https://libvirt.org/). While I believe that underneath it just uses qemu as well, there might be some additional libvirt magic happening. And it seems that macOS Mojave [supports virtio-9p](https://www.kraxel.org/blog/2019/06/macos-qemu-guest/), in which post the author also uses libvirt successfully.

Currently the NixOS VM runner just [passes arguments to qemu](https://github.com/NixOS/nixpkgs/blob/07f8292f88f87222b67d2eea7665ab3115aa7512/nixos/modules/virtualisation/qemu-vm.nix#L154-L166). In order to use libvirt we'll have to transform all these arguments to the libvirt equivalent in its [XML configuration](https://libvirt.org/format.html). There even is a libvirt [page describing the equivalent of qemu arguments](https://wiki.libvirt.org/page/QEMUSwitchToLibvirt), which will be very useful. There is also the `virsh domxml-from-native qemu-argv` command which can supposedly do this transformation automatically, though I didn't have any success with it yet.

In above-linked document describing qemu argument equivalents, the `-virtfs` (or the `-fsdev` and `-device` options it's a shorthand for) option is notably missing. This should be replaced with a `<filesystem>` section as described in the qemu documentation link above.

It would be a good idea to first manually create a libvirt configuration and verifying that it works on a NixOS VM. libvirt has a graphical interface which could also be used.

More relevant links:
- [libvirt](https://libvirt.org/news.html#v6-9-0-2020-11-02) supports `virtio-9p` since version 6.9.0
- [haxm](https://github.com/intel/haxm) might be needed for the end result to be fast
- `virtio-9p` can be slow. There is a faster replacement [`virtio-fs`](https://virtio-fs.gitlab.io/). However as far as I know, macOS doesn't have a driver for that.
- [A blogpost](https://www.naut.ca/blog/2020/08/26/ubuntu-vm-on-macos-with-libvirt-qemu/) describing how to use libvirt on macOS to start an Ubuntu VM
- The [NixOS Wiki page on libvirt](https://nixos.wiki/wiki/Libvirt)

## Removing the need for filesystem mapping (might work)

The main reason this `-virtfs` argument is used at all is so that the guest machine in the VM can access the host machines `/nix/store`, which is where the whole system that the guest runs resides in.

An alternate approach however could be to create a `/nix/store` image that can be used by qemu as the `/nix/store` directly, therefore not depending on this filesystem mapping to the host.

See the various `make-*` files in https://github.com/NixOS/nixpkgs/tree/master/nixos/lib, which could be useful for this

**Comment by zupo** [comment]
Another benefit if we get MacOS + QEMU story working: ATM, running NixOS tests on various CI providers such as CircleCI and GitHub Actions is very slow since these services do not provide `/dev/kvm/` on their Linux runners. But they do provide MacOS runners, that come with Mac's KVM alternative, so if MacOS + QEMu story is improved, even people that don't really care about MacOS, but do run CI in the cloud (looking at @domenkozar), stand to gain lots of speed improvements.

**Comment by Infinisil** [comment]
I don't have a lot of time right now, but here's a basic skeleton that could be used to create a libvirt xml config for seeing if that approach is viable:
```nix
let
  pkgs = import <nixpkgs> {};
  config = (import <nixpkgs/nixos> {
    system = "x86_64-linux";
    configuration = <nixpkgs/nixos/modules/virtualisation/qemu-vm.nix>;
  }).config;
in pkgs.writeText "nixos.xml" ''
  <domain type='qemu' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
    ...
    <os>
      ...
      <kernel>${config.system.build.toplevel}/kernel</kernel>
      ...
    </os>
    ...
    <filesystem type='mount' accessmode='$security_model'>
      <source dir='/nix/store'/>
      <target dir='store'/>
    </filesystem>
    ...
  </domain>
''
```

**Comment by domenkozar** [comment]
Refs https://github.com/NixOS/nixpkgs/issues/5241

**Comment by domenkozar** [comment]
> virtio-9p can be slow. There is a faster replacement virtio-fs. However as far as I know, macOS doesn't have a driver for that.

Did you see https://passthroughpo.st/mac-os-adds-early-support-for-virtio-qemu/

**Comment by Infinisil** [comment]
@domenkozar Yeah, click the "uncovered by Qemu developer" link there, it leads to a blogpost I linked above, which only mentions virtio-9p, not virtio-fs. I'm now just seeing that that news article mistakenly used virtio-fs in its picture..

**Comment by domenkozar** [comment]
Ah! That was confused me.

**Comment by domenkozar** [comment]
Benchmarks show that should also speed up the NixOS tests https://matrix.org/_matrix/media/r0/download/johnguant.com/qgAVstnDkCydsABgKmOXRPGW

cc @JJJollyjim do you have a branch for this?

**Comment by Gaelan** [comment]
The patch you linked seems to be only one of a series - presumably you need all of them for it to work. The series is visible here: https://lore.kernel.org/qemu-devel/cover.1529196703.git.keno@juliacomputing.com/. Not sure if there's a way to get the whole series from Patchwork.

**Comment by JJJollyjim** [comment]
Oh hey, just catching up here, I'm a little confused - the stuff where apple has added support for something is all about osx guests, not osx hosts which is what we care about here right?

I don't believe the current virtiofsd (host component) is able to run on osx (e.g. it uses namespaces to sandbox itself), but I don't think there is any technical limitation stopping it being ported?

I recommend patchew if you want a nice way to search for qemu patches and their status: https://patchew.org/QEMU/cover.1529196703.git.keno@juliacomputing.com/ (wish the kernel had something like this... -_-).

Anyway, let me know if you find that switching to virtio-fs will make OSX support work:

I have a branch, but haven't worked on cleaning it up and posting it because for some reason the DAX patches still haven't been submitted to qemu (last I checked), and without DAX the tiny performance improvement isn't worth the complexity. That calculus changes if it will fix OSX though :)

**Comment by JJJollyjim** [comment]
On second thoughts, I patch out the namespace stuff (so it works in the nix sandbox), so it's possible it will run on osx without any further changes. I don't have an osx machine to test on :(

**Comment by Gaelan** [comment]
I have a macOS machine I'm happy to test stuff on if it'd b helpful for oyu.

> Oh hey, just catching up here, I'm a little confused - the stuff where apple has added support for something is all about osx guests, not osx hosts which is what we care about here right?

Not quite sure what you're referring to, but here's a quick run-down of Apple's recent-ish features for macOS hosts:

* `Hypervisor.framework`: 3-5 years old. Provides low-level userspace access to the CPU's virtualization features. I think QEMU has a backend for this, called HVF.
* `Virtualization.framework`: New with Big Sur, this year's release. Much higher-level - you give it a kernel, initrd, and disk, and it goes from there. Pretty limited - only emulates a few devices (the virtio devices for disk, network, serial, RNG and memory balloons), and only supports raw images (though APFS's sparse files negate the need for qcow2 a bit). [vftool](https://github.com/evansm7/vftool) provides a thing command-line wrapper over this.

(As a side note, I've been experimenting with using Virtualization.framework to implement a simple Linux VM, using a tiny linux kernel with [u-root](https://github.com/u-root/u-root) as a simple "bootloader" to find and exec the real kernel image off a Linux filesystem; I've got it working with Ubuntu, but not NixOS; I suspect there's some issue with virtio-console support on the install ISO.)

**Comment by JJJollyjim** [comment]
@Gaelan I was referring to Domen's Passthru Post link about virtio :)

**Comment by Gaelan** [comment]
Ah, my bad.

**Comment by mroi** [comment]
I ported [the original 9p patchset](https://patchew.org/QEMU/cover.1529196703.git.keno@juliacomputing.com/) (mentioned earlier in this thread) to QEMU 5.2.0. In initial tests, 9p support on Darwin appears to be working.

But this is a large change that should probably go to upstream and not to Nixpkgs. If you want to try anyways: https://github.com/mroi/nixpkgs/commit/839559b486d4c4dbd911a0f13a3b2d319b942cd5

**Comment by anthr76** [comment]
@mroi Would be help to at least submit the patch to Homebrew. Thanks for the work! I'll look on giving it a try.

**Comment by SCOTT-HAMILTON** [comment]
I would really love the test driver to run on MacOS with HAXM enabled. (-enable-hax)

I tried to merge both patches from @mroi and @Infinisil and ran the same command as above : 
```shell_session
$ nix-build '<nixpkgs/nixos>' \
            --argstr system x86_64-linux \
            --arg configuration '{ virtualisation.qemu.pkgs = import <nixpkgs> { system = "x86_64-darwin"; };
}' \
            -A vm \
            -I nixpkgs=http://github.com/SCOTT-HAMILTON/NixPkgs/archive/230f823cd985e499ff2fd450b419bc5b44c6db
f8.tar.gz
```

But I get this error : 
error: a 'x86_64-linux' with features {} is required to build '/nix/store/qbr4wjfz9lzrqha4gl6mjp2l0imwqdgh-append-initrd-secrets.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}

**Comment by domenkozar** [comment]
For testing patches you'll need a remote builder to build the Linux bits. The quickest way is to follow https://nix.dev/tutorials/continuous-integration-github-actions.html and get them from your binary cache.

**Comment by domenkozar** [comment]
Steps left:

- make a PR for https://github.com/Infinisil/nixpkgs/commit/4d244410ee0f3e3ece5494533217bbafbd95d9b3
- make a PR for https://github.com/mroi/nixpkgs/commit/839559b486d4c4dbd911a0f13a3b2d319b942cd5
- build on linux & test on macOS

**Comment by mroi** [comment]
> make a PR for mroi@839559b

You mean as a PR toward Nixpkgs or toward upstream QEMU? I can easily do the former. For the latter I would need to familiarise myself with their e-mail-based workflow. (Anyone here with experience in that?)

**Comment by domenkozar** [comment]
Former, although upstream patch would be really nice.

**Comment by anthr76** [comment]
> > make a PR for [mroi/nixpkgs@839559b](https://github.com/mroi/nixpkgs/commit/839559b)
> 
> You mean as a PR toward Nixpkgs or toward upstream QEMU? I can easily do the former. For the latter I would need to familiarise myself with their e-mail-based workflow. (Anyone here with experience in that?)

The linux kernel has a bot explaining their email workflow which you might find similar with QEMU

https://github.com/torvalds/linux/pull/803#issuecomment-592644193

**Comment by mroi** [comment]
I updated the 9p patches for current QEMU 6.0: #122420

I’ll look into proposing this to upstream. (Thanks @anthr76 for the link.)

**Comment by domenkozar** [comment]
@r2r-dev did you manage to get it working?

**Comment by r2r-dev** [comment]
Yup. I've prepared 2 test branches:
1. Based mostly on stuff mentioned in this issue, as well as my fix for virtfs.
 - https://github.com/r2r-dev/nixpkgs/commits/qemu-darwin-fixes
 can be tested via:
- https://github.com/r2r-dev/nixos-shell/commit/95b586bd5aef938a64ce2a9e9b61c99c9da936a2

2. With additional patches for M1, and vmnet device adapter:
- https://github.com/r2r-dev/nixpkgs/commits/wip-qemu-darwin-fixes 
can be tested via:
- https://github.com/r2r-dev/nixos-shell/commit/1f53a820f1570f9e75263e6a69103465e0cf2c46

Obviously, both of these branches aren't pretty and surely will need some cleanup.

Some remarks:
- Qemu's v9fs requires additional patching (see 1st branch). Without it, any `getdents` or `getdents64` syscalls on shared filesystem will result in a deadlock.
- overlayfs won't work on top of v9fs mounts. It seems that v9fs cannot handle xattrs querying. This can be fixed by mounting lower-dir with `-o version=9p2000.u`. However, even though I've managed to boot into VM, it was quite unstable. In order to mitigate that I've used squashfs-based /nix/store instead of one mounted from host.

**Comment by pl-misuw** [comment]
@r2r-dev This is far beyond cool, works well for my 2018 15' MBP! Kudos.

**Comment by domenkozar** [comment]
This is superb.

**Comment by hexagonal-sun** [comment]
@r2r-dev Hi, I'm giving this a try on a M1 machine and I'm getting the error:

```
# ./result/bin/nixos-shell examples/darwin.nix -- -- --argstr system aarch64-linux -I nixpkgs=http://github.com/r2r-dev/nixpkgs/archive/f68911645209742013dd6abe570a23548d9a5780.tar.gz --option builders-use-substitutes true

[...]

error: a 'x86_64-darwin' with features {} is required to build '/nix/store/zq54yx4gydijq5hryk60qs660pw84s5h-MacOSX-SDK-11.0.0.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test, recursive-nix}
```

If I change `virtualisation.qemu.pkgs.system = "aarch64-darwin"` I now get:

```
error: anonymous function at /nix/store/5s210gnpc6f7nn2jhnaakq8zm47p2dlz-source/pkgs/build-support/bintools-wrapper/default.nix:8:1 called without required argument 'lib'

       at /nix/store/5s210gnpc6f7nn2jhnaakq8zm47p2dlz-source/pkgs/stdenv/native/default.nix:133:18:

          132|       inherit lib nativePrefix;
          133|       bintools = import ../../build-support/bintools-wrapper {
             |                  ^
          134|         name = "bintools";
(use '--show-trace' to show detailed location information)
```

Any ideas on how to get this working on `aarch64-darwin`?  Thanks!

**Comment by willcohen** [comment]
See https://github.com/NixOS/nixpkgs/pull/162243 for an updated PR with the upcoming QEMU functionality backported to v6.2.0.

**Comment by willcohen** [comment]
Looking back over this thread, what remains for nixpkgs? At this point, is it only the `qemu-vm.nix` stuff?

**Comment by alyssais** [comment]
I've just merged #162243.  Is there anything else to be done here, or can this be closed now?

**Comment by Artturin** [comment]
Perhaps a test that can, for example, be run on ofborg should be created?

**Comment by YorikSar** [comment]
I'm trying to run NixOS VM on my macOS machine with M1. What's missing so far:
* virtfs still doesn't work (see below)
* we need to backport [commit](https://github.com/infinisil/nixpkgs/commit/4d244410ee0f3e3ece5494533217bbafbd95d9b3) by @Infinisil that allows to build VM script for macOS (it applies quite cleanly)
* still missing ability to detect whether to use `kvm` or `hvf` in `nixos/lib/qemu-common.nix`

Here's what I'm trying to build:
`flake.nix`:
```

**Comment by YorikSar** [comment]
I'm trying to run NixOS VM on my macOS machine with M1. What's missing so far:
1. either QEMU 6.2 or virtfs doesn't work (see below)
2. we need to backport [commit](https://github.com/infinisil/nixpkgs/commit/4d244410ee0f3e3ece5494533217bbafbd95d9b3) by @Infinisil that allows to build VM script for macOS (it applies quite cleanly)
3. still missing ability to detect whether to use `kvm` or `hvf` in `nixos/lib/qemu-common.nix`

Here's what I'm trying to build:
`flake.nix`:
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }: {
    nixosConfigurations = {
      qemu = nixpkgs-aarch.lib.nixosSystem {
        system = "aarch64-linux";
        modules = [
          (import ./qemu.nix { inherit nixpkgs; })
        ];
      };
    };
  };
}
```

`qemu.nix`:
```
{ nixpkgs }:
{ config, pkgs, lib, modulesPath, ... }:

{
  imports = [
    "${modulesPath}/virtualisation/qemu-vm.nix"
  ];

  system.stateVersion = "21.11";

  networking.useDHCP = false;
  networking.interfaces.eth0.useDHCP = true;

  services.getty.autologinUser = "test";
  users.users.test = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    hashedPassword = "$5$ZjxV1oXdKi61yoVw$iBoQwq3URyEeN56FZWEouw4G1UJM0eGQMLm54hmvd/8"; # "test"
  };
  security.sudo.wheelNeedsPassword = false;

  virtualisation = {
    qemu.pkgs = nixpkgs.legacyPackages.aarch64-darwin;
    # These two disable 9p/virtfs entirely
    useNixStoreImage = true;
    sharedDirectories = lib.mkForce { };
    graphics = false;
  };
}
```
I build it like this:
* point `nixpkgs` input at a repo with cherry-picked `qemu.pkgs` [commit](https://github.com/infinisil/nixpkgs/commit/4d244410ee0f3e3ece5494533217bbafbd95d9b3)
* `nix build .#nixosConfigurations.qemu.config.system.build.vm`
* copy `result/bin/run-nixos-vm` and replace `-enable-kvm -machine virt,gic-version=host -cpu host` in qemu arguments with `-machine virt,accel=hvf,highmem=off -cpu cortex-a72`

I was trying this with previous version of `nixpkgs` with the `qemu.pkgs` patch, and it worked fine, I got autologin on console. After I've rebased that commit on top of latest `nixpkgs` master, I don't get any output on both text and graphical consoles, both with `useNixStoreImage` and `sharedDirectories` lines and without them.

I'll post both rebased `qemu.pkgs` commit and my example somewhere a bit later, and will keep trying.

**Comment by ElvishJerricco** [comment]
@YorikSar Looks like qemu 7.0 enables 9pfs for macOS: https://wiki.qemu.org/ChangeLog/7.0#9pfs

That should fix the virtfs stuff, right?

**Comment by willcohen** [comment]
@ElvishJerricco the feature you’re noting for 7.0 is what was backported to 6.2 via #162243!

**Comment by zupo** [comment]
@YorikSar: I have an Intel-based MacBook 13" that is just sitting on my desk. I'd love to help testing this! I'm a bit of a noob so need some handholding though. Alternatively, I can give you SSH access?

**Comment by willcohen** [comment]
`nix run` on an intel mac with this flake fails with:

`error: a 'x86_64-linux' with features {} is required to build '/nix/store/89zr2gg8dd8mw8x5nq33fyy65imsc2qv-append-initrd-secrets.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test}`.


It earlier also failed with the same error but for `stdenv-linux`, but rerunning `nix run` a few times settled on `initrd-secrets`.

**Comment by willcohen** [comment]
Of course, duh. I unfortunately don't have a linux builder set up! If no one else is able to find one I can get one set up but it probably won't be until next week...

**Comment by YorikSar** [comment]
I've tested it on Intel, it seems like I've messed up QEMU arguments and also there's some problem with HVF there. I wonder if old macOS SDK on Intel is to blame. I will keep figuring this out.

By the way, one of the outcomes of this project that I see would be some way to have a local Linux builder on the Mac without any hassle. Something like a VM that is automatically spun up when the builder is needed.

**Comment by YorikSar** [comment]
`type=q35` instead of `virt` did the trick! Now it booted into the system, just like on M1 :)
I'll check out what does q35 actually mean later. For now I've updated the commit and uploading (x86 virtualised build is painfully slow) my build artefacts to Cachix. You should be able to run `nix run nixpkgs#cachix -- use yoriksar-gh` to pull them during `nix build`.

**Comment by ElvishJerricco** [comment]
@YorikSar Tried to give it a go. Got a hash mismatch on the 9p patchfile:

```
error: hash mismatch in fixed-output derivation '/nix/store/5l7yvn3kgsinggwpn6bb40wxxbvb7d0g-f5643914a9e8f79c606a76e6a9d7ea82a3fc3e65.patch.drv':
         specified: sha256-VBcvy+t6UAQeUe4hqytBJIORKoe9auAmiVur9ZLUIhs=
            got:    sha256-8i13wU135h+YxoXFtkXweBN3hMslpWoNoeQ7Ydmn3V4=
```

**Comment by YorikSar** [comment]
@ElvishJerricco I've fixed the hash and rebased the branch on the current master. Please check again, don't forget to update flake inputs.

**Comment by khaled** [comment]
> By the way, one of the outcomes of this project that I see would be some way to have a local Linux builder on the Mac without any hassle. Something like a VM that is automatically spun up when the builder is needed.

@YorikSar Do you have an outline of how this could work?  Today it seems like you need a remote Linux builder to build the builder image itself, unless it has already been built and cached somewhere...

**Comment by roberth** [comment]
> unless it has already been built and cached somewhere...

That would be `hydra.nixos.org`. If we add a system configuration to the relevant channels, as channel blockers, we can pretty much guarantee an "image" to be available.
Scare quotes because we could use 9p for the system store, just like we do in the tests. The work of configuring the VM is best done through a `nix-darwin` module. Or perhaps two modules. One for bootstrapping a lightweight builder, and a second one for configuring a VM with arbitrary configuration, that can also serve as a linux builder.

**Comment by YorikSar** [comment]
Updates:

* I've rebased the branch on the latest nixpkgs master, applied fixes for #178954
* Rebuilt the example from https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-1150149700 and pushed all rebuilt packages to Cachix
* Created pull request for qemu 9p patch: #180221
* Created pull request for NixOS modules changes: #180222

Next steps:

* Get those pull requests merged
* Add a test to Hydra that would run this basic configuration on Darwin platforms for unstable.

**Comment by ElvishJerricco** [comment]
@YorikSar I have to disable the Nix sandbox, otherwise I get errors trying to build `python3.10-requests-2.28.0.drv` on darwin. Something about sockets in the test suite. Other than that, it appears to work!

**Comment by YorikSar** [comment]
@ElvishJerricco That's great! Do you get the same errors if you rebuild `python310Packages.requests` from master with sandbox? If so, maybe file an issue (or even a PR) about that?

**Comment by peterwaller-arm** [comment]
> @willcohen Oh, yeah, to build this you need to have a Linux builder configured for your Nix daemon. 

Ah, that's unfortunate -- please could you edit [your comment](https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-1150149700) "So far on my M1 MacBook Pro this flake:" to indicate this requirement, since I've hit this and did not understand the subsequent comments until I had the problem.

Requiring a Linux builder to be configured to allow building the Linux VM from Darwin scuppers my plans to use this. What are new users meant to do if you don't have a Linux builder available? I was hoping to have a configuration I could share with anyone, instruct someone to install NixOS, and all they'd have to do was build a flake and they'd get a VM. But it seems this isn't possible yet, is that right?

**Comment by esselius** [comment]
> @YorikSar I have to disable the Nix sandbox, otherwise I get errors trying to build `python3.10-requests-2.28.0.drv` on darwin. Something about sockets in the test suite. Other than that, it appears to work!

Works with sandbox turned off for me too!

**Comment by YorikSar** [comment]
I've created a repository with instructions on how to use results of merged PRs: https://github.com/YorikSar/nixos-vm-on-macos - feel free to check that out and see if it works for you.

**Comment by Gabriella439** [comment]
@peterwaller-arm: Correct me if I'm wrong, but I believe if cache.nixos.org can serve enough Linux build products to deploy a blank NixOS VM then you can bootstrap things on a Darwin system without a remote Linux builder by:

- Deploying a blank NixOS VM for use as a local Linux builder
- Use that to then build other NixOS systems

**Comment by Gabriella439** [comment]
I had to add `highmem=off` to the QEMU run script to get this to work on my M1 MacBook Pro due to https://github.com/utmapp/UTM/issues/3946.  Without that fix this causes a kernel protection failure.

Specifically, I made the following change:

```diff
@@ -29,7 +29,7 @@
 
 
 # Start QEMU.
-exec /nix/store/h5yrqjziml4vwqq7azph6y9r2r267aq6-qemu-host-cpu-only-7.0.0/bin/qemu-system-aarch64 -machine virt,gic-version=2,accel=hvf:tcg -cpu max \
+exec /nix/store/h5yrqjziml4vwqq7azph6y9r2r267aq6-qemu-host-cpu-only-7.0.0/bin/qemu-system-aarch64 -machine virt,gic-version=2,accel=hvf:tcg,highmem=off -cpu max \
     -name nixos \
     -m 1024 \
     -smp 1 \
```

I'll try to put up a PR to fix this.

**Comment by Gabriella439** [comment]
Actually, after investigating this further it looks like the real issue was due to me being on an old version of macOS (12.0.1) and setting `highmem=off` is an undesirable solution (because it limits you to a smaller address space).  Upgrading macOS to 12.4 or newer should fix the kernel protection failure.

**Comment by Gabriella439** [comment]
The main issue I see is that networking does not appear to work within the guest VM when I tested the instructions from https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-1234408582 (and several variations, including the default networking options)

For example, these commands both fail when run from inside the VM:

```
$ host google.com
;; communications error to 10.0.2.3#53: timed out
;; communications error to 10.0.2.3#53: timed out
;; communications error to fec0::3#53: timed out
;; no servers could be reached

$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=0 ttl=255 time=1886095099620737 ms
wrong data byte #16 should be 0x10 but was 0x0
#16	0 1 0 1 98 43 26 63 0 0 0 0 34 2b 1 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48	1c 1d 1e 1f 20 21 22 23 
64 bytes from 8.8.8.8: icmp_seq=0 ttl=255 time=2630877887998121 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16	0 1 0 2 99 43 26 63 0 0 0 0 89 34 1 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48	1c 1d 1e 1f 20 21 22 23 
64 bytes from 8.8.8.8: icmp_seq=0 ttl=255 time=3259692985970728 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16	0 1 0 3 9a 43 26 63 0 0 0 0 42 3c 1 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48	1c 1d 1e 1f 20 21 22 23 
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 1 received, +2 duplicates, 66.6667% packet loss, time 2004ms
rtt min/avg/max/mdev = 1886095099620736.537/2592221991196528.640/3259692985970727.795/-6642957192704464.-896 ms, pipe 4
```

**Comment by Gabriella439** [comment]
It looks like there is another issue for `qemu` VMs on macOS: the default DNS server (`10.0.2.3`) created by `qemu` as part of user-mode networking (SLiRP) does not work.  See:

https://github.com/utmapp/UTM/issues/2353

You have to override it with the IP address of a working DNS server (e.g. `networking.nameServers = [ "8.8.8.8" ];`) in order for DNS to work on the guest VM.

**Comment by Gabriella439** [comment]
Alright, I managed to get the idea I proposed in https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-1250066968 working.  Specifically, I created a repository that lets you bootstrap a Linux guest of the same architecture on a macOS host, relying on a pre-seeded cache instead of a separate Linux builder (similar to https://github.com/NixOS/nixpkgs/issues/108984#issuecomment-1234408582):

https://github.com/Gabriella439/macos-builder

You can then use that Linux guest to build and run additional NixOS VMs on macOS.

As far as I can tell, the only remaining improvements I can think of are:

- cache.nixos.org should probably host those cached build products instead of using my own cache so that there's a better chain of trust

- Maybe we should wait until https://github.com/utmapp/UTM/issues/2353 is closed before marking this done?

  I'm not sure if this should be a blocker, though, because the work-around (hard-coding a public DNS server) is pretty easy

Other than that, I don't see any work remaining here.

**Comment by roberth** [comment]
> * cache.nixos.org should probably host those cached build products instead of using my own cache so that there's a better chain of trust

We should add the default config `toplevel` to the `nixpkgs-darwin` jobsets, so that we can guarantee its availability in the cache.

Perhaps the keys could be loaded through a 9p mount instead of baking them into the config?

Maybe enable automatic gc? That will save some annoyance and confusion. Relevant paths will be gc-rooted on the host anyway, and copying between the host and vm should be fairly quick.

Having this in a nix-darwin module would be awesome.

**Comment by virusdave** [comment]
> Having this in a nix-darwin module would be awesome.

+100 to this idea!

**Comment by anka-213** [comment]
How does this compare to https://github.com/nix-community/linuxkit-nix, which also seems to provide a virtual machine that can be used as a remote linux builder for a macOS machine?

**Comment by auscompgeek** [comment]
@anka-213 that is orthogonal to this issue which aims to allow building interactive VMs (per the first sentence of the description). Looks like it could be used to bootstrap a NixOS VM build though.

**Comment by SCOTT-HAMILTON** [comment]
So is it now possible to run github actions nixos vm tests on macos runners to speed up the CIs ?

**Comment by YorikSar** [comment]
Unfortunately, not yet. Current state is that you can build a VM from NixOS configuration that will run on macOS.
This PR by @roberth provides a way to run NixOS tests on non-Linux: https://github.com/NixOS/nixpkgs/pull/193336, and it worked for me on macOS, but it is still a draft.

**Comment by Gabriella439** [comment]
@roberth: Alright, I added automatic GC and also removed the hardcoded keys like you suggested.  The next step is that I'll work on upstreaming this into Nixpkgs so that it can be built and cached as a `nixpkgs-darwin` jobset

**Comment by schickling** [comment]
@Gabriella439 @domenkozar very excited to see this being pushed over the finish line!

Wondering whether there is any tutorial, blog post or similar that explains this further?

**Comment by infinisil** [comment]
@schickling The PR added a Nixpkgs manual section: https://nixos.org/manual/nixpkgs/unstable/#sec-darwin-builder

**Comment by Gabriella439** [comment]
@schickling: I'm also going to announce this via a blog post, but that will focus more on the background work and motivation for this

**Comment by misuzu** [comment]
```bash
% nix run nixpkgs#darwin.builder
error: a 'aarch64-linux' with features {} is required to build '/nix/store/6i2m765ifgzihprpzix5f5ghghpi2sk3-install-credentials.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
Am I doing something wrong?

**Comment by Gabriella439** [comment]
I think the issue is that it's not being built by hydra.nixos.org because it's missing a platforms attribute.  I'm looking into this

**Comment by Gabriella439** [comment]
This should hopefully fix it: https://github.com/NixOS/nixpkgs/pull/207459

**Comment by misuzu** [comment]
It's still not working 😔
```bash
% nix run github:NixOS/nixpkgs/nixpkgs-unstable#darwin.builder
error: a 'aarch64-linux' with features {} is required to build '/nix/store/6i2m765ifgzihprpzix5f5ghghpi2sk3-install-credentials.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
% nix build --dry-run github:NixOS/nixpkgs/nixpkgs-unstable#darwin.builder
these 2 derivations will be built:
  /nix/store/6i2m765ifgzihprpzix5f5ghghpi2sk3-install-credentials.drv
  /nix/store/yl0r0qgdrx50ymbrwi66wpxf4krwkrxy-create-builder.drv
these 223 paths will be fetched (220.65 MiB download, 983.89 MiB unpacked):
<..................>
```

**Comment by Gabriella439** [comment]
Yeah, this should hopefully be the last fix: https://github.com/NixOS/nixpkgs/pull/207577

**Comment by bergkvist** [comment]
This was working for me, but started failing just now:
```sh
% nix run github:NixOS/nixpkgs/nixpkgs-unstable#darwin.builder
cannot build on 'ssh-ng://builder@localhost': error: cannot open connection to remote store 'ssh-ng://builder@localhost': error: unexpected end-of-file
Failed to find a machine for remote build!
derivation: g43xrrmfr80sza9fshg99l1yc80ny1il-nixos-disk-image.drv
required (system, features): (aarch64-linux, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(aarch64-linux, 10, , )
error: a 'aarch64-linux' with features {} is required to build '/nix/store/g43xrrmfr80sza9fshg99l1yc80ny1il-nixos-disk-image.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
```
% nix build --dry-run github:NixOS/nixpkgs/nixpkgs-unstable#darwin.builder
these 4 derivations will be built:
  /nix/store/g43xrrmfr80sza9fshg99l1yc80ny1il-nixos-disk-image.drv
  /nix/store/1lhnpvb9n70gz7sf3yapwybl476cd9rd-run-nixos-vm.drv
  /nix/store/hzy3zqwb795fai8zla07hf8c04gb1cvj-nixos-vm.drv
  /nix/store/vcps33v4bra88pv8h00v41mqs3vka3sd-create-builder.drv
```
```
% nix flake metadata github:NixOS/nixpkgs/nixpkgs-unstable
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/2d38b664b4400335086a713a0036aafaa002c003
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/ld350gbq2w5654yw4q95kxhxp4569zi6-source
Revision:      2d38b664b4400335086a713a0036aafaa002c003
Last modified: 2023-01-17 10:21:52
```

Trying a slightly older commit, and it works again:
```
% nix run github:NixOS/nixpkgs/6fecd5a257327db6116b28acdfb45561e65e3dfa#darwin.builder
Formatting '/Users/tobias/nixos.qcow2', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=21474836480 lazy_refcounts=off refcount_bits=16
Formatting '/tmp/nix-vm.qudT2qcgrQ/store.img', fmt=qcow2 cluster_size=65536 extended_l2=off compression_type=zlib size=1198522368 backing_file=/nix/store/9rk814dr9dr1cxz698iq22g3c5713hfy-nixos-disk-image/nixos.qcow2 backing_fmt=qcow2 lazy_refcounts=off refcount_bits=16
...
<<< Welcome to NixOS 23.05pre-git (aarch64) - ttyAMA0 >>>

Run 'nixos-help' for the NixOS manual.

nixos login: builder (automatic login)


[builder@nixos:~]$
```

**Comment by peterwaller-arm** [comment]
@bergkvist (I'm an interested user, non-authoritative comment) One tricky thing to consider is whether the packages are in the cache yet for the commit you're building. If not, your machine would try to build it and fail.

I think the `nixos/nixpkgs/nixpkgs-unstable` branch might run ahead of the cache being populated. Try `nixos/nixpkgs/nixos-unstable` instead, which I think is updated as the cache is updated if I understand correctly.

**Comment by bergkvist** [comment]
When I try to build `github:NixOS/nixpkgs/594b94b4c3038f5c2cfb2f5d9c10ef30c7070a4c#darwin.builder` inside of my builder (`nix run github:NixOS/nixpkgs/af89d3a2be6f70edb187dd817377d6c4360134fa#darwin.builder`)
```sh
% nix build github:NixOS/nixpkgs/594b94b4c3038f5c2cfb2f5d9c10ef30c7070a4c#darwin.builder
error: build of '/nix/store/rnwbjdkq9wz43nlsmggr7ysn7k9h9z2w-nixos-disk-image.drv' on 'ssh-ng://builder@localhost' failed: builder for '/nix/store/rnwbjdkq9wz43nlsmggr7ysn7k9h9z2w-nixos-disk-image.drv' failed with exit code 32;
       last 10 log lines:
       > copying path '/nix/store/65cvxfd36l9cawzj1gkx3zpzj0bdfg0b-unit-serial-getty-.service' to 'local'...
       > copying path '/nix/store/8izgxj2nzpwkd0hpm3r38zkiklm1jkzr-unit-nixos-activation.service' to 'local'...
       > copying path '/nix/store/82nc5jrzri2w4hw6rhffis9m6n25xnbv-unit-systemd-fsck-.service' to 'local'...
       > copying path '/nix/store/r9h4h2j299iz32gnnr2qksz2hsi6i8cw-unit-systemd-udevd.service' to 'local'...
       > copying path '/nix/store/klkbaapdbcs35bxyp0l97ic3lpp0njnb-user-units' to 'local'...
       > copying path '/nix/store/c04f008fdyqmarjl6nf35fdrzfm9h6lk-system-units' to 'local'...
       > copying path '/nix/store/786ah3bs0n5lcvjq2qhp4laiqkg60wr0-etc' to 'local'...
       > copying path '/nix/store/mj26i1zj0bjv1b732bafrg2ffly34adj-nixos-system-nixos-23.05pre-git' to 'local'...
       > mount: /build/root/build/root: must be superuser to use mount.
       >        dmesg(1) may have more information after failed mount system call.
       For full logs, run 'nix log /nix/store/rnwbjdkq9wz43nlsmggr7ysn7k9h9z2w-nixos-disk-image.drv'.
error: builder for '/nix/store/rnwbjdkq9wz43nlsmggr7ysn7k9h9z2w-nixos-disk-image.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/wr12pkszc3gj021fy08cch9syhqvwyj2-run-nixos-vm.drv' failed to build
error: 1 dependencies of derivation '/nix/store/p5pa1imyb5yc6l3wy1cda5bz38dc430f-nixos-vm.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ld4rlr7sf599qi53bmd4d2xrjsm53n11-create-builder.drv' failed to build
```

https://github.com/NixOS/nixpkgs/pull/210812 also seems to have broken other builds - which triggered this emergency fix: https://github.com/NixOS/nixpkgs/pull/211218. Doesn't seem to have made it to the unstable branch yet though.

**Comment by dhess** [comment]
Is it possible to add NixOS modules to the `darwin.builder`'s `config`? If so, it's not clear how.

I ask because I'd like to run this on our `aarch64-darwin` CI machines, but enable the NixOS Tailscale module to make each `aarch64-darwin`'s `darwin.builder` available to our Hydra as a remote `aarch64-linux` builder, as well. (I believe this would also get around any host port 22 and/or macOS firewall issues.)

**Comment by Gabriella439** [comment]
@dhess: Yes.  If you copy the code from here:

https://github.com/NixOS/nixpkgs/blob/0cf78f562607f75256703af568814d3a62ded6de/pkgs/top-level/darwin-packages.nix#L215-L233

… then you can add in additional modules of your own

**Comment by bergkvist** [comment]
### In case you need more than 3GB of memory for your builder
```sh
# Starts darwin.builder VM with 8GB RAM
QEMU_OPTS="-m 8192" nix run github:NixOS/nixpkgs#darwin.builder
```

**Comment by misuzu** [comment]
Does qemu support passing rosetta binary to guest system? Would be awesome to enable https://github.com/NixOS/nixpkgs/pull/202847 to support building for x86_64-linux too.

**Comment by YorikSar** [comment]
@misuzu Rosetta "drive" is mounted via higher-level Virtualisation.framework while QEMU uses lower-level Hypervisor.framework. The later is more like kvm while the former is more like QEMU itself, so I doubt its support will happen in QEMU. I think, #5241 is relevant to bringing virtualisation backends other than QEMU for running NixOS VMs.

**Comment by roberth** [comment]
[UTM](https://github.com/utmapp/UTM) does support it, is supposedly based on QEMU, is packaged, and we have a NixOS module to support it on its guests https://github.com/NixOS/nixpkgs/pull/202847. If it has a qemu compatible command line it might be close to a drop-in replacement.

> #5241

If it's like qemu, you can set [`qemu.package`](https://nixos.org/manual/nixos/stable/index.html#test-opt-qemu.package) at the test level if you use the [documented entrypoint](https://nixos.org/manual/nixos/stable/index.html#sec-calling-nixos-tests).

**Comment by YorikSar** [comment]
@roberth UTM docs clearly state https://docs.getutm.app/advanced/rosetta/:

> Rosetta allows you to run Intel Linux executables in an Apple Silicon Linux virtual machine (using Apple Virtualization backend).

QEMU VMs don't have this setting in UTM.

**Comment by ElvishJerricco** [comment]
@roberth IIUC, UTM only supports rosetta if you tell it to use Apple Virtualisation instead of QEMU.

**Comment by willcohen** [comment]
I love QEMU, but this is awesome. I still don't quiiite have copy/paste working this way (not sure if spice + wayland is a thing), but using Apple Virtualization solves the other major pain point of having normal-ish resolutions relative to my laptop and external monitor working with wayland/sway on a graphical NixOS VM. I feel like there should be a flashing exclamation point somewhere that this works so well.

**Comment by roberth** [comment]
> supposedly based on

This was outdated information then. Thanks for correcting me.

I was thinking about the VM tests in my last comment. It'd be far easier to add Apple Virtualisation support if it's just for the `darwin.builder`, as it that's a simple entrypoint. I guess you'd have to figure out
 - how to invoke Apple Virtualization from the command line. Some apple command? UTM? Custom program?
 - create a new module with a new option that holds the Apple Virtualization invocation
   - figure out which NixOS options hold the image and kernel
 - change the `darwin.builder` package to get that option instead of the qemu one

**Comment by misuzu** [comment]
> how to invoke Apple Virtualization from the command line. Some apple command? UTM? Custom program?

Maybe this could be adapted to our use-case:
https://github.com/Code-Hex/vz/tree/main/example/linux
https://github.com/lima-vm/lima/pull/1155

**Comment by ElvishJerricco** [comment]
I do wish the kernel had support for enabling TSO mode per process. I don't even know if that's possible in a VM, but it'd be very nice for asahi linux to be able to use the rosetta binary via hacks and with TSO enabled.

**Comment by YorikSar** [comment]
There's a vmcli project: https://github.com/gyf304/vmcli#vmcli-1 - it allows to run VMs with Virtualisation.framework from CLI. We could use it to start VM and add Rosetta support to it.

**Comment by fkorotkov** [comment]
There is also [Tart](https://github.com/cirruslabs/tart) that has Rosetta support. One just need to:

```shell
brew install cirruslabs/cli/tart
tart clone ghcr.io/cirruslabs/ubuntu:20.04 ubuntu
tart run --rosetta="rosetta" ubuntu
``` 

And make sure Rosetta is configured inside the VM according to [these docs](https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta#3978496).

**Comment by dhess** [comment]
I've gotten pretty far with Tart. Thanks to @fkorotkov for making me aware of it in the above comment!

1. Create a new, empty `Virtualization.Framework` VM named `nixos` with `tart create nixos --linux`
2. Build an `aarch64-linux` NixOS configuration as a `raw-efi` image using https://github.com/nix-community/nixos-generators. For bonus points, set `virtualisation.rosetta.enable = true` and `nix.settings.extra-platforms = [ "x86_64-linux" ]` in the VM's config, so that the VM will be able to run `x86_64` Linux binaries, as well.
3. Overwrite the Tart VM's `disk.img` with the `nixos.img` file from step 2.
4. Run the VM with `tart run nixos --rosetta rosetta`

I've spent most of my time on this so far just learning how `Virtualization.Framework` works, and not much time experimenting with the running VM, but everything I've tried so far works great, including building and running `x86_64-linux` derivations. Additionally, I think it would be straightforward to automate steps 1-3 in a Nix derivation.

Even better would be to use the Mac's `/nix/store` in the VM. To experiment with this, I did the following:

1. Run the VM with `tart run nixos --rosetta rosetta --dir="store:/nix/store"`
2. In the running VM, run `mount -t virtiofs com.apple.virtio-fs.automount /mnt`. This mounts the Mac's `/nix/store` on `/mnt/store` in the running VM. I can see all the files there, though performance is a bit slow. Maybe mounting it with some `cache=` options would help.
3. Bind mount the `virtiofs`-mounted Mac Nix store to the VM's `/nix/store` via `mount --bind /mnt/store /nix/store`. (I think this extra step is necessary due to the way that `Virtualization.Framework` makes all shared filesystems available under a single mount point, but I might be missing something.) Confirm that everything still works: running commands still works, etc. 

So far, so good. However, my particular use case for this VM is to use it as an `aarch64-linux` remote builder, so I want to be able to build derivations in it, while re-using the Mac's own `/nix/store` for disk and network savings. Now I try to build something that's not in the store: `nix run nixpkgs#hello`. This fails with `error: cannot open connection to remote store 'daemon': error: reading from file: Connection reset by peer`

Looking at the logs, the problem is apparent: `unexpected Nix daemon error: error: changing ownership of path '/nix/store': Operation not permitted`

This makes sense: Nix is running in multi-user mode on my Mac, so my Mac's `/nix/store` is owned by root and managed by the local `nix-daemon` running as root. I'm running `tart` as my local macOS user, not root, so `tart` doesn't have permissions to change ownership on the Mac's `/nix/store`.

Anyway, besides that small catch, this route looks very promising. I think the main issue for our use case is that `Virtualization.Framework` doesn't support nested virtualization, so we won't be able to use this virtualized remote `aarch64-linux` builder to run NixOS tests.

**Comment by Gabriella439** [comment]
@dhess: You probably don't want to share the host's `/nix/store` with the builder anyway, for the reason outlined in this comment:

https://github.com/NixOS/nixpkgs/blob/99563190d585896d7ddb43ea448a95574dfa2373/nixos/modules/profiles/macos-builder.nix#L159-L168

**Comment by dhess** [comment]
@Gabriella439 Thanks, I did see that comment linked from elsewhere, either in this discussion, or in a related one.

However, if I understand the comment correctly, I don't think it applies in our use case. We have several dedicated macOS remote builders (let's call them `mac1`, `mac2`, etc.), which appear in our `x86_64-linux` NixOS dedicated builder's `/etc/nix/machines` file; let's call that machine `nixos1`. `mac1` etc. are not for interactive use: they only build derivations that are delegated by `nixos1`.

`nixos1` cannot build `aarch64-linux` derivations, but virtualized `aarch64-linux` NixOS VMs running on `mac1` etc. could. So what we'd like to do is have `mac1` etc. run these `aarch64-linux` VMs (let's call them `arm1` etc.), list those VMs in `nixos1`'s `/etc/nix/machines` file, and then have `nixos1` delegate `aarch64-linux` jobs to those VMs. Therefore, unless I'm missing something, the comment does not apply in our case, because the host is not delegating any jobs to the guest, only `nixos1` is.

Perhaps it's possible that `nixos1` could ask `arm1` to build platform-independent derivation `foo` at the same time as it's asking `mac1` to build it? But even in this case, I assume that whichever remote builder wins the race will go first while the other waits for the lock, then proceeds (and presumably sees that the derivation has magically appeared in the store in the meantime). In any case, I wouldn't expect a deadlock to occur in this scenario.

**Comment by protosam** [comment]
Over in this podman issue, I see that virtiofs in MacOS doesn't bypass open file limits, which leads to unexpected behavoir in the guest OS: https://github.com/containers/podman/issues/16106

I'm addressing the issue directly in podman, but I was hoping someone from this issue might have an opinion on if qemu should be bumping it's own ulimits up when it is acting as the virtiofs daemon?

**Comment by Gabriella439** [comment]
You can now run NixOS tests on macOS, too.  See: https://github.com/NixOS/nixpkgs/pull/282401/

Note that you still need a Linux builder to build the test VM, though
