### ISSUE TITLE
Raspberry Pi 4 SD card image broken on master

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#111683]
**Describe the bug**
The build of the RPI4 image has been broken for a few weeks now. See: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.sd_image_raspberrypi4.aarch64-linux

The module closure fails to build with:
```
root module: sun4i_drm
modprobe: FATAL: Module sun4i_drm not found in directory /nix/store/86byp9ixv7yy94vaah92i926ff7i0068-linux-5.4.79-1.20201201-modules/lib/modules/5.4.79
``` 

CC @samueldr  

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module: installer/cd-dvd/sd-image-raspberrypi4.nix
```

**Comment by samueldr** [comment]
Caused by https://github.com/NixOS/nixpkgs/pull/78430

See https://github.com/NixOS/nixpkgs/issues/109280

**Comment by samueldr** [comment]
For the time being, there is no quick way to work around the issue. From the list of available modules, most are needed. We'd need to be able to filter out a module from the list, which AFAIK for lists is impossible with NixOS modules.

So uh... annoyingly it'll have to stay this way until some resolution of the overall issue :/...

**Comment by domenkozar** [comment]
@samueldr couldn't we allow missing kernel modules when generating images at least?

**Comment by samueldr** [comment]
The interface/abstraction for `availableKernelModules` is lacking. The fact it's a list, and lists are *really hard* to manipulate once set in NixOS modules makes this basically a hard task. I guess augmenting #78430 with a (default true) `failOnMissingModule` would help. But really what would be required is to tell *per module* whether it is needed, and allow overriding data.

So `availableKernelModules` needs to somehow allow setting "yes/no/optional" per-module, in an ideal world.

**Comment by mohe2015** [comment]
Quick idea but what about adding a `optionalKernelModules` or something like that and then use `availableKernelModules` \setminus `optionalKernelModules` as the required kernel modules?

**Comment by domenkozar** [comment]
I've merged https://github.com/NixOS/nixpkgs/pull/121720 that fixes this issue.

Once it [reaches the channels](https://status.nixos.org) you can download it via Hydra.

You can build it on nixpkgs master using `nix-build -A sd_image_new_kernel.aarch64-linux nixos/release.nix`.

**Comment by samueldr** [comment]
I don't think it solved this issue.

#121834 *works around the issue* by removing the raspberry pi 4 board-specific image.

With #121720 merged, the modules are still added to the raspberry pi 4 board-specific image, even if they're not present in the kernel build. In fact, there may be *more* failures!

**Comment by samueldr** [comment]
Ah sorry, I pre-emptively edited this page. And I'm splitting hair right now because *technically* the issue is still going on. But really it's all but merged-and-solved.

**Comment by necrophcodr** [comment]
It appears to still be broken. Booting the latest image from Hydra ( https://hydra.nixos.org/build/142828023 ) results in the image being unable to find /nix/.../init, and failing to continue booting from there.

**Comment by domenkozar** [comment]
@necrophcodr I've booted the same image and it works. What steps did you take?

Mine are:

```
  $ nix-shell -p wget zstd
  $ wget https://hydra.nixos.org/build/142828023/download/1/nixos-sd-image-21.05pre288297.8eed0e20953-aarch64-linux.img.zst
  $ unzip -d nixos-sd-image-21.05pre288297.8eed0e20953-aarch64-linux.img.zst
  # sudo dd if=nixos-sd-image-21.05pre288297.8eed0e20953-aarch64-linux.img of=/dev/sdX bs=4096 conv=fsync status=progress
```

**Comment by necrophcodr** [comment]
I performed the same steps, except the last one where I instead used GNOME Disks to write the disk image to the SD card. I don't have a way to reproduce it currently, since the Raspberry Pi 4 I was testing it on, has since been formatted with a different OS to be used in a production system tomorrow. I'll see if I can get my hands on another RPi 4B and perform the same steps again.

**Comment by necrophcodr** [comment]
The SD card used is the NOOBs SD card, but overwritten using the `dd` command as above, but with the `of` device replaced.

**Comment by samueldr** [comment]
The underlying issue is now invalid with #121834 being merged.

@necrophcodr I invite you to open an issue, linking to this issue, for your particular problem. It seems you have some kind of hardware-specific issue at first glance.

**Comment by necrophcodr** [comment]
Thanks, i will test it with other SD cards as well. It appears to only happen with this distribution, but it could certainly still be related to the hardware.

**Comment by anandsuresh** [comment]
I am trying to build NixOS for the raspberry Pi 4 and ran into the same error that started this thread. FWIW, I'm seeing this on nixpkgs `21.05-release` and on `master` as well.

Would it be prudent to re-open this ticket or file a fresh issue?

**Comment by samueldr** [comment]
@anandsuresh open a new issue with the specific issue you're observing detailed. Please detail what you are attempting to do (e.g. whether it's booting through SD or USB), and as much information as you can.

Note that there is a known issue (totally unrelated to this one) about **USB boot**, (#143885).
