### ISSUE TITLE
netcdf fails to build for aarch64

### ISSUE THREAD

**Issue by rmcgibbo** [NixOS/nixpkgs#115788]
**Describe the bug**
`netcdf` is failing to build on hydra/master for aarch64-linux

- https://hydra.nixos.org/build/138800241
- It looks like this is a somewhat known issue: https://github.com/Unidata/netcdf-c/issues/1857
- Although the upstream bug report doesn't indicate that this should be aarch64 specific.

It looks like netcdf doesn't have a maintainer so I will take a look when I have some free time.

**Comment by rmcgibbo** [comment]
This has been fixed: https://hydra.nixos.org/build/142921485

**Comment by nh2** [comment]
@rmcgibbo This issue is back!

https://hydra.nixos.org/build/148941124 -> https://hydra.nixos.org/build/148748621

```
NetCDF: HDF error
Location: file ncdump.c; line 1732
FAIL tst_nccopy4.sh (exit status: 1)
```

**Comment by rmcgibbo** [comment]
@nh2: That's unfortunate. I'm not sure what the correct solution is. Some possibilities would be:

1. Downgrade hdf5. (Nixpkgs likes to keep up with the latest releases, so not ideal.)
2. Disable the failing test. (But are we just masking a bug?)
3. Just wait for upstream to fix (Not sure how long.)
4. Upgrade netcdf (https://github.com/Unidata/netcdf-c/issues/1938#issuecomment-768511994). (Not sure if this will work.)

**Comment by nh2** [comment]
> 4. Upgrade netcdf (https://github.com/Unidata/netcdf-c/issues/1938#issuecomment-768511994). (Not sure if this will work.)

Doesn't work currently, creates a different test failure: https://github.com/Unidata/netcdf-c/issues/1857#issuecomment-900520480

**Comment by nh2** [comment]
I merged PR #134512 to fix this, thus closing again.
