### ISSUE TITLE
If you call wrapProgram twice on the same program, it breaks

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11586]
It was user error on my part, but as part of some automation, I accidentally called `wrapProgram` twice on the same program. The first invocation moved the binary `foo` to `.foo-wrapped`, and replaced `foo` with a script that called `.foo-wrapped`. The second invocation copied the wrapper script over `.foo-wrapped` and lost the original binary.

It seems like `wrapProgram` could fail loudly in that case, since I don't think it's ever desirable. Alternately, it could use a better name generation scheme that is collision-aware.

**Comment by domenkozar** [comment]
Python uses dual wrappers sometimes (which should be refactored), but it works. I remember it's an OSX issue.

**Comment by fkz** [comment]
I don't think it works under Linux. https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/make-wrapper.sh#L105:

    wrapProgram() {
       local prog="$1"
       local hidden="$(dirname "$prog")/.$(basename "$prog")"-wrapped
       mv $prog $hidden
       makeWrapper $hidden $prog --argv0 '"$0"' "$@"
    }

So the `mv` overwrites the wrapped program. Probably we should fail instead. (Use something like `mv -nT $prog $hidden && [ ! -f $prog ]`). (Or have I overlooked something?)

**Comment by Profpatsch** [comment]
`wrapProgram` is indeed not idempotent (since only one level of wrapping will ever be created). Would be nice to have it patched, or at least for the build to fail if there is already a wrapper.

**Comment by Profpatsch** [comment]
(triage) maybe it was fixed in the meantime?

**Comment by wmertens** [comment]
Not fixed yet - on Darwin and Solaris, a shebang can't point to a script. `makeWrapper` should parse and short circuit wrappers. Or https://github.com/NixOS/nixpkgs/issues/11133#issuecomment-479823543

**Comment by Profpatsch** [comment]
We solved this problem for execline by using a C wrapper, because ELF -> Shebang -> ELF -> Shebang -> …  works even on macOS: https://github.com/NixOS/nixpkgs/pull/71357

Maybe this approach could be generalized, or makeWrapper could always be a binary on macOS.
I’d advise against making it a binary always however, because it hurts debuggability.

**Comment by wmertens** [comment]
Still a problem. I guess this needs an RFC. Ideally, we'd have a wrapper that reads a series of config files (one per wrapping) and then correctly calls the wrapped binary.

This is not always ideal, since scripts are often called as `interpreter scriptfile`, which breaks if the script isn't using the same interpreter.

So we'd need a wrapper per script type, too.

On top of that, it's not that nice to have the wrapped script/executable live in a separately named file. This can be fixed by putting the wrapper in a separate package that symlinks or hardlinks the rest of the package, but then you get into tradeoffs regarding disk cache, dentry count, and executable image sharing.

Urgh.

**Comment by Profpatsch** [comment]
I guess you haven’t seen https://github.com/NixOS/rfcs/pull/75 ?

**Comment by wmertens** [comment]
Oh wow, how did I miss this? That's great. Why don't we close this issue in favor of the RFC?

**Comment by Profpatsch** [comment]
Let’s wait and see whether the RFC merges, stale bot will remind us :D
