### ISSUE TITLE
Gnome Activities icons should appear on app install

### ISSUE THREAD

**Issue by jonocodes** [NixOS/nixpkgs#12757]
I am using gnome3 in nixos. When I install an app in the console, I should be able to see it immediately in gnome's Activities. This is the case in ubuntu and arch when using gnome. In nix I have to logout and in in order to see the apps. Can this setup so I dont have to log out?

**Comment by jgillich** [comment]
You can also restart GNOME Shell with Alt+F2 and `r`. But I agree that having to restart is really really annoying and definitely something I want to look into at some point. Again cc @lethalman, maybe you have a clue what the issue is here?

**Comment by lethalman** [comment]
I never investigated this problem, but I believe the issue is with the fact that gnome shell watches xdg directories for changes, like ~/.nix-profile/share . However, that never changes in nix. What changes is ~/.nix-profile, hence gnome shell should watch whenever symlinks of profiles change rather than the contents of xdg directories.

I'm not sure what needs to be patched, but certainly something must be done as it's an unpleasant experience.

**Comment by lethalman** [comment]
After a quick look, gnome shell uses GDesktopAppInfo for listing apps. To do this, of course GDesktopAppInfo doesn't list all the .desktop files everytime, rather it watches it for changes using GFileMonitor: https://github.com/GNOME/glib/blob/master/gio/gdesktopappinfo.c

**Comment by ttuegel** [comment]
AFAIK, KDE doesn't use inotify for this, the directories are scanned at startup.

**Comment by lethalman** [comment]
@ttuegel and so how does it detect when a new app is installed?

**Comment by ttuegel** [comment]
@lethalman It doesn't until you log out or call `kbuildsycoca5`. KDE has its own package manager that will do the latter automatically if you're using it, but of course it doesn't work with Nix.

**Comment by jonocodes** [comment]
Interestingly it looked like some apps behave differently. When I installed 'atom' I had to restart to see it. When install gnome-tweak-tool, I was able to see it immediately.

**Comment by jgillich** [comment]
Probably because gnome-tweak-tool is installed by default, unless you disabled optional packages. :)

**Comment by jonocodes** [comment]
ah. tricky

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by tadfisher** [comment]
@Profpatsch No, this has not been fixed.

On a clean install with Gnome 3 enabled, this can be reproduced with:

```
nix-env -iA gimp
```

After installing, one has to log out of the desktop and log back in.

This is using a Gnome-Wayland session, btw.

**Comment by wmertens** [comment]
The KDE approach points to a way out: find the function in gnome-shell that gets called when the directory watchers ping it, and call it directly in the reload of the service.
Also, fix the directory watchers so they know about symlinks, or disable them on store paths

**Comment by wmertens** [comment]
One more option that @emilazy pointed out but I only now understood, is to create a separate shadow XDG directories in e.g. `/run/gnome-nix` and `~/.config/gnome-nix` which consists of real directories and symlinks to the files instead of the original store paths.
This needs to be maintained on activation though, which makes it not work for nix-shell and nix-env.

**Comment by bjornfor** [comment]
> You can also restart GNOME Shell with Alt+F2 and r

Unfortunately that does not work on Wayland (which is the default now).

**Comment by rhysmdnz** [comment]
Fixed by #118100

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/118100 only fixed this partially:

> **Known limitation:** On installations to /etc/profiles/per-user, the list of applications gets updated, but Shell fails to find the icons for new applications. This is the case when installing them declaratively through home-manager's NixOS module. Other methods, such as ad-hoc via nix-env/nix profile install work fine.

**Comment by zsmith009** [comment]
Still not fixed even though the original issue was opened in 2016. Fairly unbelievable.

**Comment by bjornfor** [comment]
> Still not fixed even though the original issue was opened in 2016. Fairly unbelievable.

AFAIR, you can search and launch immediately, but the icon will be missing until re-login (a generic placeholder icon is used instead).

**Comment by pearsche** [comment]
not on nixos though:(

**Comment by alex-robbins** [comment]
> not on nixos though

You sure? I just yesterday saw it working exactly as bjornfor described. After `nixos-rebuild swtich`, Gnome immediately picked up the new .desktop files and added them to the menu, just without the right icon. 

Seems to me that this issue is reduced to tracking an upstream bug as per the Apr. 30 comment.

**Comment by pearsche** [comment]
yeah, but i use nixos + home-manager (standalone, like to keep system and user separated). I wonder if that's the thing :thinking:

**Comment by cartoonnerie** [comment]
I just ran into the issue today. I am a complete newbie so I may make some other mistake. The app icon does not appear after installing an app through nixos and home-manager

**Comment by cartoonnerie** [comment]
I just ran into the issue today. I am a complete newbie so I may make some other mistake. The app icon does not appear after installing an app through nixos and home-manager.

**Comment by DaniD3v** [comment]
ran into this issue on stable branch. It worked on unstable

**Comment by Ceralex** [comment]
The ~/.nix-profile/share/application seems to update correctly when installing a new package, so I've written this temporary fix that automatically creates symlinks when the event fires.
Note that I'm using home-manager and i install packages as user-only.

Inside home.nix
```nix
home.activation.copyDesktopFiles = lib.hm.dag.entryAfter ["installPackages"] ''
    if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ]; then
      if [ -d "${config.home.homeDirectory}/.nix-profile/share/applications" ]; then
        rm -rf ${config.home.homeDirectory}/.local/share/applications
        mkdir -p ${config.home.homeDirectory}/.local/share/applications
        for file in ${config.home.homeDirectory}/.nix-profile/share/applications/*; do
          ln -sf "$file" ${config.home.homeDirectory}/.local/share/applications/
        done
      fi
    fi
  '';
```

**Comment by mmayla** [comment]
Your script is the only thing that worked for me, thanks @Ceralex!

**Comment by the-entelechy** [comment]
Would also like to add for newbies like myself to add lib to the arguments at the top like so:
{ config, pkgs, **lib,** ...}:
