### ISSUE TITLE
NixOS: can't get machine FQDN when resolved is enabled

### ISSUE THREAD

**Issue by B4dM4n** [NixOS/nixpkgs#132646]
### Describe the bug

When `services.resolved.enable = true` is used (either manually or with `networking.useNetworkd = true`), I can no longer get the FQDN of my machine with `hostname -f`.

### Steps To Reproduce
1. Checkout f09a770d9c938fe2986fead7d96af5743eefe516 (current master commit)
2. Put `services.resolved.enable = true` in `nixos/tests/hostname.nix`
3. Run `nix-build ./nixos/tests/hostname.nix -A explicitDomain`
4. The test fails:

```
...
ahost: must succeed: hostname --fqdn
(0.01 seconds)
error:
Traceback (most recent call last):
  File "/nix/store/mb9lhv3n6h20ybbpr2j8xdhbv5jgijwb-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 943, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 11, in <module>
AssertionError
cleaning up
killing ahost (pid 10)
(0.00 seconds)
```

### Expected behavior

The test should succeed and `hostname -f` should return the FQDN when `networking.domain` is set.

### Additional context

With the above procedure I could bisect the failure to #130503.

After #130503 the `noExplicitDomain` test in `nixos/tests/hostname.nix` also fails with the following error:

```
...
(0.06 seconds)
ahost: must succeed: getent hosts 127.0.0.1 | awk '{print $2}'
ahost: output:
error:
Traceback (most recent call last):
  File "/nix/store/mb9lhv3n6h20ybbpr2j8xdhbv5jgijwb-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 943, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 22, in <module>
  File "/nix/store/mb9lhv3n6h20ybbpr2j8xdhbv5jgijwb-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 483, in succeed
    raise Exception(
Exception: command `getent hosts 127.0.0.1 | awk '{print $2}'` failed (exit code 2)
cleaning up
killing ahost (pid 10)
(0.00 seconds)
```

### Notify maintainers

@flokli 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210712_099df07`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
That's interesting `/etc/nsswitch.conf` should contain:

without resolved:
```
hosts:     mymachines files myhostname dns
```

with resolved:
```
hosts:     mymachines resolve [!UNAVAIL=return] files myhostname dns
```

This suggests something inside the `resolve` module resolves things differently.

What does `hostname --fqdn` do under the hood?

**Comment by primeos** [comment]
> This suggests something inside the resolve module resolves things differently.

Yes, `systemd` doesn't know about the domain name, only the hostname. IIRC it should work with this:
```
hosts:     mymachines files resolve [!UNAVAIL=return] myhostname dns
```

> What does hostname --fqdn do under the hood?

It was implemented like this when I last looked at it: https://gist.github.com/primeos/8f7f8e1e95518076ef38924125a2f921

**Comment by mpasternacki** [comment]
The report doesn't mention what `hostname --fqdn` actually prints for the author, so I'm not sure if it's the same issue, but on my system, `nixpkgs-unstable` with `networking.hostName` and `networking.domain` set, `hostname --fqdn` shows only short hostname (without domain).

```
[japhy@bmo:~] % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.17, NixOS, 23.05 (Stoat), 23.05.20230106.b3818a4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by wkral** [comment]
I was attempting to fix `nixos.tests.networking.hostname.explicitDomain` for ZHF and saw that seeminly this issue was fixed at some point but broke again in this build: https://hydra.nixos.org/build/208026588 on Feb 3rd. I bisected the changes and it seems it broke with fbfe290 introducing [nsncd](https://github.com/twosigma/nsncd) (assuming I bisected correctly).

I'm sort of piecing things together, from `man hostname`: 

>  The FQDN is the canonical name returned by gethostbyname2(2) when resolving the result of the gethostname(2) name. The DNS domain name  is  the  part after the first dot.

I browsed through the code and noticed `gethostbyname` and some others are not currently implemented, but from twosigma/nsncd#49 it seems @flokli you're working on that in nsncd. So perhaps this gets resolved when that does? I didn't see any mention of `gethostbyname2` in the project but maybe there is something equivalent that will resolve this issue/fix that test.

**Comment by NinjaTrappeur** [comment]
Related: 

https://github.com/NixOS/nixpkgs/issues/196934
https://github.com/nix-community/nsncd/issues/4

**Comment by 999eagle** [comment]
I still have this issue on my system (or a closely related one).

The exact conditions to trigger this issue seem to be:
- use `systemd-resolved` and `nsncd`
- have `networking.enableIPv6 = true`

`hostname --short` returns my actual (short) hostname, `hostname --fqdn` always returns `localhost` for me.

If I stop `systemd-resolved`, stop `nscd` or remove the line `::1 localhost` from `/etc/hosts`, the correct FQDN is returned.

<details>
<summary>relevant <code>systemd-resolved</code> logs for the error case</summary>
<pre>
varlink-28: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"$hostname","family":10,"flags":0}}
Looking up RR for $hostname IN AAAA.
Following CNAME/DNAME $hostname → localhost.
varlink-28: Sending message: {"parameters":{"addresses":[{"family":10,"address":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]}],"name":"localhost","flags":786945}}
</pre>
</details>
<details>
<summary>relevant <code>systemd-resolved</code> logs when IPv6 is disabled</summary>
<pre>
varlink-28: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"$hostname","family":10,"flags":0}}
Looking up RR for $hostname IN AAAA.
varlink-28: Sending message: {"error":"io.systemd.Resolve.NoSuchResourceRecord","parameters":{}}
varlink-28: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"$hostnamefamily":2,"flags":0}}
Looking up RR for $hostname IN A.
Following CNAME/DNAME $hostname → $fqdn.
varlink-28: Sending message: {"parameters":{"addresses":[{"family":2,"address":[127,0,0,2]}],"name":"$fqdn,"flags":786945}}
</pre>
</details>

When the `nscd` service is stopped, no DNS query is logged by `systemd-resolved`. This looks like `nsncd` first tries to resolve the short hostname over IPv6 only and `systemd-resolved` rewrites this to `localhost` because all three entries for `localhost`, the short hostname and the FQDN are mapped to the same IPv6 address `::1` in `/etc/hosts`.

**Comment by picnoir** [comment]
I can't repro :(

Could you give me the Nixpkgs commit ref you used for this test? Did you double-check that https://github.com/picnoir/nixpkgs/commit/364a38956d05b52e67bf3a3bcc9640368786bae1 is in your pin?

**Comment by 999eagle** [comment]
I'm on `8efd5d1e283604f75a808a20e6cde0ef313d07d4` but with `nsncd` overridden from `364a38956d05b52e67bf3a3bcc9640368786bae1`.

**Comment by picnoir** [comment]
Gah. This will never end.

Do we have a VM test for this?

I can't check it out rn. Re-opening the issue in the meantime.

**Comment by picnoir** [comment]
cc @Mic92 for https://github.com/NixOS/nixpkgs/issues/132646#issuecomment-1782594859

Maybe you have more context about this name resolution since you added this `::1` line in the hosts file.

@999eagle, could you try the same test with `services.nscd.enableNscd = false;` to see if we hit the same behaviour with Nscd. It'd be handy to see if this is Nsncd related or not.

**Comment by 999eagle** [comment]
I've tried again with `nscd` instead of `nsncd` now and it shows the exact same issue with the same logs in `systemd-resolved`. The "default" `nscd` apparently also tries to resolve the FQDN using IPv6 first. `systemd-resolved` still resolves the short hostname to `::1` with the name `localhost` as that's the first name matching `::1` in `/etc/hosts`.
Manually changing `/etc/hosts` to contain the line `::1 $fqdn $hostname localhost` makes `systemd-resolved` correctly return the FQDN. The discussion in #119236 which was already linked here before seems to be very relevant to this.

**Comment by B4dM4n** [comment]
> Do we have a VM test for this?

The reproduce steps from https://github.com/NixOS/nixpkgs/issues/132646#issue-960221270 are sufficient to trigger the bug.

The test still fails when `services.resolved.enable = true;` is added. Adding `services.nscd.enableNsncd = false;` also does not fix the issue (tested on master c05811cfed793c83e1b2d431384f13d64ffdfc13).

**Comment by sedlund** [comment]
On 23.11 with

```nix
networking.hostName = "nixos";
networking.domain = "lan";
systemd.network.enable = true;
```

I get:

``` shell
$ hostname
nixos

$ hostname -f
localhost
```

Fedora 39 has `files` first.  more specifically:

```
hosts:      files myhostname resolve [!UNAVAIL=return] dns
```

RedHat is a large contributor to systemd, uses it in their distribution and [recommends it ](https://github.com/systemd/systemd/issues/23662#issuecomment-1152955163)

I made `files` first and `hostname -f` returns `nixos.lan` as expected.  I also removed `[!UNAVAIL=return]` as it caused my pings to shortnames of my `resolved.domains` to time out and falsely claim they didn't exist.

**Comment by picnoir** [comment]
Small, note if you end up here. There's a known regression ATM. Temporarily reverting https://github.com/NixOS/nixpkgs/pull/362132 should fix the issue up until we find a proper fix.

**Comment by lschuermann** [comment]
> Small, note if you end up here. There's a known regression ATM. Temporarily reverting [#362132](https://github.com/NixOS/nixpkgs/pull/362132) should fix the issue up until we find a proper fix.

@picnoir FWIW, I'm proposing to effectively revert #362132, as that also prevents resolving v6 addresses for the machine's local FQDN despite AAAA records being present in DNS and addresses configured. So that should also work around this issue, I suppose?

**Comment by xanderio** [comment]
I'm currently facing this issue on one system where GitLab-pages wasn't able to contact the GitLab API as GitLab itself is also deployed on that same machine. The one thing that confuses me is that this issue didn't manifest until a few minutes to hours the system booted.

I was able to temporary fix this by running `resolvectl flush-caches` which removed the `127.0.0.2` response for the FQDN from the cache, but after some time this gets repopulated. A more permeant fix was achieved by specifying the public v6 and v4 as entries in the hosts files.

As this system is using 25.05 this affects our current release and isn't "contained" to unstable. Reverting #362132 would somewhat fix this, but only on systems with v6 enabled and the service listening on v6. We need to remove the 127.0.0.2 from the hosts file.

**Comment by lschuermann** [comment]
@xanderio FWIW, the preliminary conclusion in https://github.com/NixOS/nixpkgs/pull/380987 was that we need to reach out to the systemd folks on how they intend `/etc/hosts` to be populated. Unfortunately this has fallen off my radar and I'm very stretched for time right now. Would you be willing to continue the efforts in that PR?

**Comment by xanderio** [comment]
After looking at how Fedora and Debian handle this, we should provide an option to specify the public v6 and/or v4 of the host, if it has one. This information should then be used to replace the 127.0.0.2 entry.

The issue I ran into was that a service the isn't listening on `::` or `0.0.0.0` doesn't responses to request for 127.0.0.2, this is quite unintuitive.
