### ISSUE TITLE
ld.gold doesn't understand .note.gnu.property section in crt1.o

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#134700]
### Describe the bug

Presumably since https://github.com/NixOS/nixpkgs/commit/acdcb8566ae560752a8a1ce3aacc617a3da6cdd5, `glibc`'s `crt1.o` makes use of the new `.note.gnu.property` section which our binutils 2.35 `ld.gold` doesn't understand, leading to warnings such as this one:

```
/nix/store/hy3lz2vfv9qq2v5jz9nzlx6mmiaq79rj-binutils-2.35.1/bin/ld.gold: warning: /nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib/crt1.o: unknown program property type 0xc0008002 in .note.gnu.property section
```

More context can be found here:

* [Upstream bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=22914)
* [Upstream fix](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=6c04fd9b2fb4396c0189cb414ce598161ac8673e)
* [System V ABI draft for Linux](https://raw.githubusercontent.com/wiki/hjl-tools/linux-abi/linux-abi-draft.pdf) which describes the `.note.gnu.property` section

Since binutils 2.36, `ld.gold` supports the new note section. However we have been hesitant to update binutils so far (since it usually introduces a lot of breakage, e. g. see <https://github.com/NixOS/nixpkgs/pull/129900>).

Open question: Is this a serious problem? Should we apply the patch from 2.36? Should we disable `ld.gold` in the meantime where we use it?

### Steps To Reproduce

Build any haskell package on a platform that supports `ld.gold` (with `--check` if necessary).

### Notify maintainers

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: binutils, haskellPackages
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
I'd expect this would get fixed by PR https://github.com/NixOS/nixpkgs/pull/134195

**Comment by teto** [comment]
I've tried https://github.com/NixOS/nixpkgs/pull/134195 but that doesn't seem to fix it for me. It leads to a lot of warnings when building some custom packages so curious about a solution.

**Comment by sternenseemann** [comment]
All warnings I've experienced so far have been fixed by this (or some other change).

**Comment by sternenseemann** [comment]
I think this is fixed now? Haven't seen the warning for a long time now.
