### ISSUE TITLE
warning: name collision in input Nix expressions, skipping '/Users/wu/.nix-defexpr/channels_root/nixpkgs'

### ISSUE THREAD

**Issue by ixnij** [NixOS/nixpkgs#136136]
### Describe the bug

```console
wu@mbp ~ % nix-env -qa lilypond
warning: name collision in input Nix expressions, skipping '/Users/wu/.nix-defexpr/channels_root/nixpkgs'
lilypond-2.22.1
lilypond-2.22.1
```

### Steps To Reproduce
1.  `nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixpkgs-unstable nixpkgs`
2. `nix-channel --update`
3.  `nix-env -qa lilypond`

### Expected behavior
the output of "nix-env -qa lilypond" without "warning: name collision in input Nix expressions, skipping '/Users/wu/.nix-defexpr/channels_root/nixpkgs'".

### Additional context
I checked #53482  , but this solution is for nixOS. I removed nix-pkgs unstable and then added it again, which did not solve the problem.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.5.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixpkgs-21.11pre312229.08ef0f28e3a"`
 - channels(wu): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by soulomoon** [comment]
I don't see a solution, why closing it?

**Comment by ixnij** [comment]
> I don't see a solution, why closing it?

This problem was solved after I reinstalled Nix, so I closed it.

**Comment by lionello** [comment]
I got the same error after I had added `nixos` as a channel for the non-root user, but the error persisted after removing the channel. `nix-info` shows root has two channels:
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(lionello): `""`
 - channels(root): `"nixpkgs-22.05pre337993.e6df26a654b, nixos-21.05.4470.3b422991781"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

But `nix-channel --list` only showed `nixpkgs` for root user:
```
$ sudo -i nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

Even though it wasn't explicitly listed, I could still remove the `nixos` channel for root!?
```
$ sudo -i nix-channel --remove nixos
uninstalling 'nixos-21.05.4470.3b422991781'
building '/nix/store/j3ay0bx67j065rnpmmwj3fsjl17izqcs-user-environment.drv'...
```

This fixed my issue.

**Comment by Michael-J-Ward** [comment]
So, as someone that's learning `nix` i was a little surprised by this. 

`nix-channel --rollback` doesn't touch `~/.nix-channels`

So if you arrive at this issue, `--rollback` will only temporarily fix it until the next time you run `nix-channel --update`

The real solution is to run `nix-channel --remove <offending-channel>`

**Comment by Artturin** [comment]
https://github.com/NixOS/nix/pull/6244

**Comment by nekoniaow** [comment]
I seem to be having the same problem however none of the above mentioned solutions work.

Context:
```
$ nix-env -qaP 'dummysearch'
warning: name collision in input Nix expressions, skipping '/Users/laurent/.nix-defexpr/channels_root/nixpkgs'
suggestion: remove 'nixpkgs' from either the root channels or the user channels
error: selector 'dummysearch' matches no derivations

$ nix-channel --list

$ sudo -i nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable

$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin aa.bb.c, macOS xx.yy.z`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(laurent): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

$ nix-channel --remove nixpkgs
warning: selector 'nixpkgs' matched no installed derivations

$ ls -l ~/.nix-defexpr/
total 0
lrwxr-xr-x  1 root     staff  44 21 Oct  2020 channels -> /nix/var/nix/profiles/per-user/root/channels
lrwxr-xr-x  1 laurent  staff  44 23 Aug  2019 channels_root -> /nix/var/nix/profiles/per-user/root/channels
```

Isn't the issue that both `channels` and `channels_root` point to the same file?

Note that this happened after my first installation (months ago, so long forgotten), so there seems to be something in the installation process which allows this to happen.

I suppose I could correct this manually by deleting `channels` but I am hesitant to mess with those files manually.

**Comment by andrewcrook** [comment]
I have been getting the same.
I removed the the channel from root _which fixed the issue_
symbolic links I get 

```
lrwxr-xr-x    1 andrew  staff    46 27 Apr 19:04 channels -> /nix/var/nix/profiles/per-user/andrew/channels
lrwxr-xr-x    1 andrew  staff    44 25 Apr 20:02 channels_root -> /nix/var/nix/profiles/per-user/root/channels
```

```
> nix-shell -p nix-info --run "nix-info -m" 
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(andrew): `"darwin, home-manager-22.11.tar.gz, nixpkgs-22.11-darwin"`
 - channels(root): `""`
 - nixpkgs: `/Users/andrew/.nix-defexpr/channels/nixpkgs`
```

> Isn't the issue that both channels and channels_root point to the same file?

I don't know why there is a name collision. 
But I would have thought there would be a situation users could have their own subscribed channels the same or have different or perhaps I have missed something?

yet again, flakes (which I use) are pure so `<nixpkgs> <darwin> <home-manager>` shouldn’t work from what I understand hence why you define them in each flake. correct?

confusing
