### ISSUE TITLE
Desktop entries don't update when performing `nixos-rebuild switch` after adding/removing derivations containing desktop items

### ISSUE THREAD

**Issue by mitchmindtree** [NixOS/nixpkgs#139999]
### Describe the bug

When running `sudo nixos-rebuild switch` after adding or removing a system or home-manager package containing a freedesktop entry, the desktop (on GNOME 40 + Wayland at least) remains unaware of the change until logging out and logging back in again.

### Steps To Reproduce

1. Add a package with a `.desktop` entry to your `systemPackages` or home-manager packages.
2. Run `sudo nixos-rebuild switch`
3. Try searching for the entry in GNOME Activities - it will likely not appear until logging in again.

### Expected behavior

If the set of desktop entries changes during a `nixos-rebuild switch`, the desktop environment's entries should be "refreshed" and be immediately aware of the new desktop entry.

### Additional context

I'm unsure if this is also the case on KDE desktops as I've only tested with GNOME 40.

I'm unsure if this is possible to achieve without a lot of fiddling. I imagine it is the Desktop Environment's responsibility to track desktop entries. As a result, I'd imagine the procedure would have to look something like this:

1. Detect a change in the set of desktop entries. _I haven't dug into nixpkgs enough to know where this would be performed just yet._
2. If there was a change and if a desktop environment is enabled, trigger a desktop-environment-specific command to refresh its desktop entries.

There are some suggestions on how to refresh desktop entries here:

https://unix.stackexchange.com/questions/12118/how-do-i-refresh-gnome-3-applications

Unfortunately many suggestions appear to be X11 specific. The only approach I've had success with so far on Wayland is logging out and back in again (not very convenient).

The [Arch wiki suggests](https://wiki.archlinux.org/title/desktop_entries#Update_database_of_desktop_entries) to run the following:

```
$ update-desktop-database ~/.local/share/applications
```

and a [GNOME developer also suggests](https://discourse.gnome.org/t/gnome-doesnt-show-icons-for-newly-installed-applications/6237/2) running `update-desktop-database`.

The `update-desktop-database` tool is not present in the default NixOS GNOME setup, but can be installed via the `desktop-file-utils` package.

The command appears to be aware of the necessary directories to check (e.g. `/nix/store/*/share/applications`) however it fails with a `* could not be updated` error and complains that each of those directories are read-only. I'm not sure why the tool would require anything more than read-access, but either way it appears to fail to update the desktop entries when I run it locally.

<details>
<summary>`update-desktop-database --verbose` output</summary>

```
Search path is now: [/nix/store/xfc0ffwz6s87mnz9x2k2qj6ykwxgwjxk-patchelf-0.12/share/applications, /nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/jb5qfmipvsh39342xh68qfmly391b4c8-nautilus-40.1/share/gsettings-schemas/nautilus-40.1/applications, /nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/gsettings-schemas/gnome-terminal-3.40.1/applications, /nix/store/c67np55z6nc0gaa5siys5sa424xnagvm-shared-mime-info-1.13.1/share/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/6ziw5cj6bik5f8ahqn7kd6w7cvylb981-gnome-keyring-40.0/share/gsettings-schemas/gnome-keyring-40.0/applications, /nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/gsettings-schemas/gcr-3.40.0/applications, /nix/store/71qb38745nnd0gxiq5k680fqvgv7ki8j-mutter-40.1/share/gsettings-schemas/mutter-40.1/applications, /nix/store/183hqhbmzpwjsx2birbq95r9dbijl5nm-evolution-data-server-3.40.2/share/gsettings-schemas/evolution-data-server-3.40.2/applications, /nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/gsettings-schemas/gtk4-4.2.1/applications, /nix/store/4likmbhvxp8r898nqayv297ry080h7ih-gdm-40.0/share/gsettings-schemas/gdm-40.0/applications, /nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/gsettings-schemas/gnome-clocks-40.0/applications, /nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/gsettings-schemas/ibus-1.5.24/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/dr61yrxblp755iax3dxkdv3af7gw2hs5-libgweather-40.0/share/gsettings-schemas/libgweather-40.0/applications, /nix/store/ciq4n4176nw2nv36pn47aa3bp10gcvdi-libnma-1.8.30/share/gsettings-schemas/libnma-1.8.30/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications, /nix/store/6p2qz1vcfjjdhrpwqmwdfhycsg94f4j0-cups-2.3.3/share/applications, /nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/applications, /nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications, /nix/store/9abd6p55w5iplsragm9c3d590dx0jabq-adwaita-icon-theme-40.1.1/share/applications, /nix/store/8kd8w81gwn25h1zjzqq5qwiqjz58841a-hicolor-icon-theme-0.17/share/applications, /nix/store/0f6dpzgmmy9ki6sabfb5h6qmwlj4pyjf-gnome-bluetooth-3.34.5/share/applications, /nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/applications, /nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications, /nix/store/81lhj58b6n6prlm3dw4pxddq0vmczxcz-gnome-mimeapps/share/applications, /nix/store/djgq97g39zrny99lq1y1ivp1qf9jrc8h-desktops/share/applications, /home/mindtree/.nix-profile/share/applications, /etc/profiles/per-user/mindtree/share/applications, /nix/var/nix/profiles/default/share/applications, /run/current-system/sw/share/applications, /nix/store/6q9bhxxny8sascsa67jl1h8gb1yc858v-telepathy-logger-0.8.2/share/gsettings-schemas/telepathy-logger-0.8.2/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications, /nix/store/cb2bahz19g7j12lfqvyk6pdh6figg9d8-gnome-shell-extensions-40.1/share/gsettings-schemas/gnome-shell-extensions-40.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications]
Could not create cache file in "/nix/store/xfc0ffwz6s87mnz9x2k2qj6ykwxgwjxk-patchelf-0.12/share/applications": Error opening directory ?/nix/store/xfc0ffwz6s87mnz9x2k2qj6ykwxgwjxk-patchelf-0.12/share/applications?: No such file or directory
File "/nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/applications/org.gnome.Terminal.desktop" lacks MimeType key
Could not create cache file in "/nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/applications": Read-only file system
Could not create cache file in "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications": Error opening directory ?/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications?: No such file or directory
Could not create cache file in "/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications": Error opening directory ?/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/jb5qfmipvsh39342xh68qfmly391b4c8-nautilus-40.1/share/gsettings-schemas/nautilus-40.1/applications": Error opening directory ?/nix/store/jb5qfmipvsh39342xh68qfmly391b4c8-nautilus-40.1/share/gsettings-schemas/nautilus-40.1/applications?: No such file or directory
Could not create cache file in "/nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/gsettings-schemas/gnome-terminal-3.40.1/applications": Error opening directory ?/nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/gsettings-schemas/gnome-terminal-3.40.1/applications?: No such file or directory
Could not create cache file in "/nix/store/c67np55z6nc0gaa5siys5sa424xnagvm-shared-mime-info-1.13.1/share/applications": Error opening directory ?/nix/store/c67np55z6nc0gaa5siys5sa424xnagvm-shared-mime-info-1.13.1/share/applications?: No such file or directory
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/evolution-calendar.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.PortalHelper.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.desktop" lacks MimeType key
Could not create cache file in "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications": Read-only file system
Could not create cache file in "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications": Error opening directory ?/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications?: No such file or directory
Could not create cache file in "/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications": Error opening directory ?/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/6ziw5cj6bik5f8ahqn7kd6w7cvylb981-gnome-keyring-40.0/share/gsettings-schemas/gnome-keyring-40.0/applications": Error opening directory ?/nix/store/6ziw5cj6bik5f8ahqn7kd6w7cvylb981-gnome-keyring-40.0/share/gsettings-schemas/gnome-keyring-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/gsettings-schemas/gcr-3.40.0/applications": Error opening directory ?/nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/gsettings-schemas/gcr-3.40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/71qb38745nnd0gxiq5k680fqvgv7ki8j-mutter-40.1/share/gsettings-schemas/mutter-40.1/applications": Error opening directory ?/nix/store/71qb38745nnd0gxiq5k680fqvgv7ki8j-mutter-40.1/share/gsettings-schemas/mutter-40.1/applications?: No such file or directory
Could not create cache file in "/nix/store/183hqhbmzpwjsx2birbq95r9dbijl5nm-evolution-data-server-3.40.2/share/gsettings-schemas/evolution-data-server-3.40.2/applications": Error opening directory ?/nix/store/183hqhbmzpwjsx2birbq95r9dbijl5nm-evolution-data-server-3.40.2/share/gsettings-schemas/evolution-data-server-3.40.2/applications?: No such file or directory
Could not create cache file in "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/gsettings-schemas/gtk4-4.2.1/applications": Error opening directory ?/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/gsettings-schemas/gtk4-4.2.1/applications?: No such file or directory
Could not create cache file in "/nix/store/4likmbhvxp8r898nqayv297ry080h7ih-gdm-40.0/share/gsettings-schemas/gdm-40.0/applications": Error opening directory ?/nix/store/4likmbhvxp8r898nqayv297ry080h7ih-gdm-40.0/share/gsettings-schemas/gdm-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/gsettings-schemas/gnome-clocks-40.0/applications": Error opening directory ?/nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/gsettings-schemas/gnome-clocks-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/gsettings-schemas/ibus-1.5.24/applications": Error opening directory ?/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/gsettings-schemas/ibus-1.5.24/applications?: No such file or directory
Could not create cache file in "/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications": Error opening directory ?/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications?: No such file or directory
Could not create cache file in "/nix/store/dr61yrxblp755iax3dxkdv3af7gw2hs5-libgweather-40.0/share/gsettings-schemas/libgweather-40.0/applications": Error opening directory ?/nix/store/dr61yrxblp755iax3dxkdv3af7gw2hs5-libgweather-40.0/share/gsettings-schemas/libgweather-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/ciq4n4176nw2nv36pn47aa3bp10gcvdi-libnma-1.8.30/share/gsettings-schemas/libnma-1.8.30/applications": Error opening directory ?/nix/store/ciq4n4176nw2nv36pn47aa3bp10gcvdi-libnma-1.8.30/share/gsettings-schemas/libnma-1.8.30/applications?: No such file or directory
Could not create cache file in "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications": Error opening directory ?/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications?: No such file or directory
File "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications/gtk3-demo.desktop" lacks MimeType key
File "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications/gtk3-icon-browser.desktop" lacks MimeType key
File "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications/gtk3-widget-factory.desktop" lacks MimeType key
Could not create cache file in "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications": Read-only file system
File "/nix/store/6p2qz1vcfjjdhrpwqmwdfhycsg94f4j0-cups-2.3.3/share/applications/cups.desktop" lacks MimeType key
Could not create cache file in "/nix/store/6p2qz1vcfjjdhrpwqmwdfhycsg94f4j0-cups-2.3.3/share/applications": Read-only file system
File "/nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/applications/gcr-prompter.desktop" lacks MimeType key
Could not create cache file in "/nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/applications": Read-only file system
File "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications/org.gtk.IconBrowser4.desktop" lacks MimeType key
File "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications/org.gtk.WidgetFactory4.desktop" lacks MimeType key
File "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications/org.gtk.PrintEditor4.desktop" lacks MimeType key
File "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications/org.gtk.Demo4.desktop" lacks MimeType key
Could not create cache file in "/nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications": Read-only file system
Could not create cache file in "/nix/store/9abd6p55w5iplsragm9c3d590dx0jabq-adwaita-icon-theme-40.1.1/share/applications": Error opening directory ?/nix/store/9abd6p55w5iplsragm9c3d590dx0jabq-adwaita-icon-theme-40.1.1/share/applications?: No such file or directory
Could not create cache file in "/nix/store/8kd8w81gwn25h1zjzqq5qwiqjz58841a-hicolor-icon-theme-0.17/share/applications": Error opening directory ?/nix/store/8kd8w81gwn25h1zjzqq5qwiqjz58841a-hicolor-icon-theme-0.17/share/applications?: No such file or directory
File "/nix/store/0f6dpzgmmy9ki6sabfb5h6qmwlj4pyjf-gnome-bluetooth-3.34.5/share/applications/bluetooth-sendto.desktop" lacks MimeType key
Could not create cache file in "/nix/store/0f6dpzgmmy9ki6sabfb5h6qmwlj4pyjf-gnome-bluetooth-3.34.5/share/applications": Read-only file system
File "/nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/applications/org.gnome.clocks.desktop" lacks MimeType key
Could not create cache file in "/nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/applications": Read-only file system
File "/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications/org.freedesktop.IBus.Panel.Extension.Gtk3.desktop" lacks MimeType key
File "/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications/org.freedesktop.IBus.Setup.desktop" lacks MimeType key
File "/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications/org.freedesktop.IBus.Panel.Emojier.desktop" lacks MimeType key
Could not create cache file in "/nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications": Read-only file system
Could not create cache file in "/nix/store/81lhj58b6n6prlm3dw4pxddq0vmczxcz-gnome-mimeapps/share/applications": Read-only file system
Could not create cache file in "/nix/store/djgq97g39zrny99lq1y1ivp1qf9jrc8h-desktops/share/applications": Error opening directory ?/nix/store/djgq97g39zrny99lq1y1ivp1qf9jrc8h-desktops/share/applications?: No such file or directory
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_gate_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_room_builder_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_gate_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_profiler_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_expander_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_impulse_reverb_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_dyna_processor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_compressor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/carla-jack-single.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_oscillator_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_comp_delay_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x24.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/carla-rack.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_expander_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_compressor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_gate_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_surge_filter_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_slap_delay_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x16_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_dyna_processor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x32_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_dyna_processor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_comp_delay_x2_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_expander_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x32_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_loud_comp_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zynaddsubfx-jack-multi.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zynaddsubfx-oss.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_expander_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_compressor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x16_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/bitwarden.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_dyna_processor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_limiter_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_compressor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/qjackctl.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_dyna_processor_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/pcbcalculator.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/net.sourceforge.VMPK.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_crossover_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_compressor_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_expander_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x2.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_dyna_processor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_expander_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x16_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_expander_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_expander_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_impulse_responses_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_room_builder_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/cataclysm-dda.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_gate_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/mixxx.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_compressor_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_gate_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_gate_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x32_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_compressor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_gate_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x16.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x16_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_trigger_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_compressor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_compressor_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x48.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/carla-control.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x32_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_expander_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/minecraft-launcher.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_limiter_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x32_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_gate_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x32_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x12.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_dyna_processor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_impulse_reverb_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_compressor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_profiler_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x24_do.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_compressor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/carla-jack-multi.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x32_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_crossover_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_trigger_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_expander_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_expander_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/bitmap2component.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_trigger_midi_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x48_do.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zenmap-root.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x8.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_expander_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_expander_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x16_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/SoulseekQt.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_comp_delay_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zynaddsubfx-alsa.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_limiter_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/org.gnome.tweaks.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/calf.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_crossover_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_impulse_responses_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_dyna_processor_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x12_do.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_gate_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zynaddsubfx-jack.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/org.gnome.PowerStats.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_trigger_midi_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_phase_detector.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sampler_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_gate_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_compressor_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_gate_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_gate_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_compressor_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x16_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_crossover_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_compressor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x16_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_expander_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/org.gnome.Shell.Extensions.GSConnect.Preferences.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_gate_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_latency_meter.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sampler_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_gate_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_gate_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_gate_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/org.gnome.Terminal.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/carla-patchbay.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_mb_compressor_lr.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_surge_filter_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_limiter_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_mb_expander_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/bluetooth-sendto.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_expander_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x4.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_slap_delay_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_para_equalizer_x16_ms.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x32_mono.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_multisampler_x12.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/zenmap.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x1.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_loud_comp_stereo.desktop" lacks MimeType key
File "/home/mindtree/.nix-profile/share/applications/in.lsp_plug.lsp_plugins_sc_compressor_mono.desktop" lacks MimeType key
Could not create cache file in "/home/mindtree/.nix-profile/share/applications": Read-only file system
Could not create cache file in "/etc/profiles/per-user/mindtree/share/applications": Error opening directory ?/etc/profiles/per-user/mindtree/share/applications?: No such file or directory
Could not create cache file in "/nix/var/nix/profiles/default/share/applications": Error opening directory ?/nix/var/nix/profiles/default/share/applications?: No such file or directory
File "/run/current-system/sw/share/applications/org.gnome.Photos.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-power-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-info-overview-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-region-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/xterm.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/evolution-calendar.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gtk3-demo.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.seahorse.Application.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-initial-setup.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-datetime-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Evince-previewer.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/nixos-manual.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-system-monitor-kde.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-background-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-camera-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Weather.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-keyboard-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/geoclue-where-am-i.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-online-accounts-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-user-share-webdav.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Tour.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Extensions.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-control-center.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-bluetooth-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gcm-calibrate.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-mouse-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Calculator.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/geary-autostart.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Characters.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Shell.Extensions.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Shell.PortalHelper.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Evolution-alarm-notify.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-display-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-system-monitor.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-wifi-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-microphone-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-notifications-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-sound-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.ColorProfileViewer.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Contacts.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-user-accounts-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Screenshot.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-thunderbolt-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Calendar.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/rygel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-wacom-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-diagnostics-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gtk3-icon-browser.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-color-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-usage-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-applications-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Music.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-location-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Shell.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-network-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Cheese.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-search-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/rygel-preferences.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Terminal.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-printers-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-sharing-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-removable-media-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.Logs.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/simple-scan.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-default-apps-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/bluetooth-sendto.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-universal-access-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.ChromeGnomeShell.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gnome-lock-panel.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.clocks.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gtk3-widget-factory.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/org.gnome.DiskUtility.desktop" lacks MimeType key
File "/run/current-system/sw/share/applications/gcm-picker.desktop" lacks MimeType key
Could not create cache file in "/run/current-system/sw/share/applications": Read-only file system
Could not create cache file in "/nix/store/6q9bhxxny8sascsa67jl1h8gb1yc858v-telepathy-logger-0.8.2/share/gsettings-schemas/telepathy-logger-0.8.2/applications": Error opening directory ?/nix/store/6q9bhxxny8sascsa67jl1h8gb1yc858v-telepathy-logger-0.8.2/share/gsettings-schemas/telepathy-logger-0.8.2/applications?: No such file or directory
Could not create cache file in "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications": Error opening directory ?/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications?: No such file or directory
Could not create cache file in "/nix/store/cb2bahz19g7j12lfqvyk6pdh6figg9d8-gnome-shell-extensions-40.1/share/gsettings-schemas/gnome-shell-extensions-40.1/applications": Error opening directory ?/nix/store/cb2bahz19g7j12lfqvyk6pdh6figg9d8-gnome-shell-extensions-40.1/share/gsettings-schemas/gnome-shell-extensions-40.1/applications?: No such file or directory
Could not create cache file in "/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications": Error opening directory ?/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications?: No such file or directory
Could not create cache file in "/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications": Error opening directory ?/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications": Error opening directory ?/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications?: No such file or directory
Could not create cache file in "/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications": Error opening directory ?/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications?: No such file or directory
Could not create cache file in "/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications": Error opening directory ?/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications?: No such file or directory
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/evolution-calendar.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.PortalHelper.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.desktop" lacks MimeType key
Could not create cache file in "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications": Read-only file system
Could not create cache file in "/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications": Error opening directory ?/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications?: No such file or directory
Could not create cache file in "/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications": Error opening directory ?/nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications?: No such file or directory
Could not create cache file in "/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications": Error opening directory ?/nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications?: No such file or directory
Could not create cache file in "/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications": Error opening directory ?/nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications?: No such file or directory
Could not create cache file in "/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications": Error opening directory ?/nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications?: No such file or directory
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/evolution-calendar.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.Extensions.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.PortalHelper.desktop" lacks MimeType key
File "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications/org.gnome.Shell.desktop" lacks MimeType key
Could not create cache file in "/nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications": Read-only file system
The databases in [/nix/store/xfc0ffwz6s87mnz9x2k2qj6ykwxgwjxk-patchelf-0.12/share/applications, /nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/jb5qfmipvsh39342xh68qfmly391b4c8-nautilus-40.1/share/gsettings-schemas/nautilus-40.1/applications, /nix/store/gw5spz9ba90addbi91aax6j454kgz1z2-gnome-terminal-3.40.1/share/gsettings-schemas/gnome-terminal-3.40.1/applications, /nix/store/c67np55z6nc0gaa5siys5sa424xnagvm-shared-mime-info-1.13.1/share/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/6ziw5cj6bik5f8ahqn7kd6w7cvylb981-gnome-keyring-40.0/share/gsettings-schemas/gnome-keyring-40.0/applications, /nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/gsettings-schemas/gcr-3.40.0/applications, /nix/store/71qb38745nnd0gxiq5k680fqvgv7ki8j-mutter-40.1/share/gsettings-schemas/mutter-40.1/applications, /nix/store/183hqhbmzpwjsx2birbq95r9dbijl5nm-evolution-data-server-3.40.2/share/gsettings-schemas/evolution-data-server-3.40.2/applications, /nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/gsettings-schemas/gtk4-4.2.1/applications, /nix/store/4likmbhvxp8r898nqayv297ry080h7ih-gdm-40.0/share/gsettings-schemas/gdm-40.0/applications, /nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/gsettings-schemas/gnome-clocks-40.0/applications, /nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/gsettings-schemas/ibus-1.5.24/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/dr61yrxblp755iax3dxkdv3af7gw2hs5-libgweather-40.0/share/gsettings-schemas/libgweather-40.0/applications, /nix/store/ciq4n4176nw2nv36pn47aa3bp10gcvdi-libnma-1.8.30/share/gsettings-schemas/libnma-1.8.30/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/applications, /nix/store/6p2qz1vcfjjdhrpwqmwdfhycsg94f4j0-cups-2.3.3/share/applications, /nix/store/bl9p90kqm3k9vwivgx22j8lw6rmr2fq8-gcr-3.40.0/share/applications, /nix/store/6rssxfcggjdf5j8wgdj94qxbgcy2n3ck-gtk4-4.2.1/share/applications, /nix/store/9abd6p55w5iplsragm9c3d590dx0jabq-adwaita-icon-theme-40.1.1/share/applications, /nix/store/8kd8w81gwn25h1zjzqq5qwiqjz58841a-hicolor-icon-theme-0.17/share/applications, /nix/store/0f6dpzgmmy9ki6sabfb5h6qmwlj4pyjf-gnome-bluetooth-3.34.5/share/applications, /nix/store/yackllv5bkc0fr13v3h9v5csda23kl61-gnome-clocks-40.0/share/applications, /nix/store/zz9gsga50smszhlpm82npbmlg1ckp4fy-ibus-1.5.24/share/applications, /nix/store/81lhj58b6n6prlm3dw4pxddq0vmczxcz-gnome-mimeapps/share/applications, /nix/store/djgq97g39zrny99lq1y1ivp1qf9jrc8h-desktops/share/applications, /home/mindtree/.nix-profile/share/applications, /etc/profiles/per-user/mindtree/share/applications, /nix/var/nix/profiles/default/share/applications, /run/current-system/sw/share/applications, /nix/store/6q9bhxxny8sascsa67jl1h8gb1yc858v-telepathy-logger-0.8.2/share/gsettings-schemas/telepathy-logger-0.8.2/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/gsettings-schemas/gnome-shell-40.1/applications, /nix/store/cb2bahz19g7j12lfqvyk6pdh6figg9d8-gnome-shell-extensions-40.1/share/gsettings-schemas/gnome-shell-extensions-40.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/applications, /nix/store/29hybgrw0a90zws2xl46dxkz5piwd2b8-gsettings-desktop-schemas-40.0/share/gsettings-schemas/gsettings-desktop-schemas-40.0/applications, /nix/store/xfhxgfv13m6znxkhdvn9kn6gljggfv72-gtk+3-3.24.27/share/gsettings-schemas/gtk+3-3.24.27/applications, /nix/store/0x1adhk6d36faq2czgv0k67v8ajsr6qd-gnome-settings-daemon-40.0.1/share/gsettings-schemas/gnome-settings-daemon-40.0.1/applications, /nix/store/30q3li59cba9j24ibfgmmc2p07p1npkq-gnome-session-40.1.1/share/gsettings-schemas/gnome-session-40.1.1/applications, /nix/store/brj53gzhcpdnaykz8wdvvx5vn0rl5dbg-gnome-shell-40.1/share/applications] could not be updated.
```
</details>

I don't imagine this should be particularly high priority, but I've run into it enough times that I thought I'd open an issue!

### Notify maintainers

GNOME team - @hedning @jtojnar @dasj19 @maxeaubrey sorry to bother! Any thoughts/ideas would be appreciated :)

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.2, NixOS, 21.05.3065.b3083bc6933 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3065.b3083bc6933"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/12757

**Comment by rhysmdnz** [comment]
Fixed by #118100

**Comment by baronleonardo** [comment]
I'm still have the same exact issue on NixOS 22.11, how is this fixed ?!
