### ISSUE TITLE
ycmd fails to work with Atom you-complete-me plugin due to wrapper script

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#14349]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux szamito 3.18.24 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
- System: `15.09.git.45128deM (Dingo)`
- Nix version: `nix-env (Nix) 1.10`
- Nixpkgs version: `"15.09.1177.f8a795e"`
## Describe your issue here

I installed atom and ycmd, and the you-complete-me plugin for Atom, but none of the YCM functionality in Atom seems to work.
### Expected result

It works.
### Actual result

It doesn't.
### Steps to reproduce

`nix-env -i ycmd atom`
Install you-complete-me from Atom's package manager.
Set the ycmd path in the plugin's settings appropriately (`/home/glaebhoerl/.nix-profile/lib/ycmd` in my case)
Open a C/C++ source file, right click on something, try (e.g.) "GoToDeclaration" from the "YouCompleteMe" submenu
(nothing happens)

---

Boilerplate out of the way!

The above commands all say 15.09, but I installed ycmd and atom from the 16.03 beta channel. `atom-1.5.3`, `ycmd-2016-01-12`, you-complete-me plugin is 0.7.4.

Running Atom in Dev Mode, if we try anything from the YouCompleteMe submenu, we see this in the debug console:

![you-complete-me-python](https://cloud.githubusercontent.com/assets/1216629/14189232/7ff23d94-f78c-11e5-80d0-f412800f4c62.png)

Looking at that `__main__.py` file, we see that it contains:

``` bash
#! /nix/store/w6rc026a5kw9zyvvapqq6li157ckvwq7-bash-4.3-p42/bin/bash -e
export PYTHONPATH=/nix/store/9jlki3pyyxxlldsdj2zr2d5y637lfr8r-python2.7-waitress-0.8.9/lib/python2.7/site-packages:/nix/store/jzq8nbp1z182kxz3vyj51p2qki2s1vdq-python2.7-frozendict-0.5/lib/python2.7/site-packages:/nix/store/7h43ls1ixp0s1vhbdjjm44dvdkaggmlk-python2.7-bottle-0.12.8/lib/python2.7/site-packages${PYTHONPATH:+:}$PYTHONPATH
exec -a "$0" /nix/store/f91xrlqmby1sb0c3jsqbycmf19sk4nja-ycmd-2016-01-12/lib/ycmd/ycmd/.__main__.py-wrapped "${extraFlagsArray[@]}" "$@"
```

It's actually a bash script! Which Nix created to setup `PYTHONPATH` before invoking the _real_ `__main__.py` from `ycmd`. And the syntax error is presumably because Atom/YCM are trying to execute it as a python script.

We can verify this by looking at the [source for the you-complete-me plugin](https://github.com/Qusic/atom-youcompleteme/blob/9c856557ff7acc16777bdf782f547777cf7d6b4d/lib/handler.coffee#L60-L64):

``` coffee
  startServer = (optionsFile) -> new Promise (fulfill, reject) ->
    ycmdProcess = new BufferedProcess
      command: atom.config.get 'you-complete-me.pythonExecutable'
      args: [
        path.resolve atom.config.get('you-complete-me.ycmdPath'), 'ycmd'
```

But I'm not sure where or how this should be fixed.

**Comment by jgillich** [comment]
Set the path in the settings to `.__main__.py-wrapped`?

**Comment by glaebhoerl** [comment]
Yeah. I want to use [Rust support](https://github.com/NixOS/nixpkgs/pull/12330#issuecomment-204140243) and that would just mean it won't find `racerd`. Still no good, for me.

It's not reasonable to do something like make the wrapper `__main__.py` actually a Python script instead of Bash?

**Comment by jgillich** [comment]
`makeWrapper` is used for a lot of packages, not just `ycmd`. Duplicating it in Python just for this issue doesn't make much sense I think.

Ideally, you-complete-me would just be calling the executable directly, instead of going through python. Windows however doesn't understand shebags, I guess that's why they're doing it this way.

**Comment by glaebhoerl** [comment]
cc @Qusic

**Comment by glaebhoerl** [comment]
Can anyone at least recommend me a better workaround (that will work together with `racerd`) than, like, installing an Ubuntu VM? On any other OS I could just hack it by editing one of the files in question to make it work, but Nix is not very conducive to that.

**Comment by Qusic** [comment]
I am not familiar with NixOS and here is some of my thoughts after reading the discussion above.
It is not appropriate to replace `__main__.py

From python command line [documentation](https://docs.python.org/3/using/cmdline.html):
> When called with a directory name argument, it reads and executes an appropriately named script from that directory.

**Comment by glaebhoerl** [comment]
So is this a WONTFIX from both sides? As in, wouldn't even accept a patch?

(cc @Ericson2314 just in case you have any ideas, as someone I know in the intersection of the Rust and Nix communities...)

**Comment by jgillich** [comment]
We absolutely should fix this, but I'm not sure how. There's nothing we can do about the wrapper because `PYTHONPATH` absolutely has to be set, and we can't patch you-complete-me either because it's not distributed through nix. cc @domenkozar `buildPythonApplication` also uses a bash wrapper, right?

> And atom-youcompleteme can't execute __main__.py directly without running python command because there is an option for user to choose which python executable to use(useful when multiple versions of python installed).

That's quite ironic, the shell wrapper exists for exactly that purpose, it allows us to use specific versions of dependencies.

**Comment by Ericson2314** [comment]
Heh, we've got ourselves a nice case of polyglotitist here. I have no idea why the nix script is calling a bash script `.py`, that just seems plane wrong. In the spirit of hacks-on-hacks, I'd trick atom/yo into using a no-op "exec args" script as the "python interpreter"/

**Comment by glaebhoerl** [comment]
@Ericson2314 Evil genius! That seems to fix that problem -- the `ycmd` daemon gets started now. It still doesn't work (of *course*), but for some other reason...

**Comment by xwvvvvwx** [comment]
I have the same issue with the vscode ycmd plugin (https://github.com/richard1122/vscode-youcompleteme).

Setting the following as the "python interpreter" as suggested above does not work (instead just moves the error to another one of these bash in python wrappers that is imported somewhere else).

```
#! /usr/bin/env bash

eval exec $2/__main__.py "${@:2}"
```

What can be done here? This bash in python stuff does not feel super robust to me, as clearly the assumption that these scripts will not be executed by the python interpreter does not always hold. 

My first thought would be to simply wrap the bash calls in a `subprocess.call()`? so the script can also be executed as python, or is that horribly naive?

Anyway, super happy to do some work to get this fixed, but really have no idea where to start, so any tips / advice would be very much appreciated :) 

Relevant error logs / code snippets in this gist: https://gist.github.com/xwvvvvwx/bbf8bfe5979a422d7926bd0e802ad33b

**Comment by rasendubi** [comment]
Wow, I have completely missed this discussion. I have written the Nix expression for ycmd, and I only use it with vim/emacs, which do call it as a normal process. That's why wrapping python scripts in bash ones worked fine.

Making a wrapper script written in python seems the best solution for me. It should allow both running it as a python script and as a normal process, too.

**Comment by cstrahan** [comment]
Is there any reason can't just prepend to `PATH` inside the python file when we modify them in `patchPythonScript`, like we currently do to touch up the PYTHONPATH? (see [here](https://github.com/NixOS/nixpkgs/blob/b080748d42d18a3a51e4afacc962d9528ae4200d/pkgs/development/interpreters/python/wrap.sh#L35) and [here](https://github.com/NixOS/nixpkgs/blob/d68aba4cfb5d7998fbd087f7bf6f5d6f9fb5416a/pkgs/development/interpreters/python/wrap-python.nix)). If there isn't a good rationale for it, we could avoid `wrapProgram` (that is, avoid the shell script indirection) and just lean on the `sed` stuff to touch up the environment within the python script itself.

**Comment by cstrahan** [comment]
I'm playing around with fixing this, and I'd think something like this should work:

```diff
diff --git a/pkgs/development/tools/misc/ycmd/default.nix b/pkgs/development/tools/misc/ycmd/default.nix
index 57b4fe99b2..b9c4d4deac 100644
--- a/pkgs/development/tools/misc/ycmd/default.nix
+++ b/pkgs/development/tools/misc/ycmd/default.nix
@@ -3,6 +3,7 @@
 
 let
   inherit (python2Packages) python mkPythonDerivation waitress frozendict bottle;
+  pathFixup =  "import os; os.environ['PATH'] = ('{0}:{1}' if os.getenv('PATH', '') != '' else '{1}').format('$program_PATH', os.getenv('PATH', ''))";
 in mkPythonDerivation rec {
   name = "ycmd-2016-01-12";
   namePrefix = "";
@@ -26,7 +27,19 @@ in mkPythonDerivation rec {
 
   installPhase = ''
     mkdir -p $out/lib/ycmd/third_party $out/bin
+
     cp -r ycmd/ CORE_VERSION libclang.so.* ycm_client_support.so ycm_core.so $out/lib/ycmd/
+  '';
+
+  # Instead of using the wrapper bash script,
+  # use the original python file and setup the PATH there.
+  # We append our code after the segment injected by mkPythonDerivation.
+  # This fixes cases where text editors want to invoke `python __main__.py`,
+  # which would fail if __main__.py is replaced with a wrapper bash script.
+  postFixup = ''
+    mv $out/lib/ycmd/ycmd/{.__main__.py-wrapped,__main__.py}
+    sed -i "/import sys;import site;/a\
+    ${pathFixup}" $out/lib/ycmd/ycmd/__main__.py
     ln -s $out/lib/ycmd/ycmd/__main__.py $out/bin/ycmd
   '';
 

```

**Comment by cstrahan** [comment]
I think #22490 should (mostly) fix this (no more bash wrapper).

Ultimately, I think we should request that these editor plugins also support an option for invoking a command directly, that way we can just point them at `ycmd` (which will already have the appropriate interpreter in the shebang), rather than having to deal with either having the right `python` on `$PATH` or providing a full path to e.g. the nix store path for python 2 (blech).
