### ISSUE TITLE
Unstable channel hasn't updated for 2+ weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#14595]
https://github.com/NixOS/nixpkgs-channels is stuck at 32b7b0009f168cb7e020d297c2f336ef352e9ec1 because, according to https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents, a sizeable portion of our tests fail.

**Comment by domenkozar** [comment]
I've started noticing that kernel fails to find headers (because of parallelism?) https://hydra.nixos.org/build/34437606/nixlog/1/tail-reload

**Comment by domenkozar** [comment]
Arch's been also noticing it: https://aur.archlinux.org/pkgbase/linux-rt/?comments=all

**Comment by obadz** [comment]
Can't find a `prePatch` section that I can hook to but I suspect that adding

```Makefile
$(obj)/qat_asym_algs.o: $(obj)/qat_rsaprivkey-asn1.h $(obj)/qat_rsapubkey-asn1.h
```

to `drivers/crypto/qat/qat_common/Makefile` ought to fix this problem.

**Comment by obadz** [comment]
I was not able to reproduce the error locally but that commit should hopefully fix it. Should I merge it?

**Comment by dezgeg** [comment]
I'd say go for it.

**Comment by obadz** [comment]
Looks like http://hydra.nixos.org/build/34455533 started without picking up my commit, is there a way to cancel & restart?

**Comment by peti** [comment]
@obadz, please don't close this issue until we can be reasonable sure a channel update is going to occur.

**Comment by vcunat** [comment]
I merged staging now, so the situation might change a bit. I didn't want to delay that, as there were a few security fixes contained. (And incidentally there was the closure-size monster as well.)

**Comment by peti** [comment]
> I merged staging now, so the situation might change a bit.

"Might change a bit" is a cute way to put it. :-)

**Comment by vcunat** [comment]
:-) I saw "only" a couple hundred new failures when trying to compare to a similar base, so it's possible that channel blockers won't be really affected.

**Comment by obadz** [comment]
@peti - yes sorry, looks like github closed it automatically based on reference in commit comment

**Comment by dezgeg** [comment]
XFCE test is also failing since 3.4.2016 - http://hydra.nixos.org/build/34020341. I think it has to be the pulseaudio changes.

**Comment by dezgeg** [comment]
64-bit OVA build is failing: http://hydra.nixos.org/build/34515901/nixlog/11/raw

I suppose our mutiple-output multilib gcc is broken, possibly due to this in GCC's builder (being unconditional):
````
ln -s lib "$lib/lib64" # for *.la
````

**Comment by obadz** [comment]
@dezgeg, by pulseaudio do you mean ca3f82e ?

**Comment by dezgeg** [comment]
Yes. Though I previously missed that it could be the dbus change as well (in http://hydra.nixos.org/api/scmdiff?type=git&branch=&rev1=d6998b06744064deb7ed6ea38a062c51638d33bc&rev2=8c6f5ecf8f650af76034bf516392428449814b4d&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git)

**Comment by obadz** [comment]
Confirmed that dbus (83cb6ec399e067b0d111abc39381204d1796758f) is the culprit.

**Comment by domenkozar** [comment]
Let's revert for now. Anything that breaks and is not fixed in timely manner (~1 day) should be just reverted and the committer notified.

**Comment by obadz** [comment]
Done in 079e1c76cfeedbdd0610fc9b50cb9583a330e77e
cc // @peterhoeg

**Comment by obadz** [comment]
With workaround in bf5e339d246714b59ee6ac14d9a76eb39ff1241b, `nix-build '<nixos/release.nix>' -A ova.x86_64-linux` succeeds
See https://github.com/NixOS/patchelf/issues/93

**Comment by dezgeg** [comment]
I still don't think that's the problem but our multilib GCC, like I said in https://github.com/NixOS/nixpkgs/issues/14595#issuecomment-209866424.

In fact, if you try to build `rr` (another `stdenv_32bit` user) the exact same problem is there as well.

**Comment by abbradar** [comment]
Hm, but why does non-`patchelf`ed binary works fine? I've tested it manually in `nix-shell` right after `--shrink-rpath` it breaks (and this shouldn't happen in any conditions).

**Comment by dezgeg** [comment]
I think the underlying problem is that the linker is generating binaries with an RPATH that contains both 32-bit and 64-bit library directories in the first place. Or does it do that before the closure-size merge as well?

**Comment by abbradar** [comment]
That's a good question and may be another bug!

**Comment by vcunat** [comment]
RPATH changes might due to binutils update instead of closure-size changes.

**Comment by dezgeg** [comment]
It's not binutils because bde82098b88861a27faadc8a69b597510e56d846 works fine.

**Comment by joachifm** [comment]
@obadz how did you confirm that dbus was the culprit? The xfce test still fails on `nixpkgs-unstable` with the dbus user service patch reverted.

**Comment by domenkozar** [comment]
Printing test is the last blocker.

**Comment by dezgeg** [comment]
Also of note some closure-size merge related regressions: https://github.com/NixOS/nixpkgs/issues?q=label%3A%226.topic%3A+closure-size%22+label%3A%220.kind%3A+bug%22+is%3Aopen

In particular https://github.com/NixOS/nixpkgs/issues/14682 sounds relatively nasty if it hits the channel.

**Comment by obadz** [comment]
Coming up on 4 weeks without a release. Would have been nice to get `closure-size` pass the full battery of tests before merging.

(FWIW I've been on e5d00a28dd77b1a42b6d1d1da3adeb83f7a47638 and things are working ok)

**Comment by vcunat** [comment]
> Would have been nice to get closure-size pass the full battery of tests before merging.

I would've preferred that, but it turned out to be infeasible. The branch was running for years, and changes on master were continuously breaking it, little by little. There were only a handful of people I managed to get interested enough to contribute to it nontrivially (until it got merged). Therefore on NixCon we agreed to merge it even if not in perfect state, as people have the release as fallback... and since then I even lagged with it a few months longer than planned.

**Comment by obadz** [comment]
@vcunat, ah, fair enough.

**Comment by domenkozar** [comment]
Note that we'll also have to fix https://github.com/NixOS/nixpkgs/issues/14902 before channel will get unblocked

**Comment by vcunat** [comment]
All tests succeed now: http://hydra.nixos.org/build/34939239

**Comment by abbradar** [comment]
Hooray!

We need https://github.com/NixOS/nixpkgs/pull/14953 to be merged before a release, I think. Any other things we can consider blockers?

**Comment by obadz** [comment]
Anyone feel comfortable merging #14339 ? Otherwise this upcoming release is going to feel painful for skype users…

**Comment by abbradar** [comment]
Perhaps you meant #14751?

**Comment by obadz** [comment]
@abbradar, yes my bad.

**Comment by domenkozar** [comment]
@edolstra apparently tested job passed 2 days ago, but still no channel update.

**Comment by vcunat** [comment]
There are still unfinished jobs in those evaluations. One of them even seemed to be running for over two days (!). I don't know why that one didn't time-out or why the others weren't being scheduled, but I just canceled those now.

**Comment by vcunat** [comment]
Updated, exactly after a month. Thanks everyone!
