### ISSUE TITLE
running `nixos-rebuild switch` in fresh virtualbox image bricks the vm by removing demo user

### ISSUE THREAD

**Issue by brainrape** [NixOS/nixpkgs#14970]
## Issue description
Running `nixos-rebuild switch` in a fresh VirtualBox appliance removes the demo user and logs you out, and there is no way to log in.

Apparently, the virtualbox image's active configuration includes https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/demo.nix via https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/virtualbox-demo.nix but it is not present in `/etc/nixos/configuration.nix`. 
It is unexpected that the active configuration does not match `/etc/nixos/configuration.nix`. Worse is that rebuilding bricks the vm.

Suggested solution: add `profiles/demo.nix` to `/etc/nixos/configuration.nix` in the image. Not sure if `nixos-generate-config` is involved. Also, run `nixos-rebuild switch` in the vm before shipping, so that running it on a freshly downloaded image does nothing.

### Steps to reproduce
1. Download VirtualBox appliance, in my case:
http://releases.nixos.org/nixos/16.03/nixos-16.03.616.4ac4b35/nixos-16.03.616.4ac4b35-x86_64-linux.ova
2. Import appliance in virtualbox (I used default settings) and start it
3. log in with user: demo, password: demo
4. run `sudo nixos-rebuild switch`
When it finishes, you are logged out, the demo user is removed, and there is no way to log in.

## Technical details

* System: NixOS 16.03.616.4ac4b35 (Emu)
* Nix version: 1.11.2
* Nixpkgs version: 16.03.616.4ac4b35

**Comment by juh2** [comment]
The error is not fixed in nixos-16.03.714.69420c5-x86_64-linux

Very annoying if you just want to evaluate NixOS.

**Comment by basilevs** [comment]
Demo user is still removed in 16.03.1162

**Comment by brainrape** [comment]
Looks like this is fixed on master in https://github.com/NixOS/nixpkgs/commit/58db7f508f815ac7c1e12e3abd8f7d0fcf25a0cb . I'd like confirmation but I don't know how to build the image. Can someone help me out with a command?
Thanks

**Comment by obadz** [comment]
Duplicate of #13927 

Fixed by 58db7f5

Image can be created with `nix-build '<nixpkgs/nixos/release.nix>' -A ova`

Pls reopen if it turns out I'm wrong.

**Comment by STRML** [comment]
This is still an issue in the latest ova (nixos-16.03.1299.a8e0739).

**Comment by obadz** [comment]
it's fixed in `master` and `16.09` but not `16.03`.

**Comment by STRML** [comment]
Yeah - so the issue is that if you download the 16.03 ova, then upgrade to unstable, you're still toast.
