### ISSUE TITLE
some gtk3 programs crash when using file picker component when on plasma desktop

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#149812]
### Describe the bug

When using a GTK component to choose a file from the filesystem in audacity-gtk3, grsync and zim packages, they have a segmentation fault and stop. This only happen when using plasma desktop, it works fine in Gnome or Xfce desktop (I didn't try other environments).

I tried to use an open file GTK component from foliate, cozy, gimp, pidgin, filezilla, gedit, easytag, geany, gthumb, pcmanfm, claws-mail, deluge, transmission-gtk, remmina, osmo without a crash.

What I see in common for these three packages is they existed in gtk2 flavor before and maybe something in the code is wrong now with gtk3. It may be related to a theme issue, I had a similar issue with some file picker component on another OS which was related to GTK themes.

### Steps To Reproduce

For audacity-gtk3
- log in a plasma desktop
- run audacity-gtk3
- from menu file, click Open
- audacity crashes

This is also reproducible with zim:
- log in a plasma desktop
- open zim
- menu File > Import page
- zim crashes

with grsync:
- log in a plasma desktop
- open grsync
- click on "Open" for source or destination
- it crashes

### Expected behavior

it shouldn't crash

### Additional context

I used gdb to get some extra information for audacity
```
Thread 1 "audacity" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5e56a07 in g_log_structured_array () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff5e56a07 in g_log_structured_array () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#1  0x00007ffff5e56e15 in g_log_default_handler () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#2  0x00007ffff5e5705e in g_logv () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#3  0x00007ffff5e5730f in g_log () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#4  0x00007ffff6083cfa in g_settings_set_property () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgio-2.0.so.0
#5  0x00007ffff5f4b9b6 in object_set_property () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#6  0x00007ffff5f4bd6c in g_object_new_internal () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#7  0x00007ffff5f4d688 in g_object_new_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#8  0x00007ffff5f4dbb9 in g_object_new () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#9  0x00007ffff66f546c in _gtk_file_chooser_get_settings_for_widget () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#10 0x00007ffff66f6460 in gtk_file_chooser_widget_get_default_size () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#11 0x00007ffff66f09d6 in file_chooser_widget_default_size_changed () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#12 0x00007ffff5f4664f in g_closure_invoke () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#13 0x00007ffff5f5837b in signal_emit_unlocked_R.isra.0 () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#14 0x00007ffff5f5ea5f in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#15 0x00007ffff5f5f1df in g_signal_emit_by_name () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#16 0x00007ffff5f46879 in _g_closure_invoke_va () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#17 0x00007ffff5f5ed2b in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#18 0x00007ffff5f5efbf in g_signal_emit () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#19 0x00007ffff5f46879 in _g_closure_invoke_va () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#20 0x00007ffff5f5ed2b in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#21 0x00007ffff5f5efbf in g_signal_emit () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#22 0x00007ffff68167f5 in gtk_style_context_validate () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#23 0x00007ffff66c6f89 in gtk_css_widget_node_validate () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#24 0x00007ffff66aa44a in gtk_css_node_validate_internal.part () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#25 0x00007ffff66aa47b in gtk_css_node_validate_internal.part () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#26 0x00007ffff66aa47b in gtk_css_node_validate_internal.part () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#27 0x00007ffff68d0e76 in gtk_window_show () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#28 0x00007ffff5f4664f in g_closure_invoke () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#29 0x00007ffff5f58011 in signal_emit_unlocked_R.isra.0 () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#30 0x00007ffff5f5ea5f in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#31 0x00007ffff5f5efbf in g_signal_emit () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#32 0x00007ffff68bd386 in gtk_widget_show () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#33 0x00007ffff7819105 in wxWindow::Show(bool) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#34 0x00007ffff780240c in wxTopLevelWindowGTK::Show(bool) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#35 0x00007ffff785684c in wxDialog::Show(bool) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#36 0x00007ffff7856abb in wxDialog::ShowModal() () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#37 0x0000000001009a37 in FileDialog::ShowModal() ()
#38 0x0000000000a1624b in ProjectFileManager::ShowOpenDialog(FileNames::Operation, FileNames::FileType const&) ()
#39 0x0000000000a2a5f5 in ProjectManager::OpenFiles(AudacityProject*) ()
#40 0x0000000000b3d7e4 in CommandManager::HandleCommandEntry(AudacityProject&, CommandListEntry const*, std::bitset<64ul>, bool, wxEvent const*) ()
#41 0x0000000000b43b38 in CommandManager::HandleMenuID(AudacityProject&, int, std::bitset<64ul>, bool) ()
#42 0x0000000000a3951c in ProjectWindow::OnMenu(wxCommandEvent&) ()
#43 0x00007ffff7ecd11e in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#44 0x00007ffff7ecd293 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#45 0x00007ffff7ecd949 in wxEvtHandler::TryHereOnly(wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#46 0x00007ffff7ecd3a3 in wxEvtHandler::DoTryChain(wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#47 0x00007ffff7ecdad1 in wxEvtHandler::ProcessEvent(wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#48 0x00007ffff79de6ca in wxWindowBase::TryAfter(wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#49 0x00007ffff7ecf4a7 in wxEvtHandler::SafelyProcessEvent(wxEvent&) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#50 0x00007ffff798f390 in wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#51 0x00007ffff798f5f8 in wxMenuBase::SendEvent(int, int) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#52 0x00007ffff786991f in menuitem_activate () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#53 0x00007ffff5f4664f in g_closure_invoke () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#54 0x00007ffff5f5837b in signal_emit_unlocked_R.isra.0 () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#55 0x00007ffff5f5ea5f in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#56 0x00007ffff5f5efbf in g_signal_emit () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#57 0x00007ffff68b6964 in gtk_widget_activate () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#58 0x00007ffff677bbf6 in gtk_menu_shell_activate_item () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#59 0x00007ffff677bed3 in gtk_menu_shell_button_release () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#60 0x00007ffff66099f4 in _gtk_marshal_BOOLEAN__BOXEDv () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#61 0x00007ffff5f46879 in _g_closure_invoke_va () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#62 0x00007ffff5f5e184 in g_signal_emit_valist () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#63 0x00007ffff5f5efbf in g_signal_emit () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libgobject-2.0.so.0
#64 0x00007ffff68b3ba4 in gtk_widget_event_internal.part () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#65 0x00007ffff67665e0 in propagate_event () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#66 0x00007ffff67681e3 in gtk_main_do_event () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#67 0x00007ffff64a2b15 in _gdk_event_emit () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgdk-3.so.0
#68 0x00007ffff64f8b82 in gdk_event_source_dispatch () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#69 0x00007ffff5e4faab in g_main_context_dispatch () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#70 0x00007ffff5e4fd58 in g_main_context_iterate.constprop () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#71 0x00007ffff5e5004b in g_main_loop_run () from /nix/store/mbgcj6maiy41m0hacf1pw5nw56m3wn3q-glib-2.70.1/lib/libglib-2.0.so.0
#72 0x00007ffff6767235 in gtk_main () from /nix/store/g2xxryy86xk29p8dgxggzz1q3qb1bhcm-gtk+3-3.24.30/lib/libgtk-3.so.0
#73 0x00007ffff77eb405 in wxGUIEventLoop::DoRun() () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_gtk3u_core-3.1.so.3
#74 0x00007ffff7da519d in wxEventLoopBase::Run() () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#75 0x00007ffff7d711f5 in wxAppConsoleBase::MainLoop() () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#76 0x00007ffff7deb116 in wxEntry(int&, wchar_t**) () from /nix/store/mx61hhxa744gj6ha9dwp2grw9fjmf12s-wxwidgets-3.1.4/lib/libwx_baseu-3.1.so.3
#77 0x00000000007ec7a6 in main ()
```

### Notify maintainers

@lheckemann (audacity), @pSub (zim), @kuznero (grsync)

### Metadata

I'm using 21.11-small but problem also occurs on 21.11

```console
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334201.3b1e4c3cf2a"`
 - channels(solene): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by K900** [comment]
Possibly related? https://github.com/NixOS/nixpkgs/issues/140909

**Comment by rapenne-s** [comment]
> Possibly related? #140909

I can't trigger the firefox issue but I used to gnome and xfce in the past so my HOME isn't entirely clean. Maybe it would fail on a fresh plasma profile. Some tests should be done on a clean user, I'll try if I find some time.

**Comment by K900** [comment]
The Firefox issue seems to have resolved itself on unstable, and I also can't reproduce other things crashing on unstable now...

**Comment by rapenne-s** [comment]
> The Firefox issue seems to have resolved itself on unstable, and I also can't reproduce other things crashing on unstable now...

I tried on a fresh 21.11 user with plasma and I can't reproduce the Firefox crash.

I'll try upgrading to unstable to see if I can trigger the crash.

**Comment by rapenne-s** [comment]
I booted on a nixos-unstable environment with plasma desktop on my new user.

- firefox works
- audacity-gtk3 crashes
- zim crashes
- grsync crashes

**Comment by unclechu** [comment]
For me it’s Qt applications crashing when I try to open File Dialog. I’m using NixOS 21.11 (there was no such bug in 21.05), i3wm, Adwaita Dark system theme, and adwaita-qt. For example **audacious** and **qtcreator** are crashing with these errors:

> (qtcreator:31572): GLib-GIO-ERROR **: 16:18:25.686: No GSettings schemas are installed on the system

> (.audacious-wrapped:39675): GLib-GIO-ERROR **: 16:20:43.314: No GSettings schemas are installed on the system

But not always. If I just reboot and try to open a file dialog in audacious it works. Until some point, don’t know at what moment it breaks.

**Comment by rapenne-s** [comment]
> For me it’s Qt applications crashing when I try to open File Dialog. I’m using NixOS 21.11 (there was no such bug in 21.05), i3wm, Adwaita Dark system theme, and adwaita-qt. For example **audacious** and **qtcreator** are crashing with these errors:
> 
> > (qtcreator:31572): GLib-GIO-ERROR **: 16:18:25.686: No GSettings schemas are installed on the system
> 
> > (.audacious-wrapped:39675): GLib-GIO-ERROR **: 16:20:43.314: No GSettings schemas are installed on the system
> 
> But not always. If I just reboot and try to open a file dialog in audacious it works. Until some point, don’t know at what moment it breaks.

This seems an entirely different issue

**Comment by vs49688** [comment]
Have just hit this issue with `mednaffe` and `gramps`, am running Plasma on `21.11.334247.573095944e7`
```
$ mednaffe 
[23:36:52] Starting Mednaffe 0.9.1
[23:36:52] Joystick found: ID: 0x0005054c09cc81000008000d00000000 - Wireless Controller

(mednaffe:84401): GLib-GIO-ERROR **: 23:36:54.464: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)

$ gramps 
2021-12-16 23:37:43.442: WARNING: grampsgui.py: line 538: GTK translations missing, GUI will be broken, especially for RTL languages!
2021-12-16 23:37:45.197: WARNING: dummydb.py: line 1420: database is closed

(.gramps-wrapped:84564): GLib-GIO-ERROR **: 23:38:00.628: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

Not sure if related, but gramps spits out:
![grampserror](https://user-images.githubusercontent.com/4423262/146382450-8a152aaf-0709-48a9-8a1f-f2bbb6aa4f7e.png)
Did the same when I used `LANG=en_US.UTF-8 LANGUAGE=en_US`.

**Comment by niknetniko** [comment]
At least for Gramps, I was able to fix it locally by applying `strictDeps = false` to the `buildPythonApplication` instructions.

**Comment by ThibaultLemaire** [comment]
For gramps at least, for most (if not all) dialogs, you can get around by dragging and dropping files from the file manager, or pasting a path you've copied from elsewhere.

**Comment by thiagokokada** [comment]
This is also happening for me on i3wm, so this issue is more universal than it seems.

Someone already workaround this on its own package: https://github.com/NixOS/nixpkgs/issues/142014. However I think this should be fixed on `wrapGAppsHook` itself.

See also some discussion in https://github.com/NixOS/nixpkgs/pull/153364.

Pinging @NixOS/gnome.

**Comment by jtojnar** [comment]
GTK file chooser requires a directory containing certain GSettings schemas (`${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas}`) in `$XDG_DATA_DIRS` environment variable. Without it, the app will crash when file chooser is opened.

Every GTK app should have that set in a wrapper by `wrapGAppsHook`, which every GTK app should use but sometimes the maintainer does not add `wrapGAppsHook` to dependencies – perhaps the [docs](https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome) are not clear enough?

Even if `wrapGAppsHook` is included, the setup hook might misbehave when the package has `strictDeps` enabled. Note that `strictDeps` are on by default for packages built with `buildPythonPackage` and `buildRustPackage`.

Finally, Qt uses GTK file chooser in some desktop environments, which basically requires all Qt apps to use `wrapGAppsHook` too to avoid crashing. The alternative would be [hardcoding](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-unwrappable-package-gsettings-c) the schema path in GTK, which would prevent unwrapped apps from crashing but they might still be rendered improperly since the wrapper is also needed for rendering SVG icons by GTK.

**Comment by thiagokokada** [comment]
> 

In #153364 I am using the `wrapGAppsHook`, and it does not set `strictDeps`, however I still am having issues.

Adding `--prefix XDG_DATA_DIRS : ${gsettings-desktop-schemas}/share/gsettings-schemas/${gsettings-desktop-schemas.name}` to `gappsWrapperArgs` didn't work (it changes the error to "Settings schema 'org.gtk.Settings.FileChooser' is not installed" though), however adding `--prefix XDG_DATA_DIRS : ${gtk3}/share/gsettings-schemas/${gtk3.name}` did the trick. Setting both also fails with "Settings schema 'org.gtk.Settings.FileChooser' is not installed" error.

Maybe I understand it wrong, but it doesn't seem to be working as it should.

**Comment by jtojnar** [comment]
@thiagokokada you are right, I misremembered, it is indeed the GTK schema which is required. However, including both should work too as `XDG_DATA_DIRS` is traversed for each schema and GNOME apps frequently rely on schemas from multiple packages.

**Comment by rapenne-s** [comment]
`czkawka_gui` from `czkawka` package is also failing

```
(czkawka_gui:11159): GLib-GIO-ERROR **: 12:25:26.737: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

**Comment by rapenne-s** [comment]
minigalaxy fixed by #169919

**Comment by unclechu** [comment]
After upgrading to 22.05 the bug is still there. After pressing “add files” in Audacious this printed to the log and the app crashes:

> (.audacious-wrapped:10657): GLib-GIO-ERROR **: 23:47:29.112: No GSettings schemas are installed on the system  
> Trace/breakpoint trap (core dumped)

For instance Carla also crashes when I press anything that invokes file picker:

``` console
$ nix-shell -p carla --run carla
Carla 2.4.3 started, status:
  Python version: 3.9.12
  Qt version:     5.15.3
  PyQt version:   5.15.4
  Binary dir:     /nix/store/hsb2j6s5rdk9gg7bq0ipikh6j69p0di7-carla-2.4.3/lib/carla
  Resources dir:  /nix/store/hsb2j6s5rdk9gg7bq0ipikh6j69p0di7-carla-2.4.3/share/carla/resources
Frontend pixel ratio is 1.0
libjack.so.0 loaded successfully!
[carla] No device set, using 2 inputs and 2 outputs
/tmp/nix-shell-12924-0/rc: line 3: 14969 Trace/breakpoint trap   (core dumped) carla
```

**Comment by unclechu** [comment]
I managed to fix Audacious by doing this (Nix Shell config):

``` nix
{ pkgs ? import <nixpkgs> {}
}:

let
  audacious = pkgs.symlinkJoin {
    name = "${pkgs.lib.getName pkgs.audacious}-wrapper";
    nativeBuildInputs = [ pkgs.makeWrapper ];
    buildInputs = [ pkgs.gtk3 ];
    paths = [ pkgs.audacious ];
    postBuild = ''
      wrapProgram "$out"/bin/audacious \
        --prefix XDG_DATA_DIRS : "$GSETTINGS_SCHEMAS_PATH"
    '';
  };
in

pkgs.mkShell {
  buildInputs = [
    audacious
  ];
}
```

**Comment by unclechu** [comment]
Works for Carla as well:

``` nix
{ pkgs ? import <nixpkgs> {}
}:

let
  carla = pkgs.symlinkJoin {
    name = "${pkgs.lib.getName pkgs.carla}-wrapper";
    nativeBuildInputs = [ pkgs.makeWrapper ];
    buildInputs = [ pkgs.gtk3 ];
    paths = [ pkgs.carla ];
    postBuild = ''
      wrapProgram "$out"/bin/carla \
        --prefix XDG_DATA_DIRS : "$GSETTINGS_SCHEMAS_PATH"
    '';
  };
in

pkgs.mkShell {
  buildInputs = [
    carla
  ];
}
```

**Comment by unclechu** [comment]
Fixed this issue with Qt application by applying this hack to NixOS configuration:

``` nix
{ pkgs, lib, ...  }:
let
  missing-gsettings-schemas-fix = builtins.readFile "${pkgs.stdenv.mkDerivation {
    name = "missing-gsettings-schemas-fix";
    dontUnpack = true; # Make it buildable without “src” attribute
    buildInputs = [ pkgs.gtk3 ];
    installPhase = '' printf %s "$GSETTINGS_SCHEMAS_PATH" > "$out" '';
  }}";
in
{
  # Fix for “No GSettings schemas are installed on the system” error
  # that causes Qt application to crash when opening file picker dialog window.
  environment.sessionVariables.XDG_DATA_DIRS = lib.mkAfter [ "${missing-gsettings-schemas-fix}" ];
}
```

**Comment by rapenne-s** [comment]
It would be nice to solve this in nixpkgs itself. The problem still exists.

**Comment by gvolpe** [comment]
First time I bumped into this issue (surprisingly) while running `nautilus`:

```console
$ nautilus
(org.gnome.Nautilus:141313): GLib-GIO-ERROR **: 15:34:21.237: Settings schema 'org.gtk.Settings.FileChooser' is not installed
fish: Job 1, 'nautilus' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

Wrapping the program with `GSETTINGS_SCHEMAS_PATH` in `XDG_DATA_DIRS` works but it is extremely slow, seems malfunctioning... Another rabbit hole to dig in 🥲

**Comment by slenderq** [comment]
> Fixed this issue with Qt application by applying this hack to NixOS configuration:
> 
> ```nix
> { pkgs, lib, ...  }:
> let
>   missing-gsettings-schemas-fix = builtins.readFile "${pkgs.stdenv.mkDerivation {
>     name = "missing-gsettings-schemas-fix";
>     dontUnpack = true; # Make it buildable without “src” attribute
>     buildInputs = [ pkgs.gtk3 ];
>     installPhase = '' printf %s "$GSETTINGS_SCHEMAS_PATH" > "$out" '';
>   }}";
> in
> {
>   # Fix for “No GSettings schemas are installed on the system” error
>   # that causes Qt application to crash when opening file picker dialog window.
>   environment.sessionVariables.XDG_DATA_DIRS = lib.mkAfter [ "${missing-gsettings-schemas-fix}" ];
> }
> ```

This fixed the "GSettings schema" errors that I was in getting in the sooperlooper package. 
It seems this affects a bunch of different packages?

**Comment by K900** [comment]
That just means that package needs `wrapGAppsHook` added.

**Comment by 573** [comment]
Reproducible with simple-scan:

* Run Lxde-Desktop
* Scan something with simple-scan
* Click `save`

File picker is shown and crashes with simple-scan.

**Comment by jtojnar** [comment]
simple-scan is properly wrapped so that must be some other issue.

**Comment by jqueuniet** [comment]
I'm also having this issue with the `basiliskii` package. The workaround of settings XDG_DATA_DIRS for the whole session solves it for now.
