### ISSUE TITLE
Nixops package fails to install on 21.11

### ISSUE THREAD

**Issue by ivanovsaleksejs** [NixOS/nixpkgs#149836]
### Describe the bug
When upgrading to 21.11 I've got an error which was quite ambiguous: 
`flake8-4.0.1 not supported for interpreter python2.7`
I tried to remove packages one by one and figured out that the error is caused by nixops package. I've replaced nixops with the one from 21.05 tarball and was able to upgrade.

### Steps To Reproduce
1. Have a 21.05 build with nixops installed.
2. Add 21.11 channel and run rebuild.
3. Rebuild fails with the error above.

### Expected behavior
A 21.05 build with nixops installed should be upgradable without any problem.

### Metadata
``` 
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.4438.5854a24cfcc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334139.1bd4bbd49be, nixos-unstable-21.11pre294109.fbfb79400a0"`
 - channels(aleksejs): `"nixos-21.11pre291991.ea7d4aa9b82, nixos-20.03-20.03.3328.6d1a044fc9f, nixos-unstable-21.11pre291991.ea7d4aa9b82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by M-Gregoire** [comment]
I can confirm this issue as I have encountered the same bug.

**Comment by dotlambda** [comment]
This was already fixed, `nixops` builds just fine in `release-21.11`.

**Comment by rprije** [comment]
I just tried the release at https://releases.nixos.org/nixos/21.11/nixos-21.11.334247.573095944e7 and it still fails with this error. Is there a fresher place to get the latest release update than https://nixos.org/channels/nixos-21.11 ?

For avoidance of doubt, this is a different error to #147049 which has left nixops broken for the past few weeks.

**Comment by ivanovsaleksejs** [comment]
It's still not fixed, same error:
`error: flake8-4.0.1 not supported for interpreter python2.7`

**Comment by dotlambda** [comment]
The channel hasn't advanced yet, but the next time it does (check https://status.nixos.org/) it will be fixed in `nixos-21.11` as well.
We can keep this open until then.

**Comment by yshui** [comment]
There are more packages with this problem, e.g. `nix-shell -p pythonPackages.pyside`

I am on nixpkgs-unstable.

**Comment by dotlambda** [comment]
@yshui Python 2 reached its end of life on January 1, 2020. Use `python3Packages.pyside`.

**Comment by dotlambda** [comment]
`nixops` now builds just fine on `nixos-21.11`
