### ISSUE TITLE
Losing audio on the host when VirtualBox is installed

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#15005]
## Issue description

When I enable `virtualisation.virtualbox.host.enable = true;` I reliably lose the sound on next reboot. Switching to the previous generation restores the sound again.

```
$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 30
Server Protocol Version: 30
Is Local: yes
Client Index: 30
Tile Size: 65472
User Name: zimbatm
Host Name: xps13
Server Name: pulseaudio
Server Version: 8.0-rebootstrapped
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: auto_null
Default Source: auto_null.monitor
Cookie: 9a4a:e597
```

I think it might be due to the udev triggers that are being installed but I don't really know. Looking for some clues on how to dig this further.
## Technical details
- System: `16.09pre79453.32b7b00 (Flounder)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.09pre79453.32b7b00`

**Comment by dvc94ch** [comment]
+1

**Comment by NotaseCretagen** [comment]
Does it work if you plug in headphones?

**Comment by yawnt** [comment]
+1 me too

**Comment by zimbatm** [comment]
Here is the diff of `lsmod`:
```diff
--- broken/lsmod.sorted	2016-05-21 11:16:36.271596859 +0100
+++ working/lsmod.sorted	2016-05-21 11:16:42.487651429 +0100
@@ -32,6 +32,7 @@
 cryptd                  8714  3 aesni_intel,ablk_helper
 dcdbas                  5639  1 dell_laptop
 dell_laptop            14492  0
+dell_led                2708  1
 dell_wmi                2434  0
 dm_crypt               18570  1
 dm_mod                 88592  3 dm_crypt
@@ -58,7 +59,7 @@
 i2c_designware_platform     4178  0
 i2c_hid                11523  0
 i8042                  14260  2 libps2,dell_laptop
-i915                 1120694  8
+i915                 1120694  9
 idma64                  7024  0
 industrialio           39089  2 acpi_als,kfifo_buf
 input_leds              3086  0
@@ -81,14 +82,14 @@
 iptable_raw             1516  1
 ip_tables              16280  2 iptable_filter,iptable_raw
 ipt_rpfilter            2036  1
-ipv6                  322848  39 ip6t_rpfilter,nf_defrag_ipv6,nf_conntrack_ipv6
+ipv6                  322848  55 ip6t_rpfilter,nf_defrag_ipv6,nf_conntrack_ipv6
 irqbypass               2872  1 kvm
 jbd2                   79947  1 ext4
 joydev                 10215  0
 kfifo_buf               2935  1 acpi_als
 kvm                   441701  1 kvm_intel
 kvm_intel             157008  0
-led_class               4231  2 dell_laptop,input_leds
+led_class               4231  3 dell_led,dell_laptop,input_leds
 libahci                22013  1 ahci
 libata                185794  2 ahci,libahci
 libps2                  4547  1 atkbd
@@ -131,12 +132,14 @@
 serio_raw               4785  0
 shpchp                 24402  0
 slhc                    5555  1 ppp_generic
-snd                    59380  9 snd_pcm_oss,snd_soc_core,snd_hwdep,snd_timer,snd_pcm,snd_hda_codec,snd_hda_intel,snd_compress,snd_mixer_oss
+snd                    59380  17 snd_hda_codec_realtek,snd_pcm_oss,snd_soc_core,snd_hwdep,snd_timer,snd_pcm,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_compress,snd_mixer_oss
 snd_compress            7211  1 snd_soc_core
-snd_hda_codec          85254  1 snd_hda_intel
-snd_hda_core           39531  4 snd_hda_ext_core,snd_hda_codec,snd_hda_intel,snd_soc_skl
+snd_hda_codec          85254  3 snd_hda_codec_realtek,snd_hda_codec_generic,snd_hda_intel
+snd_hda_codec_generic    55618  1 snd_hda_codec_realtek
+snd_hda_codec_realtek    58813  1
+snd_hda_core           39531  6 snd_hda_codec_realtek,snd_hda_ext_core,snd_hda_codec_generic,snd_hda_codec,snd_hda_intel,snd_soc_skl
 snd_hda_ext_core        9547  1 snd_soc_skl
-snd_hda_intel          24101  0
+snd_hda_intel          24101  3
 snd_hwdep               6186  1 snd_hda_codec
 snd_mixer_oss          14190  1 snd_pcm_oss
 snd_pcm                80588  8 snd_pcm_oss,snd_hda_ext_core,snd_soc_core,snd_hda_codec,snd_hda_intel,snd_soc_skl,snd_pcm_dmaengine,snd_hda_core
@@ -162,9 +165,6 @@
 usbhid                 36972  0
 uvcvideo               74695  0
 v4l2_common             3790  1 videobuf2_v4l2
-vboxdrv               372610  2 vboxnetadp,vboxnetflt
-vboxnetadp             19156  0
-vboxnetflt             18878  0
 vfat                   10415  1
 video                  25160  3 i915,dell_wmi,dell_laptop
 videobuf2_core         20349  2 uvcvideo,videobuf2_v4l2
@@ -173,7 +173,7 @@
 videobuf2_vmalloc       5030  1 uvcvideo
 videodev              133453  4 uvcvideo,v4l2_common,videobuf2_core,videobuf2_v4l2
 virt_dma                2020  1 idma64
-wmi                     7778  1 dell_wmi
+wmi                     7778  2 dell_led,dell_wmi
 x86_pkg_temp_thermal     5253  0
 xhci_hcd              112156  1 xhci_pci
 xhci_pci                4522  0
```

Loading snd_hda_codec_realtek and restarting my session restores the audio

**Comment by zimbatm** [comment]
So I can add this to the boot.kernelModules array and it should fix the problem (and the `dell_led`). I think the issue is the `/etc/modules-load.d/nixos.conf` load order:
```
kvm-intel
vboxdrv
vboxnetadp
vboxnetflt
ipv6
cpufreq_ondemand
loop
atkbd
ppp_mppe
nf_conntrack_ftp
tun
snd_pcm_oss
```

**Comment by yawnt** [comment]
so basically if i understand correctly we should fix the order in here ?
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/virtualbox-host.nix#L53

**Comment by zimbatm** [comment]
I changed the order with the following change but it doesn't fix the problem for me. It must be something else.
```
diff --git a/nixos/modules/virtualisation/virtualbox-host.nix b/nixos/modules/virtualisation/virtualbox-host.nix
index 5fb472e..6c22558 100644
--- a/nixos/modules/virtualisation/virtualbox-host.nix
+++ b/nixos/modules/virtualisation/virtualbox-host.nix
@@ -50,7 +50,7 @@ in
   };
 
   config = mkIf cfg.enable (mkMerge [{
-    boot.kernelModules = [ "vboxdrv" "vboxnetadp" "vboxnetflt" ];
+    boot.kernelModules = mkAfter [ "vboxdrv" "vboxnetadp" "vboxnetflt" ];
     boot.extraModulePackages = [ virtualbox ];
     environment.systemPackages = [ virtualbox ];
 
```

```
$ cat /etc/modules-load.d/nixos.conf
kvm-intel
ipv6
cpufreq_ondemand
loop
atkbd
ppp_mppe
nf_conntrack_ftp
tun
snd_pcm_oss
vboxdrv
vboxnetadp
vboxnetflt
```

**Comment by zimbatm** [comment]
during boot I am also seeing this backtrace:
```
[    8.893508] ------------[ cut here ]------------
[    8.893515] WARNING: CPU: 3 PID: 630 at /tmp/nix-build-linux-4.4.10.drv-0/linux-4.4.10/kernel/memremap.c:65 memremap+0x9f/0x110()
[    8.893517] memremap attempted on mixed range 0x0000000000000000 size: 0x0
[    8.893518] Modules linked in: brcmutil btusb cfg80211 snd_soc_skl(+) btrtl btbcm snd_soc_skl_ipc btintel efivars(+) pstore zlib_deflate snd_soc_sst_ipc snd_soc_sst_dsp bluetooth dw_dmac_core snd_hda_ext_core snd_hda_core rtsx_pci_ms memstick rfkill snd_soc_core drm_kms_helper snd_compress ac97_bus snd_pcm_dmaengine drm idma64 virt_dma shpchp i2c_algo_bit syscopyarea mei_me sysfillrect sysimgblt fb_sys_fops mei intel_lpss_pci fan processor_thermal_device thermal intel_soc_dts_iosf iosf_mbi wmi i2c_hid snd_pcm_oss i2c_core snd_mixer_oss snd_pcm snd_timer snd pinctrl_sunrisepoint int3403_thermal pinctrl_intel soundcore int340x_thermal_zone video intel_lpss_acpi intel_lpss int3400_thermal tpm_tis button acpi_als tun kfifo_buf acpi_pad battery acpi_thermal_rel fjes tpm industrialio nf_conntrack_ftp ac
[    8.893555]  nf_conntrack processor arc4 ecb ppp_mppe ppp_generic slhc loop cpufreq_ondemand vboxnetflt(O) vboxnetadp(O) vboxdrv(O) kvm_intel kvm irqbypass efivarfs ip_tables x_tables ipv6 autofs4 ext4 crc16 mbcache jbd2 dm_crypt usbhid hid ahci libahci libata scsi_mod xhci_pci rtsx_pci_sdmmc xhci_hcd mmc_core atkbd usbcore libps2 aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd crc32c_intel nvme rtsx_pci usb_common rtc_cmos i8042 serio intel_agp intel_gtt agpgart dm_mod
[    8.893584] CPU: 3 PID: 630 Comm: systemd-udevd Tainted: G           O    4.4.10 #1-NixOS
[    8.893586] Hardware name: Dell Inc. XPS 13 9350/0VM5NC, BIOS 1.3.3 03/01/2016
[    8.893587]  0000000000000000 ffff8804660b79e0 ffffffff812bfbee ffff8804660b7a28
[    8.893590]  ffffffff81720fc0 ffff8804660b7a18 ffffffff8106e5b2 0000000000000000
[    8.893592]  0000000000000001 000000000000000f 0000000000000009 ffffffffa0befec0
[    8.893597] Call Trace:
[    8.893603]  [<ffffffff812bfbee>] dump_stack+0x63/0x85
[    8.893607]  [<ffffffff8106e5b2>] warn_slowpath_common+0x82/0xc0
[    8.893610]  [<ffffffff8106e63c>] warn_slowpath_fmt+0x4c/0x50
[    8.893614]  [<ffffffff81353bff>] ? acpi_evaluate_object+0x222/0x234
[    8.893616]  [<ffffffff8115187f>] memremap+0x9f/0x110
[    8.893621]  [<ffffffffa0bec844>] skl_nhlt_init+0x64/0xa0 [snd_soc_skl]
[    8.893624]  [<ffffffffa0beb602>] skl_probe+0x252/0x5c0 [snd_soc_skl]
[    8.893627]  [<ffffffff812fd4c5>] local_pci_probe+0x45/0xa0
[    8.893630]  [<ffffffff81235a99>] ? sysfs_do_create_link_sd.isra.2+0x69/0xb0
[    8.893632]  [<ffffffff812fe89b>] pci_device_probe+0xdb/0x130
[    8.893635]  [<ffffffff813cb0c7>] driver_probe_device+0x1f7/0x310
[    8.893637]  [<ffffffff813cb264>] __driver_attach+0x84/0x90
[    8.893639]  [<ffffffff813cb1e0>] ? driver_probe_device+0x310/0x310
[    8.893641]  [<ffffffff813c9174>] bus_for_each_dev+0x64/0xa0
[    8.893643]  [<ffffffff813ca98e>] driver_attach+0x1e/0x20
[    8.893645]  [<ffffffff813ca5c1>] bus_add_driver+0x1b1/0x220
[    8.893647]  [<ffffffffa0bf2000>] ? 0xffffffffa0bf2000
[    8.893649]  [<ffffffff813cbaf0>] driver_register+0x60/0xe0
[    8.893652]  [<ffffffff812fce2c>] __pci_register_driver+0x4c/0x50
[    8.893656]  [<ffffffffa0bf201e>] skl_driver_init+0x1e/0x20 [snd_soc_skl]
[    8.893659]  [<ffffffff81002109>] do_one_initcall+0x99/0x1e0
[    8.893662]  [<ffffffff811a7fa8>] ? kmem_cache_alloc_trace+0x38/0x150
[    8.893664]  [<ffffffff81152096>] do_init_module+0x5f/0x1c3
[    8.893668]  [<ffffffff810e37ff>] load_module+0x1f5f/0x2370
[    8.893670]  [<ffffffff810e0320>] ? __symbol_put+0x50/0x50
[    8.893674]  [<ffffffff810e3d23>] SYSC_init_module+0x113/0x130
[    8.893676]  [<ffffffff810e3dee>] SyS_init_module+0xe/0x10
[    8.893679]  [<ffffffff814ef9ee>] entry_SYSCALL_64_fastpath+0x12/0x6d
[    8.893692] ---[ end trace 05762e63115a0023 ]---
```

**Comment by zimbatm** [comment]
One piece of info that's missing. Can you all give your output for `uname -a` ?

> Linux xps13 4.4.11 #1-NixOS SMP Thu May 19 00:08:36 UTC 2016 x86_64 GNU/Linux

**Comment by zimbatm** [comment]
5.5 has the same issue

**Comment by yawnt** [comment]
`Linux ehecatl 4.4.10 #1-NixOS SMP Wed May 11 09:23:26 UTC 2016 x86_64 GNU/Linux`

thanks for looking into this!!!

**Comment by dvc94ch** [comment]
Linux xps 4.4.11 #1-NixOS SMP Thu May 19 00:08:36 UTC 2016 x86_64 GNU/Linux

**Comment by zimbatm** [comment]
Well I ran out of ideas again. 4.5 and 4.6 also have the same issue, 4.6 even has two backtraces instead of one.

Can you maybe give me your `lsmod` and computer model to see if there are any commonalities ?

**Comment by yawnt** [comment]
http://sprunge.us/DEWK

here is my lsmod :)

**Comment by dvc94ch** [comment]
http://sprunge.us/HIFT

sprunge.us is pretty cool, didn't know it...

**Comment by zimbatm** [comment]
Interesting, we all have the `snd_hda_codec_realtek` module

**Comment by zimbatm** [comment]
And I've got a Dell XPS13. Mind pasting the lspci output as well ?

`lspci`: http://sprunge.us/eEGY

**Comment by yawnt** [comment]
lspci: http://sprunge.us/LCPC

**Comment by dvc94ch** [comment]
* model: Dell XPS13
* lspci: http://sprunge.us/SCUb
* lsmod: http://sprunge.us/HIFT

**Comment by zimbatm** [comment]
So @dvc94ch and me both have the same model and we all have a Skylake architecture

**Comment by dvc94ch** [comment]
Nice! What's the saying? Great minds think alike =P On the other hand there aren't too many alternatives with recent hardware that I'm aware of, so I guess it's not uncommon for linux users to have a xps...

**Comment by martijnvermaat** [comment]
- Model: Lenovo ThinkPad Carbon X1 (4th gen, Skylake)
- lsmod without VirtualBox: http://sprunge.us/SAfi
- lsmod with VirtualBox: http://sprunge.us/DchP
- lspci: http://sprunge.us/abRI

**Comment by cleverca22** [comment]
another datapoint: my laptop is using snd_hda_codec_idt and has virtualbox host enabled, but audio isnt broken

**Comment by DamienCassou** [comment]
I have the same issue with linux 4.7. I'm on Lenovo T460s as well.

**Comment by DamienCassou** [comment]
I'm not sure it's related, but the laptop reboot takes more than 2 minutes when VBox is enabled and less than 30 seconds when disabled.

**Comment by DamienCassou** [comment]
I consider this problem a major bug as I (and certainly other) spend their working time in a VM and communicating with remotes colleagues.

**Comment by zimbatm** [comment]
Same issue with the Lenovo X1 Yoga - http://sprunge.us/NNiB

**Comment by zimbatm** [comment]
@DamienCassou can you post `lspci | curl -F 'sprunge=<-' http://sprunge.us`

**Comment by DamienCassou** [comment]
@zimbatm http://sprunge.us/AZWd

**Comment by FRidh** [comment]
Perhaps updating ALSA helps? http://www.alsa-project.org/main/index.php/Changes_v1.1.1_v1.1.2
We're on 1.1.1 now.

**Comment by zimbatm** [comment]
Reported the issue upstream: https://www.virtualbox.org/ticket/15919

The next thing to do would be to upgrade VirtualBox as we're a couple of releases behind (and probably won't get support from upstream because of that).

@FRidh: I think the issue is on the kernel level. If the audio driver isn't loaded I don't think it will make a difference what audio library we're using.

**Comment by domenkozar** [comment]
Looks similar to https://www.virtualbox.org/ticket/15859 except that we don't have those versions.

**Comment by domenkozar** [comment]
Seems to be happening on 5.1.4, we should try upgrading to 5.1.2.

https://www.virtualbox.org/ticket/15806

**Comment by DamienCassou** [comment]
I'm trying to build 5.1.2, but currently fails: https://github.com/NixOS/nixpkgs/pull/17502

**Comment by DamienCassou** [comment]
The sound problem is still there with 5.1.2 :-(.

**Comment by aszlig** [comment]
Haven't read all the comments, but could you try it with `pulseSupport = true`?

**Comment by DamienCassou** [comment]
@aszlig I've tried to activate pulseSupport everywhere, but this doesn't fix the problem with VirtualBox 5.1.4.

**Comment by DamienCassou** [comment]
@aszlig I merged all the changes (to get 5.1.6) you merged yesterday and I still have the issue: my computer takes 2 minutes more to boot and I don't have sound on the host.

**Comment by DamienCassou** [comment]
@zimbatm @dvc94ch @yawnt Do you guys have workarounds?

**Comment by DamienCassou** [comment]
I found a workaround for me:

```
sudo modprobe snd_hda_intel
```

Just doing that is enough, no need to restart the session. The boot is still way too long though (more than 2 minutes whereas it's less than 30 seconds without VirtualBox installed).

**Comment by yawnt** [comment]
@DamienCassou that modprobe does not work for me :(

**Comment by DamienCassou** [comment]
@yawnt try replacing `snd_hda_intel` by `snd_hda_codec_realtek`. Also try logging out and back in.

**Comment by aszlig** [comment]
@DamienCassou: I'm assuming you mean the host, what do go get with `systemd-analyze blame`?

**Comment by DamienCassou** [comment]
@aszlig I'm only talking the host, right.

```
$ systemd-analyze blame
         30.398s vboxnet0.service
          4.839s user@1000.service
```

```
$ journalctl --boot
[...]
sept. 14 10:19:34 luz4 ntpd[792]: new interface(s) found: waking up resolver
sept. 14 10:19:36 luz4 systemd[1]: Time has been changed
sept. 14 10:19:37 luz4 ntpd[792]: Listen normally on 8 wlp4s0 [fe80::9b7a:fd5:f318:7cec%3]:123
sept. 14 10:19:37 luz4 ntpd[792]: new interface(s) found: waking up resolver
sept. 14 10:19:59 luz4 vboxnet0-start[919]: VBoxManage: error: Failed to create the VirtualBox object!
sept. 14 10:19:59 luz4 vboxnet0-start[919]: VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (
sept. 14 10:19:59 luz4 vboxnet0-start[919]: VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
sept. 14 10:19:59 luz4 systemd[1]: vboxnet0.service: Main process exited, code=exited, status=1/FAILURE
sept. 14 10:19:59 luz4 systemd[1]: Failed to start VirtualBox vboxnet0 Interface.
sept. 14 10:19:59 luz4 systemd[1]: vboxnet0.service: Unit entered failed state.
sept. 14 10:19:59 luz4 systemd[1]: vboxnet0.service: Failed with result 'exit-code'.
sept. 14 10:20:28 luz4 systemd-udevd[609]: seq 1250 '/devices/pci0000:00/0000:00:02.0' is taking a long time
sept. 14 10:20:28 luz4 systemd-udevd[609]: seq 1321 '/devices/pci0000:00/0000:00:1f.3' is taking a long time
sept. 14 10:20:58 luz4 systemd[1]: sys-subsystem-net-devices-vboxnet0.device: Job sys-subsystem-net-devices-vboxnet0.device/start timed out.
sept. 14 10:20:58 luz4 systemd[1]: Timed out waiting for device sys-subsystem-net-devices-vboxnet0.device.
sept. 14 10:20:58 luz4 systemd[1]: Dependency failed for Link configuration of vboxnet0.
sept. 14 10:20:58 luz4 systemd[1]: network-link-vboxnet0.service: Job network-link-vboxnet0.service/start failed with result 'dependency'.
sept. 14 10:20:58 luz4 systemd[1]: Dependency failed for Address configuration of vboxnet0.
sept. 14 10:20:58 luz4 systemd[1]: network-addresses-vboxnet0.service: Job network-addresses-vboxnet0.service/start failed with result 'depe
sept. 14 10:20:58 luz4 systemd[1]: sys-subsystem-net-devices-vboxnet0.device: Job sys-subsystem-net-devices-vboxnet0.device/start failed wit
sept. 14 10:20:58 luz4 systemd[1]: Reached target All Network Interfaces.
[...]
sept. 14 10:20:59 luz4 systemd[1]: Startup finished in 7.697s (kernel) + 1min 30.525s (userspace) = 1min 49.512s.
sept. 14 10:21:00 luz4 cupsd[1233]: Expiring subscriptions...
sept. 14 10:21:00 luz4 cupsd[1233]: REQUEST localhost - - "POST / HTTP/1.1" 200 349 Create-Printer-Subscriptions successful-ok
sept. 14 10:21:00 luz4 cupsd[1233]: REQUEST localhost - - "POST / HTTP/1.1" 200 176 Create-Printer-Subscriptions successful-ok
sept. 14 10:21:01 luz4 cupsd[1233]: Expiring subscriptions...
sept. 14 10:21:31 luz4 cupsd[1233]: Saving subscriptions.conf...
sept. 14 10:21:31 luz4 cupsd[1233]: Expiring subscriptions...
sept. 14 10:22:28 luz4 systemd-udevd[609]: seq 1250 '/devices/pci0000:00/0000:00:02.0' killed
sept. 14 10:22:28 luz4 systemd-udevd[609]: seq 1321 '/devices/pci0000:00/0000:00:1f.3' killed
sept. 14 10:22:28 luz4 kernel: snd_soc_skl 0000:00:1f.3: failed to add i915 component master (-19)
sept. 14 10:22:28 luz4 kernel: i915 0000:00:02.0: enabling device (0006 -> 0007)
sept. 14 10:22:28 luz4 systemd-udevd[609]: worker [618] terminated by signal 9 (Killed)
sept. 14 10:22:28 luz4 systemd-udevd[609]: worker [618] failed while handling '/devices/pci0000:00/0000:00:1f.3'
```

**Comment by lapp0** [comment]
Same issue Thinkpad T560
```
cat /proc/modules | grep snd
snd_seq_dummy 1403 2 - Live 0x0000000000000000
snd_seq 50009 7 snd_seq_dummy, Live 0x0000000000000000
snd_seq_device 3496 1 snd_seq, Live 0x0000000000000000
snd_hda_intel 24293 0 - Live 0x0000000000000000
snd_hda_codec 85446 1 snd_hda_intel, Live 0x0000000000000000
snd_hwdep 6186 1 snd_hda_codec, Live 0x0000000000000000
snd_soc_skl 23957 0 - Live 0x0000000000000000
snd_soc_skl_ipc 13432 1 snd_soc_skl, Live 0x0000000000000000
snd_soc_sst_ipc 4062 1 snd_soc_skl_ipc, Live 0x0000000000000000
snd_soc_sst_dsp 25938 1 snd_soc_skl_ipc, Live 0x0000000000000000
dw_dmac_core 14833 1 snd_soc_sst_dsp, Live 0x0000000000000000
snd_hda_ext_core 9675 1 snd_soc_skl, Live 0x0000000000000000
snd_hda_core 39723 4 snd_hda_intel,snd_hda_codec,snd_soc_skl,snd_hda_ext_core, Live 0x0000000000000000
snd_soc_core 150531 1 snd_soc_skl, Live 0x0000000000000000
snd_pcm_oss 37312 0 - Live 0x0000000000000000
snd_mixer_oss 14190 1 snd_pcm_oss, Live 0x0000000000000000
snd_compress 7211 1 snd_soc_core, Live 0x0000000000000000
ac97_bus 1630 1 snd_soc_core, Live 0x0000000000000000
snd_pcm_dmaengine 3566 1 snd_soc_core, Live 0x0000000000000000
snd_pcm 80652 8 snd_hda_intel,snd_hda_codec,snd_soc_skl,snd_hda_ext_core,snd_hda_core,snd_soc_core,snd_pcm_oss,snd_pcm_dmaengine, Live 0x0000000000000000
snd_timer 20425 2 snd_seq,snd_pcm, Live 0x0000000000000000
snd 59636 14 snd_seq,snd_seq_device,snd_hda_intel,snd_hda_codec,snd_hwdep,snd_soc_core,snd_pcm_oss,snd_mixer_oss,snd_compress,snd_pcm,snd_timer,thinkpad_acpi, Live 0x0000000000000000
soundcore 5475 1 snd, Live 0x0000000000000000

```

**Comment by domenkozar** [comment]
@lapp0  can you pastebin `journalctl -b` and `journalctl -k` for the time when audio fails?

**Comment by lapp0** [comment]
journalctl -b for my last boot (I have audio until I reboot) http://pastebin.com/raw/rayr66u7
journalctl -k http://pastebin.com/raw/8j2QcJgh

**Comment by domenkozar** [comment]
@lapp0 can you also paste `$ lspci -nn`?

Also, does the workaround help for you: `sudo modprobe snd_hda_intel`?

**Comment by lapp0** [comment]
@domenkozar 

`00:00.0 Host bridge [0600]: Intel Corporation Sky Lake Host Bridge/DRAM Registers [8086:1904] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] (rev 07)
00:08.0 System peripheral [0880]: Intel Corporation Sky Lake Gaussian Mixture Model [8086:1911]
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Device [8086:9d31] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:9d3a] (rev 21)
00:16.3 Serial controller [0700]: Intel Corporation Device [8086:9d3d] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Device [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:9d10] (rev f1)
00:1c.2 PCI bridge [0604]: Intel Corporation Device [8086:9d12] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:9d48] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Device [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:9d70] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:9d23] (rev 21)
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection I219-LM [8086:156f] (rev 21)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device [10ec:522a] (rev 01)
04:00.0 Network controller [0280]: Intel Corporation Wireless 8260 [8086:24f3] (rev 3a)
`

**Comment by domenkozar** [comment]
Although sound is indeed important, I'll let this go as a blocker. Hopefully we can fix it after the release asap.

**Comment by DamienCassou** [comment]
I have the impression this is fixed in `channels/16.09`.

**Comment by martijnvermaat** [comment]
I can confirm :clap:

**Comment by lapp0** [comment]
Works for me as well. Thanks for your great work devs!

**Comment by zimbatm** [comment]
Same, does somebody know what fixed the issue exactly?
