### ISSUE TITLE
meld on Mac M1 is broken.

### ISSUE THREAD

**Issue by sequencer** [NixOS/nixpkgs#151803]
### Describe the bug
run `meld` from zsh+tmux on M1 MacBook Air 16G, log below: 
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               python3.9 [49102]
Path:                  /Volumes/VOLUME/*/python3
Identifier:            python3.9
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [28956]
Responsible:           Alfred [4406]
User ID:               501

Date/Time:             2021-12-23 02:23:33.1763 +0800
OS Version:            macOS 12.2 (21D5025f)
Report Version:        12
Anonymous UUID:        BBEEA9DD-326D-6FE8-9435-4F6AFAEDE56B

Sleep/Wake UUID:       BF3A4700-04FD-475B-BF5E-44EBE49410D8

Time Awake Since Boot: 93000 seconds
Time Since Wake:       48543 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xa940421110fe0018 -> 0x0000421110fe0018 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0xa940421110fe0018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [49102]

VM Region Info: 0x421110fe0018 is not in any region.  Bytes after previous region: 72160030621721  Bytes before following region: 32912049307624
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	       0x105ad2530 g_callable_info_free_closure + 20
1   ???                           	       0x105a89924 _pygi_invoke_closure_free + 28
2   ???                           	       0x105a89924 _pygi_invoke_closure_free + 28
3   ???                           	       0x10a01bc8c gtk_combo_box_destroy + 100
4   ???                           	       0x105b0d750 g_closure_invoke + 200
5   ???                           	       0x105b238d0 signal_emit_unlocked_R + 2416
6   ???                           	       0x105b24434 g_signal_emit_valist + 2548
7   ???                           	       0x105b24748 g_signal_emit + 44
8   ???                           	       0x10a279dd8 gtk_widget_dispose + 128
9   ???                           	       0x105b12ef4 g_object_unref + 232
10  ???                           	       0x10a098214 set_extra_widget + 72
11  ???                           	       0x105b14a6c object_set_property + 316
12  ???                           	       0x105b146b0 g_object_setv + 168
13  ???                           	       0x105b154dc g_object_set_property + 48
14  ???                           	       0x105b14a6c object_set_property + 316
15  ???                           	       0x105b146b0 g_object_setv + 168
16  ???                           	       0x105b154dc g_object_set_property + 48
17  ???                           	       0x105a8adbc pygi_set_property_value + 984
18  ???                           	       0x105a72580 PyGProps_setattro + 336
19  ???                           	       0x105521e80 PyObject_SetAttr + 148
20  ???                           	       0x1055ad348 _PyEval_EvalFrameDefault + 13492
21  ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
22  ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
23  ???                           	       0x1054dd7c0 method_vectorcall + 396
24  ???                           	       0x105a8b39c pygi_signal_closure_marshal + 860
25  ???                           	       0x105b0d750 g_closure_invoke + 200
26  ???                           	       0x105b236a8 signal_emit_unlocked_R + 1864
27  ???                           	       0x105b24434 g_signal_emit_valist + 2548
28  ???                           	       0x105b24748 g_signal_emit + 44
29  ???                           	       0x105b17d48 g_object_dispatch_properties_changed + 80
30  ???                           	       0x105b13838 g_object_notify_queue_thaw + 264
31  ???                           	       0x105b146cc g_object_setv + 196
32  ???                           	       0x105b154dc g_object_set_property + 48
33  ???                           	       0x10a0872c4 gtk_file_chooser_button_set_property + 416
34  ???                           	       0x105b14a6c object_set_property + 316
35  ???                           	       0x105b14cfc g_object_set_valist + 392
36  ???                           	       0x105b153c8 g_object_set + 76
37  ???                           	       0x10a0870b0 gtk_file_chooser_button_constructed + 1428
38  ???                           	       0x105b141c0 g_object_new_internal + 264
39  ???                           	       0x105b14578 g_object_newv + 264
40  ???                           	       0x109fd9718 _gtk_builder_construct + 676
41  ???                           	       0x109fdfcb8 builder_construct + 92
42  ???                           	       0x109fdf8c0 end_element + 1052
43  ???                           	       0x105c2e3d0 emit_end_element + 244
44  ???                           	       0x105c2dd00 g_markup_parse_context_parse + 5988
45  ???                           	       0x109fde090 _gtk_builder_parser_parse_buffer + 248
46  ???                           	       0x109fda934 gtk_builder_extend_with_template + 368
47  ???                           	       0x10a2789f4 gtk_widget_init_template + 212
48  ???                           	       0x105a3404c ffi_call_SYSV + 76
49  ???                           	       0x105a318cc ffi_call_int + 1208
50  ???                           	       0x105a8bd84 pygi_invoke_c_callable + 1984
51  ???                           	       0x105a8cf00 pygi_function_cache_invoke + 68
52  ???                           	       0x1054dacc0 _PyObject_MakeTpCall + 360
53  ???                           	       0x1055b2490 call_function + 516
54  ???                           	       0x1055afd3c _PyEval_EvalFrameDefault + 24232
55  ???                           	       0x1054db534 function_code_fastcall + 116
56  ???                           	       0x1055b242c call_function + 416
57  ???                           	       0x1055afd3c _PyEval_EvalFrameDefault + 24232
58  ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
59  ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
60  ???                           	       0x1054dd750 method_vectorcall + 284
61  ???                           	       0x1054db994 _PyObject_CallFunctionVa + 136
62  ???                           	       0x1054dc0fc _PyObject_CallMethod_SizeT + 112
63  ???                           	       0x105a7ba10 pygobject__g_instance_init + 196
64  ???                           	       0x105b2641c g_type_create_instance + 520
65  ???                           	       0x105b14100 g_object_new_internal + 72
66  ???                           	       0x105b13b2c g_object_new_with_properties + 352
67  ???                           	       0x105a7844c pygobject_constructv + 80
68  ???                           	       0x105a72240 pygobject_init + 292
69  ???                           	       0x10553ea4c wrap_init + 20
70  ???                           	       0x1054dacc0 _PyObject_MakeTpCall + 360
71  ???                           	       0x1055b2490 call_function + 516
72  ???                           	       0x1055afcc0 _PyEval_EvalFrameDefault + 24108
73  ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
74  ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
75  ???                           	       0x1054daab0 _PyObject_FastCallDictTstate + 312
76  ???                           	       0x1054db840 _PyObject_Call_Prepend + 148
77  ???                           	       0x10553e960 slot_tp_init + 216
78  ???                           	       0x105535774 type_call + 352
79  ???                           	       0x1054dacc0 _PyObject_MakeTpCall + 360
80  ???                           	       0x1055b2490 call_function + 516
81  ???                           	       0x1055afd3c _PyEval_EvalFrameDefault + 24232
82  ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
83  ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
84  ???                           	       0x1055b242c call_function + 416
85  ???                           	       0x1055afc9c _PyEval_EvalFrameDefault + 24072
86  ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
87  ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
88  ???                           	       0x105a894f0 _pygi_closure_handle + 816
89  ???                           	       0x105a31d84 ffi_closure_SYSV_inner + 1040
90  ???                           	       0x105a341d4 ffi_closure_SYSV + 52
91  ???                           	       0x10617291c _g_cclosure_marshal_INT__OBJECTv + 120
92  ???                           	       0x105b0d968 _g_closure_invoke_va + 212
93  ???                           	       0x105b23e3c g_signal_emit_valist + 1020
94  ???                           	       0x105b24748 g_signal_emit + 44
95  ???                           	       0x1061cbb34 g_application_call_command_line + 124
96  ???                           	       0x1061cd968 g_application_real_local_command_line + 1464
97  ???                           	       0x1061cb878 g_application_run + 408
98  ???                           	       0x105a3404c ffi_call_SYSV + 76
99  ???                           	       0x105a318cc ffi_call_int + 1208
100 ???                           	       0x105a8bd84 pygi_invoke_c_callable + 1984
101 ???                           	       0x105a8cf00 pygi_function_cache_invoke + 68
102 ???                           	       0x1054db2e0 _PyObject_Call + 172
103 ???                           	       0x1055affb8 _PyEval_EvalFrameDefault + 24868
104 ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
105 ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
106 ???                           	       0x1055b242c call_function + 416
107 ???                           	       0x1055afc9c _PyEval_EvalFrameDefault + 24072
108 ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
109 ???                           	       0x1054db4b4 _PyFunction_Vectorcall + 256
110 ???                           	       0x1055b242c call_function + 416
111 ???                           	       0x1055afd3c _PyEval_EvalFrameDefault + 24232
112 ???                           	       0x1054db534 function_code_fastcall + 116
113 ???                           	       0x1055b242c call_function + 416
114 ???                           	       0x1055afd3c _PyEval_EvalFrameDefault + 24232
115 ???                           	       0x1055b3424 _PyEval_EvalCode + 3196
116 ???                           	       0x1055a9dcc PyEval_EvalCode + 80
117 ???                           	       0x1055f4204 pyrun_file + 304
118 ???                           	       0x1055f211c PyRun_SimpleFileExFlags + 660
119 ???                           	       0x10560fbd0 Py_RunMain + 1724
120 ???                           	       0x1056100e0 pymain_main + 340
121 ???                           	       0x10561016c Py_BytesMain + 56
122 dyld                          	       0x104fe10f4 start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x197078010 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x197078010 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x197078010 start_wqthread + 0

Thread 4:: gmain
0   libsystem_kernel.dylib        	       0x197049ad0 poll + 8
1   ???                           	       0x105c291e8 g_main_context_iterate + 444
2   ???                           	       0x105c29324 g_main_context_iteration + 112
3   ???                           	       0x105c2b5a8 glib_worker_main + 48
4   ???                           	       0x105c529ac g_thread_proxy + 68
5   libsystem_pthread.dylib       	       0x19707d240 _pthread_start + 148
6   libsystem_pthread.dylib       	       0x197078024 thread_start + 8

Thread 5:: pool-spawner
0   libsystem_kernel.dylib        	       0x1970450c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19707d808 _pthread_cond_wait + 1228
2   ???                           	       0x105c7b788 g_cond_wait + 44
3   ???                           	       0x105bf5788 g_async_queue_pop_intern_unlocked + 144
4   ???                           	       0x105c53050 g_thread_pool_spawn_thread + 88
5   ???                           	       0x105c529ac g_thread_proxy + 68
6   libsystem_pthread.dylib       	       0x19707d240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x197078024 thread_start + 8

Thread 6:: pool-org.gnome.
0   libsystem_kernel.dylib        	       0x1970450c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19707d834 _pthread_cond_wait + 1272
2   ???                           	       0x105c7b9a0 g_cond_wait_until + 144
3   ???                           	       0x105bf57ac g_async_queue_pop_intern_unlocked + 180
4   ???                           	       0x105c53d8c g_thread_pool_thread_proxy + 172
5   ???                           	       0x105c529ac g_thread_proxy + 68
6   libsystem_pthread.dylib       	       0x19707d240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x197078024 thread_start + 8

Thread 7:: pool-org.gnome.
0   libsystem_kernel.dylib        	       0x1970450c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19707d834 _pthread_cond_wait + 1272
2   ???                           	       0x105c7b9a0 g_cond_wait_until + 144
3   ???                           	       0x105bf57ac g_async_queue_pop_intern_unlocked + 180
4   ???                           	       0x105c53d8c g_thread_pool_thread_proxy + 172
5   ???                           	       0x105c529ac g_thread_proxy + 68
6   libsystem_pthread.dylib       	       0x19707d240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x197078024 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000013b330190   x1: 0x0000000106aa4430   x2: 0x0000000000000008   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000002   x6: 0x0000600002a95200   x7: 0x0000000109fa01cc
    x8: 0xa940421110fe0010   x9: 0x0000000000000002  x10: 0x0000000000000000  x11: 0x0000000000000002
   x12: 0x000000000000001e  x13: 0x0000000000000066  x14: 0x0000000000000066  x15: 0x0000000000000000
   x16: 0x0000000105ad251c  x17: 0x00000001f13881b8  x18: 0x0000000000000000  x19: 0x0000000106aa4430
   x20: 0x000000013b62eff0  x21: 0x000000016af2e420  x22: 0x0000000000000001  x23: 0x0000000000000000
   x24: 0x0000000000000098  x25: 0x0000000000000002  x26: 0x0000000105b0de58  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016af2e270   lr: 0x0000000105a89924
    sp: 0x000000016af2e260   pc: 0x0000000105ad2530 cpsr: 0x60001000
   far: 0xa940421110fe0018  esr: 0x92000004 (Data Abort) byte read Translation fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x104fdc000 -        0x10503bfff dyld (*) <6c3fc6e6-ee27-3ad4-82fd-73e4b990bb02> /usr/lib/dyld
       0x197076000 -        0x197082fff libsystem_pthread.dylib (*) <61ee3110-0816-31e9-84bb-6a4fe8548658> /usr/lib/system/libsystem_pthread.dylib
       0x197040000 -        0x197075fff libsystem_kernel.dylib (*) <b2f21b34-f3f3-3a01-8537-dcd2cc36d2da> /usr/lib/system/libsystem_kernel.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=799.2M resident=0K(0%) swapped_out_or_unallocated=799.2M(100%)
Writable regions: Total=976.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=976.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          464K       23 
CoreGraphics                        48K        3 
Kernel Alloc Once                   32K        1 
MALLOC                           210.2M       28 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         360.0M        3         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        1.0G       43 
__AUTH                            1766K      143 
__AUTH_CONST                      9132K      283 
__DATA                            9373K      336 
__DATA_CONST                      10.8M      348 
__DATA_DIRTY                       593K       99 
__FONT_DATA                          4K        1 
__LINKEDIT                       581.1M       68 
__OBJC_CONST                      1223K      117 
__OBJC_RO                         82.0M        1 
__OBJC_RW                         3104K        1 
__TEXT                           218.1M      364 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                       63.5M       33 
shared memory                     1408K       14 
===========                     =======  ======= 
TOTAL                              3.0G     1934 
TOTAL, minus reserved VM space     2.2G     1934 
```
### Steps To Reproduce
1. nix-env -I meld
2. meld
3. broken

### Expected behavior
run

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - host os: `Darwin 21.3.0, macOS 12.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(sequencer): `"nixpkgs-22.05pre339739.1dd151f0c0c"`
 - channels(root): `"nixpkgs-21.11pre325327.30f73c6493b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jiegec** [comment]
It seems to be a cairo bug, fixed by https://github.com/NixOS/nixpkgs/pull/178551. Could you try again after the pr lands in master?

**Comment by robelsharma** [comment]
I am still seeing this issue on Macbook Pro M1. Any fix for this yet?

**Comment by kolmodin** [comment]
`nix run nixpkgs#meld` works on darwin now, and it can compare files. This bug should be closed.
