### ISSUE TITLE
Wireplumber completely broke audio and video playback

### ISSUE THREAD

**Issue by alyaeanyx** [NixOS/nixpkgs#163066]
### Describe the bug
After Wireplumber was enabled by default in #159546, audio and video playback completely broke on my machine (NixOS-unstable, GNOME on X11, x86_64-linux). Preview thumbnails of videos did show, but clicking "play" on audio/video tracks does nothing. I've observed this directly in Firefox, Element Desktop, Freetube, Rhythmbox and Signal.

Reverting #159546 by putting
```
services.pipewire.media-session.enable = true;
services.pipewire.wireplumber.enable = false;
```
into my config resolves the issue.

### Steps To Reproduce
1. Install Firefox
2. Try to play a video

### Notify maintainers
@K900 since you authored the PR

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220221_caf5172`
 - channels(root): `"nixos"`
 - channels(alexandra): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by alyaeanyx** [comment]
I've also verified that this isn't resolved by #162730.

**Comment by kirillrdy** [comment]
I am also experiencing issues with video playback, I am glad i found this issue.

```
services.pipewire.media-session.enable = true;
services.pipewire.wireplumber.enable = false;

```
seems to have fixed it

**Comment by jansol** [comment]
Known regression with pipewire 0.3.48 and wireplumber 0.4.8. Should be fixed by #163060.

**Comment by alyaeanyx** [comment]
I've tried applying the fix from #163060 with:
```
services.pipewire.wireplumber.package = (import (pkgs.fetchFromGitHub { owner = "K900"; repo = "nixpkgs"; rev = "57c7ee78b9bab82b036a232904f9161c5c4537cd"; sha256 = "sha256-CIk45MlAa8f9UdPD5DsqjiOT89ecFsxFpM40VHOLuAE="; }) { system = "x86_64-linux"; }).wireplumber;
```
but it didn't resolve the issue for me.

**Comment by K900** [comment]
That is strange. What's the store hash of your wireplumber build after this?

**Comment by alyaeanyx** [comment]
With the nixpkgs revision 3e072546ea98db00c2364b81491b893673267827, I get:
```
nix-repl> :b nixosConfigurations.thermidor.config.services.pipewire.wireplumber.package

This derivation produced the following outputs:
  dev -> /nix/store/0xqmxnkvdn4p3a9pwfs1ddiyvrbai0qw-wireplumber-0.4.8-dev
  doc -> /nix/store/5nrq2c9csx8psxhagyvllyqd7vss5ilj-wireplumber-0.4.8-doc
  out -> /nix/store/8a0bakgzc5wdkvf0yjv0vnvv1bydzvsp-wireplumber-0.4.8
```
I haven't applied any overlays that influence wireplumber. (Checked by directly building wireplumber from your Nixpkgs PR branch)

**Comment by K900** [comment]
That has does seem to match. I wonder if it's a different issue then... Can you also run `systemctl --user status wireplumber`?

**Comment by alyaeanyx** [comment]
```
alexandra@thermidor ~> systemctl --user status wireplumber
● wireplumber.service - Multimedia Service Session Manager
     Loaded: loaded (/etc/systemd/user/wireplumber.service; enabled; vendor preset: enabled)
    Drop-In: /nix/store/dvv4r5whxfhcgw4bg6qaw2w92qf938qc-user-units/wireplumber.service.d
             └─overrides.conf
     Active: active (running) since Mon 2022-03-07 10:49:19 CET; 10s ago
   Main PID: 2723 (wireplumber)
      Tasks: 5 (limit: 19015)
     Memory: 15.2M
        CPU: 98ms
     CGroup: /user.slice/user-1001.slice/user@1001.service/session.slice/wireplumber.service
             └─2723 /nix/store/8a0bakgzc5wdkvf0yjv0vnvv1bydzvsp-wireplumber-0.4.8/bin/wireplumber

Mar 07 10:49:19 thermidor systemd[1935]: Started Multimedia Service Session Manager.
Mar 07 10:49:19 thermidor wireplumber[2723]: Failed to set scheduler settings: Operation not permitted
Mar 07 10:49:22 thermidor wireplumber[2723]: The decibel volume range for element 'PCM' (-6400 dB - -100 dB) has negative maximum. Disabling the decibel range.
Mar 07 10:49:22 thermidor wireplumber[2723]: The decibel volume range for element 'PCM' (-6400 dB - -100 dB) has negative maximum. Disabling the decibel range.
Mar 07 10:49:22 thermidor wireplumber[2723]: The decibel volume range for element 'PCM' (-6400 dB - -100 dB) has negative maximum. Disabling the decibel range.
Mar 07 10:49:22 thermidor wireplumber[2723]: The decibel volume range for element 'PCM' (-6400 dB - -100 dB) has negative maximum. Disabling the decibel range.
Mar 07 10:49:22 thermidor wireplumber[2723]: The decibel volume range for element 'PCM' (-6400 dB - -100 dB) has negative maximum. Disabling the decibel range.
```
By the way, if you want to, we can continue this on Matrix (I'm @alxanyae:matrix.org there).

**Comment by K900** [comment]
Honestly at this point I'd probably just report a bug upstream, or ask around in #pipewire:matrix.org

**Comment by alyaeanyx** [comment]
Okay, thanks, I'll try that. Do you happen to know whether wireplumber has some sort of "verbose/debug log" build option which might make it easier to find the bug?

**Comment by K900** [comment]
Try WIREPLUMBER_DEBUG=10

**Comment by eadwu** [comment]
You should try zapping all config and cache.

Especially if you use bluetooth.

**Comment by JonathanReeve** [comment]
I've been having this issue, too, on unstable. What I've noticed is that, on reboot or logout/login, playing a video works just fine the first time. But on the second and subsequent times, video won't play. A stil image from the video is displayed, but the video doesn't play at all. 

Here's what I see with `systemctl --user status wireplumber`: 

```
Mar 08 13:53:56 jon-laptop wireplumber[7089]: Failed to set scheduler settings: Operation not permitted
```

For me, running `systemctl --user stop wireplumber.service` fixes this problem immediately. That is, videos suddenly start playing.

**Comment by K900** [comment]
Is this with the patch or without?

**Comment by alyaeanyx** [comment]
@K900 there might be relevant details here https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/214#note_1288170

**Comment by collares** [comment]
How are you enabling Pipewire? Something like the snippet below?
```
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    jack.enable = true;
    pulse.enable = true;
  };
```

**Comment by alyaeanyx** [comment]
That's an interesting question. I didn't explicitly enable Pipewire anythere, my sound config is just:
```
sound.enable = true;
hardware.pulseaudio.enable = true;
```
Basically, I have no idea of audio systems on Linux and I just assumed that it was some sort of backend for PulseAudio. On my system however, the Pipewire and Wireplumber services are there. Maybe that's some sort of bug in the NixOS audio submodules?

**Comment by alyaeanyx** [comment]
With `nix repl`, I've confirmed that something in my config indeed causes `services.pipewire.enable` to be set to true, but `services.pipewire.{alsa,jack,pulse}.enable` are all false.

**Comment by alyaeanyx** [comment]
I've backtraced this and `services.pipewire.enable = true` is set by `services.gnome.gnome-remote-desktop.enable = true`, which is in turn enabled by default on Gnome (nixos/modules/services/x11/desktop-managers/gnome.nix:411). It might be worth to open an issue for that.

**Comment by collares** [comment]
This is really useful debugging information! Take my next paragraph with a grain of salt, since I am not a PipeWire expert.

Some parts of PipeWire relate to screensharing (which is probably why `gnome-remote-desktop` enables it) and supposedly should work even without the ALSA/PulseAudio/Jack emulation, but sometimes there are bugs in the session managers; for example, https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/768 was a bug in the old session manager with a similar outcome. I *think* that screensharing use cases are meant to work even for PulseAudio users (that is, without enabling PipeWire's PulseAudio "emulation" layer).

**Comment by collares** [comment]
It seems that part of the problem is that `pipewire-media-session` had those extra knobs for turning various emulation layers on and off (such as `alsa.enable` and `pulse.enable`), but those are no longer respected when using WirePlumber. This might lead to some weird conflicts for PulseAudio users (for example, if WirePlumber decides to start pipewire-pulse).

**Comment by collares** [comment]
But does this mean that the WirePlumber switch broke audio for every GNOME user that does *not* use PipeWire? This seems like the default config!

**Comment by K900** [comment]
Those knobs are for Pipewire itself, not pipewire-media-session. Wireplumber should still be functional in a mixed PW/Pulse setup, so it's probably worth reopening the upstream issue.

**Comment by alyaeanyx** [comment]
I'd ask someone else to open that issue though because my knowledge on this topic is close to zero, and I'll probably not be able to accurately describe the technical details here.

> But does this mean that the WirePlumber switch broke audio for every GNOME user that does not use PipeWire?
I've also tested this on my laptop, and it has the same issue, so that actually seems like a realistic possibility.
I'm not really sure when it comes to user statistics, but from what I've seen, GNOME tends to be mostly used by less experienced users, while KDE and WMs like i3 are a lot more popular among advanced users, and the unstable repositories of an operating system are generally almost exclusively used by advanced users. So after considering the small user base of NixOS, it's really possible that there are just not that many GNOME/nixos-unstable users who are likely to encounter that bug.

**Comment by collares** [comment]
> Those knobs are for Pipewire itself, not pipewire-media-session. Wireplumber should still be functional in a mixed PW/Pulse setup, so it's probably worth reopening the upstream issue.

Ideally yes, but there are two places in the NixOS module that look at `cfg.pulse.enable`: `pipewire.nix` uses it to decide if the systemd service should be installed, and `pipewire-media-session.nix` looks at it to create the `with-pulseaudio` file. Therefore, `pipewire-media-session` is given a hint that pipewire-pulse shouldn't be started, while upstream WirePlumber does not seem to have such an option. If I had to bet, I'd say WirePlumber does not currently support this use case.

**Comment by K900** [comment]
pipewire-media-session doesn't start pipewire-pulse, systemd does. Wireplumber should detect the right setup automatically.

**Comment by jansol** [comment]
Yeah the `with-pulseaudio` file dates back to before the systemd service for pipewire-pulse existed. It is probably redundant nowadays.

**Comment by collares** [comment]
I agree with what you two are saying, but I think I didn't express myself clearly, so I will try again; apologies if this is annoying. My point is that we have no indication that WirePlumber is designed to support mixed setups. The release notes for WirePlumber 0.4.0 say

 "It is a fundamental goal of this series to maintain compatibility with pipewire-media-session, making WirePlumber suitable for a desktop PulseAudio & JACK replacement setup, while supporting other setups as well (ex. automotive) by making use of its brand new Lua scripting engine, which allows making customizations easily."
 
and it's unclear if they care about our use case (IMO it would be perfectly reasonable to not support PulseAudio). I'll ask upstream.

**Comment by Baughn** [comment]
Is that in fact how we're using it? Or is it opening the sound devices regardless?

...I should just check. Will report back later.

**Comment by Baughn** [comment]
With Pulseaudio enabled (by `sound.enable = true`), Pipewire started when I opened a video on youtube, and no sooner — there was, however, no sound. Chrome connected to pulseaudio regardless. Pavucontrol reported no sound output devices available; only sound input was possible. A bit of searching in /proc indicated that pipewire was holding the audio devices open, and my sound card indeed only supports one stream at a time... but I'm unable to confirm that this is the issue.

Regardless, I was only able to make sound work by either completely disabling pipewire, or completely disabling pulseaudio.

**Comment by jansol** [comment]
Hmm without looking deeply into it, I'm guessing the problem is that wireplumber [always enables its alsa listener by default](https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/b3446efa164b49663438c3b31ee9c0357b3016aa/src/config/main.lua.d/90-enable-all.lua#L9) and we don't have any way of configuring that via nix yet.

Can you try if it works with pipewire-media-session if you disable all the audio stuff? This should cause alsa-monitor to never get loaded in pipewire:
```nix
hardware.pulseaudio.enable = true;

services.pipewire = {
  enable = true;

  # Enable the (deprecated) media-session session manager instead of wireplumber
  media-session.enable = true;
  wireplumber.enable = false;

  # Disable everything that causes pipewire to interact with alsa devices
  alsa.enable = false;
  pulse.enable = false;
  jack.enable = false;
};
```

**Comment by uzytkownik** [comment]
> How are you enabling Pipewire? Something like the snippet below?
> 
> ```
>   services.pipewire = {
>     enable = true;
>     alsa.enable = true;
>     jack.enable = true;
>     pulse.enable = true;
>   };
> ```

```
  hardware.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    jack.enable = true;
    pulse.enable = true;
  };
```

Fixed problem for me

**Comment by TheSirC** [comment]
I must say that this problem has been driving me crazy and you guys just prevented hours of debugging.

 @uzytkownik I will try your fix and report any problems.

**Comment by K900** [comment]
OK, I think we need to add an assertion here. I'll do it tomorrow unless someone snipes me.

**Comment by K900** [comment]
So, while switching to Pipewire is nice, I really don't think that justifies breaking people's mixed PW/Pulse setups. Please test the fix in #165231 if you're affected (and make sure you disable Pipewire beforehand).

**Comment by K900** [comment]
Please don't bump one-year-old threads. File a new issue.
