### ISSUE TITLE
Cross compiling Python2 `greenlet` fails for Raspberry Pi

### ISSUE THREAD

**Issue by cyber-murmel** [NixOS/nixpkgs#166053]
### Describe the bug
Cross compiling Python2 `greenlet` (needed for klipper) for Raspberry Pi fails with
```
armv6l-unknown-linux-gnueabihf-gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/nix/store/zxrnf05y8h59s5pz5gsjwgr78lb6mm67-python-2.7.18/include/python2.7 -c src/greenlet/greenlet.c -o build/temp.linux-x86_64-2.7/src/greenlet/greenlet.o
In file included from /nix/store/zxrnf05y8h59s5pz5gsjwgr78lb6mm67-python-2.7.18/include/python2.7/Python.h:61,
                 from src/greenlet/greenlet.h:8,
                 from src/greenlet/greenlet.c:11:
/nix/store/zxrnf05y8h59s5pz5gsjwgr78lb6mm67-python-2.7.18/include/python2.7/pyport.h:895:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  895 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^~~~~
```

### Steps To Reproduce
```bash
# build from current master (Mon Mar 28 08:55:41 AM UTC 2022)
nix-build https://github.com/NixOS/nixpkgs/archive/e801b16.tar.gz -A pkgsCross.raspberryPi.python2Packages.greenlet
```

### Expected behavior
A successful build of the package with.

### Screenshots
![image](https://user-images.githubusercontent.com/30078229/160366763-da4886b2-b21a-47d6-bac5-75b663a938fc.png)

### Additional context
```bash
# same problem with 21.11
nix-build https://github.com/NixOS/nixpkgs/archive/nixos-21.11.tar.gz -A pkgsCross.raspberryPi.python2Packages.greenlet
```

### Notify maintainers
@wamserma
@mweinelt

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.106, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(marble): `"nixos-unstable-22.05pre356180.d5f23787297"`
 - channels(root): `"nixos-21.11.336646.d2caa937753"`
 - channels(work): `"nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mindavi** [comment]
I don't think we support python2 much anymore (upstream also hasn't for a while).

**Comment by wamserma** [comment]
> I don't think we support python2 much anymore (upstream also hasn't for a while).

That is correct. Python2 is EOL for quite some time now and we only keep it around to avoid breaking a few packages that have not been updated yet.
You may try `pkgsCross.raspberryPi.pypy2packages` or wait for `klipper`'s Python3 migration to be finished. Looking at the open PRs this seems to be an active topic.

**Comment by Artturin** [comment]
maybe fixed by https://github.com/NixOS/nixpkgs/pull/177888

**Comment by rnhmjoj** [comment]
@Artturin, it looks like it's still failing with the same error (and other packages with C extensions).
