### ISSUE TITLE
scipy doesn't build on Darwin

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#170143]
### Describe the bug

scipy doesn't build on Darwin right now (trunk).
Hydra: https://hydra.nixos.org/build/173999765

The error in Hydra seems to be some builder failure and not actually related to the issue.
It however fails as well when I try to build on my Mac. We should get rid of both issues.

### Steps To Reproduce
1. Try to build `python39Packages.scipy`

### Expected behavior

It builds

### Additional context

I don't need this Python module myself but a lot of other packages depend on it.
This is currently the package with the most dependants (322) that fails so it'd be nice to have this cleaned up before ZHF starts.

### Notify maintainers

@NixOS/darwin-maintainers

**Comment by toonn** [comment]
The too many open files sounds like it could be related to the very low default limit on open files on macOS. For me it defaults to 256, I think more recent versions have increased the limit but it's still lower than for Linux and the tests were probably written with that in mind.

**Comment by reckenrode** [comment]
scipy builds for me on both x86_64-darwin and aarch64-darwin.

$ nix-info -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.8.0`
 - channels(reckenrode): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

**Comment by reckenrode** [comment]
> @reckenrode, what does `ulimit -n` report for you?

```
$ ulimit -n
256
```

**Comment by toonn** [comment]
Ok, then my hypothesis is debunked.

**Comment by smaret** [comment]
Could this be due to the file descriptor leak bug in nix ?
https://github.com/NixOS/nix/issues/4046
This would explain why it fails to build for some users but not for others. I believe the bug was fixed in nix 2.8.

**Comment by siraben** [comment]
scipy seems to be build for me on `aarch64-darwin`, can anyone else confirm? Looks like it's still failing on `x86_64-darwin`.

**Comment by 06kellyjac** [comment]
can we just disable the tests on `x86_64-darwin` for now?

as a note `ulimit -n 1024` (or whatever) can bump the open file limit but you might then run into memory limits like I've experienced in #172548

**Comment by siraben** [comment]
I'm going to disable tests on `x86-64-darwin` so we can work on other issues for ZHF. If anyone wants to debug specific failures in scipy please reply to this issue. It currently causes hundreds of other packages to transitively fail.

**Comment by risicle** [comment]
Wonder if reducing parallelism would help.
