### ISSUE TITLE
Grafana phantomjs png rendering failure. 

### ISSUE THREAD

**Issue by mckeankylej** [NixOS/nixpkgs#17182]
## Issue description
When asking grafana to render a graph to a [png](http://docs.grafana.org/reference/sharing/) using a minimal grafana set up (see below) it errors with:
```sh
Server side error :(
Failed to render to png
```
When checking `journalclt` I get the following error:
```sh
Jul 22 19:12:01 grafana grafana-server[268]: 2016/07/22 19:12:01 [render.go:41 RenderToPng()] [E] Failed to render to png:
 fork/exec /var/lib/grafana/vendor/phantomjs/phantomjs: no such file or directory                                        

```
### Steps to reproduce
1. Add this to your configuration.nix and rebuild
```nix
services.grafana.enable = true;
```
2. Go to localhost:3000 in your browser
3. Click the button in the top right corner named [Home]
4. Click the button labeled [+ New]
5. Build a graph by clicking [Add Panel] -> [Graph]
6. Leave the graph editor by clicking back to dashboard
7. Click on the title of the graph until a pop up box appears. Then click [Share]
8. Click the button [Direct Link Rendered Image] in the pop up that appears. 

## Extra Info
When searching through the issues on grafana's github page I came across the follwing issues
1. [windows specific](https://github.com/grafana/grafana/issues/3657)
2. [macos specific](https://github.com/grafana/grafana/issues/2662)
The common theme is that these platforms aren't standard linux machines and they build grafana from source. In both of those issues they close them by saying we need to have a phantomjs binary in `/var/lib/grafana/vendor/phantomjs` when building from source. When looking at the [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/monitoring/grafana/default.nix) for grafana any mention of phantomjs is missing. I would submit a pr adding in phantomjs to the default.nix but I know next to nothing about how golang or how go builds. 

## Technical details

* System: (16.09pre85931.125ffff)
* Nix version: (1.11.2)
* Nixpkgs version: (16.09pre85931.125ffff)

**Comment by cransom** [comment]
The fix was committed for this last week and it's available in the latest nixos-unstable channel.

**Comment by grahamc** [comment]
Thanks! Please ping if this isn't fixed on the new unstable, and we'll reopen :)

**Comment by mckeankylej** [comment]
The fix doesn't fully solve the issue I think we patch phantomjs' dependencies. I now get a png that looks like this:
![notfoundgrafana](https://cloud.githubusercontent.com/assets/10640231/17104093/61a80ae4-524f-11e6-81e0-b243ea8e29ae.png)
And when I look through `journalctl` I see the following error:
```sh
msg="PhantomRenderer::renderToPng url [http://localhost:3000/dashboard-solo/new?panelId=1&from=1469433180340&to=1469454780341&width=1000&height=500]"
Jul 25 13:53:04 grafana grafana-server[275]: Error: undefined is not an object (evaluating 'b.$$route.pageClass')
Jul 25 13:53:04 grafana grafana-server[275]: http://localhost:3000/public/app/boot.8ba215a1.js:28:59476
Jul 25 13:53:04 grafana grafana-server[275]: $broadcast@http://localhost:3000/public/app/boot.8ba215a1.js:36:69848
Jul 25 13:53:04 grafana grafana-server[275]: http://localhost:3000/public/app/boot.8ba215a1.js:8:110832
Jul 25 13:53:04 grafana grafana-server[275]: h@http://localhost:3000/public/app/boot.8ba215a1.js:36:36230
Jul 25 13:53:04 grafana grafana-server[275]: http://localhost:3000/public/app/boot.8ba215a1.js:36:36402
Jul 25 13:53:04 grafana grafana-server[275]: $eval@http://localhost:3000/public/app/boot.8ba215a1.js:36:68457
Jul 25 13:53:04 grafana grafana-server[275]: $digest@http://localhost:3000/public/app/boot.8ba215a1.js:36:66970
Jul 25 13:53:04 grafana grafana-server[275]: $apply@http://localhost:3000/public/app/boot.8ba215a1.js:36:68747
Jul 25 13:53:04 grafana grafana-server[275]: http://localhost:3000/public/app/boot.8ba215a1.js:34:61513
Jul 25 13:53:04 grafana grafana-server[275]: g@http://localhost:3000/public/app/boot.8ba215a1.js:35:8417
Jul 25 13:53:04 grafana grafana-server[275]: h@http://localhost:3000/public/app/boot.8ba215a1.js:34:38469
Jul 25 13:53:04 grafana grafana-server[275]: ha@http://localhost:3000/public/app/boot.8ba215a1.js:34:38748
Jul 25 13:53:04 grafana grafana-server[275]: http://localhost:3000/public/app/boot.8ba215a1.js:10:36668
Jul 25 13:53:04 grafana grafana-server[275]: O@http://localhost:3000/public/app/boot.8ba215a1.js:6:1544
Jul 25 13:53:04 grafana grafana-server[275]: K@http://localhost:3000/public/app/boot.8ba215a1.js:6:1173
Jul 25 13:53:04 grafana grafana-server[275]: when@http://localhost:3000/public/app/boot.8ba215a1.js:6:4847
Jul 25 13:53:04 grafana grafana-server[275]: run@http://localhost:3000/public/app/boot.8ba215a1.js:6:3886
Jul 25 13:53:04 grafana grafana-server[275]: _drain@http://localhost:3000/public/app/boot.8ba215a1.js:5:106318
Jul 25 13:53:04 grafana grafana-server[275]: drain@http://localhost:3000/public/app/boot.8ba215a1.js:5:78654
Jul 25 13:53:04 grafana grafana-server[275]:   http://localhost:3000/public/app/boot.8ba215a1.js:36
``` 
ping @grahamc @cransom

**Comment by mckeankylej** [comment]
Thanks!

**Comment by fpletz** [comment]
Hmm, weird, I have a grafana instance deployed from master a few weeks ago that can generate images for graphs without problems. It was broken before with the new version, that's why I fixed it with febcd39afa6dff017290d3c56b7c545c8e05659b.

**Comment by mckeankylej** [comment]
Works on latest unstable closing.
