### ISSUE TITLE
Munin: ability to use plugins from munin-contrib

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#17895]
Munin has a wide range of plugins at https://github.com/munin-monitoring/contrib, we should support using them.

I'm particularly interested into raid monitoring at the moment.

**Comment by danbst** [comment]
I have a WIP for munin 2.999, and rework for munin service (munin 3 will contain nice webui standalone server). Should I publish this WIP? It has some plugins fixed, and community plugins are on my todo List.

**Comment by domenkozar** [comment]
Sure! I'd prefer to use stable version but let's see if something can be extracted :)

**Comment by domenkozar** [comment]
@danbst did you get somewhere with this?

**Comment by Profpatsch** [comment]
(triage) can we close this in favor of the PR?

**Comment by ToxicFrog** [comment]
A workable stopgap until full contrib support can be implemented might be:

 1. add a `services.munin-node.extraPluginConfig` option that's appended to `munin-plugin.conf`, in the same manner as `services.munin-node.extraConfig`
 1. add a `services.munin-node.extraPlugins` option that lists additional plugin files to be symlinked into /etc/munin/plugins; at the moment it just blindly accepts whatever `munin-node-configure` outputs
 1. add a `services.munin-node.disabledPlugins` to replace the existing hard-coded disablement of `diskstats` (which may not even be needed anymore, but if it is we can make that the default value)

This lets users disable plugins at will (useful since `munin-node-configure` tends to be very aggressive in what it enables), and add new plugins by manually downloading them and referencing them from `extraPlugins` -- which isn't as nice as having all the contrib plugins available as part of the munin build, but is an improvement on the status quo.

**Comment by ToxicFrog** [comment]
I started work on this. It's more complicated than it looks, and I ran into some other issues I want to fix while I'm in there, but it's coming along nicely.

**Comment by ToxicFrog** [comment]
@florianjacob #51980

**Comment by florianjacob** [comment]
As #51980 was merged, this is resolved now.

**Comment by ToxicFrog** [comment]
IMO this isn't fully resolved until `munin-contrib` is also packaged so users don't have to manually download it and fish individual plugins out of it for use with `extraPlugins` -- this should be pretty simple, I just haven't had the bandwidth to do it.

**Comment by florianjacob** [comment]
Makes sense, I thought those were delivered with the main package already.

**Comment by ToxicFrog** [comment]
No, only the core munin plugins are (contrib is a separate and much more eclectic repo) and I was in a hurry and already had munin-contrib checked out in /usr/src, so I added a feature to load arbitrary munin plugins, pointed that at my local checkout and concluded that was good enough for the moment.

Once munin-contrib is packaged it means that stuff like this:

    extraAutoPlugins = [
      /usr/src/munin-contrib/plugins/zfs
    ];

gets replaced with this:

    extraAutoPlugins = [
      ${pkgs.munin-contrib}/plugins/zfs
    ];

while still letting users who have written their own plugins outside contrib reference them directly in `extraPlugins` and `extraAutoPlugins`.

I don't think munin-contrib needs any sort of installation procedure, it's just fetch+unpack, so I may see if I can get it packaged soon. It should be an easy review so hopefully it doesn't languish unmerged for _too_ long and then we can close this.

**Comment by ToxicFrog** [comment]
This is still relevant.
