### ISSUE TITLE
vscode: "Extensions have been modified on disk. Please reload the window."

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#180736]
### Describe the bug
Very often, when opening Visual Studio Code (Codium in my case), or when opening a new folder, if you have with many extensions, the message in the title may appear.
I have no idea what exactly causes this to happen. With the many extensions I use, this message appears more than half of the time.

I managed to make the message spawn with only two extensions, but it isn't consistent at all (I managed to do it twice):

### Steps To Reproduce
1. Install vscode with the extensions below (it can also be installed with `nix-shell`);
2. Open `code` (`codium` in my case). Maybe also load a folder;
3. You may see the notification: "Extensions have been modified on disk. Please reload the window.".

### Expected behavior
The notification shouldn't appear.

### Additional context
Here are the logs.
The notification message is in the logs, so it can be searched, then look the context around.

With many extensions: <redacted>
```
<redacted>
```

With few extensions: <redacted>
```
<redacted>
```

### Notify maintainers
@Synthetica9 @turion @bobby285271 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.9-zen1, NixOS, 22.11 (Raccoon), 22.11pre390234.2770cc0b1e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by winterqt** [comment]
Fixed upstream: https://github.com/microsoft/vscode/issues/151370.

**Comment by SuperSamus** [comment]
Sorry, saw another issue about that in the repo that was closed, making me think it was a NixOS issue.
([This one](https://github.com/Microsoft/vscode/issues/39758))

**Comment by SuperSamus** [comment]
I still experience the issue on VSCodium 1.69.1.
Clearing the cache also didn't fix it.

**Comment by winterqt** [comment]
The fix I mentioned is still only released to Insiders, I'll keep this open until we have the release version that contains this fix packaged.
