### ISSUE TITLE
NetworkManager doesn't start up automatically when NetworkManager-wait-online is disabled

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#181237]
### Describe the bug
The NetworkManager service doesn't start automatically.
I need to manually start it  each time with: `sudo systemctl start NetworkManager.service`
### Additional context
I can see this in my system journal:
```
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Reached target Network.
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Started Network Manager.
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Started Network Manager Script Dispatcher Service.
Jul 12 16:16:18 nixos-wlaptop systemd[1]: network-local-commands.service: Job network-local-commands.service/start failed with result 'dependency'.
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Dependency failed for Extra networking commands..
Jul 12 16:16:18 nixos-wlaptop systemd[1]: network-local-commands.service: Bound to unit network-setup.service, but unit isn't active.
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Starting Network Manager...
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Starting Network Manager Script Dispatcher Service...
Jul 12 16:16:18 nixos-wlaptop systemd[1]: Reached target All Network Interfaces (deprecated).
```
I am using sway, and I have `networking.networkmanager.enable = true;` in my configuration.nix.
I have also disabled: ` systemd.services.NetworkManager-wait-online.enable = false;` for a faster boot.
### Notify maintainers
 @jtojnar @domenkozar @obadz @maxeaubrey 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.1-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre390948.5f43d8b088d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
send your configuration file and remove the disabling of wait-online

**Comment by QuantMint** [comment]
> send your configuration file and test removing the disabling of wait-online

Enabling `systemd.services.NetworkManager-wait-online.enable` makes it work, but my system used to work with the service disabled for months without any issue.
Also, the error in the system journal persists anyway.
My config is pretty huge and in multiple files, but this is everything related to networking:
```
 networking = {
    useDHCP = false; # Deprecated, so set to false.
    nameservers = [
      "2a10:50c0::ad1:ff"
      "2a10:50c0::ad2:ff"
      "94.140.14.14"
      "94.140.15.15"
    ];
  };
  networking = {
    networkmanager = {
      enable = true;
      wifi.macAddress = "random";
    };
    firewall.trustedInterfaces = [ "enp8s0" ];
  };
    systemd.services.NetworkManager-wait-online.enable = false;
```

**Comment by Artturin** [comment]
What is the last nixos-unstable revision in which it worked

**Comment by dschrempf** [comment]
Not sure if this is realted, but `network-local-commands.service` also fails on my machines with the following error (`journalctl -x` output):

```
Jul 18 10:05:21 schwarzbaer systemd[1]: network-local-commands.service: Bound to unit network-setup.service, but unit isn't active.
Jul 18 10:05:21 schwarzbaer systemd[1]: Dependency failed for Extra networking commands..
░░ Subject: A start job for unit network-local-commands.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit network-local-commands.service has finished with a failure.
░░
░░ The job identifier is 91 and the job result is dependency.
```

It may be related to https://github.com/NixOS/nixpkgs/pull/179163, but I do not know.

**Comment by Artturin** [comment]
> Not sure if this is realted, but `network-local-commands.service` also fails on my machines with the following error (`journalctl -x` output):
> 
> ```
> Jul 18 10:05:21 schwarzbaer systemd[1]: network-local-commands.service: Bound to unit network-setup.service, but unit isn't active.
> Jul 18 10:05:21 schwarzbaer systemd[1]: Dependency failed for Extra networking commands..
> ░░ Subject: A start job for unit network-local-commands.service has failed
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░
> ░░ A start job for unit network-local-commands.service has finished with a failure.
> ░░
> ░░ The job identifier is 91 and the job result is dependency.
> ```
> 
> It may be related to [ec00b4b](https://github.com/NixOS/nixpkgs/commit/ec00b4bb1186719bbee30a89ca7f519c30001abd), see #179163, but I do not know.

Thanks for finding that 

Could one of you test the PR https://nixos.wiki/wiki/Nixpkgs/Reviewing_changes#Modules if it works ill merge

**Comment by dschrempf** [comment]
Hi! Sorry from the NixOS Wiki page I can not see what we should do. The example with flakes seems to test the branch `pipewireldpath`, and includes some `pipewire` specific configuration settings. Maybe we could improve the Wiki page?

Anyways, I saw that the PR was merged a few hours ago, so I guess it works!

**Comment by Artturin** [comment]
> Hi! Sorry from the NixOS Wiki page I can not see what we should do. The example with flakes seems to test the branch `pipewireldpath`, and includes some `pipewire` specific configuration settings. Maybe we could improve the Wiki page?

yes since its an example

> Anyways, I saw that the PR was merged a few hours ago, so I guess it works!

i only tested it by running the tests with `nix build -f . "nixosTests.networking.scripted"` 

though all of those already worked before

**Comment by dschrempf** [comment]
I see!

I just tried this on `nixpkgs-unstable-small`, and the problem is fixed! Thank you!

@QuantMint is it Ok for you to close?

**Comment by QuantMint** [comment]
> I see!
> 
> I just tried this on `nixpkgs-unstable-small`, and the problem is fixed! Thank you!
> 
> @QuantMint is it Ok for you to close?

The problem isn't fixed yet, when NetworkManager-wait-online gets disabled networkmanager doesn't start at all.

**Comment by QuantMint** [comment]
The NetworkManager service doesn't start because network.target doesn't start, but it isn't clear to me how network.target is related with NetworkManager-wait-online.

I also don't understand how it is possible that networkmanager is both a dependency and depends on network.target??

```
❯ systemctl list-dependencies network.target
network.target
○ ├─network-local-commands.service
○ ├─NetworkManager-dispatcher.service
○ ├─NetworkManager.service
○ └─network-interfaces.target
❯ systemctl list-dependencies network.target --reverse
network.target
○ ├─cups.service
○ └─NetworkManager.service
```
Maybe someone more familiar NetworkManager services can help me?

**Comment by QuantMint** [comment]
I tried again recently and the issue got fixed somehow.
