### ISSUE TITLE
python-wrapper broken by recent re-factoring

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#1826]
The following attribute used to work fine:

    python27Full = pkgs.python27Full.override {
      extraLibs = with pkgs.pythonPackages; [pkgs.pylint pkgs.scons];
      postBuild = ''
        cd ${pkgs.pylint}/bin
        for i in *; do
          rm $out/bin/$i
          sed -r -e "s|^exec |exec $out/bin/python -- |" <$i >$out/bin/$i
          chmod +x $out/bin/$i
        done;
      '';
    };

but after bf5d6fb9b1c12a919853f15571b5a012f87fd928 its broken:

    $ nix-env -p /tmp/yo -iA python27Full
    replacing old `python-2.7.6-wrapper'
    installing `python-2.7.6-wrapper'
    these derivations will be built:
      /nix/store/k6rd60c4xmjp9590blifa2603ygpqzc3-python-2.7.6-wrapper.drv
    building path(s) `/nix/store/hk8nc4bzfcrcpxgdi237x9mnwbpvkn2p-python-2.7.6-wrapper'
    building /nix/store/hk8nc4bzfcrcpxgdi237x9mnwbpvkn2p-python-2.7.6-wrapper
    collision between `/nix/store/5p6p5p2rz0x04vhzpvj66zpd7kqx2cw6-python2.7-logilab-astng-0.24.1/bin/pytest' and `/nix/store/ib2jamy5n1i9wmb1pb9lbw3rwkc0pfbn-python2.7-logilab-common-0.58.2/bin/pytest' at /nix/store/9z6d76pz8rr7gci2n3igh5dqi7ac5xqj-builder.pl line 72.
    builder for `/nix/store/k6rd60c4xmjp9590blifa2603ygpqzc3-python-2.7.6-wrapper.drv' failed with exit code 2
    error: build of `/nix/store/k6rd60c4xmjp9590blifa2603ygpqzc3-python-2.7.6-wrapper.drv' failed

**Comment by domenkozar** [comment]
@peti why did you close it?

**Comment by peti** [comment]
Because I don't have that problem any more. It appears to have been fixed a long time ago. I don't remember anymore who fixed it, but someone committed a change that made a difference.

**Comment by peti** [comment]
@domenkozar, why did you re-open it?

**Comment by domenkozar** [comment]
Because it's still not fixed, packages using setuptools namespaces have problems/collisions.

**Comment by peti** [comment]
Well, all I can say is that the issue I intended to report with this ticket does no longer exist, so I'd rather not keep this ticket open. Would you mind opening a new ticket for that topic?

**Comment by domenkozar** [comment]
Sure!
