### ISSUE TITLE
Unable to build kernel-4.7.7

### ISSUE THREAD

**Issue by mrobbetts** [NixOS/nixpkgs#19698]
## Issue description

When trying to do a nixos-rebuild for the last few days (I'm tracking master), I get the following failure for the kernel build:

```
these derivations will be built:
  /nix/store/qpyva026rnf1w1nz60wg5p4n6x5lb8pp-linux-config-4.7.7.drv
  /nix/store/z6m5y7v9gxgjpq4qxypiby30flk1yvff-linux-4.7.7.drv
  /nix/store/vqp258snxq2rz2qc5a74906hc9vdgdb6-firmware.drv
  /nix/store/3n2q8k8jg7a7a62md9ccbw861jgq1khh-etc-nixos.conf.drv
  /nix/store/51ixn0wblv7nr61259hc9fr708cf2ngq-udev-rules.drv
  /nix/store/daizsns4wcrkyhk6pxdp31qrbpjrnl55-system-path.drv
  /nix/store/r88cllvmj342si458h20gj721ya53mw2-dbus-conf.drv
  /nix/store/zx1yndrr9w2irmdjb2rdn7m1wcyp4mcy-unit-dbus.service.drv
  /nix/store/74dhmzsa7v577rk08d2588ycsl5lkzjv-user-units.drv
  /nix/store/4yp0a1mjwy92afrijycrms2zs1nx8phc-unit-dbus.service.drv
  /nix/store/az50y30l6ardalk29rwrr7msrpwg6ygn-unit-systemd-udevd.service.drv
  /nix/store/q6zhk65z21707lgkkm1k46jrbspz1jgk-nixos.conf.drv
  /nix/store/cy9dvw476i2avkhqbi0hzy6b29jqn3v3-unit-systemd-modules-load.service.drv
  /nix/store/zq5kvbxp06vb3k65hljg5wg8piplxja8-unit-polkit.service.drv
  /nix/store/h499ajjyqbfgww8b3z88p03whdrsmbv7-system-units.drv
  /nix/store/nk99q1365c7wh5757jjgxxbhi2pns6xh-hwdb.bin.drv
  /nix/store/0lhmgdcpl3ynwn5cipygnr7sl9l4fn46-etc.drv
  /nix/store/aps0spi9vv8rmk7wrimij2739pyrssc2-kernel-modules.drv
  /nix/store/r88hzinnz6vwwrrhgrg1hn3v7amqfj4m-kernel-modules-shrunk.drv
  /nix/store/skv02rzg25gzj112a6g8mkdxvwdzhcb8-stage-1-init.sh.drv
  /nix/store/dr8n03wlsc9wrja9myxdb8yjxm7lq2i8-initrd.drv
  /nix/store/6n22bssjdn7b5cnbrb5lc5ki7vxfs81j-nixos-system-braid-17.03.git.7b4a9cd.drv
building path(s) ‘/nix/store/c8qi87lyaxvy67h97l9qi0c51zms0zsh-hwdb.bin’
building path(s) ‘/nix/store/w0v4cqnxi56acp8py6x5qb12y64a8pan-nixos.conf’
building path(s) ‘/nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules’
building path(s) ‘/nix/store/y07m8n8x07wy1pbmxplziv8iaqi5n94z-system-path’
Adding hwdb files for package /nix/store/3igi1j0mg5n8dar78npiihdc1wvfvk30-systemd-231
Adding hwdb files for package /nix/store/hidzqkak3nwbqw09gdjs69gqaw3j33cl-mdadm-3.3.4
Adding hwdb files for package /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140
Adding hwdb files for package /nix/store/gvs4454dm5d4493l6fzsl6hmka84rzr1-udisks-2.1.6
Adding hwdb files for package /nix/store/1zm5lcp78yvwx1kd7lm5zygq9r0v3i1p-extra-udev-rules
Adding hwdb files for package /nix/store/ralxfrhzqm8016gsaqy1d2j9bdbvv2fn-extra-hwdb-file
Adding hwdb files for package /nix/store/9z91snhvz99x60419g1ann86siqw0mbc-alsa-utils-1.1.0
Adding hwdb files for package /nix/store/j3cy2blqphb9s0va19cnyiaj22c8zkqf-gradm-3.1-201608131257
Adding hwdb files for package /nix/store/sh0sd1nv279kgcmv7gi9p7bnw4f9xiqh-crda-3.18
Generating hwdb database...
Adding rules for package /nix/store/hidzqkak3nwbqw09gdjs69gqaw3j33cl-mdadm-3.3.4
Copying /nix/store/hidzqkak3nwbqw09gdjs69gqaw3j33cl-mdadm-3.3.4/lib/udev/rules.d/63-md-raid-arrays.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/63-md-raid-arrays.rules
Copying /nix/store/hidzqkak3nwbqw09gdjs69gqaw3j33cl-mdadm-3.3.4/lib/udev/rules.d/64-md-raid-assembly.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/64-md-raid-assembly.rules
building path(s) ‘/nix/store/7fwjwdmxl9xlifz0fzcll731gk1vycnj-linux-config-4.7.7’
Adding rules for package /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140
Copying /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140/lib/udev/rules.d/10-dm.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/10-dm.rules
Copying /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140/lib/udev/rules.d/11-dm-lvm.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/11-dm-lvm.rules
Copying /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140/lib/udev/rules.d/13-dm-disk.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/13-dm-disk.rules
Copying /nix/store/02dj97lpkllg21b57hzw69j58yh5jyy2-lvm2-2.02.140/lib/udev/rules.d/95-dm-notify.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/95-dm-notify.rules
Adding rules for package /nix/store/gvs4454dm5d4493l6fzsl6hmka84rzr1-udisks-2.1.6
Copying /nix/store/gvs4454dm5d4493l6fzsl6hmka84rzr1-udisks-2.1.6/lib/udev/rules.d/80-udisks2.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/80-udisks2.rules
Adding rules for package /nix/store/1zm5lcp78yvwx1kd7lm5zygq9r0v3i1p-extra-udev-rules
Copying /nix/store/1zm5lcp78yvwx1kd7lm5zygq9r0v3i1p-extra-udev-rules/etc/udev/rules.d/99-local.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/99-local.rules
Adding rules for package /nix/store/ralxfrhzqm8016gsaqy1d2j9bdbvv2fn-extra-hwdb-file
Adding rules for package /nix/store/9z91snhvz99x60419g1ann86siqw0mbc-alsa-utils-1.1.0
Copying /nix/store/9z91snhvz99x60419g1ann86siqw0mbc-alsa-utils-1.1.0/lib/udev/rules.d/90-alsa-restore.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/90-alsa-restore.rules
Adding rules for package /nix/store/j3cy2blqphb9s0va19cnyiaj22c8zkqf-gradm-3.1-201608131257
Copying /nix/store/j3cy2blqphb9s0va19cnyiaj22c8zkqf-gradm-3.1-201608131257/etc/udev/rules.d/80-grsec.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/80-grsec.rules
Adding rules for package /nix/store/sh0sd1nv279kgcmv7gi9p7bnw4f9xiqh-crda-3.18
Copying /nix/store/sh0sd1nv279kgcmv7gi9p7bnw4f9xiqh-crda-3.18/lib/udev/rules.d/85-regulatory.rules to /nix/store/d4iah5rqqghw542b71nndx1bqd0my5g6-udev-rules/85-regulatory.rules
collision between `/nix/store/ip4rh8n3p6ajnnf584wm2qj2x3ak73i8-coreutils-8.25/share/man/man1/groups.1.gz' and `/nix/store/58xnax8r36hdf2qnsfrn6dqnzciwgz7f-shadow-4.2.1-man/share/man/man1/groups.1.gz'
unpacking sources
unpacking source archive /nix/store/3ln0w66rdgb12yj4107j3g2c0ic1j3xx-linux-4.7.7.tar.xz
collision between `/nix/store/mvsk01qj2aq1kgbnf4nrbsi7rc0g0zc3-bind-9.10.4-P3-bin/bin/host' and `/nix/store/na7whsi91m4j5kasm3kyiqfs5a69rp9q-bind-9.10.4-P3-host/bin/host'
Checking that all programs called by relative paths in udev rules exist in /nix/store/3igi1j0mg5n8dar78npiihdc1wvfvk30-systemd-231/lib/udev... OK
Checking that all programs called by absolute paths in udev rules exist... OK
building path(s) ‘/nix/store/yy741d0bvasl4wmfcbwa8mc9vs01l1kh-unit-systemd-modules-load.service’
building path(s) ‘/nix/store/kfqvfwrischdvyrlc0madvzqklpkax2z-unit-systemd-udevd.service’
created 5138 symlinks in user environment
install-info: warning: no info dir entry in `/nix/store/y07m8n8x07wy1pbmxplziv8iaqi5n94z-system-path/share/info/time.info'
building path(s) ‘/nix/store/01w8fp73h6mixz82dbs5v2pz2a6d3rgv-dbus-conf’
building path(s) ‘/nix/store/00dndhdkbf6d06syqddgiprrz74w3dpr-unit-polkit.service’
building path(s) ‘/nix/store/c2mdqzasyg4qpv13rdz0gf2q4wvzj809-unit-dbus.service’
building path(s) ‘/nix/store/svnhw5x1fdghl9gdmh4agzsazq1d2lyf-unit-dbus.service’
building path(s) ‘/nix/store/f0k5ycgwc4v6h17wa2rv7psii9jc17r9-system-units’
building path(s) ‘/nix/store/q7acbi1zrzikvlmgja6xq5wqa051gg95-user-units’
source root is linux-4.7.7
setting SOURCE_DATE_EPOCH to timestamp 1475846525 of file linux-4.7.7/virt/lib/irqbypass.c
patching sources
stripping FHS paths in `./virt/lib/Makefile'...
stripping FHS paths in `./virt/Makefile'...
stripping FHS paths in `./usr/Makefile'...
stripping FHS paths in `./tools/vm/Makefile'...
...
...
[lots of more stripping FHS paths lines up here]
...
...
stripping FHS paths in `./Documentation/accounting/Makefile'...
stripping FHS paths in `./Documentation/Makefile'...
stripping FHS paths in `./Documentation/EDID/Makefile'...
stripping FHS paths in `./Documentation/DocBook/media/Makefile'...
stripping FHS paths in `./Documentation/DocBook/Makefile'...
applying patch /nix/store/gxmfgl658kal3m0chgvpz3ylld9cp478-grsecurity-3.1-4.7.7-201610101902.patch
patching file .gitignore
patching file Documentation/dontdiff
patching file Documentation/kbuild/makefiles.txt
patching file Documentation/kernel-parameters.txt
patching file Documentation/sysctl/kernel.txt
patching file Makefile
...
...
[lots of patching-file lines up here]
...
...
patching file sound/usb/line6/toneport.c
patching file tools/include/linux/compiler.h
patching file tools/perf/util/include/asm/alternative-asm.h
patching file tools/virtio/linux/uaccess.h
patching file virt/kvm/kvm_main.c
applying patch /nix/store/gxmfgl658kal3m0chgvpz3ylld9cp478-grsecurity-3.1-4.7.7-201610101902.patch
patching file .gitignore
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file .gitignore.rej
patching file Documentation/dontdiff
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
16 out of 16 hunks ignored -- saving rejects to file Documentation/dontdiff.rej
...
...
[literally hundreds more such patch errors are listed, before final failure]
...
...
patching file virt/kvm/kvm_main.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
11 out of 11 hunks ignored -- saving rejects to file virt/kvm/kvm_main.c.rej
builder for ‘/nix/store/qpyva026rnf1w1nz60wg5p4n6x5lb8pp-linux-config-4.7.7.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/z6m5y7v9gxgjpq4qxypiby30flk1yvff-linux-4.7.7.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/vqp258snxq2rz2qc5a74906hc9vdgdb6-firmware.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/aps0spi9vv8rmk7wrimij2739pyrssc2-kernel-modules.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3n2q8k8jg7a7a62md9ccbw861jgq1khh-etc-nixos.conf.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/r88hzinnz6vwwrrhgrg1hn3v7amqfj4m-kernel-modules-shrunk.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/0lhmgdcpl3ynwn5cipygnr7sl9l4fn46-etc.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/skv02rzg25gzj112a6g8mkdxvwdzhcb8-stage-1-init.sh.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/dr8n03wlsc9wrja9myxdb8yjxm7lq2i8-initrd.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/6n22bssjdn7b5cnbrb5lc5ki7vxfs81j-nixos-system-braid-17.03.git.7b4a9cd.drv’: 5 dependencies couldn't be built
error: build of ‘/nix/store/6n22bssjdn7b5cnbrb5lc5ki7vxfs81j-nixos-system-braid-17.03.git.7b4a9cd.drv’ failed
```

### Steps to reproduce
I'm not really sure. I have

```
security = {
                grsecurity = {
                        enable = true;
                        lockTunables = true;
                };
        };
```
in my `configuration.nix`, so this is a grsecurity-kernel build. Other than that, I'm not sure what I might be doing to earn the ire of this package.

Has anyone seen this?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`17.03.git.0dd3f7d (Gorilla)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.4`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"17.03.git.521e6b9"`

**Comment by NeQuissimus** [comment]
This must have something to do with grsec. The kernel builds fine otherwise. 

@joachifm is the resident grsecurity master :)

**Comment by joachifm** [comment]
The build succeeds on 16.09 (https://hydra.nixos.org/build/42376325) and unstable (https://hydra.nixos.org/build/41905516), but the tests only fail on the latter branch, giving the same error as in the OP.  As far as grsec is concerned, the 16.09 branch should be equivalent to master. How vexing ...

**Comment by joachifm** [comment]
(As an aside, if you're using this system for anything, building from master is not a good choice).

**Comment by mrobbetts** [comment]
[sorry for the temporary thread-jack]

> (As an aside, if you're using this system for anything, building from master is not a good choice).

@joachifm, is that so? I have it set this way because I found it difficult (or impossible?) to make changes to packages -- simple things, like proposing an update to a package -- when using the channel system.

There is a strong possibility I've missed the intended process, though, as I was piecing things together from guides and still don't understand it very well.

On the flip side, why is tracking master actively not a good choice? Of course, every now and then I'll get a package that fails to build; in the past, I have just waited a day or and it generally gets fixed -- and otherwise, I'll report it on here and it will get fixed. Are there deeper problems than this?

**Comment by NeQuissimus** [comment]
@mrobbetts I have been using `nixos-unstable-small` for a while now as my channel for my main laptop. I would not use an unstable channel for any of my servers but I have found it is fine for my own system.
If you look at https://github.com/NeQuissimus/DevSetup, this is how I handle my system. I have my user environment packages defined in /users/ and import custom nix expressions for things that are not in nixpkgs or stuff I want to try out. (I use the Sublime Text Dev builds for example, since I have a license for it)
It has been working fairly well for me that way.
`ux305c.nix` is my main `configuration.nix` for my laptop.

**Comment by joachifm** [comment]
@mrobbetts lack of testing is the primary reason. Just because a build passes doesn't mean the resulting program or combination of programs that make up the system config won't wreck your data, steal your bitcoins, and brick your hardware. Now, the test coverage is pretty weak, so you're still under significant risk, but you can be reasonably sure that basic stuff work as intended.

I'd never run anything but the latest release. Instead of using `nix-channel`, you can track the corresponding branch in the nixpkgs-channels repository, cherry-picking whatever additional stuff you need from upstream master. I develop stuff against a dedicated tree.
Use the -small channels if you always want the latest bugs, but I'd avoid the full unstable channel because it can get stuck for weeks at a time. I don't know your constraints etc of course, so these are just general remarks/my opinion.

**Comment by joachifm** [comment]
Anyway, I've pushed an update for grsecurity. I've yet to complete the build, but it proceeds beyond initial config so appears to fix this issue.

**Comment by mrobbetts** [comment]
@joachifm, ah, that all makes sense. I will probably change my configuration when I get a minute.

Also, thanks for pushing the update. Unfortunately, I'm still getting the same failure with it :/

**Comment by joachifm** [comment]
Hrm, I'm stumped, it works here, on current master. I've no idea what could account for this discrepancy ...

Can you try e.g., `nix-build /path/to/development/checkout -A linux_grsec_nixos.configfile`, ensuring there are no overrides and whatnot?

**Comment by joachifm** [comment]
Alright, I've reproduced this now. I'm fairly sure it's caused by da36847d925058fd86f027b64cc712c57be11ad8. With that commit, building a NixOS system with grsecurity fails, reverting it fixes the problem. cc @cstrahan

**Comment by joachifm** [comment]
So I guess this either means the grsec module needs to be adapted to the new code somehow, or there's a bug somewhere in the expansion of the `apply` logic (it's unclear to me whether it's the apply itself or the new extension stuff that's tripping up). The error message seems to indicate that the patch is applied twice.

**Comment by mrobbetts** [comment]
@joachifm, thanks for looking into this! If it helps, the command you gave me completes just fine.

Well done finding the offending commit. I'm curious though: since that commit landed in April, do you know why it has only broken things now? I've been using grsecurity on my nixos machine for a few months with no problems.

**Comment by joachifm** [comment]
@mrobbetts the changes to `linuxPackages` & related nixos module options didn't land in master until after 16.09 was released. The patch was under development for quite a while so it's probably been amended over and over again, retaining the original commit date.

Unfortunately, the new code is a bit too dense for me to quickly ascertain exactly what is happening, so I'd have to trace it out, perhaps over the weekend, but @cstrahan knows better than I how it's supposed to work. Until then I can only suggest switching to 16.09 or reverting locally.

**Comment by mrobbetts** [comment]
@joachifm, that makes perfect sense. Thanks for the analysis!

I've simply disabled grsecurity on my machine for now, as I still don't understand enough about nix to be able to really dig into this. I'll look forward to re-enabling again once this issue is sorted out. With any luck, the bug will be silly copy-pasta or something :)

**Comment by joachifm** [comment]
I believe I've "fixed" the problem, though not the root cause.

**Comment by mrobbetts** [comment]
@joachifm, thanks! FWIW, it builds fine for me now and seems to be working perfectly.

**Comment by joachifm** [comment]
@mrobbetts great. Thank you for testing
