### ISSUE TITLE
snowsql fails with missing libcrypto library

### ISSUE THREAD

**Issue by padhia** [NixOS/nixpkgs#199622]
### Describe the bug
`snowsql` fails with an error that a dependency is missing

### Steps To Reproduce
1. allow unfree packages: `export NIXPKGS_ALLOW_UNFREE=1`
2. run: `nix run nixpkgs#snowsql --impure -- --accountname unknown --username alice <<<"select current_user()"`
3. supply any text when prompted to enter a password

### Expected behavior
The command should either succeed when supplied with valid parameters or end with an error message to the effect that the parameters aren't valid.

### Screenshots
The following error is not one of the expected error:

```
The library libcrypto could not be found
If the error message is unclear, enable logging using -o log_level=DEBUG and see the log to find out the cause. Contact support for further help.
```

### Additional context
`snowsql` runs without the above error when `binutils` is also installed. 

`snowsql` is likely written in Python using `snowflake-connector-python` which had a known bug as described in [#176917 ](https://github.com/NixOS/nixpkgs/issues/176917).

Additional reference: https://github.com/dbt-labs/dbt-core/issues/3366#issuecomment-849764321

### Notify maintainers

@andehen 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.3, NixOS, 22.11 (Raccoon), 22.11.20221025.f994293`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(padhia): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by andehen** [comment]
Thanks for reporting this! I'll take a look at it when I have time.

**Comment by nathanruiz** [comment]
Fixed by #217234

**Comment by padhia** [comment]
Unfortunately, this bug isn't fixed yet. I still get the same error:

```
~❯ export NIXPKGS_ALLOW_UNFREE=1                                                                                                                                                 ~took 13s ❯
~❯ nix run nixpkgs#snowsql --impure -- --accountname unknown --username alice <<<"select current_user()"                                                                                  ~❯
Password:
The library libcrypto could not be found
If the error message is unclear, enable logging using -o log_level=DEBUG and see the log to find out the cause. Contact support for further help.
Goodbye!
```

**Comment by padhia** [comment]
If anyone else runs into this problem, I have this [flake](https://github.com/padhia/snowsql) that seems to have fixed this issue for me.
