### ISSUE TITLE
wrong NVM checksum for I219-V ethernet controller

### ISSUE THREAD

**Issue by pca006132** [NixOS/nixpkgs#202067]
### Describe the bug

My motherboard (a cheap B660M motherboard from MSI) uses Intel's I219-V (rev 11) Ethernet controller, which is controlled by the e1000e driver. However, the kernel driver reports "The NVM Checksum Is Not Valid", similar to the post in https://unix.stackexchange.com/questions/294753/intel-ethernet-connection-i219-v-not-working-under-linux-on-an-asuspro-b-laptop

### Steps To Reproduce
1. Get a motherboard with I219-V Ethernet controller.
2. Run the installer on it and boot.

### Expected behavior
There should be Ethernet connection detected.

### Additional context

From the post mentioned above, one possible fix is to comment out the checksum validation in the kernel driver. In fact, from https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1936998 it seems that the checksum validation is not really needed because the driver can no longer write back a correct checksum to it due to security reasons.

I tried using the patch and indeed that fixes the issue and I can have access to Ethernet. This issue is annoying because the Ethernet controller is the only controller on my motherboard, I have no WiFi modules or external Ethernet controllers around. I have to patch the kernel and compile the installer on another machine (because this too is broken in other distribution, e.g. Ubuntu 22.10 Desktop).

The exact patch I used: https://gist.github.com/pca006132/a32913653e360a718de8cf9906c50f0e
```nix
  boot.kernelPatches = [
    {
      name = "e1000e-bypass-checksum";
      patch = builtins.fetchurl {
        url = "https://gist.githubusercontent.com/pca006132/a32913653e360a718de8cf9906c50f0e/raw/2a74f266a8eb0693e09290c507a40a59dba72334/e1000e.diff";
        sha256 = "1ia27szwk099jrpq06d242kfs903dcq4bdv2k1vqcnlrr9wss69q";
      };
    }
  ];
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 22.05 (Quokka), 22.05.4270.b68a6a27adb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixpkgs-unstable"`
 - channels(pca006132): `"home-manager-22.05.tar.gz, nixpkgs-22.05, nixpkgs-unstable"`
 - nixpkgs: `/home/pca006132/.nix-defexpr/channels/nixpkgs`
```

**Comment by jacekkow** [comment]
There are two patches coming (hopefully) to the mainline that should fix it:
https://patchwork.ozlabs.org/project/intel-wired-lan/patch/22c8ffce-a0f4-4780-b722-492487d58b88@jacekk.info/
https://patchwork.ozlabs.org/project/intel-wired-lan/patch/28347e4f-c6a7-4194-8a80-34508891c8ec@jacekk.info/

Could you test those?

**Comment by pca006132** [comment]
@jacekkow I combined them into the following and replaced the patch I use:

```diff
diff --git a/drivers/net/ethernet/intel/e1000e/defines.h b/drivers/net/ethernet/intel/e1000e/defines.h
index 8294a7c4f122..ba331899d186 100644
--- a/drivers/net/ethernet/intel/e1000e/defines.h
+++ b/drivers/net/ethernet/intel/e1000e/defines.h
@@ -638,6 +638,9 @@ 
 /* For checksumming, the sum of all words in the NVM should equal 0xBABA. */
 #define NVM_SUM                    0xBABA
 
+/* Uninitialized ("empty") checksum word value */
+#define NVM_CHECKSUM_UNINITIALIZED 0xFFFF
+
 /* PBA (printed board assembly) number words */
 #define NVM_PBA_OFFSET_0           8
 #define NVM_PBA_OFFSET_1           9
diff --git a/drivers/net/ethernet/intel/e1000e/nvm.c b/drivers/net/ethernet/intel/e1000e/nvm.c
index e609f4df86f4..16369e6d245a 100644
--- a/drivers/net/ethernet/intel/e1000e/nvm.c
+++ b/drivers/net/ethernet/intel/e1000e/nvm.c
@@ -558,6 +558,12 @@  s32 e1000e_validate_nvm_checksum_generic(struct e1000_hw *hw)
 		checksum += nvm_data;
 	}
 
+	if (hw->mac.type == e1000_pch_tgp &&
+	    nvm_data == NVM_CHECKSUM_UNINITIALIZED) {
+		e_dbg("Uninitialized NVM Checksum on TGP platform - ignoring\n");
+		return 0;
+	}
+
 	if (checksum != (u16)NVM_SUM) {
 		e_dbg("NVM Checksum Invalid\n");
 		return -E1000_ERR_NVM;
diff --git a/drivers/net/ethernet/intel/e1000e/ich8lan.c b/drivers/net/ethernet/intel/e1000e/ich8lan.c
index 364378133526..df4e7d781cb1 100644
--- a/drivers/net/ethernet/intel/e1000e/ich8lan.c
+++ b/drivers/net/ethernet/intel/e1000e/ich8lan.c
@@ -4274,6 +4274,8 @@  static s32 e1000_validate_nvm_checksum_ich8lan(struct e1000_hw *hw)
 			ret_val = e1000e_update_nvm_checksum(hw);
 			if (ret_val)
 				return ret_val;
+		} else if (hw->mac.type == e1000_pch_tgp) {
+			return 0;
 		}
 	}
 
```

The kernel builds, but it doesn't work, `dmesg` still shows
```
e1000e 0000:00:1f.6: The NVM Checksum Is Not Valid
e1000e: probe of 0000:00:1f.6 failed with error -5
```

I am running Linux 6.6.92, probably a bit outdated, but I think it should not matter?

**Comment by jk-nf** [comment]
@pca006132 - no, if the patch applies it should not matter.

Could you also check a value of `hw->mac.type` of your card (alternatively just paste the line for the Ethernet controller from the output of `lspci -nn`) and additionally dump the NVM (`ethtool -e DEVNAME` - this requires reverting to the working patch first)?

**Comment by jacekkow** [comment]
@pca006132 - no, if the patch applies it should not matter.

Could you also check a value of `hw->mac.type` of your card (alternatively just paste the line for the Ethernet controller from the output of `lspci -nn`) and additionally dump the NVM (`ethtool -e DEVNAME` - this requires reverting to the working patch first)?

**Comment by pca006132** [comment]
@jacekkow 

```
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (17) I219-V [8086:1a1d] (rev 11)
```

NVM:
```
Offset		Values
------		------
0x0000:		04 7c 16 0e 81 b8 00 08 ff ff 34 20 01 00 68 00 
0x0010:		ff ff ff ff c3 10 46 7d 62 14 1d 1a 00 00 00 00 
0x0020:		00 00 00 00 00 80 05 a7 30 30 00 16 00 00 00 0c 
0x0030:		f4 18 00 0a 43 08 13 01 1c 1a ad ba 1c 1a 1d 1a 
0x0040:		ad ba 1c 1a ad ba 1c 1a 00 00 00 80 00 4e 86 08 
0x0050:		00 00 00 00 07 00 ff a0 20 00 00 00 00 0e 00 00 
0x0060:		00 01 00 40 28 12 07 40 ff ff ff ff ff ff ff ff 
0x0070:		ff ff ff ff ff ff ff ff ff ff 00 02 ff ff ff ff 
0x0080:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0090:		00 00 00 00 00 00 ff ff ff ff ff ff ff ff ff ff 
0x00a0:		94 b0 00 08 0a 00 04 90 b0 47 40 24 c2 e1 21 c3 
0x00b0:		3f 00 00 80 00 00 00 00 00 00 00 00 00 00 00 00 
0x00c0:		80 60 1f 00 00 48 10 00 40 60 1f 00 04 d3 11 00 
0x00d0:		03 0a 12 00 00 00 1f 00 04 b4 30 00 1c 00 31 00 
0x00e0:		06 b4 30 00 09 00 31 00 07 b4 30 00 10 00 31 00 
0x00f0:		0a b4 30 00 18 00 31 00 0c b4 30 00 18 00 31 00 
0x0100:		0d b4 30 00 18 00 31 00 01 fd 30 00 2c 9c 31 00 
0x0110:		4c b6 30 00 05 00 31 00 ff ff ff ff ff ff ff ff 
0x0120:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0130:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0140:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0150:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0160:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0170:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0180:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0190:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x01f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0200:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0210:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0220:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0230:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0240:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0250:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0260:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0270:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0280:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0290:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x02f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0300:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0310:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0320:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0330:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0340:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0350:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0360:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0370:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0380:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0390:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x03f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0400:		69 53 84 03 01 00 00 00 00 00 00 00 00 00 00 00 
0x0410:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0420:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0430:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0440:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0450:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0460:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0470:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0480:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0490:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04a0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04b0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04c0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04d0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04e0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x04f0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0500:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0510:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0520:		00 00 00 00 00 00 00 00 03 3d 00 00 00 00 00 00 
0x0530:		00 00 00 00 00 00 00 00 00 00 00 00 bc 0c 00 00 
0x0540:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0550:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0560:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0570:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0580:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0590:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05a0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05b0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05c0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05d0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05e0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x05f0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0600:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0610:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0620:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0630:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0640:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0650:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0660:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0670:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0680:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0690:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06a0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06b0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06c0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06d0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06e0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x06f0:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0700:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0710:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0720:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0730:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0740:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0750:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0760:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0770:		00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0x0780:		00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff 
0x0790:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x07f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0800:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0810:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0820:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0830:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0840:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0850:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0860:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0870:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0880:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0890:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x08f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0900:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0910:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0920:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0930:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0940:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0950:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0960:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0970:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0980:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0990:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09a0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09b0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09c0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09d0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09e0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x09f0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0a90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0aa0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ab0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ac0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ad0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ae0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0af0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0b90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ba0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0bb0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0bc0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0bd0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0be0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0bf0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0c90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ca0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0cb0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0cc0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0cd0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ce0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0cf0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0d90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0da0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0db0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0dc0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0dd0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0de0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0df0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0e90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ea0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0eb0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ec0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ed0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ee0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ef0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f00:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f10:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f20:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f30:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f40:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f50:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f60:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f70:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f80:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0f90:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0fa0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0fb0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0fc0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0fd0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0fe0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
0x0ff0:		ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
```

**Comment by jacekkow** [comment]
Thanks! So it seems that your affected by both(!) issues (checksum valid bit unset AND checksum equal to 0xFFFF) but on Adler Lake (12th gen Adler Lake rather that 11th Tiger Lake).

Either patch (no need for both) should work if you change `e1000_pch_tgp` to `e1000_pch_adp`. Could you check that? I'll try to send a patch upstream once the current ones are merged.

**Comment by jacekkow** [comment]
BTW, @pca006132, you have the latest BIOS update installed?

**Comment by pca006132** [comment]
> Thanks! So it seems that your affected by both(!) issues (checksum valid bit unset AND checksum equal to 0xFFFF) but on Adler Lake (12th gen Adler Lake rather that 11th Tiger Lake).
> 
> Either patch (no need for both) should work if you change `e1000_pch_tgp` to `e1000_pch_adp`. Could you check that? I'll try to send a patch upstream once the current ones are merged.

Yeah it works now.


> BTW, [@pca006132](https://github.com/pca006132), you have the latest BIOS update installed?

Probably not... I haven't checked BIOS update manually for a long time, and it seems that my motherboard is not supported by fwupdmgr.

**Comment by jacekkow** [comment]
@pca006132 - if you could, please try to upgrade BIOS first (as it might have been fixed in some release). It should be possible to upgrade via a USB drive if your BIOS don't have an option to upgrade over the Internet.

**Comment by jacekkow** [comment]
@pca006132 - BTW, the expected changes in the ethtool output are:
```
-0x0000:		XX XX XX XX XX XX 00 08 ff ff 34 20 01 00 68 00
+0x0000:		XX XX XX XX XX XX 01 08 ff ff 34 20 01 00 68 00
                                          ^^
```
```
-0x0070:		ff ff ff ff ff ff ff ff ff ff 00 02 ff ff ff ff 
+0x0070:		ff ff ff ff ff ff ff ff ff ff 00 02 ff ff XX XX
                                                                  ^^^^^
```

**Comment by pca006132** [comment]
@jacekkow Thanks. Will try later once I have more time.

**Comment by pca006132** [comment]
> [@pca006132](https://github.com/pca006132) - have you had a moment to try a new BIOS?

Sorry forgot this for a while, will do this weekend.

**Comment by pca006132** [comment]
For some reason, MSI's firmware doesn't recognize the `.bin` file I downloaded from their webpage, and I cannot update the BIOS... The FS is fine: it can detect directories in the FS, but all files were missing. It seems that it can also update via Windows (they have a tool for that), but I don't have Windows on my machine.

**Comment by pca006132** [comment]
OK found the BIOS file (2025-08-18), should be updated now (I cannot enter grub and BIOS interface now after the update, so apparently something changed...). The NVM dump is identical to the old one, so I don't think the issue is fixed from BIOS update.

**Comment by pca006132** [comment]
@jacekkow ping
