### ISSUE TITLE
Bottles: Downloaded file [runtime.tar.gz] looks corrupted.

### ISSUE THREAD

**Issue by TheOddler** [NixOS/nixpkgs#204786]
### Describe the bug

When using [Bottles](https://usebottles.com/) at first startup it tries to download some runtime, but seems to fail.

### Steps To Reproduce
1. Install `bottles`
2. Start it
3. Click next, next, install
4. It's stuck at "Downloading" forever

### Expected behavior

It actually downloads the required runtime.

### Screenshots

![image](https://user-images.githubusercontent.com/1831376/205929419-f1c90552-5843-44c0-902d-b18f3c2d5a60.png)

When running `bottles` through the console I can see some additional info, and it shows:

```
13:48:04 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [c68c5c8df840a5c70bcfec32514e3af0] 
13:48:08 (ERROR) Removing corrupted file [runtime.tar.gz]. 
13:48:12 (ERROR) Extraction failed! Archive ends earlier than expected. 
13:48:16 (WARNING) No runtime found. 
13:48:19 (INFO) Installing component: [runtime-0.5]. 
Downloading runtime.tar.gz: 100% [==================================================>

13:48:23 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz]. 
13:48:23 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
13:48:27 (ERROR) Source cksum: [1747a350e92bd1e82d4d4e8ae617deeb] downloaded: [c68c5c8df840a5c70bcfec32514e3af0] 
13:48:30 (ERROR) Removing corrupted file [runtime.tar.gz]. 
13:48:34 (ERROR) Extraction failed! Archive ends earlier than expected. 
13:48:38 (WARNING) No runtime found. 
13:48:42 (INFO) Installing component: [runtime-0.5]. 
Downloading runtime.tar.gz: 100% [==================================================>

13:48:46 (INFO) Renaming [runtime.tar.gz] to [runtime.tar.gz]. 
13:48:46 (ERROR) Downloaded file [runtime.tar.gz] looks corrupted. 
...
```

This repeats forever.

### Additional context

Nothing, I think?

### Notify maintainers

@psydvl @SCOTT-HAMILTON 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.466.596a8e828c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by psydvl** [comment]
@TheOddler can you write what version of package you are using?
It seems this problem from old version that still in stable and resolved in one that in unstable channel

@SuperSamus it seems you're maintaining bottles better than me now, can you add yourself into maintainers with new PR and backport it?

**Comment by SuperSamus** [comment]
It's not solved by updating to 2022.11.14.
Seems to be an upstream issue: https://github.com/bottlesdevs/Bottles/issues/2278.

**Comment by TheOddler** [comment]
I'm indeed using the current version of the stable channel:

```
❯ bottles --version
2022.5.28-trento-3
```

I also tried the version from the unstable branch, but indeed that does not fix it as SuperSamus said. I'll keep an eye on the upstream issue.

**Comment by nash-pillai** [comment]
I was able to fix this by [manually downloading the runtime](https://github.com/bottlesdevs/runtime/releases/download/0.6/runtime.tar.gz) and extracting it into `$HOME/.data/bottles/runtimes/`

To be clear, inside the `runtimes` folder there should be a `runtime` folder, inside which are `lib`, `lib32`, `manifest.yml`, etc.
