### ISSUE TITLE
Jetbrains IDEA crash on start

### ISSUE THREAD

**Issue by pineapplehunter** [NixOS/nixpkgs#206110]
### Describe the bug
JEtbrains IDEA crashes when I try to run it.
It is happening on 22.11 and unstable but not on 22.05. The main difference I see is the JDK.

### Steps To Reproduce
1. Install jetbrains.idea-ultimate on nixos 22.11
2. run `idea-ultimate`

or

1. NIXPKGS_ALLOW_UNFREE=1 nix run --impure "nixpkgs/nixos-22.11#jetbrains.idea-ultimate"

### Expected behavior
IDE window opens and starts.
Expected behavior on 22.05 `NIXPKGS_ALLOW_UNFREE=1 nix run --impure "nixpkgs/nixos-22.05#jetbrains.idea-ultimate"`.

### Screenshots

N/A

### Additional context
<details>
<summary>Log</summary>

```shell
$ NIXPKGS_ALLOW_UNFREE=1 nix run --impure "nixpkgs/nixos-unstable#jetbrains.idea-ultimate"                                                                                       12/15/2022 02:23:59 午前
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Gtk-Message: 02:24:10.149: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:24:10.149: Failed to load module "canberra-gtk-module"
2022-12-15 02:24:10,398 [    292]   WARN - #c.i.i.p.PluginManager - Problems found loading plugins:
  The Japanese Language Pack / 日本語言語パック (id=com.intellij.ja, path=~/.local/share/JetBrains/IntelliJIdea2022.2/ja.223.218, version=223.218) plugin Plugin 'Japanese Language Pack / 日本語言語パック' (version '223.218') is not compatible with the current version of the IDE, because it requires build 223 or newer but the current build is IU-222.4345.14
  The Material Theme UI Lite (id=com.mallowigi.idea, path=~/.local/share/JetBrains/IntelliJIdea2022.2/Material Theme UI Lite, version=19.0.0) plugin Plugin 'Material Theme UI Lite' (version '19.0.0') is not compatible with the current version of the IDE, because it requires build 223.0000 or newer but the current build is IU-222.4345.14
  The Indent Rainbow (id=indent-rainbow.indent-rainbow, path=~/.local/share/JetBrains/IntelliJIdea2022.2/Indent Rainbow, version=2.1.0) plugin Plugin 'Indent Rainbow' (version '2.1.0') is not compatible with the current version of the IDE, because it requires build 223 or newer but the current build is IU-222.4345.14
  The Makefile Language (id=name.kropp.intellij.makefile, path=~/.local/share/JetBrains/IntelliJIdea2022.2/makefile, version=223.7571.203) plugin Plugin 'Makefile Language' (version '223.7571.203') is not compatible with the current version of the IDE, because it requires build 223.7571 or newer but the current build is IU-222.4345.14
  The EasySoC Chisel (id=org.easysoc.chisel, path=~/.local/share/JetBrains/IntelliJIdea2022.2/EasySOC Chisel, version=1.4.0) plugin Plugin 'EasySoC Chisel' cannot be loaded because it depends on plugin 'Scala' which failed to load
  The Scala (id=org.intellij.scala, path=~/.local/share/JetBrains/IntelliJIdea2022.2/Scala, version=2022.3.13) plugin Plugin 'Scala' (version '2022.3.13') is not compatible with the current version of the IDE, because it requires build 223.7571 or newer but the current build is IU-222.4345.14
  The Rust (id=org.rust.lang, path=~/.local/share/JetBrains/IntelliJIdea2022.2/intellij-rust, version=0.4.183.5026-223) plugin Plugin 'Rust' (version '0.4.183.5026-223') is not compatible with the current version of the IDE, because it requires build 223.7126 or newer but the current build is IU-222.4345.14
2022-12-15 02:24:12,447 [   2341] SEVERE - #c.i.i.StartupUtil - Cannot start app
com.intellij.ide.plugins.StartupAbortedException: Cannot start app
	at com.intellij.idea.StartupUtil.lambda$start$15(StartupUtil.java:265)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1418)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1529)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1495)
	at java.desktop/javax.swing.UIManager.getLookAndFeelDefaults(UIManager.java:1098)
	at java.desktop/javax.swing.plaf.synth.SynthLookAndFeel$AATextListener.propertyChange(SynthLookAndFeel.java:867)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport$1.run(Toolkit.java:2334)
	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport.firePropertyChange(Toolkit.java:2344)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Toolkit.setDesktopProperty(Toolkit.java:1605)
	at java.desktop/sun.awt.SunToolkit.fireDesktopFontPropertyChanges(SunToolkit.java:1722)
	at java.desktop/sun.awt.SunToolkit.setAAFontSettingsCondition(SunToolkit.java:1767)
	at java.desktop/sun.swing.SwingUtilities2.putAATextInfo(SwingUtilities2.java:177)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:1532)
	at com.intellij.ide.ui.laf.IdeaLaf.initComponentDefaults(IdeaLaf.java:33)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:153)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1566)
	at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$19(StartupUtil.java:516)
	at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.java:74)
	at com.intellij.ui.scale.JBUIScale.getSystemFontData(JBUIScale.java:365)
	at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$21(StartupUtil.java:514)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-12-15 02:24:12,452 [   2346] SEVERE - #c.i.i.StartupUtil - IntelliJ IDEA 2022.2.3  Build #IU-222.4345.14
2022-12-15 02:24:12,453 [   2347] SEVERE - #c.i.i.StartupUtil - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: N/A
2022-12-15 02:24:12,453 [   2347] SEVERE - #c.i.i.StartupUtil - OS: Linux

Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.ide.plugins.StartupAbortedException: Cannot start app
	at com.intellij.idea.StartupUtil.lambda$start$15(StartupUtil.java:265)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1418)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1529)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1495)
	at java.desktop/javax.swing.UIManager.getLookAndFeelDefaults(UIManager.java:1098)
	at java.desktop/javax.swing.plaf.synth.SynthLookAndFeel$AATextListener.propertyChange(SynthLookAndFeel.java:867)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport$1.run(Toolkit.java:2334)
	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport.firePropertyChange(Toolkit.java:2344)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Toolkit.setDesktopProperty(Toolkit.java:1605)
	at java.desktop/sun.awt.SunToolkit.fireDesktopFontPropertyChanges(SunToolkit.java:1722)
	at java.desktop/sun.awt.SunToolkit.setAAFontSettingsCondition(SunToolkit.java:1767)
	at java.desktop/sun.swing.SwingUtilities2.putAATextInfo(SwingUtilities2.java:177)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:1532)
	at com.intellij.ide.ui.laf.IdeaLaf.initComponentDefaults(IdeaLaf.java:33)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:153)
	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1566)
	at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$19(StartupUtil.java:516)
	at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.java:74)
	at com.intellij.ui.scale.JBUIScale.getSystemFontData(JBUIScale.java:365)
	at com.intellij.idea.StartupUtil.lambda$scheduleInitUi$21(StartupUtil.java:514)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

-----
Your JRE: 17.0.5+8-nixos amd64 (N/A)
/nix/store/720fjhrd7qmahhxafg9q75c489n9nci4-jetbrains-jdk-17.0.5-b653.14/lib/openjdk
java.lang.Error: no ComponentUI class for: javax.swing.JTextPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,kit=,typeHandlers=]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:146)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1077)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JEditorPane.<init>(JEditorPane.java:254)
	at java.desktop/javax.swing.JTextPane.<init>(JTextPane.java:100)
	at com.intellij.idea.Main.showMessage(Main.java:265)
	at com.intellij.idea.Main.showMessage(Main.java:221)
	at com.intellij.ide.plugins.StartupAbortedException.logAndExit(StartupAbortedException.java:91)
	at com.intellij.idea.StartupUtil.lambda$start$15(StartupUtil.java:265)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Also, a UI exception occurred on an attempt to show the above message
java.lang.NullPointerException: Cannot invoke "javax.swing.text.Caret.setDot(int)" because "this.caret" is null
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1691)
	at com.intellij.idea.Main.showMessage(Main.java:269)
	at com.intellij.idea.Main.showMessage(Main.java:221)
	at com.intellij.ide.plugins.StartupAbortedException.logAndExit(StartupAbortedException.java:91)
	at com.intellij.idea.StartupUtil.lambda$start$15(StartupUtil.java:265)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
</details>

### Notify maintainers

@edwtjo @gytis-ivaskevicius @steinybot @AnatolyPopov 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

checked on two systems.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixpkgs"`
 - channels(shogo): `"home-manager, nixpkgs"`
 - channels(riken): `""`
 - nixpkgs: `/home/shogo/.nix-defexpr/channels/nixpkgs`
```

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12, NixOS, 23.05 (Stoat), 23.05.20221213.1710ed1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"home-manager, nixos"`
 - channels(shogo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by gytis-ivaskevicius** [comment]
I tested on unstable with sway (Wayland) and it works fine.
Keep in mind if you guys use Wayland then the `_JAVA_AWT_WM_NONREPARENTING=1;` env variable must be set

**Comment by Lysanleo** [comment]
> I tested on unstable with sway (Wayland) and it works fine. Keep in mind if you guys use Wayland then the `_JAVA_AWT_WM_NONREPARENTING=1;` env variable must be set

thx, I did use gnome with Wayland and I've tried set this env variable with `environment.variable`, but the idea still didn't shown up.

**Comment by gytis-ivaskevicius** [comment]
Depending on your setup there is a good chance that the variable is not getting propagated to IntelliJ without a reboot. Try rebooting or executing it from terminal

**Comment by Lysanleo** [comment]
thx, I also tried reboot&executeing from terminal, but still, have the same problem.
I temporarily switched from gnome to KDE with Wayland, and the problem was solved in this somewhat weird way.

**Comment by pineapplehunter** [comment]
same here.
I tested with the command below on gnome(wayland) and still have the issue.

```shell
$ _JAVA_AWT_WM_NONREPARENTING=1 NIXPKGS_ALLOW_UNFREE=1 nix run --impure "nixpkgs/nixos-22.11#jetbrains.idea-ultimate"
```

**Comment by pineapplehunter** [comment]
It has been a while since I checked this, and it seems to be working fine now.
I will close this issue.
