### ISSUE TITLE
Jekyll does not include redcarpet

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#20617]
## Issue description

I'm currently attempting to build a site that uses the `redcarpet` gem for Markdown handling, and it's failing to build with the following error:

```
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-05-29-adios-hola.markdown':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

The offending line in the Jekyll configuration is the following:

```
markdown: redcarpet
```

It appears that the `redcarpet` dependency is missing, and there appears to be no way to specify it for Jekyll from within my `configuration.nix`.

### Steps to reproduce

1. Install Jekyll from nixpkgs.
2. Clone https://github.com/lizardhq/lizardhq-website.git
3. Run `jekyll build` in the repository

## Technical details

* System: 16.03.1337.c1c0484 (Emu)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.03.1337.c1c0484

**Comment by joepie91** [comment]
cc @pesterhazy, as the maintainer of this expression.

**Comment by Profpatsch** [comment]
(triage) has this been fixed in recent versions?

**Comment by raboof** [comment]
This issue still exists on current nixos-unstable (37bd39839acf99c5b738319f42478296f827f274). It is also present when setting `withOptionalDependencies`.

The reason it is not more often a problem is that the default markdown processor, kramdown, is included. redcarpet also seems in common use though.

**Comment by raboof** [comment]
ah, redcarpet support has been dropped upstream in jekyll 4.0

https://github.com/jekyll/jekyll/issues/7838
