### ISSUE TITLE
nixos-unstable doesn't update anymore

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#20735]
There have been no updates for over two weeks now, despite the fact there have been several [tested](http://hydra.nixos.org/job/nixos/trunk-combined/tested/all?page=1) builds succeeding since then.

Any ideas? I fear it might be some problem requiring a Hydra admin &ndash; /cc @edolstra &ndash; but I can't see anything suspicious.

**Comment by vcunat** [comment]
BTW, the **Darwin slaves** don't seem to work today, except for `mac6`. If unchanged, it would soon have impact on the nixpkgs-unstable channel.

**Comment by matthewbauer** [comment]
The Darwin machines are still acting up.

**Comment by domenkozar** [comment]
Fixed

**Comment by vcunat** [comment]
Thanks!
... but the Darwin situation still persists. On staging it will push us into dilemmas whether to wait very long or merge regardless of Darwin status. Now I'm waiting for a couple days already after Linux finished.

**Comment by vcunat** [comment]
Now 5/6 Darwin machines seem to work OK :-)
