### ISSUE TITLE
Lilypond build may need FONTCONFIG configuration

### ISSUE THREAD

**Issue by nxg** [NixOS/nixpkgs#209525]
### Describe the bug
Lilypond may need FONTCONFIG adjustments in build (macOS)

### Steps To Reproduce
1. Create `foo.ly`
2. `lilypond foo.ly`

I get

    % lilypond foo.ly 
    GNU LilyPond 2.22.2
    Fontconfig error: Cannot load default config file: No such file: (null)
    Fontconfig error: Cannot load default config file: No such file: (null)
    Segmentation fault: 11

The issue appears to be that there is no `/etc/fonts` on macOS, which upsets fontconfig terribly.

### Expected behavior
No crash

### Screenshots
n/a

### Additional context
In the context of a [discussion about a similar issue in ImageMagick](https://discourse.nixos.org/t/imagemagicks-convert-command-fails-due-to-fontconfig-error/20518/5), there is a suggestion that

    # Fontconfig error: Cannot load default config file
    FONTCONFIG_FILE = makeFontsConf {
      fontDirectories = [ freefont_ttf ];
    };

will help, in the appropriate `.nix` file, and that a workaround is

    % export FONTCONFIG_FILE=$(nix-build -E 'let pkgs = import <nixpkgs> { }; in pkgs.makeFontsConf { fontDirectories = [ pkgs.freefont_ttf ]; }')

The latter does indeed work for me, which suggests that the resolution might be similar.  However my nix-fu is very shaky, and I can't claim to fully understand the suggestion I'm here passing on (it looks plausible!, but who am I to say?).

### Notify maintainers

@marcweber @yurrriq (based on contents of `pkgs/misc/lilypond/default.nix` – correct?)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
     - system: `"x86_64-darwin"`
     - host os: `Darwin 22.2.0, macOS 10.16`
     - multi-user?: `no`
     - sandbox: `no`
     - version: `nix-env (Nix) 2.12.0`
     - channels(norman): `"nixpkgs"`
     - nixpkgs: `/Users/norman/.nix-defexpr/channels/nixpkgs`
```

**Comment by yurrriq** [comment]
Thanks for the report. Unfortunately I don't really have a Darwin machine I can test with. Might you be willing and able to open a PR?

**Comment by nxg** [comment]
I'd be happy to try to help test, but I'd need some handholding, as I've never fully got to grips with the Nix language.

I presume all that's required is to confirm that the suggested `FONTCONFIG_FILE` setting has the right effect on Darwin, but in which file?  I don't see a `.nix` in `/nix/store/4kkk1v4ijx3gp54d8pxgim6xmkh6ppcg-lilypond-2.22.2` on my machine (but I know enough to not expect that to be there).

If you can point me towards the right `.nix` file on <https://github.com/NixOS/nixpkgs/tree> (?), I can try making the edit and doing `...$CMD...` here to verify it works.

**Comment by yurrriq** [comment]
Awesome! I can try to help. Probably you'll want to edit https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/lilypond/default.nix. `stdenv.isDarwin` will surely come in handy too. Maybe something like this?

```nix
{ stdenv, lib # ...
, freefont_ttf
# ...
}:

stdenv.mkDerivation rec {
  # ...
  FONTCONFIG_FILE = lib.optional stdenv.isDarwin makeFontsConf {
    fontDirectories = [ freefont_ttf ];
  };
  # ...
}
```

**Comment by nxg** [comment]
I've tried:

    $ diff lilypond-{orig,mod}.nix
    3a4
    > , freefont_ttf, makeFontsConf 
    63a65,68
    >   };
    > 
    >   FONTCONFIG_FILE = lib.optional stdenv.isDarwin makeFontsConf {
    >     fontDirectories = [ freefont_ttf ];

but I suspect I'm using `nix-shell` incorrectly (I'm still contentedly using Nix as a magic wand):

    $ nix-shell lilypond-mod.nix 
    error: cannot evaluate a function that has an argument without a value ('stdenv')
    
           Nix attempted to evaluate a function as a top level expression; in
           this case it must have its arguments supplied either by default
           values, or passed explicitly with '--arg' or '--argstr'. See
           https://nixos.org/manual/nix/stable/#ss-functions.
    
           at /private/tmp/lilypond-mod.nix:1:3:
    
                1| { stdenv, lib, fetchurl, ghostscript, gyre-fonts, texinfo, imagemagick, texi2html, guile
                 |   ^
                2| , python3, gettext, flex, perl, bison, pkg-config, autoreconfHook, dblatex
    admetus:/tmp>

**Comment by yurrriq** [comment]
If you edit pkgs/misc/lilypond/default.nix in place, you can do like this from the nixpkgs project root:

```bash
nix shell .#lilypond
```

**Comment by nxg** [comment]
Ooookay.  I've unpacked a zip of the current nixpkgs repository, made the changes, and

    $ ls
    CONTRIBUTING.md		doc/			nixos/
    COPYING			flake.nix		pkgs/
    README.md		lib/
    default.nix		maintainers/
    $ nix --extra-experimental-features nix-command shell --extra-experimental-features flakes '.#lilypond'
    error: attempt to call something which is not a function but a list
    
           at /nix/store/3d0g3iqrhiw691hkbsp1nx56qwqlxcp7-source/pkgs/misc/lilypond/default.nix:67:21:
    
               66|
               67|   FONTCONFIG_FILE = lib.optional stdenv.isDarwin makeFontsConf {
                 |                     ^
               68|     fontDirectories = [ freefont_ttf ];
    (use '--show-trace' to show detailed location information)

    $ tail pkgs/misc/lilypond/default.nix 
        homepage = "http://lilypond.org/";
        license = licenses.gpl3;
        maintainers = with maintainers; [ marcweber yurrriq ];
        platforms = platforms.all;
      };
    
      FONTCONFIG_FILE = lib.optional stdenv.isDarwin makeFontsConf {
        fontDirectories = [ freefont_ttf ];
      };
    }

So we're not there yet.

**Comment by yurrriq** [comment]
Try this?

```diff
diff --git a/pkgs/misc/lilypond/default.nix b/pkgs/misc/lilypond/default.nix
index 759ecdc68e4..dda06f2fbfb 100644
--- a/pkgs/misc/lilypond/default.nix
+++ b/pkgs/misc/lilypond/default.nix
@@ -1,6 +1,7 @@
 { stdenv, lib, fetchurl, ghostscript, gyre-fonts, texinfo, imagemagick, texi2html, guile
 , python3, gettext, flex, perl, bison, pkg-config, autoreconfHook, dblatex
 , fontconfig, freetype, pango, fontforge, help2man, zip, netpbm, groff
+, makeFontsConf, freefont_ttf
 , makeWrapper, t1utils, boehmgc, rsync
 , texlive, tex ? texlive.combine {
     inherit (texlive) scheme-small lh metafont epsf fontinst;
@@ -50,6 +51,10 @@ stdenv.mkDerivation rec {
 
   enableParallelBuilding = true;
 
+  FONTCONFIG_FILE = lib.optional stdenv.isDarwin (makeFontsConf {
+    fontDirectories = [ freefont_ttf ];
+  });
+
   passthru.updateScript = {
     command = [ ./update.sh ];
     supportedFeatures = [ "commit" ];
```

**Comment by nxg** [comment]
Well, _that_ got my fans going...

    $ nix --extra-experimental-features nix-command\ flakes shell '.#lilypond'
    $ lilypond --version
    GNU LilyPond 2.24.1 (running Guile 2.2)
    
    Copyright (c) 1996--2023 by
      Han-Wen Nienhuys <hanwen@xs4all.nl>
      Jan Nieuwenhuizen <janneke@gnu.org>
      and others.
    
    This program is free software.  It is covered by the GNU General Public
    License and you are welcome to change it and/or distribute copies of it
    under certain conditions.  Invoke as `lilypond --warranty' for more
    information.
    $

So success, I think!

To avoid ambiguity, I've attached the actual [default.nix.gz](https://github.com/NixOS/nixpkgs/files/11366818/default.nix.gz) that worked.

**Comment by yurrriq** [comment]
Excellent! Would you mind opening a PR then, with a mention of this issue in the summary?

**Comment by nxg** [comment]
I can have a go at that tomorrow (I've found [the docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) which explain how to embark on that), but if you already have a checkout of this, ready to hand, mightn't it be less overhead if you dropped your code in there?

**Comment by yurrriq** [comment]
See also: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md.

Sure, it might be less overhead if I did it myself, but if you're willing, I'd prefer you open a PR and get proper attribution, since you reported, fixed, and tested this. What do you think?

**Comment by Joshua-Mastachi** [comment]
Hello!
I was wondering if this was fixed.
I'm trying to replace my previous Homebrew setup with Nix since i was having problems Homebrew on MacOS Mojave.
I tried intalling both `lilypond` and `lilypond-with-fonts`, but both of them give me errors like this one:
```
GNU LilyPond 2.24.1 (running Guile 2.2)
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
warning: cannot find fontconfig default config, skipping.
Fontconfig error: No writable cache directories
Usage: lilypond [OPTION]... FILE...

Typeset music and/or produce MIDI from FILE.

LilyPond produces beautiful music notation.
For more information, see https://lilypond.org

Options:
  -f, --formats=FORMATs            dump FORMAT,...  Also as separate options:
      --pdf                        generate PDF files (default)
      --svg                        generate SVG files
      --png                        generate PNG files
      --ps                         generate PostScript files
  -E, --eps                        generate Encapsulated PostScript files
  -O, --pspdfopt=KEY               set ps/pdf optimization to KEY, which is either
                                     'size' (default), 'TeX', or 'TeX-GS'
  -d, --define-default=SYM[=VAL]   set Scheme option SYM to VAL (default: '#t')
  -d, --define-default=no-SYM      set Scheme option SYM to '#f'
  -d, --define-default=help        show help for Scheme options
  -e, --evaluate=EXPR              evaluate scheme code
  -h, --help                       show this help and exit
  -H, --header=FIELD               dump \header field FIELD to file
                                     named BASENAME.FIELD
  -I, --include=DIR                append DIR to search path
  -i, --init=FILE                  use FILE as init file
  -j, --jail=USER,GROUP,JAIL,DIR   chroot to JAIL, become USER:GROUP
                                     and cd into DIR
  -l, --loglevel=LOGLEVEL          print log messages according to LOGLEVEL,
                                     which is either NONE, ERROR, WARNING,
                                     BASIC, PROGRESS, INFO (default), or DEBUG
  -o, --output=FILE                write output to FILE (suffix will be added)
                                     or to FOLDER, in which case the file name
                                     will be taken from the input file.
      --relocate                   (ignored)
  -s, --silent                     no progress, only error messages
                                     (equivalent to --loglevel=ERROR)
  -v, --version                    show version number and exit
  -V, --verbose                    be verbose (equivalent to --loglevel=DEBUG)
  -w, --warranty                   show warranty and copyright

You found a bug? Please read https://lilypond.org/bug-reports.html
```

**Comment by Joshua-Mastachi** [comment]
I tried installing them with both `nix-env` and home-manager (`home.nix`)
I started reading about Nix about yesterday, so there's a possibility I'm doing something wrong.
But it's weird that all 4 installs give `Fontconfig` errors

**Comment by yurrriq** [comment]
Yeah, should have been fixed in #229456. Make sure you're pointing to a recent enough nixpkgs commit from the master branch, such as a23730167676c5aac4a0ac710162220e104e1336

**Comment by Kernald** [comment]
For what it's worth, I'm still getting the same (non-blocking) error with nixpkgs 24.05 as of yesterday. It seems to make it impossible to change fonts though (or at least I haven't figured out a working solution).

**Comment by nicball** [comment]
I am still having `Fontconfig error: No writable cache directories` error on **linux**. I have tried on different machines and the newest nixpkgs.

**Comment by cueaz** [comment]
Have you tried using lilypond unstable (>=2.25.5)? This version fixes a issue where lilypond unintentionally affects fontconfig by setting XDG_CACHE_HOME. I haven't tried it yet, but it looks promising.

https://github.com/lilypond/lilypond/commit/ff304e3b8bd477fb37a20726ecc62e172a716e23

Another solution can be manually configuring fonts.conf to prevent fontconfig from being influenced by XDG_CACHE_HOME. I managed to fix "no writable cache directories" issue in this way.

```nix
...
    with pkgs; rec {
      ...
      lilyFontsConf = writeText "fonts.conf" ''
        <?xml version='1.0'?>
        <!DOCTYPE fontconfig SYSTEM 'urn:fontconfig:fonts.dtd'>
        <fontconfig>
          <dir>${dejavu_fonts.minimal}</dir>
          <!-- <cachedir prefix="xdg">fontconfig</cachedir> -->
          <cachedir>~/.cache/fontconfig</cachedir>
        </fontconfig>
      '';
      lilypond = pkgs.lilypond.overrideAttrs (oldAttrs: {
        postInstall = ''
          for f in "$out/bin/"*; do
              # Override default argv[0] setting so LilyPond can find
              # its Scheme libraries.
              wrapProgram "$f" --set GUILE_AUTO_COMPILE 0 \
                               --set PATH "${ghostscript}/bin" \
                               --set FONTCONFIG_FILE "${lilyFontsConf}" \
                               --argv0 "$f"
          done
        '';
      });
      ...
    }
...
```

**Comment by nicball** [comment]
`lilypond-unstable` is good. Thanks for the solution.
