### ISSUE TITLE
module "cupsex" is missing - HPLIP printing doesn't work.

### ISSUE THREAD

**Issue by toogley** [NixOS/nixpkgs#21084]
## Issue description

the HP printing system `hplip` can't be used - everytime a `hp-*` method is invoked, I receive an `module named cupsext` error.

### Steps to reproduce
```
$ nix-env -i '(.*hplip*|.*cups.*)'
replacing old ‘hplip-3.16.5’
replacing old ‘cups-2.1.4’
replacing old ‘libgnomecups-0.2.3’
replacing old ‘python2.7-pycups-1.9.73’
replacing old ‘python3.5-pycups-1.9.73’
replacing old ‘apcupsd-3.14.14’
replacing old ‘brgenml1cupswrapper-3.1.0-1’
replacing old ‘cups-bjnp-1.2.2’
replacing old ‘cups-filters-1.11.1’
replacing old ‘cups-gutenprint-binary-5.0.1’
replacing old ‘cups-pk-helper-0.2.5’
installing ‘apcupsd-3.14.14’
installing ‘brgenml1cupswrapper-3.1.0-1’
installing ‘cups-2.1.4’
installing ‘cups-bjnp-1.2.2’
installing ‘cups-filters-1.11.1’
installing ‘cups-gutenprint-binary-5.0.1’
installing ‘cups-pk-helper-0.2.5’
installing ‘hplip-3.16.5’
installing ‘libgnomecups-0.2.3’
installing ‘python2.7-pycups-1.9.73’
installing ‘python3.5-pycups-1.9.73’
building path(s) ‘/nix/store/33hsh6yqswi5dlsya42jqk724mslpb7x-user-environment’
created 2642 symlinks in user environment
$ hp-print
Traceback (most recent call last):
  File "/nix/store/pbk0vcaz2p4p8q9cdj3y9q32dk5h2cif-hplip-3.16.5/share/hplip/print.py", line 36, in <module>
    from base import utils, device, tui, module
  File "/nix/store/pbk0vcaz2p4p8q9cdj3y9q32dk5h2cif-hplip-3.16.5/share/hplip/base/device.py", line 42, in <module>
    from . import status
  File "/nix/store/pbk0vcaz2p4p8q9cdj3y9q32dk5h2cif-hplip-3.16.5/share/hplip/base/status.py", line 33, in <module>
    import cupsext
ImportError: No module named cupsext
$ hp-check
warning: CUPSEXT could not be loaded. Please check HPLIP installation.
```

## Technical details

* System: NixOS: `16.09` 
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version:  `"16.09.1038.a6728e1"`

**Comment by Mic92** [comment]
Actually the fix should have been back ported: https://github.com/NixOS/nixpkgs/issues/20438

**Comment by FRidh** [comment]
This has been fixed, and the fix is also available on NixOS 16.09. `16.09.1038.a6728e1` is already an old version so @toogley, you should update your channel.

**Comment by toogley** [comment]
@FRidh 
After `nix-channel --add https://nixos.org/channels/nixos-16.09 nixos` and `nixos-rebuild switch --upgrade` the error still remains. Is this what you meant? My NixOS version is now `16.09.1229.f52eaf4 (Flounder)`

**Comment by FRidh** [comment]
@toogley the package at that revision is working properly. Can you share store path (the big hash)?
```
$ nix-build '<nixos>' -A hplip
```
you might have to replace `nixos` with `nixpkgs`.

I get `/nix/store/rf43wgjnj77q17wqlvcjb5zbabfxhi92-python2.7-hplip-3.16.5`. Note the name of the package, that's a mistake on my side when I converted the expression to `mkPythonDerivation`. Therefore, if you've installed the package with `nix-env` it won't upgrade it because the package name has changed.

**Comment by toogley** [comment]
@FRidh I receive `/nix/store/rf43wgjnj77q17wqlvcjb5zbabfxhi92-python2.7-hplip-3.16.5` - although I recently updated to the unstable channel.
