### ISSUE TITLE
Suggestion: allow mostly-static builds targeting Darwin

### ISSUE THREAD

**Issue by Thesola10** [NixOS/nixpkgs#214611]
### Describe the bug
I understand that purely static binaries are not supported under Darwin, due to the unstable system call ABI. My suggestion is that `pkgsStatic`, on Darwin ~~or cross-compiling to Darwin~~, should produce static _libraries_, which would result in _dynamic_ binaries which only depend on `libSystem.dylib`. This would be useful for single-file software for embedding, as well as simplifying distribution of Nix-built binaries on systems without Nix.

### Steps To Reproduce
1. Build `nixpkgs#legacyPackages.x86_64-darwin.pkgsStatic.nix`
2. Run `llvm-otool -L result/bin/nix`
3. Resulting derivation is a dynamic executable with dependencies elsewhere in the Nix Store

### Expected behavior
Resulting executable would only depend on `/usr/lib/libSystem.B.dylib`

### Notify maintainers
@NixOS/darwin-maintainers

**Comment by Thesola10** [comment]
I'm currently trying to build with the following overlays:
```nix
{ cpu ? builtins.head (builtins.split "-" builtins.currentSystem)
, nixpkgs ? <nixpkgs>
}:

let
  nixpkgsShared = import nixpkgs { system = "${cpu}-darwin"; };
in import nixpkgs {
  system = "${cpu}-darwin";
  overlays =
  [ (self: super: 
    { stdenv = super.stdenv // {
        # Force target platform to become static
        targetPlatform = super.stdenv.targetPlatform // { isStatic = true; };
      };
      darwin = nixpkgsShared.darwin;
      targetPackages = super.targetPackages // {
        darwin = nixpkgsShared.darwin // {
          # Allow Darwin -> Darwin cross-compilation
          LibsystemCross = nixpkgsShared.darwin.Libsystem;
        };
      };
    })
  ];
}
```

The above seems to produce static libraries and very dependency-light binaries... all the way up to `bootstrap-stage2-stdenv-darwin` which fails because:
```
error: output '/nix/store/slpsqw2q0r3zp79jv6v28vxz3csndmmh-bootstrap-stage2-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/0lfss9hf1sgdwlxym1rj7a2r98fisz11-libunistring-1.0
         /nix/store/6852iypxpmwmfh0zzl31xb38qq3lmb42-curl-7.85.0
         /nix/store/8p24iy6wzw13x3zmy2f8hz32dhsw30ri-libkrb5-1.20
         /nix/store/b1mzc9ilryj4kckib5yavl5irz23bass-libcxx-11.1.0
         /nix/store/b2h3dcd8fc81h4vpm2p89rdxlz48lnhw-libxml2-2.10.0
         /nix/store/d70hc1izv04pa2kc5g64zsyppnd42z26-nghttp2-1.49.0-lib
         /nix/store/k7l8w9mh12x7w70pw16wffp4qc55sxwl-libcxxabi-11.1.0
         /nix/store/n63wlghd6cczckb9ymkgxz2pahlfvspk-bash-5.1-p16
         /nix/store/ns78fkxlgvys1xhb354dg0gmzba1x9cj-libssh2-1.10.0
         /nix/store/qvnsf008wav1g9s956z42arar509amri-openssl-3.0.5
         /nix/store/v0qih9ajf1kqpfqmabzd4p77w6qizml6-zstd-1.5.2
         /nix/store/v75grrfn09lrw9szvy9kwwd18xdf24dy-brotli-1.0.9-lib
         /nix/store/vqlxbhyqal8amwfbi029c1rgs1mqikzi-zlib-1.2.12
         /nix/store/wcdzhplb433acc3m5jcvrpqn7215xrzj-libidn2-2.3.2
```

**Comment by Thesola10** [comment]
Currently attempting to override builds on the basis that gcc actually discards `--static` on Darwin and thus produces dynamic binaries with static libraries, but I'm running into a bunch of infinite recursion errors.

My overlay for reference:
```nix
self: super:
{ stdenv = super.stdenv //
  { hostPlatform = super.stdenv.hostPlatform // { isStatic = true; };
    targetPlatform = super.stdenv.targetPlatform // { isStatic = true; };
  };
  targetPackages = super.targetPackages //
  { darwin = super.targetPackages.darwin //
    { LibsystemCross = super.targetPackages.darwin.Libsystem;
    };
  };
}
```

**Comment by Thesola10** [comment]
Okay, I have a working Nixpkgs expression for building "static" executables targeting Darwin (on Darwin only).

The second overlay skips recompiling the compiler since we're not actually "cross-compiling".
```nix
let sys = "x86_64-darwin";
in import <nixpkgs> {
  localSystem = sys;
  crossSystem = {
    isStatic = true;
    system = sys;
  };
  overlays = [
    (self: super: {
      darwin = super.darwin // {
        Libsystem = super.buildPackages.darwin.Libsystem;
        LibsystemCross = super.buildPackages.darwin.Libsystem;
      };

      libcCross = super.buildPackages.darwin.Libsystem;

      targetPackages = self;
    })
    (self: super: {
      stdenv = (import nixpkgs { system = sys; }).stdenv // {
        inherit (super.stdenv) buildPlatform hostPlatform targetPlatform;
      };
    })
  ];
}
```

**Comment by Thesola10** [comment]
Managed to produce a working Nix binary, but for some reason it still has a dependency on `libc++.dylib` and `libc++abi.dylib`. Still trying to figure out how to throw that away

**Comment by Thesola10** [comment]
This overlay produces a completely freestanding Nix binary for macOS

[nixie-dev/nixie:static-bins/nixpkgs-darwin-static.nix](https://github.com/nixie-dev/nixie/blob/5ad90f9cf8907eebf1040986c968f8605c87cc56/static-bins/nixpkgs-darwin-static.nix)

**Comment by andrewcrook** [comment]
FYI I have seen people use zig to compile C programs statically on macOS

**Comment by Thesola10** [comment]
Fixed by #235990

**Comment by reckenrode** [comment]
Should this be closed when static builds still don’t work on x86_64-darwin?

**Comment by winterqt** [comment]
Agreed, let's keep this open till all supported Darwin platforms have working static builds.

**Comment by reckenrode** [comment]
Fortunately, that should be coming pretty soon.

I have a branch with working x86_64-darwin cross-compilation, which includes mostly-static builds. I need to make sure I didn’t break the stdenv or aarch64-darwin cross-compilation, so it’ll probably be a few days before I can open the PR.
