### ISSUE TITLE
zellij stopped working

### ISSUE THREAD

**Issue by dit7ya** [NixOS/nixpkgs#216961]
### Describe the bug

Currently `zellij` fails to start. See more context about the issue at https://github.com/zellij-org/zellij/issues/2170.

### Steps To Reproduce
1. Install zellij from current master/ nixos-unstable
2. start `zellij`

### Expected behavior
Should not quit with `Received empty message from server`

### Notify maintainers
@therealansh @_0x4A6F @abbe @thehedgeh0g

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12, NixOS, 23.05 (Stoat), 23.05.20230216.ac1f5b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by kulabun** [comment]
I have the same problem. Here is what I see in `journalctl`:
```
Feb 18 14:11:59 desktop kernel: wasm[3974]: segfault at 7f343502cb19 ip 00007f3426291f8d sp 00007f342561e8f8 error 4 in libc>
Feb 18 14:11:59 desktop kernel: Code: 00 00 00 00 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 66 2e 0f 1f 84 00 00 00 00 00 66 90>
Feb 18 14:11:59 desktop systemd[1]: Started Process Core Dump (PID 3977/UID 0).
Feb 18 14:12:02 desktop systemd-coredump[3978]: [🡕] Process 3964 (zellij) of user 1000 dumped core.
                                                           
                                                           Module linux-vdso.so.1 with build-id 40692bbca60fb501c0462e7bfdd47adda0923212
                                                           Module ld-linux-x86-64.so.2 with build-id 425d0b541792ce3617a98d1da22d8d12b2>
                                                           Module libm.so.6 with build-id 4fc4bafd0b116fa570aefe9614d2e8be14054836
                                                           Module libgcc_s.so.1 without build-id.
                                                           Module libc.so.6 with build-id fb65299612b964ce84ef5eac98cbc42e997483c9
                                                           Module zellij without build-id.
                                                           Stack trace of thread 3974:
                                                           #0  0x00007f3426291f8d __memcpy_avx_unaligned_erms (libc.so.6 + 0x159f8d)
                                                           #1  0x000055a0fe045bda n/a (zellij + 0x64abda)
                                                           #2  0x000055a0fe03ce20 n/a (zellij + 0x641e20)
                                                           #3  0x000055a0fe03e6a2 n/a (zellij + 0x6436a2)
                                                           #4  0x000055a0fe434464 n/a (zellij + 0xa39464)
                                                           #5  0x000055a0fe42fb8b n/a (zellij + 0xa34b8b)
                                                           #6  0x000055a0fe33c133 n/a (zellij + 0x941133)
                                                           #7  0x000055a0fe388f23 n/a (zellij + 0x98df23)
                                                           #8  0x000055a0fe391ff0 n/a (zellij + 0x996ff0)
                                                           #9  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #10 0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #11 0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           
                                                           Stack trace of thread 3964:
                                                           #0  0x00007f342623fd3d syscall (libc.so.6 + 0x107d3d)
                                                           #1  0x000055a0fdf4abe4 n/a (zellij + 0x54fbe4)
                                                           #2  0x000055a0fe2360c5 n/a (zellij + 0x83b0c5)
                                                           #3  0x000055a0fe477462 n/a (zellij + 0xa7c462)
                                                           #4  0x000055a0fe47e790 n/a (zellij + 0xa83790)
                                                           #5  0x000055a0fe1c24fb n/a (zellij + 0x7c74fb)
                                                           #6  0x000055a0fe1c3ae3 n/a (zellij + 0x7c8ae3)
                                                           #7  0x000055a0fe1c1a94 n/a (zellij + 0x7c6a94)
                                                           #8  0x00007f342616124e __libc_start_call_main (libc.so.6 + 0x2924e)
                                                           #9  0x00007f3426161309 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29309)
                                                           #10 0x000055a0fdb42375 n/a (zellij + 0x147375)
                                                           
                                                           Stack trace of thread 3967:
                                                           #0  0x00007f34262366b4 read (libc.so.6 + 0xfe6b4)
                                                           #1  0x000055a0fe395b86 n/a (zellij + 0x99ab86)
                                                           #2  0x000055a0fe285fda n/a (zellij + 0x88afda)
                                                           #3  0x000055a0fe29b2c7 n/a (zellij + 0x8a02c7)
                                                           #4  0x000055a0fe389122 n/a (zellij + 0x98e122)
                                                           #5  0x000055a0fe38c23e n/a (zellij + 0x99123e)
                                                           #6  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #7  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #8  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)

                                                           Stack trace of thread 3966:
                                                           #0  0x00007f342623fd3d syscall (libc.so.6 + 0x107d3d)
                                                           #1  0x000055a0fdf4abe4 n/a (zellij + 0x54fbe4)
                                                           #2  0x000055a0fe2360c5 n/a (zellij + 0x83b0c5)
                                                           #3  0x000055a0fe477462 n/a (zellij + 0xa7c462)
                                                           #4  0x000055a0fe386d31 n/a (zellij + 0x98bd31)
                                                           #5  0x000055a0fe3a0a38 n/a (zellij + 0x9a5a38)
                                                           #6  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #7  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #8  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           
                                                           Stack trace of thread 3973:
                                                           #0  0x00007f342623fd3d syscall (libc.so.6 + 0x107d3d)
                                                           #1  0x000055a0fdf4abe4 n/a (zellij + 0x54fbe4)
                                                           #2  0x000055a0fde2c708 n/a (zellij + 0x431708)
                                                           #3  0x000055a0fde2cca7 n/a (zellij + 0x431ca7)
                                                           #4  0x000055a0fe3bce22 n/a (zellij + 0x9c1e22)
                                                           #5  0x000055a0fe38874a n/a (zellij + 0x98d74a)
                                                           #6  0x000055a0fe391502 n/a (zellij + 0x996502)
                                                           #7  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #8  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #9  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           
                                                           Stack trace of thread 3975:
                                                           #0  0x00007f342623fd3d syscall (libc.so.6 + 0x107d3d)
                                                           #1  0x000055a0fdf4abe4 n/a (zellij + 0x54fbe4)
                                                           #2  0x000055a0fde2c708 n/a (zellij + 0x431708)
                                                           #3  0x000055a0fde2cca7 n/a (zellij + 0x431ca7)
                                                           #4  0x000055a0fe385be2 n/a (zellij + 0x98abe2)
                                                           #5  0x000055a0fe3918e7 n/a (zellij + 0x9968e7)
                                                           #6  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #7  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #8  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           
                                                           Stack trace of thread 3972:
                                                           #0  0x00007f342623fd3d syscall (libc.so.6 + 0x107d3d)
                                                           #1  0x000055a0fdf4abe4 n/a (zellij + 0x54fbe4)
                                                           #2  0x000055a0fde2c708 n/a (zellij + 0x431708)
                                                           #3  0x000055a0fde2cca7 n/a (zellij + 0x431ca7)
                                                           #4  0x000055a0fe441632 n/a (zellij + 0xa46632)
                                                           #5  0x000055a0fe389d62 n/a (zellij + 0x98ed62)
                                                           #6  0x000055a0fe392550 n/a (zellij + 0x997550)
                                                           #7  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #8  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #9  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           
                                                           Stack trace of thread 3965:
                                                           #0  0x00007f3426248917 accept (libc.so.6 + 0x110917)
                                                           #1  0x000055a0fe38a3a1 n/a (zellij + 0x98f3a1)
                                                           #2  0x000055a0fe453707 n/a (zellij + 0xa58707)
                                                           #3  0x000055a0fe391c74 n/a (zellij + 0x996c74)
                                                           #4  0x000055a0fdf60d15 n/a (zellij + 0x565d15)
                                                           #5  0x00007f34261c0e86 start_thread (libc.so.6 + 0x88e86)
                                                           #6  0x00007f3426247d30 __clone3 (libc.so.6 + 0x10fd30)
                                                           ELF object binary architecture: AMD x86-64
```

**Comment by budimanjojo** [comment]
I had the same problem and rolled back to use zellij from stable repo. I believe this has to do with new rust version like the recent wezterm https://github.com/NixOS/nixpkgs/issues/216394

**Comment by aktaboot** [comment]
same here, although running zellij with `-l compact` does not cause it to crash for me fwiw

**Comment by xinyangli** [comment]
Fixed by removing `$HOME/.cache/zellij`, [according to this answer](https://github.com/zellij-org/zellij/issues/2170#issuecomment-1451883326).

@aktaboot

**Comment by aktaboot** [comment]
Thank you, I guess this can be closed now ?

**Comment by lboklin** [comment]
I don't think this should be considered resolved until the cause has been established and addressed. Deleting the cache is a workaround and others will continue to be affected and they shouldn't have to troubleshoot like those of us here.

**Comment by budimanjojo** [comment]
I think this is an upstream issue rather than NixOS issue because the workaround above fixed my problem too, and it's also mentioned in `zellij` `v0.35.1` release note https://github.com/zellij-org/zellij/releases/tag/v0.35.1. There's also `v0.35.2` released 14 hours ago. So yes this should be closed and people should report to upstream instead because this is not the `rust` build problem like I assume it was (my mistake).

**Comment by matthiasbeyer** [comment]
Please check whether this issue is resolved with #225990

**Comment by kate-shine** [comment]
> Please check whether this issue is resolved with #225990

I don't think so, I just found this thread and it helped me to solve it by erasing cache, but I was already on 0.36.0

**Comment by brianmay** [comment]
I am getting this problem with 0.36.0 but have no `$HOME/.cache/zellij` to delete.

**Comment by callesp** [comment]
> I am getting this problem with 0.36.0 but have no `$HOME/.cache/zellij` to delete.

Same here.

**Comment by dheater** [comment]
Also seeing this issue on Mac with `0.36.0` and I also do not have a `$HOME/cache/zellij`.  Fixed for now by reverting to `0.35.2` by running:
` nix-env -iA zellij -f https://github.com/NixOS/nixpkgs/archive/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8.tar.gz`

**Comment by brianmay** [comment]
Am wondering if the cache is in a different place under OSX. e.g. maybe `~/Library/Caches/`.

Unfortunately I don't have access to an OSX computer to check this on.

**Comment by gotr00t0day** [comment]
I'm having the same issue

**Comment by gotr00t0day** [comment]
> same here, although running zellij with `-l compact` does not cause it to crash for me fwiw

This worked for me ;)

**Comment by ingvarch** [comment]
Removed `~/Library/Caches/org.Zellij-Contributors.Zellij` on my Mac and it helped me. 

P.S. Thanks @brianmay for clue

**Comment by brianmay** [comment]
Thanks, that works for me to. Was looking for `~/Library/Caches/zellij` - didn't realize the name was different.

**Comment by matthiasbeyer** [comment]
I think this issue can be closed, right?

**Comment by ingvarch** [comment]
I think so

**Comment by pio2398** [comment]
..and everyone will have to clear the cache after update?
For me seem like upstream issue but problem still exists.

**Comment by brianmay** [comment]
I don't think there is anything more we can do here.

There is an upstream bug, see https://github.com/zellij-org/zellij/issues/2170

**Comment by brianmay** [comment]
I wonder if nixos changed the build options, dependencies, or something for zellij, resulting in the format of the cache directory changed. I don't see any reports of problems from non-nixos users.

**Comment by lboklin** [comment]
I'm not clear on whether this is specific to Nix(OS), but if it is, I think this is best resolved by performing a check for whether the problematic cache is present and print a warning if so. Is that possible?

**Comment by carlosonrails** [comment]
It happens on with me on Arch Linux. 
The "zellij -l compact" trick works here too. 
Normal way is still broken.
