### ISSUE TITLE
gnome-tweak-tool-3.22 does not start; confused dependencies.

### ISSUE THREAD

**Issue by dbeecham** [NixOS/nixpkgs#21851]
## Issue description
> gnome-tweak-tool
Traceback (most recent call last):
  File "/nix/store/7a9v4hcky68cq3v02hd4fgyi66pyjlfd-gnome-tweak-tool-3.22.0/bin/.gnome-tweak-tool-wrapped", line 26, in <module>
    import gtweak
ImportError: No module named 'gtweak'

The gnome-tweak-tool script has this line:
PYTHONPATH=/nix/store/7a9v4hcky68cq3v02hd4fgyi66pyjlfd-gnome-tweak-tool-3.22.0/lib/**python2.7**/site-packages:<other python 3 packages>
and then it executes `.gnome-tweak-tool.wrapped` which uses python 3.
The library 'gtweak' is in gnome-tweak-tool/lib/python3.5/site-packages.

Not sure what is happening here; I think all of the paths should be python2? If I change gnome-tweak-tool/default.nix to use python3, the library loads, but crashes since the code is indeed not python3 (incorrect print statement). I see no python3 reference that I could change.

The same issue exists in the latest git of nixpkgs (using nix-build $NIXPKGS -A gnome3.gnome-tweak-tool).

### Steps to reproduce
I guess just install gnome-tweak-tool-3.22.0.

## Technical details

* System: 
Running nixos on nixos-unstable;
> nixos-version
17.03pre98682.f673243 (Gorilla)

* Nix version: (run `nix-env --version`)
> nix-env --version
nix-env (Nix) 1.11.5

* Nixpkgs version:
> nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre98682.f673243"

**Comment by dbeecham** [comment]
Ok, I found the issue. It's this line here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/3.22/core/gnome-shell/default.nix#L28

It propagates python3 as dependency making gnome-tweak-tool compile to python3 even though the library does not support it. Should gnome-shell really propagate python3? Is it possible for gnome-tweak-tool to override this propagation?

**Comment by Mic92** [comment]
Are you sure `gnome-tweak-tool` does not support python3?

**Comment by dbeecham** [comment]
Somewhat. When I run gnome-tweak-tool which has been compiled against python3, I get this error:

    File "/nix/store/q8a3cdw476z6nnin69i731c15qpcgb7l-gnome-tweak-tool-3.22.0/lib/python3.5/site-packages/gtweak/app.py", line 87
        print "This does nothing. It is only a demonstration."

That's definitely a python2 print statement. Unless there is some weird patching taking place, I'd guess there is no python3 support in the library.

The solution I used was to add "python" as the first dependency in buildInputs of gnome-tweak-tool. That puts python2 before python3 in the PATH, and everything is fine. Seems a bit like a kludge, but it works.

**Comment by jgeerds** [comment]
Would be better if gnome-shell-tweaks would explicitly use `python2` and not `python`. Is that somehow configurable? 

(I'm thinking of Arch Linux where `python` already points to python3)

**Comment by eqyiel** [comment]
@Mic92 it definitely doesn't support Python 3, at least at the moment.

There's a patch on their Bugzilla to port to Python 3: https://bugzilla.gnome.org/show_bug.cgi?id=740219#c7

Unfortunately it's been ignored for about 6 months now.

**Comment by dezgeg** [comment]
It doesn't sound sane that `gnome-shell` propagates `python3`.

**Comment by eqyiel** [comment]
@dezgeg as far as I understand, it means that all derivations that have `gnome-shell` as a dependency have a hidden Python 3 input that the derivation doesn't know about (and may or may not build without it)?  Is that correct?  🙀

**Comment by FRidh** [comment]
> @dezgeg as far as I understand, it means that all derivations that have gnome-shell as a dependency have a hidden Python 3 input that the derivation doesn't know about (and may or may not build without it)? Is that correct?  :scream_cat:

Correct. Propagating build inputs is something to be careful with. In this case, certain programs likely need a Python interpreter with a certain set of packages. In that case it makes more sense to have the Python env as `buildInput`. `patchShebangs` will then take care of pointing the shebang to that env.

**Comment by jgeerds** [comment]
75492617979f9bd11889bc980024ee62acdf52e8 introduced the propagated python dependency

see also
https://github.com/NixOS/nixpkgs/pull/16433
https://github.com/NixOS/nixpkgs/issues/14651
https://github.com/NixOS/nixpkgs/pull/14716

**Comment by jgeerds** [comment]
Fixed with #22937

If you run into any errors please ping me

**Comment by samotarnik** [comment]
@jgeerds i still have this problem, after updating my nix config with [this fix](https://github.com/NixOS/nixpkgs/issues/24172). my system info:
```
$ nix-env --version
nix-env (Nix) 1.11.5
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
```
and my [current configuration](https://github.com/samotarnik/dotfiles/tree/master/nixos).
any ideas?

**Comment by mickours** [comment]
I also run into this problem while updating to unstable. But, I just check in the package and gtweak is there and in python2: ``/nix/store/gk3id8jkh7jipaw77bz5xay8c79iqy8k-gnome-tweak-tool-3.22.0/lib/python2.7/site-packages/gtweak``
