### ISSUE TITLE
buildRustPackage fails for projects with no dependencies in Cargo.toml

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#22737]
## Issue description

`buildRustPackage` fails for projects that declare no dependencies in `Cargo.toml`.

see #22735

### Steps to reproduce

Try building this [example][example] project:

```
❯ nix-build release.nix -A build --arg nixpkgs '<nixpkgs>' --argstr system x86_64-linux
these derivations will be built:
  /nix/store/dw177b3in0rmfsx237jlzqimbjmcxrpk-ill-fetch.drv
  /nix/store/c4klqbmccg501naxznl48w24hpazgdc1-ill.drv
building path(s) ‘/nix/store/dy1dywfq2mh035z4v0phmx0kg7p066cw-ill-fetch’
unpacking sources
unpacking source archive /nix/store/q6b7iql14yafz8j2hqq3x4g6fzpdamxy-ill
source root is ill
installing
Fetching /tmp/nix-build-ill-fetch.drv-0/ill to /nix/store/dy1dywfq2mh035z4v0phmx0kg7p066cw-ill-fetch
Using rust registry from /nix/store/ri6jzyj02dw56zr5bk9yvaci6zr4g7vw-rustRegistry-2017-01-27-6a73a15
warning: custom registry support via the `registry.index` configuration is being removed, this functionality will not work in the future
mv: missing destination file operand after '/nix/store/dy1dywfq2mh035z4v0phmx0kg7p066cw-ill-fetch/registry/cache/HASH'
Try 'mv --help' for more information.
builder for ‘/nix/store/dw177b3in0rmfsx237jlzqimbjmcxrpk-ill-fetch.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/c4klqbmccg501naxznl48w24hpazgdc1-ill.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c4klqbmccg501naxznl48w24hpazgdc1-ill.drv’ failed
```

[example]: http://bitbucket.org/dermetfan/ill

## Technical details

* System: `17.03pre100522.01fef3f (Gorilla)`
* Nix version:`nix-env (Nix) 1.11.6`
* Nixpkgs version: `17.03pre100522.01fef3f`

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by Deluvi** [comment]
I have just tested on the sample hello world that Cargo provides with `cargo init`, `buildRustPackage` was able to perform the build just fine. This has probably been fixed at some point.

**Comment by liff** [comment]
I think this still happens. The `elfcat` package fails to build (from [Hydra](https://hydra.nixos.org/build/176058059/nixlog/2)):

```
unpacking sources
unpacking source archive /nix/store/y61ycffrys6xjvgfhhhi8s2fidaz43ga-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
There is no dependency to vendor in this project.
Traceback (most recent call last):
  File "/nix/store/9cqhrbp7v53q98ly12gzpsqck1cxzqvp-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 42, in <module>
    main()
  File "/nix/store/9cqhrbp7v53q98ly12gzpsqck1cxzqvp-cargo-vendor-normalise/bin/.cargo-vendor-normalise-wrapped", line 17, in main
    assert list(data.keys()) == ["source"]
AssertionError
```

It has [`cargoSha256 = null`](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/tools/misc/elfcat/default.nix#L14=) so I imagine this was working earlier and then regressed.

**Comment by liff** [comment]
Bisected to dc93e10397b6efadefe58fe0a74925595d273d75. Looks like the way `cargo vendor` works changed between 1.58 and 1.59.

```
❯ rustup run 1.58.1 cargo vendor
To use vendored sources, add this to your .cargo/config.toml for this project:

[source.vendored-sources]
directory = "vendor"
❯ rustup run 1.59.0 cargo vendor
There is no dependency to vendor in this project.
```

The `cargo-vendor-normalise` script [always expects the first kind of output](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/build-support/rust/fetch-cargo-tarball/cargo-vendor-normalise.py#L16=).
