### ISSUE TITLE
Wrangler is broken

### ISSUE THREAD

**Issue by Chebuya** [NixOS/nixpkgs#235329]
### Describe the bug
Wrangler is broken on version 3.0.1

### Steps To Reproduce
nix shell nixpkgs#wrangler (latest flake)
wrangler dev
--> Error: spawn /nix/store/d70h3plhhzpx0wrn20dpyghi3nrp28wx-wrangler-3.0.1/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-64/bin/workerd ENOENT

### Expected behavior
wrangler dev should start the server

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.3.1-zen1, NixOS, 23.11 (Tapir), 23.11.20230529.5e871d8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(chebuya): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kirillrdy** [comment]
greetings !

I am not familiar enough with wrangler, but maybe the issue has been fixed ?

```
 nix shell nixpkgs#wrangler

[kirillvr@tsutenkaku:~]$ wrangler dev
 ⛅️ wrangler 3.1.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote

✘ [ERROR] Missing entry-point: The entry-point should be specified via the command line (e.g. `wrangler dev path/to/script`) or the `main` config field.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

```

**Comment by tinybeachthor** [comment]
Still broken on `3.1.0`. 

The issue is with `workerd`, included binary which is not fixed for nixos.
```
zsh: no such file or directory: /nix/store/0bd0rqri60r80yq5r5icq5lc191xi55k-wrangler-3.1.0/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-64/bin/workerd
```

**Comment by kirillrdy** [comment]
@Chebuya @tinybeachthor if you are able to test this https://github.com/NixOS/nixpkgs/pull/238886

**Comment by tinybeachthor** [comment]
@kirillrdy #238886 fixes it, thanks!

(There is a typo in the PR name, `wranger` instead of `wrangler`.)

**Comment by kirillrdy** [comment]
@tinybeachthor thanks for picking up typo !

**Comment by Chebuya** [comment]
Yeah, it works. tried it too.
```
chebuya@laptop ~/d/ircworker> wrangler dev                                                                                                                                                                           
 ⛅️ wrangler 3.1.0 (update available 3.1.1)
-----------------------------------------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-18",
but you've requested "2023-06-01". Falling back to "2023-05-18"...
[mf:inf] Ready on http://127.0.0.1:8787/
```
