### ISSUE TITLE
Steam fails to launch on unstable

### ISSUE THREAD

**Issue by starcraft66** [NixOS/nixpkgs#238101]
### Describe the bug
Steam takes a long time to start and ends up crashing after 30-45 seconds. I initially thought this was related to https://github.com/NixOS/nixpkgs/issues/236561 but I upgraded to latest unstable (this fix is merged into it) and the issue persists. I'm thinking it may have to do with the new UI redesign since there are JS engine errors?

### Additional context
Log:

```
steam.sh[83097]: Running Steam on nixos 23.11 64-bit
steam.sh[83097]: STEAM_RUNTIME is enabled automatically
setup.sh[83175]: Steam runtime environment up-to-date!
run.sh[83187]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[83097]: Steam client's requirements are satisfied
[2023-06-16 11:04:32] Startup - updater built Jun 16 2023 01:41:16
[2023-06-16 11:04:32] Startup - Steam Client launched with: '/home/tristan/.local/share/Steam/ubuntu12_32/steam'
06/16 11:04:32 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(83210)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-16 11:04:32] Loading cached metrics from disk (/home/tristan/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-16 11:04:32] Using the following download hosts for Public, Realm steamglobal
[2023-06-16 11:04:32] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-16 11:04:32] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-16 11:04:32] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-16 11:04:32] Checking for update on startup
[2023-06-16 11:04:32] Checking for available updates...
[2023-06-16 11:04:32] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-06-16 11:04:32] Manifest download: send request
[2023-06-16 11:04:32] Manifest download: waiting for download to finish
[2023-06-16 11:04:33] Manifest download: finished
[2023-06-16 11:04:33] Download skipped: /steam_client_ubuntu12 version 1686880776, installed version 1686880776, existing pending version 0
[2023-06-16 11:04:33] Nothing to do
[2023-06-16 11:04:33] Verifying installation...
[2023-06-16 11:04:33] Performing checksum verification of executable files
[2023-06-16 11:04:33] Verification complete

(process:83210): GLib-GObject-CRITICAL **: 11:04:33.554: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:83210): GLib-GObject-CRITICAL **: 11:04:33.554: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
/nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf0a066b0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf0a04f80
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1735-g2e465ae31
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
steamwebhelper.sh[83477]: Runtime for steamwebhelper: defaulting to /home/tristan/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[83477]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 135 milliseconds to initialize
src/steamUI/steamuisharedjscontroller.cpp (529) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (529) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (529) : Fatal assert; application exiting
src/steamUI/steamuisharedjscontroller.cpp (529) : Fatal assert; application exiting
06/16 11:05:23 Init: Installing breakpad exception handler for appid(steam)/version(1686880776)/tid(83210)
assert_20230616110523_30.dmp[83767]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230616110523_30.dmp
_ExitOnFatalAssert
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
@luna:~ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.34, NixOS, 23.11 (Tapir), 23.11.20230616.ba43650`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `""`
 - channels(tristan): `""`
 - nixpkgs: `/nix/store/5msxca2cg67cyiwwj0hizw2y2q4a7c57-3kxbx2fvdzsqqy1qqhbnbfqwv2cb1j5h-patched-nixpkgs`
```

**Comment by starcraft66** [comment]
Related to https://github.com/ValveSoftware/steam-for-linux/issues/9321 it seems.

**Comment by samueldr** [comment]
If it's like the previous time, the JS errors were red herrings, and symptoms of the earlier failure.

I would hazard a guess that this is the actual cause?

```
/nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
```

But I don't know for sure.

**Comment by K900** [comment]
Same version of Steam starts fine here.

**Comment by starcraft66** [comment]
I had xdg-desktop-portal-gnome enabled on my machine and leftover from some testing. I don't actually even use it for anything. I disabled it per suggestions here and in the upstream thread, now steam opens and works fine...

**Comment by Ashe** [comment]
Unsure if its the same issue, but I don't have that gnome portal enabled. Here's my logs:

<details>
  <summary>Log</summary>

 ```
❯ steam           
steam.sh[39368]: Running Steam on nixos 23.11 64-bit
steam.sh[39368]: STEAM_RUNTIME is enabled automatically
setup.sh[39447]: Steam runtime environment up-to-date!
run.sh[39459]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[39368]: Steam client's requirements are satisfied
[2023-06-23 18:08:33] Startup - updater built Jun 21 2023 21:17:38
[2023-06-23 18:08:33] Startup - Steam Client launched with: '/home/ashe/.local/share/Steam/ubuntu12_32/steam'
06/23 18:08:33 Init: Installing breakpad exception handler for appid(steam)/version(1687386907)/tid(39482)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-06-23 18:08:33] Loading cached metrics from disk (/home/ashe/.local/share/Steam/package/steam_client_metrics.bin)
[2023-06-23 18:08:33] Using the following download hosts for Public, Realm steamglobal
[2023-06-23 18:08:33] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-06-23 18:08:33] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-06-23 18:08:33] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-06-23 18:08:33] Checking for update on startup
[2023-06-23 18:08:33] Checking for available updates...
[2023-06-23 18:08:33] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-06-23 18:08:33] Manifest download: send request
[2023-06-23 18:08:33] Manifest download: waiting for download to finish
[2023-06-23 18:08:33] Manifest download: finished
[2023-06-23 18:08:33] Download skipped: /steam_client_ubuntu12 version 1687386907, installed version 1687386907, existing pending version 0
[2023-06-23 18:08:33] Nothing to do
[2023-06-23 18:08:33] Verifying installation...
[2023-06-23 18:08:33] Performing checksum verification of executable files
[2023-06-23 18:08:34] Verification complete

(process:39482): GLib-GObject-CRITICAL **: 18:08:34.410: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:39482): GLib-GObject-CRITICAL **: 18:08:34.410: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
/nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf63236b0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf6321f80
GetWin32Stats: display was not open yet, good
Loaded SDL version 3.0.0-1782-g214d5daa3
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
steamwebhelper.sh[39596]: Runtime for steamwebhelper: defaulting to /home/ashe/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[39596]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 100 milliseconds to initialize
Failed to init SteamVR because it isn't installed

(steam:39482): Gtk-WARNING **: 18:08:35.418: gtk_disable_setlocale() must be called before gtk_init()
Local Device Found
  type: 054c 0ce6
  path: sdl://1
  serial_number:  - 0
  Manufacturer: 
  Product:      DualSense Wireless Controller
  Release:      100
  Interface:    -1

!! Steam controller device opened for index 0.
local (potentially out of sync) copy of roaming config loaded - 4748 bytes.
[2023-06-23 18:08:36.370] [MANGOHUD] [info] [blacklist.cpp:59] process 'vulkandriverquery' is blacklisted in MangoHud
[2023-06-23 18:08:36.370] [MANGOHUD] [info] [blacklist.cpp:59] process 'vulkandriverquery' is blacklisted in MangoHud
ac_compute_device_uuid's output is based on invalid pci bus info.
ac_compute_device_uuid's output is based on invalid pci bus info.
[2023-06-23 18:08:36.404] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/ashe/.config/MangoHud/MangoHud.conf'
!! Controller 0 attributes:
  Type: 45
  ProductID: 3302
  Serial: DS4cb99b925440
  Capabilities: 02975bff
  Firmware Version: 305
  Firmware Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
  Bootloader Build Time: 2147483647 (Tue, 19 Jan 2038 03:14:07 GMT)
Loaded Config for Local Selection Path for App ID 413090, Controller 0: controller_base/bigpicture_gamepad.vdf
Loaded Config for Local Selection Path for App ID 413090, Controller 0: controller_base/bigpicture_gamepad.vdf
Loaded Config for Local Selection Path for App ID 769, Controller 0: controller_base/basicui_gamepad.vdf
Loaded Config for Last Resort Path for App ID 769, Controller 0: /home/ashe/.local/share/Steam//controller_base/basicui_gamepad.vdf
Loaded Config for Local Selection Path for App ID 413090, Controller 0: controller_base/bigpicture_gamepad.vdf
[2023-06-23 18:08:36.968] [MANGOHUD] [info] [blacklist.cpp:59] process 'vulkandriverquery' is blacklisted in MangoHud
[2023-06-23 18:08:36.968] [MANGOHUD] [info] [blacklist.cpp:59] process 'vulkandriverquery' is blacklisted in MangoHud
ac_compute_device_uuid's output is based on invalid pci bus info.
ac_compute_device_uuid's output is based on invalid pci bus info.
[2023-06-23 18:08:37.015] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/ashe/.config/MangoHud/MangoHud.conf'

(steam:39482): GLib-GObject-CRITICAL **: 18:08:37.082: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:39482): GLib-GObject-CRITICAL **: 18:08:37.082: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(steam:39482): GLib-GObject-CRITICAL **: 18:08:37.389: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:39482): GLib-GObject-CRITICAL **: 18:08:37.389: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Loaded Config for Local Override Path for App ID 413080, Controller 0: /home/ashe/.local/share/Steam//controller_base/empty.vdf
Fossilize INFO: Setting autogroup scheduling.
BRefreshApplicationsInLibrary 1: 2ms
sanitize shortcut app id xdg-open: replacing 0 with 3850029430, reason: k_unAppIdInvalid
sanitize shortcut app id xdg-open: replacing 0 with 3553052455, reason: k_unAppIdInvalid
roaming config store loaded successfully - 4748 bytes.
migrating temporary roaming config store
Loaded Config for Local Override Path for App ID 413080, Controller 0: /home/ashe/.local/share/Steam//controller_base/empty.vdf

(steam:39482): GLib-GObject-CRITICAL **: 18:08:38.111: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(steam:39482): GLib-GObject-CRITICAL **: 18:08:38.111: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
System startup time: 3.82 seconds
  ```
</details>

You can find my config here: https://github.com/ashe/dotfiles.

When I try opening steam, it just endlessly sits on the 'log in screen' and no further output displays as shown below

![image](https://github.com/NixOS/nixpkgs/assets/8940077/1ae6f537-0be7-46a3-aed4-8d274caa4450)

**Comment by n3oney** [comment]
I don't have xdg-desktop-portal-gnome and never had. It doesn't start...

**Comment by PedroHLC** [comment]
Masked all the portals' units here:
```
╰─λ ps aux | grep -i steam
pedrohlc  142924  0.0  0.0 222720  1728 pts/1    S+   17:59   0:00 /nix/store/7ws5zmh4llmml550x02pqpcyzv5j4m4c-gnugrep-3.11/bin/grep --color=auto -i steam
```

Tried to run with `-no-cef-sandbox`, simply does not work. Log looks identical, but I get a loop of (instead of a crash):
```
steamwebhelper.sh[149778]: Runtime for steamwebhelper: defaulting to /home/pedrohlc/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[149778]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[149778]: CEF sandbox already disabled
```

**Comment by Ashe** [comment]
Short term fix: start steam with `steam -vgui` works for me

**Comment by imsofi** [comment]
While steam launches perfectly for me, using Proton 8.0+ will lead to various issues like a set of dependencies refusing to install, (e.g. DirectX), and when launching the EA game launcher for NFS Heat, will lead to the same error of:

```
(process:57874): GLib-GObject-CRITICAL **: 02:41:10.794: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

<details>
<summary>Full CLI output of steam using Proton Experimental launching NFS Heat and getting into the EA launcher</summary>

```
 % steam
steam.sh[60830]: Running Steam on nixos 23.11 64-bit
steam.sh[60830]: STEAM_RUNTIME is enabled automatically
setup.sh[60908]: Steam runtime environment up-to-date!
run.sh[60920]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[60830]: Steam client's requirements are satisfied
[2023-07-01 03:03:42] Startup - updater built Jun 28 2023 23:05:30
[2023-07-01 03:03:42] Startup - Steam Client launched with: '/home/sofi/.local/share/Steam/ubuntu12_32/steam'
[2023-07-01 03:03:42] Opted in to client beta 'publicbeta' via beta file
You are in the 'publicbeta' client beta.
07/01 03:03:42 Init: Installing breakpad exception handler for appid(steam)/version(1688001191)/tid(60943)
[2023-07-01 03:03:42] Loading cached metrics from disk (/home/sofi/.local/share/Steam/package/steam_client_metrics.bin)
[2023-07-01 03:03:42] Using the following download hosts for Public, Realm steamglobal
[2023-07-01 03:03:42] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2023-07-01 03:03:42] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2023-07-01 03:03:42] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-07-01 03:03:42] Verifying installation...
[2023-07-01 03:03:42] Verification complete
/nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so
Loaded SDL version 3.0.0-1782-g214d5daa3
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf0a2c6b0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf0a2af80
GetWin32Stats: display was not open yet, good
ComputeStartupMode: found registry default startup mode: 0
Switching to desktopui, since -vgui was not specified
GetWin32Stats: display was not open yet, good
steamwebhelper.sh[60949]: Runtime for steamwebhelper: defaulting to /home/sofi/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[60949]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 160 milliseconds to initialize
Failed to init SteamVR because it isn't installed
local (potentially out of sync) copy of roaming config loaded - 57228 bytes.
BRefreshApplicationsInLibrary 1: 106ms
roaming config store loaded successfully - 57228 bytes.
migrating temporary roaming config store
System startup time: 3.50 seconds
BuildCompleteAppOverviewChange: 731 apps
RegisterForAppOverview 1: 49ms
RegisterForAppOverview 2: 49ms
ExecCommandLine: "'/home/sofi/.local/share/Steam/ubuntu12_32/steam'"
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
pressure-vessel-wrap[62335]: W: Found more than one possible libdrm data directory from provider
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_get_source_tag
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiolibproxy.so
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognutls.so: undefined symbol: g_byte_array_steal
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognutls.so
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_get_source_tag
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognomeproxy.so
/nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: undefined symbol: g_hash_table_get_keys_as_array
Failed to load module: /nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_source_tag
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgioremote-volume-monitor.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_source_tag
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp waiting for user response to ProcessingShaderCache ""
Fossilize INFO: Setting autogroup scheduling.
GameAction [AppID 1222680, ActionID 1] : LaunchApp continues with user response "skip"
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 /home/sofi/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1222680 -- /home/sofi/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/games/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/sofi/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  'link2ea://launchgame/1222680?platform=steam&theme=nfsh'\0
Game process added : AppID 1222680 "PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 /home/sofi/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1222680 -- /home/sofi/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/games/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/sofi/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  'link2ea://launchgame/1222680?platform=steam&theme=nfsh'", ProcID 62605, IP 0.0.0.0:0
chdir "/mnt/games/Steam/steamapps/common/Need for Speed Heat"
ERROR: ld.so: object '/home/sofi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sofi/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/sofi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sofi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sofi/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 1222680, ActionID 1] : LaunchApp changed task to Completed with ""
pressure-vessel-wrap[62606]: W: Found more than one possible libdrm data directory from provider
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_get_source_tag
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiolibproxy.so
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognutls.so: undefined symbol: g_byte_array_steal
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognutls.so
/nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_get_source_tag
Failed to load module: /nix/store/28rngi2lbkcx4vzq331hlhf8bgq0351m-glib-networking-2.76.0/lib/gio/modules/libgiognomeproxy.so
/nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: undefined symbol: g_hash_table_get_keys_as_array
Failed to load module: /nix/store/p7njqfc1l00hxvm5zvjshahxqca5k9vm-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_source_tag
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgioremote-volume-monitor.so
/nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_source_tag
Failed to load module: /nix/store/gdmf479v2jnb55y9nwckhr47q54qq10a-gvfs-1.50.4/lib/gio/modules/libgvfsdbus.so
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
ThreadGetProcessExitCode: no such process 62803
ThreadGetProcessExitCode: no such process 62801
ThreadGetProcessExitCode: no such process 62607
ThreadGetProcessExitCode: no such process 62806
Game process updated : AppID 1222680 "PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 /home/sofi/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1222680 -- /home/sofi/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/games/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/sofi/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  'link2ea://launchgame/1222680?platform=steam&theme=nfsh'", ProcID 62802, IP 0.0.0.0:0
Setting breakpad minidump AppID = 1222680
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198041538495 [API loaded no]
ThreadGetProcessExitCode: no such process 62849
Game process added : AppID 1182480 "", ProcID 62872, IP 0.0.0.0:0
info:  Game: EABackgroundService.exe
info:  DXVK: v2.2-98-g089585890137269
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4add830
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
warn:  OpenXR: Unable to get required Vulkan instance extensions size
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 15.0.7, 256 bits)
warn:  Skipping CPU adapter: llvmpipe (LLVM 15.0.7, 256 bits)
warn:  OpenXR: Unable to get required Vulkan Device extensions size
info:  NVIDIA GeForce RTX 2060:
info:    Driver : NVIDIA 535.54.3
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 17988 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  NVIDIA GeForce RTX 2060:
info:    Driver : NVIDIA 535.54.3
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 17988 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
07/01 03:04:32 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(20230628230553)/tid(63008)
07/01 03:04:32 Init: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)/tid(63008)
ThreadGetProcessExitCode: no such process 63006
ThreadGetProcessExitCode: no such process 63256
Game process removed: AppID 1182480 "", ProcID 62872 
ThreadGetProcessExitCode: no such process 62872
Game 1182480 created interface SteamController008 / 
Game 1182480 created interface SteamInput006 / 
Game 1182480 created interface SteamUser021 / 
Game 1182480 created interface SteamUser021 / User
Game 1182480 created interface SteamUtils010 / 
Game 1182480 method call count for IClientUtils::SetGameLauncherMode : 2
Game 1182480 method call count for IClientUtils::RecordSteamInterfaceCreation : 7
Game 1182480 method call count for IClientUtils::GetAppID : 9
Game 1182480 method call count for IClientUser::GetAuthSessionTicket : 1
Game 1182480 method call count for IClientUser::GetSteamID : 1
Game 1182480 method call count for IClientUser::BLoggedOn : 1
Uploaded AppInterfaceStats to Steam
ThreadGetProcessExitCode: no such process 62997

(process:63008): GLib-GObject-CRITICAL **: 03:04:42.021: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Fossilize INFO: Overriding serialization path: "/mnt/games/Steam/steamapps/shadercache/1222680/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/mnt/games/Steam/steamapps/shadercache/1222680/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/mnt/games/Steam/steamapps/shadercache/1222680/fozpipelinesv6/steamapprun_pipeline_cache".
Fossilize INFO: Overriding serialization path: "/mnt/games/Steam/steamapps/shadercache/1222680/fozpipelinesv6/steamapprun_pipeline_cache".
reaping pid: 63008 -- gameoverlayui
ThreadGetProcessExitCode: no such process 62949
ThreadGetProcessExitCode: no such process 62856
ThreadGetProcessExitCode: no such process 62836
ThreadGetProcessExitCode: no such process 62822
ThreadGetProcessExitCode: no such process 62811
ThreadGetProcessExitCode: no such process 62796
ThreadGetProcessExitCode: no such process 62606
pid 62804 != 62803, skipping destruction (fork without exec?)
Game process removed: AppID 1222680 "PROTON_ENABLE_NVAPI=1 DXVK_ASYNC=1 /home/sofi/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1222680 -- /home/sofi/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/games/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/sofi/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  'link2ea://launchgame/1222680?platform=steam&theme=nfsh'", ProcID 62872 
ThreadGetProcessExitCode: no such process 62842
ThreadGetProcessExitCode: no such process 62808
ThreadGetProcessExitCode: no such process 62802
Uploaded AppInterfaceStats to Steam
ExecuteSteamURL: "steam://open/steam://exit/"
[2023-07-01 03:05:15] Shutdown
```
</details>

I cannot figure out if this is a NixOS issue or a Steam issue. As it seems very irregular and shows up differently for similar installs of Steam.

**Comment by ShaddyDC** [comment]
It's broken for me on Hyprland, getting stuck at "Loading user data", but it's working on KDE Wayland.
I'm using the official Hyprland flake, and I've got `pkgs.xdg-desktop-portal-gtk` enabled, although removing that doesn't seem to fix it. Some games like Cyberpunk are also currently broken for me on Hyprland, giving only a black screen, while working fine on KDE, which may or may not be related.

**Comment by LegitCamper** [comment]
I am experiencing a similar issue just after the "loading user data" screen I am greeted with a black box that does nothing.  My log shows the same thing. I am also using the hyprland flake.
> 
> ```
> (process:57874): GLib-GObject-CRITICAL **: 02:41:10.794: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
> ```
edit: after killing my xdg portals mine just sits on the "loading user data" seemingly forever

**Comment by geri1701** [comment]
Steam doesn't start for me either since the new client was available, I also use the hyprland flake. The loading screen hangs at "loading user data...".

**Comment by PedroHLC** [comment]
It seems this also happens in Arch and Fedora: https://github.com/ValveSoftware/steam-for-linux/issues?q=is%3Aissue+-vgui+created%3A%3E%3D2023-06-26

**Comment by Ashe** [comment]
Things are working for me now:
1. Use `steam -vgui` to open steam with old UI
2. Opt-in to steam beta
3. Disable GPU accelerated rendering in web views
4. Close down steam (and maybe reboot machine?)
5. (Maybe) update your conf files to use latest version of NixOS unstable

I hope this helps people

**Comment by Tony-Klink** [comment]
@Ashe this solution doesn't work for me, unfortunately

**Comment by soupglasses** [comment]
I have a possible fix, and i would love to hear if it helps anyone else. Try the following in your NixOS configuration wherever your steam is set up:

```nix
  programs.steam = {
    enable = true;
    package = pkgs.steam.override {
      extraLibraries = p: with p; [
        (lib.getLib networkmanager)
      ];
    };
  };
```

**Comment by soupglasses** [comment]
If you are running an Nvidia graphics card, you can try ONE of the following.

1. Delete Nvidia Cache `~/.cache/nvidia/GLCache`.
2. Use Steam Beta as it has a workaround applied for Nvidia.
3. Disabling `GPU-accelerated web rendering` inside of Steam.

**Comment by x10an14** [comment]
> ```nix
```

**Comment by x10an14** [comment]
> Short term fix: start steam with `steam -vgui` works for me

Seems to start Steam for me, but no games are launchable, even w/graphics card offloading.

**Comment by soupglasses** [comment]
Yeah the `networkmanager` seems to be a dead end, and was a fix to `libgudev 238`, by pulling in `libnm.so` that i found on ArchLinux Bug tracker: https://bugs.archlinux.org/task/79006

But nixpkgs is currently on `237` so it likely doesn't do much.

**Comment by soupglasses** [comment]
For reference, there is an update to `libgudev 238` in nixpkgs here: #241939 but it shouldn't give the issue as seen in Arch.

**Comment by x10an14** [comment]
With a `nix flake update` to nixpkgs df1eee2aa65052a18121ed4971081576b25d6b5c, it works for me today. No other diffs in my nixos config.

**Comment by fr33zing** [comment]
@x10an14 That didn't work for me, is there something I'm missing here?
```
nix flake update nixpkgs
sudo nixos-rebuild switch
```

**Comment by FlorianFranzen** [comment]
> If it's like the previous time, the JS errors were red herrings, and symptoms of the earlier failure.
> 
> I would hazard a guess that this is the actual cause?
> 
> ```
> /nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
> Failed to load module: /nix/store/fac4mci5szyhvjwziqln1c8z4lyzc0z2-dconf-0.40.0-lib/lib/gio/modules/libdconfsettings.so
> ```
@samueldr  This seems to be an impurity. It vanishes on my system if I use `nix-shell --pure -p steam --command steam` instead. And it does not fix the crash.

**Comment by x10an14** [comment]
> @x10an14 That didn't work for me, is there something I'm missing here?
> 
> ```
> nix flake update nixpkgs
> sudo nixos-rebuild switch
> ```

Not AFAIK, but I guess there are more variables to this than I'm aware/this thread has managed to "lock down"?

**Comment by dmayle** [comment]
I ran into this issue a few weeks ago, and at the time, running `steam -no-cef-sandbox` once caused steam to start, and after that I could just run regular steam.

After reboot today, I'm experience the exact same problem again, and nothing seams to get steam working, not the -vgui, not the -no-cef-sandbox, not deleting nvidia cache, not deleting steam packages

**Comment by dmayle** [comment]
I just got steam working again.  I had to `pkill steam`, then I was able to run steam --reset, and after rebooting steam would launch again

**Comment by Tony-Klink** [comment]
> I just got steam working again. I had to pkill steam, then I was able to run steam --reset, and after rebooting steam would launch again

Steam permanently stuck on "Loading user data" screen

**Comment by SrEstegosaurio** [comment]
> Unsure if its the same issue, but I don't have that gnome portal enabled. Here's my logs:
> 
> Log
> You can find my config here: https://github.com/ashe/dotfiles.
> 
> When I try opening steam, it just endlessly sits on the 'log in screen' and no further output displays as shown below
> 
> ![image](https://user-images.githubusercontent.com/8940077/248332229-1ae6f537-0be7-46a3-aed4-8d274caa4450.png)

I'm having the exact same problem but only while in Wayland. If I open Steam on X11 it works fine.
The funniest part about that is that I'm usign the flatpak version. If trying to launch Steam from nixpkgs I don't get to see a window. Even more, I cannot close it. I can close the terminal from which I've launched it and still not closed.

**Comment by Baughn** [comment]
Indications are the nvidia bug is fixed with 535.95... whenever they show up.

**Comment by colemickens** [comment]
@vegaelle what desktop environment, and do you know if you have XDG portals working? And can you confirm if you've tried `steam --reset`?

(I'm running Sway and have been finding Steam pretty seamless other than needing to do `steam --reset` once. )

**Comment by SrEstegosaurio** [comment]
Now, after running `steam --reset` I've managed to pass the _"loading user data"_ screen on Hyprland, using `xdg-desktop-portal-hyprland` and `xdg-desktop-portal-gtk`.

I'm running latest unstable, using the official hyprland flake and most wayland related derivations are being pulled from `nixpkgs-wayland`.

But when finished loading Steam appeared as an unresponsive transparent window.

**Comment by justinrubek** [comment]
> Now, after running `steam --reset` I've managed to pass the _"loading user data"_ screen on Hyprland, using `xdg-desktop-portal-hyprland` and `xdg-desktop-portal-gtk`.
> 
> I'm running latest unstable, using the official hyprland flake and most wayland related derivations are being pulled from `nixpkgs-wayland`.
> 
> But when finished loading Steam appeared as an unresponsive transparent window.

Are you able to open it from a terminal? This is currently how I am launching steam from hyprland. If I do that it works.

**Comment by SrEstegosaurio** [comment]
> Are you able to open it from a terminal? This is currently how I am launching steam from hyprland. If I do that it works.

 @justinrubek sadly that makes no difference. :/

Il fact this time I don't even get pass the _"Loading user data..."_ screen.

**Comment by SrEstegosaurio** [comment]
Launching steam in latest hyprland, using nixpkgs-wayland and steam beta I've got this far:

![20231022_17h29m09s_grim](https://github.com/NixOS/nixpkgs/assets/49443421/183979ba-677b-4fe2-bc54-c37e5eaf8daf)

I can even open games by right-clicking the steam applet on the top right corner...

I also have to launch steam with the `--reset` flag.

**Comment by Dekomoro** [comment]
Don't know if this is a potential fix, but disabling the steam gamescope session had fixed this issue for me

**Comment by vegaelle** [comment]
How do you do it? As far as i understand it, gamescope is a compositor made for steamdeck

**Comment by SrEstegosaurio** [comment]
> How do you do it? As far as i understand it, gamescope is a compositor made for steamdeck

You can actually disable it via options with `programs.steam.gamescopeSession.enable`.

I've tried this and so far got no luck with it.

**Comment by SrEstegosaurio** [comment]
Also, I also get stuck on _"loading user data"_ when using the Flatpak version but only under wayland _(Hyprland)_.

**Comment by dmizelle** [comment]
I ran into this today and I'm not really sure that what I found is related to what other people were seeing. Here's my troubleshooting steps and what I did to fix it.

## How I Fixed It
I ran Steam from the terminal and saw that nothing appeared besides these lines repeating:

```
steamwebhelper.sh[209006]: Runtime for steamwebhelper: defaulting to /home/devon/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[209006]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[209190]: Runtime for steamwebhelper: defaulting to /home/devon/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[209190]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[209376]: Runtime for steamwebhelper: defaulting to /home/devon/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[209376]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()

```

Saw the following in one of the Steam logs that @PedroHLC mentioned:

```
$ tail -f ~/.steam/root/logs/steamwebhelper.log
[1111/154330.691524:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 2 time(s)
[1111/154330.692974:INFO:crash_reporting.cc(271)] Crash reporting enabled for process: gpu-process
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id:
[1111/154330.999616:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 3 time(s)
[1111/154331.001181:INFO:crash_reporting.cc(271)] Crash reporting enabled for process: gpu-process
[1111/154331.011927:WARNING:gpu_process_host.cc(984)] Reinitialized the GPU process after a crash. The reported initialization time was 10 ms
/home/devon/.local/share/Steam/ubuntu12_64/steamwebhelper: /home/devon/.local/share/Steam/ubuntu12_64/steam-runtime-heavy/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
[1111/154331.056497:WARNING:crash_reporting.cc(287)] Failed to set crash key: UserID with value: 0
[1111/154331.056546:WARNING:crash_reporting.cc(287)] Failed to set crash key: BuildID with value: 1698777785
[1111/154331.056549:WARNING:crash_reporting.cc(287)] Failed to set crash key: SteamUniverse with value: Public
[1111/154331.056552:WARNING:crash_reporting.cc(287)] Failed to set crash key: Vendor with value: Valve
[1111/154331.056555:WARNING:crash_reporting.cc(287)] Failed to set crash key: Platform with value: Linux
[1111/154331.057277:INFO:crash_reporting.cc(248)] Crash reporting enabled for process: utility
[1111/154331.212749:INFO:crash_reporting.cc(271)] Crash reporting enabled for process: renderer
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```

Ending up pondering the orb for a bit and then decided to check `dmesg` to see any reports of segfaulting:

```
$ sudo dmesg -T | tail -n 5
[Sat Nov 11 15:46:05 2023] traps: steamwebhelper[211571] general protection fault ip:7f6bc2f63582 sp:7ffc3e862030 error:0 in libglapi.so.0.0.0[7f6bc2f56000+e000]
[Sat Nov 11 15:46:15 2023] traps: steamwebhelper[211697] general protection fault ip:7f97e65aa582 sp:7ffeeb88a550 error:0 in libglapi.so.0.0.0[7f97e659d000+e000]
[Sat Nov 11 15:46:15 2023] traps: steamwebhelper[211715] general protection fault ip:7f97e65aa582 sp:7ffeeb88a550 error:0 in libglapi.so.0.0.0[7f97e659d000+e000]
[Sat Nov 11 15:46:15 2023] traps: steamwebhelper[211735] general protection fault ip:7f97e65aa582 sp:7ffeeb88a550 error:0 in libglapi.so.0.0.0[7f97e659d000+e000]
[Sat Nov 11 15:46:17 2023] traps: steamwebhelper[211658] general protection fault ip:7f45a289e582 sp:7ffc9f62cf70 error:0 in libglapi.so.0.0.0[7f45a2891000+e000]
```

Got me thinking what package provides `libglapi.so.0.0.0`:

```
$ nix-locate libglapi.so.0.0.0 | grep -v '^('
driversi686Linux.mesa.out                       232,836 x /nix/store/kx3dn4gaxz18my9xyj4bpjwzfii3jfws-mesa-22.0.4/lib/libglapi.so.0.0.0
mesa_drivers.out                                317,064 x /nix/store/s4v469a3m7076hcjbwgh6vyy4dinba8h-mesa-22.0.4/lib/libglapi.so.0.0.0
```

Seeing this line in the rebuilding of my `nixosConfiguration` also made me suspect as well:

```
steam-usr-target> warning: collision between `/nix/store/x17mgkzay4g3p4rv2air688nrnbwfnwh-mesa-2cf031/lib/libglapi.so' and `/nix/store/7wxw1dkd6pn6wd5zidd8096m6fknacrg-mesa-23.1.9/lib/libglapi.so'
steam-run-usr-target> warning: collision between `/nix/store/x17mgkzay4g3p4rv2air688nrnbwfnwh-mesa-2cf031/lib/libglapi.so' and `/nix/store/7wxw1dkd6pn6wd5zidd8096m6fknacrg-mesa-23.1.9/lib/libglapi.so'
```

Realized that I was using [`chaotic-cx/nyx`](https://github.com/chaotic-cx/nyx) to give myself `mesa-git` to fix a _very specific issue for a game_. Found [this comment that recommends changing the method as to which it is patched in](https://github.com/chaotic-cx/nyx/issues/260#issuecomment-1678919437) as a troubleshooting step. So I set the following:

```nix
  chaotic = {
    mesa-git = {
      enable = true;
      fallbackSpecialisation = false;
      method = "replaceRuntimeDependencies";
    };
  };
```

Rebuilt my system with `--impure` (which I want to avoid, but I guess that's what I get for using the bleeding edge):

```
sudo nixos-rebuild switch --flake '.#dionysus' -L --verbose --impure
```

**Now steam runs fine from the terminal and I'm able to log in.**

## Rambling

It kind of got me thinking: since it started working once I forced (I guess that's what the `method` option does) `mesa-git` to be used, is there some weirdness going on with multiple versions of `mesa` lying around?

I tried to use `nix-tree` to do some spelunking and noticed this message:

```
trace: replace-dependency.nix: Derivation /nix/store/cj5xwz6m6f73hm054dlz30dq5nxfqsc0-nixos-system-dionysus-23.11.20231104.85f1ba3 does not depend on /nix/store/jx2hkgk3ydlvr6qv5d7wwjcahll19vf2-mesa-23.1.9
```

Anyways, searching for `mesa` with `nix-tree` gave me the following. Sorry, its messy as its a TUI program so I'm snipping some menu stuff:

```
mesa|                  
───────────────────────
mesa-23.1.9-drivers    
mesa-23.1.9-osmesa     
mesa-23.1.9-drivers.drv
mesa-2cf031.drv        
mesa-23.1.9            
mesa-2cf031-drivers    
mesa-2cf031-drivers    
mesa-2cf031            
mesa-2cf031            
mesa-23.1.9-osmesa.drv 
```

One _could_ force usage of the `chaotic-cx/nyx` packages across the derivation/system by setting something like:

```
  nixpkgs.overlays = [
    (
      _: prev: {
        mesa = prev.mesa_git;
        mesa32 = prev.mesa32_git;
      }
    )
  ];
```

This would cause quite a number of packages to be rebuilt though.

I did try and set the following, but it didn't end up fixing Steam not launching.

```
hardware.opengl = {
  package = pkgs.mesa_git.drivers;
  package32 = pkgs.mesa32_git.drivers;
};
```

I would say, if you are running into the above problems, try and see if you are pulling multiple versions of `mesa` and `mesa32` in by using something like nix-tree. Maybe you have different versions of `nixpkgs` for various flake inputs?

**Comment by PedroHLC** [comment]
> Realized that I was using [`chaotic-cx/nyx`](https://github.com/chaotic-cx/nyx) to give myself `mesa-git` to fix a _very specific issue for a game_

Sorry about that, most apps work flawlessly with my libgbm-rename approach, but Firefox wrapper and all the DMs adds mesa to either LD_PRELOAD or LD_LIBRARY_PATH, even though both works without this at all, and breaks my hack. @K900 has a good solution for this though, one day we won't need my hack at all for all mesa versions to seamlessly talk with each other.

FFx wrapper is absurd, it adds a bunch of stuff when only dbus and gstreamer stuff are required for our built-in-house browser. Probably some approach to use pre-compiled browsers and code-sharing between chrome and firefox. Meanwhile, DMs do the best they can to guarantee X11 will start in all distros, even though that's not the best approach for Nix.

Steam will work flawlessly with the mesaa-git pure approach when running directly from a tty (with gamescope), and if you start your DE directly from tty too. Watch out for gamescope's capSysNice option, that breaks randomly.

**Comment by SrEstegosaurio** [comment]
> Steam will work flawlessly with the mesaa-git

I might be mistaken but doesn't `mesa-git` not work when using nvidia on a laptop? Or at least I recall seeing something similar on the [chaotic-cx/nyx](https://github.com/chaotic-cx/nyx) options description.

**Comment by SrEstegosaurio** [comment]
I fixed Steam being transparent for me in Hyprland by disabling hw accel as listed here https://github.com/hyprwm/Hyprland/issues/4173#event-11406636025

**Comment by vendion** [comment]
I'm running into a similar problem, for me of the workarounds suggested here they sometimes work, but it is so inconsistent I can't be certain.

Workarounds I tried:
1. Launching steam with `steam -vgui`
2. Launching steam with `steam --reset`
3. Removing `$HOME/.cache/nvidia/GLCache` directory, then launching steam.
4. Launching steam with `steam -no-cef-sandbox`
5. Overriding the steam package as suggested in https://github.com/NixOS/nixpkgs/issues/238101#issuecomment-1627838797

**Comment by K900** [comment]
This issue has become a complete mess because I'm pretty sure there's like twenty different issues combined here. I'm going to close this, and please file new issues for anything you still experience.
