### ISSUE TITLE
Merge LLVM 4.0 Darwin stdenv

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#24294]
This issue is to help me and @LnL7 (and anyone else who wants to help) track which packages the LLVM 4 upgrade breaks. I'm harvesting it from [here](http://hydra.nixos.org/eval/1344071?compare=trunk#tabs-now-fail).

- [ ] [atlasWithLapack.x86_64-darwin](http://hydra.nixos.org/build/50771271)
- [ ] [atomicparsley.x86_64-darwin](http://hydra.nixos.org/build/50777742)
- [ ] [bedtools.x86_64-darwin](http://hydra.nixos.org/build/50776777)
- [x] [buildbot.x86_64-darwin](http://hydra.nixos.org/build/50775147)
- [x] [caf.x86_64-darwin](http://hydra.nixos.org/build/50772243)
- [x] [capnproto.x86_64-darwin](http://hydra.nixos.org/build/50770122)
- [ ] [flann.x86_64-darwin](http://hydra.nixos.org/build/50777805)
- [ ] [grib-api.x86_64-darwin](http://hydra.nixos.org/build/50776566)
- [ ] [haskellPackages.foldl-statistics.x86_64-darwin](http://hydra.nixos.org/build/50776441)
- [ ] [haskellPackages.pipes-concurrency.x86_64-darwin](http://hydra.nixos.org/build/50770477)
- [x] [iperf2.x86_64-darwin](http://hydra.nixos.org/build/50773927)
- [ ] [lean2.x86_64-darwin](http://hydra.nixos.org/build/50777700)
- [x] [nix.x86_64-darwin](http://hydra.nixos.org/build/50772793)
- [x] [nixStable.x86_64-darwin](http://hydra.nixos.org/build/50776967)
- [x] [nodejs-4_x.x86_64-darwin](http://hydra.nixos.org/build/50772514)
- [x] [nodejs-slim-4_x.x86_64-darwin](http://hydra.nixos.org/build/50777243)
- [x] [podofo.x86_64-darwin](http://hydra.nixos.org/build/50772525)
- [x] [qt4.x86_64-darwin](http://hydra.nixos.org/build/50770432)
- [x] [qt48.x86_64-darwin](http://hydra.nixos.org/build/50775490)
- [x] [qt48Full.x86_64-darwin](http://hydra.nixos.org/build/50772538)
- [x] [qt56.qtbase.x86_64-darwin](http://hydra.nixos.org/build/50770905)
- [x] [qt57.qtbase.x86_64-darwin](http://hydra.nixos.org/build/50776921)
- [ ] [root.x86_64-darwin](http://hydra.nixos.org/build/50774882)
- [x] [rtags.x86_64-darwin](http://hydra.nixos.org/build/50777321)
- [x] [rustc.x86_64-darwin](http://hydra.nixos.org/build/50775846)
- [ ] [swftools.x86_64-darwin](http://hydra.nixos.org/build/50772296)
- [ ] [vtk.x86_64-darwin](http://hydra.nixos.org/build/50777940)

**Comment by copumpkin** [comment]
For `capnproto`, see https://github.com/sandstorm-io/capnproto/issues/433

**Comment by LnL7** [comment]
I think the `qt57` and `qt56` failures are just because it was fixed in master recently.

**Comment by LnL7** [comment]
Looks like `nodejs-4_x` works with https://github.com/NixOS/nixpkgs/pull/24329

**Comment by copumpkin** [comment]
Buildbot appears to be spurious

**Comment by copumpkin** [comment]
`iperf2` fixed in https://github.com/NixOS/nixpkgs/commit/c46600d47b12ba81f8cc88dc4240ac58cad467f3

**Comment by copumpkin** [comment]
`root` is caused by https://sft.its.cern.ch/jira/browse/ROOT-8728

**Comment by copumpkin** [comment]
For `rustc`, see https://github.com/rust-lang/rust/issues/37609. For now I'll point `rustc` at an LLVM 3.9 `stdenv`, since that appears to be working fine (build still hasn't finished but looks like it's moving as expected).

**Comment by copumpkin** [comment]
@LnL7 fixed `rustc` in https://github.com/NixOS/nixpkgs/commit/01d8d1b062495b47c80a765a90176b70dc09a347

**Comment by copumpkin** [comment]
`qt4` and friends seem to be a signed pointer comparison, so should be an easy fix (if the build ever finishes)

**Comment by copumpkin** [comment]
I have a working `qt4` build that I'll push later. Also, `caf` should be fixed by adding this patch: https://github.com/actor-framework/actor-framework/commit/c5a3ee26a6e76b28dd4226f35230b280f291386d (see https://github.com/actor-framework/actor-framework/issues/545 for more)

**Comment by copumpkin** [comment]
`qt4` and friends fixed in https://github.com/NixOS/nixpkgs/commit/409fe12f7653bd1d9c20cf2759e32fc38f5c3ef4

**Comment by copumpkin** [comment]
`caf` fixed in https://github.com/NixOS/nixpkgs/commit/8636ce283fd9ec1d16ea604b4dd5a26b8c59c69a

**Comment by copumpkin** [comment]
`rtags` in https://github.com/NixOS/nixpkgs/commit/3a9c217804688668404ebfe9a199e6e85297a3a7

**Comment by copumpkin** [comment]
This is now merged into staging

**Comment by vcunat** [comment]
Now it's in master, but note the two [failures in the unstable job](http://hydra.nixos.org/build/51317581#tabs-constituents).

**Comment by copumpkin** [comment]
Thanks! I'll look into the bootstrap tools issue. Nix is currently broken
against LLVM 4 but the next 1.11 release will fix it. If that takes too
long to appear I'll apply the patch in our expression but I'd prefer not to

**Comment by copumpkin** [comment]
@vcunat figured out the `stdenvBootstrapTools` issue, just running a (long) test build and will push a fix later. Do you think I should just apply an ad-hoc fix to Nix?

**Comment by vcunat** [comment]
If it's `optional stdenv.isDarwin`, I think nothing will be harmed.

**Comment by copumpkin** [comment]
@vcunat it should be pretty harmless on other platforms too, and I don't think Nix causes many rebuilds, right? The patch just makes it conform more strictly to C++ rules (which LLVM 4 now cares about)

**Comment by copumpkin** [comment]
Okay, both failures should be fixed now 😄

**Comment by vcunat** [comment]
The bootstrapping is still failing on Hydra: http://hydra.nixos.org/build/51386512 (which is after 72d9016b8b)

**Comment by copumpkin** [comment]
Yeah there's another issue that I'm about to fix, unrelated to LLVM 4 and
caused by our recent purchase of more Macs and an impurity

**Comment by copumpkin** [comment]
So the issue causing http://hydra.nixos.org/build/51386512/nixlog/1 should be fixed in https://github.com/NixOS/nixpkgs/commit/d93f2c38659b6ec5a61428ce504626e742c2a361
