### ISSUE TITLE
Docker fails to run containers

### ISSUE THREAD

**Issue by ppom0** [NixOS/nixpkgs#244159]
### Describe the bug

docker fails to run containers since go has been updated to go1.20.6.

Issue is known upstream: https://github.com/moby/moby/issues/45935 (concise explanation in https://github.com/docker/cli/issues/4437#issuecomment-1637715017)

### Steps To Reproduce
1. Update from the channel nixos-23.05-small
2. Try a `docker run alpine sh`. Fails with `http: invalid Host header`

### Expected behavior

I can run containers on my server :sob: 

### Quickfix

While I'm waiting for a released fix on nixpkgs, how can I circumvent this? Easiest way seems to downgrade go version used to compile various docker binaries, but docker's https://github.com/nixOS/nixpkgs/blob/master/pkgs/applications/virtualization/docker/default.nix can't accept overrides as various packages are built in a `let...in`.

Is there an easy way to revert commit e5a213cdcef7cebd8c2e2e07767fc943370dfbb5 in nixpkgs?
Or is there any easy way to fix this?

Thanks y'all!

### Notify maintainers

docker: @offlinehacker @tailhook @vdemeester @periklis @mikroskeem @maxeaubrey 
go: @kalbasit @Mic92 @zowoq @qbit 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.2067.5f621193137`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05-small, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by marysaka** [comment]
Same issue here, all my containers died on last auto upgrade.

**Comment by skeuchel** [comment]
> ### Quickfix
> While I'm waiting for a released fix on nixpkgs, how can I circumvent this? Easiest way seems to downgrade go version used to compile various docker binaries, but docker's https://github.com/nixOS/nixpkgs/blob/master/pkgs/applications/virtualization/docker/default.nix can't accept overrides as various packages are built in a `let...in`.
> 
> Is there an easy way to revert commit [e5a213c](https://github.com/NixOS/nixpkgs/commit/e5a213cdcef7cebd8c2e2e07767fc943370dfbb5) in nixpkgs? Or is there any easy way to fix this?

You can also pin nixpkgs to a working commit.

> I find it very strange that I'm the first one reporting this issue, as #242949 has been merged on the 12th.
> Also I don't get why I already have it on my production system while [nixpk.gs indicates it is not in production yet](https://nixpk.gs/pr-tracker.html?pr=242949)

That is tracking the master -> nixos-unstable path. The commit was backported to 23.05. It went through the staging branches first, that's why it took some time to show up in the stable branches. That's why it took so long to show up in production after the initial commit.

**Comment by sudoexec** [comment]
For anyone who don't want to rollbak, exec into docker container without docker exec:
- `docker inspect --format '{{.State.Pid}}' ${CONTAINER_NAME}`
- sudo nsenter --target ${PID} --mount --uts --ipc --net --pid
- nsenter --target ${PID} --mount --uts --ipc --net --pid

**Comment by htower** [comment]
Hello, I also have this problem. On one machine, I did a rollback as suggested by the author of the topic - everything works as it should. On another system, I upgraded to the latest version, but unfortunately nothing has changed:

```
~ # nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.2143.fa793b06f56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


~ # docker --version    
Docker version 20.10.25, build v20.10.25

~ # docker run alpine sh
http: invalid Host header
```

It is worth noting that all my docker-based services work fine on this machine, although I do not run them directly, but through `docker-compose`.

Does anyone reproduce this bug after the "fix" merge, or is it just me who is so "lucky"? To be honest, the breakdown of such an important basic component as docker surprised me very unpleasantly. I would like more stability and predictability of the software on the servers, but I don't really want to go back to debian :(

**Comment by ipoupaille** [comment]
Same for me, not working with 23.05.2143.fa793b06f56 (docker 20.10.25)

**Comment by vst** [comment]
I have updated my nixos-23.05 channel that is supposed to have received backported fix by now:

https://nixpk.gs/pr-tracker.html?pr=244310

However, I still get the same error. I may be missing something, though.

Currently, I am using the (not) so yummy hack to soothe the pain:

```sh
docker context create localhost --docker "host=ssh://localhost"
```

.., and then:

```sh
docker --context localhost run -it hello-world
```

**Comment by ipoupaille** [comment]
I prefer replacing just docker client with working value like this:
environment.systemPackages =
    let
      pinnedPkgs = import(pkgs.fetchFromGitHub {
        owner = "NixOS";
        repo = "nixpkgs";
        rev = "b6bbc53029a31f788ffed9ea2d459f0bb0f0fbfc";
        sha256 = "sha256-JVFoTY3rs1uDHbh0llRb1BcTNx26fGSLSiPmjojT+KY=";
      }) { config = config.nixpkgs.config; };
      pinnedDocker = pkgs.runCommand "pinned-docker" {} ''
        mkdir -p $out/bin
        ln -s ${lib.getBin pinnedPkgs.docker}/bin/docker $out/bin/docker
      '';
    in
    [ 
      (pkgs.hiPrio pinnedDocker)
    ];

**Comment by tomgray** [comment]
You can also use an overlay in your Nix configuration (`/etc/NixOS/configuration.nix` on NixOS) to pin the version of the `docker` derivation to an older revision of `nixpkgs` similar to the comment above:

```
  # pin docker to older nixpkgs: https://github.com/NixOS/nixpkgs/issues/244159
  nixpkgs.overlays = [
    (let
      pinnedPkgs = import(pkgs.fetchFromGitHub {
        owner = "NixOS";
        repo = "nixpkgs";
        rev = "b6bbc53029a31f788ffed9ea2d459f0bb0f0fbfc";
        sha256 = "sha256-JVFoTY3rs1uDHbh0llRb1BcTNx26fGSLSiPmjojT+KY=";
      }) {};
    in
    final: prev: {
      docker = pinnedPkgs.docker;
    })
  ];
```

**Comment by jgus** [comment]
+1. Still broken for me without the workaround of pinning to an older version.

**Comment by SuperSandro2000** [comment]
> I find it very strange that I'm the first one reporting this issue, as #242949 has been merged on the 12th. Also I don't get why I already have it on my production system while [nixpk.gs indicates it is not in production yet](https://nixpk.gs/pr-tracker.html?pr=242949)
> 
> ![nixpk.gs screenshot](https://user-images.githubusercontent.com/38916722/254270280-2ae360af-5a3a-4450-8944-237cc2ffe333.png)

The linked PR is not in some channel yet, so the status of this hasn't changed and it doesn't help anyone if more people comment that they still have the problem. Please refrain from commenting that. If the PR has landed and the problem isn't fixed yet, please make you heard.

**Comment by SuperSandro2000** [comment]
> I prefer replacing just docker client with working value like this:

You rather want to use the option ``virtualisation.docker.package``.

**Comment by zackelan** [comment]
> The linked PR is not in some channel yet, so the status of this hasn't changed and it doesn't help anyone if more people comment that they still have the problem. Please refrain from commenting that. If the PR has landed and the problem isn't fixed yet, please make you heard.

yes, it has landed, and the problem still isn't fixed. that's why people are commenting.

#244310 backported the change to 23.05. that change [has made it to the release channel](https://nixpk.gs/pr-tracker.html?pr=244310).

looking at [the `release-23.05` commit history](https://github.com/NixOS/nixpkgs/commits/release-23.05?after=0ee595490f5b1d181cccc17928aa250faf4b91c1+34&branch=release-23.05&qualified_name=refs%2Fheads%2Frelease-23.05), that backport went in as `b8f0f72fce33bec8332cb2670d073dcc34684088` on July 19th. 

on a test box running 23.05, which I just upgraded to make sure I've got the latest from the release channel:

```
$ nixos-version
23.05.2162.6da4bc6cb07 (Stoat)
```

[`6da4bc6cb07`](https://github.com/NixOS/nixpkgs/commit/6da4bc6cb07cba1b8e53d139cbf1d2fb8061d967) went in to `release-23.05` yesterday (the 21st). so by all accounts the version on my running system should include the backported patch. and yet:

```
$ docker run alpine sh
http: invalid Host header
```

**Comment by ipoupaille** [comment]
> 

With my solution, only docker client is replaced, not docker daemon.

**Comment by dali99** [comment]
This is still an  issue on 23.05

**Comment by LeSuisse** [comment]
A patch was missed in the first workaround, see #245178

**Comment by dali99** [comment]
This seems fixed now (at least in the stable-small channel), so I'm closing this again :)

**Comment by kido5217** [comment]
It's still broken for me on default channel `nixos-23.05`

```sh
kido@vivec ~> sudo nix-channel --list
nixos https://nixos.org/channels/nixos-23.05
```
```sh
kido@vivec ~> sudo nixos-rebuild switch --upgrade
unpacking channels...
building Nix...
building the system configuration...
activating the configuration...
setting up /etc...
reloading user units for kido...
setting up tmpfiles
```
```sh
kido@vivec ~> sudo docker run hello-world
http: invalid Host header
```
Should I wait some more?

**Comment by dali99** [comment]
You can track the fix in https://nixpk.gs/pr-tracker.html?pr=245179

As you can see it has not yet reached the 23.05 channel

**Comment by speckbr** [comment]
Why are we downgrading go when this issue was already fixed in docker 24.0.5?

**Comment by dali99** [comment]
We are not downgrading go, we're just patching docker to work with the newer go. These patches will disappear when the docker package is upgraded later

**Comment by n8henrie** [comment]
Still broken for me on release-23.05, after a `nix flake update` (nixos.verison 23.05.20230727.9462344), even though it seems like this has been backported.

```
# docker compose up
[+] Building 0.0s (0/0)
http: invalid Host header
```

**Comment by ipoupaille** [comment]
That is working for me (not using flake)
nixos-version: 23.05.2274.6dc93f0daec

**Comment by frprm** [comment]
> Still broken for me on release-23.05, after a `nix flake update` (nixos.verison 23.05.20230727.9462344), even though it seems like this has been backported.
> 
> ```
> # docker compose up
> [+] Building 0.0s (0/0)
> http: invalid Host header
> ```
> 
> EDIT: Looks like it might be a docker vs docker compose issue, `docker run hello-world` works.

I observed the same. Docker compose exhibits the issue and Docker doesn’t…

**Comment by LeSuisse** [comment]
For compose please see and test #245782.

Note the issue also likely exist for buildx, the corresponding upstream PR is https://github.com/docker/buildx/pull/1953
Feel free to take a look, I will not have time to deal with it before this week end.

**Comment by n8henrie** [comment]
https://github.com/NixOS/nixpkgs/pull/245782 works great, thank you!

**Comment by vidbina** [comment]
Bumped into this issue today and my workaround was to build Docker with Go v.1.18 for reasons outlined in https://github.com/NixOS/nixpkgs/issues/245365#issuecomment-1656806031.

```nix
virtualization.docker.package = docker.override {
  buildGoPackage = pkgs.buildGo118Package;
}
```

**Comment by felipelalli** [comment]
> ### Quickfix
> 
>     1. Add this to `/etc/nixos/configuration.nix` to [pin nixpkgs](https://nix.dev/reference/pinning-nixpkgs) to just before the [offending commit](https://github.com/NixOS/nixpkgs/commit/e5a213cdcef7cebd8c2e2e07767fc943370dfbb5):
> 
> 
> ```nix
>   nix.nixPath = [
>     "nixpkgs=https://github.com/NixOS/nixpkgs/archive/b6bbc53029a31f788ffed9ea2d459f0bb0f0fbfc.tar.gz"
>     "nixos-config=/etc/nixos/configuration.nix"
>     "/nix/var/nix/profiles/per-user/root/channels"
>   ];
> ```
> 
>     2. Run `sudo nixos-rebuild switch` once. It updates the `NIX_PATH` for future invocations.
> 
>     3. Run `sudo nixos-rebuild switch` a second time. It rebuilds your system taking into account the new `NIX_PATH`.
> 
> 
> Just hope that downgrading all the other software updated since then won't break anything else crossed_fingers (It didn't on my server)

It looks dangerous. What are the consequences?

**Comment by felipelalli** [comment]
> My version is still 23.05.2162.6da4bc6cb07 - how can I upgrade? (I'm newbie on NixOS)

**Comment by felipelalli** [comment]
> That is working for me (not using flake) nixos-version: 23.05.2274.6dc93f0daec

My version is still 23.05.2162.6da4bc6cb07 - how can I upgrade? (I'm newbie on NixOS)

**Comment by jarjee** [comment]
> For compose please see and test #245782.
> 
> Note the issue also likely exist for buildx, the corresponding upstream PR is [docker/buildx#1953](https://github.com/docker/buildx/pull/1953) Feel free to take a look, I will not have time to deal with it before this week end.

Now that this has been merged into 23.05, I did a rebuild and this fixed my devcontainers, thank you for the patch.


> > That is working for me (not using flake) nixos-version: 23.05.2274.6dc93f0daec
> 
> My version is still 23.05.2162.6da4bc6cb07 - how can I upgrade? (I'm newbie on NixOS)

It depends on how you've set up your system, but I'm assuming you're not using flakes.

```bash
sudo nixos-rebuild switch --upgrade
```
You can also check how to update & manage channels in the [NixOS Manual](https://nixos.org/manual/nixos/stable/#sec-upgrading) (for the inevitable 23.11 release)

**Comment by happyalu** [comment]
It appears `buildx` is still affected by this.

```
❯ docker buildx build .
[+] Building 0.0s (0/0)
ERROR: http: invalid Host header
```

```
❯ nixos-version
23.05.20230801.bd836ac (Stoat)
```

```
❯ docker version
Client:
 Version:           20.10.25
 API version:       1.41
 Go version:        go1.20.6
 Git commit:        v20.10.25
 Built:             Thu Jan  1 00:00:00 1970
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       v20.10.23
  Built:            Tue Jan  1 00:00:00 1980
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.1
  GitCommit:        v1.7.1
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Comment by felipelalli** [comment]
> > That is working for me (not using flake) nixos-version: 23.05.2274.6dc93f0daec
> 
> My version is still 23.05.2162.6da4bc6cb07 - how can I upgrade? (I'm newbie on NixOS)

It worked for me:

```
sudo nix-channel --update
sudo nixos-rebuild switch
```

**Comment by dmizelle** [comment]
Confirmed that this is now resolved for me on `nixos-unstable` branch of `nixpkgs` at commit `18036c0be90f4e308ae3ebcab0e14aae0336fe42`.

**Comment by PierreR** [comment]
> It appears `buildx` is still affected by this.

Same here using https://releases.nixos.org/nixos/23.05-small/nixos-23.05.2799.771b86d407c5,  released on 2023-08-14 06:44:13
