### ISSUE TITLE
python3: running python scripts under root changes nix store

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#24924]
## Issue description

Running python3 scripts under root results in nix store corruption
File ```${pkgs.python3}/lib/python3.5/__pycache__/_sysconfigdata.cpython-35.pyc``` appears there.

### Steps to reproduce

![py3bug](https://cloud.githubusercontent.com/assets/508305/25062713/ddd9f5be-21c0-11e7-9e89-a418329d6d52.png)

## Technical details

* System: 17.03.git.7fc765a (Gorilla)
* Nix version: 1.12pre5122_c60715e
* Nixpkgs version: "17.03.git.c9f4424b0c"

**Comment by FRidh** [comment]
It's undesirable but this indeed happens. As root you can write to the store, and CPython always tries to update its bytecode when it can. The only way to prevent this from happening when running as root would be to somehow patch CPython so that it doesn't update bytecode that is situated in `/nix/store`.

In any case, here it seems it doesn't just update its bytecode. It creates a file, `__pycache__/_sysconfigdata.cpython-35.pyc`, which we removed in the `postFixup`. The original Python file contained references which we didn't want to have, so we patched that, but the `.pyc` file was already generated so it was removed. The line of code removing the file mentioned it had to be regenerated. 

I actually fixed regenerating the files deterministically earlier, however, it didn't fix this issue yet because the files are regenerated before this file is removed. The patch is therefore quite easy.

**Comment by Mic92** [comment]
How does this work? I thought that `/nix/store` is bind-mounted read-only?

**Comment by FRidh** [comment]
I think that should be considered a bug as well. I see no reason that the nix store should be mounted as `rw` when using `nix-shell`.

**Comment by Mic92** [comment]
In this case, this should be a new issue in https://github.com/NixOS/nix

**Comment by FRidh** [comment]
I've pushed a fix to staging https://github.com/NixOS/nixpkgs/commit/5c8ffe0311ca2bdd477cc6bc3c9b101ca75e16e5

**Comment by FRidh** [comment]
@volth can you confirm this has been fixed on master / nixos-unstable?

**Comment by volth** [comment]
In [nixpkgs-unstable](https://github.com/NixOS/nixpkgs-channels/commits/nixpkgs-unstable) is not fixed.
I am going to check [nixos-unstable](https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable) in a few hours, it is 200+ commits ahead

**Comment by FRidh** [comment]
@volth the commit indeed hasn't landed yet in `nixpkgs-unstable`.

**Comment by volth** [comment]
Fixed in ```nixos-unstable```
