### ISSUE TITLE
NixOS unstable fails to build warlock

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#25470]
## Issue description

```
running egg_info
writing requirements to warlock.egg-info/requires.txt
writing warlock.egg-info/PKG-INFO
writing top-level names to warlock.egg-info/top_level.txt
writing dependency_links to warlock.egg-info/dependency_links.txt
reading manifest file 'warlock.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'warlock.egg-info/SOURCES.txt'
Copying warlock.egg-info to build/bdist.linux-x86_64/wheel/warlock-1.2.0-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/warlock-1.2.0.dist-info/WHEEL
installing
/tmp/nix-build-python2.7-warlock-1.2.0.drv-0/warlock-1.2.0/dist /tmp/nix-build-python2.7-warlock-1.2.0.drv-0/warlock-1.2.0
Processing ./warlock-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: jsonschema<3,>=0.7 in /nix/store/6cvp8v15virzaadpyiqc5bsxv6vg1r6r-python2.7-jsonschema-2.5.1/lib/python2.7/site-packages (from warlock==1.2.0)
Requirement already satisfied: jsonpatch<2,>=0.10 in /nix/store/8kki25mznddiv5wvjwrcawjm931rhpjc-python2.7-jsonpatch-1.11/lib/python2.7/site-packages (from warlock==1.2.0)
Processing ./stevedore-1.7.0-py2.py3-none-any.whl
Requirement already satisfied: six in /nix/store/m0apm5s8w43q8r9q9ciz3xj6vvxj5xci-python2.7-six-1.10.0/lib/python2.7/site-packages (from warlock==1.2.0)
Requirement already satisfied: functools32; python_version == "2.7" in /nix/store/pb415bpgr4gliq3k4l7i65xcq26bjvqv-python2.7-functools32-3.2.3-2/lib/python2.7/site-packages (from jsonschema<3,>=0.7->warlock==1.2.0)
Requirement already satisfied: jsonpointer>=1.9 in /nix/store/a1f0h5q27gy8aznyn306dqispabjds08-python2.7-jsonpointer-1.9/lib/python2.7/site-packages (from jsonpatch<2,>=0.10->warlock==1.2.0)
Installing collected packages: warlock
Successfully installed warlock-1.2.0
/tmp/nix-build-python2.7-warlock-1.2.0.drv-0/warlock-1.2.0
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/7wfg41kzmvv5zgf2arcicf481pfnqngs-python2.7-warlock-1.2.0
stripping (with flags -S) in /nix/store/7wfg41kzmvv5zgf2arcicf481pfnqngs-python2.7-warlock-1.2.0/lib
patching script interpreter paths in /nix/store/7wfg41kzmvv5zgf2arcicf481pfnqngs-python2.7-warlock-1.2.0
Requirement already satisfied: argparse in /nix/store/xd23v7nwcy15mka9qnbqbgb8sl36ihwg-python2.7-argparse-1.4.0/lib/python2.7/site-packages (from stevedore==1.7.0)
Collecting pbr<2.0,>=1.3 (from stevedore==1.7.0)
  Could not find a version that satisfies the requirement pbr<2.0,>=1.3 (from stevedore==1.7.0) (from versions: )
No matching distribution found for pbr<2.0,>=1.3 (from stevedore==1.7.0)
builder for ‘/nix/store/v54s56rk8zhhvnivrzc5h1massz8j45q-python2.7-stevedore-1.7.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/gd7xka1hm9g7zbd1c64hprzkwg5p5pba-python2.7-keystoneauth1-1.1.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/id6im6hcljvjvi46jv87c5q4czhrf8qn-python2.7-keystoneclient-1.8.1.drv’: 1 dependencies couldn't bebuilt
cannot build derivation ‘/nix/store/gm77j3i4cq30wky924b7g2qfkshnkgi4-python2.7-oslo.config-2.5.0.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/0031v1s9jp595p8xh4ygkv3wy3fa72c9-qemu.conf’
building path(s) ‘/nix/store/rvcc67yvgpdamaggxlnshjch7mahs2n6-reader.conf’
cannot build derivation ‘/nix/store/vbbvjiwc4vjqnir8h37y7npxksilscsj-python2.7-glanceclient-1.1.0.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/902mimp2bhq5bp1gmwl82z1v4nc54176-reload-container’
cannot build derivation ‘/nix/store/jpl3f0i25z9ygidqfcswk1ahmb8nkxgm-virt-manager-1.4.1.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/aq70bfm3l0xxghiazv4sbxc1hmzm8g3g-virtualbox-5.1.18’, ‘/nix/store/l4rm3910fbl0dfnys66a4bipy8hr3iaw-virtualbox-5.1.18-modsrc’
cannot build derivation ‘/nix/store/cximrlmvc4n72qrdxy8xzgrwd3mp9583-system-path.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/nz6mx3h43jqc2w42n804rw5i585n6vfa-systemd-user.pam’
building path(s) ‘/nix/store/4pnaffan4vni15yjkrccdri2kg32d89d-torrc’
building path(s) ‘/nix/store/fpnxfzb3i0vbzz6yhrb269v8mx5r866v-torsocks.conf’
building path(s) ‘/nix/store/x2ps4k2l83gn48h001czapfd7lm8d9sa-udev-rules’
cannot build derivation ‘/nix/store/z1lhwyca1phv6bb8lgd6l3c9h0w6dv4k-nixos-system-subi-17.09pre106801.207a0af06a.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/z1lhwyca1phv6bb8lgd6l3c9h0w6dv4k-nixos-system-subi-17.09pre106801.207a0af06a.drv’ failed
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre106299.7f3b857d0d (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.9

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre106801.207a0af06a"

**Comment by bachp** [comment]
I can not reproduce this. `nix-build -A pythonPackages.warlock` is working correctly with https://github.com/NixOS/nixpkgs/commit/c5badb123a2dd6e2b38dcd2ddbe73e13dc6b554f.

It might help if you can provide your `/etc/nixos/configuration.nix`.

**Comment by sjau** [comment]
Now I get:

```
error: Package ‘python2.7-os-testr-0.4.2’ in ‘/nix/store/zaphjxhxnrx2cncmbmpaacqv4w503cgf-nixos-17.09pre106916.c5badb123a/nixos/pkgs/development/interpreters/python/mk-python-derivation.nix:56’ is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

my config: https://github.com/sjau/nixos/blob/master/configuration.nix

**Comment by bachp** [comment]
If I understand you correctly you are trying to build packages that are marked as broken?

I guess the packages are marked broken for a reason, probably because they don't compile.

**Comment by sjau** [comment]
No, what I try to do is run

```
nixos-rebuild switch --upgrade
```

And now I get those errors.

**Comment by FRidh** [comment]
There was some breakage on master due to a `pbr` update. Most of the fallout has been fixed but in between a channel update occurred. The package does build on master at 5db271c99a3313d36d72e008ad5db1335024de5e so I am closing this.

**Comment by jeremejevs** [comment]
How do I make this work in the meanwhile? Can't use `virtmanager` otherwise. I'm trying the following:

```nix
nixpkgs.config = {
  packageOverrides = pkgs: rec {
    pythonPackages = pkgs.pythonPackages // {
      os-testr = pkgs.callPackage /latest-nixpkgs-master/pkgs/development/python-modules/os-testr { };
    };
  };
};
```

But `NIXPKGS_ALLOW_BROKEN=1 nixos-rebuild switch` still tries building `os-testr` 0.4.2, instead of master's 0.8.1. Am I overriding it wrong?

**Comment by sjau** [comment]
Still getting the error? Shouldn't packages move from master to unstable when they build fine in master?

**Comment by FRidh** [comment]
See the explanation at the top of http://howoldis.herokuapp.com/

The channel has just updated. Furthermore, judging from the tests done
during the past days it seemed quite safe to rebuild directly from master.

**Comment by sjau** [comment]
I'm still getting that error in unstable. You're sure it's fixed?

```
root@subi:~# date
Son Mai  7 18:29:16 CEST 2017
root@subi:~# nixos-rebuild switch --upgrade
downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre106916.c5badb123a/nixexprs.tar.xz’...
downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.09pre106916.c5badb123a/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/s]
unpacking channels...
building Nix...
building the system configuration...
error: Package ‘python2.7-os-testr-0.4.2’ in ‘/nix/store/zaphjxhxnrx2cncmbmpaacqv4w503cgf-nixos-17.09pre106916.c5badb123a/nixos/pkgs/development/interpreters/python/mk-python-derivation.nix:56’ is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
root@subi:~#
```

**Comment by FRidh** [comment]
```
$ git fetch channels && git checkout channels/nixpkgs-unstable && nix-build -A python.pkgs.warlock
HEAD is now at 477fa42be6... maintainers: add vmchale, missing after #25514
/nix/store/7wfg41kzmvv5zgf2arcicf481pfnqngs-python2.7-warlock-1.2.0
```

**Comment by FRidh** [comment]
nixos-unstable
```
$ git fetch channels && git checkout channels/nixos-unstable && nix-build -A python.pkgs.warlock
HEAD is now at c5badb123a... Merge pull request #25482 from PierreR/master
/nix/store/7wfg41kzmvv5zgf2arcicf481pfnqngs-python2.7-warlock-1.2.0
```

**Comment by sjau** [comment]
not really sure how that is supposed to work:

```
git fetch channels && git checkout channels/nixos-unstable && nix-build -A python.pkgs.warlock
fatal: Not a git repository (or any of the parent directories): .git
```
