### ISSUE TITLE
qtwebkit contains a forbidden reference to /tmp/nix-build-qtwebkit-5.6.2.drv-0

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#25585]
## Issue description

Staging recently introduced [a new hook](https://github.com/NixOS/nixpkgs/commit/94d164dd7f20c785a543d1fb1d5bd359fb38bd25) checking for $TMPDIR references. 

References occur in
- [5.6.2](http://hydra.nixos.org/build/52541212)
- [5.8.0](http://hydra.nixos.org/build/52532632), which is blocking Plasma

cc maintainer @abbradar

**Comment by FRidh** [comment]
cc other maintainer @periklis

**Comment by vcunat** [comment]
IIRC I've seen more Qt packages that have this problem.  I assume the short-term solution would be to have a hook that you can explicitly add to remove all such RPATH references. (or extend the current one with an explicit option)

I think it should break nothing, as the TMPDIR paths should be nonexistent normally.

**Comment by vcunat** [comment]
(I assume this is marked as *security* due to having security updates in staging.)

**Comment by dezgeg** [comment]
The problem is security-related since any user can create `/tmp/nix-build-qtwebkit-5.8.0.drv-0` and cause other users of the same package to load `.so`:s from that path.

Now if we had https://github.com/NixOS/patchelf/commit/48143414941d91016efca2b0ef6f32475d6eaa75 in a patchelf release we could use that.

**Comment by vcunat** [comment]
I thought the security part was resolved by the hook, killing packages with insecure RPATHs, but that certainly does make the topic security related.

**Comment by periklis** [comment]
Is this only darwin-related? If yes, i would say the severity is lower, because qtwebkit builds are still broken and wip on darwin.

**Comment by FRidh** [comment]
No, this is NixOS (and maybe darwin, didn't check).

**Comment by vcunat** [comment]
I disabled that hook on Darwin for now.  This ticket is for NixOS.

**Comment by vcunat** [comment]
/cc @edolstra anyway.  I think we can at least afford to patch the default patchelf on master; it seems safe enough.

IMHO just removing RPATH items leading out of nix store is a good default action, at least on Linux.  (That patchelf change prints a warning when it does so.)

**Comment by dezgeg** [comment]
It's a debug level message in patchelf though.

**Comment by vcunat** [comment]
Actually there's a simple hack that makes the standard patchelf phase remove the reference:
```
preFixup = ''rm -rf "$(pwd)" '';
```

I suppose that's a good enough workaround for now?  (If accompanied by explanation in comment.)

**Comment by vcunat** [comment]
I forgot to say, it utilizes the fact that we run it with `--shrink-rpath` by default.

**Comment by ttuegel** [comment]
The Qt setup hook removes these references from the RPATH of other Qt-based packages. If that's not happening for `qtwebkit`, it indicates that it's packaged incorrectly.
