### ISSUE TITLE
Removing users.extraUsers.<user>.openssh.authorizedKeys.keys does not remove /etc/ssh/authorized_keys.d/<user>

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#2559]
This is because this file is stored as a regular file rather than as a symlink to /etc/static. So the etc updater script doesn't know that it needs to delete it.

**Comment by Profpatsch** [comment]
(triage) what’s the status?

**Comment by aszlig** [comment]
There is an [upstream report to allow `StrictModes` within `Match`](https://bugzilla.mindrot.org/show_bug.cgi?id=2498), once this is implemented we can generate the `sshd_config` like this:

```nix
''
  ... some sshd options ...

  ${map (user: ''
  Match User ${user.name}
    StrictModes no
    AuthorizedKeysFile ${pkgs.writeText "authorized-keys-${user.name}" ''
      ${concatStringsSep "\n" user.openssh.authorizedKeys.keys}
      ${concatMapStringsSep "\n" readFile user.openssh.authorizedKeys.keyFiles}
    ''}
  '') usersWithKeys}

  ... other sshd options ...
''
```

This would be way less racy than adding a "authorized keys file cleaner".

I also thought about patching OpenSSH to prevent mode checking on store paths, but this would actually lead to roughly the same as setting `StrictModes` to `no` because an attacker who is able to modify the `authorized_keys` file in the user's home directory can simply create a file in the Nix store and symlink to it, whereas with `StrictModes` it's assured that the file is only writable by the corresponding user so an attacker can't do the "symlink to the Nix store" trick to bypass that.

Selectively turning off `StrictModes` for only a limited set of `authorized_keys` allows us to still have that check on for user home directories while not checking the modes when we explicitly state the allowed keys by creating a store path along with the main `sshd_config`.

**Comment by Profpatsch** [comment]
(triage) still an issue?

**Comment by bjornfor** [comment]
Doh! This is bad. (I just switched to this API, thinking "yay, declarative keys!")

**Comment by grahamc** [comment]
Seems to be long fixed:

```
grahamc@Morbo> sudo nixos-rebuild switch
[sudo] password for grahamc: 
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/librlnhh1ncb0im17b6wm2x2hwq2xws6-grahamc-authorized_keys.drv
  /nix/store/00khi83m940w76a59jbs9jhg6pak4k64-etc.drv
  /nix/store/0na2nmpssnh5szpxrxa2898dym0ywspy-nixos-system-Morbo-17.03.1700.51a83266d1.drv
building path(s) ‘/nix/store/26092zqbjkgx0cwgf08wsh1a5j1axwva-grahamc-authorized_keys’
building path(s) ‘/nix/store/dl0m1zdw6vibzksscnphi93sd57g01sq-etc’
building path(s) ‘/nix/store/zkf6wlbi0vsw5j20hz0yjpf1gc7f1xzb-nixos-system-Morbo-17.03.1700.51a83266d1’
activating the configuration...
setting up /etc...
setting up tmpfiles

```

and `/etc/ssh/authorized_keys.d/grahamc` exists... removed the option, and:

```
grahamc@Morbo> sudo nixos-rebuild switch
building Nix...
building the system configuration...
activating the configuration...
setting up /etc...
removing obsolete file ‘/etc/ssh/authorized_keys.d/grahamc’...
setting up tmpfiles
grahamc@Morbo> cat /etc/ssh/authorized_keys.d/grahamc
cat: /etc/ssh/authorized_keys.d/grahamc: No such file or directory
```

**Comment by grahamc** [comment]
Fixed in July 2014 : https://github.com/NixOS/nixpkgs/commit/7c480ad89695c1309cc2ed5d07c166722476cd8c thanks @cleverca22

**Comment by acarrico** [comment]
@grahamc as far as I can tell, only the directory ```ssh/authorized_keys.d/user``` is tracked in ```/etc/.clean```, not the keys, and so old keys will still hang around when the user removes or changes them. I would say that is still a security issue.

**Comment by acarrico** [comment]
No that isn't quite right. That is a file, not a directory, but it does seem to keep the old keys. I haven't looked at the derivation; perhaps they are added to the file but never removed.

**Comment by acarrico** [comment]
@grahamc On further testing this is working correctly. Sorry for the false alarm.
