### ISSUE TITLE
LibreWolf can't install addons from Mozilla if ResistFingerprinting is disabled

### ISSUE THREAD

**Issue by awebeer256** [NixOS/nixpkgs#260488]
### Describe the bug
The Nix build of LibreWolf (package `librewolf`) changes the substring, "Firefox," to, "LibreWolf," in the browser's user agent string.  As a result, `addons.mozilla.org` believes that your browser is not Firefox, and so it is impossible to install addons normally from that website.

### Steps To Reproduce
1. Go to `about:preferences#librewolf`
2. Uncheck the box, "Fingerprinting" -> "Enable ResistFingerprinting"
3. Go to the AMO page for any extension that is not currently installed, e.g. [Emoji](https://addons.mozilla.org/en-US/firefox/addon/emoji-sav)

### Expected behavior
There is a button to install the extension.

### Observed behavior
There is the message, "You'll need Firefox to use this extension," and a button to download Firefox.

### Screenshots

None provided.

### Additional context

This bug was fixed in the LibreWolf team's packages [at least a year and a half ago](https://codeberg.org/librewolf/issues/issues/73), and I confirmed that it doesn't currently exist in their Flatpak package. I didn't check whether it exists in the `librewolf-unwrapped` Nix package.

### Notify maintainers

@squalus 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.55, NixOS, 23.05 (Stoat), 23.05.4112.5a237aecb572`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.5`
 - channels(root): `"nixos-23.05, nixos-unstable"`
 - channels(<username>): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by squalus** [comment]
Confirmed that this is a problem. I don't know what's causing it.

To work around this, you can set `general.useragent.compatMode.firefox` to true in `about:config`

**Comment by superherointj** [comment]
Fixed by #321083

**Comment by sysop84** [comment]
Verified this problem is back in LibreWolf-138.0-2-windows-x86_64-portable. Verified problem is not present in LibreWolf-137.0.2-1-windows-x86_64-portable.

Was 138 built with `--with-app-basename`?

**Comment by badplay** [comment]
Its Back on all of my PCS WIndows

**Comment by AntonMeenov** [comment]
@sysop84 @badplay 
https://codeberg.org/librewolf/issues/issues/2459
