### ISSUE TITLE
Logseq, search in

### ISSUE THREAD

**Issue by IogaMaster** [NixOS/nixpkgs#264885]
### Steps To Reproduce
Open logseq, after #264827 is merged.
Type in the window.

### Expected behavior
No errors.

### Screenshots
![image](https://github.com/NixOS/nixpkgs/assets/67164465/779eb255-322e-4297-8ad5-95290f832510)

### Additional context
Running the appimage with `appimage-run` resolves the issue.

### Notify maintainers
@IogaMaster 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.59, NixOS, 23.11 (Tapir), 23.11.20231024.8efd5d1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(iogamaster): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by BruceBoterf** [comment]
thanks @IogaMaster 

I am seeing this on my nix os as well:

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.57, NixOS, 23.05 (Stoat), 23.05.20231013.898cb20`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.17.0`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
 
 ```

**Comment by IogaMaster** [comment]
The issue with logseq is cause by the electron version not matching upstream after #264884

**Comment by davidak** [comment]
> The issue with logseq is caused by the electron version not matching upstream

Then it's probably fixed by now. Can you test again?

Their electron is 27.1.3 while our electron is 27.2.2.

**Comment by calops** [comment]
I can confirm that the error is still present on the latest version.

**Comment by BWbwchen** [comment]
the error is still present on the latest version.

**Comment by chairbender** [comment]
FYI, corresponding issue in logseq: https://github.com/logseq/logseq/issues/10851

**Comment by ebardie** [comment]
Which lead to me skirting the workaround I had in place for the when LoqSeq wasn't working with  the then current version of electron in NixOS.  It's now working fine (or at least doesn't trigger that error immediately, which it was doing with 100% reproducibility).  Doh!
