### ISSUE TITLE
KDevelop broken on unstable

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#27044]
## Issue description

Current unstable seems totally broken:

KDevelop fails to install/build

```
-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
onfig.cmake (found version "5.34.0") 
-- Found KF5XmlGui: /nix/store/ymbvyfr55swrpbxzpfh3r0w51z3kl5vk-kxmlgui-5.34.0-dev/lib/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.34.0") 
CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:13  Could NOT find KF5 (missing: WindowSystem) (found suitable version
  "5.34.0", minimum required is "5.18.0")
Call Stack (most recent call first):
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/yk2v9qp15989i9pnb7bmik9y3fbly8kk-extra-cmake-modules-5.34.0/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/nix-build-kdevplatform-5.1.1.drv-0/kdevplatform-5.1.1/build/CMakeFiles/CMakeOutput.log".
builder for ‘/nix/store/qrrrgx90kn83vp09bzriv19i41jn7qlv-kdevplatform-5.1.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/hhl4i5gnsga7syk333n0j0bb69xwjaaz-kdevelop-5.1.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/rv5jyiqdi0iwmlrmnp8a11z5qq1k4z20-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3xlsv8k86z92w7fah0ap9lq43hc8xjag-nixos-system-subi-17.09pre110094.1add3519df.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/3xlsv8k86z92w7fah0ap9lq43hc8xjag-nixos-system-subi-17.09pre110094.1add3519df.drv’ failed
```

### Steps to reproduce

Running   nixos-rebuild boot --upgrade

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre109180.0d4431cfe9 (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre110094.1add3519df"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

build-use-sandbox = false

**Comment by joachifm** [comment]
cc @ambrop72

**Comment by FRidh** [comment]
fixed in 43ca91106d7d53e5e9214da12dacfdaa9e4672e4

**Comment by sjau** [comment]
Still fails to install:

```
-- Found KF5Notifications: /nix/store/r4zqnffl0zyqabqm6a47nc8xa0ns6avw-knotifications-5.34.0-dev/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.34.0") 
-- Found KF5NotifyConfig: /nix/store/s05xp77fz3ms9613lfzk30v0jyca6kw7-knotifyconfig-5.34.0-dev/lib/cmake/KF5NotifyConfig/KF5NotifyConfigConfig.cmake (found version "5.34.0") 
-- Found KF5KDELibs4Support: /nix/store/hd5s9pdwhpdp8ibska7blfbpykgf5xpd-kdelibs4support-5.34.0-dev/lib/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake (found version "5.34.0") 
-- Found KF5: success (found suitable version "5.34.0", minimum required is "5.15") found components:  I18n KIO XmlGui Notifications NotifyConfig Solid Config CoreAddons DocTools Kross KCMUtils Sonnet DBusAddons Crash Archive KDELibs4Support 
-- Found KF5Parts: /nix/store/ljr3dy2zclk3vmzhwdyzdh56nsw6kgk1-kparts-5.34.0-dev/lib/cmake/KF5Parts/KF5PartsConfig.cmake (found version "5.34.0") 
-- Found KF5Service: /nix/store/v1cbmpy1h91jilrax9w43a0n79lq3hkc-kservice-5.34.0-dev/lib/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.34.0") 
-- Found KF5Sonnet: /nix/store/hsb3v54k678jw3l7ha47bfgmvj8f91zf-sonnet-5.34.0-dev/lib/cmake/KF5Sonnet/KF5SonnetConfig.cmake (found version "5.34.0") 
-- Found KF5TextEditor: /nix/store/41vg64q5fv65g1x01m29bpck51rajydm-ktexteditor-5.34.0-dev/lib/cmake/KF5TextEditor/KF5TextEditorConfig.cmake (found version "5.34.0") 
-- Found KF5ThreadWeaver: /nix/store/lazd87zlglv33p4wzp4jpnnkyq1zpgpw-threadweaver-5.34.0-dev/lib/cmake/KF5ThreadWeaver/KF5ThreadWeaverConfig.cmake (found version "5.34.0") 
CMake Warning at /nix/store/yk2v9qp15989i9pnb7bmik9y3fbly8kk-extra-cmake-modules-5.34.0/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5WindowSystem"                                                          
  (requested version 5.18.0) with any of the following names:     

    KF5WindowSystemConfig.cmake  
    kf5windowsystem-config.cmake 

  Add the installation prefix of "KF5WindowSystem" to CMAKE_PREFIX_PATH or                                                           
  set "KF5WindowSystem_DIR" to a directory containing one of the above files.                                                        
  If "KF5WindowSystem" provides a separate development package or SDK, be                                                            
  sure it has been installed.    
Call Stack (most recent call first):                              
  CMakeLists.txt:49 (find_package)                                


-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake                        
-- Found KF5Declarative: /nix/store/hrfx4ca6hp3dvmlibcwyd2wi7kcrbbvg-kdeclarative-5.34.0-dev/lib/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.34.0") 
-- Found KF5XmlGui: /nix/store/ymbvyfr55swrpbxzpfh3r0w51z3kl5vk-kxmlgui-5.34.0-dev/lib/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.34.0") 
CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: WindowSystem) (found suitable version                                                                 
  "5.34.0", minimum required is "5.18.0")                         
Call Stack (most recent call first):                              
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/yk2v9qp15989i9pnb7bmik9y3fbly8kk-extra-cmake-modules-5.34.0/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:49 (find_package)                                


-- Configuring incomplete, errors occurred!                       
See also "/tmp/nix-build-kdevplatform-5.1.1.drv-0/kdevplatform-5.1.1/build/CMakeFiles/CMakeOutput.log".                              
builder for ‘/nix/store/rr48lpav0l9xc3xiy58742472v7d9d8v-kdevplatform-5.1.1.drv’ failed with exit code 1                             
cannot build derivation ‘/nix/store/vhk89zxq0i1a4j998slfzyb63wlhlqdd-kdevelop-5.1.1.drv’: 1 dependencies couldn't be built           
cannot build derivation ‘/nix/store/im6dwzjw9rpwqffi7kvdfn915rnj4msk-system-path.drv’: 1 dependencies couldn't be built              
cannot build derivation ‘/nix/store/ra556bx144qqkvqiv0wimj186v96yn25-nixos-system-subi-17.09pre110181.c5e314dabe.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ra556bx144qqkvqiv0wimj186v96yn25-nixos-system-subi-17.09pre110181.c5e314dabe.drv’ failed                 
```

17.09pre110094.1add3519df (Hummingbird)
nix-env (Nix) 1.11.11
"17.09pre110181.c5e314dabe"
build-use-sandbox = false
