### ISSUE TITLE
Ktorrent broken on unstable

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#27043]
## Issue description

Current unstable seems totally broken:

KTorrent fails to install/build

```
CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibGcrypt (missing: LibGcrypt_INCLUDE_DIRS       
  LibGcrypt_LIBRARIES) (Required is at least version "1.4.5")     
Call Stack (most recent call first):                              
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/0znc26msy9nvybwnd8x3yaj661i7l4w6-libktorrent-2.0.1-dev/lib/cmake/LibKTorrent/FindLibGcrypt.cmake:108 (find_package_handle_standard_args)
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/CMakeFindDependencyMacro.cmake:55 (find_package)   
  /nix/store/0znc26msy9nvybwnd8x3yaj661i7l4w6-libktorrent-2.0.1-dev/lib/cmake/LibKTorrent/LibKTorrentConfig.cmake:82 (find_dependency)
  CMakeLists.txt:21 (find_package)                                


-- Configuring incomplete, errors occurred!                       
See also "/tmp/nix-build-ktorrent-5.0.1.drv-0/ktorrent-5.0.1/build/CMakeFiles/CMakeOutput.log".                                      
-- Found KF5JobWidgets: /nix/store/3qwp25zfh54x3y3p8n0jqniff51jikz6-kjobwidgets-5.34.0-dev/lib/cmake/KF5JobWidgets/KF5JobWidgetsConfig.cmake (found version "5.34.0") 
builder for ‘/nix/store/fb1hsshjvcwq56nfkdv04ffcxjj9in9v-ktorrent-5.0.1.drv’ failed with exit code 1                                 
cannot build derivation ‘/nix/store/c53s5d0vcfbydx6df4dhx0cmbiv0ha8h-system-path.drv’: 1 dependencies couldn't be built              
cannot build derivation ‘/nix/store/jbiqdv3yd9m38jnwhvqkd2g2pkh83apv-nixos-system-subi-17.09pre110094.1add3519df.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jbiqdv3yd9m38jnwhvqkd2g2pkh83apv-nixos-system-subi-17.09pre110094.1add3519df.drv’ failed 
```

### Steps to reproduce

Running   nixos-rebuild boot --upgrade

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.09pre109180.0d4431cfe9 (Hummingbird)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.09pre110094.1add3519df"

* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)

build-use-sandbox = false

**Comment by FRidh** [comment]
fixed in 8f5cf685ad7b8a79b2033e99604898a9fa1fe819

**Comment by sjau** [comment]
still broken

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /nix/store/3k978nnp7ppjim34di40vwz5f95rsxhw-gcc-wrapper-5.4.0/bin/gcc
-- Check for working C compiler: /nix/store/3k978nnp7ppjim34di40vwz5f95rsxhw-gcc-wrapper-5.4.0/bin/gcc -- works
-- Detecting C compile features
-- Check for working CXX compiler: /nix/store/3k978nnp7ppjim34di40vwz5f95rsxhw-gcc-wrapper-5.4.0/bin/g++
-- Detecting CXX compiler ABI info
-- Detecting CXX compile features
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT - Success
-- Found PythonInterp: /nix/store/frnm6ahmm6kzlh7sqrn09hdkkfyy9q39-python-2.7.13/bin/python (found version "2.7.13") 
5.34.0") 
0") 
ersion "5.34.0") 
-- Found KF5Notifications: /nix/store/r4zqnffl0zyqabqm6a47nc8xa0ns6avw-knotifications-5.34.0-dev/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.34.0") 
figConfig.cmake (found version "5.34.0") 
n "5.34.0") 
ersion "5.34.0") 
g.cmake (found version "5.34.0") 
(found version "5.34.0") 
-- Found KF5Kross: /nix/store/m8lh5mq2d53358cria6aagdfi131ps3p-kross-5.34.0-dev/lib/cmake/KF5Kross/KF5KrossConfig.cmake (found versio-- Found KF5KCMUtils: /nix/store/l59v0441b28nn1875wvikiv51wmmx85m-kcmutils-5.34.0-dev/lib/cmake/KF5KCMUtils/KF5KCMUtilsConfig.cmake (-- Found LibGMP: /nix/store/qsiqw59f3k9d8csckmb0q4ip1pkk0bbz-gmp-6.1.2-dev/include (found suitable version "6.1.2", minimum required CMake Error at /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibGcrypt (missing: LibGcrypt_INCLUDE_DIRS
Call Stack (most recent call first):
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /nix/store/0znc26msy9nvybwnd8x3yaj661i7l4w6-libktorrent-2.0.1-dev/lib/cmake/LibKTorrent/FindLibGcrypt.cmake:108 (find_package_handle_standard_args)
  /nix/store/5dh82kd6qppsap7b12llcbp6w4d2i6a9-cmake-3.8.2/share/cmake-3.8/Modules/CMakeFindDependencyMacro.cmake:55 (find_package)
  /nix/store/0znc26msy9nvybwnd8x3yaj661i7l4w6-libktorrent-2.0.1-dev/lib/cmake/LibKTorrent/LibKTorrentConfig.cmake:82 (find_dependency)
  CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/nix-build-ktorrent-5.0.1.drv-0/ktorrent-5.0.1/build/CMakeFiles/CMakeOutput.log".
builder for ‘/nix/store/kkzvsvgnhys5kiwbcr19xybq9r1a2piz-ktorrent-5.0.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/jxvfx7lh0lf2s1vjxsvagm6h57f77bvf-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/lw1g40ah99fwva0wnkl5jqlcs54bfm12-nixos-system-subi-17.09pre110181.c5e314dabe.drv’: 1 dependencies couldn't be built
```


17.09pre110094.1add3519df (Hummingbird)
nix-env (Nix) 1.11.11
"17.09pre110181.c5e314dabe"
build-use-sandbox = false

**Comment by FRidh** [comment]
For crying out loud, how many times do you need to be explained how channels and revisions work. Neither of these fixes have occurred yet at the revisions you refer to. Stop wasting my time.
