### ISSUE TITLE
Build failure: Lokinet (23.11)

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#270515]
### Steps To Reproduce

1. Use NixOS 23.11
2. services.lokinet.enable = true;

### Build log

I apologize in advance. I'm not sure what to make of this, but I'm trying to give useful information.

```
# nix flake update /etc/nixos/ && nixos-rebuild switch -L
building the system configuration...
lokinet> unpacking sources
lokinet> unpacking source archive /nix/store/8cmahbj2i3a22c5n6pw024yk78381xwp-source
tor-browser> unpacking sources
tor-browser> unpacking source archive /nix/store/qgm844sgnsc4rwgfb36jdbbzaa19kxfh-tor-browser-linux-x86_64-13.0.5.tar.xz
lokinet> source root is source
lokinet> patching sources
lokinet> updateAutotoolsGnuConfigScriptsPhase
lokinet> configuring
lokinet> fixing cmake files...
lokinet> cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/share/doc/lokinet -DCMAKE_INSTALL_INFODIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/include -DCMAKE_INSTALL_SBINDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/ranlib -DCMAKE_AR=/nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/xf0lfqc8nnibcx0dwvn6krw9ayil0i97-lokinet-0.9.11 -DGIT_VERSION=v0.9.11 -DWITH_BOOTSTRAP=OFF -DWITH_SETCAP=OFF
lokinet> -- The C compiler identification is GNU 12.3.0
lokinet> -- The CXX compiler identification is GNU 12.3.0
lokinet> -- Detecting C compiler ABI info
lokinet> -- Detecting C compiler ABI info - done
lokinet> -- Check for working C compiler: /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/gcc - skipped
lokinet> -- Detecting C compile features
lokinet> -- Detecting C compile features - done
lokinet> -- Detecting CXX compiler ABI info
lokinet> -- Detecting CXX compiler ABI info - done
lokinet> -- Check for working CXX compiler: /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/g++ - skipped
lokinet> -- Detecting CXX compile features
lokinet> -- Detecting CXX compile features - done
lokinet> -- LTO enabled
lokinet> -- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
lokinet> -- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
lokinet> -- Have working 64bit atomics
lokinet> -- Performing Test was_compiled
lokinet> -- Performing Test was_compiled - Success
lokinet> -- we have std::optional
lokinet> -- Performing Test filesystem_compiled
lokinet> -- Performing Test filesystem_compiled - Success
lokinet> -- No extra link flag needed for std::filesystem
lokinet> -- we have std::filesystem
lokinet> -- Found PkgConfig: /nix/store/ljrkf0kwgckcy02kdlz8sjdnxb2pwjb4-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2")
lokinet> -- Checking for module 'libuv>=1.18.0'
lokinet> --   Found libuv, version 1.46.0
lokinet> -- Checking for module 'libsodium>=1.0.18'
lokinet> --   Found libsodium, version 1.0.18
lokinet> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
lokinet> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
lokinet> -- Found Threads: TRUE
lokinet> -- Checking for module 'libunbound'
lokinet> --   Found libunbound, version 1.18.0
lokinet> Package hogweed was not found in the pkg-config search path.
lokinet> Perhaps you should add the directory containing `hogweed.pc'
lokinet> to the PKG_CONFIG_PATH environment variable
lokinet> Package 'hogweed', required by 'libunbound', not found
lokinet> Package hogweed was not found in the pkg-config search path.
lokinet> Perhaps you should add the directory containing `hogweed.pc'
lokinet> to the PKG_CONFIG_PATH environment variable
lokinet> Package 'hogweed', required by 'libunbound', not found
lokinet> Package hogweed was not found in the pkg-config search path.
lokinet> Perhaps you should add the directory containing `hogweed.pc'
lokinet> to the PKG_CONFIG_PATH environment variable
lokinet> Package 'hogweed', required by 'libunbound', not found
lokinet> Package hogweed was not found in the pkg-config search path.
lokinet> Perhaps you should add the directory containing `hogweed.pc'
lokinet> to the PKG_CONFIG_PATH environment variable
lokinet> Package 'hogweed', required by 'libunbound', not found
lokinet> -- Checking for module 'libsystemd'
lokinet> --   Found libsystemd, version 254
lokinet> -- Could NOT find Git (missing: GIT_EXECUTABLE)
lokinet> -- Checking for module 'liboxenc>=1.0.4'
lokinet> --   No package 'liboxenc' found
lokinet> -- using oxenc submodule
lokinet> -- oxenc v1.0.6
lokinet> -- Checking for module 'liboxenmq>=1.2.14'
lokinet> --   No package 'liboxenmq' found
lokinet> -- using oxenmq submodule
lokinet> -- oxenmq v1.2.14
lokinet> -- using pre-existing oxenc::oxenc target
lokinet> -- Checking for module 'libzmq>=4.3'
lokinet> --   Found libzmq, version 4.3.5
lokinet> -- Checking for module 'nlohmann_json>=3.7.0'
lokinet> --   Found nlohmann_json, version 3.11.2
lokinet> -- Found system nlohmann_json 3.11.2
lokinet> -- Found fmt 9.1.0
lokinet> -- Found spdlog 1.12.0
lokinet> -- Stripping source root /build/source from log paths
lokinet> -- Looking for arpa/inet.h
lokinet> -- Looking for arpa/inet.h - found
lokinet> -- Looking for netinet/in.h
lokinet> -- Looking for netinet/in.h - found
lokinet> -- Looking for stddef.h
lokinet> -- Looking for stddef.h - found
lokinet> -- Looking for stdint.h
lokinet> -- Looking for stdint.h - found
lokinet> -- Looking for stdlib.h
lokinet> -- Looking for stdlib.h - found
lokinet> -- Looking for string.h
lokinet> -- Looking for string.h - found
lokinet> -- Looking for unistd.h
lokinet> -- Looking for unistd.h - found
lokinet> -- Looking for sys/endian.h
lokinet> -- Looking for sys/endian.h - not found
lokinet> -- Looking for endian.h
lokinet> -- Looking for endian.h - found
lokinet> -- Looking for byteswap.h
lokinet> -- Looking for byteswap.h - found
lokinet> -- Looking for sys/types.h
lokinet> -- Looking for sys/types.h - found
lokinet> -- Check size of ssize_t
lokinet> -- Check size of ssize_t - done
lokinet> -- Looking for be64toh
lokinet> -- Looking for be64toh - not found
lokinet> -- Looking for bswap_64
tor-browser> source root is tor-browser
tor-browser> setting SOURCE_DATE_EPOCH to timestamp 946684800 of file tor-browser/start-tor-browser.desktop
tor-browser> patching sources
tor-browser> updateAutotoolsGnuConfigScriptsPhase
lokinet> -- Looking for bswap_64 - found
lokinet> -- Checking for module 'jemalloc'
lokinet> --   No package 'jemalloc' found
tor-browser> configuring
lokinet> -- jemalloc not found, not linking to jemalloc
lokinet> -- Performing Test COMPILER_SUPPORTS_AVX2
tor-browser> no configure script, doing nothing
tor-browser> building
lokinet> -- Performing Test COMPILER_SUPPORTS_AVX2 - Success
lokinet> -- Performing Test COMPILER_SUPPORTS_FMA
lokinet> -- Performing Test COMPILER_SUPPORTS_FMA - Success
lokinet> -- Building libntrup with runtime AVX2/FMA support
lokinet> -- Could NOT find Git (missing: GIT_EXECUTABLE)
lokinet> -- Building with MAINNET fallback boostrap path "/build/source/contrib/bootstrap/mainnet.signed"
lokinet> -- Building with TESTNET fallback boostrap path "/build/source/contrib/bootstrap/testnet.signed"
lokinet> -- Checking for module 'libcrypt'
lokinet> --   No package 'libcrypt' found
lokinet> -- Documentation generation disabled (doxygen not found)
lokinet> -- not building gui
lokinet> -- Configuring done (23.5s)
lokinet> CMake Error in external/oxen-mq/CMakeLists.txt:
lokinet>   Imported target "PkgConfig::libzmq" includes non-existent path
lokinet>     "/nix/store/j3rbg8r5fdgyk8sz6pl9zckczc5ia6a7-zeromq-4.3.5//nix/store/j3rbg8r5fdgyk8sz6pl9zckczc5ia6a7-zeromq-4.3.5/include"
lokinet>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
lokinet>   * The path was deleted, renamed, or moved to another location.
lokinet>   * An install or uninstall procedure did not complete successfully.
lokinet>   * The installation package was faulty and references files it does not
lokinet>   provide.
lokinet>
lokinet> -- Generating done (0.5s)
lokinet> CMake Warning:
lokinet>   Manually-specified variables were not used by the project:
lokinet>     BUILD_TESTING
lokinet>     CMAKE_EXPORT_NO_PACKAGE_REGISTRY
lokinet>     CMAKE_POLICY_DEFAULT_CMP0025
lokinet>
lokinet> CMake Generate step failed.  Build files cannot be regenerated correctly.
error: builder for '/nix/store/jb6jfcicm19ynsc9af9v238yca216a8z-lokinet-0.9.11.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/wyr2fhf8y0m2gb87dg9skanshy3v5ayx-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5sr8cs9p56fpk88r3mq1167z8kpdn3nx-unit-lokinet.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xyhp38fhly36cgdy9prj8v3dkx39nb7a-nixos-system-spooks-23.11.20231127.070b5cf.drv' failed to build
#
```

### Additional context
I'm using flakes, and I'm able to successfully build Lokinet using this commit, from 2 weeks ago.
"github:NixOS/nixpkgs/bf744fe90419885eefced41b3e5ae442d732712d"

### Notify maintainers

@tobim @fabaff @r-ryantm @wyndon  @Mindavi 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.1, NixOS, 23.11 (Tapir), 23.11.20231125.21af6ad`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11, nixos-hardware, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by wyndon** [comment]
It's already fixed with https://github.com/NixOS/nixpkgs/pull/269920, but it hasn't been merged in unstable/23.11 yet. You can fix it by doing the following in the meantime :

In your flake.nix, add this input :
```nix
inputs = {
  nixpkgs-269920.url = "github:NixOS/nixpkgs/pull/269920/head";
};
```

In the file where you have the lokinet service enabled, add the following `package` option :
```nix
services.lokinet = {
  enable = true;
  package = inputs.nixpkgs-269920.legacyPackages.${pkgs.system}.lokinet
};
```

**Comment by Sepero** [comment]
Thank you for your excellent answer with extremely helpful instructions. NixOS may not have the all the documentation, but it's people are super knowledgeable and kind. Thanks

**Comment by Sepero** [comment]
Lokinet is still failing to build for 23.11 Stable and Unstable for me. The linked issue appears to be closed. Has this fix not been merged into a channel yet?

**Comment by Mindavi** [comment]
See https://nixpk.gs/pr-tracker.html?pr=269965, it's still in staging

**Comment by Sepero** [comment]
This is a first for me to see a new "stable" repository released with known broken packages. Maybe it happens in other distros, and I've just never yet been aware of it? Thankfully fixing it in NixOS isn't too difficult. I very much appreciate your help on this.
