### ISSUE TITLE
esphome: Component not found: font.

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#272334]
### Describe the bug
compilation fails with minimal example (see below). used to work in nixos 23.05, but is now broken on nixos 23.11 and master.
```
INFO ESPHome 2023.11.6
INFO Reading configuration /var/lib/esphome/test.yaml...
Failed config

font: [source /var/lib/esphome/test.yaml:36]
  
  Component not found: font.
  - file: weise-pixel.ttf
    id: digit_font
    size: 8
```

I tried patching the pillow version: https://github.com/NixOS/nixpkgs/compare/master...Stunkymonkey:nixpkgs:esphome-patch-pillow-10.1.0 But sadly the same result.

With the official docker image the compilation works.

### Steps To Reproduce
1. copy minimal example
2. compile
3. see error

### Expected behavior
compilation works.

### Screenshots
![Screenshot-2023-12-05_204039](https://github.com/NixOS/nixpkgs/assets/1315818/6a17ad09-6f7f-409c-b920-76f41dd1d735)

### Additional context
<details><summary>Minimal example</summary>

```
esphome:
  name: test
  friendly_name: test

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NGYeKcZvhRMUV6dY0UrI+Kk0is0Si6MteS/awYxXk+Q="

ota:
  password: "940c7ad78caf2dc2257030fbfc1eef43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# matrix
time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"

spi:
  clk_pin: D1
  mosi_pin: D3

font:
  - file: "weise-pixel.ttf"
    id: digit_font
    size: 8

display:
  - platform: max7219digit
    id: led_matrix
    scroll_enable: False
    cs_pin: D2
    num_chips: 4
    intensity: 0
    lambda: |-
      it.strftime(0, 1, id(digit_font), "%H:%M", id(sntp_time).now());
```

</details>

### Notify maintainers
@globin @hexa @oddlama

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 24.05 (Uakari), 24.05.20231204.c542e2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/store/f8lzbrj0yck7pa5yghwyyg9a1yl508qm-i6dl9wwr6hs6jb09lqjav5j663mm74ra-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Stunkymonkey** [comment]
the problem was the exact pillow version was not correct. by updating the package it will be fixed. see pr #277425

**Comment by mweinelt** [comment]
The example still doesn't work for me on this PR.

**Comment by Stunkymonkey** [comment]
Is the "font" file missing? If yes better use gfonts. sorry for that.

<details><summary>better Minimal example</summary>

```
esphome:
  name: test
  friendly_name: test

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NGYeKcZvhRMUV6dY0UrI+Kk0is0Si6MteS/awYxXk+Q="

ota:
  password: "940c7ad78caf2dc2257030fbfc1eef43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# matrix
time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"

spi:
  clk_pin: D1
  mosi_pin: D3

font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: digit_font
    size: 8

display:
  - platform: max7219digit
    id: led_matrix
    scroll_enable: False
    cs_pin: D2
    num_chips: 4
    intensity: 0
    lambda: |-
      it.strftime(0, 1, id(digit_font), "%H:%M", id(sntp_time).now());
```
</details>

**Comment by Stunkymonkey** [comment]
is fixed now.

**Comment by goatchurchprime** [comment]
Still not working for me, no matter what.

I've checked everything I can, including the pillow version 10.2.0, which is correct in latest unstable.  I am not able to isolate the problem.  The error is too unhelpful in not saying why the font component is broken.  

I've been reduced to doing the following (because I have no alternative):

pip-shell.nix:
```nix
{ pkgs ? import <nixpkgs> {} }:
(pkgs.buildFHSUserEnv {
  name = "pipzone";
  targetPkgs = pkgs: (with pkgs; [
    python311
    python311Packages.pip
    python311Packages.virtualenv
  ]);
  runScript = "bash";
}).env
```

Then

> export NIXPKGS_ALLOW_UNFREE=1
> nix-shell pip-shell.nix
> python -m venv venv_esphome    # [ONCE]
> source venv_esphome/bin/activate
> pip install esphome    # [ONCE]

try esphome compiling something with a font to get:

* Please install the pillow python package to use this feature. (pip install "pillow==10.2.0").

> pip install "pillow==10.2.0" # [ONCE]

**Comment by pwntester** [comment]
Same problem here. Im using Esphome CLI on a mac with the following yaml:

```
esphome:
  name: esp32-s3-box-3
  friendly_name: ESP32 S3 Box 3
  name_add_mac_suffix: false

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: TEST
    password: !secret ap_password 

captive_portal:
```

And Im getting:

```
Failed config

image: [source .esphome/packages/c46f54c1/wake-word-voice-assistant/esp32-s3-box-3.yaml:415]

  Component not found: image.

...

display.ili9xxx: [source .esphome/packages/c46f54c1/wake-word-voice-assistant/esp32-s3-box-3.yaml:513]

  Please install the pillow python package to use this feature. (pip install "pillow==10.2.0").

...
```

I have pillow 10.2.0 installed:

```
❯ pip list | grep pillow
pillow                   10.2.0
```

**Comment by pwntester** [comment]
@goatchurchprime did you find a workaround?

**Comment by mweinelt** [comment]
With the following bits of config I think I should be able to reproduce your issue, but I can't.

Using esphome 2024.2.0 from nixpkgs master.

```yaml
# wifi, captive_portal, logger, time, api, web_sever, ota included

esphome:
  name: esp32-s3-box-3
  friendly_name: ESP32 S3 Box 3
  name_add_mac_suffix: false

packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
```

[Full build log](https://gist.github.com/mweinelt/d623175a2ddb26b1b4b3254d512db579)

**Comment by pwntester** [comment]
Thanks for looking into it @mweinelt. Im using Version: 2024.2.2 from homebrew if that makes any difference

**Comment by pwntester** [comment]
Sorry my fault, but your pointer about python version got me to get the latest pypi version and that fixed the issue, so thanks!
