### ISSUE TITLE
install NixOS without internet connection

### ISSUE THREAD

**Issue by char16t** [NixOS/nixpkgs#27252]
## Issue description

I tried install NixOS from graphical iso image and minimal iso image. Both requires internet connection for downloading "acl" package with nix package manager, but I have no internet connection via WiFi. File /etc/nixos/configuration.nix in live CD is read-only. File /etc/network/interfaces is not exists.
I have no availability connect to internet via Ethernet cable.

### Steps to reproduce

1. Download graphiclal ISO image from nixos.org
2. Write ISO image to USB drive via `dd`
3. Boot from USB without internet connection
4. Prepare drive (/dev/sda10 for example)
5. Mount /dev/sda10 to /mnt
6. Generate config with `nixos-generate-config`
7. Add only one line to config: `boot.loader.grub.device = "/dev/sda";`
8.  Execute `nixos-install`
9. Get error: build of nixos-system-nixos-17.03.drv failed

![img_20170709_112429](https://user-images.githubusercontent.com/5310476/27992291-d97340c4-64a1-11e7-802a-541f334a692b.jpg)
![img_20170709_112410](https://user-images.githubusercontent.com/5310476/27992292-e8c90c16-64a1-11e7-8f60-f40345c2a7d0.jpg)

## Technical details

* System: 17.03.1482.1b57bf274a (Gorilla)
* Nix version: 1.11.11
* Nixpkgs version:  17.03.1482.1b57bf274a
* Sandboxing enabled: false

**Comment by 0xABAB** [comment]
A release test should also be added, which tests for this property.

**Comment by char16t** [comment]
After connecting and removing ethernet cable I can connect to WiFi (networks menu is shown).

But I still would like to be able install nixos without internet (if it need someone else).

**Comment by avnik** [comment]
Confirm, install media miss stuff for bootloader installation (grub/grub-efi).

**Comment by 0xABAB** [comment]
@char16t Please close this issue, since your immediate problem has been resolved and there is now an issue for improving the quality of the release such that this won't happen again.

**Comment by Meizikyn** [comment]
Rather than open a new issue, I would like to reopen this one.

As of Loris 19.09 this issue still persists.

**Comment by char16t** [comment]
Hi Nicholas,

I recommend you create new issue with link to this. You should provide your technical details in issue description.

**Comment by char16t** [comment]
@Meizikyn

**Comment by bernadinm** [comment]
I've just tested this on a new machine (Framework Laptop) running 21.04 and it doesn't work without an internet connection.

**Comment by nkichukov** [comment]
Same here, nixos-install fails with some unable to download DNS resolution failures for cache.nixos.org ... any workaround to this?

**Comment by jcleng** [comment]
> 



> Same here, nixos-install fails with some unable to download DNS resolution failures for cache.nixos.org ... any workaround to this?
> 
> Nixos 22.05.1460 here.

the same

**Comment by joserafaelterra** [comment]
@jcleng  @nkichukov 

Hi,

I solved the problem by following these steps:

- Disable Wired connection

- Enable Wi-fi and configure ip and dns manually

- Restart services network-interfaces.target and network-online.target

- Close and reopen the Calamares installer

**Comment by jcleng** [comment]
> @jcleng @nkichukov
> 
> Hi,
> 
> I solved the problem by following these steps:
> 
> * Disable Wired connection
> * Enable Wi-fi and configure ip and dns manually
> * Restart services network-interfaces.target and network-online.target
> * Close and reopen the Calamares installer

I think what I need is no network for installation,offline install, rather than network for installation

**Comment by pete3n** [comment]
If you want to install NixOS from an ISO completely offline, I created [this repo](https://github.com/pete3n/nix-offline-iso) to build an ISO with the the graphical installer that works offline.
