### ISSUE TITLE
Build failure: yubioath-flutter

### ISSUE THREAD

**Issue by panchoh** [NixOS/nixpkgs#276412]
### Steps To Reproduce

1. build *yubioath-flutter*
`nix build nixpkgs#yubioath-flutter`

### Build log

```
❯ nix log '/nix/store/zm76i6m184h5fs9yaihjxinqym3f6vkn-yubioath-flutter-6.2.0-dart-deps-list.json.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/8vm4mcm7j05jpaywqs259vgx781jxzky-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
'/nix/store/yhkl29rlrxvizgzw7382zzpgrvb58f7q-yubioath-flutter-6.2.0-dart-deps/pubspec/pubspec.lock' -> './pubspec.lock'
Resolving dependencies...
! intl 0.18.1 (overridden in ./pubspec_overrides.yaml)
Got dependencies!
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
The Flutter SDK is not available.
```

### Additional context

The flutter derivation has been [drastically updated recently](https://github.com/NixOS/nixpkgs/pull/262789).
I think it may be related.  I see no recent changes in the `yubioath-flutter` module.

### Notify maintainers

@lukegb @hacker1024 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.8, NixOS, 24.05 (Uakari), 24.05.20231222.6df37dc`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `not found`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by v411e** [comment]
Same here with localsend

```
> nix log '/nix/store/72bjd7x50y8f95hsvjhnbphjk5xgcykd-localsend-1.12.0-dart-deps-list.json.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/xmirdp6khwp3caxkf1wg6pp5l2fj5rx0-source
source root is source/app
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
Resolving dependencies...
! permission_handler_windows 0.1.2 from git https://github.com/localsend/permission_handler_windows_noop.git at fc09b7 (overridden)
Got dependencies!
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
The Flutter SDK is not available.
```

**Comment by mkg20001** [comment]
Should be fixed with #276414

**Comment by YaroKasear** [comment]
This is still failing for me.

```
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.7-zen1, NixOS, 24.05 (Uakari), 24.05.20231219.54aac08`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(This is actually not accurate, I'm using flakes that source from nixos-unstable.)

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/8vm4mcm7j05jpaywqs259vgx781jxzky-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
'/nix/store/yhkl29rlrxvizgzw7382zzpgrvb58f7q-yubioath-flutter-6.2.0-dart-deps/pubspec/pubspec.lock' -> './pubspec.lock'
Resolving dependencies...
! intl 0.18.1 (overridden in ./pubspec_overrides.yaml)
Got dependencies!
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
The Flutter SDK is not available.
```

**Comment by mkg20001** [comment]
I've tried building yubioath-flutter on d2e4e09de4b8a27228295951c3847cfc8f06fd15 (master) and it just pulled from cache

You're using sandbox so I suspect that's not the issue.

nixos-unstable is not directly master, try with master and see if the issue still persists.

Check https://nixpk.gs/pr-tracker.html?pr=276414, nixos-unstable doesn't yet have the fix

**Comment by panchoh** [comment]
[...[
> nixos-unstable is not directly master, try with master and see if the issue still persists.
> 
> Check https://nixpk.gs/pr-tracker.html?pr=276414, nixos-unstable doesn't yet have the fix
The change finally percolated to `nixos-unstable`, yay!

Build working again, no issues.
