### ISSUE TITLE
Cannot build gnustep-make on osx 10.12

### ISSUE THREAD

**Issue by pvmart** [NixOS/nixpkgs#27946]
## Issue description
```
configure flags: --prefix=/nix/store/id9ncgn105cp1icxwy4rbdl6jqilpy88-gnustep-make-2.6.8 --with-layout=fhs-system --disable-install-p --with-config-file=/nix/store/id9ncgn105cp1icxwy4rbdl6jqilpy88-gnustep-make-2.6.8/etc/GNUstep/GNUstep.conf
checking build system type... i386-apple-darwin16.7.0
checking host system type... i386-apple-darwin16.7.0
checking target system type... i386-apple-darwin16.7.0
checking for library combo... apple-apple-apple
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/var/folders/db/8jrwbcyx73375g6d3pzzzlg40000z7/T/nix-build-gnustep-make-2.6.8.drv-1/gnustep-make-2.6.8':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
builder for ‘/nix/store/37jilqd8jyn2sjj1wmnc5nhjz3ds5xcj-gnustep-make-2.6.8.drv’ failed with exit code 1
```

### Steps to reproduce
nix-env -f '<nixpkgs>' -i gnustep-make

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.13
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.09pre-git"
* Sandboxing enabled: (run `grep build-use-sandbox /etc/nix/nix.conf`)
n/a

**Comment by matthewbauer** [comment]
I've had this same issue previously but can't reproduce it right now. Hydra has the same issue though:

https://hydra.nixos.org/build/57646187/nixlog/1

Here's the diff that caused it to fail:

https://hydra.nixos.org/api/scmdiff?rev2=feeed410ffff620897f61a2beead9415c2e38ef1&rev1=b2608b891062dcc95e50f00c304b297a727adf97&branch=&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&type=git

Maybe it is somehow related to changes in stdenv and cross compilation.
/cc @Ericson2314 maybe?

**Comment by matthewbauer** [comment]
I've had this same issue previously but can't reproduce it right now. Hydra has the same issue though:

https://hydra.nixos.org/build/57646187/nixlog/1

Here's the diff that caused it to fail:

https://hydra.nixos.org/api/scmdiff?rev2=feeed410ffff620897f61a2beead9415c2e38ef1&rev1=b2608b891062dcc95e50f00c304b297a727adf97&branch=&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&type=git

Maybe it is somehow related to changes in stdenv and cross compilation.
/cc @Ericson2314 maybe?

**Comment by adelbertc** [comment]
Running into same issue trying to install `ripgrep`, `stack`, and probably other Haskell packages.

**Comment by matthewbauer** [comment]
Yeah Haskell shouldn't depend on gnustep. Here's the override causing it:

https://github.com/NixOS/nixpkgs/blob/4f80406fdd762a1244c7952a04179f32ad6b451c/pkgs/development/haskell-modules/configuration-nix.nix#L124-L133

**Comment by matthewbauer** [comment]
So the configure script is trying to run this conftest program:

```
#include <stdio.h>
int
main ()
{
FILE *f = fopen ("conftest.out", "w");
 return ferror (f) || fclose (f) != 0;

  ;
  return 0;
}
```

Output from it I get is:

```
[nix-shell:/tmp/gnustep/gnustep-make-2.6.8]$ ./conftest
Killed: 9
```

Maybe related to https://github.com/NixOS/nixpkgs/pull/28050#issuecomment-321359222?

/cc @LnL7

**Comment by LnL7** [comment]
Looks similar, is the LC_LOAD_DYLINKER valid? That should be fixed in staging https://github.com/NixOS/nixpkgs/commit/bf8c1251708f013ecbcf3a1c6770a175e9161170.

**Comment by matthewbauer** [comment]
Yep

```
Load command 7
          cmd LC_LOAD_DYLINKER
      cmdsize 40
         name /usr/lib/dyld/usr/lib/dyld (offset 12)
```

**Comment by LnL7** [comment]
Ok, great! I was going to look into this today, but then this will be fixed with the next staging merge.
I'll keep an eye on https://hydra.nixos.org/eval/1382682

**Comment by pvmart** [comment]
Fixed. Thanks.

**Comment by ivan-m** [comment]
This fix still doesn't seem to be in the nixpkgs-unstable channel :/

**Comment by mjhoy** [comment]
@ivan-m it is fixed for me (10.12), is there a test i can run? nix downloaded from the binary cache, and i also tried to configure it manually in nix-shell which worked.

**Comment by ivan-m** [comment]
@mjhoy the [nixpkgs-unstable channel](https://github.com/NixOS/nixpkgs-channels/commits/nixpkgs-unstable) doesn't seem to have been updated for 9 days now, and the solution in bf8c125 [doesn't seem to be there](https://github.com/NixOS/nixpkgs-channels/blob/nixpkgs-unstable/pkgs/build-support/cc-wrapper/default.nix#L181) (and also isn't there if I view that file in the channel unpacked locally).

**Comment by lancelet** [comment]
nixpkgs-unstable now hasn't been updated in 17 days. Is there some guidance on the process for updating that channel, so we can help to get this fix in?

**Comment by matthewbauer** [comment]
We need a new nixStable release:

NixOS/nix#1526
