### ISSUE TITLE
qutebrowser broken on nixos-unstable

### ISSUE THREAD

**Issue by NickHu** [NixOS/nixpkgs#28214]
```
 ❯ qutebrowser --backend webengine                                                                          [23:55:13]
Cannot mix incompatible Qt library (version 0x50900) with this library (version 0x50901)
[1]    6745 abort      qutebrowser --backend webengine
```

## Technical details

* System: 17.09pre112691.abdb58e407 (Hummingbird)
* Nix version: nix-env (Nix) 1.11.13
* Nixpkgs version: 17.09pre112691.abdb58e407
* Sandboxing enabled: yes

**Comment by jpotier** [comment]
Confirmed here. Same message.

Any way around this?

**Comment by NickHu** [comment]
Seems like this is fixed in the latest unstable. Can anyone else confirm?

**Comment by jpotier** [comment]
Installing the version from nixpkgs-unstable-small did not fix the problem, unfortunately.

**Comment by NickHu** [comment]
Could you try just upgrading your system?

**Comment by jpotier** [comment]
Well, my system is on stable. My user environment is using `nixpkgs-unstable-small`. I guess I'm gonna have to wait.

**Comment by elitak** [comment]
I've been getting the same issue for the past week or so, on the master branch, running the virtualbox package's VirtualBox binary. The QT packages are 5.9.1 now, updated from 5.9.0, but I'm failing to see how exactly the latter are interfering with the former. Are the binaries in these packages in need of wrappers to pin down the QT environment?

**Comment by jpotier** [comment]
It is fixed for me on nixpkgs "17.09pre113138.96457d26dd".

**Comment by fpletz** [comment]
Yeah, works on on master. Thanks!
