### ISSUE TITLE
Opening luks devices fails when all have keyfiles set

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#29142]
## Issue description

Opening a luks device with a keyfile via fileSystems.*.encrypted.enable fails at boot (and the corresponding systemd task hangs) when no non-keyfile luks devices are configured, as cryptsetup is missing from the initrd.

It seems that cryptsetup is only added to the initrd when boot.initrd.luks.devices has entries.

https://github.com/NixOS/nixpkgs/blob/6b5150d29dada2f8366e0e1c1220dd8736f51aea/nixos/modules/system/boot/luksroot.nix#L420

But when fileSystems.*.encrypted.keyFile is set, the device is unlocked "manually".

https://github.com/NixOS/nixpkgs/blob/75b3113a4dc90cf1565c167ee510f6f892405889/nixos/modules/tasks/encrypted-devices.nix#L65-L67

### Steps to reproduce

Add a fileSystems entry with encrypted.keyFile set, and no other luks devices. E.g. something like (not actually tested)

```
fileSystems."/foo" = {
  device = "/dev/foo";
  fsType = "ext4";
  encrypted.enable = true;
  encrypted.blkDev = "/dev/bar";
  encrypted.label = "luks";
  encrypted.keyFile = "/keyfile";
};
```

## Technical details

* System: 17.03.1814.46fc14b6b2 (Gorilla)
* Nix version: nix-env (Nix) 1.11.14
* Nixpkgs version: "17.03.1814.46fc14b6b2"
* Sandboxing enabled: no

**Comment by Moredread** [comment]
I'm working on a PR, but am open for help :)

**Comment by fpletz** [comment]
A PR would be great! We should fix this for 17.09. If you need help or are unsure how to fix this, please ping me.

**Comment by bachp** [comment]
I'm still having issues on current master that my encrypted device is not mounting at boot. I will do some more investigation this week.

**Comment by bachp** [comment]
The external encrypted disk is a USB disk and it seems it get detected to late in the process so it is not available when `cryptsetup` runs.

I think in the case where just an additional disk should be mounted encrypted, [`systemd-cryptsetup-generator`](https://www.freedesktop.org/software/systemd/man/systemd-cryptsetup-generator.html) might be useful. I'm currently looking into it.

**Comment by bachp** [comment]
I added `systemd.generator-packages = [ pkgs.systemd-cryptsetup-generator ];` and then manually added the file `/etc/crytptab` and now everything works.

I will try to rewrite the encrypted-filesystem module to use [`systemd-cryptsetup-generator`](https://www.freedesktop.org/software/systemd/man/systemd-cryptsetup-generator.html). With an `/etc/crypttab` for non root devices. I think it should even work for for encrypted rootfs if use the kernel 
 parameters are used.

@Moredread I think you have some more experience. Does this sound reasonable from your point of view?

**Comment by Moredread** [comment]
@bachp I'm actually quite new to NixOS and I guess it's mainly a question whether it fits the NixOS style. At the moment it doesn't need external dependencies, and I'm not sure, if modules should strive for that. On the other hand I personally think that systemd-cryptsetup-generator seems to fit the usecase. Do you think it can replicate everything that the current module can do?

**Comment by bachp** [comment]
I have a PoC that replaces the current manual command with a crypttab setup. It works for my case where I mount a disk late. I need to check if it also works for disks earlier in the boot, not the root disk which I think is special.

I will push my WIP branch later.

**Comment by Moredread** [comment]
@bachp you might want to have a look at PR #29269 which adds a test that might be interesting for you.

**Comment by fpletz** [comment]
Fixed by #29344.

**Comment by Moredread** [comment]
I still fails sometimes for a luks on lvm setup.

When I boot the machine without automatic luks unlocking, the corresponding lvm vg is not activated sometimes. I guess that causes the issue with unlocking the device during boot.
