### ISSUE TITLE
[nixos] Blank screen and unresponsive laptop after resume; i5-1145G7/TigerLake-LP GT2

### ISSUE THREAD

**Issue by philipwilk** [NixOS/nixpkgs#291588]
### Describe the bug
When I do a ``systemctl suspend`` on my laptop, the system appears to successfully suspend, but when I try to resume it, the screen stays blank, my speaker/mic mute lights turn on on my keyboard and the machine becomes completely unresponsive.
This is not an issue on other distros - I have booted into the latest fedora and ubuntu live ISOs and they are able to suspend and resume completely fine on this laptop.
This is also not an issue on my desktop computer (also on nixos).

 
### Steps To Reproduce
1. ``systemctl suspend``
2. press power button to wake system after is has suspended / lift lid.
3. blank screen/unresponsive and must hard reboot.

### Expected behavior
It should be able to resume normally as on other distros.

### Screenshots
blank screen

### Additional context
<details> <summary> Journalctl after initiating a suspend </summary>

```
Feb 26 14:43:24 nixowos-laptop systemd-logind[1169]: The system will suspend now!
Feb 26 14:43:24 nixowos-laptop polkitd[1867]: Unregistered Authentication Agent for unix-process:10889:69458 (system bus name :1.74, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_GB.UTF>
Feb 26 14:43:24 nixowos-laptop dbus-daemon[992]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.7' (uid=0 pid=12>
Feb 26 14:43:24 nixowos-laptop systemd[1]: Starting Network Manager Script Dispatcher Service...
Feb 26 14:43:24 nixowos-laptop dbus-daemon[992]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Feb 26 14:43:24 nixowos-laptop systemd[1]: Started Network Manager Script Dispatcher Service.
Feb 26 14:43:24 nixowos-laptop kernel: wlp0s20f3: deauthenticating from 84:23:88:38:71:ac by local choice (Reason: 3=DEAUTH_LEAVING)
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: wlp0s20f3: CTRL-EVENT-DISCONNECTED bssid=84:23:88:38:71:ac reason=3 locally_generated=1
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: wlp0s20f3: CTRL-EVENT-DSCP-POLICY clear_all
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopped target Host and Network Name Lookups.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopping Host and Network Name Lookups...
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopped target User and Group Name Lookups.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopping User and Group Name Lookups...
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopping Name Service Cache Daemon (nsncd)...
Feb 26 14:43:24 nixowos-laptop systemd[1]: nscd.service: Deactivated successfully.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Stopped Name Service Cache Daemon (nsncd).
Feb 26 14:43:24 nixowos-laptop systemd[1]: nscd.service: Consumed 299ms CPU time, 3.4M memory peak, 0B memory swap peak, received 242B IP traffic, sent 154B IP traffic.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Starting Name Service Cache Daemon (nsncd)...
Feb 26 14:43:24 nixowos-laptop nsncd[10994]: Feb 26 14:43:24.801 INFO started, config: Config { ignored_request_types: {}, worker_count: 8, handoff_timeout: 3s }, path: "/var/run/nscd/socket"
Feb 26 14:43:24 nixowos-laptop systemd[1]: Started Name Service Cache Daemon (nsncd).
Feb 26 14:43:24 nixowos-laptop systemd[1]: Reached target Host and Network Name Lookups.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Reached target User and Group Name Lookups.
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: p2p-dev-wlp0s20: CTRL-EVENT-DSCP-POLICY clear_all
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: p2p-dev-wlp0s20: CTRL-EVENT-DSCP-POLICY clear_all
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: nl80211: deinit ifname=p2p-dev-wlp0s20 disabled_11b_rates=0
Feb 26 14:43:24 nixowos-laptop systemd[1]: Starting Pre-Sleep Actions...
Feb 26 14:43:24 nixowos-laptop systemd[1]: pre-sleep.service: Deactivated successfully.
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: wlp0s20f3: CTRL-EVENT-DSCP-POLICY clear_all
Feb 26 14:43:24 nixowos-laptop systemd[1]: Finished Pre-Sleep Actions.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Reached target Sleep.
Feb 26 14:43:24 nixowos-laptop systemd[1]: Starting System Suspend...
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: wlp0s20f3: CTRL-EVENT-DSCP-POLICY clear_all
Feb 26 14:43:24 nixowos-laptop wpa_supplicant[1503]: nl80211: deinit ifname=wlp0s20f3 disabled_11b_rates=0
```
</details>

I can't get any logs of what is happening when it is resuming, since the resume appears to halt before logging starts. ``journalctl -b-1`` shows me up to the above, while ``journalctl -b`` only shows the current clean boot.

[Hardware probe of the laptop that is having this issue](https://linux-hardware.org/?probe=848c852446)

[The nixos hardware config for the laptop](https://github.com/philipwilk/nixconf/blob/main/workstations/infra/nixowos-laptop/hardware-configuration.nix)

Only notable thing I can think of I suppose is that I have encrypted root and swap I guess?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.5, NixOS, 24.05 (Uakari), 24.05.20240221.0e74ca9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/bjjfp9f2342bim734yyy498gvwxi301i-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Wiesel871** [comment]
I am experiencing the same issue and have found similiar reports dating back to 2018 so I doubt this is going to be resolved

**Comment by philipwilk** [comment]
I'm hoping it's a i915 issue and that the new intel xe driver fixes it but I don't have my hopes up.

**Comment by woojiq** [comment]
I had this problem after updating my nixpkgs input from about 28.02.24 to 14.03.24.

**Comment by woojiq** [comment]
I was able to get a dmesg after the resume failed. This is not related to Nvidia because I was able to reproduce the same without nvidia drivers.

<details>
  <summary>dmesg</summary>
<pre>
[  560.650004] ath10k_pci 0000:3b:00.0: wmi service ready event not received
[  560.707978] ath10k_pci 0000:3b:00.0: Could not init core: -110
[  560.707983] ------------[ cut here ]------------
[  560.707983] Hardware became unavailable upon resume. This could be a software issue prior to suspend or a hardware issue.
[  560.708008] WARNING: CPU: 0 PID: 3692 at net/mac80211/util.c:2593 ieee80211_reconfig+0xa1/0x1510 [mac80211]
[  560.708078] Modules linked in: snd_seq_dummy snd_hrtimer snd_seq snd_seq_device rfcomm xfrm_interface xfrm6_tunnel tunnel4 tunnel6 xfrm_user xfrm_algo twofish_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic blowfish_generic blowfish_x86_64 blowfish_common cast5_avx_x86_64 cast5_generic cast_common des3_ede_x86_64 des_generic libdes cbc camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 camellia_x86_64 xcbc md4 ccm snd_hda_codec_hdmi snd_ctl_led snd_hda_codec_realtek snd_hda_codec_generic xt_CHECKSUM xt_MASQUERADE ipt_REJECT nf_reject_ipv4 nft_chain_nat nf_nat af_packet cmac algif_hash algif_skcipher af_alg bnep snd_sof_pci_intel_cnl snd_sof_intel_hda_common snd_soc_hdac_hda soundwire_intel snd_sof_intel_hda_mlink soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp msr snd_sof snd_sof_utils soundwire_generic_allocation hid_multitouch soundwire_bus hid_generic snd_soc_skl joydev snd_soc_sst_ipc
[  560.708112]  mousedev nouveau snd_soc_sst_dsp ath10k_pci snd_hda_ext_core snd_soc_acpi_intel_match intel_uncore_frequency intel_uncore_frequency_common snd_soc_acpi ath10k_core i915 intel_tcc_cooling snd_soc_core x86_pkg_temp_thermal intel_powerclamp coretemp cmdlinepart crc32_pclmul polyval_clmulni polyval_generic snd_compress gf128mul spi_nor ath ghash_clmulni_intel ac97_bus mei_hdcp mei_pxp snd_pcm_dmaengine intel_rapl_msr ee1004 sha512_ssse3 drm_gpuvm mtd dell_wmi sha512_generic dell_laptop mei_wdt iTCO_wdt mac80211 drm_exec snd_hda_intel sha256_ssse3 gpu_sched sha1_ssse3 intel_pmc_bxt snd_intel_dspcfg btusb drm_buddy drm_ttm_helper uvcvideo xt_conntrack aesni_intel ttm watchdog btrtl snd_intel_sdw_acpi crypto_simd ledtrig_audio btintel drm_display_helper nf_conntrack videobuf2_vmalloc snd_hda_codec cryptd dell_smbios btbcm uvc btmtk nf_defrag_ipv6 processor_thermal_device_pci_legacy dell_wmi_sysman cec dcdbas processor_thermal_device nf_defrag_ipv4 firmware_attributes_class dell_wmi_descriptor wmi_bmof
[  560.708150]  intel_wmi_thunderbolt mxm_wmi rapl ip6t_rpfilter snd_hda_core processor_thermal_wt_hint videobuf2_memops rc_core videobuf2_v4l2 processor_thermal_rfim processor_thermal_rapl cfg80211 bluetooth dell_smm_hwmon ipt_rpfilter snd_hwdep intel_cstate drm_kms_helper nls_iso8859_1 snd_pcm videodev intel_gtt nls_cp437 snd_timer agpgart intel_rapl_common vfat intel_lpss_pci i2c_hid_acpi intel_uncore psmouse fat ucsi_acpi xt_pkttype snd typec_ucsi i2c_algo_bit ecdh_generic mei_me videobuf2_common processor_thermal_wt_req i2c_i801 video i2c_hid rfkill processor_thermal_power_floor intel_lpss xt_LOG spi_intel_pci mc cdc_acm ecc libaes soundcore spi_intel i2c_smbus tpm_crb nf_log_syslog typec idma64 processor_thermal_mbox libarc4 intel_soc_dts_iosf mei thermal hid intel_pch_thermal virt_dma roles battery xt_tcpudp nft_compat int3403_thermal int340x_thermal_zone tiny_power_button evdev intel_pmc_core wmi dell_smo8800 pinctrl_cannonlake intel_vsec tpm_tis input_leds tpm_tis_core pmt_telemetry intel_hid led_class
[  560.708192]  int3400_thermal ac acpi_pad pmt_class acpi_thermal_rel sparse_keymap button mac_hid serio_raw nf_tables sch_fq_codel libcrc32c uinput ctr loop cpufreq_powersave tun tap macvlan bridge stp llc kvm_intel kvm drm irqbypass fuse efi_pstore backlight configfs nfnetlink efivarfs tpm rng_core dmi_sysfs ip_tables x_tables autofs4 ext4 crc32c_generic crc16 mbcache jbd2 ahci libahci rtsx_pci_sdmmc xhci_pci libata mmc_core xhci_pci_renesas nvme firmware_class atkbd libps2 vivaldi_fmap nvme_core xhci_hcd scsi_mod t10_pi crc32c_intel rtsx_pci crc64_rocksoft crc64 crc_t10dif crct10dif_generic crct10dif_pclmul crct10dif_common scsi_common i8042 rtc_cmos serio dm_mod dax
[  560.708229] CPU: 0 PID: 3692 Comm: kworker/u24:42 Tainted: G        W          6.8.1 #1-NixOS
[  560.708231] Hardware name: Dell Inc. XPS 15 9570/0D0T05, BIOS 1.30.0 12/15/2022
[  560.708233] Workqueue: events_unbound async_run_entry_fn
[  560.708237] RIP: 0010:ieee80211_reconfig+0xa1/0x1510 [mac80211]
[  560.708293] Code: 00 41 c6 86 85 05 00 00 00 4c 89 f7 e8 78 81 fb ff 41 89 c4 85 c0 0f 84 15 03 00 00 90 48 c7 c7 28 58 8d c1 e8 70 86 4c d3 90 <0f> 0b 90 90 eb 31 84 c0 0f 85 a1 01 00 00 c6 87 85 05 00 00 00 e8
[  560.708294] RSP: 0018:ffffa5bbc7a87cd8 EFLAGS: 00010282
[  560.708296] RAX: 0000000000000000 RBX: ffff88fcdc9e0538 RCX: 0000000000000027
[  560.708297] RDX: ffff89002c221848 RSI: 0000000000000001 RDI: ffff89002c221840
[  560.708298] RBP: ffff88fcdc9e03c0 R08: 0000000000000000 R09: 0a2e657573736920
[  560.708299] R10: 646e657073757320 R11: 6168206120726f20 R12: 00000000ffffff92
[  560.708300] R13: 0000000000000000 R14: ffff88fcdc9e0900 R15: ffff88fdaae5f388
[  560.708302] FS:  0000000000000000(0000) GS:ffff89002c200000(0000) knlGS:0000000000000000
[  560.708303] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  560.708304] CR2: 000000000049f030 CR3: 00000002d2420002 CR4: 00000000003706f0
[  560.708305] Call Trace:
[  560.708308]  <TASK>
[  560.708309]  ? ieee80211_reconfig+0xa1/0x1510 [mac80211]
[  560.708364]  ? __warn+0x81/0x130
[  560.708369]  ? ieee80211_reconfig+0xa1/0x1510 [mac80211]
[  560.708426]  ? report_bug+0x171/0x1a0
[  560.708430]  ? handle_bug+0x3d/0x80
[  560.708432]  ? exc_invalid_op+0x17/0x70
[  560.708434]  ? asm_exc_invalid_op+0x1a/0x20
[  560.708438]  ? ieee80211_reconfig+0xa1/0x1510 [mac80211]
[  560.708494]  ? ieee80211_reconfig+0xa0/0x1510 [mac80211]
[  560.708549]  ? schedule+0x32/0xd0
[  560.708552]  ? wq_worker_running+0xe/0x60
[  560.708555]  ? schedule_timeout+0x151/0x160
[  560.708558]  ? wait_for_completion+0x95/0x160
[  560.708562]  wiphy_resume+0x82/0x1b0 [cfg80211]
[  560.708613]  ? __pfx_wiphy_resume+0x10/0x10 [cfg80211]
[  560.708650]  dpm_run_callback+0x89/0x1b0
[  560.708654]  device_resume+0xb0/0x2d0
[  560.708656]  async_resume+0x1d/0x30
[  560.708658]  async_run_entry_fn+0x31/0x130
[  560.708660]  process_one_work+0x173/0x340
[  560.708663]  worker_thread+0x27b/0x3a0
[  560.708666]  ? __pfx_worker_thread+0x10/0x10
[  560.708668]  kthread+0xd4/0x100
[  560.708670]  ? __pfx_kthread+0x10/0x10
[  560.708671]  ret_from_fork+0x31/0x50
[  560.708674]  ? __pfx_kthread+0x10/0x10
[  560.708675]  ret_from_fork_asm+0x1b/0x30
[  560.708681]  </TASK>
[  560.708681] ---[ end trace 0000000000000000 ]---
[  560.708728] ------------[ cut here ]------------
[  560.708728] WARNING: CPU: 0 PID: 3692 at net/mac80211/driver-ops.c:41 drv_stop+0xf6/0x100 [mac80211]
[  560.708770] Modules linked in: snd_seq_dummy snd_hrtimer snd_seq snd_seq_device rfcomm xfrm_interface xfrm6_tunnel tunnel4 tunnel6 xfrm_user xfrm_algo twofish_generic twofish_avx_x86_64 twofish_x86_64_3way twofish_x86_64 twofish_common serpent_avx2 serpent_avx_x86_64 serpent_sse2_x86_64 serpent_generic blowfish_generic blowfish_x86_64 blowfish_common cast5_avx_x86_64 cast5_generic cast_common des3_ede_x86_64 des_generic libdes cbc camellia_generic camellia_aesni_avx2 camellia_aesni_avx_x86_64 camellia_x86_64 xcbc md4 ccm snd_hda_codec_hdmi snd_ctl_led snd_hda_codec_realtek snd_hda_codec_generic xt_CHECKSUM xt_MASQUERADE ipt_REJECT nf_reject_ipv4 nft_chain_nat nf_nat af_packet cmac algif_hash algif_skcipher af_alg bnep snd_sof_pci_intel_cnl snd_sof_intel_hda_common snd_soc_hdac_hda soundwire_intel snd_sof_intel_hda_mlink soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp msr snd_sof snd_sof_utils soundwire_generic_allocation hid_multitouch soundwire_bus hid_generic snd_soc_skl joydev snd_soc_sst_ipc
[  560.708799]  mousedev nouveau snd_soc_sst_dsp ath10k_pci snd_hda_ext_core snd_soc_acpi_intel_match intel_uncore_frequency intel_uncore_frequency_common snd_soc_acpi ath10k_core i915 intel_tcc_cooling snd_soc_core x86_pkg_temp_thermal intel_powerclamp coretemp cmdlinepart crc32_pclmul polyval_clmulni polyval_generic snd_compress gf128mul spi_nor ath ghash_clmulni_intel ac97_bus mei_hdcp mei_pxp snd_pcm_dmaengine intel_rapl_msr ee1004 sha512_ssse3 drm_gpuvm mtd dell_wmi sha512_generic dell_laptop mei_wdt iTCO_wdt mac80211 drm_exec snd_hda_intel sha256_ssse3 gpu_sched sha1_ssse3 intel_pmc_bxt snd_intel_dspcfg btusb drm_buddy drm_ttm_helper uvcvideo xt_conntrack aesni_intel ttm watchdog btrtl snd_intel_sdw_acpi crypto_simd ledtrig_audio btintel drm_display_helper nf_conntrack videobuf2_vmalloc snd_hda_codec cryptd dell_smbios btbcm uvc btmtk nf_defrag_ipv6 processor_thermal_device_pci_legacy dell_wmi_sysman cec dcdbas processor_thermal_device nf_defrag_ipv4 firmware_attributes_class dell_wmi_descriptor wmi_bmof
[  560.708830]  intel_wmi_thunderbolt mxm_wmi rapl ip6t_rpfilter snd_hda_core processor_thermal_wt_hint videobuf2_memops rc_core videobuf2_v4l2 processor_thermal_rfim processor_thermal_rapl cfg80211 bluetooth dell_smm_hwmon ipt_rpfilter snd_hwdep intel_cstate drm_kms_helper nls_iso8859_1 snd_pcm videodev intel_gtt nls_cp437 snd_timer agpgart intel_rapl_common vfat intel_lpss_pci i2c_hid_acpi intel_uncore psmouse fat ucsi_acpi xt_pkttype snd typec_ucsi i2c_algo_bit ecdh_generic mei_me videobuf2_common processor_thermal_wt_req i2c_i801 video i2c_hid rfkill processor_thermal_power_floor intel_lpss xt_LOG spi_intel_pci mc cdc_acm ecc libaes soundcore spi_intel i2c_smbus tpm_crb nf_log_syslog typec idma64 processor_thermal_mbox libarc4 intel_soc_dts_iosf mei thermal hid intel_pch_thermal virt_dma roles battery xt_tcpudp nft_compat int3403_thermal int340x_thermal_zone tiny_power_button evdev intel_pmc_core wmi dell_smo8800 pinctrl_cannonlake intel_vsec tpm_tis input_leds tpm_tis_core pmt_telemetry intel_hid led_class
[  560.708864]  int3400_thermal ac acpi_pad pmt_class acpi_thermal_rel sparse_keymap button mac_hid serio_raw nf_tables sch_fq_codel libcrc32c uinput ctr loop cpufreq_powersave tun tap macvlan bridge stp llc kvm_intel kvm drm irqbypass fuse efi_pstore backlight configfs nfnetlink efivarfs tpm rng_core dmi_sysfs ip_tables x_tables autofs4 ext4 crc32c_generic crc16 mbcache jbd2 ahci libahci rtsx_pci_sdmmc xhci_pci libata mmc_core xhci_pci_renesas nvme firmware_class atkbd libps2 vivaldi_fmap nvme_core xhci_hcd scsi_mod t10_pi crc32c_intel rtsx_pci crc64_rocksoft crc64 crc_t10dif crct10dif_generic crct10dif_pclmul crct10dif_common scsi_common i8042 rtc_cmos serio dm_mod dax
[  560.708892] CPU: 0 PID: 3692 Comm: kworker/u24:42 Tainted: G        W          6.8.1 #1-NixOS
[  560.708893] Hardware name: Dell Inc. XPS 15 9570/0D0T05, BIOS 1.30.0 12/15/2022
[  560.708894] Workqueue: events_unbound async_run_entry_fn
[  560.708897] RIP: 0010:drv_stop+0xf6/0x100 [mac80211]
[  560.708937] Code: 00 48 85 c0 74 0c 48 8b 78 08 48 89 de e8 c2 0e 05 00 65 ff 0d 63 24 89 3e 0f 85 39 ff ff ff 0f 1f 44 00 00 e9 2f ff ff ff 90 <0f> 0b 90 5b c3 cc cc cc cc 90 90 90 90 90 90 90 90 90 90 90 90 90
[  560.708938] RSP: 0018:ffffa5bbc7a87c28 EFLAGS: 00010246
[  560.708939] RAX: 0000000000000000 RBX: ffff88fcdc9e0900 RCX: ffff88fcc031e868
[  560.708941] RDX: 0000000080000000 RSI: 0000000000000282 RDI: ffff88fcdc9e0900
[  560.708942] RBP: ffff88fcdc9e0900 R08: 0000000000000000 R09: 0000000000000000
[  560.708943] R10: 0000000000000001 R11: 0000000000000100 R12: ffff88fcdc9e11d0
[  560.708943] R13: ffff88fcdc9e0e10 R14: 0000000000000000 R15: ffff88fcd95c5c18
[  560.708944] FS:  0000000000000000(0000) GS:ffff89002c200000(0000) knlGS:0000000000000000
[  560.708946] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  560.708947] CR2: 000000000049f030 CR3: 00000002d2420002 CR4: 00000000003706f0
[  560.708948] Call Trace:
[  560.708949]  <TASK>
[  560.708949]  ? drv_stop+0xf6/0x100 [mac80211]
[  560.708989]  ? __warn+0x81/0x130
[  560.708992]  ? drv_stop+0xf6/0x100 [mac80211]
[  560.709032]  ? report_bug+0x171/0x1a0
[  560.709035]  ? handle_bug+0x3d/0x80
[  560.709037]  ? exc_invalid_op+0x17/0x70
[  560.709039]  ? asm_exc_invalid_op+0x1a/0x20
[  560.709042]  ? drv_stop+0xf6/0x100 [mac80211]
[  560.709082]  ? drv_stop+0x12/0x100 [mac80211]
[  560.709121]  ieee80211_do_stop+0x56c/0x810 [mac80211]
[  560.709171]  ieee80211_stop+0x58/0x180 [mac80211]
[  560.709218]  __dev_close_many+0xa7/0x130
[  560.709222]  dev_close_many+0xa9/0x180
[  560.709224]  dev_close+0x8c/0xc0
[  560.709227]  cfg80211_shutdown_all_interfaces+0x4d/0xf0 [cfg80211]
[  560.709265]  wiphy_resume+0xc1/0x1b0 [cfg80211]
[  560.709302]  ? __pfx_wiphy_resume+0x10/0x10 [cfg80211]
[  560.709339]  dpm_run_callback+0x89/0x1b0
[  560.709341]  device_resume+0xb0/0x2d0
[  560.709343]  async_resume+0x1d/0x30
[  560.709345]  async_run_entry_fn+0x31/0x130
[  560.709348]  process_one_work+0x173/0x340
[  560.709351]  worker_thread+0x27b/0x3a0
[  560.709353]  ? __pfx_worker_thread+0x10/0x10
[  560.709355]  kthread+0xd4/0x100
[  560.709357]  ? __pfx_kthread+0x10/0x10
[  560.709358]  ret_from_fork+0x31/0x50
[  560.709360]  ? __pfx_kthread+0x10/0x10
[  560.709361]  ret_from_fork_asm+0x1b/0x30
[  560.709366]  </TASK>
[  560.709366] ---[ end trace 0000000000000000 ]---
[  560.709417] ieee80211 phy0: PM: dpm_run_callback(): wiphy_resume+0x0/0x1b0 [cfg80211] returns -110
[  560.709457] ieee80211 phy0: PM: failed to resume async: error -110
[  560.710963] OOM killer enabled.
[  560.710964] Restarting tasks ... done.
[  560.712226] random: crng reseeded on system resumption
[  560.712384] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_ops [i915])
[  560.770809] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.771073] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.771332] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.771595] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.771854] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.772112] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.772370] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
[  560.772629] ACPI Warning: Time parameter 250 us > 100 us violating ACPI spec, please fix the firmware. (20230628/exsystem-141)
</pre>
</details>

**Comment by woojiq** [comment]
I'm not 100% sure but I can't to reproduce it anymore on the latest nixpkgs fd281bd6b7d3e32ddfa399853946f782553163b5
I assume it was fixed by the new Linux kernel version. I had 6.7.6 and now 6.8.3.

**Comment by philipwilk** [comment]
might have been a different issue for you then, it still happens on my machine.
