### ISSUE TITLE
Mission Center does not show GPU stats on AMD GPU

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#294143]
### Describe the bug
Since the update to 0.4.4 in #287820, mission center no longer displays GPU stats for my AMD graphics card.

### Steps To Reproduce
1. Open mission center

### Expected behavior
GPU usage should be shown

### Additional context
I have an AMD Radeon RX 6800 XT.

The previous version contains these extra lines in the startup logs:
```
DRI driver not from this Mesa build ('24.0.1' vs '23.3.5')
failed to bind extensions
DRI driver not from this Mesa build ('24.0.1' vs '23.3.5')
failed to bind extensions
DRI driver not from this Mesa build ('24.0.1' vs '23.3.5')
failed to bind extensions

(missioncenter-gatherer:74376): Gatherer::GpuInfo-ERROR **: 23:6:36.43: Failed to get OpenGL information: No such file or directory (os error 2)
```

### Notify maintainers
@GaetanLepage

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.7.6, NixOS, 24.05 (Uakari), 24.05.20240229.1536926`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos"`
 - channels(lunik1): `""`
 - nixpkgs: `/nix/store/lwyjz70qh12nq6cb7fixl85vryzxqm3c-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Aleksanaa** [comment]
I don't have a graphics card but I would guess you used a different nixpkgs checkout than the system closure to run the mission-center (e.g. with nix-shell or nix run)? Therefore, the mesa version to which this package is linked does not match the version of your system.

**Comment by lunik1** [comment]
I think those are a red herring. They are shown on the old version when I run from a nixpkgs checkout, but I still get GPU stats.

**Comment by GaetanLepage** [comment]
> I think those are a red herring. They are shown on the old version when I run from a nixpkgs checkout, but I still get GPU stats.

I don't have an AMD GPU either... Not sure what we can do here...
Any chance that the issue is actually caused by upstream ?

**Comment by lunik1** [comment]
Possibly. I have tried using the flatpak version and that doesn't show my graphics card either, but all versions seem to have that issue.

**Comment by Lyndeno** [comment]
Does not seem to show stats for my laptop nvidia gpu either

**Comment by Arqamz** [comment]
My AMD dGPU doesnt show up in mission center either

**Comment by lunik1** [comment]
It's back for me

**Comment by kimjongbing** [comment]
Does not show up on my Nvidia GPU either.

**Comment by lunik1** [comment]
Issues on NVIDIA might be best as a new issue.

**Comment by lunik1** [comment]
Since the original issue with AMD cards is fixed for me, I'm going to close.

**Comment by NonRidiculousAdjective** [comment]
I still have this problem

**Comment by brckd** [comment]
> Since the original issue with AMD cards is fixed for me, I'm going to close.

Do you know what fixed the issue? I experience this problem with my AMD Radeon RX 6600.

**Comment by saygo-png** [comment]
Same issue on 0.6.2

**Comment by GaetanLepage** [comment]
> Same issue on 0.6.2

We have just merged the update to `1.0.2`. Can you tell me if it now works?

https://nixpkgs-tracker.ocfox.me/?pr=403986

**Comment by saygo-png** [comment]
> We have just merged the update to `1.0.2`. Can you tell me if it now works?

Sadly it still doesn't, i'm also running the AMD Radeon RX 6600 like the person above. It spits out an error in the console, not sure if its significant, it did that on 0.6.2 too.
My setup is specific in that i also have a an integrated gpu.

Tested on this commit, the "pc" configuration  https://github.com/saygo-png/nixos/commit/ef25ff24e882c69de3d165776f219155b571d9fa

![Image](https://github.com/user-attachments/assets/41341b66-7555-481f-9ce4-1a67f26ebcd3)

**Comment by GaetanLepage** [comment]
Well, I would be curious to see if this is happening with a non-nix version of mission-center.
This would tell us if it is a packaging issue or a problem with the upstream package itself.

**Comment by saygo-png** [comment]
> Well, I would be curious to see if this is happening with a non-nix version of mission-center.

I don't have a non nixos system, so i tried running it using the flatpak. The gpu info was still missing, but i'm also getting a shared lib error most likely caused by nixos. 
I tried to run the flatpak in a shell with the dependencies from the nix package but i still got the missing lib error.
Though maybe this is still an upstream issue? I thought flatpak was supposed to isolate the dependencies from the host system.

![Image](https://github.com/user-attachments/assets/74d21e83-f7cc-49cc-b89f-36c5ee4e0fb0)

**Comment by bricked-dev** [comment]
I posted the same issues on https://gitlab.com/mission-center-devs/mission-center/-/issues/330

**Comment by ReeSilva** [comment]
Same thing happening here with a RX 5700 XT. My logs are a little bit different, tho

<img width="2213" height="486" alt="Image" src="https://github.com/user-attachments/assets/81a05571-805a-452a-900c-1aa350aa34a8" />

**Comment by qwertychouskie** [comment]
> I thought flatpak was supposed to isolate the dependencies from the host system.

Normally yes, but Mission Center has to run some of the gatherer stuff outside the sandbox for it to work properly.  I think I was told at some point that NixOS same something like `steam-run` that simulates a normal directory structure?  It may work if you use that, worth a shot anyways.

**Comment by brckd** [comment]
> I tried to run the flatpak in a shell with the dependencies from the nix package but i still got the missing lib error. 

Possibly see #49957 @saygo-png

**Comment by jfreuden** [comment]
@GaetanLepage Using the `steam-run` hint from @qwertychouskie and strace, I was able to fix this on my machine by adding `libdrm` to the `missioncenter-magpie` wrapper in `package.nix`. Still new to NixOS, Are there any considerations to making this modification? Also, is there a possibility this would resolve the reports of similar issues for Nvidia GPU's?

**Comment by saygo-png** [comment]
> Can you confirm it works when building `mission-center` from this branch?

It works!!! Thank you guys so much.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7a47b768-3134-47f6-9d18-d810d9a7306d" />

**Comment by jfreuden** [comment]
I can also confirm that it works from that branch.

<img width="1533" height="1288" alt="Image" src="https://github.com/user-attachments/assets/c0fac248-3e63-49ad-b1fc-2761b1e5a06b" />
