### ISSUE TITLE
plasma6 lock-screen: virtual keyboard not working

### ISSUE THREAD

**Issue by pbek** [NixOS/nixpkgs#303526]
### Describe the bug
At the plasma6 lock-screen, the virtual keyboard (button on the bottom left) is not working (Wayland or X11 doesn't matter).

### Steps To Reproduce
1. Enable plasma6 in your configuration with `services.desktopManager.plasma6.enable = true;` in nixos-unstable
2. Reboot and see the lock-screen
3. Try to click the virtual keyboard on the bottom left, nothing seems to happen (works in plasma5)

### Expected behavior

Upon clicking the virtual keyboard button, a virtual keyboard shows up to enter the password, just like in plasma5.

### Notify maintainers

Something for you, @K900?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.6.23, NixOS, 24.05 (Uakari), 24.05.20240403.08b9151`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/run/current-system/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by K900** [comment]
Interesting. It works for me on Wayland at least.

**Comment by pbek** [comment]
Really? It doesn't work for me on devices with Wayland (with AMD or Intel GPU) or X11.
Need the Virtual Keyboard, because the Asus ROG Ally only has a touchscreen. 😁 Had to fall back to plasma5! 😱😉

**Comment by betalars** [comment]
I can confirm this. It used to work before plasma 6 and now the button just seems to switch keyboard layouts I think.

**Comment by pbek** [comment]
Still an issue for me with Plasma 6.0.4 (Wayland), KDE Framework 6.1.0.

- DE: Plasma 6.0.4 (Wayland) 
- WM: kwin 
- CPU: Intel i5-8250U (8) @ 3.400GHz 
- GPU: Intel UHD Graphics 620 

`nix-shell -p nix-info --run "nix-info -m"`:

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.29, NixOS, 24.05 (Uakari), 24.05.20240502.63c3a29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by BeiNacht** [comment]
Any progress on this bug? I also have it under wayland. Havent tested Xorg

**Comment by K900** [comment]
This should have been fixed upstream a long time ago. Are you on 24.05?

**Comment by pbek** [comment]
I am on latest unstable. Still an issue, even under Wayland.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 25.05 (Warbler), 25.05.20241119.23e89b7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/run/current-system/nixpkgs`

When I click the virtual keyboard button in the lock screen, nothing happens.

**Comment by K900** [comment]
And you have `maliit-keyboard` installed?

**Comment by pbek** [comment]
> And you have `maliit-keyboard` installed?

Oh. No, I don't. Should I have it installed?

**Comment by K900** [comment]
Yes, we don't install it by default, though maybe we should.

**Comment by BeiNacht** [comment]
> This should have been fixed upstream a long time ago. Are you on 24.05?

24.05 and unstable. Have this problem at least since plasma6.

Installed maliit-keyboard aswell doenst works, cause was looking in KDE communities for a fix. Found this issue only yesterday. What i read was that `kdePackages.qtvirtualkeyboard` is used in sddm.
I wasnt also able to find any log which gives me informations. Any ideas?

**Comment by pbek** [comment]
> And you have `maliit-keyboard` installed?

Installing it also didn't make the virtual keyboard at the lock screen work for me.

**Comment by K900** [comment]
You may also need to install `maliit-framework`.

**Comment by pbek** [comment]
That came with `maliit-keyboard`. 🤔

**Comment by pbek** [comment]
Tried to add it to the config, still no on-screen keyboard...

**Comment by deftdawg** [comment]
In Deck mode, I get `maliit-keyboard`, it looks just like SteamOS works perfectly.

On the KDE Plasma6 lock screen, I get `qtvirtualkeyboard`, if I use the touch screen I can enter a password, if I use the touchpad to move the pointer I'm lucky if it will let me click on one letter of my password before it disappears until the machine is sleep cycled (sometimes) or re-locked (using a physical keyboard to unlock).

On an unlocked Plasma6 Desktop, I can't get any virtualkeyboard to appear at all either with Steam running (which seems to capture the deck controls) or without Steam running where touchpad works as a mouse (Steam +X doesn't work).

Idk if it's a skill issue on my part (misconfiguration), but I miss being able to use mailit everywhere on the desktop and not having steam hog the controls while it's running.
  

https://github.com/user-attachments/assets/fca72757-49b5-4b6b-9e4c-563a217823e5

**Comment by Worble** [comment]
I fixed this issue by changing the Compositor Command to launch `kwin_wayland` with `--inputmethod maliit-keyboard` which I took from the arch wiki https://wiki.archlinux.org/title/SDDM#Virtual_keyboards
Judging from the wiki, `qt6-virtualkeyboard` should also work if you don't want to install `maliit-keyboard`

e.g
```nix
{ pkgs, lib, ... }:

let
  kwin = lib.concatStringsSep " " [
    "${lib.getBin pkgs.kdePackages.kwin}/bin/kwin_wayland"
    "--no-global-shortcuts"
    "--no-kactivities"
    "--no-lockscreen"
    "--locale1"
    "--inputmethod maliit-keyboard"
  ];
in
{
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    settings = {
      Wayland = {
        CompositorCommand = kwin;
      };
    };
  };
}
```

Is this something missing from the sddm module? I'm new to nix but would be happy to try make a PR so that sddm passes `qt6-virtualkeyboard` or optionally `maliit-keyboard` to kwin_wayland if it's installed.

**Comment by pbek** [comment]
@Worble, I tried using that in https://github.com/pbek/nixcfg/commit/eac4801631c26bfba7661e3802695f37078fb8a4 on my ROG Ally, but when I lock the Plasma session the *Virtual Keyboard* button still does nothing. 😬

**Comment by K900** [comment]
You also need to install `maliit-framework`.

**Comment by pbek** [comment]
When I set `malit` as virtual keyboard in the `Virtual Keyboard` settings, I get the virtual keyboard every time I need to type text, even in konsole! 🥳🎉
And also in the password field in the lock screen! 👏

> You also need to install maliit-framework.

`maliit-keyboard` was enough in when I use the setting. 🥳

**Comment by pbek** [comment]
As a test, I tried to set the Virtual Keyboard to *none* again, installed `maliit-framework`, rebooted, logged in, locked again. Not keyboard with the *Virtual Keyboard* button at the lock screen...

**Comment by K900** [comment]
You don't. The SDDM configuration does not affect your lock screen, because your lock screen is not SDDM.

**Comment by pbek** [comment]
Ah, thank you for clarifying! I thought https://github.com/NixOS/nixpkgs/issues/303526#issuecomment-2632406493 was also about the lock screen.
