### ISSUE TITLE
blender-hip does not detect compatible GPU on default kernel

### ISSUE THREAD

**Issue by betalars** [NixOS/nixpkgs#303586]
### Describe the bug
When trying to set up my compatible AMD-video-card with blender-hip, it is not being detected.  Console reads:
`HIP hipInit: Invalid device`

### Steps To Reproduce
0. have a system with a compatible AMD card
1. `nix shell nixpkgs#blender-hip`
2. `blender`
3. edit > preferences > system > cycles render settings > hip

### Observed behavior
No compatible GPUs found for cycles [...]

### Additional context
[I have read the wiki and it says using blender-hip is all I should need to do.](https://nixos.wiki/wiki/AMD_GPU)

#### Known Workaround
You can [upgrade the Kernel used to the latest Version](https://wiki.nixos.org/wiki/Linux_kernel) and that resolved the issue for me.

### Notify maintainers
@cillianderoiste @veprbl

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.78, NixOS, 24.05 (Uakari), 24.05.20240403.fd281bd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos, nixpkgs"`
 - channels(betalars): `"nixos, nixpkgs"`
 - nixpkgs: `/home/betalars/.nix-defexpr/channels/nixpkgs`
```
_Please note: I am running flakes and am actually on unstable:_
```
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Guekka** [comment]
@betalars I fixed the same issue by upgrading the kernel, can you try this?

**Comment by betalars** [comment]
@Guekka oh now I understand what they were discussing in that other thread.]\

I still do not consider this issue to be resolved, but I personally can work with this for now.

**Comment by betalars** [comment]
fyi I added a disclaimer to the wiki, that should be discarded when this is resolved or a new LTS Kernel is released.

**Comment by betalars** [comment]
Closing, as this is only a kernel version thing and not an actual bug.
