### ISSUE TITLE
Xserver/awesome buggy video output when changing resolution of screen

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#30502]
## Issue description
When a screen is connected, everything is fine (no matter whether it is the first, second or third screen, it is auto detected and it runs flawlessly). But when I change the resolution of a (or multiple) screen, everything on the output goes mad (like windows are drawn multiple times and are not aligned with the screen borders and so on, have a look on the Screenshot):

![2017-10-17t12 41 21_1024x768](https://user-images.githubusercontent.com/20400405/31661099-ce8d61c6-b339-11e7-8a73-9ed9cf03d4b6.png)

There is an offset between where the mouse is displayed and where it actually does things too. I had this very thing occur to me this year in spring using arch linux, however, the issue resolved itself after a few weeks (for reference: https://github.com/awesomeWM/awesome/issues/1704 ). I think (but I cannot confirm) that this issue was resolved due to an update of `Xserver`, which kind of fits, as the actual version of X I'm using now on nixos is  `Release Date: 2017-03-15`, so just a few weeks **before**  the issue was resolved in Arch (which happens to use the most recent release of X).

I'am relatively sure that this is not an direct awesome issue, but appears on awesome because is relying on X features more heavily than most established desktop environments. I was using awesome 4.1 when this happened and after it was resolved on arch, now I have awesome 4.2, which implicates that the issue is not caused by awesome.

### Steps to reproduce
+ Connect a screen to a machine running nixos and awesome wm
+ Use `arandr` or `xrandr` to change the resoultion of at least one connected screen

## Technical details
* awesomewm: `awesome 4.2 (Human after all)`
* X: `X.Org X Server 1.19.3`
* System: NixOS: `17.09.1535.1fdca25ee8 (Hummingbird)`
* Nix version: `nix-env (Nix) 1.11.15`
* Nixpkgs version: "17.09.1535.1fdca25ee8"
* Sandboxing enabled: `build-use-sandbox = false`

Is there an easy way of trying different X releases?

**Comment by dtzWill** [comment]
Whoa I'm seeing this too.  When I saw the wrapping I thought my video driver was bugged (seemed plausible since I'm using bumblebee for intel/nvidia by-our-powers-combined).  I don't have any answers for you yet, but you're not alone!

**Comment by vcunat** [comment]
If you suspect X server version, you should update.  Current 17.09 channel has 1.19.5 &ndash; security fixes BTW.

**Comment by wucke13** [comment]
Just did the upgrade to `X.Org X Server 1.19.5`. This screenshot is from a dual head setup. Regarding the driver: back in arch, that happend both on nouveau and nvidia driver. Today this happens on nouveau, but on my laptop too, which has an intel igp (that seems to have good driver support). Maybe an kernel/driver problem which was resolved later on?
![2017-10-21t12 06 01_1824x768](https://user-images.githubusercontent.com/20400405/31850769-b114248c-b658-11e7-8254-808faa476995.png)

**Comment by GallagherCommaJack** [comment]
I'm having this issue with intel graphics on i3 and xfce, so I'm pretty sure it's a general issue with xrandr

**Comment by dv-blk** [comment]
By simply using xrandr to change resolution I can also reproduce this wrapping behaviour.

Some details:
- bspwm or xmonad 
- xrandr 1.5,  xorg 1.19.5 or with `xorg.abiCompat = "1.18";`
- intel display drivers i915
- slim or sddm (i think this happened on sddm too)
- nixos updated as of yesterday

This too doesn't happen on arch using the same computer, same version of xrandr, X 1.19.4

**Comment by dv-blk** [comment]
I am able to save xrandr settings from arandr, run this file before my window manager starts, and my display does not repeat in the same way as above-- it simply displays the window manager _only_ displaying (hanging) off the bottom half of the screen.

**Comment by wucke13** [comment]
This bug is now resolved for me, using arandr to change resolution or alignment is rock solid for now for me. I am on `nixos-17.09.3023.c882c4dd55e`. How about you, is the issue still there?

**Comment by dv-blk** [comment]
Thanks for the update! This has been fixed up for me too.

**Comment by GallagherCommaJack** [comment]
It's fixed enough to support my normal workflow, but not actually 100% fixed for me.
`arandr` still doesn't do the right thing if I try to use both my laptop and desktop monitors side by side instead of mirrored.
The screen on the right will invariably be locked to whatever the main display area was showing at the time of the I set the layout using `arandr`.
Script can be found [here](https://pastebin.com/QRRiJqke).
Scrot of what happens when I run that script ![here](https://user-images.githubusercontent.com/5674469/36778366-60b33ac6-1c21-11e8-918e-e813763b3cad.png)
