### ISSUE TITLE
clonehero segfaults on launch

### ISSUE THREAD

**Issue by natervader** [NixOS/nixpkgs#313012]
Was not sure if it was best to open a new issue here. If this isn't the right place feel free to let me know too! I have also seen this come up in #275039, which is why I was hesitant on opening a new issue.

### Describe the bug
Clonehero returns with a "Segmentation fault (core dumped)" upon launching.

### Steps To Reproduce
1. Add `clonehero` to `environment.systemPackages` in my `/etc/nixos/configuration.nix`.
2. Rebuild the NixOS system to install package.
3. Run `clonehero`.

### Expected behavior
Clonehero opens in a playable state.

### Additional context
Running `clonehero` results with:
```
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
Segmentation fault (core dumped)
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.91, NixOS, 23.11 (Tapir), 23.11.7202.e7cc61784ddf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Side Note
I'm not sure how else to determine the issue on my end. Downloading the game directly from the official site and running the executable with `steam-run` *does* work, however.

**Comment by Aleksanaa** [comment]
Ping @syboxez @kira-bruneau

**Comment by kira-bruneau** [comment]
Oh yep, sorry! Looks like it's the same issue, but for the nixos-23.11 release branch and we just never backported the fix. This should fix it: https://github.com/NixOS/nixpkgs/pull/313149.

**Comment by natervader** [comment]
> Oh yep, sorry! Looks like it's the same issue, but for the nixos-23.11 release branch and we just never backported the fix. This should fix it: #313149.

Sounds great! 

I must admit my ignorance since I'm still getting used to NixOS. What would be the best method for testing the fix on my end? 

Thanks again @kira-bruneau.
