### ISSUE TITLE
Direct firmware load for mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin failed with error -2

### ISSUE THREAD

**Issue by jezcope** [NixOS/nixpkgs#315103]
### Describe the bug
As of Linux kernel 6.9.1 (as currently assigned to `linux_latest`), the kernel tries to load a 

### Steps To Reproduce
1. Have a USB BT controller with mediatek MT7961
2. Update to Linux kernel 9.6.1 (e.g. with `{ boot.kernelPackages = pkgs.linuxPackages_latest; }`
3. Bluetooth does not work (no controller found) and journal shows:

```
May 27 14:59:40 gwydion kernel: bluetooth hci0: Direct firmware load for mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin failed with error -2
May 27 14:59:40 gwydion kernel: Bluetooth: hci0: Failed to load firmware file (-2)
May 27 14:59:40 gwydion kernel: Bluetooth: hci0: Failed to set up firmware (-2)
May 27 14:59:40 gwydion kernel: Bluetooth: hci0: HCI Enhanced Setup Synchronous Connection command is advertised, but not supported.
```

### Expected behavior
Firmware loads and bluetooth functions correctly.

### Additional context
Problem is known upstream, reported in [218757 on Kernel.org Bugzilla](https://bugzilla.kernel.org/show_bug.cgi?id=218757) which gives a few workarounds. The cause is that the updated firmware is not yet available in `linux-firmware`. I have currently worked around it by reverting to a 6.8-series kernel, but symlinking the current firmware to the new name or manually downloading the updated firmware both seem to work.

### Notify maintainers

@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.10, NixOS, 24.11 (Vicuña), 24.11.20240524.bfb7a88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.90.0-beta.1-lixpre20240506-b6799ab`
 - channels(jez): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source`
```

_NB. this is while booting the working system (kernel 6.8.10)_

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by lxsameer** [comment]
I have the same problem. I created a derivation for the new firmware and used it. Now the firmware loads but as it said on the kernel bugzilla as well now there is another issue that needs a kernel patch. 

Just for search engines sake:

```
[   19.592665] Bluetooth: hci0: Execution of wmt command timed out
[   19.592684] Bluetooth: hci0: Failed to send wmt func ctrl (-110)
[   19.592692] Bluetooth: hci0: HCI Enhanced Setup Synchronous Connection command is advertised, but not supported.
[   24.712662] Bluetooth: hci0: Failed to write uhw reg(-110)
[   29.832914] Bluetooth: hci0: Failed to read uhw reg(-110)
[   34.952893] Bluetooth: hci0: Failed to write uhw reg(-110)
[   40.072820] Bluetooth: hci0: Failed to write uhw reg(-110)
[   45.192617] Bluetooth: hci0: Failed to read uhw reg(-110)
[   50.312549] Bluetooth: hci0: Failed to write uhw reg(-110)
[   55.432598] Bluetooth: hci0: Failed to read uhw reg(-110)
[   60.552819] Bluetooth: hci0: Failed to write uhw reg(-110)
[   65.672662] Bluetooth: hci0: Failed to read uhw reg(-110)
[   70.792784] Bluetooth: hci0: Failed to read uhw reg(-110)
[   75.913388] Bluetooth: hci0: Failed to read uhw reg(-110)
```

**Comment by alyssais** [comment]
This should have been fixed in https://github.com/NixOS/nixpkgs/pull/314630.  Reply if it isn't and we can re-open.

**Comment by highghlow** [comment]
> This should have been fixed in #314630. Reply if it isn't and we can re-open.

@alyssais , it's still broken. I have tried it on linux 6.8, 6.9 and latest (6.10) while on the unstable branch

**Comment by highghlow** [comment]
I think this patch is related: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20240517&id=958cd6beab693f395ffe07814ef77d2b45e8b0fc

**Comment by alyssais** [comment]
@highghlow are you sure it's the same issue?  When did it start happening?  Can you post some logs?

**Comment by highghlow** [comment]
> @highghlow are you sure it's the same issue? When did it start happening? Can you post some logs?

```
nixer@laptop:~ 
> uname -r                                                                     
6.9.12

nixer@laptop:~ 
> sudo dmesg | grep blue                                                       
[sudo] password for nixer: 
[   10.871550] bluetooth hci0: Direct firmware load for mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin failed with error -2
```

**Comment by highghlow** [comment]
The same exact thing happens when using 6.8 and 6.10

**Comment by alyssais** [comment]
Can you please test 6.9.2 specifically, and let me know if it works there?  That will tell us if this regressed again, or never fixed the issue for you.

**Comment by highghlow** [comment]
Alright

**Comment by highghlow** [comment]
Wait, how? `pkgs.linuxPackages_9_2` returns the 9.2.12 kernel...

**Comment by alyssais** [comment]
Either use an old Nixpkgs commit, manually edit kernels-org.json, or call `buildLinux` in your config:

```nix
boot.kernelPackages = with pkgs; linuxPackagesFor (buildLinux {
  version = "6.9.2";

  src = fetchurl {
    url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.2.tar.xz";
    hash = "sha256-1Gxb3yxZYcwqTe3v4ENNRWhl6V5KfNn5P/8FT5CQ5fk=";
  };
});
```

**Comment by alyssais** [comment]
The old Nixpkgs commit method would be best, in case it's something else (e.g. linux-firmware update) that broke this in the meantime.  Try 7e8989a8f354c7dab23b89d0d39a997cfed55917?

**Comment by highghlow** [comment]
I have added the commit you sent me to flake inputs:

```
nixpkgs-oldkernel.url = "github:nixos/nixpkgs/7e8989a8f354c7dab23b89d0d39a997cfed55917";
```

but now
```
boot.kernelPackages = inputs.nixpkgs-oldkernel.linuxPackages_6_9;
```

returns
```
error: attribute 'linuxPackages_6_9' missing
```

**Comment by highghlow** [comment]
> I think this patch is related: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20240517&id=958cd6beab693f395ffe07814ef77d2b45e8b0fc

Can this be helpful in resolving the issue (it's about a wifi module, but I have the same problem with it)

**Comment by highghlow** [comment]
I guess we won't be able to tell if it's a regression or not. The issue still needs to be fixed though. Where dpes nixos pull firmware from?

**Comment by highghlow** [comment]
I found the offending file on the linux-firmware repo. It was last updated 3 weeks ago, should we try just updating it in nixpkgs? https://gitlab.com/kernel-firmware/linux-firmware/-/commits/main/mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin?ref_type=heads

**Comment by alyssais** [comment]
The version of linux-firmware in nixos-unstable is from a week ago.

**Comment by highghlow** [comment]
hm...

**Comment by highghlow** [comment]
The patch says it fixes a previous patch, which broke the mt7921 chip and it is weirdly linked with our bluetooth problem

**Comment by highghlow** [comment]
I got the older kernel (seen in the build logs). I will soon have physical acees to enter the luks lassword

**Comment by highghlow** [comment]
It's still broken with the commit you sent me

**Comment by alyssais** [comment]
Did you build your whole configuration with the old Nixpkgs, or just the kernel?

**Comment by highghlow** [comment]
Only the old kernel

**Comment by alyssais** [comment]
Could you please building your whole configuration with the old Nixpkgs? It could be a regression in something else, like linux-firmware.

**Comment by highghlow** [comment]
My current config fails if I downgrade nixpkgs. I will need to make a minimal config to build it

**Comment by highghlow** [comment]
I have now build a minimal config with the older nixpkgs. It still returns this error

**Comment by highghlow** [comment]
@alyssais I think the issue was never fixed...

**Comment by alyssais** [comment]
Thanks, so I guess the fix didn't work for you.  In that case, I think you need to report this upstream, and explain that you've tried kernels that are supposed to include the patch, but that they don't work for you.

**Comment by alyssais** [comment]
ENOENT 2 No such file or directory

**Comment by highghlow** [comment]
Wait a minute... **The latest NixOS Installer has WIFI!** (uses linux 6.6.45), so it is a regression!

**Comment by alyssais** [comment]
Wait… you have firmware enabled in your NixOS configuration, right?  hardware.enableRedistributableFirmware?

**Comment by highghlow** [comment]
I think so...

**Comment by highghlow** [comment]
Maybe not...

**Comment by highghlow** [comment]
I enabled it and it now works! lol

**Comment by highghlow** [comment]
Well, in my defense, nobody told me this option existed... In my antidefense, it's referenced in the generated hwconfig...

**Comment by highghlow** [comment]
Okay, @alyssais , you can close the issue
