### ISSUE TITLE
Build failure: python3Packages.spacy, python3Packages.wandb

### ISSUE THREAD

**Issue by cfhammill** [NixOS/nixpkgs#329949]
### Steps To Reproduce

nix-shell -p 'python3Packages.wandb'

### Build log

```
 error: Package ‘python3.11-youtube-dl-2021.12.17’ in /mnt/data/home/HammillC/documents/nixpkgs/pkgs/tools/misc/youtube-dl/default.nix:84 is marked as insecure, refusing to evaluate.


       Known issues:
        - youtube-dl is unmaintained, migrate to yt-dlp, if possible
```

### Additional context

Fixed by fixing moviepy as in https://github.com/NixOS/nixpkgs/pull/329762

### Notify maintainers

@samuela

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by samuela** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/329762

**Comment by alexvorobiev** [comment]
The title is misleading - both spacy and wandb are still broken due to dependency on pathtools which doesn't support python-3.12.
