### ISSUE TITLE
ghcjsHEAD doesn't build anymore

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#33113]
After about an hour of debugging I've been able to work out this "tree of failure":

* GHC 8.0:
  * cabal-install doesn't build, because it wants Cabal 2.0 which isn't bundled with GHC.
    * We don't have an older version of cabal-install in the Hackage package set anymore?? `haskell.packages.ghc802.cabal-install` doesn't build at all. WTF?
* GHC 8.2:
  * shelly doesn't build, but we can just skip the checkPhase for that.
  * haddock-api wants a haddock-library version that isn't in the Hackage package set.
    * If I override the version of haddock-library, the haddock-api build gives me this error: `cp: missing destination file operand after '/private/tmp/nix-build-haddock-api-2.18.1.drv-0/package.conf.d/'` because haddock-library doesn't have anything in its package.conf.d directory. Why not??

**Comment by domenkozar** [comment]
cc @shlevy

**Comment by shlevy** [comment]
The second issue is due to https://github.com/NixOS/nixpkgs/issues/32980, fixed in https://github.com/NixOS/nixpkgs/pull/32993

**Comment by turion** [comment]
Does it make sense to rename this issue to "cabal-install-2.0.0.1 doesn't build"? That's what's leftover, it seems, and it still appears in nixos-unstable. See the following log:

```
building path(s) ‘/nix/store/9w97856hwm2f805fbnk6zzxqr0lkv4i8-cabal-install-2.0.0.1’, ‘/nix/store/a73mkvn66zy9p49hmzwvcjkbs5nv0p5s-cabal-install-2.0.0.1-doc’
setupCompilerEnvironmentPhase
Build with /nix/store/sfqmsw46sl9zkcyfvpjx91xwbjpcs3sp-ghc-8.2.1-binary.
unpacking sources
unpacking source archive /nix/store/v502d5pw3kr5r17iwlwwdb478ycyvp12-cabal-install-2.0.0.1.tar.gz
source root is cabal-install-2.0.0.1
setting SOURCE_DATE_EPOCH to timestamp 1512181414 of file cabal-install-2.0.0.1/tests/README.md
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/cabal-install-2.0.0.1/revision/3.cabal.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-cabal-install-2.0.0.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-cabal-install-2.0.0.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/9w97856hwm2f805fbnk6zzxqr0lkv4i8-cabal-install-2.0.0.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/a73mkvn66zy9p49hmzwvcjkbs5nv0p5s-cabal-install-2.0.0.1-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-cabal-install-2.0.0.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/9w97856hwm2f805fbnk6zzxqr0lkv4i8-cabal-install-2.0.0.1/lib/ghc-8.2.1-binary/cabal-install-2.0.0.1 --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --ghc-option=-split-sections
Configuring cabal-install-2.0.0.1...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:948:20 in Cabal-2.0.0.2:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:470:12 in Cabal-2.0.0.2:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:570:20 in Cabal-2.0.0.2:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.0.0.2:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:174:19 in Cabal-2.0.0.2:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:128:42 in Cabal-2.0.0.2:Distribution.Simple
  defaultMainWithHooks, called at Setup.hs:42:8 in main:Main
Setup: Encountered missing dependencies:
Cabal >=2.0.1.0 && <2.1
builder for ‘/nix/store/y3ck7yq5v2syjwax8r1j1af7kcdby0fj-cabal-install-2.0.0.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/k2zwvrlns3isd911l8ysawkzbcbs4mf3-ghcjs-0.2.0.drv’: 1 dependencies couldn't be built
```

**Comment by turion** [comment]
If anyone can give me a pointer what should be done, I'll happily give it a try, but right now I'm with pikajude on "WTF" ;)

**Comment by turion** [comment]
I think this issue doesn't occur anymore. But there is a different issue now: #34783

**Comment by ryantm** [comment]
`nix-build . -A haskell.compiler.ghcjs` builds and there is no attribute called ghcjsHEAD in nixpkgs `master`, so this should probably be closed.
