### ISSUE TITLE
odfpy build broken

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#33362]
## Issue description

The update in 2815c987d9bdb43f6cb47e8be4964f4b862c701a broke the package.

### Steps to reproduce

Per hydra: https://hydra.nixos.org/build/67105275

**Comment by mdorman** [comment]
@FRidh I don't know if you have any insight into why this is failing?

**Comment by FRidh** [comment]
Was fixed in e92a133238aea65770556631bdff307855ecdc77 and 5304715a24b12241d0b307a97bdb49a477db2473.

**Comment by stubbfel** [comment]
may is still broken. after an upgrade today (17.09.small) i got following test error 

======================================================================
ERROR: testAttributeForeign (teststyles.TestQattributes)
Test that you can add foreign attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-odfpy-1.3.6.drv-0/odfpy-1.3.6/tests/teststyles.py", line 91, in testAttributeForeign
    s.index(u'xmlns:ns44="http://foreignuri.com"')
ValueError: substring not found

----------------------------------------------------------------------

**Comment by FRidh** [comment]
I've just checked (it's at 31baf4e57ba02b7b7c3b448eaba63394c5bf7beb at the time of writing) and was able to produce
```
/nix/store/pbdag7v39nh7q10pjwdvx1f840ymqbb9-python2.7-odfpy-1.3.6
/nix/store/gnrgghiww13sk72k2c2nymxynx5xqxx2-python3.6-odfpy-1.3.6
```

**Comment by stubbfel** [comment]
hmm i still get the  same error. but i see the the disable test commit  6484eac5b2e38490724d9df3079e736605c7eeb6 was not apply to the 17.09 branch/channel

**Comment by FRidh** [comment]
@stubbfel are you building from source, without sandbox (and not using the binary cache)?

**Comment by stubbfel** [comment]
yes sandbox and cache  are disabled

**Comment by FRidh** [comment]
It is quite likely a build fails when the sandbox is disabled.

**Comment by stubbfel** [comment]
i got also the error when i add  `nix.useSandbox = true;` to my configuration.nix

**Comment by plumps** [comment]
```
# git branch --contains 6484eac5b2e38490724d9df3079e736605c7eeb6
master
```

**Comment by rleppink** [comment]
I'm experiencing the issue with the, currently latest `nix-channel --update` on 17.09.

`nixos-rebuild` log: https://gist.github.com/rleppink/7faa6c859d557a48b2e461f5aa00a60b

`nix-info` output:
`system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.16, channels(username): "", channels(root): "nixpkgs-unstable-18.03pre126798.42b9b8f7c86, nixos-17.09.2905.c1d9aff56e0", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by FRidh** [comment]
@rleppink 
Nixpkgs at c1d9aff56e0 should produce 
```
nix-build -A python2.pkgs.odfpy
/nix/store/pbdag7v39nh7q10pjwdvx1f840ymqbb9-python2.7-odfpy-1.3.6

nix-build -A python3.pkgs.odfpy
/nix/store/gnrgghiww13sk72k2c2nymxynx5xqxx2-python3.6-odfpy-1.3.6
```

Nixpkgs at 42b9b8f7c86 should produce
```
nix-build -A python2.pkgs.odfpy
/nix/store/aar63w0dz4dls343jzpkg30wwfnwbsf8-python2.7-odfpy-1.3.6

nix-build -A python3.pkgs.odfpy
/nix/store/l503fkfxa2lggcfjgs5jq9ki0h9x4d0m-python3.6-odfpy-1.3.6
```

In your log it produces
```
/nix/store/pbdag7v39nh7q10pjwdvx1f840ymqbb9-python2.7-odfpy-1.3.6
```



which implies you are actually using a different `nixpkgs` (did you set `-I` or `NIX_PATH`) or overrides (overlays?).

**Comment by rleppink** [comment]
> did you set -I or NIX_PATH

`echo $NIX_PATH
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels`

`sudo nix-channel --list
nixos https://nixos.org/channels/nixos-17.09
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable`

Where would I set `-I` or overrides/overlays? I don't think I did any of those.

**Comment by plumps** [comment]
@FRidh 

Nope c1d9aff56e0ae52ee4705440fe09291a51e91977 leads to 

broken build for

```
nix-build '<nixpkgs>' -A python2.pkgs.odfpy

nix-shell -p nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 1.11.16, channels(root): "nixos-17.09.2905.c1d9aff56e0", channels(plumps): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

My guess would be 6484eac5b2e38490724d9df3079e736605c7eeb6 missing in 17.09.

**Comment by FRidh** [comment]
```
nix-build -A python2.pkgs.odfpy -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/c1d9aff56e0ae52ee4705440fe09291a51e91977.tar.gz
/nix/store/y14x8861qg1asm44m5lc3vnahq8p3ija-python2.7-odfpy-1.3.6
```

**Comment by plumps** [comment]
Ah okay,

because 
```nix-build https://github.com/NixOS/nixpkgs/archive/c1d9aff56e0ae52ee4705440fe09291a51e91977.tar.gz -A python2.pkgs.odfpy```
leads to the very same build issue

**Comment by FRidh** [comment]
Yes, that's what I wanted to write. 

You are getting the same error? It does not try to fetch a binary substitute?

**Comment by plumps** [comment]
Nope, have a look at https://gist.github.com/plumps/ba9769430e10ab5570bd658549b6ff83.

It's my understanding hydra fails to build the very same nix expression.

**Comment by FRidh** [comment]
You are correct, Hydra reports build failures: https://hydra.nixos.org/build/67761002

Yet, when I select the git revision and build from it, I do get a successful build:
```
nix-build https://github.com/NixOS/nixpkgs/archive/0186286433cccbf6faf288c22df03e63e46dd94d.tar.gz  -A python2.pkgs.odfpy
```
It does build locally, so it would appear that the odd things are happening at *my* side.

**Comment by FRidh** [comment]
Commit 6484eac5b2e38490724d9df3079e736605c7eeb6 simply disables tests for 2.7. Reverting that patch on master still builds it on master for me.

**Comment by FRidh** [comment]
I've checked on two machines running 17.09 with `nixUnstable`. On both it builds fine. Hydra also runs 17.09 but with an even newer `nixUnstable`, `nix-2.0pre5889_c287d731`.

**Comment by plumps** [comment]
:relaxed:

**Comment by FRidh** [comment]
Seems like I'm the only one that is *not* encountering the issue.

I've pushed c6c57ef24a441dffca7dbc51e3f08411e9ff25c5 to `release-17.09`.
