### ISSUE TITLE
Build/launch failure: jcm-deepfilternet (easyeffects plugin)

### ISSUE THREAD

**Issue by why-not-try-calmer** [NixOS/nixpkgs#335551]
### Steps To Reproduce

1. sudo nixos-rebuild

### Build log

```
unpacking channels...
unpacking channels...
building Nix...
building the system configuration...
these 16 derivations will be built:
  /nix/store/kqwx4dqjag49hfvawi2jyjw1cil0yjcm-deepfilternet-0.5.6.drv
  /nix/store/jgd13cgyk7ldz71v7jnw8bi1fdrha9rf-easyeffects-7.1.7.drv
  /nix/store/1qypfs5cfrgkz7i73flxl4jmd29axl3y-home-manager-path.drv
  /nix/store/nn0610ksrrkw29z2hq56c344mdpiy0s2-activation-script.drv
  /nix/store/rgicrawdww4305xx4z2283zcaaaxzc5c-man-paths.drv
  /nix/store/9il4nzpsjdxkg3yym1b1jp95cbfwgnn7-man-cache.drv
  /nix/store/7kknvxr0pi6m9kgizk8lk6nni1ndn5ba-hm_.manpath.drv
  /nix/store/vrxn9rw3xp9c2ssc15zcpxphw3fxfzhl-easyeffects-7.1.7-fish-completions.drv
  /nix/store/i8n9njkl8vam2d86mv50g70y6nwa12af-ad-fish-completions.drv
  /nix/store/j4myvjyj4d0yd3a64qcmaisyl9lxaxjk-easyeffects.service.drv
  /nix/store/xl7nrwjdy4zyxndhassvx172lwvrjm4x-home-manager-files.drv
  /nix/store/4290wpiawmcfzmfa0am79rcp3n50pfc1-home-manager-generation.drv
  /nix/store/iir0799cf83fs7mf80cjr40sqqas2blg-unit-home-manager-ad.service.drv
  /nix/store/9f3d783w54mjd94g4awzzv5n3m52ywg0-system-units.drv
  /nix/store/vbpp6nl2pkjd61vg0shna7jim4swarhq-etc.drv
  /nix/store/1saybbi277snz3sgg0pbkg2z9klb5wmm-nixos-system-nixos-gnome-24.11pre666839.c3aa7b8938b1.drv
building '/nix/store/kqwx4dqjag49hfvawi2jyjw1cil0yjcm-deepfilternet-0.5.6.drv'...
Running phase: unpackPhase
unpacking source archive /nix/store/zjx7jxm12259mp6j9jpsaxa4zf9i64vk-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
Running phase: buildPhase
Executing cargoBuildHook
/build/source/ladspa /build/source
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc HOST_CXX=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --offline --profile release
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: /build/source/pyDF-data/Cargo.toml: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
(in the `pyo3` dependency)
   Compiling autocfg v1.1.0
   Compiling libm v0.2.7
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling memchr v2.5.0
   Compiling libc v0.2.147
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.47
   Compiling once_cell v1.18.0
   Compiling version_check v0.9.4
   Compiling ucd-trie v0.1.6
   Compiling serde v1.0.188
   Compiling either v1.9.0
   Compiling time-core v0.1.1
   Compiling regex-syntax v0.7.5
   Compiling syn v1.0.109
   Compiling time-macros v0.2.14
   Compiling itertools v0.10.5
   Compiling static_assertions v1.1.0
   Compiling deranged v0.3.8
   Compiling itoa v1.0.9
   Compiling ahash v0.7.6
   Compiling num-traits v0.2.16
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.4
   Compiling adler v1.0.2
   Compiling quote v1.0.33
   Compiling aho-corasick v1.0.4
   Compiling anymap2 v0.13.0
   Compiling syn v2.0.29
   Compiling cc v1.0.83
   Compiling getrandom v0.2.10
   Compiling doc-comment v0.3.3
   Compiling miniz_oxide v0.7.1
   Compiling matrixmultiply v0.3.7
   Compiling gimli v0.28.0
   Compiling unicode-segmentation v1.10.1
   Compiling tinyvec_macros v0.1.1
   Compiling percent-encoding v2.3.0
   Compiling tinyvec v1.6.0
   Compiling object v0.32.0
   Compiling time v0.3.28
   Compiling rustfft v6.1.0
   Compiling regex-automata v0.3.7
   Compiling same-file v1.0.6
   Compiling anyhow v1.0.75
   Compiling strength_reduce v0.2.4
   Compiling backtrace v0.3.69
   Compiling rustc-demangle v0.1.23
error[E0282]: type annotations needed for `Box<_>`
  --> /build/cargo-vendor-dir/time-0.3.28/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling rawpointer v0.2.1
   Compiling transpose v0.2.2
   Compiling unicode-normalization v0.1.22
   Compiling walkdir v2.3.3
   Compiling primal-check v0.3.3
   Compiling hashbrown v0.11.2
   Compiling half v2.2.1
   Compiling minimal-lexical v0.2.1
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: builder for '/nix/store/kqwx4dqjag49hfvawi2jyjw1cil0yjcm-deepfilternet-0.5.6.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/jgd13cgyk7ldz71v7jnw8bi1fdrha9rf-easyeffects-7.1.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vrxn9rw3xp9c2ssc15zcpxphw3fxfzhl-easyeffects-7.1.7-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j4myvjyj4d0yd3a64qcmaisyl9lxaxjk-easyeffects.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1qypfs5cfrgkz7i73flxl4jmd29axl3y-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rgicrawdww4305xx4z2283zcaaaxzc5c-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4290wpiawmcfzmfa0am79rcp3n50pfc1-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/iir0799cf83fs7mf80cjr40sqqas2blg-unit-home-manager-ad.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9f3d783w54mjd94g4awzzv5n3m52ywg0-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vbpp6nl2pkjd61vg0shna7jim4swarhq-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1saybbi277snz3sgg0pbkg2z9klb5wmm-nixos-system-nixos-gnome-24.11pre666839.c3aa7b8938b1.drv' failed to build
```

### Additional context

Using `nixos-unstable`. Last attempt just now.

### Notify maintainers

@ralismark @getchoo 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.4, NixOS, 24.11 (Vicuna), 24.11pre666839.c3aa7b8938b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"home-manager, nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by robert-elles** [comment]
I experience the same issue

**Comment by getchoo** [comment]
This should have been fixed in https://github.com/NixOS/nixpkgs/pull/334838, which hasn't made it to `nixos-unstable` yet. Could you try running this against latest `nixpkgs-unstable`?

**Comment by why-not-try-calmer** [comment]
Thanks @getchoo, I'm fairly sure that will fix it, else will reopen.

**Comment by jakob1379** [comment]
I still have this issue on ubuntu using nix+home-manager, manually pointing to the newest version of easyeffects fixes the issue:
```nix
services.easyeffects = {
      enable = true;
      package = pkgs.fetchFromGitHub {
      owner = "wwmm";
      repo = "easyeffects";
      rev = "v7.1.8";
      hash = "sha256-eDjtmr100WOCd0k0p3rUEtu6O9LlSGs43oaIXT07ikI=";
    };
```

**Comment by getchoo** [comment]
This seems like a different issue if easyeffects itself is failing to build (also thanks for tipping me off to the new release 😆)

**Comment by why-not-try-calmer** [comment]
It did work but now the service doesn't launch :(

[logs.txt](https://github.com/user-attachments/files/16686863/logs.txt)

**Comment by why-not-try-calmer** [comment]
Any news on that? The service still won't start on NixOS unstable.

**Comment by getchoo** [comment]
> It did work but now the service doesn't launch :( I did recursively reset the easyeffects' dconf keys, didn't help.
> 
> [logs.txt](https://github.com/user-attachments/files/16686863/logs.txt)

The logs are sadly not very useful, only containing `Failed to register: Unable to acquire bus name` errors over and over again. Perhaps you already have another instance of easyeffects running?

This also appears to be different from the original issue reported

**Comment by why-not-try-calmer** [comment]
Hum okay I had to kill `.easyeffects-wr` and then everything fixed itself. Is that a known culprit?

**Comment by getchoo** [comment]
> Is that a known culprit?

Running two processes that want to own a bus name is, yes
But I'm not really sure why another process was running in the background; that should not happen normally
