### ISSUE TITLE
Build failure: surrealdb-1.5.4

### ISSUE THREAD

**Issue by BridgerB** [NixOS/nixpkgs#336907]
### Steps To Reproduce

Attempt to build surrealdb version 1.5.4 on NixOS 24.11.
The build fails during the build phase.

### Build log

```
error: builder for '/nix/store/bnxga2xb1z0wvi3kadjs54ri0y53al6k-surrealdb-1.5.4.drv' failed with exit code 101;
       last 10 log lines:
       >    |
       > 83 |     let items: Box<_> = format_items
       >    |              ++++++++
       >
       >    Compiling crossbeam-deque v0.8.5
       >    Compiling headers v0.3.9
       >    Compiling proc-macro-crate v1.3.1
       > For more information about this error, try `rustc --explain E0282`.
       > error: could not compile `time` (lib) due to 1 previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/bnxga2xb1z0wvi3kadjs54ri0y53al6k-surrealdb-1.5.4.drv'.
```

### Notify maintainers

@sikmir

@r-ryantm

@happysalada

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.10.5-zen1, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source`
 ```

**Comment by BridgerB** [comment]
```
bridger@nixos:~/github/nix/ > nix log /nix/store/bnxga2xb1z0wvi3kadjs54ri0y53al6k-surrealdb-1.5.4.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/bnxga2xb1z0wvi3kadjs54ri0y53al6k-surrealdb-1.5.4.drv^*'
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/3jmlgr934a06l7sdpcphcrbhcxllvwpd-source
source root is source
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/6acfp565ngfl4k9h1gpa0pwyphn1gf9i-surrealdb-1.5.4-vendor.tar.gz
Finished cargoSetupPostUnpackHook
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/surrealdb-1.5.4-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/lbk30k56awz9vz9qpid93fkjns0xwlhd-gcc-wrapper-13.3.0/bin/c++ CARG>
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/build/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling autocfg v1.2.0
   Compiling libc v0.2.153
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling serde v1.0.197
   Compiling once_cell v1.19.0
   Compiling pin-project-lite v0.2.14
   Compiling memchr v2.7.2
   Compiling futures-core v0.3.30
   Compiling bytes v1.6.0
   Compiling scopeguard v1.2.0
   Compiling log v0.4.21
   Compiling libm v0.2.8
   Compiling itoa v1.0.11
   Compiling zerocopy v0.7.32
   Compiling allocator-api2 v0.2.16
   Compiling typenum v1.17.0
   Compiling ahash v0.8.11
   Compiling lock_api v0.4.11
   Compiling num-traits v0.2.18
   Compiling slab v0.4.9
   Compiling generic-array v0.14.7
   Compiling futures-sink v0.3.30
   Compiling quote v1.0.35
   Compiling byteorder v1.5.0
   Compiling aho-corasick v1.1.3
   Compiling syn v2.0.58
   Compiling either v1.10.0
   Compiling jobserver v0.1.28
   Compiling regex-syntax v0.8.3
   Compiling futures-io v0.3.30
   Compiling pin-utils v0.1.0
   Compiling spin v0.9.8
   Compiling futures-channel v0.3.30
   Compiling fnv v1.0.7
   Compiling futures-task v0.3.30
   Compiling smallvec v1.13.2
   Compiling cc v1.0.92
   Compiling thiserror v1.0.58
   Compiling tracing-core v0.1.32
   Compiling parking_lot_core v0.9.9
   Compiling glob v0.3.1
   Compiling equivalent v1.0.1
   Compiling prettyplease v0.2.17
   Compiling crossbeam-utils v0.8.19
   Compiling subtle v2.5.0
   Compiling http v0.2.12
   Compiling pkg-config v0.3.30
   Compiling clang-sys v1.7.0
   Compiling getrandom v0.2.14
   Compiling num_cpus v1.16.0
   Compiling rand_core v0.6.4
   Compiling signal-hook-registry v1.4.1
   Compiling mio v0.8.11
   Compiling socket2 v0.5.6
   Compiling crypto-common v0.1.6
   Compiling minimal-lexical v0.2.1
   Compiling ppv-lite86 v0.2.17
   Compiling block-buffer v0.10.4
   Compiling nom v7.1.3
   Compiling libloading v0.8.3
   Compiling rand_chacha v0.3.1
   Compiling digest v0.10.7
   Compiling syn v1.0.109
   Compiling lazycell v1.3.0
   Compiling lazy_static v1.4.0
   Compiling rand v0.8.5
   Compiling shlex v1.3.0
   Compiling ring v0.17.8
   Compiling regex-automata v0.4.6
   Compiling peeking_take_while v0.1.2
   Compiling percent-encoding v2.3.1
   Compiling tinyvec_macros v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling tinyvec v1.6.0
   Compiling untrusted v0.9.0
   Compiling ryu v1.0.17
   Compiling httparse v1.8.0
   Compiling semver v1.0.22
   Compiling rustix v0.38.32
   Compiling indexmap v1.9.3
   Compiling rustls v0.21.11
   Compiling tower-service v0.3.2
   Compiling cpufeatures v0.2.12
   Compiling serde_json v1.0.115
   Compiling linux-raw-sys v0.4.13
   Compiling bitflags v2.5.0
   Compiling form_urlencoded v1.2.1
   Compiling unicode-normalization v0.1.23
   Compiling http-body v0.4.6
   Compiling ident_case v1.0.1
   Compiling base64 v0.21.7
   Compiling bindgen v0.66.1
   Compiling async-trait v0.1.79
   Compiling home v0.5.9
   Compiling cexpr v0.6.0
   Compiling hashbrown v0.14.5
   Compiling hashbrown v0.12.3
   Compiling zstd-sys v2.0.10+zstd.1.5.6
   Compiling unicode-bidi v0.3.15
   Compiling regex v1.10.4
   Compiling indexmap v2.2.6
   Compiling try-lock v0.2.5
   Compiling httpdate v1.0.3
   Compiling want v0.3.1
   Compiling idna v0.5.0
   Compiling unicase v2.7.0
   Compiling strsim v0.10.0
   Compiling mime v0.3.17
   Compiling rustc_version v0.4.0
   Compiling which v4.4.2
   Compiling url v2.5.0
   Compiling darling_core v0.20.8
   Compiling dirs-sys-next v0.1.2
   Compiling stable_deref_trait v1.2.0
   Compiling crunchy v0.2.2
   Compiling rustversion v1.0.15
   Compiling dirs-next v2.0.0
   Compiling heapless v0.7.17
   Compiling sha1 v0.10.6
   Compiling serde_derive v1.0.197
   Compiling tokio-macros v2.2.0
   Compiling futures-macro v0.3.30
   Compiling thiserror-impl v1.0.58
   Compiling tracing-attributes v0.1.27
   Compiling tokio v1.37.0
   Compiling futures-util v0.3.30
   Compiling darling_macro v0.20.8
   Compiling pin-project-internal v1.1.5
   Compiling tracing v0.1.40
   Compiling tiny-keccak v2.0.2
   Compiling heapless v0.8.0
   Compiling siphasher v0.3.11
   Compiling darling v0.20.8
   Compiling phf_shared v0.10.0
   Compiling parking_lot v0.12.1
   Compiling term v0.7.0
   Compiling hash32 v0.2.1
   Compiling pin-project v1.1.5
   Compiling hash32 v0.3.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling same-file v1.0.6
   Compiling bit-vec v0.6.3
   Compiling precomputed-hash v0.1.1
   Compiling new_debug_unreachable v1.0.6
   Compiling fixedbitset v0.4.2
   Compiling urlencoding v2.1.3
   Compiling unicode-width v0.1.11
   Compiling webpki-roots v0.25.4
   Compiling petgraph v0.6.4
   Compiling bit-set v0.5.3
   Compiling string_cache v0.8.7
   Compiling futures-executor v0.3.30
   Compiling walkdir v2.5.0
   Compiling ascii-canvas v3.0.0
   Compiling lalrpop-util v0.20.2
   Compiling itertools v0.11.0
   Compiling tokio-util v0.7.10
   Compiling psm v0.1.21
   Compiling num-integer v0.1.46
   Compiling ena v0.14.2
   Compiling proc-macro-error v1.0.4
   Compiling crc32fast v1.4.0
   Compiling bindgen v0.65.1
   Compiling vcpkg v0.2.15
   Compiling alloc-no-stdlib v2.0.4
   Compiling unicode-xid v0.2.4
   Compiling sync_wrapper v0.1.2
   Compiling zstd-safe v7.1.0
   Compiling pico-args v0.5.0
   Compiling alloc-stdlib v0.2.2
   Compiling rquickjs-sys v0.5.1
   Compiling rstar v0.11.0
   Compiling rstar v0.12.0
   Compiling libz-sys v1.1.16
   Compiling rustls-webpki v0.101.7
   Compiling sct v0.7.1
   Compiling lalrpop v0.20.2
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling stacker v0.1.15
   Compiling lz4-sys v1.9.4
   Compiling serde_urlencoded v0.7.1
   Compiling concurrent-queue v2.4.0
   Compiling inout v0.1.3
   Compiling approx v0.5.1
   Compiling robust v1.1.0
   Compiling adler v1.0.2
   Compiling paste v1.0.14
   Compiling heck v0.4.1
   Compiling utf-8 v0.7.6
   Compiling arbitrary v1.3.2
   Compiling data-encoding v2.5.0
   Compiling tower-layer v0.3.2
   Compiling bitflags v1.3.2
   Compiling dashmap v5.5.3
   Compiling miniz_oxide v0.7.2
   Compiling cipher v0.4.4
   Compiling h2 v0.3.26
   Compiling geo-types v0.7.13
   Compiling tokio-rustls v0.24.1
   Compiling tungstenite v0.20.1
   Compiling earcutr v0.4.3
   Compiling brotli-decompressor v3.0.0
   Compiling axum-core v0.3.4
   Compiling serde_with_macros v3.7.0
   Compiling miette-derive v5.10.0
   Compiling hyper v0.14.28
   Compiling itertools v0.10.5
   Compiling geographiclib-rs v0.2.4
   Compiling matrixmultiply v0.3.8
   Compiling num-bigint v0.4.4
   Compiling time-core v0.1.2
   Compiling winnow v0.5.40
   Compiling powerfmt v0.2.0
   Compiling anyhow v1.0.81
   Compiling float_next_after v1.0.0
   Compiling toml_datetime v0.6.5
   Compiling parking v2.2.0
   Compiling event-listener v2.5.3
   Compiling ipnet v2.9.0
   Compiling num-conv v0.1.0
   Compiling base64ct v1.6.0
   Compiling doc-comment v0.3.3
   Compiling time-macros v0.2.17
   Compiling password-hash v0.5.0
   Compiling event-listener v4.0.3
   Compiling deranged v0.3.11
   Compiling rustc_lexer v0.1.0
   Compiling librocksdb-sys v0.11.0+8.1.1
   Compiling miette v5.10.0
   Compiling serde_with v3.7.0
   Compiling toml_edit v0.19.15
   Compiling brotli v4.0.0
   Compiling flate2 v1.0.28
   Compiling mime_guess v2.0.4
   Compiling tokio-tungstenite v0.20.1
   Compiling tower v0.4.13
   Compiling smol_str v0.2.1
   Compiling tokio-stream v0.1.15
   Compiling futures v0.3.30
   Compiling axum v0.6.20
   Compiling ring v0.16.20
   Compiling crossbeam-epoch v0.9.18
   Compiling headers-core v0.2.0
   Compiling thread_local v1.1.8
   Compiling relative-path v1.9.2
   Compiling rawpointer v0.2.1
   Compiling fastrand v2.0.2
   Compiling iana-time-zone v0.1.60
   Compiling rayon-core v1.12.1
   Compiling unicode-segmentation v1.11.0
   Compiling rust_decimal v1.35.0
   Compiling unicode-script v0.5.6
   Compiling bitmaps v3.2.1
   Compiling ref-cast v1.0.22
   Compiling atomic v0.5.3
   Compiling convert_case v0.6.0
   Compiling unicode-security v0.1.1
   Compiling uuid v1.8.0
   Compiling time v0.3.34
   Compiling chrono v0.4.37
   Compiling imbl-sized-chunks v0.1.2
   Compiling rquickjs-core v0.5.1
error[E0282]: type annotations needed for `Box<_>`
  --> /build/surrealdb-1.5.4-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

   Compiling crossbeam-deque v0.8.5
   Compiling headers v0.3.9
   Compiling proc-macro-crate v1.3.1
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by dotlambda** [comment]
see #332957

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/336144

**Comment by BridgerB** [comment]
@dotlambda I just successfully rebuilt using nixos-unstable.

Surrealist is still broken with the same error.
