### ISSUE TITLE
Build failure: freecad-0.21.2

### ISSUE THREAD

**Issue by sgrb** [NixOS/nixpkgs#343250]
### Steps To Reproduce

```nix shell github:nixos/nixpkgs/99dc8785f6a0adac95f5e2ab05cc2e1bf666d172#legacyPackages.x86_64-linux.freecad```

### Build log

```
error: hash mismatch in fixed-output derivation '/nix/store/cryjqhbbc9kp0l9bil1pbxm7knc244vl-source.drv':
         specified: sha256-EeLfIu+InGy56zqjhbNle4hPjQmzwqzHA4ODBMjb9kg=
            got:    sha256-dUFmcUOdNc3ZFtr+Hnh3Q3OY/JA/WxmiRJiU2RFSSus=
error: 1 dependencies of derivation '/nix/store/m80qyciqxqy64g4vv2nb7ms9frvw5ggr-coin-4.0.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wfma13lqsf97jllarksks70vn9gwkz2b-freecad-0.21.2.drv' failed to build

```

### Notify maintainers
@gebner @AndersonTorres 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.51, NixOS, 24.11 (Vicuna), 24.11.20240916.99dc878`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `""`
 - channels(slava): `""`
 - nixpkgs: `/etc/nix/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by 5chmidti** [comment]
Should be fixed by #342221

**Comment by zoriya** [comment]
This patch is already merged into unstable but I still have the build issue, is there something needed for it to reflect?

**Comment by ViaoV** [comment]
If you're using a flake based config:

```
nix flake update
nixos-rebuild
```
got it installed for me
