### ISSUE TITLE
libpsl cannot be cross-compiled on netbsd

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#344423]
### Describe the bug

Because we cannot cross-compile python and libpsl depends on python,
we cannot cross-compile nix to netbsd.

Until this is fixed, we will disable netbsd cross-compilation in the nix package manager repository.

Context: https://github.com/NixOS/nixpkgs/pull/344211

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/350833 This issue should be fixed on staging!

**Comment by Mic92** [comment]
https://nixpk.gs/pr-tracker.html?pr=350833

**Comment by srd424** [comment]
OOI, https://github.com/NixOS/nix/blob/aa9d7cdc4a913fc4ced56af5f12cfffbed5141d7/flake.nix#L52-L53 still shows the netbsd as disabled - is it possible to re-enable?
