### ISSUE TITLE
Build failure: dkjson

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#345965]
Seeing a dkjson hash mismatch again.   
This tar.gz URL isn't linked on dkolf.de/dkjson-lua/ 's main page at all, only a single .lua file.
Looks like the lone .lua file version hasn't changed since it was uploaded in June, if the ETag / modified headers can be believed.

### Steps To Reproduce

1. build dkjson 2.8

### Build log

```
┃ error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
┃         likely URL: http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz
┃          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
┃             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
┣━ 1 Traces: -
```

Related: #334395 #334775

cc @teto @GaetanLepage 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Ate329** [comment]
Just got the same issue
```shell
error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
         specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
            got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
error: 1 dependencies of derivation '/nix/store/86q933a9bmx1j2g1jg54vc7kha56y0b7-luajit2.1-dkjson-2.8-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z3q6mngf9c1k38jfbx31p3bqq9jnpris-luajit2.1-lua-lsp-0.1.0-2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6cpjpqa71ilqg8pwds1rpgy7455x6xfk-neovim-0.10.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/awda6q5jgjg4i5ka95xb3cx29jriygn5-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/17bhjhqg4npvzgdyx59g7qrmrsyslp1y-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/41zr82p1p7q3bsngrxnq9bn3iz5pgfbc-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/crv1gvdirj03819snnwbiq5bwlw8p9kf-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9aigyxf3qvnyv70ljh98iv26p619nc9s-nixos-system-nixos-24.11.20241001.27e30d1.drv' failed to build
┏━ 1 Errors: 
┃ error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
┃          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
┃             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
```

**Comment by LunNova** [comment]
Noting upstream is served over HTTP and at extra risk of MitM, not too great if we end up blindly updating the hash repeatedly :/

**Comment by PlasmaShift** [comment]
I am also having this isssue

```nix
dkjson-2.8.tar.gz> 100 17442  100 17442    0     0  14862      0  0:00:01  0:00:01 --:--:-- 14869
error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c49771jmrva-dkjson-2.8.tar.gz.drv':
         specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
            got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
error: 1 dependencies of derivation '/nix/store/86q933a9bmx1j2g1jg54vc7kha56y0b7-luajit2.1-dkjson-2.8-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z3q6mngf9c1k38jfbx31p3bqq9jnpris-luajit2.1-lua-lsp-0.1.0-2.drv' failed to build
copying path '/nix/store/ggmvjwbxpw9hg2ap7r53dqvv9h8pr42d-nixos-render-docs-0.0' from 'https://cache.nixos.org'
error: 1 dependencies of derivation '/nix/store/cpwddikkabjp6ldabzh1yd16spm4zwn4-neovim-0.10.1.drv' failed to build
copying path '/nix/store/b9czbq78g8ng05ysfvwfs3gklzxp5qnk-python3.12-pygobject-3.48.2' from 'https://cache.nixos.org'
error: 1 dependencies of derivation '/nix/store/86j4v6avgmphx0wpkn4y810l0fphjdv0-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sn9yqhszs33cpd75qd2yb07i6n6mmnr7-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/npg7p1h1bgirgm72rz3abmsif3yqrp6n-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/h9hjwdx3k1kr5bvmdb4zbiwpnjal2npx-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/965yqzqin4s0gx3m8g08cl158vvi6kwc-nixos-system-DragonDesktop-24.11.20241001.27e30d1.drv' failed to build








┏━ 1 Errors: 
┃ error: hash mismatch in fixed-output derivation '/nix/store/xldxkrh87vnxpdm3si720c…
┃          specified: sha256-CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=
┃             got:    sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=
┣━ Dependency Graph:
```

**Comment by kira-bruneau** [comment]
It looks like this was fixed in #345767, but it will come back again the next time the luarocks package updater is executed. It keeps resetting it back to the broken hash.

**Comment by Thiago-Assis-T** [comment]
> It looks like this was fixed in #345767, but it will come back again the next time the luarocks package updater is executed. It keeps resetting it back to the broken hash.
> 
> I don't think we should close this issue until it's fixed in the updater.

why does this happen? why it resets to the broken hash, i've had problems with dkjson a couple of times, but still don't understand why...

**Comment by kira-bruneau** [comment]
I'm not 100% sure why yet, but I traced the problem to the output of `luarocks nix`: https://github.com/nix-community/luarocks-nix

**Comment by kira-bruneau** [comment]
I've collected all the PRs that had to manually fix the hash in the past:
- [#306080](https://github.com/NixOS/nixpkgs/pull/306080/commits/b9a7c64a9e3f8e1111e5418505ad58b499dba8e6)
- [#322274](https://github.com/NixOS/nixpkgs/pull/322274/commits/f560e20cb6c677d17920593faf955314c58c4bcd)
- [#333779](https://github.com/NixOS/nixpkgs/pull/333779/commits/0c2db3c06f09434ea697963ee78e08d5ebfac0a0)
- [#345767](https://github.com/NixOS/nixpkgs/pull/345767/commits/947b3a56478e8fa151c1786079bd00beabaf8822)

**Comment by kira-bruneau** [comment]
And here's how to reproduce the command that produces the broken hashes:

```shell
nix run nixpkgs#luaPackages.luarocks-nix -- nix dkjson
```

```nix
{ buildLuarocksPackage, fetchurl, luaAtLeast, luaOlder }:
buildLuarocksPackage {
  pname = "dkjson";
  version = "2.8-1";
  knownRockspec = (fetchurl {
    url    = "mirror://luarocks/dkjson-2.8-1.rockspec";
    sha256 = "060410qpbsvmw2kwbkwh5ivcpnqqcbmcj4dxhf8hvjgvwljsrdka";
  }).outPath;
  src = fetchurl {
    url    = "http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz";
    sha256 = "0js9z5ja3ws1i9gj2m673459rwm0gadxbf86mcif7d8286h61yh9";
  };

  disabled = luaOlder "5.1" || luaAtLeast "5.5";

  meta = {
    homepage = "http://dkolf.de/dkjson-lua/";
    description = "David Kolf's JSON module for Lua";
    license.fullName = "MIT/X11";
  }
```

**Comment by kira-bruneau** [comment]
Ok, weird... the difference seems to be between using `pkgs.fetchurl` and `builtins.fetchurl`:

```nix
pkgs.fetchurl {
  url = "http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz";
  # hash = "sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=";
  sha256 = "0chmlcv8498n313x19aampwvz2s1pp4zpcvvxdhwihcixcxwvs14";
}

builtins.fetchurl {
  url = "http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz";
  sha256 = "0js9z5ja3ws1i9gj2m673459rwm0gadxbf86mcif7d8286h61yh9";
}
```

**Comment by khaneliman** [comment]
Looks like luarocks-nix is fetching hash using [nix-prefetch-url](https://github.com/nix-community/luarocks-nix/blob/9d0440da358eac11afdbef392e2cf3272a8c7101/src/luarocks/cmd/nix.lua#L100) which gives me that builtins.fetchurl hash. 

```bash
nix-prefetch-url http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz --type sha256
path is '/nix/store/6nm14d7995c8la0fbza855azwij2s0q8-dkjson-2.8.tar.gz'
0js9z5ja3ws1i9gj2m673459rwm0gadxbf86mcif7d8286h61yh9
```

**Comment by RVxLab** [comment]
Is there a way one could fix this locally using an overlay until a proper fix lands?

I'm attempting to do just that but my experience in writing overlays and derivations are sadly lacking.

**Comment by khaneliman** [comment]
> Is there a way one could fix this locally using an overlay until a proper fix lands?
> 
> I'm attempting to do just that but my experience in writing overlays and derivations are sadly lacking.

The hash should be proper in nixpkgs, right now.

**Comment by RVxLab** [comment]
> The hash should be proper in nixpkgs, right now.

Ah, sweet!

> Or do you mean to prevent accidental breakage?

Pretty much that. Looking at past issues this wasn't the first time this happened, nor do I think it'll be the last. So as an interim solution I just want to create an overlay where I can temporarily fix it myself should this happen again, though with how quickly you guys tend to be with these things it may not be needed.

**Comment by khaneliman** [comment]
I didn't test it, but it would be something like this to ensure it is pinned:

```nix
  luaPackages = prev.luaPackages // {
    dkjson = prev.luaPackages.dkjson.overrideAttrs {
      knownRockspec = (fetchurl {
        url    = "mirror://luarocks/dkjson-2.8-1.rockspec";
        hash = "sha256-arasJeX7yQ2Rg70RyepiGNvLdiyQz8Wn4HXrdTEIBBg=";
      }).outPath;
      src = fetchurl {
        url    = "http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz";
        hash = "sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI=";
      };
    };
  };

**Comment by teto** [comment]
(The snippet above changes the default lua package set, if you are using the lua51Packages or luajit, you will have to do it for those as well, the nixpkgs doc also mention how to use "packageOverrides")

**Comment by dhkolf** [comment]
I noticed that I got the hash from the original report (`CfpgoEECteMiqwa51Zt6oPKcChnHVCFfikHzoWT5SUs=`) when I `gunzip` the dkjson-2.8.tar.gz file and take the hash from the uncompressed tar-archive. In case the unzipping is always applied, it should still be reproducible.

**Comment by GraysonTinker** [comment]
Now working: https://hydra.nixos.org/build/336943384
