### ISSUE TITLE
gpu-screen-recorder: fails to record

### ISSUE THREAD

**Issue by keenanweaver** [NixOS/nixpkgs#349648]
### Describe the bug

gpu-screen-recorder after latest bump/module change does not record.

### Steps To Reproduce
1. Enable gpu-screen-recorder module. `programs.gpu-screen-recorder.enable = true;`
2. Run a command like: `gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -k av1 -o ~/Videos`
3. See error that program is not in PATH.
4. Add `gpu-screen-recorder` to `environment.systemPackages`, rebuild
5. Run command again and see:

```
┌───────────────────>
│keenan in ~
❌255 ❄️ zsh ›
└─>gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -k av1 -o /home/keenan/Videos
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
gsr error: gsr_kms_client_init: gsr-kms-server is not installed (/nix/store/pw1kisi5r82ck96f46lqggbxlvklarmm-gpu-screen-recorder-4.2.1/bin/.wrapped/gsr-kms-server not found)
gsr error: gsr_capture_start failed
```
### Expected behavior

Should start recording.

### Screenshots

![image](https://github.com/user-attachments/assets/582b4b87-9167-480e-ac22-569f86edc384)

### Additional context

I didn't see this behavior in testing the changes, so I must've done something wrong.

### Notify maintainers
@DontEatOreo
@dec05eba (tagging for GSR knowledge)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.3, NixOS, 24.11 (Vicuna), 24.11.20241016.5785b6b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.9`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/w7nfn4lcfisddz14b0y8n05rjf0dl5lq-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dec05eba** [comment]
I see. In other distros the gpu-screen-recorder binary and gsr-kms-server binary are in the same directory. This error happens when they are not. Maybe this can be solved in the nix package, but I can make it fallback to PATH environment variable if not found there.

**Comment by keenanweaver** [comment]
> I see. In other distros the gpu-screen-recorder binary and gsr-kms-server binary are in the same directory. This error happens when they are not. Maybe this can be solved in the nix package, but I can make it fallback to PATH environment variable if not found there.

It may simply just be adding another wrapper to the postInstall portion, like here: https://github.com/NixOS/nixpkgs/blob/5785b6bb5eaae44e627d541023034e1601455827/pkgs/applications/video/gpu-screen-recorder/default.nix#L73

**Comment by dec05eba** [comment]
Oh ok nice, that could be used. I fixed it also in the gpu-screen-recorder source code, to make it fallback to PATH if not found in the same directory (released version 4.2.3 with the change).

**Comment by keenanweaver** [comment]
Adding this to the postInstall does allow recording to happen again.

``` nix
    makeWrapper "$out/bin/.wrapped/gsr-kms-server" "$out/bin/gsr-kms-server" \
      --prefix LD_LIBRARY_PATH : "${
        lib.makeLibraryPath [
          libglvnd
          addDriverRunpath.driverLink
        ]
      }" \
      --prefix PATH : "${wrapperDir}" \
      --suffix PATH : "$out/bin"
```

But I am still seeing an issue with `gpu-screen-recorder` not being on the path by default. (I'm assuming something in the module needs to change). The sys_admin cap isn't applying now as well. Maybe it can't be wrapped?

```
┌───────────────────>
│keenan in ~
❄️ zsh ›
└─>gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -fm cfr -k av1 -ac opus -r 90 -v no -a DAC/alsa_output.usb-Schiit_Audio_Schiit_Modi_-00.analog-stereo.monitor -a Game/Game.monitor -a mono-microphone -a Voice/Voice.monitor -a Music/Music.monitor -o /home/keenan/Videos
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
gsr info: gsr_kms_client_init: setting up connection to /nix/store/h23zhb5wr4imzkn1myk7178sk3pah4q0-gpu-screen-recorder-4.2.1/bin/.wrapped/gsr-kms-server
gsr info: gsr_kms_client_init: gsr-kms-server is missing sys_admin cap and will require root authentication. To bypass this automatically, run: sudo setcap cap_sys_admin+ep '/nix/store/h23zhb5wr4imzkn1myk7178sk3pah4q0-gpu-screen-recorder-4.2.1/bin/.wrapped/gsr-kms-server'
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[av1_vaapi @ 0x365b9f40] ignoring invalid SAR: 0/0
```

**Comment by dec05eba** [comment]
I guess it cant be wrapped, as getcap is run on the wrapper and the wrapper itself doesn't have the capability set. An update to version 4.2.3 is needed to fix it in a nice way I guess.

**Comment by keenanweaver** [comment]
Yep, we're good now on 4.2.3. I'll get a PR opened up. Thanks for responding so quickly!

```
┌───────────────────>
│keenan in ~
❄️ zsh ›
└─>gpu-screen-recorder -w DP-1 -c mkv -q ultra -f 60 -fm cfr -k av1 -ac opus -r 90 -v no -a DAC/alsa_output.usb-Schiit_Audio_Schiit_Modi_-00.analog-stereo.monitor -a Game/Game.monitor -a mono-microphone -a Voice/Voice.monitor -a Music/Music.monitor -o /home/keenan/Videos
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
gsr info: gsr_kms_client_init: gsr-kms-server is not installed in the same directory as gpu-screen-recorder (/nix/store/zb48miplkrs59cv732ixkrx1rwhhf8ra-gpu-screen-recorder-4.2.3/bin/.wrapped/gsr-kms-server not found), looking for gsr-kms-server in PATH instead
gsr info: gsr_kms_client_init: setting up connection to /run/wrappers/bin/gsr-kms-server
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[av1_vaapi @ 0x23efd840] ignoring invalid SAR: 0/0
/home/keenan/Videos/Replay_2024-10-18_18-57-08.mkv
```

My
