### ISSUE TITLE
qt6ct custom palette not being applied in dolphin

### ISSUE THREAD

**Issue by zspher** [NixOS/nixpkgs#355602]
### Describe the bug

the qt6ct custom palette is not being applied in dolphin; just the default theme is applied.

### Steps To Reproduce

1. pick `windows` style in qt6ct
2. select `darker` as the colorscheme
3. apply

### Expected behavior

the selected color palette should be applied

### Screenshots

![Screenshot_2024-11-12-23-52-28](https://github.com/user-attachments/assets/d444c2c6-a340-4b6c-a12f-db1aa557ce7d)

### Additional context

- on qbitorrent qt6 the custom palette works
- i have tried setting the kde colorscheme in `~/.config/kdeglobals` but that does not work for dolphin
  - on kdeconnect settings the kdeglobals solution works
- might be relevant: https://github.com/prasanthrangan/hyprdots/issues/1843

### Notify maintainers

@Scrumplex
@Flakebi 

@K900 

### Metadata

Please insert the output of running `nix-shell -p nix-info --run "nix-info -m"` below this line

```sh
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 6.11.7, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Lix, like Nix) 2.91.1
- nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Scrumplex** [comment]
It seems to be working fine for me. Is it possible that some random configuration is causing this?

**Comment by Gliczy** [comment]
It's working fine for me as well. Could you share the relevant config?
Also, to be sure, could you check that you are using `pkgs.kdePackages.dolphin` and *not* `libsForQt5.dolphin`?

**Comment by zspher** [comment]
yup, im using `kdePackages.dolphin`

ive used plasma6 setting to set dolphin themes but that still does not work
the color theme only uses the default breeze theme
also when i set via qt6ct the theme is applied and the removed on new dolphin startup


https://github.com/user-attachments/assets/263be426-d683-4f2c-9dff-43cf1c140b4f


```nix
  theme.catppuccin.kde.enable = true;
  qt = {
    enable = true;
    style.package = with pkgs; [
      lightly-boehs
      self.packages.${pkgs.system}.lightly-qt6
    ];
    platformTheme.name = "qtct";
    kde.settings.kdeglobals.General.TerminalApplication = "kitty";
    kde.settings.kdeglobals.Icons.Theme = config.gtk.iconTheme.name;
  };
  home.packages = with pkgs.kdePackages; [
    dolphin
    # https://invent.kde.org/frameworks/kimageformats
    kimageformats # avif, xcf, jxl
    # https://apps.kde.org/kdegraphics_thumbnailers/
    kdegraphics-thumbnailers # PS, PDF, RAW, mobi, blender
    ffmpegthumbs # video thumbnails
    qtimageformats # for webp thumbnails
  ];

```

**Comment by zspher** [comment]
fixed with https://github.com/prasanthrangan/hyprdots/pull/1999

added the ff. to `~/.config/dolphinrc`

```
[UiSettings]
ColorScheme=*
```

**Comment by TRPB** [comment]
that works for the fonts but the icons are still incorrect like the screenshot in https://github.com/prasanthrangan/hyprdots/pull/1999 for me 

It feels like a cache issue but doesn't seem to be that
