### ISSUE TITLE
Bambu Studio / OrcaSlicer cannot find printers on local network

### ISSUE THREAD

**Issue by MdotAmaan** [NixOS/nixpkgs#355821]
## Steps To Reproduce

1. Install Orcaslicer / Bambustudio from nixpkgs
2. Set Bambu printer to LAN only
3. Attempt to add the printer to the slicer

## Expected behavior

The printer should show up under "Other Device"

## Additional context

This appears to be due to the firewall. [Here's a list of the ports the Bambu printers need](https://wiki.bambulab.com/en/general/printer-network-ports). Adding this to my nix config appears to solve the problem
```
    networking.firewall.extraCommands = ''
    iptables -I INPUT -m pkttype --pkt-type multicast -j ACCEPT
    iptables -A INPUT -m pkttype --pkt-type multicast -j ACCEPT
    iptables -I INPUT -p udp -m udp --match multiport --dports 1990,2021 -j ACCEPT
    '';
```
## Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.59, NixOS, 24.11 (Vicuna), 24.11.20241109.76612b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/0sxsfzswhjck7f4sbsvznz285s4i7y64-source`
```
## Notify maintainers

@zhaofengli @pinpox  

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by pinpox** [comment]
If opening ports resolves this issue, it is not a bug with this package but rather your configuration. 

Closing this, as I can't do anything in the package to fix this. Feel free to re-open if you disagree or have any pointers on how to improve this.

**Comment by MdotAmaan** [comment]
I'm not very well versed with nix yet, but couldn't something similar to the [Sunshine](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/nixos/modules/services/networking/sunshine.nix) package be done, where there's an "openFirewall" config option?

**Comment by MdotAmaan** [comment]
I don't think I'm able to re-open issues, but #362630 should resolve this.

**Comment by gomarworks** [comment]
The firewall fix still makes orcaslicer crash on my machine when connecting to the web interface of my ratrig running klipper.
It seems a longstanding issue for me on multiple versions of orcaslicer.

OS: NixOS 24.11.20250126.4e96537 (Vicuna)
Kernel: 6.6.72

**Comment by mwlaboratories** [comment]
I tried out that fix but orca still crashes when trying to get to the ratrig mainsail interface. Tried a lot of versions, I'm on unstable right now.
