### ISSUE TITLE
Build failure: calibre

### ISSUE THREAD

**Issue by nipsy** [NixOS/nixpkgs#356556]
## Steps To Reproduce

1.Add calibre from current unstable to system flake.
2. nixos-rebuild.

## Build log

```
error: builder for '/nix/store/xyjf2iypjc6sml5ik342mxvglv3sxl9q-calibre-7.20.0.drv' failed with exit code 1;
       last 25 log lines:
       > test_podofo (calibre.test_build.BuildTest.test_podofo) ... ok [0.0 s]
       > test_psutil (calibre.test_build.BuildTest.test_psutil) ... ok [0.0 s]
       > test_pychm (calibre.test_build.BuildTest.test_pychm) ... ok [0.0 s]
       > test_pycryptodome (calibre.test_build.BuildTest.test_pycryptodome) ... ok [0.0 s]
       > test_regex (calibre.test_build.BuildTest.test_regex) ... ok [0.0 s]
       > test_speech_dispatcher (calibre.test_build.BuildTest.test_speech_dispatcher) ... ok [0.0 s]
       > test_sqlite (calibre.test_build.BuildTest.test_sqlite) ... ok [0.0 s]
       > test_terminal (calibre.test_build.BuildTest.test_terminal) ... ok [0.0 s]
       > test_tinycss_tokenizer (calibre.test_build.BuildTest.test_tinycss_tokenizer) ... ok [0.0 s]
       > test_winutil (calibre.test_build.BuildTest.test_winutil) ... skipped 'winutil is windows only' [0.0 s]
       > test_wpd (calibre.test_build.BuildTest.test_wpd) ... skipped 'WPD is windows only' [0.0 s]
       > test_zeroconf (calibre.test_build.BuildTest.test_zeroconf) ... ok [0.1 s]
       >
       > ======================================================================
       > FAIL: test_imaging (calibre.test_build.BuildTest.test_imaging)
       > ----------------------------------------------------------------------
       > Traceback (most recent call last):
       >   File "/build/calibre-7.20.0/src/calibre/test_build.py", line 449, in test_imaging
       >     self.assertIn(line.strip(), out)
       > AssertionError: '--- WEBP Transparency support ok' not found in '--------------------------------------------------------------------\nPillow 11.0.0\nPython 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0]\n--------------------------------------------------------------------\nPython executable is /nix/store/jf0krwdycq55cfzqmn8rwbawxnwd7nz6-python3-3.12.7-env/bin/python3.12\nEnvironment Python files loaded from /nix/store/jf0krwdycq55cfzqmn8rwbawxnwd7nz6-python3-3.12.7-env\nSystem Python files loaded from /nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7\n--------------------------------------------------------------------\nPython Pillow modules loaded from /nix/store/jf0krwdycq55cfzqmn8rwbawxnwd7nz6-python3-3.12.7-env/lib/python3.12/site-packages/PIL\nBinary Pillow modules loaded from /nix/store/jf0krwdycq55cfzqmn8rwbawxnwd7nz6-python3-3.12.7-env/lib/python3.12/site-packages/PIL\n--------------------------------------------------------------------\n--- PIL CORE support ok, compiled for 11.0.0\n*** TKINTER support not installed\n--- FREETYPE2 support ok, loaded 2.13.3\n--- LITTLECMS2 support ok, loaded 2.16\n--- WEBP support ok, loaded 1.4.0\n--- JPEG support ok, compiled for libjpeg-turbo 3.0.4\n--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2\n--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1\n--- LIBTIFF support ok, loaded 4.7.0\n--- RAQM (Bidirectional Text) support ok, loaded 0.10.2\n--- LIBIMAGEQUANT (Quantization method) support ok, loaded 4.2.2\n--- XCB (X protocol) support ok\n--------------------------------------------------------------------\n'
       >
       > ----------------------------------------------------------------------
       > Ran 337 tests in 32.401s
       >
       > FAILED (failures=1, skipped=9)
       For full logs, run 'nix log /nix/store/xyjf2iypjc6sml5ik342mxvglv3sxl9q-calibre-7.20.0.drv'.
error: 1 dependencies of derivation '/nix/store/363k63indzg0x1mnlclcfrq4lp2b0znp-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w581qfnr0lfd5l564r0hzg2i7d1cwsmb-nixos-system-arrakis-25.05.20241115.5e4fbfb.drv' failed to build
```

Full build log at https://gist.github.com/nipsy/32e785f030650aa55d150830706e29c3.

## Metadata

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.60, NixOS, 24.11 (Vicuna), 24.11.20241111.dc460ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/4r8s42c9mwfvgdlxv0izb1cmlzrsb5nz-source`
```

## Notify maintainers

@pSub

**Comment by alapshin** [comment]
It should be fixed in https://github.com/NixOS/nixpkgs/pull/355885

**Comment by nipsy** [comment]
Yep, installing calibre from master worked a treat.  Closing this.

**Comment by jperon** [comment]
@pSub @diogotcorreia  I still encounter this bug while upgrading to 24.11.

**Comment by diogotcorreia** [comment]
@jperon The backported fix still hasn't reached the `nixos-24.11` channel: https://nixpk.gs/pr-tracker.html?pr=356515
