### ISSUE TITLE
FreeCAD v1.0.0 fails to start - segmentation fault

### ISSUE THREAD

**Issue by Joshua265** [NixOS/nixpkgs#366299]
## Describe the bug

I'm unable to start FreeCad v1.0.0.
When trying to start it, I get the following error:
```
$ freecad --verbose
FreeCAD 1.0.0, Libs: 1.0.0RUnknown
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Program received signal SIGSEGV, Segmentation fault.
#0  /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6(+0x40620) [0x7f0560247620]
#1  [0x7ffc91e29a10]
```

## Steps To Reproduce

1. Add the `freecad` or `freecad-wayland`  package from nixpkgs 24.11 or unstable
2. Start it

I coudn't reproduce this on my laptop (Intel CPU with integrated Graphics). There it works well.
The Issue only happened on my Desktop with NVIDIA GPU, but i have no idea if this is related to the GPU or another problem entirely.
Both machines run on a similar nix-config.

## Expected behavior

I expect FreeCAD to start without issues.

## Additional context

Running v0.21 from nixpkgs 24.05 works (except some NVIDIA Flickering&trade;)

Also I found this old issue, which looks related #42790

## Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.66, NixOS, 24.11 (Vicuna), 24.11.20241216.3945713`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-23.11"`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```
I'm using flakes and use a NVIDIA GPU.

## Notify maintainers

@gebner 
@AndersonTorres
@srounce

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by liberodark** [comment]
On my side in 24.11 that work : 

```
freecad --verbose
FreeCAD 1.0.0, Libs: 1.0.0RUnknown
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
```

**Comment by srounce** [comment]
I'm also using an Nvidia GPU (2080) and am having no issues with FreeCAD. Are you using multiple versions of Nixpkgs in your flake inputs by any chance?

**Comment by Joshua265** [comment]
Thank you guys for the quick response, I really hoped someone else encountered the same issue...

I'm running a RTX 3090 with stable drivers (565.77).

I am using unstable and 24.11 in my flakes, but there seems to be an issue with cura, therefore I am using that with 24.05.

I did some debugging of the launch, and had some interesting findings:

Using gdb with
```
$ gdb --args freecad
(gdb) run
```
actually runs the program without issues.

Running `valgrind --trace-children=yes freecad` actually encountered the issue:
<details>
  <summary>Logs</summary>

```
==1085025== Memcheck, a memory error detector
==1085025== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==1085025== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==1085025== Command: freecad
==1085025== 
==1085025== Memcheck, a memory error detector
==1085025== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==1085025== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==1085025== Command: /nix/store/ffq5vq0vxc5py7id8nkh72vxq6bplid7-freecad-1.0.0/bin/.FreeCAD-wrapped_
==1085025== 
==1085025== Memcheck, a memory error detector
==1085025== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==1085025== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==1085025== Command: /nix/store/ffq5vq0vxc5py7id8nkh72vxq6bplid7-freecad-1.0.0/bin/.FreeCAD-wrapped
==1085025== 
==1085025== Memcheck, a memory error detector
==1085025== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==1085025== Using Valgrind-3.23.0 and LibVEX; rerun with -h for copyright info
==1085025== Command: /nix/store/ffq5vq0vxc5py7id8nkh72vxq6bplid7-freecad-1.0.0/bin/..FreeCAD-wrapped-wrapped
==1085025== 
==1085025== realloc() with size 0
==1085025==    at 0x484E492: realloc (in /nix/store/jlcmn1sc1k1ryzk2lzxs3af4m1ghmdy6-valgrind-3.23.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1085025==    by 0x11012CFE: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libnvidia-glcore.so.565.77)
==1085025==    by 0x10473936: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x104CEC61: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x10473012: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x4036FFF: ??? (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400438C: call_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40044CB: _dl_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x4001585: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B0CD: dl_open_worker (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40014F0: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B45B: _dl_open (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==  Address 0x100c1030 is 0 bytes after a block of size 0 alloc'd
==1085025==    at 0x48467D9: malloc (in /nix/store/jlcmn1sc1k1ryzk2lzxs3af4m1ghmdy6-valgrind-3.23.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1085025==    by 0x11012CEE: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libnvidia-glcore.so.565.77)
==1085025==    by 0x10473936: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x104CEC61: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x10473012: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x4036FFF: ??? (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400438C: call_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40044CB: _dl_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x4001585: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B0CD: dl_open_worker (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40014F0: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B45B: _dl_open (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025== 
==1085025== posix_memalign() invalid size value: 0
==1085025==    at 0x484EF00: posix_memalign (in /nix/store/jlcmn1sc1k1ryzk2lzxs3af4m1ghmdy6-valgrind-3.23.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1085025==    by 0x11012D35: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libnvidia-glcore.so.565.77)
==1085025==    by 0x10473936: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x104CEC61: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x10473012: ??? (in /nix/store/jddpjvnl554s1bids0xacq7ribm69k90-nvidia-x11-565.77-6.6.66/lib/libGLX_nvidia.so.565.77)
==1085025==    by 0x4036FFF: ??? (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400438C: call_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40044CB: _dl_init (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x4001585: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B0CD: dl_open_worker (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x40014F0: _dl_catch_exception (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025==    by 0x400B45B: _dl_open (in /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2)
==1085025== 
FreeCAD 1.0.0, Libs: 1.0.0RUnknown
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

libEGL warning: egl: failed to create dri2 screen
warning: queue 0x16a1ef40 destroyed while proxies still attached:
  wl_display#1 still attached
==1085025== Use of uninitialised value of size 8
==1085025==    at 0x34059DCB: ??? (in /memfd:sljit (deleted))
==1085025== 
==1085025== Jump to the invalid address stated on the next line
==1085025==    at 0x0: ???
==1085025==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==1085025== 
Program received signal SIGSEGV, Segmentation fault.
#0  /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6(+0x40620) [0xad45620]
```
</details>

I have no idea about the Memory Error, but libEGL sounded like an OpenGL issue to me. Therefore I checked my OpenGL information and running freecad with nixGL. 

```
$ glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'
direct rendering: Yes
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3090/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 565.77
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6.0 NVIDIA 565.77
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 565.77
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

```
$ nix run --override-input nixpkgs nixpkgs/nixos-21.11 --impure github:nix-community/nixGL -- freecad
warning: not writing modified lock file of flake 'github:nix-community/nixGL':
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/441dc5d512153039f19ef198e662e4f3dbb9fd65?narHash=sha256-a1LARMMYQ8DPx1BgoI/UN4bXe12hhZkCNqdxNi6uS0g%3D' (2022-08-15)
  → 'github:NixOS/nixpkgs/eabc38219184cc3e04a974fe31857d8e0eac098d?narHash=sha256-hekabNdTdgR/iLsgce5TGWmfIDZ86qjPhxDg/8TlzhE%3D' (2022-08-02)
FreeCAD 1.0.0, Libs: 1.0.0RUnknown
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Program received signal SIGSEGV, Segmentation fault.
#0  /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6(+0x40620) [0x7fb77fc47620]
#1  [0x7fffaa4c0820]
```

Sadly that did not resolve the issue yet. I'm still curious, why it works when running gdb.

**Comment by DasenB** [comment]
I dot have the exact same problem on my Laptop (Thinkapd X1 Extreme Gen5 with GeForce RTX 3050 Ti)

**Comment by srounce** [comment]
> I am using unstable and 24.11 in my flakes

In the past I've run into issues with other Python applications where different versions of glibc were targeted by the host application and the C/C++ components of various python modules being loaded, this has tended to be when mixing and matching versions of Nixpkgs. Can you confirm everything is definitely using the same glibc version.

**Comment by calops** [comment]
I have the exact same issue on my system. Also using unstable with 24.11 and an nvidia GPU. No idea where to go from there to troubleshoot this.

**Comment by srounce** [comment]
I'm wondering if this is related to the `stable` Nvidia driver package not actually using the stable driver (recently fixed in #365711). 

@Joshua265 it seems the version you're running is not actual stable release, what happens if you switch to the *real* stable (`production`)?

@calops Which driver are you using?

**Comment by calops** [comment]
I have this in my config if that's what you're asking: 

```
    services.xserver.videoDrivers = [ "nvidia" ];
```

Do I need to check something else beyond that?

**Comment by Joshua265** [comment]
You would need to set the following line @calops :
`hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.production;`

I changed mine to production, but it didn't solve the problem.

Regarding the dependencies:

> > I am using unstable and 24.11 in my flakes
> 
> In the past I've run into issues with other Python applications where different versions of glibc were targeted by the host application and the C/C++ components of various python modules being loaded, this has tended to be when mixing and matching versions of Nixpkgs. Can you confirm everything is definitely using the same glibc version.

I'm not sure how to check it for all python deps, but for freecad it returned:
```
$ ldd /home/user/.nix-profile/bin/freecad
	linux-vdso.so.1 (0x00007ffe7e589000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f588088c000)
	/nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/ld-linux-x86-64.so.2 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib64/ld-linux-x86-64.so.2 (0x00007f5880a87000)
```

When I checked the .so files in the nix store, I have some which are using glibc 2.39-52 instead of 2.40-36. Freecad packages all used 2.40-36:
<details>
  <summary>Click me</summary>
  
```
$ find /nix/store/ffq5vq0vxc5py7id8nkh72vxq6bplid7-freecad-1.0.0 -name "*.so" -exec ldd {} \; | grep libc.so.6
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f9fc3807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fa278807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fbf0e007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fd514e07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f3175cc8000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f611fc14000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fb19d214000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f7989407000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f739ec07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fed6cc14000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f045d007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f34b4c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007ff2eb207000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fec27007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fb0a3007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f97eac07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f938f407000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fdda4207000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fcaa8814000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f65c1414000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fd2e0007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5f9b607000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007feac9807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007ff8e4807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f43b1814000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f354d920000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fc7f3c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fd21f807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f78c4407000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fe988007000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5f39807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fc8f1e07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f85e0607000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f138fc07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f0fa5407000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f2826c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f3efca07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f9a23807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f7d2ee07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fe30c0c8000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fe0cc807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f3891a07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fc9ea807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f4fccc07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f7819207000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fb9f9c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f62b0814000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fcb28a07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5e74207000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fdefd607000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f9b6be14000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007efd8ae07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f4a5ac07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f3b3a614000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f50f5807000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f7866207000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007ff306407000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fb39ee07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007fd624e14000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5195c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5b60c07000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f1c486c8000)
	libc.so.6 => /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6 (0x00007f5d3cc07000)
```
</details>

**Comment by DasenB** [comment]
I just updated my flakes to the latest version and the problem still persists. 

It seems to have no effect whether stable or unstable is used. Normally I use both stable and unstable as input in my flakes. For debugging I removed the unstable input from my flakes which did not change anything. 

I noticed that kicad seems to have the same problem. `kicad-cli` dies with a segmentation fault but with gdb it runs just fine.

I use Wayland with Hyprland as compositor. 

```
glxinfo -B | grep -i '\(direct rendering\|opengl\|profile\)'
direct rendering: Yes
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 565.77
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6.0 NVIDIA 565.77
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 565.77
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

This is my current graphics configuration:
``` nixos
services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    nvidiaPersistenced = false;
    prime = {
      offload = {
		enable = true;
		enableOffloadCmd = true;
	  };
      intelBusId  = "PCI:00:02:0";
      nvidiaBusId  = "PCI:01:00:0";
    };
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };
```

**Comment by DasenB** [comment]
I tested some more applications that have the same problem. All crash without gdb but can be executed with gdb. When doing this for `orca-slicer` it eventually also segfaults from within gdb. This is the backtrace:

```
0x00007fffe7caf6b6 in ppoll () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
(gdb) backtrace
#0  0x00007fffe7caf6b6 in ppoll () from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
#1  0x00007fffecd0d763 in g_main_context_iterate_unlocked.isra () from /nix/store/26hcp8h792wl0h52c5r94qakhvk6q717-glib-2.82.1/lib/libglib-2.0.so.0
#2  0x00007fffecd0e0df in g_main_loop_run () from /nix/store/26hcp8h792wl0h52c5r94qakhvk6q717-glib-2.82.1/lib/libglib-2.0.so.0
#3  0x00007fffed41456d in gtk_main () from /nix/store/8cw08cgb87bpyzbqrk9pwb1fj7lfyxql-gtk+3-3.24.43/lib/libgtk-3.so.0
#4  0x00007fffef570555 in wxGUIEventLoop::DoRun() () from /nix/store/r2xw2lzgn96hsfq4b8qb0i078bgphbi6-wxwidgets-3.1.7/lib/libwx_gtk3u_core-3.1.so.7
#5  0x00007fffefcd5d8d in wxEventLoopBase::Run() () from /nix/store/r2xw2lzgn96hsfq4b8qb0i078bgphbi6-wxwidgets-3.1.7/lib/libwx_baseu-3.1.so.7
#6  0x00007fffefca992b in wxAppConsoleBase::MainLoop() () from /nix/store/r2xw2lzgn96hsfq4b8qb0i078bgphbi6-wxwidgets-3.1.7/lib/libwx_baseu-3.1.so.7
#7  0x00007fffefd187c7 in wxEntry(int&, wchar_t**) () from /nix/store/r2xw2lzgn96hsfq4b8qb0i078bgphbi6-wxwidgets-3.1.7/lib/libwx_baseu-3.1.so.7
#8  0x00000000013f8bcb in Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&) ()
#9  0x00000000008cd51b in Slic3r::CLI::run(int, char**) ()
#10 0x0000000000833804 in main ()
```

**Comment by fuma-afk** [comment]
I have the exact same issue on my desktop with nvidia GPU (RTX 3070)
if i run it with gdb it starts withotu issue but, if normally executed it goes into Seg fault.

On my framework laptop with AMD and the exact same flake and versions i'm using on my desktop (except for AMD drivers instead of Nvidia) it starts without issue, so i guess it's Nvidia

i got open set to true on my nvidia conf but i doubt that is the issue

**Comment by iynaix** [comment]
I've been able to get it to run without segfaulting by using software rendering instead:

```nix
(pkgs.symlinkJoin {
    name = "FreeCAD";
    paths = [ pkgs.freecad-wayland ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
        wrapProgram $out/bin/FreeCAD \
        --set __GLX_VENDOR_LIBRARY_NAME mesa \
        --set __EGL_VENDOR_LIBRARY_FILENAMES ${pkgs.mesa.drivers}/share/glvnd/egl_vendor.d/50_mesa.json
    '';
    meta.mainProgram = "FreeCAD";
})
```

A similar workaround can also be used for orca-slicer / bambu-studio (which don't show the build plate)

**Comment by ZAZPRO** [comment]
Have the same issue on my home pc with RTX 3080.
What I have noticed is that if you run FreeCAD/KiCAD with strace it doesn't segfault.

**Comment by pdelbarba** [comment]
Same situation as @ZAZPRO but with a 1080.  Running under strace also magically causes it to run.

**Comment by WJKPK** [comment]
Despite shutting down the Issue on the Hyprland side, it still occurs when using the latest version Hyprland on nix unstable

**Comment by DasenB** [comment]
For me the problem also still persists after multiple updates of pretty much all the components involved. :(

**Comment by mwlaboratories** [comment]
tried to use freecad on unstable but the viewport is so unresponsive it crashes
