### ISSUE TITLE
Darwin `stdenvNoCC` pulls in full compiler

### ISSUE THREAD

**Issue by mroi** [NixOS/nixpkgs#371465]
The `stdenvNoCC` environment on Darwin depends on a full LLVM toolchain and clang compiler. Consequently, `stdenvNoCC` has a large closure size on Darwin: 1.09GiB vs. 71MiB on Linux (determined using `nix-tree nixpkgs#stdenvNoCC` on both platforms).

## Steps To Reproduce

Run one of the following:
`nix-tree nixpkgs#stdenvNoCC`
`nix why-depends nixpkgs#stdenvNoCC nixpkgs#llvmPackages.clang-unwrapped`

## Expected behavior

`stdenvNoCC` should not pull in a compiler, resulting in a smaller closure size than currently reported by `nix-tree`. Specifically, `nix why-depends` should show it *not* to depend on `clang-unwrapped`.

## Additional context

The culprit appears to be that the `setup` script of `stdenvNoCC` contains the store path of the Apple SDK in the variable `defaultBuildInputs`. This pulls in the entire build toolchain. Unfortunately, I do not understand the creation process of `stdenv` well enough to see how to test getting rid of this. I’d think that if a compiler-less `stdenv` is requested, the SDK would not be needed?

## Metadata

 - system: `"x86_64-darwin"`
 - host os: `Darwin 24.2.0, macOS 15.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/4c6wr0gvjr2azsng4vi8a9j1y1yzai4y-source`

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
CC @NixOS/darwin-core @NixOS/llvm

**Comment by emilazy** [comment]
Yes, I suppose we could omit the SDK for `stdenvNoCC`. I think this might need special handling for the fallback SDK too.

**Comment by mroi** [comment]
Let me know, if there is any way I can help. If someone could give me a hint as to how the SDK ends up in the `setup` script, I could test removing it.

**Comment by emilazy** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/392695 after the next `staging-next` cycle reaches the channels (you can track it on https://nixpk.gs/pr-tracker.html). Thanks for the report!

**Comment by mroi** [comment]
It looks like this issue is not fully fixed. I see with current unstable (507b63021ada5fee621b6ca371c4fca9ca46f52c), the dependency on `clang-unwrapped` is still there:
```
> nix why-depends nixpkgs#stdenvNoCC nixpkgs#llvmPackages.clang-unwrapped
/nix/store/ziy3jxmzjncsbi431j32686d9pi3c6xw-stdenv-darwin
└───/nix/store/kgbfazf2npzbwf1yw1n3cbc8gdhh17hx-apple-sdk-11.3
    └───/nix/store/x3bdc5hhm06j0s2dhp63rw2rs86bl65l-cctools-binutils-darwin-1010.6
        └───/nix/store/9ywg16p7a14wrwjbflaq81sjm9i44pp7-clang-19.1.7
```

Consequently, the `stdenvNoCC` closure remains large:
```
> nix path-info --closure-size --human-readable nixpkgs#stdenvNoCC
/nix/store/ziy3jxmzjncsbi431j32686d9pi3c6xw-stdenv-darwin	   1.1 GiB
```

It looks like #392695 removed `extraBuildInputs`, but the SDK is still pulled in via (at least) `defaultBuildInputs`:
```
> nix eval nixpkgs#stdenvNoCC.extraBuildInputs
[ ]
> nix eval nixpkgs#stdenv.defaultBuildInputs
[ «derivation /nix/store/c9s7bqqlrjhwjbrrh02hj59ird4ww8fi-apple-sdk-11.3.drv» ]
```

Should `defaultBuildInputs` also be emptied [here](https://github.com/NixOS/nixpkgs/blob/507b63021ada5fee621b6ca371c4fca9ca46f52c/pkgs/top-level/stage.nix#L64)?

**Comment by toonn** [comment]
I do think you're right. @reckenrode can you take another look?

**Comment by toonn** [comment]
Closing because #429386 was merged, which should've fixed this.
