### ISSUE TITLE
libreoffice: broken build

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#37619]
## Issue description

Build broken in hydra: https://hydra.nixos.org/build/71636765

I'm afraid I don't have the horsepower available to do a bisection.

**Comment by 7c6f434c** [comment]
@mdorman yes, it is `poppler` update that dropped `UTF8.h` and there is an upstream `libreoffice-still` update and I have started doing something to bump LibreOffice in Nixpkgs.

**Comment by 7c6f434c** [comment]
OK, just a bump will probably not help, but apparently this situation has already happenned in the past and we can try to force a similar workaround.

**Comment by 7c6f434c** [comment]
Forgot to write here: push fixed, for example it works in https://hydra.nixos.org/build/71902525

@mdorman I will close it at some point unless you explicitly object

**Comment by Anton-Latukha** [comment]
@7c6f434c @mdorman 
Close, it is old BR on old build.
Now it builds:
https://hydra.nixos.org/job/nixos/release-18.03/nixpkgs.libreoffice.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/staging/libreoffice.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/trunk/libreoffice.x86_64-linux

**Comment by 7c6f434c** [comment]
Note that I will likely downgrade LibreOffice Still (it somehow got coalesced with Fresh in staging branch…)

**Comment by 7c6f434c** [comment]
I know, but doing anything with LibreOffice build takes a lot of time and I haven't yet allocated a chunk.

Also, after a weird staging merge fresh and still are the same in unstable; not sure if pointing the still back at still.nix will fix the builf because see previous sentence.

**Comment by averelld** [comment]
It was broken by the xmlsec minor version upgrade in 45eeb247019d6f05626ca06b9ea155fc2d8805a9
If anyone needs a quick fix, just revert that.

**Comment by peti** [comment]
I reverted the `xmlsec` update in 31b4bfe649ce92b1a74dbc464f16c542c32e9043.

**Comment by 7c6f434c** [comment]
Thanks @peti

**Comment by 7c6f434c** [comment]
`getentropy`? is this kernel version dependent?

Current `master` is buildable for me…

**Comment by peti** [comment]
Maybe something happened between 7296c261f782ae525bdaf2a8c885e0d2c0f640e1 (the version built by Hydra) and c5fb293a1dd1d03c3a99f78896d445e0ea5763ae (`master` now)?

**Comment by 7c6f434c** [comment]
Both revisions give the same output path for me (I probably have built it using yet another revision)

**Comment by peti** [comment]
Hmm, strange. I'll run a local build with c5fb293 now. Let's see what happens.

**Comment by peti** [comment]
`libreoffice` compiled fine locally in revision bbf359ecc8baa1c627360d3e4892a4172f28a78c. *sighs*  Let's hope Hydra sees it the same way in the next evaluation.

**Comment by joncojonathan** [comment]
The build is broken still it would seem.  Left my machine trying to `nixos-rebuild switch --upgrade`, which included a LibreOffice upgrade and it looks like a problem with the tests, to my untrained eye:

```
/build/libreoffice-6.0.3.2/xmlsecurity/qa/unit/signing/signing.cxx:453:SigningTest::testOOXMLPartial
assertion failed
- Expression: (nActual == SignatureState::NOTVALIDATED || nActual == SignatureState::PARTIAL_OK)
- 2


/build/libreoffice-6.0.3.2/xmlsecurity/qa/unit/signing/signing.cxx:524:SigningTest::test96097Calc
assertion failed
- Expression: (nActual == SignatureState::OK || nActual == SignatureState::NOTVALIDATED || nActual == SignatureState::INVALID)
- 2

/build/libreoffice-6.0.3.2/xmlsecurity/qa/unit/signing/signing.cxx:572:SigningTest::test96097Doc
assertion failed
- Expression: (nActual == SignatureState::OK || nActual == SignatureState::NOTVALIDATED || nActual == SignatureState::INVALID)
- 2
...

make[1]: *** [/build/libreoffice-6.0.3.2/solenv/gbuild/CppunitTest.mk:115: /build/libreoffice-6.0.3.2/workdir/CppunitTest/xmlsecurity_signing.test] Error 1
make: *** [Makefile:270: build] Error 2
[LibreOfficeBuildFailure.txt](https://github.com/NixOS/nixpkgs/files/2122438/LibreOfficeBuildFailure.txt)


etc.
```

My buffer only goes back so far, but I've attached what I have.

I hope this helps with the troubleshooting.

**Comment by 7c6f434c** [comment]
>The build is broken still it would seem.  Left my machine trying to `nixos-rebuild switch --upgrade`, which included a LibreOffice upgrade and it looks like a problem with the tests, to my untrained eye:
>
>```
>/build/libreoffice-6.0.3.2/xmlsecurity/qa/unit/signing/signing.cxx:453:SigningTest::testOOXMLPartial
>assertion failed
>- Expression: (nActual == SignatureState::NOTVALIDATED || nActual == SignatureState::PARTIAL_OK)
>- 2

`6.0.3.2` is the channel revision, not the `master` branch revision — _this_ problem has been already fixed by not using global `xmlsec`.

**Comment by peterhoeg** [comment]
```libreoffice-fresh``` is still broken on the last unstable whereas ```libreoffice-still``` is building (and in the cache).

**Comment by 7c6f434c** [comment]
`getentropy` seems to be a relatively (sigh) recent system call on 
Linux, what is the kernel version on the builder? Locally from master
(as of some random point between 06:00 and 10:00 UTC) I can build both
versions.

**Comment by peterhoeg** [comment]
Both ```fresh``` and ```still``` are working again on unstable.
