### ISSUE TITLE
Rabbitmq is broken on release-18.03

### ISSUE THREAD

**Issue by nlewo** [NixOS/nixpkgs#37638]
## Issue description
`rabbitmq_server` fails to build on release-18.03 (a614f9f4c1b) but it builds on master.
```
nix-build ./ -A rabbitmq_server 
these derivations will be built:
  /nix/store/ijvnmcf4zhc7jkv16k045s0pyrd0c1z2-rabbitmq-server-3.6.15.drv
building '/nix/store/ijvnmcf4zhc7jkv16k045s0pyrd0c1z2-rabbitmq-server-3.6.15.drv'...
...
...
...
build flags: SHELL=/nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12/bin/bash
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
make[1]: Entering directory '/tmp/nix-build-rabbitmq-server-3.6.15.drv-1/rabbitmq-server-3.6.15/deps/rabbit_common'
make[2]: Entering directory '/tmp/nix-build-rabbitmq-server-3.6.15.drv-1/rabbitmq-server-3.6.15/deps/recon'
 DEPEND recon.d
{"init terminating in do_boot",{'cannot get bootfile','start_clean.boot'}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
make[2]: *** [/tmp/nix-build-rabbitmq-server-3.6.15.drv-1/rabbitmq-server-3.6.15/deps/rabbit_common/erlang.mk:5092: recon.d] Error 1
...
...
```

### Steps to reproduce
```
cd nixpkgs/
git checkout a614f9f4c1ba72a9f0dedb3332aeec480c3c46c8
nix-build ./ -A rabbitmq_server
```

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.
```
- system: `"x86_64-linux"`
 - host os: `Linux 4.9.80, NixOS, 17.09.3008.c831224528c (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.12pre5873_b76e282d`
 - channels(lewo): `"contrail, contrail-testing"`
 - channels(root): `"nixos-17.09.3008.c831224528c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by nlewo** [comment]
I've tryied the patch proposed in https://github.com/NixOS/nixpkgs/issues/36853#issuecomment-375361313 and it fixes the `rabbitmq` build.

**Comment by the-kenny** [comment]
Note that I just pushed 3e61f3b911c to master. Please try cherry-picking it to your clone of `release-18.03` and report if it fixes the issue. If so, we can push it to `release-18.03` too :)

**Comment by nlewo** [comment]
I think a test on my sidewould not be relevant since I can build locally (I've forced a rebuild on erlang) the derivation that failed on Hydra.

**Comment by vcunat** [comment]
I can reproduce it locally on some 18.03 commits, but not after systemd update 2d2ab94c (!).  Picking 3e61f3b on top of 2d2ab94c^ didn't fix the build locally.

**Comment by vcunat** [comment]
Seems OK now: https://hydra.nixos.org/job/nixos/release-18.03/nixos.tests.rabbitmq.x86_64-linux  Reopen otherwise.

**Comment by Profpatsch** [comment]
Yes, thanks for noticing. Forgot about this issue.
