### ISSUE TITLE
Build failure: python3.10-mistune

### ISSUE THREAD

**Issue by MrSom3body** [NixOS/nixpkgs#381110]
### Nixpkgs version

- Unstable (25.05)

### Steps to reproduce

1. Add `nwg-display` to packages
2. Rebuild

### Can Hydra reproduce this build failure?

Please select the Hydra Status.

### Relevant log output

```console
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pypa-build-hook
Using pypaBuildPhase
Sourcing python-runtime-deps-check-hook
Using pythonRuntimeDepsCheckHook
Sourcing pypa-install-hook
Using pypaInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing pytest-check-hook
Using pytestCheckPhase
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/2910gi8llwppdpflck3s06mdsw43cmaw-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file "source/tests/test_syntax.py"
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Executing pypaBuildPhase
Creating a wheel...
pypa build flags: --no-isolation --outdir dist/ --wheel
[1m* Getting build dependencies for wheel...[0m
running egg_info
creating src/mistune.egg-info
writing src/mistune.egg-info/PKG-INFO
writing dependency_links to src/mistune.egg-info/dependency_links.txt
writing requirements to src/mistune.egg-info/requires.txt
writing top-level names to src/mistune.egg-info/top_level.txt
writing manifest file 'src/mistune.egg-info/SOURCES.txt'
reading manifest file 'src/mistune.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
writing manifest file 'src/mistune.egg-info/SOURCES.txt'
[1m* Building wheel...[0m
running bdist_wheel
running build
running build_py
creating build/lib/mistune
copying src/mistune/__init__.py -> build/lib/mistune
copying src/mistune/__main__.py -> build/lib/mistune
copying src/mistune/block_parser.py -> build/lib/mistune
copying src/mistune/core.py -> build/lib/mistune
copying src/mistune/helpers.py -> build/lib/mistune
copying src/mistune/inline_parser.py -> build/lib/mistune
copying src/mistune/list_parser.py -> build/lib/mistune
copying src/mistune/markdown.py -> build/lib/mistune
copying src/mistune/toc.py -> build/lib/mistune
copying src/mistune/util.py -> build/lib/mistune
creating build/lib/mistune/directives
copying src/mistune/directives/__init__.py -> build/lib/mistune/directives
copying src/mistune/directives/_base.py -> build/lib/mistune/directives
copying src/mistune/directives/_fenced.py -> build/lib/mistune/directives
copying src/mistune/directives/_rst.py -> build/lib/mistune/directives
copying src/mistune/directives/admonition.py -> build/lib/mistune/directives
copying src/mistune/directives/image.py -> build/lib/mistune/directives
copying src/mistune/directives/include.py -> build/lib/mistune/directives
copying src/mistune/directives/toc.py -> build/lib/mistune/directives
creating build/lib/mistune/plugins
copying src/mistune/plugins/__init__.py -> build/lib/mistune/plugins
copying src/mistune/plugins/abbr.py -> build/lib/mistune/plugins
copying src/mistune/plugins/def_list.py -> build/lib/mistune/plugins
copying src/mistune/plugins/footnotes.py -> build/lib/mistune/plugins
copying src/mistune/plugins/formatting.py -> build/lib/mistune/plugins
copying src/mistune/plugins/math.py -> build/lib/mistune/plugins
copying src/mistune/plugins/ruby.py -> build/lib/mistune/plugins
copying src/mistune/plugins/speedup.py -> build/lib/mistune/plugins
copying src/mistune/plugins/spoiler.py -> build/lib/mistune/plugins
copying src/mistune/plugins/table.py -> build/lib/mistune/plugins
copying src/mistune/plugins/task_lists.py -> build/lib/mistune/plugins
copying src/mistune/plugins/url.py -> build/lib/mistune/plugins
creating build/lib/mistune/renderers
copying src/mistune/renderers/__init__.py -> build/lib/mistune/renderers
copying src/mistune/renderers/_list.py -> build/lib/mistune/renderers
copying src/mistune/renderers/html.py -> build/lib/mistune/renderers
copying src/mistune/renderers/markdown.py -> build/lib/mistune/renderers
copying src/mistune/renderers/rst.py -> build/lib/mistune/renderers
running egg_info
writing src/mistune.egg-info/PKG-INFO
writing dependency_links to src/mistune.egg-info/dependency_links.txt
writing requirements to src/mistune.egg-info/requires.txt
writing top-level names to src/mistune.egg-info/top_level.txt
reading manifest file 'src/mistune.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
writing manifest file 'src/mistune.egg-info/SOURCES.txt'
copying src/mistune/py.typed -> build/lib/mistune
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/mistune
copying build/lib/mistune/__init__.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/__main__.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/block_parser.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/core.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/helpers.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/inline_parser.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/list_parser.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/markdown.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/toc.py -> build/bdist.linux-x86_64/wheel/./mistune
copying build/lib/mistune/util.py -> build/bdist.linux-x86_64/wheel/./mistune
creating build/bdist.linux-x86_64/wheel/mistune/directives
copying build/lib/mistune/directives/__init__.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/_base.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/_fenced.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/_rst.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/admonition.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/image.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/include.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
copying build/lib/mistune/directives/toc.py -> build/bdist.linux-x86_64/wheel/./mistune/directives
creating build/bdist.linux-x86_64/wheel/mistune/plugins
copying build/lib/mistune/plugins/__init__.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/abbr.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/def_list.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/footnotes.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/formatting.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/math.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/ruby.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/speedup.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/spoiler.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/table.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/task_lists.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
copying build/lib/mistune/plugins/url.py -> build/bdist.linux-x86_64/wheel/./mistune/plugins
creating build/bdist.linux-x86_64/wheel/mistune/renderers
copying build/lib/mistune/renderers/__init__.py -> build/bdist.linux-x86_64/wheel/./mistune/renderers
copying build/lib/mistune/renderers/_list.py -> build/bdist.linux-x86_64/wheel/./mistune/renderers
copying build/lib/mistune/renderers/html.py -> build/bdist.linux-x86_64/wheel/./mistune/renderers
copying build/lib/mistune/renderers/markdown.py -> build/bdist.linux-x86_64/wheel/./mistune/renderers
copying build/lib/mistune/renderers/rst.py -> build/bdist.linux-x86_64/wheel/./mistune/renderers
copying build/lib/mistune/py.typed -> build/bdist.linux-x86_64/wheel/./mistune
running install_egg_info
Copying src/mistune.egg-info to build/bdist.linux-x86_64/wheel/./mistune-3.1.0-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/mistune-3.1.0.dist-info/WHEEL
creating '/build/source/dist/.tmp-1o0ipu5a/mistune-3.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'mistune/__init__.py'
adding 'mistune/__main__.py'
adding 'mistune/block_parser.py'
adding 'mistune/core.py'
adding 'mistune/helpers.py'
adding 'mistune/inline_parser.py'
adding 'mistune/list_parser.py'
adding 'mistune/markdown.py'
adding 'mistune/py.typed'
adding 'mistune/toc.py'
adding 'mistune/util.py'
adding 'mistune/directives/__init__.py'
adding 'mistune/directives/_base.py'
adding 'mistune/directives/_fenced.py'
adding 'mistune/directives/_rst.py'
adding 'mistune/directives/admonition.py'
adding 'mistune/directives/image.py'
adding 'mistune/directives/include.py'
adding 'mistune/directives/toc.py'
adding 'mistune/plugins/__init__.py'
adding 'mistune/plugins/abbr.py'
adding 'mistune/plugins/def_list.py'
adding 'mistune/plugins/footnotes.py'
adding 'mistune/plugins/formatting.py'
adding 'mistune/plugins/math.py'
adding 'mistune/plugins/ruby.py'
adding 'mistune/plugins/speedup.py'
adding 'mistune/plugins/spoiler.py'
adding 'mistune/plugins/table.py'
adding 'mistune/plugins/task_lists.py'
adding 'mistune/plugins/url.py'
adding 'mistune/renderers/__init__.py'
adding 'mistune/renderers/_list.py'
adding 'mistune/renderers/html.py'
adding 'mistune/renderers/markdown.py'
adding 'mistune/renderers/rst.py'
adding 'mistune-3.1.0.dist-info/LICENSE'
adding 'mistune-3.1.0.dist-info/METADATA'
adding 'mistune-3.1.0.dist-info/WHEEL'
adding 'mistune-3.1.0.dist-info/top_level.txt'
adding 'mistune-3.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
[1m[92mSuccessfully built [4mmistune-3.1.0-py3-none-any.whl[0m[1m[92m[0m
Finished creating a wheel...
Finished executing pypaBuildPhase
Running phase: pythonRuntimeDepsCheckHook
@nix { "action": "setPhase", "phase": "pythonRuntimeDepsCheckHook" }
Executing pythonRuntimeDepsCheck
Checking runtime dependencies for mistune-3.1.0-py3-none-any.whl
  - typing-extensions not installed
```

### Additional context

I couldn't find the hydra status for this package 😥

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.13.0, NixOS, 25.05 (Warbler), 25.05.20250129.9d3ae80`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/karun/.config/nix/nix.conf:/nix/store/9jqgk9pki7gqrqv7ri2sycn91wwqakf8-stylix-kde-config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/karun/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/karun/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/karun/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/karun/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/8yx7cj2wvh6iz8pddq4zn7lxlp0na01a-lix-2.91.1/share`
 - channels(root): `"home-manager, nixos-24.05"`
 - nixpkgs: `/nix/store/pgg4vm83q0kr4hxzcwhdgdiv2yfnh3dw-source`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+build+failure%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by arminius-smh** [comment]
Already fixed here: https://github.com/NixOS/nixpkgs/pull/380573 just not yet in unstable

**Comment by florpe** [comment]
Still occurs for me on unstable. The commit from  #380573 is present, but the error is exactly as above.

**Comment by florpe** [comment]
It seems that mistune is pulled in via httpx and flasgger - for me it's ultimately a transitive dependency of swaymonad:
```
> nix why-depends /nix/store/8jpsvza9i47j7w4kn14xmrwfc1ivz0i1-home-manager-generation.drv /nix/store/kfm51mja2n1wprigbpg6f3298inhahyy-python3.10-mistune-3.1.0.drv

/nix/store/8jpsvza9i47j7w4kn14xmrwfc1ivz0i1-home-manager-generation.drv
└───/nix/store/8x1pnj8ax4pgkj3nhcmjq757q8dzl8lz-home-manager-path.drv
    └───/nix/store/1p8sl146xqz7phd2zpxxgac2xvchg04d-swaymonad-0.0.1.drv
        └───/nix/store/25ghn2sxspcjv6w5s899c27zzvpqpyc4-python3-3.10.16-env.drv
            └───/nix/store/plfllj0hlfz88zrfxv114xkyl0338nza-python3.10-i3ipc-2.2.1.drv
                └───/nix/store/mbj52mwivrryrld3yqjzvjr0k7m0gs19-python3.10-pytest-xvfb-3.0.0.drv
                    └───/nix/store/4dx5ynp4w9xqcrcplggb6br592sn47z2-python3.10-pyvirtualdisplay-3.0.drv
                        └───/nix/store/2g7wpa7iqs0y4mx9spy0405qccbk027k-python3.10-vncdo-1.2.0.drv
                            └───/nix/store/39hdz17qpxr9pw9n94hb2adgn5p3aj0l-python3.10-twisted-24.11.0.drv
                                └───/nix/store/2iwqpsr3c96gp255gzzmnwaijk2s088w-python3.10-httpx-0.28.1.drv
                                    └───/nix/store/914kmgl91dw7xm6hbhh4px2az3ff8w4b-python3.10-httpcore-1.0.7.drv
                                        └───/nix/store/npilqx2hswvgwhnxcnd8fwav9k6742l1-python3.10-pytest-httpbin-2.0.0.drv
                                            └───/nix/store/qaxnr7j65423wy3anzlypfi5mjhqs556-python3.10-httpbin-0.10.2.drv
                                                └───/nix/store/d00f16js75ak45s5zb2xbjllzj7d2qxm-python3.10-flasgger-0.9.7.1.drv
                                                    └───/nix/store/kfm51mja2n1wprigbpg6f3298inhahyy-python3.10-mistune-3.1.0.drv
```

**Comment by arminius-smh** [comment]
I made a pr, should have done that in the first place as well, sorry!
