### ISSUE TITLE
Kernel 6.12+: Hardware Acceleration fails on Wayland on Electron apps and Chromium browsers

### ISSUE THREAD

**Issue by michaelBelsanti** [NixOS/nixpkgs#382612]
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

When using any kernel verson 6.12 and higher, many Electron apps are failing to start. I have tested this with Obsidian, Discord, Equibop, Vesktop and Legcord.
I have confirmed that anything below 6.12 works as expected.

This occurs on my desktop using an AMD RX 7800XT, but not on my laptop which uses an AMD Radeon 760M.

### Steps to reproduce

1. Use any kernel after 6.12, I believe this is done by default on unstable.
2. Launch an effected Electron app that uses GPU acceleration
3. If it fails to launch, try again with --disable-gpu and see that it 

### Expected behaviour

The app launching with GPU acceleration.

### Relevant log output

```console
[5899:0216/112650.076963:ERROR:angle_platform_impl.cc(44)] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[5899:0216/112650.077021:ERROR:scoped_egl_image.cc(23)] Failed to create EGLImage: EGL_SUCCESS
[5899:0216/112650.077049:ERROR:native_pixmap_egl_binding.cc(117)] Unable to initialize binding from pixmap
[5899:0216/112650.077079:ERROR:ozone_image_backing.cc(307)] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[5899:0216/112650.077101:ERROR:shared_image_manager.cc(256)] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
[5899:0216/112650.077151:ERROR:gpu_service_impl.cc(1162)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5764:0216/112650.193274:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=8704
[5764:0216/112650.279832:ERROR:interface_endpoint_client.cc(725)] Message 6 rejected by interface blink.mojom.WidgetHost
[5764:0216/112650.279846:ERROR:interface_endpoint_client.cc(725)] Message 7 rejected by interface blink.mojom.WidgetHost
[5981:0216/112650.288680:ERROR:angle_platform_impl.cc(44)] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[5981:0216/112650.288723:ERROR:scoped_egl_image.cc(23)] Failed to create EGLImage: EGL_SUCCESS
[5981:0216/112650.288749:ERROR:native_pixmap_egl_binding.cc(117)] Unable to initialize binding from pixmap
[5981:0216/112650.288775:ERROR:ozone_image_backing.cc(307)] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[5981:0216/112650.288796:ERROR:shared_image_manager.cc(256)] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
[5981:0216/112650.288835:ERROR:gpu_service_impl.cc(1162)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5906:0216/112650.292625:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[5764:0216/112650.294337:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=8704
[6032:0216/112650.379589:ERROR:angle_platform_impl.cc(44)] ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
ERR: ImageEGL.cpp:112 (operator()): eglCreateImage failed with 0x00003009
[6032:0216/112650.379641:ERROR:scoped_egl_image.cc(23)] Failed to create EGLImage: EGL_SUCCESS
[6032:0216/112650.379686:ERROR:native_pixmap_egl_binding.cc(117)] Unable to initialize binding from pixmap
[6032:0216/112650.379722:ERROR:ozone_image_backing.cc(307)] OzoneImageBacking::ProduceSkiaGanesh failed to create GL representation
[6032:0216/112650.379749:ERROR:shared_image_manager.cc(256)] SharedImageManager::ProduceSkia: Trying to produce a Skia representation from an incompatible backing: OzoneImageBacking
[6032:0216/112650.379813:ERROR:gpu_service_impl.cc(1162)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5764:0216/112650.386158:ERROR:gpu_process_host.cc(981)] GPU process exited unexpectedly: exit_code=8704
[5906:0216/112650.446486:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

### Additional context

Upstream issue: https://issues.chromium.org/issues/396434686

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.13, NixOS, 25.05 (Warbler), 25.05.20250213.2ff53fe`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/quasi/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/quasi/.local/share/flatpak/exports/etc/xdg/nix/nix.conf:/var/lib/flatpak/exports/etc/xdg/nix/nix.conf:/home/quasi/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/quasi/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/quasi/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/r7dh04pv6v6hc3w2v97423im7khkgd2s-lix-2.92.0/share`
 - channels(root): `"nixos"`
 - channels(quasi): `""`
 - nixpkgs: `/nix/store/brjzz8wv5k09bq0yrvhc1j4hd8677k21-source`

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by JohnRTitor** [comment]
I think I can reproduce this with VSCode too, though I am on 6.13, not sure if this is a kernel bug though (probably a driver incompatibility with the new electron). 

CC @K900

**Comment by michaelBelsanti** [comment]
> I think I can reproduce this with VSCode too, though I am on 6.13, not sure if this is a kernel bug though (probably a driver incompatibility with the new electron).

It does occur for me on 6.13 as well. I'm currently assuming some bug. Mind sharing what GPU you have?

**Comment by K900** [comment]
Dupe of https://github.com/NixOS/nixpkgs/issues/334175?

**Comment by michaelBelsanti** [comment]
I will double-check, but I believe the crashes still happened when using NIXOS_OZONE_WL=0.

**Comment by michaelBelsanti** [comment]
Confirmed that the issue still occurs when using NIXOS_OZONE_WL=0

**Comment by emilylange** [comment]
Can those that are affected by this check whether this is an `electron-bin` vs `electron-source` thing?
Unlike `electron_33`, `electron_34` is only available as `electron-bin`.

An increasing amount of electron consumers in nixpkgs don't respect the usual nixpkgs `.override` pattern, so consider using the following overlays:

```nix
{
  nixpkgs.overlays = [
    (final: prev: {
      electron = final.electron-source.electron_33;
      electron_34 = final.electron-source.electron_33;
    })
  ];
}
```

and then to compare:

```nix
{
  nixpkgs.overlays = [
    (final: prev: {
      electron = final.electron_33-bin;
      electron_34 = final.electron_33-bin;
    })
  ];
}
```

Thanks.

Ref: #380429 #383706

**Comment by michaelBelsanti** [comment]
It seems like I must have made a mistake or had some kind of fluke while testing. This issue is actually occuring for electron versions prior to 34, including at least 33 and 32, confirmed with Legcord and Zulip, my bad.

I have confirmed the issue occurs when using both electron-bin and source.

**Comment by michaelBelsanti** [comment]
Update on this issue:

This is still occurring on 6.13.5. I was not able to reproduce this on CachyOS, but one user has shared in an Electron issue that they are getting the same errors on Arch running Linux 6.13.5. This issue is not exclusive to packages from Nixpkgs, it occurs using Flatpak as well. This issue also only occurs when using the Wayland backend. Removing access to the Wayland socket from Flatpak apps makes them work normally.

**Comment by michaelBelsanti** [comment]
This happens on all apps using Chromium, not just Electron apps.

**Comment by JohnRTitor** [comment]
So according to the Chromium issue tracker, this bug/feature has been backported to 6.13.1 and 6.12.13 kernels.

Let's track it for now, this needs a fix from upstream Chromium, which will eventually land on Electron too.

FWIW, I just noticed I can reproduce this too, after upgrading to 6.13.4 :(

![Image](https://github.com/user-attachments/assets/3774d710-8496-4731-b1c1-625f6520b5ce)

**Comment by meatcar** [comment]
For clarity, the workaround for 6.12+ kernels is to force chromium/electron apps to run in X11 mode.

You can do that by making sure `NIXOS_OZONE_WL` isn't set anywhere in your environment. Setting `NIXOS_OZONE_WL=0` is insufficient as [the `:+` parameter expansion](https://github.com/NixOS/nixpkgs/blob/0f80da4f5e0dbe1f917f6f3643a262bae7dbb34e/pkgs/applications/networking/browsers/chromium/default.nix#L176) is a null-check and still triggers ([per bash manual](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html).)

**Comment by michaelBelsanti** [comment]
The issue is related to multiple GPU systems. Disabling integrated graphics if you don't need them seems to be a decent workaround.

According to the chromium bug tracker the patch for this issue will make it to chromium canary today. I assume it will take some time before the patch reaches electron, and that old electron versions probably won't use it.

**Comment by sodiboo** [comment]
Is there any supported kernel version that isn't affected by this issue? I'm experiencing it now on both kernel versions `6.6.87` and `6.1.134`. It's no longer just `6.12` and up.

**Comment by JohnRTitor** [comment]
It's a CVE fix, so it's likely been backported to any actively maintained LTS release.

**Comment by fee1-dead** [comment]
We should probably rename this issue to say kernel 6.x then.

**Comment by JohnRTitor** [comment]
This has been fixed on Chromium 135+ as far as I can see.

**Comment by fee1-dead** [comment]
Could we keep this open to track the fix in nixpkgs (and close only when it's been fixed in nixpkgs)? There's also electron

**Comment by ToasterUwU** [comment]
Electron is a big thing for this issue honestly. And thats not fixed as far as i understand.

No working hardware acceleration in Electron Apps means there is no HA in Discord for example as well. 

Just because Chromium fixed it upstream doesnt mean than Electron did and also not that those fixes arrived in nixpkgs.

I also think this issue is not ready to be closed. Its at most half fixed and only in upstream, im not sure what the policy is or if one exists, but i think its not sensible to have upstream only half fixed be the cause to close an issue.

**Comment by anders130** [comment]
Just yesterday, **vesktop** started throwing errors when I try to screenshare:
<details><summary>vesktop logs</summary>
<code>[39306:0903/223013.012993:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[39306:0903/223013.013008:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188757872388 and trying to renegotiate stream parameters
[39306:0903/223014.012792:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[39306:0903/223014.012806:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188757856004 and trying to renegotiate stream parameters
[39306:0903/223015.007538:ERROR:egl_dmabuf.cc(609)] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH
[39306:0903/223015.007558:ERROR:shared_screencast_stream.cc(951)] Dropping DMA-BUF modifier: 144115188757659396 and trying to renegotiate stream parameters
</code>
</details>

Is this related to this issue?
I am on **NixOS 25.05.20250829.41d292b (Warbler)**
with **Linux 6.12.44**
and Window-Manager: **hyprland 0.50.1**

Note: OBS and firefox still do screenshare just fine. Also discord's screenshare via the chromium browser is broken as well:

<details><summary>chromium logs</summary>
<code>[36482:36525:0903/222045.276417:ERROR:net/cert/ev_root_ca_metadata.cc:162] Failed to decode OID: 0 [36482:36482:0903/222045.477469:ERROR:mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:732] Message 0 rejected by interface blink.mojom.WidgetHost [36482:36862:0903/222139.339211:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/egl_dmabuf.cc:621] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH [36482:36862:0903/222139.339224:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc:973] Dropping DMA-BUF modifier: 144115188757659396 and trying to renegotiate stream parameters [36482:36862:0903/222139.347228:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/egl_dmabuf.cc:621] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH [36482:36862:0903/222139.347236:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc:973] Dropping DMA-BUF modifier: 144115188757659396 and trying to renegotiate stream parameters 'loop->recurse > 0' failed at ../src/pipewire/thread-loop.c:425 pw_thread_loop_wait() [36482:36870:0903/222143.027184:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/egl_dmabuf.cc:621] Failed to record frame: Error creating EGLImage - EGL_BAD_MATCH [36482:36870:0903/222143.027206:ERROR:third_party/webrtc/modules/desktop_capture/linux/wayland/shared_screencast_stream.cc:973] Dropping DMA-BUF modifier: 144115188757659396 and trying to renegotiate stream parameters
</code>
</details>

**Comment by michaelBelsanti** [comment]
> Just yesterday, **vesktop** started throwing errors when I try to screenshare:
> ...
> Is this related to this issue? I am on **NixOS 25.05.20250829.41d292b (Warbler)** with **Linux 6.12.44** and Window-Manager: **hyprland 0.50.1**

I think this is likely a separate GPU issue.
