### ISSUE TITLE
Evremap: Only supports keys with fully alphabetic names

### ISSUE THREAD

**Issue by bbenne10** [NixOS/nixpkgs#387975]
### Nixpkgs version

- Stable (24.11)

### Describe the bug

[Here](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/nixos/modules/services/misc/evremap.nix#L11), the type for the evremap keys definition is restricted such that only upper cased ASCII characters are accepted. This disallows valid keys such as `KEY_F13`.

### Steps to reproduce

```
services.evremap = {
    enable = true;
    settings = {
      device_name = "AT Translated Set 2 keyboard";
      remap = [ {
        input = [ "KEY_CAPSLOCK" ];
        output = [ "KEY_F13" ];
      }];
    };
  };
```

### Expected behaviour

This should probably be ` key = lib.types.strMatching "KEY_[[:upper:]].+" // {     description = "key ID prefixed with KEY_";   };` or something similar to enforce that the first character is upcased, but the rest is whatever the user typed. (Or `KEY_[[:upper::digit:]]+` to just limit it to the upcase and digits)

### Relevant log output

```console

```

### System metadata

This is meaningless, but 

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.10-zen1, NixOS, 24.11 (Vicuna), 24.11.20250228.b27ba4e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.92.0
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/bryan/.config/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/bryan/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/bryan/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/bryan/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/7xars01wfprnfg5rqyl9gf6ypkk99jrs-lix-2.92.0/share`
 - nixpkgs: `/nix/store/5k90vvmnhiyjfyz2fq2qcznb2l13c8x8-source`
```

### Notify maintainers

@pluiedev 
---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by bbenne10** [comment]
I am happy to get a PR opened to fix this if we can agree on the regex to use for the solution. I am presently at Planet Nix and the internet is...uh...saturated and cloning Nixpkgs would be a fool's errand right this moment.

**Comment by eclairevoyant** [comment]
It should be upper, digit, or underscore.

https://github.com/ndesh26/evdev-rs/blob/8c0628511f537060d9602fb08bc62db446ffcc73/src/enums.rs#L319

**Comment by bbenne10** [comment]
Thank you for pointing this out. I'll generalize the regex and get a PR opened.

**Comment by bbenne10** [comment]
This is already resolved on unstable. I'm sorry for the noise. I wonder if there's a possibility of a backport of https://github.com/NixOS/nixpkgs/pull/362661 to stable, as the interface widens rather than changes there, best I can tell.

**Comment by eclairevoyant** [comment]
But this wasn't resolved on unstable, the PR only adds `BTN` as a prefix.
The original issue you reported is still not correctly addressed.

A new PR is needed, then you can request a backport of the commits that are both in the PR you tagged + the new PR.

**Comment by bbenne10** [comment]
I misread the regex, unfortunately. You're correct: It only adds a new BTN prefix. I'll open a PR that fixes the regex, accounting for the prefix. I'll then label appropriately.

**Comment by bbenne10** [comment]
Addressed in #388802

**Comment by bbenne10** [comment]
Closed via #388802
