### ISSUE TITLE
nixos/hyprland: bump of nixpkgs causes `error: ‘mkIf’ called with a non-Boolean condition`

### ISSUE THREAD

**Issue by malikwirin** [NixOS/nixpkgs#400287]
### Nixpkgs version

- Stable (24.11)

### Describe the bug

My configuration no longer builds after bumping the version of nixpkgs in my flake.lock. Feel free to ask for details of my config.

### Steps to reproduce

In my case applying the following patch:
```patch
diff --git a/flake.lock b/flake.lock
index 42d910e..f94d8ed 100644
--- a/flake.lock
+++ b/flake.lock
@@ -1095,11 +1095,11 @@
     },
     "nixpkgs": {
       "locked": {
-        "lastModified": 1744168086,
-        "narHash": "sha256-S9M4HddBCxbbX1CKSyDYgZ8NCVyHcbKnBfoUXeRu2jQ=",
+        "lastModified": 1745068291,
+        "narHash": "sha256-pWKgZ0CPAVJ8jk8Y8g0zN9+r1mNdB7aZSFseYdC/T/o=",
         "owner": "NixOS",
         "repo": "nixpkgs",
-        "rev": "60e405b241edb6f0573f3d9f944617fe33ac4a73",
+        "rev": "3b5d63ccaed2b178edc7d3278c5c6ffa625be8d1",
         "type": "github"
       },
       "original": {
```

### Expected behaviour

Since the configuration did not change it should build

### Relevant log Summary
<details>
<summary>with --show-trace</summary>

```console
building the system configuration...
error:
       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1529:14:
         1528|         zipAttrsWith (
         1529|           n: values:
             |              ^
         1530|           let

       … while calling the 'head' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1534:13:
         1533|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1534|             head values
             |             ^
         1535|           else

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1033:5:
         1032|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
         1033|     mergedValue =
             |     ^
         1034|       if isDefined then

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1034:7:
         1033|     mergedValue =
         1034|       if isDefined then
             |       ^
         1035|         if all (def: type.check def.value) defsFinal then

       … while evaluating the attribute 'values'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1027:9:
         1026|       {
         1027|         values = defs''';
             |         ^
         1028|         inherit (defs'') highestPrio;

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1021:11:
         1020|           # Avoid sorting if we don't have to.
         1021|           if any (def: def.value._type or "" == "order") defs''.values then
             |           ^
         1022|             sortProperties defs''.values

       … while calling the 'any' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1021:14:
         1020|           # Avoid sorting if we don't have to.
         1021|           if any (def: def.value._type or "" == "order") defs''.values then
             |              ^
         1022|             sortProperties defs''.values

       … while evaluating the attribute 'values'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1136:7:
         1135|     {
         1136|       values = concatMap (def: if getPrio def == highestPrio then [ (strip def) ] else [ ]) defs;
             |       ^
         1137|       inherit highestPrio;

       … while calling the 'concatMap' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1136:16:
         1135|     {
         1136|       values = concatMap (def: if getPrio def == highestPrio then [ (strip def) ] else [ ]) defs;
             |                ^
         1137|       inherit highestPrio;

       … while calling the 'concatMap' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1007:17:
         1006|         # Process mkMerge and mkIf properties.
         1007|         defs' = concatMap (
             |                 ^
         1008|           m:

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1008:11:
         1007|         defs' = concatMap (
         1008|           m:
             |           ^
         1009|           map (value: {

       … while calling the 'map' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1009:11:
         1008|           m:
         1009|           map (value: {
             |           ^
         1010|             inherit (m) file;

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/activation/top-level.nix':

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1012:81:
         1011|             inherit value;
         1012|           }) (addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                 ^
         1013|         ) defs;

       … while calling 'dischargeProperties'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1093:5:
         1092|   dischargeProperties =
         1093|     def:
             |     ^
         1094|     if def._type or "" == "merge" then

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1094:5:
         1093|     def:
         1094|     if def._type or "" == "merge" then
             |     ^
         1095|       concatMap dischargeProperties def.contents

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:732:23:
          731|               inherit (module) file;
          732|               inherit value;
             |                       ^
          733|             }

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/activation/top-level.nix:84:5:
           83|   baseSystemAssertWarn =
           84|     if failedAssertions != [ ] then
             |     ^
           85|       throw "\nFailed assertions:\n${concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"

       … while calling the 'map' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/activation/top-level.nix:81:22:
           80|
           81|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                      ^
           82|

       … while calling the 'filter' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/activation/top-level.nix:81:42:
           80|
           81|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                                          ^
           82|

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/activation/top-level.nix:81:67:
           80|
           81|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                                                                   ^
           82|

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `assertions':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/boot/systemd.nix':

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1012:81:
         1011|             inherit value;
         1012|           }) (addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                 ^
         1013|         ) defs;

       … while calling 'dischargeProperties'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1093:5:
         1092|   dischargeProperties =
         1093|     def:
             |     ^
         1094|     if def._type or "" == "merge" then

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1094:5:
         1093|     def:
         1094|     if def._type or "" == "merge" then
             |     ^
         1095|       concatMap dischargeProperties def.contents

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:732:23:
          731|               inherit (module) file;
          732|               inherit value;
             |                       ^
          733|             }

       … while calling the 'concatLists' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/boot/systemd.nix:538:18:
          537|
          538|     assertions = concatLists (
             |                  ^
          539|       mapAttrsToList (

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/boot/systemd.nix:539:7:
          538|     assertions = concatLists (
          539|       mapAttrsToList (
             |       ^
          540|         name: service:

       … while calling 'mapAttrsToList'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1079:23:
         1078|   */
         1079|   mapAttrsToList = f: attrs: map (name: f name attrs.${name}) (attrNames attrs);
             |                       ^
         1080|

       … while calling the 'map' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1079:30:
         1078|   */
         1079|   mapAttrsToList = f: attrs: map (name: f name attrs.${name}) (attrNames attrs);
             |                              ^
         1080|

       … while calling the 'attrNames' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1079:64:
         1078|   */
         1079|   mapAttrsToList = f: attrs: map (name: f name attrs.${name}) (attrNames attrs);
             |                                                                ^
         1080|

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/boot/systemd.nix:555:9:
          554|           ])
          555|       ) cfg.services
             |         ^
          556|     );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `systemd.services':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix':

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1012:81:
         1011|             inherit value;
         1012|           }) (addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                 ^
         1013|         ) defs;

       … while calling 'dischargeProperties'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1093:5:
         1092|   dischargeProperties =
         1093|     def:
             |     ^
         1094|     if def._type or "" == "merge" then

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1097:7:
         1096|     else if def._type or "" == "if" then
         1097|       if isBool def.condition then
             |       ^
         1098|         if def.condition then dischargeProperties def.content else [ ]

       … while calling the 'isBool' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1097:10:
         1096|     else if def._type or "" == "if" then
         1097|       if isBool def.condition then
             |          ^
         1098|         if def.condition then dischargeProperties def.content else [ ]

       … while evaluating the attribute 'condition'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1220:13:
         1219|     _type = "if";
         1220|     inherit condition content;
             |             ^
         1221|   };

       … while evaluating the attribute 'condition'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1220:13:
         1219|     _type = "if";
         1220|     inherit condition content;
             |             ^
         1221|   };

       … while evaluating the attribute 'condition'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1220:13:
         1219|     _type = "if";
         1220|     inherit condition content;
             |             ^
         1221|   };

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:308:21:
          307|
          308|   config = lib.mkIf cfg.enable {
             |                     ^
          309|     systemd.services.logrotate = {

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `services.logrotate.enable':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1033:5:
         1032|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
         1033|     mergedValue =
             |     ^
         1034|       if isDefined then

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1034:7:
         1033|     mergedValue =
         1034|       if isDefined then
             |       ^
         1035|         if all (def: type.check def.value) defsFinal then

       … while evaluating the attribute 'values'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1027:9:
         1026|       {
         1027|         values = defs''';
             |         ^
         1028|         inherit (defs'') highestPrio;

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1021:11:
         1020|           # Avoid sorting if we don't have to.
         1021|           if any (def: def.value._type or "" == "order") defs''.values then
             |           ^
         1022|             sortProperties defs''.values

       … while calling the 'any' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1021:14:
         1020|           # Avoid sorting if we don't have to.
         1021|           if any (def: def.value._type or "" == "order") defs''.values then
             |              ^
         1022|             sortProperties defs''.values

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1021:19:
         1020|           # Avoid sorting if we don't have to.
         1021|           if any (def: def.value._type or "" == "order") defs''.values then
             |                   ^
         1022|             sortProperties defs''.values

       … while evaluating the attribute 'value._type'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1133:67:
         1132|       strip =
         1133|         def: if def.value._type or "" == "override" then def // { value = def.value.content; } else def;
             |                                                                   ^
         1134|     in

       … while evaluating the attribute 'value.content'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1234:22:
         1233|     _type = "override";
         1234|     inherit priority content;
             |                      ^
         1235|   };

       … while evaluating the attribute 'default'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:9:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |         ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:19:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |                   ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … while calling 'foldr'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:139:14:
          138|   foldr =
          139|     op: nul: list:
             |              ^
          140|     let

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:144:5:
          143|     in
          144|     fold' 0;
             |     ^
          145|

       … while calling 'fold''
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:15:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |               ^
          143|     in

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:44:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |                                            ^
          143|     in

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:33:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |                                 ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … in the left operand of the OR (||) operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:38:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |                                      ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:64:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |                                                                ^
          143|     in

       … while calling 'fold''
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:15:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |               ^
          143|     in

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:44:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |                                            ^
          143|     in

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:33:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |                                 ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … in the right operand of the OR (||) operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/services/logging/logrotate.nix:149:38:
          148|       enable = lib.mkEnableOption "the logrotate systemd service" // {
          149|         default = lib.foldr (n: a: a || n.enable) false (lib.attrValues cfg.settings);
             |                                      ^
          150|         defaultText = lib.literalExpression "cfg.settings != {}";

       … while calling the 'elemAt' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/lists.nix:142:48:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |                                                ^
          143|     in

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:654:26:
          653|             loc: defs:
          654|             mapAttrs (n: v: v.value) (
             |                          ^
          655|               filterAttrs (n: v: v ? value) (

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1050:41:
         1049|
         1050|     optionalValue = if isDefined then { value = mergedValue; } else { };
             |                                         ^
         1051|   };

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1036:11:
         1035|         if all (def: type.check def.value) defsFinal then
         1036|           type.merge loc defsFinal
             |           ^
         1037|         else

       … while calling 'merge'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:1082:18:
         1081|           merge =
         1082|             loc: defs:
             |                  ^
         1083|             (base.extendModules {

       … while evaluating the attribute 'config'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:360:9:
          359|         options = checked options;
          360|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          361|         _module = checked (config._module);

       … while calling the 'seq' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:360:18:
          359|         options = checked options;
          360|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          361|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:295:9:
          294|       checkUnmatched =
          295|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [ ] then
             |         ^
          296|           let

       … in the left operand of the AND (&&) operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:295:72:
          294|       checkUnmatched =
          295|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [ ] then
             |                                                                        ^
          296|           let

       … in the left operand of the AND (&&) operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:295:33:
          294|       checkUnmatched =
          295|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [ ] then
             |                                 ^
          296|           let

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:292:11:
          291|         else
          292|           recursiveUpdate freeformConfig declaredConfig;
             |           ^
          293|

       … while calling 'recursiveUpdate'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1584:10:
         1583|   recursiveUpdate =
         1584|     lhs: rhs:
             |          ^
         1585|     recursiveUpdateUntil (

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1585:5:
         1584|     lhs: rhs:
         1585|     recursiveUpdateUntil (
             |     ^
         1586|       path: lhs: rhs:

       … while calling 'recursiveUpdateUntil'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1524:16:
         1523|   recursiveUpdateUntil =
         1524|     pred: lhs: rhs:
             |                ^
         1525|     let

       … while calling the 'zipAttrsWith' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1539:5:
         1538|     in
         1539|     f [ ] [ rhs lhs ];
             |     ^
         1540|

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:283:42:
          282|             in
          283|             if defs == [ ] then { } else declaredConfig._module.freeformType.merge prefix defs;
             |                                          ^
          284|

       … while calling 'merge'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:653:18:
          652|           merge =
          653|             loc: defs:
             |                  ^
          654|             mapAttrs (n: v: v.value) (

       … while calling the 'mapAttrs' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:654:13:
          653|             loc: defs:
          654|             mapAttrs (n: v: v.value) (
             |             ^
          655|               filterAttrs (n: v: v ? value) (

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:655:15:
          654|             mapAttrs (n: v: v.value) (
          655|               filterAttrs (n: v: v ? value) (
             |               ^
          656|                 zipAttrsWith (name: defs: (mergeDefinitions (loc ++ [ name ]) elemType defs).optionalValue)

       … while calling 'filterAttrs'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:23:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                       ^
          658|

       … while calling the 'removeAttrs' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:28:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                            ^
          658|

       … while calling the 'filter' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:45:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                                             ^
          658|

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:53:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                                                     ^
          658|

       … in the argument of the not operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:60:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                                                            ^
          658|

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:60:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                                                            ^
          658|

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:655:31:
          654|             mapAttrs (n: v: v.value) (
          655|               filterAttrs (n: v: v ? value) (
             |                               ^
          656|                 zipAttrsWith (name: defs: (mergeDefinitions (loc ++ [ name ]) elemType defs).optionalValue)

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:657:70:
          656|   */
          657|   filterAttrs = pred: set: removeAttrs set (filter (name: !pred name set.${name}) (attrNames set));
             |                                                                      ^
          658|

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/types.nix:656:37:
          655|               filterAttrs (n: v: v ? value) (
          656|                 zipAttrsWith (name: defs: (mergeDefinitions (loc ++ [ name ]) elemType defs).optionalValue)
             |                                     ^
          657|                   # Push down position info.

       … while evaluating the attribute 'optionalValue'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1050:5:
         1049|
         1050|     optionalValue = if isDefined then { value = mergedValue; } else { };
             |     ^
         1051|   };

       … while evaluating a branch condition
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1050:21:
         1049|
         1050|     optionalValue = if isDefined then { value = mergedValue; } else { };
             |                     ^
         1051|   };

       (6 duplicate frames omitted)

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/system/boot/systemd.nix:804:31:
          803|         rotate = 1;
          804|         create = "0664 root ${config.users.groups.utmp.name}";
             |                               ^
          805|         minsize = "1M";

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `users.groups':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix':

       (7 duplicate frames omitted)

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix:173:15:
          172|
          173|     (lib.mkIf cfg.enable {
             |               ^
          174|       users.groups.resolvconf = { };

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `networking.resolvconf.enable':

       (8 duplicate frames omitted)

       … while evaluating the attribute 'default'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix:73:9:
           72|         type = lib.types.bool;
           73|         default = !(config.environment.etc ? "resolv.conf");
             |         ^
           74|         defaultText = lib.literalExpression ''!(config.environment.etc ? "resolv.conf")'';

       … in the argument of the not operator
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix:73:21:
           72|         type = lib.types.bool;
           73|         default = !(config.environment.etc ? "resolv.conf");
             |                     ^
           74|         defaultText = lib.literalExpression ''!(config.environment.etc ? "resolv.conf")'';

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix:73:21:
           72|         type = lib.types.bool;
           73|         default = !(config.environment.etc ? "resolv.conf");
             |                     ^
           74|         defaultText = lib.literalExpression ''!(config.environment.etc ? "resolv.conf")'';

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `environment.etc':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portal.nix':

       (7 duplicate frames omitted)

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portal.nix:118:10:
          117|     in
          118|     mkIf cfg.enable {
             |          ^
          119|       warnings = lib.optional (cfg.configPackages == [ ] && cfg.config == { }) ''

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `xdg.portal.enable':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portals/wlr.nix':

       (8 duplicate frames omitted)

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portals/wlr.nix:57:21:
           56|
           57|   config = lib.mkIf cfg.enable {
             |                     ^
           58|     xdg.portal = {

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1182:17:
         1181|         mapAttrs (
         1182|           name: value:
             |                 ^
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/attrsets.nix:1183:85:
         1182|           name: value:
         1183|           if isAttrs value && cond value then recurse (path ++ [ name ]) value else f (path ++ [ name ]) value
             |                                                                                     ^
         1184|         );

       … while calling anonymous lambda
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:273:71:
          272|           # For definitions that have an associated option
          273|           declaredConfig = mapAttrsRecursiveCond (v: !isOption v) (_: v: v.value) options;
             |                                                                       ^
          274|

       … while evaluating the attribute 'value'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `xdg.portal.wlr.enable':

       (10 duplicate frames omitted)

       … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/programs/wayland/hyprland.nix':

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1012:81:
         1011|             inherit value;
         1012|           }) (addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                 ^
         1013|         ) defs;

       … while calling 'dischargeProperties'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1093:5:
         1092|   dischargeProperties =
         1093|     def:
             |     ^
         1094|     if def._type or "" == "merge" then

       … from call site
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1098:31:
         1097|       if isBool def.condition then
         1098|         if def.condition then dischargeProperties def.content else [ ]
             |                               ^
         1099|       else

       … while calling 'dischargeProperties'
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1093:5:
         1092|   dischargeProperties =
         1093|     def:
             |     ^
         1094|     if def._type or "" == "merge" then

       … while calling the 'throw' builtin
         at /nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/lib/modules.nix:1100:9:
         1099|       else
         1100|         throw "‘mkIf’ called with a non-Boolean condition"
             |         ^
         1101|     else

       error: ‘mkIf’ called with a non-Boolean condition
```

</details>

Without `--show-trace`:
```
┏━ 1 Errors:
 ⋮
┃
┃        … while evaluating the option `services.logrotate.enable':
┃
┃        … while evaluating the option `users.groups':
┃
┃        … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/resolvconf.nix':
┃
┃        … while evaluating the option `networking.resolvconf.enable':
┃
┃        … while evaluating the option `environment.etc':
┃
┃        … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portal.nix':
┃
┃        … while evaluating the option `xdg.portal.enable':
┃
┃        … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/config/xdg/portals/wlr.nix':
┃
┃        … while evaluating the option `xdg.portal.wlr.enable':
┃
┃        … while evaluating definitions from `/nix/store/66cg9qq5jryjp60kr5vxgh7h6g144mvc-source/nixos/modules/programs/wayland/hyprland.nix':
┃
┃        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
┃
┃        error: ‘mkIf’ called with a non-Boolean condition
```

### Additional context

It seems to also have to do with xdg portals and resolvd

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.86, NixOS, 24.11 (Vicuna), 24.11.20250409.60e405b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.14`
 - nixpkgs: `/nix/store/97hykhxj3miqqhfnf55b1rphiwcpxlcr-source`

### Notify maintainers

@fufexan 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by fufexan** [comment]
Not sure what's wrong. Do you have your config posted somewhere?

Worst case scenario, if nothing else changed, you may have to bisect.

**Comment by malikwirin** [comment]
> Not sure what's wrong. Do you have your config posted somewhere?

I have not.
But this has only to do with the nixos configuration, I can ignore the home-manager configuration where most hyprland stuff happens?

**Comment by fufexan** [comment]
Looks like that shouldn't have any effect, so yes.

**Comment by acid-bong** [comment]
Found the culprit: https://github.com/NixOS/nixpkgs/commit/ae711c3e33a9143e92cb1108b537321a365947f6 (while glancing over https://github.com/NixOS/nixpkgs/compare/60e405b241edb6f0573f3d9f944617fe33ac4a73...3b5d63ccaed2b178edc7d3278c5c6ffa625be8d1)

@getchoo explain yourself, please

**Comment by acid-bong** [comment]
BTW, @malikwirin, you can make long sections of text collapsible with some HTML, like this
<details>
<summary>Summary</summary>
Content
</details>

```md
<details>
<summary>Summary</summary>
Content
</details>
```

**Comment by malikwirin** [comment]
> BTW, [@malikwirin](https://github.com/malikwirin), you can make long sections of text collapsible with some HTML, like this
> 
> Summary
> <details>
> <summary>Summary</summary>
> Content
> </details>

Thank you. I will use that more often

**Comment by sodiboo** [comment]
> Found the culprit: https://github.com/NixOS/nixpkgs/commit/ae711c3e33a9143e92cb1108b537321a365947f6 (while glancing over https://github.com/NixOS/nixpkgs/compare/60e405b241edb6f0573f3d9f944617fe33ac4a73...3b5d63ccaed2b178edc7d3278c5c6ffa625be8d1)
> 
> @getchoo explain yourself, please

What? but that's obviously a boolean condition?

**Comment by getchoo** [comment]
> Found the culprit: [ae711c3](https://github.com/NixOS/nixpkgs/commit/ae711c3e33a9143e92cb1108b537321a365947f6) (while glancing over [60e405b...3b5d63c](https://github.com/NixOS/nixpkgs/compare/60e405b241edb6f0573f3d9f944617fe33ac4a73...3b5d63ccaed2b178edc7d3278c5c6ffa625be8d1))
> 
> [@getchoo](https://github.com/getchoo) explain yourself, please

I think the PR and linked issue explain why this was implemented in the way it was

The breakage here comes from the (IMO totally reasonable) assumption `enableWlrPortal` is a boolean. This is true in all cases except the Hyprland module, where for whatever reason, a `lib.mkDefault` expression [is passed](https://github.com/NixOS/nixpkgs/blob/26d499fc9f1d567283d5d56fcf367edd815dba1d/nixos/modules/programs/wayland/hyprland.nix#L118) when making a primitive `import` of the changed file. This is a good example as to why module system structures and language primitives shouldn't be mixed, as they're [quite different in their effects](https://wiki.nixos.org/wiki/The_Nix_Language_versus_the_NixOS_Module_System)

This seems to have already been fixed in https://github.com/NixOS/nixpkgs/pull/394858, but remains in the stable branch due to it not being backported; https://github.com/NixOS/nixpkgs/pull/400957 has been made to now do that

**Comment by getchoo** [comment]
Fixed by the above

**Comment by guttermonk** [comment]
Has the fix been added to 24.11? Still getting: `error: ‘mkIf’ called with a non-Boolean condition`

**Comment by h7x4** [comment]
@guttermonk: You can track when the PR hits the different branches here: https://nixpk.gs/pr-tracker.html?pr=400957

**Comment by malikwirin** [comment]
> Has the fix been added to 24.11? Still getting: `error: ‘mkIf’ called with a non-Boolean condition`

It works for me

**Comment by h7x4** [comment]
The fix is already landed in `release-24.11` and `nixos-24.11-small`, but not in `nixos-24.11` which runs a different set of tests in hydra. Having one working and another not could just be that your nixpkgs instances come from different branches. I believe everything is going to be fixed in probably less than 72 hours, once the PR has been merged everywhere.

It's also possible to use `nixos-24.11-small` in the meanwhile. It has all packages despite its name - just fewer cached ones. See https://wiki.nixos.org/wiki/Channel_branches#The_official_channels for a better explanation.

**Comment by eclairevoyant** [comment]
-small branches are generally a bad idea. Not only are most packages uncached -- by nature, they are also untested.

Just wait.

**Comment by Schuasda** [comment]
@malikwirin 

    … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/programs/wayland/hyprland.nix':

       … from call site
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:35898:
       … while calling 'dischargeProperties'
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:38713:
       … from call site
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:38912:
       … while calling 'dischargeProperties'
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:38713:
       … while calling the 'throw' builtin
         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:38972:
       error: ‘mkIf’ called with a non-Boolean condition

i am using the standard 24.11 channel, so @h7x4 explanation makes sense to me. I will just wait, but it kinda sucks, that this prevents me from changing my config in any other way as well...

**Comment by eclairevoyant** [comment]
You can always roll back your channel or lockfile if you need to make other changes in the meantime.

**Comment by Jan-Koll** [comment]
> @guttermonk: You can track when the PR hits the different branches here: https://nixpk.gs/pr-tracker.html?pr=400957

The PR seems to be merged now in nixos-24.11. After a `nix flake update` and `nixos-rebuild switch` the error was resolved for me.
