### ISSUE TITLE
Build failure: flycast

### ISSUE THREAD

**Issue by nPrevail** [NixOS/nixpkgs#414098]
### Nixpkgs version

- Stable (25.05)

### Describe the bug

I receive the following output when trying to run `sudo nixos-rebuild switch --upgrade`:

```
[ 74%] Building CXX object CMakeFiles/flycast.dir/core/network/naomi_network.cpp.o
make[2]: *** [CMakeFiles/flycast.dir/build.make:2585: CMakeFiles/flycast.dir/core/network/miniupnp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:522: CMakeFiles/flycast.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/r3jh2pnywygygp1ajhwfzc5glcxk08jm-flycast-2.4.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/ab8rvz734b48r4rjacv4fh703cmnig9a-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j8pdapdrm7h42n43r4zazcgzl9xcph5j-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qamj50hz4qs4yayrii1hjq253jcx9c7c-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d9hhn37wx4766y099mkim589arjimrjz-nixos-system-nixos-25.05.803396.8f1b52b04f2c.drv' failed to build

```

I know there's no maintainer at the moment, but I wanted to put this out there.

Does anyone know if this gets fixed in Flycast version 2.5? I see it's available in `unstable`.

I may consider using the `flatpak` version for now....

### Steps to reproduce

Have `pkgs.flycast` in your nixos config file.

Run `sudo nixos-rebuild switch --upgrade`

### Expected behaviour

You'll get the output mentioned above

### Relevant log output

```console
[ 74%] Building CXX object CMakeFiles/flycast.dir/core/network/naomi_network.cpp.o
make[2]: *** [CMakeFiles/flycast.dir/build.make:2585: CMakeFiles/flycast.dir/core/network/miniupnp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:522: CMakeFiles/flycast.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/r3jh2pnywygygp1ajhwfzc5glcxk08jm-flycast-2.4.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/ab8rvz734b48r4rjacv4fh703cmnig9a-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j8pdapdrm7h42n43r4zazcgzl9xcph5j-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qamj50hz4qs4yayrii1hjq253jcx9c7c-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d9hhn37wx4766y099mkim589arjimrjz-nixos-system-nixos-25.05.803396.8f1b52b04f2c.drv' failed to build
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.14.9, NixOS, 25.05 (Warbler), 25.05.803396.8f1b52b04f2c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - channels(root): `"nixos-25.05"`
 - nixpkgs: `/nix/store/cx77jv4ryh7hkh2r041cf9hnf9y3q2i7-nixos-25.05/nixos`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by applePrincess** [comment]
At least I can see 2.5 builds on hydra for nixpkgs:trunk i.e. master branch

https://hydra.nixos.org/build/299060015

**Comment by applePrincess** [comment]
And I can build 2.5 on unstable branch c2a03962b8e24e669fb37b7df10e7c79531ff1a4 (HEAD at the time of writing).

**Comment by phanirithvij** [comment]
should be fixed now, https://github.com/NixOS/nixpkgs/pull/413994

close this issue if it works.

you need to update your channels or flake

**Comment by nPrevail** [comment]
It's still not building properly for NixOS 25.05 (stable). It still builds Flycast 2.4, and not 2.5. Same error:

```
make[2]: *** [CMakeFiles/flycast.dir/build.make:2585: CMakeFiles/flycast.dir/core/network/miniupnp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:522: CMakeFiles/flycast.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/r3jh2pnywygygp1ajhwfzc5glcxk08jm-flycast-2.4.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/ab8rvz734b48r4rjacv4fh703cmnig9a-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j8pdapdrm7h42n43r4zazcgzl9xcph5j-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qamj50hz4qs4yayrii1hjq253jcx9c7c-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d9hhn37wx4766y099mkim589arjimrjz-nixos-system-nixos-25.05.803396.8f1b52b04f2c.drv' failed to build

```

**Comment by phanirithvij** [comment]
Sorry I was mistaken, it still needs to reach nixos-25.05 see https://github.com/NixOS/nixpkgs/issues/414072#issuecomment-2944918229

**Comment by nPrevail** [comment]
Flycast was able to be rebuilt, and runs! 

Closing this issue.

Thank you!
