### ISSUE TITLE
waybar: crashes while running remmina

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#423670]
### Nixpkgs version

- Stable (25.05)

### Describe the bug

If I start remmina (just start no need to do anything) it kills my waybar, and the waybar cannot be restarted until after I exit remmina. If restarting waybar manually I get the error in the log below.

### Steps to reproduce

Run remmina with a sway session that has waybar.

### Expected behaviour

waybar should not crash

### Relevant log output

```console
** (waybar:39398): WARNING **: 10:42:08.695: Status Notifier Item with bus name ':1.119' and object path '/org/ayatana/NotificationItem/remmina_icon' is already registered

(waybar:39398): Gtk-CRITICAL **: 10:42:08.696: gtk_icon_info_load_symbolic_for_context: assertion 'icon_info != NULL' failed
zsh: segmentation fault (core dumped)  waybar
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.35, NixOS, 25.05 (Warbler), 25.05.20250629.b43c397`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - nixpkgs: `/nix/store/j95fcik6rzsydwips4m89dmlvfj9hg9y-source`

### Notify maintainers

waybar: @FlorianFranzen @lovesegfault @minijackson @rodrgz @Synthetica9 @khaneliman
remmina: @bbigras @melsigl @ryantm

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by minijackson** [comment]
Hmmm, it looks like the same issue that was fixed in #421229. Can you confirm that you are on the latest version of the nixos-25.05 branch?

**Comment by brianmay** [comment]
Was almost going to complain that the problem was not fixed.

Then I work up and realized the fix was in waybar, not remmina. Oops.

If I update waybar, it seems to work fine after the fix.
