### ISSUE TITLE
X11 crash at end of nixos-rebuild switch --upgrade

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#44344]
## Issue description

```
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
Please consult the The X.Org Foundation support
        at http://wiki.x.org
for help.
```

See [syslog.txt](https://github.com/NixOS/nixpkgs/files/2253026/syslog2.txt) for more informations. 
Maybe related to https://github.com/NixOS/nixpkgs/issues/39791 https://github.com/NixOS/nixpkgs/issues/40218

### Steps to reproduce

1. `nixos-rebuild switch --upgrade`
2. at the end of the rebuild where the services get restartet, my GNOME 3 session crashes and i get to tty1, after some seconds the GDM login screen is visible and i can login again to GNOME

It happens on some upgrades on my Lenovo Thinkpad L470. (my X230 don't have this problem)

Also happens on rollback to a version where it happened.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133004.a1299c9951b (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03, nixos-hardware, nixos-unstable-18.09pre143771.a8c71037e04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
It's actually not every upgrade. This time everything works as expected.

```
these derivations will be built:
  /nix/store/24mcrlasnskm3m1kvkwfq5w89iiiwgzx-youtube-dl-2018.05.01.drv
  /nix/store/s1bdycaib9y2hglsrzkcacswgw9dzcf1-vim_configurable-8.0.1451.drv
  /nix/store/05c8myvafhmakswhskgfc8p4dpj7sknb-system-path.drv
  /nix/store/8w5zws7gqcqswb6s9rndkjggpklfibig-xsession.drv
  /nix/store/110j2922dq65hsn3z3awg1n41401p18x-desktops.drv
  /nix/store/47sgc3bfyylwd967p5sg8ab9n8cm7ad7-kernel-modules-shrunk.drv
  /nix/store/sq6r44v2ssaazd4izp6yhkkwzscfs8ff-breeze-plymouth-5.12.6.drv
  /nix/store/lh0pdnvdwvg1m6jbz94v3dh3vdfvw1jd-plymouth-themes.drv
  /nix/store/4nva6bmj43wpq8mli5jxhzwlf29jk0pv-extra-utils.drv
  /nix/store/g0gigj13fq8w45skp16jbns380rwg8jg-udev-rules.drv
  /nix/store/72i31bwnacphm83m186hzqskgdr3lr6a-stage-1-init.sh.drv
  /nix/store/2fqwrggjvk8alkmdjbghpi689gkds4ib-initrd.drv
  /nix/store/2mnz56c8ldymbqzac0h05w7l3k5b5lmh-xserver.conf.drv
  /nix/store/4c8v1aq7f0d4a37c804qp3iy554am17d-unit-systemd-fsck-.service.drv
  /nix/store/672mm692c1wlsp4r4hr01jvqqc37k90y-unit-script.drv
  /nix/store/67dgiq0c8h9qnvwlv0kkwjbpichi5w1l-gdm.pam.drv
  /nix/store/7bqbg9q1v07nzr89jphj6hl4nkh83fh9-unit-polkit.service.drv
  /nix/store/7chz1173y151qvihlnnc9wgcxdb4sq3m-unit-nix-gc.service.drv
  /nix/store/7fbgrnr9b85mf640j9f54si70lwjgxsn-unit-colord.service.drv
  /nix/store/y51wj4xfn45l5z2sfjvdkan0b5akflg4-dbus-1.drv
  /nix/store/87p0jj1m3m9gbbnzrsr5qgs4lr9cjacl-unit-dbus.service.drv
  /nix/store/8m2lg7lflsv6qgp6jdm6vbkvlys9533i-unit-script.drv
  /nix/store/qf6byg8y8jz4a3n5wmxi0nm0gy2pjqjr-unit-script.drv
  /nix/store/8w9bykw4aydghm4672c76zi846m2h99a-unit-nixos-upgrade.service.drv
  /nix/store/azppmlfm252kxjdkxkpv76ypj7d1bf6d-unit-packagekit.service.drv
  /nix/store/kf74nsp1d14vjyml5j1zrflwsvr6hzzk-unit-upower.service.drv
  /nix/store/krskspyxbi4ns048pfhicnrz0598ln2s-unit-nix-daemon.service.drv
  /nix/store/m6nmhk36q8hah6lzdpl929f78sa0ldjk-unit-udisks2.service.drv
  /nix/store/nnx84zk94wfpn059ivifxw347vqnhi48-unit-vboxnet0.service.drv
  /nix/store/fagsqc7dya4390s52cx9g79zr2y99yn9-extra-udev-rules.drv
  /nix/store/s4qr74fmjcjq9shhsw2qnmyxxkj8zhai-unit-systemd-udevd.service.drv
  /nix/store/yb7408rdgg5lgjj3qbxwysvd332sw1x1-unit-display-manager.service.drv
  /nix/store/yg2bl8dhwrxcw4zxap3gwhbl2501da93-unit-nix-optimise.service.drv
  /nix/store/cz0i2kcmz866fgljq1h8pzbbg085n51n-system-units.drv
  /nix/store/dkyjwkf8xcfmc0y3biq2f8625nbfrm7v-issue.drv
  /nix/store/j56wmkx8y1ihb92w0zsmyda1xnxh612g-user-units.drv
  /nix/store/kl5v0k6wb9yb7533z26lcfqmlcnvcjfc-etc-os-release.drv
  /nix/store/n9g5h3p031g2jb8lh18z7afblvgn0z40-gdm-password.pam.drv
  /nix/store/qkp0djnghzlsg577h48l7vh8sfpcvfbg-udev-rules.drv
  /nix/store/rkibn7lp5nwld3y6jvvj2cjnzkqj6yd8-etc-profile.drv
  /nix/store/swf7b8piyvj6wryiz0h64zh2i04p3f0p-hwdb.bin.drv
  /nix/store/gdy8zjx17c8mim7ih104j6srfycyz7zw-etc.drv
  /nix/store/wnsrqxvjss5afq4aslh36vig5lii8m9m-systemd-boot-builder.py.drv
  /nix/store/p9dyjfsq5dcn7fyx621zjggv0njic290-nixos-system-nixos-18.03.133017.0e55dde2eaa.drv
these paths will be fetched (712.39 MiB download, 3306.57 MiB unpacked):
  /nix/store/00jnw1kfa4b08iw8vqmvg1inxjx0zld4-pantheon-terminal-0.4.3
  /nix/store/0331kadqakv8975kriwf19a5b1q7rbqr-ghex-3.18.3
  /nix/store/05pl5in0x7abw2fqd09bmihivxwvn800-qtmultimedia-5.10.1-bin
  /nix/store/06v22csyb3cza3jnfrxg9nkr6s09n4am-gnome-logs-3.26.3
  /nix/store/0812k2mx8nbnyhsihrx8ayjxpsfla8zp-gegl-0.3.28
  /nix/store/09hipv8b6khqcfjx6hsrj0hp357nbsql-network-manager-applet-1.8.6
  /nix/store/0bjvdrzfapnmd7b4prw0zrw50wv7h1v4-gupnp-dlna-0.10.5
  /nix/store/0n20jynfkcpwir3svil56jiin6f8f2f8-gnome-user-docs-3.26.2.1
  /nix/store/0pdxxk9kiw1anxjlbllxrgdyinm774jd-glu-9.0.0
  /nix/store/0px3argiyl7mxy1l3qrnjnpvv7pgi9nw-libgdata-0.17.9
  /nix/store/0ra4k2sygizgfz31pzlgywq4yx97x59h-pavucontrol-3.0
  /nix/store/0slhqyvrdwjr07k9cm0jvkpswpc6lr3m-kernel-modules
  /nix/store/10xlanzzznzy0npr7420v8b377wj7jcn-at-spi2-core-2.26.2
  /nix/store/18ih9iywg9ajm8fq3cn38zhq8d968hcl-opengl-drivers
  /nix/store/1dzwqf2pc0j38x7skg2hcs7krm9jw8kr-libspectre-0.2.7
  /nix/store/1fhz7f68dna4xxiy0n4jqcv6hn7m6chf-hexchat-2.12.4
  /nix/store/1id9sm8kni4k5c0ca5xc0z0s2ca2kyv5-epiphany-3.26.6
  /nix/store/1sajxrhr22b3d0zqf7bb20sy33r3fzs7-mesa-noglu-17.3.6-drivers
  /nix/store/1yv2v4nzsb82ar5akbi6s8kg3bax8y6j-gnome-characters-3.26.2
  /nix/store/21bm1ddd78yp1xsxy1vrgkdzmg58w6l7-json-glib-1.4.2
  /nix/store/237hz3fy4wia3y6fra6kdh71mjmmm161-libdbusmenu-gtk3-16.04.0
  /nix/store/24ickjn87803plw1l88pbczxr272wvhx-vino-3.22.0
  /nix/store/2948w33g8jk0rd12np57b3cbc33njs95-json-glib-1.4.2-dev
  /nix/store/2by3rq2ldzjqh6kh3h4gba2b85a2nh6n-plymouth-0.9.3
  /nix/store/2c3bzn0s3lzz8mp6j3rkl37vbix3sng9-xf86-video-ati-7.9.0
  /nix/store/2f45xvax8mbc8z483m5rihfpxy8iz1w9-gsound-1.0.2
  /nix/store/2m33l6xnp9ffrq2cjc9ifcnn5awlvwnc-freerdp-2.0.0-rc2
  /nix/store/2mlag4flrk396zpazqgzvimhddcg6cvk-simplescreenrecorder-0.3.9
  /nix/store/2p4glg2xix5ak6am9n8d6ghcxh7sq8zk-udisks-2.1.6-man
  /nix/store/2pcrbj4irn066qvygch1myik3d05fqi5-qtmultimedia-5.10.1
  /nix/store/2rxkpr15i4cdwznhpzd5bpdbpljl64xy-libcanberra-0.30
  /nix/store/2sams5jisaj01wb3qr83i9wy6p36vikh-greybird-3.22.6
  /nix/store/2wh0hbcxs07pfwj5xza1r2h1vam7z3sl-gtkspell-3.0.9
  /nix/store/2wjxxqv6h1fqyi8dinlcq56wh6n1vxl0-gnome-packagekit-3.26.0
  /nix/store/30xppapbssskjwwm0qh4pdgxsvm42n90-nautilus-3.26.2
  /nix/store/3176cxw8flwl9k2z1r53h67dvkpdbgd0-gnome-calculator-3.26.0
  /nix/store/378krwfrgr80xfqpr5s9l6hb09kpj8bd-clutter-gst-3.0.24
  /nix/store/37mi6vp5a5i07060801yvv68lsm8ywkd-xf86-video-vesa-2.3.4
  /nix/store/3c5rdsh3zsslqiphccb92v9b8blm92rb-yelp-3.26.0
  /nix/store/3fyfndsqqwgyg7bnhkshfrlf0xckn87i-python3.6-pygobject-3.26.1-dev
  /nix/store/3k0iap81pvprhq17py73gni3ghi9cfaq-gvfs-1.34.2
  /nix/store/3k59x6mw1ng7ks60yca3x56p48y5zp94-totem-3.26.0
  /nix/store/3nph4vq403n89hsgsfrmzsk76xdasqvd-grilo-plugins-0.3.5
  /nix/store/3sc2cz2ppnhwakmb9b3wav9lzwhplahz-qtlocation-5.10.1-bin
  /nix/store/3ss0paipj0rxmp481k72nzy0ahp2s4ij-libxklavier-5.3
  /nix/store/3xpdz54fglnjx0wgcfg3jwnf5vxf8c9c-gnome-screenshot-3.26.0
  /nix/store/3xz40d6j40pabp7jxvi0m99za0pv0iag-geoclue-2.4.7
  /nix/store/3zfqqbiq2p0w5fpm2v6a3b248yicgz4v-imagemagick-6.9.9-34-doc
  /nix/store/42hi676nyfpm68049239c8phyifwm69y-gtk+3-3.22.28-dev
  /nix/store/43hhi0j14r4prmlx3bb823nx34p8ahlz-gnome-software-3.26.7
  /nix/store/43ljvdb31lha4i1ldbyzzqlgwkvqpxbp-net-snmp-5.7.3
  /nix/store/450drdmv5wh3dv01srcamg40x6w00dpi-colord-1.4.1
  /nix/store/45fws0fl2vv0lm2rzni3ncnlad4p75vw-imagemagick-6.9.9-34-dev
  /nix/store/47yfl25d59xq65vnv6wxwymvvply3hn3-libgweather-3.26.1
  /nix/store/4glnip7zzy2bi44sdhbcldjsvgw84bgk-gnome-bluetooth-3.26.1
  /nix/store/4mmyymvli6v56wbjjlr0f2xar127yikz-gtk-vnc-0.7.0
  /nix/store/4mwm4n71zyx9cbr5ah7bwq2plrmzxs4h-colord-gtk-0.1.26
  /nix/store/4q9262v7bh92qj96cfd1fkbyz3l1pycf-sushi-3.24.0
  /nix/store/4ql4apzd3802jpqz5fjlgf5k1h08drhc-dconf-0.26.1
  /nix/store/4qr08wn3dr923kpc7ldvdjivs6lx6fwn-gtkmm-2.24.5
  /nix/store/4vij1h9k3faq4qddz92f4ppv8z9czllz-tracker-2.0.3
  /nix/store/4xsjlrncqp59qaxhdval5nf2ip8dadm6-libindicator-gtk3-12.10.1
  /nix/store/4z1r94sp4byv666wr9vg9z502v1przy1-libmwaw-0.3.13
  /nix/store/53y3c4ahi7cw1hxcg7zjz53f9n0l62fb-gnome-maps-3.26.2
  /nix/store/56zpc0f6qd5vpp84ljbfsi6qzk718k7v-phantomjs-2.1.1
  /nix/store/58mh05mlhw9p3n62a24ycvqfqk9hfkgk-dleyna-core
  /nix/store/5bfgbs0n6fbf19nnynw71dmw8ci3s5d1-liferea-1.12.2
  /nix/store/5bkbgm4kacis8xkbj5cxs1k0lpnxd7az-cheese-3.26.0-man
  /nix/store/5h8kvf9nfp4wdvvwg0zwxsi7zn7l9rnp-dconf-editor-3.26.2
  /nix/store/5llfpf69xy89m82iiz1hh7jv8ag67vdg-libsecret-0.18.5
  /nix/store/5lr3na5jzg9rg418dmyas253xrgxlnr8-qtdeclarative-5.10.1-bin
  /nix/store/5ml07yr190wyaa9zbzx7acy1l71lg3xp-gconf-3.2.6
  /nix/store/5pp3jag61r48pqrhpzkgvylf1xl1qwqw-djvulibre-3.5.27
  /nix/store/5sl8hjgm12f9c30vx5hk6ins4gdrhi8s-accountsservice-0.6.46
  /nix/store/5vgv4gbhlwr69c176di260slrv085bcs-accerciser-3.22.0
  /nix/store/5wza204wvk2nwdic3msd418k98342pm5-NetworkManager-vpnc-gnome-1.2.6
  /nix/store/6000is8qwliawkify1870i4bk8bhv4n0-gnome-power-manager-3.26.0
  /nix/store/66165kykv6nyd4apxyi3y41ijrr5bdrl-cairomm-1.12.2
  /nix/store/6an4n543qmdjb0vy5z2lrj63c0nm60s7-gnome-session-3.26.1
  /nix/store/6g15qmfpssipgj0sp9dz5mwhspp9n6dg-cheese-3.26.0
  /nix/store/6j031ql2120bkal97ch50da7qmcbnywm-cogl-1.22.2
  /nix/store/6k66rn4nbdm4xwimgmyb905mq6sb7zbv-pangomm-2.40.1
  /nix/store/6kdq71sdxz10hn0wr2jki260ad46gx87-atom-1.25.1
  /nix/store/6r3js1xlpqvhjmdrxk0bcc7lrn3fvqag-file-roller-3.26.2
  /nix/store/6sf97mdmpmcknylhmcgj2pn3j21rkwdn-remmina-1.2.30.1
  /nix/store/6vrwzn50w64ih4ws1hq741sl1cvzbrgx-gpa-0.9.10
  /nix/store/70zfx3x4j7jrbfwcam7m8wb7n5ccfj4k-libva-full-2.0.0
  /nix/store/774v9nwsxbdaz710aa2a1x0bird0l6h4-gusb-0.2.11
  /nix/store/7nh1xn84f54fipwbrs4lh1f8bfkqa6hv-keepassxc-2.3.1
  /nix/store/7p3mbpnwxbwd02a16dnfgpc8pjf03jil-meld-3.18.0
  /nix/store/7qsq0cy90hnpzflw0vda3zkb08kp3rky-qtbase-5.10.1-bin
  /nix/store/8087x8wqqq3pjp59kv96vjpyii971ghg-obexftp-0.24
  /nix/store/81xc6lyzfzil2k6yll8lr1ljabajmzp2-mesa-noglu-17.3.6
  /nix/store/841qlnkvxf7q56aasx6zhis9k8n4wxxg-mpv-0.27.0
  /nix/store/855m90jixn06kdwas34v6k0fds5nr7ww-SDL-1.2.15
  /nix/store/8im7sbvxqnp98zpkcz3hqpirw34vpf2s-geocode-glib-3.24.0
  /nix/store/8l1qbqpkfi4yjqf3vwii7lys2gvw8x1b-NetworkManager-strongswan-1.4.1
  /nix/store/96pjvdvi52r1vfq0ib92g297gdc8aajq-gpgme-1.11.1
  /nix/store/96ra3i8cwqdl5bcfl695hvm0hzyy15wc-python3.6-dbus-python-1.2.4
  /nix/store/98yq0nq52vxv2fh9x3h9qwq502nn77fd-atk-2.26.1-dev
  /nix/store/9dfk43nvxrgfpgvm5xmx91cqq624z8x7-strongswan-5.6.3
  /nix/store/9dkjaharf22gdhp2gs400j86w1l17v5v-libgnome-keyring-3.12.0-dev
  /nix/store/9hhnh9rx04hksygbn5676dqsjgm15y9k-gnome-shell-3.26.2
  /nix/store/9i5sdca9v8l7qnl4kh47qlgs7k51vck2-libreoffice-5.4.5.1
  /nix/store/9jhl90nd83pxx800mlz1p8ky1zargrbg-mesa-drivers+txc-17.3.6
  /nix/store/9rm0y4wvla0ik7ligjwbpynir3k7ckv1-vte-0.36.3
  /nix/store/9vx9lc68dzl8j85lij4dmmfnckc9nisv-librsvg-2.42.2
  /nix/store/9xqmf3phgcdhydmiwlvz8n5s4mfl9nda-mesa-17.3.6
  /nix/store/9yn9ajyqhrja1q9gqv6hasdmgqzihrjq-NetworkManager-openconnect-gnome-1.2.4
  /nix/store/a17qbpyxs6xd3z77qbpdbi94v5rzafdk-python3.6-pycairo-1.15.4
  /nix/store/a1arg60zbbhzssxablfk1s67ggji2820-evince-3.26.0
  /nix/store/a47qwmxvvbsh494b8ly1fi6k9shj2vr9-libgsf-1.14.41
  /nix/store/a4mfrqs06w8kpnd26r2pgicvm3czvcj7-libappindicator-gtk3-12.10.0
  /nix/store/a594pl90pk4rhdsd576nq0110pcrz6zg-granite-0.5
  /nix/store/a60xrgpwlnaql76qsvq9gkhjf5jbhfpa-libtxc_dxtn_s2tc-1.0
  /nix/store/aif0j8q66hfj6m1sg5a2ispa0lc0mwsl-gnome-clocks-3.26.1
  /nix/store/ak5ifzi5p5pdfs5gm0wyp3ls86cigynk-atk-2.26.1
  /nix/store/algbgh43pbw1zs3l3mdyjx1fx9607bl2-telepathy-mission-control-5.16.4
  /nix/store/aqy4ap8slkwqfxgxjvybf3mn6xpy7n85-pinentry-1.1.0
  /nix/store/b1kxa6kdj9xlh386bj4fk0nvx7m7f863-libwpg-0.3.2
  /nix/store/b2dvzjnzz8vhiixi20fy7wf7shqq0p0a-libpeas-1.22.0
  /nix/store/b7sx61f0rw7418b1y8gzh68a3z8x4dhw-qtsvg-5.10.1-bin
  /nix/store/bgkny452zy6k7b632hgbz8avc2i3banv-gnome-music-3.26.2
  /nix/store/bjah6yfivi39xgaa783q9fjhzpyl8c90-glu-9.0.0-dev
  /nix/store/bn80mbf8kplg12h7w0h030q3j2lllfpq-librsvg-2.42.2
  /nix/store/bpcf1jan8f6fbdwzafvfql2zxx06yc2l-gdk-pixbuf-2.36.7
  /nix/store/bq0iwybdnq6hcav91zraglsqkk6c2j6a-harfbuzz-1.7.1
  /nix/store/c05hd888ifvlxw8z9ai07s8r9jipf5z8-grilo-0.3.4
  /nix/store/c81lg4awjjbx7jqgzq66pmvy3rs6wwad-NetworkManager-openvpn-gnome-1.8.0
  /nix/store/cbyccn344k1db3a7qmw3w07zqgxkyqb7-ModemManager-1.6.8
  /nix/store/cbyg65gwsj6jlkj9s72kmd57r33j061g-libmediaart-1.9.4
  /nix/store/cii2cq2jr2g4lmb4nx6sr3nmb81dzlyg-libgee-0.20.1
  /nix/store/cj7x0bnf2j75la0jvmn9xjf32dha4r0n-epoxy-1.3.1
  /nix/store/clqa8i5rkdj021s5kipy0xhjv5h0f8ky-libnotify-0.7.7
  /nix/store/cm1v9hi7y23k128x4mx131jbl7qdacil-xwayland-1.19.6
  /nix/store/cpd2dn5pdwzzpapidvmaf7q1116s0cak-polkit-0.113
  /nix/store/cqzb4lnhvcp2vrq6rcq4bsplw731ny93-gnome-user-share-3.18.3
  /nix/store/cv3n0j9dmc3lqbhdgkvlynzc6gz7d0nl-libass-0.14.0
  /nix/store/cvf6yjql1iprvalv7mnlg2nqc87djk5m-folks-0.11.4
  /nix/store/d2358mx9ba92xmwz1d98pygn8wdjayfz-libzapojit-0.0.3
  /nix/store/d2nvw3y4fsjlxyraiipyr1jgv0ipharn-gsettings-desktop-schemas-3.24.1
  /nix/store/dcmrjlwbi8blgfrwpv5jlmr10x6jc2bq-gnome-disk-utility-3.26.2
  /nix/store/dgii7a9vay8c3jvrxwwymfypmlqik7xg-gnome-mpv-0.13
  /nix/store/dkmzzs9bg2jjvf78w7cbb0s8ym90i518-qtxmlpatterns-5.10.1
  /nix/store/dkx1pspzbvibq1prfk62423xyq52fha8-gst-plugins-good-1.12.3
  /nix/store/dm7sws3damhbjjhzzas6nqdkch9c14x5-telepathy-glib-0.24.1
  /nix/store/dzh4g2p1izdj1j7gnx2vgy80xdd82f5p-python3.6-pygobject-3.26.1
  /nix/store/f1n42nx22wgp1587d41a4p8g21i41sfh-pyatspi-2.18.0
  /nix/store/f292nmb698bn7kw7wfffz9li4d4h8mm6-nixos-gsettings-desktop-schemas
  /nix/store/f3mnh73893lh0pmdacn1y0i6b2pf1igr-virtualbox-modules-5.2.14-4.14.59
  /nix/store/f7d70i3vbk9r09wbgvsw01n1rf3k6443-pango-1.40.14
  /nix/store/fd0m5zkz0pvkvl7pga4in2qy8z73xyr2-libgnome-keyring-3.12.0
  /nix/store/fdlyjxgbpx3n1mz7acy3130kyry10aac-seahorse-3.20.0
  /nix/store/fdpysl8vz3rdk5q35slz84lccyfj2pra-imagemagick-6.9.9-34
  /nix/store/ff2avqwdp12gc46z3ahgxc5ia6hfgilg-gnome-photos-3.26.3
  /nix/store/fixrcl7syq7ixxg3r09pn2w0aqsqaldg-vinagre-3.22.0
  /nix/store/fjh268dqn5szr368ajhl0swyk1zxzppp-gnome-settings-daemon-3.26.2
  /nix/store/fplpbwvaxp6gjks16yn9apl9pq5i0z91-gst-plugins-ugly-1.12.3
  /nix/store/fyk89qpjfa3dr1rl4f2q94q1m080x9h2-libodfgen-0.1.6
  /nix/store/fzzlsyj56snkcvkbpm9qh3n2iap23y38-virtualbox-5.2.14
  /nix/store/g06idk3icgn6gq26kbdq4jj51j53zf8i-xorg-server-1.19.6
  /nix/store/g4ip6wa9528mjk1j06x6x14gzqspyrnc-gnome-weather-3.26.0
  /nix/store/g4lxbi7w2pjwwl9k2jlgwinyxnp9dxhw-upower-0.99.7
  /nix/store/gd0j1sf586y4d48j1ya58rqxlp90wiwd-libwpd-0.10.0
  /nix/store/ggjq9l8ipj1b8k5v8mghp89aa64v53n5-stoken-v0.90
  /nix/store/ghwbf7zj5r72n8lxby03wx64raacan0m-gmime-2.6.23
  /nix/store/gkqpplcmvp2c0wr0qj5hq5f264123mfr-gnome-system-monitor-3.26.0
  /nix/store/gmb5df1xw4va1ifa9l9gd1y9lkm47yww-dleyna-connector-dbus
  /nix/store/gq6sgvhyxdnyh7ly8ybf6f3jnxzggfjb-gstreamer-1.12.3
  /nix/store/gqc3ph65prkrjg2kn4n2c5d6xxfy1av8-evolution-3.26.5
  /nix/store/gz90q9kww1gvz0n33w3jfc4alwkljawn-gobject-introspection-1.54.1-dev
  /nix/store/h3ibs7pwq0x0pjh7sn3di2zm6a4nfn1x-gupnp-1.0.2
  /nix/store/hd2szmv3mdwp2wl1nc8lzy4c35vxcmv6-baobab-3.26.1
  /nix/store/hhvkqg0fxk7a3hy900b6632zj79ndwk4-gjs-1.50.4
  /nix/store/hn87wfpw8xl70lyfzqsh7h94xgiwyc7d-eog-3.26.2
  /nix/store/hqsdbc0zf7v6b9xyjw02wc86fggszjfq-nautilus-sendto-3.8.6
  /nix/store/hx98s7d6mv9s1r1s3m6xrxhcr2l5b6h9-harfbuzz-1.7.1-dev
  /nix/store/hxhp1ifm3d2ngv6knsxssn6psmw1rq6p-gexiv2-0.10.8
  /nix/store/hxv45b6ghw5gfackddnrcykgc9371a2f-NetworkManager-l2tp-gnome-1.2.8
  /nix/store/i120cjga8iq6dlfhw7kwzh0kfxsj7gqz-gvfs-1.34.2
  /nix/store/i155j7867k9h5g20a7q65wpn1vgxbni8-gnome-terminal-3.26.2
  /nix/store/i5bcq78cfngmlw4r00y88mwbz7f2w3dm-gupnp-av-0.12.10
  /nix/store/i84aqycczkffr3nyscskvfnivdzagk23-openjdk-8u181b13-jre
  /nix/store/i93jr4dcb83l5wwsw3lhrab72y1pyyzy-gnome-calendar-3.26.3
  /nix/store/ifzzdsiw9ddal13xy7hl68sf3a32h70q-gtk+-2.24.32
  /nix/store/ig1sqdwjar8d0i3k5gsd4zj1k184sbqm-caribou-0.4.21
  /nix/store/iqa4fbpm33xwxswg88qxvlzc6fc4fq5r-openjdk-8u181b13
  /nix/store/j1v8ld0b8pzpf9nkz8xzqj8d1vkmlfvz-gtkmm-3.22.2
  /nix/store/j2ir4iwp6i0lm7xirkrni5h0jqkigjhg-ffmpeg-3.4.3-bin
  /nix/store/j5jx5vb25lbc96hp8l2ia2l41vkgv2qh-xf86-video-vmware-13.2.1
  /nix/store/j7i1b76l71gbx3jfi63zymaa8sb17fcn-libvisio-0.1.3
  /nix/store/j8pj9y032vsrbrj95kkv701w0ayy4ylw-gnome-themes-standard-3.22.3
  /nix/store/jczqylzzi1kpdq2qxz1ycwx50iv9dh79-qtlocation-5.10.1
  /nix/store/jjjnqwnwa7zwfip8609wyzh4ps0gm493-openobex-1.7.2
  /nix/store/jn23wgzgxpiha4srv85ddmaryq4gdyfp-gst-libav-1.12.3
  /nix/store/k2c387bkjfa7g6xb62i03xh0xiglk6a5-gconf-2.32.4
  /nix/store/kbrsf9rmaysijyr1zfhfkwrv11687f5w-gst-plugins-base-1.12.3-dev
  /nix/store/kdwrdgxq3ax2pvaxngi72644vkz0658r-clutter-1.26.2
  /nix/store/kp8dln81vazwpnvw7q3ym46x1svp85s3-gst-plugins-base-1.12.3
  /nix/store/kx6d8ln1ww3wf4ilgsy4qwsy6g33m02g-cairo-1.14.10
  /nix/store/kx7fmlzzkjrskaz1gkb8faykjpj6d1dl-poppler-glib-0.56.0
  /nix/store/kxlkr978d9g1flc41d4r54di12as4g81-firefox-unwrapped-61.0.1
  /nix/store/kz8fadwyz1f72klqz2xf04152vkpd283-polkit-0.113-bin
  /nix/store/l5swcjr5gix56a7qmyd7qnm147hcjmn6-gconf-3.2.6-dev
  /nix/store/l5zb1kb9jnsa4dzb9cpy7864c3hw00kl-gnome-tweak-tool-3.26.4
  /nix/store/ladyrpgpya56i2idvdlnczc0fgqn3fvk-qtsvg-5.10.1
  /nix/store/lgj2jfl54y3pz0w3hxs6nwja7n7w5cj5-elementary-xfce-icon-theme-2017-11-28
  /nix/store/lj5vlp391k22qcydcws5mbcny9h8a9qh-dleyna-server
  /nix/store/lmsq3ik7zd3sanvhnd9vn0yq6p6764qk-gedit-3.22.1
  /nix/store/lqjql5nlxkda7gss1w4gg3mzvzq04gwr-chromium-68.0.3440.75-sandbox
  /nix/store/lr9k166msxz1aq7l82g14iwng1l7v5fj-gtksourceview-3.24.6
  /nix/store/ls746fcvxgi1d4yh4qx83p0lskd0g96v-gtk-engine-murrine-0.98.2
  /nix/store/lzi3k2fa5xyx2lf1gbqmr9hy0qhm3vvk-qtdeclarative-5.10.1
  /nix/store/m4kv2903c7zn7mx9032qz6wl9glm5g5p-libcdr-0.1.4
  /nix/store/m71lwjfvjjgmx4d74m58x2p8i65zqb01-ostree-2018.4
  /nix/store/m8lmvxpiv580c1qpa7h4fj1y7n3lm469-gcr-3.20.0
  /nix/store/m9fl03bqjha6j543s2fj6lbiqbxk86ga-thunderbird-52.9.0
  /nix/store/mbkzsndn53rlza3ya1xp5a68rw8y40df-gnome-menus-3.10.1
  /nix/store/ml8ghv3vr2gvxasdjyjqf3gwxh8zdbpf-pango-1.40.14-dev
  /nix/store/mnlgyxd06pzfs97fkqc9ckqyyb56lkkw-gparted-0.30.0
  /nix/store/msmw6n1xfcg986fiwba7120phz37prar-nixos-icons-2017-03-16
  /nix/store/mz78n164r8vn593j31h24drik1hvv3ki-mesa-noglu-17.3.6-dev
  /nix/store/n4adjr1vl88vw71rscxql9ap476cy63d-gnome-online-miners-3.26.0
  /nix/store/n66xm4knss53kgvd9s0ph9q09z2230si-libgnomekbd-3.26.0
  /nix/store/ncl0rbhr1csq4cw9ib8if93l48zvs3za-gnome-online-accounts-3.26.2-man
  /nix/store/ng4ff0gx16c2gb0kjrhab2inn2gwdzsr-harfbuzz-icu-1.7.1
  /nix/store/ngv1r2g85al65gnb8q0r8n7j6yvx5vij-gnome-control-center-3.26.2
  /nix/store/ngwmccra01f3g8f6vh4mrqk28vmbr3fh-gnome-system-log-3.9.90
  /nix/store/njxm9kvsj3spdzdqbrfgmlif6isrca3v-gnome-autoar-0.2.3
  /nix/store/nmn608d28abh406gac5xzyqqllw1ng2c-file-5.32
  /nix/store/nr7f4yc94vww66h7akcf4r09yn8ki4w8-xdg-utils-1.1.2
  /nix/store/nswa94jy2cmagvpa538bqbjf763y0m0b-gdk-pixbuf-2.36.7-dev
  /nix/store/nyp04csxcwyp7qscfl0ywbm3jjdlds3m-sane-backends-1.0.27
  /nix/store/p051qyvjlqxa5d8xry2v0xhwr8bbphkd-dleyna-renderer
  /nix/store/p44xskblxix7yxqyhnjmgal9rl2qjqka-vte-0.50.2
  /nix/store/p45dg9h342v8fw8kcy5bbznryc1jmdjk-udisks-2.1.6
  /nix/store/p99h2g6i06yybgfqwbfgg9hywnp2dag2-glib-networking-2.54.1
  /nix/store/p9f20bdpz7v2dipw403q2za22jzmfrhd-qtwebkit-5.9.1
  /nix/store/pb404qxmv1n2mpvgxjnz6fzm65kry9zx-firefox-61.0.1
  /nix/store/piqdnkdpkzyb1ppfaww0w16vfx0s0xqr-python3-3.6.6-env
  /nix/store/pj1w2g16jmpwcfw2vjz1a32iz3n9hfnk-libcanberra-0.30
  /nix/store/plcw0kisr6x6rykk1xglkkn3rx53xrj1-packagekit-1.1.8
  /nix/store/pp26893i1gw252k6npll625n3hmpbk2s-gtk+3-3.22.28
  /nix/store/pxv664lyv6rj143a131g5kl1a7rylzz9-tracker-miners-2.0.4
  /nix/store/q1i08xv5ix87ankkb0crmsxp9n5jiwgv-libchamplain-0.12.16
  /nix/store/q3xy9fdvp1da2a8kxpvngr5f3ba2shqp-xf86-input-libinput-0.26.0
  /nix/store/q483kvjm8rphh342z4md1zc8fwlcswrs-gnome-vfs-2.24.4
  /nix/store/q5dd2knlpv5c49hccn1ybzlp14bdiglh-clutter-gtk-1.8.4
  /nix/store/qcfj7vw5479c4nh3mwj2z5kycb0c4d79-gnome-shell-extensions-3.26.2
  /nix/store/qq3mn05fjcvyrsj5529bxhdf46sm25r4-gdm-3.26.2.1
  /nix/store/qwmxdcw14dx5kmrjr0wq40wa7whbw6sg-qtsensors-5.10.1-bin
  /nix/store/qzxcqg608bjdj8gaw5dr9vik97icwxa4-dconf-0.26.1-lib
  /nix/store/r1hwyj9v5dna583krw40sfrlbjj23m1j-xf86-video-cirrus-1.5.3
  /nix/store/rgn59m2mbykhdndq06has2bfgzg45cvn-gnupg-2.2.8
  /nix/store/rhiw1ds89ypij96i7yhan83j6dm48amn-gfbgraph-0.2.3
  /nix/store/ri4w9gkclf7ff3c4mhi9dvlzxm2hdngk-gnome-online-accounts-3.26.2
  /nix/store/rn826yfd8q6l0sg2jnlvhsaw1x4z4pla-telepathy-logger-0.8.2
  /nix/store/rrvj5jcnkwjzhfiwb45fzqk7fmzd4zm2-libsoup-2.60.2
  /nix/store/rv5anlasxz2jhsah1jy15mgvvfqq5170-spice-gtk-0.34
  /nix/store/rw5px16kizwas8hksyhk9x413d83r8sk-ibus-1.5.17
  /nix/store/rzfvpcmfykppcld8pjrnjy00ny7i8qcs-ffmpeg-3.4.3
  /nix/store/s1p5q26wwdwd1d485jdwdccwbgp6xqbf-libsoup-2.60.2-dev
  /nix/store/s2qdadk2xkjfm5jahlflbj1bhcyycsvn-chromium-68.0.3440.75
  /nix/store/s40cfwczmic3qm4wqbyw7sz50mfza3b1-evolution-data-server-3.26.5
  /nix/store/s5azwlp8wmk85pq5d9ingazdhwnihbh3-cairo-1.14.10-dev
  /nix/store/s77shsnlx78y4fdshm6idm646wks2n9m-dhcp-4.3.4
  /nix/store/s9sj8zi3bk442pm4b82yfrbs9q81dimg-SDL2-2.0.8
  /nix/store/sb9h2lxnmi04wgx5hs8ihd10p8a8lllh-mesa-noglu-17.3.6
  /nix/store/sgfc1rx845pi0h11ckmd9g6aqf03lv7j-gnome-keyring-3.20.1
  /nix/store/sinpckqf9g9pv50jyspm311zkdy6kn77-nixos-install
  /nix/store/sk1i9dkdzf65sb57v402kdazm3hvmg42-libproxy-0.4.15
  /nix/store/sk3lqc860dblxhzr4jjs4mv1sr7bp5fl-gstreamer-1.12.3-dev
  /nix/store/skfhfyxjjw9lyhv2v2cdyi61pyhkky5a-libxklavier-5.3-dev
  /nix/store/spma5al3aj1xmp9ki4ap13ia88ri0xw7-mutter-3.26.2
  /nix/store/sxn56v7pimvpmzwl5m1dyayrkcm3m6mb-qtbase-5.10.1
  /nix/store/syjk5rks1ayjkd62fl79pzwbv09lball-gssdp-1.0.1
  /nix/store/szwywk0jwjyn7vlhcnv190hr954m8qi7-libsecret-0.18.5-dev
  /nix/store/v0jd5fj19nd33hw5lgl2qk16zmh5vfx1-gst-plugins-base-0.10.36
  /nix/store/v2wfjxdfz3dhqnns3f6wmb4z3jm329gr-NetworkManager-iodine-gnome-1.2.0
  /nix/store/vc4ay7gi8jpm6iic304375828rsiz095-gnome-contacts-3.26.1
  /nix/store/vw039x8sj2nk89nprp021ijk7irg60yz-qtsensors-5.10.1
  /nix/store/vwqcajs385f2wy86xa3lbqs699fkv5zd-nixos-version
  /nix/store/vxc1n3z6fxs2d6mbq6zscl5qrf3qkwx7-twemoji-color-font-1.3
  /nix/store/vyrvyhwk743c1da7y20xhnp5i95q77z5-libgepub-0.5.3
  /nix/store/vys2wkxs65wxa9pni0xp1qj2720v3bwh-network-manager-1.10.2
  /nix/store/vyxk1ll85rvmr3wkvmxp3mr5fsa900v3-gnome-desktop-3.26.2
  /nix/store/w4h57imccpr0n6pvic3md3xsz4n5lifb-youtube-dl-2018.05.01
  /nix/store/w6dhrw2wl0ypqd2n139hw53x3kgkh68w-libgtop-2.38.0
  /nix/store/wjrp5dan82waaym475lzv3zfakyakrcr-gspell-1.6.1
  /nix/store/wmxlf58ffhawr3d9wn9j10vhj3a0xgb1-webkitgtk-2.20.3
  /nix/store/x0sq1rys22i5h0dby1aqnfqhnpm7js11-NetworkManager-fortisslvpn-gnome-1.2.4
  /nix/store/x64420x53qg5j0691qs66kh34cimv5ym-bluez-5.48
  /nix/store/xf83mk9mqwc18xcfa1r27wdys3i4dcab-gnome-font-viewer-3.26.0
  /nix/store/xldkgddbiwxnssnhm8icsijlkzha2r76-adwaita-icon-theme-3.26.1
  /nix/store/xn95x20q4wfbhcz9crc7z5rfwafjaa0v-openconnect-7.08
  /nix/store/xrszdj3n8bzw9kfv702js9039zfqly7p-appstream-glib-0.7.6
  /nix/store/xxv83kj6mhvyr7bfw1p56vk955i4bmfp-xf86-input-evdev-2.10.5
  /nix/store/y2yhvw4ayz3mgc01byi5xam80ckbq6fg-pango-1.40.14-bin
  /nix/store/ya22805njp1gif0vrd4223fvv62wckbp-chromium-68.0.3440.75
  /nix/store/yarnzva0zixnp96vc96fabn3g87byczv-qt-4.8.7
  /nix/store/yb5rnip831zy8ar1a1h3j5jgchpyy9zz-gobject-introspection-1.54.1
  /nix/store/ykpwns0aclip31s8k78i4dvhnzf1102n-gst-plugins-bad-1.12.3
  /nix/store/ynd48l9kspmxz4x758a1q37v5yqwcmbv-gnome-documents-3.26.2
  /nix/store/ypycljz8c3jlvgjclm6xy08qijxiqnk7-inkscape-0.92.2
  /nix/store/yqlm7h7mvyzlhx2bi5y9zv1yafqgljyp-chromium-68.0.3440.75-sandbox
  /nix/store/ywncxp0b6y55lq9ml2kq9lf4a1c9jyfi-gst-plugins-good-1.12.3-dev
  /nix/store/z1lk1mp1pifql6hjcm9zlzlha40c56lx-atkmm-2.24.2
  /nix/store/z1s0xw5qhhvdij8142177qkaac3dmlqa-totem-pl-parser-3.26.0
  /nix/store/z5cjvy3392h9hnz07b74cfddbkbb5ahz-gnome-nettool-3.8.1
  /nix/store/z8hdxa70y2zm7kr63kflfm72x5yqhdmd-simple-scan-3.26.3
  /nix/store/z8kyrkda61jdn5vagp4dhcyfbhvbrynv-gcab-1.1
  /nix/store/za8wfdw1nih9ms9q4g37by16dy0wsfkq-pipewire-0.1.9
  /nix/store/zb7187l6idlci848yf4jyl8x16y8fm7r-libreoffice-5.4.5.1
  /nix/store/zd3ss1rbnk9w08lcsv7fwpwhs1ia1mpx-qtx11extras-5.10.1
  /nix/store/zdjma6jgbm0k2k90rcy7zmzw9m6drbc0-rest-0.8.1
  /nix/store/zjly5dck6mcwdqcb2wkrdv3mmsifwbia-at-spi2-atk-2.26.1
  /nix/store/zkkb6xp7ik18y8q5m2vvv7gm4hg3v28y-gucharmap-10.0.3
  /nix/store/zlykmg9fyp7gcrq8y5nga0xmd9rnc824-xf86-video-intel-2017-10-19
  /nix/store/zn9z7awa95zp5xzl7lgn6q2qrclz2rqm-librsvg-2.42.2-dev
  /nix/store/zv4lwwql3w3s771a6a7lq62md9pjwqxf-nix-2.0.4-dev
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.59, NixOS, 18.03.133017.0e55dde2eaa (Impala)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.133017.0e55dde2eaa, nixos-hardware, nixos-unstable-18.09pre143771.a8c71037e04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by davidak** [comment]
Another rebuild without problems including

```
  /nix/store/55zwn8g6nqnip8f6dyk4x729ncrpjfxv-system-path.drv
  /nix/store/s522zmfp1vzlk5l77ymmgrxb7flxlf7v-xsession.drv
  /nix/store/0iqp3m5xgbdz5yiaxqmnpha5hr8llrj1-desktops.drv
  /nix/store/109g1na7grsv4l2q4xm4vvdwynzwcc6y-unit-display-manager.service.drv
  /nix/store/4bpdg06vgs4225srjlsf0dbs9xcr1rbi-unit-systemd-fsck-.service.drv
  /nix/store/519mlybi9ib1v18nm0wzxwinbdq7c1cm-unit-cpufreq.service.drv
  /nix/store/vlgs7kncl7i1bd5fg8wq4jswvirzcxih-kernel-modules-shrunk.drv
  /nix/store/fvy7ii0lbnnba6m6wdj434bh4vy942xh-stage-1-init.sh.drv
  /nix/store/54f602ck0rmd866n5a8c0j3scj5dp8jj-initrd.drv
  /nix/store/5lqfh53aw5zrz5h1fy5218hpq9sjg5vl-etc-nixos.conf.drv
  /nix/store/p21l5xmv2qc506qan1flp4swkkncdn51-dbus-1.drv
  /nix/store/kkrplxn5qn95rbsjzjb05i4k4xwgpigs-unit-dbus.service.drv
  /nix/store/wkkjxcwdyawmkacgj3ls6wmm81iyh0cs-unit-polkit.service.drv
  /nix/store/g03samj2zx47b1301d4p6h0mg4hk0nqb-system-units.drv
  /nix/store/pxqd2kfmpf908xv6lp5b7yr61l4yd55p-user-units.drv
  /nix/store/wd19pl6ry5qrhxg887rxl5a97ni7199y-issue.drv
  /nix/store/x1x3f355bq00wn9krfzja65hzswg4y19-etc-os-release.drv
  /nix/store/bj6mvip6m7x29id3rlsx8nzc2kr78ysx-etc.drv
  /nix/store/cqsnpz4zm5zl6qqvhbsg6pi0l4f3nrf8-nixos-system-ethmoid-18.03.133034.230f98aa79b.drv
these paths will be fetched (63.58 MiB download, 121.62 MiB unpacked):
  /nix/store/6x1s9qn07n9xiivwbxw72kgskam8wdq8-linux-4.14.60
  /nix/store/adnl12g8z38rximlhf7w6hw9w2fx359n-virtualbox-modules-5.2.14-4.14.60
  /nix/store/l79bchg8i8wi85m3gkpaq0g7ys6wndr4-firmware
  /nix/store/p74487jwds0kadagljiyhnz73wab6i57-cpupower-4.14.60
  /nix/store/q89dy4n1z9hjc4pilx3gsvjrni33i2d3-nixos-version
  /nix/store/qxli28dnhvw1drb4pri5zjymzzp126jj-python3-3.5.6
  /nix/store/r7f47mmh4l6hq9i640143cswksfjk79i-kernel-modules
```

So this might be fixed somehow.

I close it now and observe the next updates.

**Comment by davidak** [comment]
This time it happened again. See 
[syslog.txt](https://github.com/NixOS/nixpkgs/files/2302307/since.txt)

**Comment by davidak** [comment]
I have done an update after 2 weeks vacation and it happened again.

syslog:
```
Sep 10 11:08:22 ethmoid systemd[1]: Started Nix Daemon.
Sep 10 11:08:22 ethmoid nix-daemon[31010]: accepted connection from pid 31005, user root (trusted)
Sep 10 11:08:22 ethmoid nix-daemon[31010]: accepted connection from pid 31014, user root (trusted)
Sep 10 11:08:23 ethmoid nix-daemon[31010]: accepted connection from pid 31031, user root (trusted)
Sep 10 11:08:28 ethmoid nix-daemon[31010]: accepted connection from pid 31038, user root (trusted)
Sep 10 11:08:30 ethmoid nixos[31045]: switching to system configuration /nix/store/91yw4baf4aflw9xx41fyx3f0ynvx3kxf-nixos-system-ethmoid-18.03.133192.45f52f765cd
Sep 10 11:08:30 ethmoid systemd[1]: Stopped target Local File Systems.
Sep 10 11:08:30 ethmoid systemd[1]: Stopped target All Network Interfaces (deprecated).
Sep 10 11:08:30 ethmoid systemd[1]: Stopped target Remote File Systems.
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitored file `/etc/group` was moved into place, adding watch
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitoring file `/etc/group` (6)
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitoring directory `/etc` (2)
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitored file `/etc/passwd` was moved into place, adding watch
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitoring file `/etc/passwd` (7)
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitoring directory `/etc` (2)
Sep 10 11:08:30 ethmoid nscd[29867]: 29867 monitored file `/etc/hosts` was moved into place, adding watch
Sep 10 11:08:30 ethmoid polkitd[29778]: Reloading rules
Sep 10 11:08:30 ethmoid polkitd[29778]: Collecting garbage unconditionally...
Sep 10 11:08:30 ethmoid polkitd[29778]: Loading rules from directory /etc/polkit-1/rules.d
Sep 10 11:08:30 ethmoid polkitd[29778]: Loading rules from directory /var/run/current-system/sw/share/polkit-1/rules.d
Sep 10 11:08:30 ethmoid polkitd[29778]: Finished loading, compiling and executing 4 rules
Sep 10 11:08:30 ethmoid polkitd[29778]: Reloading rules
Sep 10 11:08:30 ethmoid polkitd[29778]: Collecting garbage unconditionally...
Sep 10 11:08:30 ethmoid polkitd[29778]: Loading rules from directory /etc/polkit-1/rules.d
Sep 10 11:08:30 ethmoid polkitd[29778]: Loading rules from directory /var/run/current-system/sw/share/polkit-1/rules.d
Sep 10 11:08:30 ethmoid polkitd[29778]: Finished loading, compiling and executing 4 rules
Sep 10 11:08:30 ethmoid systemd[1]: Reloading.
Sep 10 11:08:30 ethmoid systemd[1]: Reached target Local File Systems.
Sep 10 11:08:30 ethmoid systemd[1]: Reached target Remote File Systems.
Sep 10 11:08:30 ethmoid systemd[1]: Starting PackageKit Daemon...
Sep 10 11:08:30 ethmoid systemd[1]: Reached target All Network Interfaces (deprecated).
Sep 10 11:08:30 ethmoid systemd[1]: Starting Tell Plymouth To Write Out Runtime Data...
Sep 10 11:08:30 ethmoid PackageKit[31313]: daemon start
Sep 10 11:08:30 ethmoid PackageKit[31313]: daemon quit
Sep 10 11:08:30 ethmoid systemd[1]: Started Tell Plymouth To Write Out Runtime Data.
Sep 10 11:08:30 ethmoid packagekitd[31313]: Failed to load the backend: opening module nix failed : /nix/store/yd2i58l2bj7lm3y7ng4jcny9k1c5gxy9-packagekit-1.1.8/lib/packagekit-backend/libpk_backend_nix.so: cann>
Sep 10 11:08:30 ethmoid systemd[1]: Started PackageKit Daemon.
Sep 10 11:08:30 ethmoid systemd[1]: Starting Terminate Plymouth Boot Screen...
Sep 10 11:08:30 ethmoid nixos[31045]: finished switching to system configuration /nix/store/91yw4baf4aflw9xx41fyx3f0ynvx3kxf-nixos-system-ethmoid-18.03.133192.45f52f765cd
Sep 10 11:08:30 ethmoid systemd[1]: Started Terminate Plymouth Boot Screen.
```

dmesg: [Untitled Document 1.txt](https://github.com/NixOS/nixpkgs/files/2366007/Untitled.Document.1.txt)

**Comment by davidak** [comment]
Problem still reproducible.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.82, NixOS, 18.09.1436.a7fd4310c0c (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.1436.a7fd4310c0c, nixos-hardware, nixos-unstable-19.03pre159472.80738ed9dc0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
Another time where it was **not** reproducible.

stopping the following units: accounts-daemon.service, colord.service, cpufreq.service, modem-manager.service, network-manager.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, udisks2.service
NOT restarting the following changed units: **display-manager.service**, systemd-fsck@dev-disk-by\x2duuid-1455\x2d7FCD.service
activating the configuration...
setting up /etc...
reloading user units for gdm...
reloading user units for davidak...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service
starting the following units: accounts-daemon.service, colord.service, cpufreq.service, modem-manager.service, network-manager.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, udisks2.service
the following new units were started: systemd-hostnamed.service

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.97, NixOS, 18.09.2132.109a28ab954 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2132.109a28ab954, nixos-hardware, nixos-unstable-19.03pre168781.929cc78363e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
The problem is still reproducible.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.108, NixOS, 18.09.2390.40e716b92a7 (Jellyfish)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2390.40e716b92a7, nixos-hardware, nixos-unstable-19.09pre173166.373488e6f4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by kraem** [comment]
I, also, get these occasional freezes when `nixos-rebuild switch`ing.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.15, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.09pre226482.28357868f82"`
 - channels(kraem): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Please tell me if I can provide any more info that would help.

As a side note I get also get freezes sometimes when opening `virt-manager` after my system has been suspended. Might be a correlation as I see you also have `virtualisation.libvirtd.enable = true;` in your config.

**Comment by andersk** [comment]
I believe this was fixed by #70357, #71065, and #100569.

**Comment by dasJ** [comment]
This issue is still referenced in the manual in `17.7.2. Why does nixos-rebuild switch sometimes kill my session?`

**Comment by andersk** [comment]
@dasJ Indeed, opened #157320 to remove that.
