### ISSUE TITLE
rpi-imager: error: builder for '/nix/store/...-rpi-imager-1.9.4.drv' failed with exit code 1

### ISSUE THREAD

**Issue by turbotimon** [NixOS/nixpkgs#461249]
### Nixpkgs version

- Stable (25.05)

### Describe the bug

`nix-shell -p rpi-imager` fails

### Steps to reproduce

After I updated the 25.05 channel, it suddenly fails

### Expected behaviour

not to fail

### Relevant log output

```console
$nix-shell -p rpi-imager
this derivation will be built:
  /nix/store/9ymk5b5hllggn4naxc4w491csrip29xx-rpi-imager-1.9.4.drv
building '/nix/store/9ymk5b5hllggn4naxc4w491csrip29xx-rpi-imager-1.9.4.drv'...
Running phase: qtPreHook
Running phase: unpackPhase
unpacking source archive /nix/store/k2mpywh314ls37n5g7ff1c3xvybld0x0-source
source root is source/src
Running phase: patchPhase
applying patch /nix/store/f7sk9fmk8yrxns3a8jmfilm54az7iqxc-remove-vendoring-and-lsblk-check.patch
patching file CMakeLists.txt
Running phase: updateAutotoolsGnuConfigScriptsPhase
Running phase: configurePhase
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/share/doc/rpi-imager -DCMAKE_INSTALL_INFODIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/share/man -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/include -DCMAKE_INSTALL_SBINDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/kks0nbx2riwry5qsx0qr87qr0lswmhzi-gcc-wrapper-14.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/kks0nbx2riwry5qsx0qr87qr0lswmhzi-gcc-wrapper-14.3.0/bin/ranlib -DCMAKE_AR=/nix/store/kks0nbx2riwry5qsx0qr87qr0lswmhzi-gcc-wrapper-14.3.0/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/x72scvj608gqkdcw4d2lfhv9y82qy7gd-rpi-imager-1.9.4 -DENABLE_VENDORING:BOOL=FALSE -DENABLE_CHECK_VERSION:BOOL=FALSE -DENABLE_TELEMETRY:BOOL=FALSE -DQT_OPTIONAL_TOOLS_PATH=/nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3 -DQT_OPTIONAL_TOOLS_PATH=/nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3
-- The CXX compiler identification is GNU 14.3.0
-- The C compiler identification is GNU 14.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/kks0nbx2riwry5qsx0qr87qr0lswmhzi-gcc-wrapper-14.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/kks0nbx2riwry5qsx0qr87qr0lswmhzi-gcc-wrapper-14.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /nix/store/f2q5ld1nipl8w1r2w8m6azhlm2varqgb-zlib-1.3.1/lib/libz.so (found version "1.3.1")
-- Looking for lzma_auto_decoder in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so
-- Looking for lzma_auto_decoder in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so
-- Looking for lzma_easy_encoder in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so
-- Looking for lzma_lzma_preset in /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so - found
-- Found LibLZMA: /nix/store/6ab07lf8v6zjcjr8ysxcsf13kn8593vb-xz-5.8.1/lib/liblzma.so (found version "5.8.1")
-- Found CURL: /nix/store/nshhjm3s9pwc86s5hyzqf22pn8kikw8j-curl-8.14.1/lib/libcurl.so (found suitable version "8.14.1", minimum required is "8.13.0")
-- Found LibArchive: /nix/store/b7lgmwg8dcm6qvi62sncv1r9k7pl70vs-libarchive-3.8.2-lib/lib/libarchive.so (found suitable version "3.8.2", minimum required is "3.7.8")
Package p11-kit-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `p11-kit-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'p11-kit-1', required by 'gnutls', not found
Package p11-kit-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `p11-kit-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'p11-kit-1', required by 'gnutls', not found
Package p11-kit-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `p11-kit-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'p11-kit-1', required by 'gnutls', not found
Package p11-kit-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `p11-kit-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'p11-kit-1', required by 'gnutls', not found
-- Found GnuTLS: /nix/store/zrqnaqv2l3vq6w80jwaf5qhgjjkdk937-gnutls-3.8.9/lib/libgnutls.so (found version "3.8.9")
-- Performing Test atomicbuiltin
-- Performing Test atomicbuiltin - Success
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found OpenGL: /nix/store/if6m6nami517vhq99phj9jmy8fzg44ap-libglvnd-1.7.0/lib/libOpenGL.so
udisks2 support enabled
CMake Error at /nix/store/mi969jlnxpiizlmpi0j4n6h8k63iyd3x-qtbase-6.9.3/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:1146 (get_property):
  get_property could not find TARGET rpi-imager.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:321 (_qt_internal_get_target_autogen_build_dir)
  /nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:976 (qt6_add_lupdate)
  CMakeLists.txt:332 (qt_add_lupdate)


-- Configuring incomplete, errors occurred!
error: builder for '/nix/store/9ymk5b5hllggn4naxc4w491csrip29xx-rpi-imager-1.9.4.drv' failed with exit code 1;
       last 25 log lines:
       > Package p11-kit-1 was not found in the pkg-config search path.
       > Perhaps you should add the directory containing `p11-kit-1.pc'
       > to the PKG_CONFIG_PATH environment variable
       > Package 'p11-kit-1', required by 'gnutls', not found
       > Package p11-kit-1 was not found in the pkg-config search path.
       > Perhaps you should add the directory containing `p11-kit-1.pc'
       > to the PKG_CONFIG_PATH environment variable
       > Package 'p11-kit-1', required by 'gnutls', not found
       > -- Found GnuTLS: /nix/store/zrqnaqv2l3vq6w80jwaf5qhgjjkdk937-gnutls-3.8.9/lib/libgnutls.so (found version "3.8.9")
       > -- Performing Test atomicbuiltin
       > -- Performing Test atomicbuiltin - Success
       > -- Performing Test HAVE_STDATOMIC
       > -- Performing Test HAVE_STDATOMIC - Success
       > -- Found OpenGL: /nix/store/if6m6nami517vhq99phj9jmy8fzg44ap-libglvnd-1.7.0/lib/libOpenGL.so
       > udisks2 support enabled
       > CMake Error at /nix/store/mi969jlnxpiizlmpi0j4n6h8k63iyd3x-qtbase-6.9.3/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:1146 (get_property):
       >   get_property could not find TARGET rpi-imager.  Perhaps it has not yet been
       >   created.
       > Call Stack (most recent call first):
       >   /nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:321 (_qt_internal_get_target_autogen_build_dir)
       >   /nix/store/3q57rmja601hbj5y4fnd888cggq0fw5k-qttools-6.9.3/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:976 (qt6_add_lupdate)
       >   CMakeLists.txt:332 (qt_add_lupdate)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run:
         nix log /nix/store/9ymk5b5hllggn4naxc4w491csrip29xx-rpi-imager-1.9.4.drv
```

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.57, NixOS, 25.05 (Warbler), 25.05.812676.c2448301fb85`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.5`
 - channels(root): `"nixos-25.05, unstable"`
 - nixpkgs: `/nix/store/igxxaqzi057by2pjgh4rqsv1xz5hr8np-nixos-25.05/nixos`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CaffeinatedOpe** [comment]
Experiencing an identical issue on nixos unstable.

**Comment by RoubenRehman** [comment]
I've tested on 25.05 and unstable and can confirm the issue exists on both. Installing rp-imager from 24.11 works.

**Comment by jeremystucki** [comment]
I think this might has been solved by https://github.com/NixOS/nixpkgs/pull/460416 as I cannot reproduce it on master.

**Comment by robotfishe** [comment]
I am experiencing the same on 25.05 stable. @CaffeinatedOpe 's fix worked for me.

**Comment by IgnoreWarnings** [comment]
Can confirm the same problem still exists on  25.11. The above mentioned fix still works.
