### ISSUE TITLE
nixos-option broken and 18.09 beta

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#47722]
## Issue description
cc @samueldr @vcunat is this a release blocker?
```
$ nixos-option networking.useDHCP

This attribute set contains:
error:
syntax
error,
unexpected
:,
expecting
```

### Steps to reproduce

Run `nixos-option` on current 18.09 beta (7f70ebf30b8). Unstable seems to be affected too.

## Technical details

Seems to be a fairly simple case of nixos-option capturing *all* the output of nix-instantiate, including the missing-NIX_PATH-entry warning. I'll have a look at fixing this.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.71, NixOS, 18.09beta696.7f70ebf30b8 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09beta696.7f70ebf30b8, nixos-unstable-19.03pre154105.e1605d9b21b"`
 - channels(steam): `""`
 - channels(linus): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by lheckemann** [comment]
I suppose this is just a consequence of #40165, combined with poor handling of the warning by `nixos-option`.

**Comment by vcunat** [comment]
I expect this is fixed since ee582a32d25 then.  I'm unable to reproduce it on 18.09beta676.66fd61163a8, even with `sudo` etc.

**Comment by lheckemann** [comment]
@vcunat no, it's not — this still happens when it's expanded correctly if `~/.nix-defexpr/channels` doesn't exist.

**Comment by vcunat** [comment]
@lheckemann: can you also re-test this patch: de93b32?

**Comment by lheckemann** [comment]
Yep that fixes it!
