### ISSUE TITLE
Pipenv fails to create virtualenv outside of `nix-shell`

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixpkgs#48107]
## Issue description

Running `pipenv install` in a project that doesn't already have a venv fails with the following message:

```
 $ pipenv install                                                                                                                                                                                
Creating a virtualenv for this project...
Pipfile: /path/to/Pipfile
Using /nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/bin/python3.6m (3.6.6) to create virtualenv...
⠋/nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/bin/python3.6m: Error while finding module specification for 'pipenv.pew' (ModuleNotFoundError: No module named 'pipenv')

Virtualenv location: 
Traceback (most recent call last):
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/bin/.pipenv-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/core.py", line 1759, in do_install
    pypi_mirror=pypi_mirror,
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/core.py", line 614, in ensure_project
    path_to_python = which('python') or which('py')
  File "/nix/store/wayj9fv1kmvp6rnzjyjv70kzqh87k2q7-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/core.py", line 115, in which
    p = os.path.join(location, 'bin', command)
  File "/nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This happens when Pipenv is installed with `nix-env -i pipenv` or by adding it to `systemPackages`, but not when ran in a `nix-shell -p pipenv`. It also does not happen if the venv already exists.

Running `pipenv --rm && pipenv install` triggers the error again (if ran outside of `nix-shell`).

### Steps to reproduce

1. `nix-env -i pipenv`
2. `cd $(mktemp -d)`
3. `pipenv install`

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.18.12, NixOS, 19.03pre154487.0a7e258012b (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-19.03pre154487.0a7e258012b"`
 - channels(teo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teozkr** [comment]
Even weirder, this also happens when ran using `nix run nixpkgs.pipenv`.

**Comment by teozkr** [comment]
Seems like the culprit is that `$PYTHONPATH` is set by `nix-shell`, but not the others. Copying the contents of that env variable makes it work in both `nix run` and the user profile.

**Comment by stig** [comment]
I have this problem too. Thanks @teozkr for the work-around :-)

**Comment by zauberpony** [comment]
I have the same issue, and tried to dig a little bit into it.

IMO the problem is, that pipenv executes "python -m 'virtualenv'" as a subprocess ([in core.py](https://github.com/pypa/pipenv/blob/6e793a402a410675e08e470306a7b1ba9291de86/pipenv/core.py#L874)), so the `virtualenvwrapper` import in ".pipenv-wrapped" does not apply.

If startet with PYTHONPATH, that environment variable gets passed to the subprocess, so that's why the workaround is possible.

**Comment by stig** [comment]
@zauberpony do you have a suggestion for how this could be fixed? Do you feel this should be fixed in `pipenv` itself, or is a fix in Nixpkgs more appropriate?

**Comment by adisbladis** [comment]
This should have been fixed by 11d491dce56b964dffd0175f891299bee646501d.
@teozkr Could you check and close if it's fixed?

**Comment by das-g** [comment]
I tried steps to reproduce from [the issue descripton](https://github.com/NixOS/nixpkgs/issues/48107#issue-368194457) on NixOS 19.03

> 1. `nix-env -i pipenv`
> 2. `cd $(mktemp -d)`
> 3. `pipenv install`

<details><summary>output of <code>nix-env -i pipenv</code> (click to expand)</summary>

```
installing 'pipenv-2018.11.26'
these paths will be fetched (8.82 MiB download, 30.52 MiB unpacked):
  /nix/store/1ivbmg3kg1pnp81jr8c76p4r1mdcgg62-python3.7-virtualenv-16.4.1
  /nix/store/30whm1n7baz436a2850bqz4gix0m5612-python3.7-mccabe-0.6.1
  /nix/store/67svzmip2y006da5hxk0alw3lzksjmiw-python-recursive-pth-loader-1.0
  /nix/store/6paazxg5gqjv2q1jskbq6s6n67xm9fvr-python3.7-invoke-1.2.0
  /nix/store/86b79h895inhj9h6z3qzyq6pja4yjbrz-python3.7-pip-19.0.3
  /nix/store/8jcync4248iq73ny01cw8j7w5m94y37y-python3.7-entrypoints-0.3
  /nix/store/9la2vqlkfylxgk807bw4pgajzzzsa2sf-python3.7-pyflakes-2.1.0
  /nix/store/c9lwp70y0kc4099d8as403pdn5hdsjnn-python3.7-virtualenv-clone-0.5.1
  /nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26
  /nix/store/j36596qp47qnasx17nlrrd1f43c1ngnq-python3.7-Arpeggio-1.9.0
  /nix/store/kh5mjxssksavsz6l3jj8dd3jd3ssvvwc-python3.7-parver-0.2.1
  /nix/store/m4afsmk95qd54xi464pzlhw1bl1911xa-python3.7-attrs-18.2.0
  /nix/store/msg8v0f7kp9hpx6i57cfrcp98bihk7fm-python3.7-flake8-3.7.6
  /nix/store/w0r3pnqa88yypkp0jyg8abi1vvzv0s5b-pew-1.1.2
  /nix/store/wnl1qp6f9rmic2pnpx7q9g581drb8768-python3.7-pycodestyle-2.5.0
copying path '/nix/store/67svzmip2y006da5hxk0alw3lzksjmiw-python-recursive-pth-loader-1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/j36596qp47qnasx17nlrrd1f43c1ngnq-python3.7-Arpeggio-1.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/m4afsmk95qd54xi464pzlhw1bl1911xa-python3.7-attrs-18.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/8jcync4248iq73ny01cw8j7w5m94y37y-python3.7-entrypoints-0.3' from 'https://cache.nixos.org'...
copying path '/nix/store/6paazxg5gqjv2q1jskbq6s6n67xm9fvr-python3.7-invoke-1.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/30whm1n7baz436a2850bqz4gix0m5612-python3.7-mccabe-0.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/86b79h895inhj9h6z3qzyq6pja4yjbrz-python3.7-pip-19.0.3' from 'https://cache.nixos.org'...
copying path '/nix/store/wnl1qp6f9rmic2pnpx7q9g581drb8768-python3.7-pycodestyle-2.5.0' from 'https://cache.nixos.org'...
copying path '/nix/store/9la2vqlkfylxgk807bw4pgajzzzsa2sf-python3.7-pyflakes-2.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/1ivbmg3kg1pnp81jr8c76p4r1mdcgg62-python3.7-virtualenv-16.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/msg8v0f7kp9hpx6i57cfrcp98bihk7fm-python3.7-flake8-3.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/kh5mjxssksavsz6l3jj8dd3jd3ssvvwc-python3.7-parver-0.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/c9lwp70y0kc4099d8as403pdn5hdsjnn-python3.7-virtualenv-clone-0.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/w0r3pnqa88yypkp0jyg8abi1vvzv0s5b-pew-1.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26' from 'https://cache.nixos.org'...
building '/nix/store/cr92r8a14rrj8b1nbhwgf87dv3kyx0ji-user-environment.drv'...
created 2 symlinks in user environment
```

</details>

output of `pipenv install` in fresh temporary dir:

```
Creating a virtualenv for this project…
Pipfile: /tmp/tmp.0l7MmpS7uM/Pipfile
Using /nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/bin/python3.7 (3.7.3) to create virtualenv…
⠋ Creating virtual environment...
✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/h3249czbivbqjan2z3qp0jqj1xpx4fmq-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: /nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/bin/python3.7: No module named virtualenv

Failed to create virtual environment.
```

So that's a different error message, but still not working as expected.

Like the original error, this one also occurs with `pipenv` is uninstalled again and the steps to reproduce are repeated with `nix run nixpkgs.pipenv` instead of `nix-env -i pipenv`, but not with `nix-shell -p pipenv` instead of  `nix-env -i pipenv`. (With `nix-shell -p pipenv` it seems to work as expected.)

---

 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.12, NixOS, 19.03.172470.a177da6b86e (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172494.2dcbd447e42"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rawkode** [comment]
I've tried this on unstable, unfortunately it still fails:

```
Creating a virtualenv for this project…
Pipfile: /home/rawkode/Code/src/github.com/rawkode/influxdb-crime-san-francisco/Pipfile
Using /nix/store/10rqw9cx8x2knwdaxhlyb4drla8v8zzk-python3-3.7.4/bin/python3.7 (3.7.4) to create virtualenv…
⠋ Creating virtual environment...
✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: /nix/store/10rqw9cx8x2knwdaxhlyb4drla8v8zzk-python3-3.7.4/bin/python3.7: No module named virtualenv

Failed to create virtual environment.
```

Installing pipenv with `home-manager`:

```
{ config, pkgs, ... }:

with pkgs;
{
  home.packages = (with pkgs; [
    pipenv
  ]);
}
```

**Comment by adisbladis** [comment]
@rawkode I tried reproducing (using your exact same outputs):
`nix-store -r /nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26`

And we can see in the wrapper it's not setting `PYTHONPATH`:
```
#! /nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/10rqw9cx8x2knwdaxhlyb4drla8v8zzk-python3-3.7.4/bin:/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/bin:/nix/store/qp8hhw1xs5jbr8i9qn1fznwvwckq3mmq-pew-1.1.2/bin:/nix/store/9z9ccnsn7gi3hm9lazpqb6x1i4z7m0cs-python3.7-virtualenv-16.4.1/bin:/nix/store/5kj4i9nkrn66q9jl21m0694aqaz9cw9a-python3.7-setuptools-40.8.0/bin:/nix/store/pzcyq3k69wsl1fkvbm6fgmk49fjzi1gw-python3.7-virtualenv-clone-0.5.1/bin:/nix/store/pxlzvkn8cgdb0vxv6vh4pbi1b2wwgjkn-python3.7-pip-19.0.3/bin:/nix/store/9qgf0kkw9dxraagv1qxmswgiq10gpqv4-python3.7-chardet-3.0.4/bin:/nix/store/3cqajj4nardv4wmschvxgyxr52pq8qv2-python3.7-flake8-3.7.6/bin:/nix/store/pnyz9jmxp68mp5h1ia2imbzq7cfhflnx-python3.7-pyflakes-2.1.0/bin:/nix/store/z5k63j7qnafa5frjh59v1qw6cqp9ck75-python3.7-pycodestyle-2.5.0/bin:/nix/store/nbpa5ahmrcp623g54ik3jm5hq66xvkzd-python3.7-invoke-1.2.0/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/464wvp9rz43nsv4haxcgyma39ahxzq7n-pipenv-2018.11.26/bin/.pipenv-wrapped"  "${extraFlagsArray[@]}" "$@"
```

This is using `pipenv` from latest unstable:
```
#! /nix/store/xfghy8ixrhz3kyy6p724iv3cxji088dx-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/zjzq4qp81z8qnnnchnkycmsq0impw173-python3-3.7.4/bin:/nix/store/f9vy64ijva7gdw33cl37pfdap6p4f6w2-pipenv-2018.11.26/bin:/nix/store/8wjyr5zp9gfshm1hbip4j7ymy171xkcb-python3.7-flake8-3.7.7/bin:/nix/store/fjlamsyrjpbpgr265gk5vzqvqlznb5af-python3.7-setuptools-41.0.1/bin:/nix/store/30l12q8fcv5gkqxlc0a4ryv36h538gyq-python3.7-pyflakes-2.1.1/bin:/nix/store/hdidrxm4fifp1f46plg6sa94kr57ngpm-python3.7-pycodestyle-2.5.0/bin:/nix/store/vad259nyjpvw5hhilhsmby7qn9wwbml0-python3.7-invoke-1.2.0/bin:/nix/store/za67rv5pr4m68inws4k5rnidrp8xapik-python3.7-pip-19.1.1/bin:/nix/store/4q87f34lcqcy88i9h6wf4p6jivi3x68g-python3.7-chardet-3.0.4/bin:/nix/store/sja48s8jvl8di68sp192gjrk7i582npa-python3.7-virtualenv-16.4.3/bin:/nix/store/43zx94pd44z61li5p3i63dsc37b7y9hq-python3.7-virtualenv-clone-0.5.3/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
export PYTHONPATH='.:/nix/store/f9vy64ijva7gdw33cl37pfdap6p4f6w2-pipenv-2018.11.26/lib/python3.7/site-packages:/nix/store/zjzq4qp81z8qnnnchnkycmsq0impw173-python3-3.7.4/lib/python3.7/site-packages:/nix/store/fjlamsyrjpbpgr265gk5vzqvqlznb5af-python3.7-setuptools-41.0.1/lib/python3.7/site-packages:/nix/store/fp9hanzxk5n1la0fh4n6z522acgbrg7m-python3.7-bootstrapped-pip-19.1.1/lib/python3.7/site-packages:/nix/store/8wjyr5zp9gfshm1hbip4j7ymy171xkcb-python3.7-flake8-3.7.7/lib/python3.7/site-packages:/nix/store/qz21wd8r3qh5b2mmsn1wwv1kclm4j3sj-python3.7-entrypoints-0.3/lib/python3.7/site-packages:/nix/store/zjzq4qp81z8qnnnchnkycmsq0impw173-python3-3.7.4/lib/python3.7/site-packages:/nix/store/fjlamsyrjpbpgr265gk5vzqvqlznb5af-python3.7-setuptools-41.0.1/lib/python3.7/site-packages:/nix/store/30l12q8fcv5gkqxlc0a4ryv36h538gyq-python3.7-pyflakes-2.1.1/lib/python3.7/site-packages:/nix/store/hdidrxm4fifp1f46plg6sa94kr57ngpm-python3.7-pycodestyle-2.5.0/lib/python3.7/site-packages:/nix/store/6zbx4bw1injyj4flfnl1l5vpk36h1s7b-python3.7-mccabe-0.6.1/lib/python3.7/site-packages:/nix/store/vad259nyjpvw5hhilhsmby7qn9wwbml0-python3.7-invoke-1.2.0/lib/python3.7/site-packages:/nix/store/k10wzgxgxq1jr7xma68yrznnb6sp3vqy-python3.7-parver-0.2.1/lib/python3.7/site-packages:/nix/store/csxgphv9iwzm4dp4nxvf9r66ikp2fg4m-python3.7-six-1.12.0/lib/python3.7/site-packages:/nix/store/3600fmy3s4ln7zf4j0mnrsza9kmymqmv-python3.7-attrs-18.2.0/lib/python3.7/site-packages:/nix/store/8kriknrig34g0xgfyldmlviqbvrxfk19-python3.7-Arpeggio-1.9.0/lib/python3.7/site-packages:/nix/store/za67rv5pr4m68inws4k5rnidrp8xapik-python3.7-pip-19.1.1/lib/python3.7/site-packages:/nix/store/f6hww5za9pzhz5lqwibds1nwhhz4svkh-python3.7-requests-2.21.0/lib/python3.7/site-packages:/nix/store/avx6j4hr75jy48kwckn0w25sxhn62hhq-python3.7-urllib3-1.24.3/lib/python3.7/site-packages:/nix/store/qmhpx9faak54z75kf5m7db623xhqxw1m-python3.7-asn1crypto-0.24.0/lib/python3.7/site-packages:/nix/store/qy8cwiwqxkdblzldyiwdd5j25kkvdpa7-python3.7-packaging-19.0/lib/python3.7/site-packages:/nix/store/2cy8wlpzchszrckk0az60cp8kf6fdxjv-python3.7-pyparsing-2.3.1/lib/python3.7/site-packages:/nix/store/9inbpkcbj0cllsiaslmbqywz2d4h59dp-python3.7-pycparser-2.19/lib/python3.7/site-packages:/nix/store/f6nhx4jpndbqd76nqlr0bq2xq37kaz3r-python3.7-cffi-1.12.3/lib/python3.7/site-packages:/nix/store/74v4gfyss09wi0xcr4i2z0m6hypgzh6v-python3.7-cryptography-2.7/lib/python3.7/site-packages:/nix/store/p1fg65nhvxnn2dmszzmhaxm9izlzsfl6-python3.7-pyasn1-0.4.5/lib/python3.7/site-packages:/nix/store/axprss18cdljj4kdlbl8nyqga46iy0ii-python3.7-idna-2.8/lib/python3.7/site-packages:/nix/store/l3aflqwcqnzkns44cahipbmcvy2sqhqy-python3.7-pyOpenSSL-19.0.0/lib/python3.7/site-packages:/nix/store/82gynlnk9l6yq4w38z5285rsf3c2i6i7-python3.7-certifi-2019.3.9/lib/python3.7/site-packages:/nix/store/29616690p14c7qljh56iz7z69pc2wvam-python3.7-pysocks-1.6.8/lib/python3.7/site-packages:/nix/store/4q87f34lcqcy88i9h6wf4p6jivi3x68g-python3.7-chardet-3.0.4/lib/python3.7/site-packages:/nix/store/sja48s8jvl8di68sp192gjrk7i582npa-python3.7-virtualenv-16.4.3/lib/python3.7/site-packages:/nix/store/43zx94pd44z61li5p3i63dsc37b7y9hq-python3.7-virtualenv-clone-0.5.3/lib/python3.7/site-packages'
export PIP_IGNORE_INSTALLED='1'
exec -a "$0" "/nix/store/f9vy64ijva7gdw33cl37pfdap6p4f6w2-pipenv-2018.11.26/bin/.pipenv-wrapped"  "${extraFlagsArray[@]}" "$@"

I suggest trying to bump your channel, there seems to have been something wrong with python wrappers that's now fixed.
```

**Comment by rawkode** [comment]
Yep! Sorry @adisbladis. An accidental `sudo` prior to a channel change for my home-manager config meant it didn't actually changed.

Can confirm this fix works :D

**Comment by red-hood** [comment]
Will this fix be included in the 19.03 stable channel?
