### ISSUE TITLE
Steam won't install - cannot download libvulkan1.deb from any mirror

### ISSUE THREAD

**Issue by xurei** [NixOS/nixpkgs#49048]
## Issue description
I'm trying to install steam on my fresh NixOS installation. I get the error :
```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download libvulkan1.deb from any mirror
builder for '/nix/store/ia8g6grzgmajmi0jrlz3b7b4n097klvx-libvulkan1.deb.drv' failed with exit code 1
building '/nix/store/k13k56wnzm6s698n5fsb6x3v3rv0q3kg-libx11-6.deb.drv'...
building '/nix/store/n14ic4g08snkjygxp6zkhmcadp4wcchn-libx11-data.deb.drv'...
building '/nix/store/2msn0xc9dmg2fvihz6ri6dq8sg6wnjxx-libx11-xcb1.deb.drv'...
building '/nix/store/hbhfj73imjv54h3lkx1003qlrprnvl91-libxau6.deb.drv'...
cannot build derivation '/nix/store/ix2kwzv85q503ncbav999r9gy123bryy-steam-runtime.json.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r15kqc4sn25wq67d9mv8s6lxqwnn237h-steam-runtime-2016-08-13.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bq005jgyqz74mi9gzgwd4jfv2f5jcpp4-steam-runtime-wrapped.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/npnfqdg5ansavc40rlrnkml5ln0px5jf-steam-usr-multi.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5jgnnd0cas6kbjdvhxl7paxd6gfj42sc-steam-fhs.drv': 1 dependencies couldn't be built
building '/nix/store/j25lqaishvz7a1rp3dkhj7v4hjm37rb8-steam-original-1.0.0.51.drv'...
building '/nix/store/lpyrhsaiiqmn73wq8kgifjzjq382nsmv-steam-wrapper.sh.drv'...
cannot build derivation '/nix/store/pr74gm36jv4c65p0sshga8sr86impiqr-steam-init.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/aikkixznbqscqx1qjqvwqggms8y60dpi-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5k90n0w9ri1n3ca4gpr1fsa6z8mh0k7k-system-path.drv': 1 dependencies couldn't be built
```

### Steps to reproduce
- Add steam to your packages in configuration.nix
- `nixos-rebuild switch`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.76, NixOS, 18.09.932.09195057114 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.1`
 - channels(root): `"nixos-18.09.932.09195057114, nixos1803-18.09.932.09195057114, unstable-19.03pre155751.45a419ab5a2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by DIzFer** [comment]
I can confirm this happens on unstable.

**Comment by jethrokuan** [comment]
@abbradar looks like this is fetching from your domain, would you mind taking a look?

**Comment by adz21c** [comment]
Looks like the steam runtime deb packages have changed. I think @abbradar is just running a mirror of the packages.

I've just checked out release-18.09, ran update-runtime.py, and installed. I can log into steam and stream content from another computer.

**Comment by Infinisil** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/49363

**Comment by seb62** [comment]
I still have the same problem. Do I have to do something special, more than "nixos-rebuild switch --upgrade" et reboot, that I tried without success ?

**Comment by Infinisil** [comment]
@seb62 It will take some time for the channel to update, see http://howoldis.herokuapp.com/ or https://channels.nix.gsc.io/nixos-18.09/

**Comment by seb62** [comment]
Thanks for your replies.
@jethrokuan : as you joigned this issue to the non upgraded unstable channel problem, does it mean that the problem won't be solved in the 18.09 channel ?

**Comment by xurei** [comment]
I can confirm it works : after cherry-picking the PR in my git repo, I can install Steam.
Thanks for the quick reaction !

**Comment by jethrokuan** [comment]
@seb62: ah yeah if you're on `nixos-18.09` then you shouldn't have to wait too long, since the PR has been backported to `nixos-18.09`. `nixos-unstable` channel users will have to wait till that is resolved.
