### ISSUE TITLE
exfat is marked as broken

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixpkgs#53678]
## Issue description
The [FAQ](https://nixos.wiki/wiki/FAQ) lists instructions for adding exfat support. These are broken for kernel >4.18 per https://github.com/NixOS/nixpkgs/pull/45410

### Steps to reproduce
Add `boot.extraModulePackages = [ config.boot.kernelPackages.exfat-nofuse ];` to configuration.nix.

Is there another way to read exFAT on nixos? Many usb flash drives are formatted as exFAT.

**Comment by devhell** [comment]
Maybe `nixpkgs.exfat` and `nixpkgs.exfat-fuse`? I mount exFAT formatted usb drives usually via `udisksctl mount -b /dev/foo` and it works fine. I'm on unstable and running kernel 4.19.13 (at the moment due to VirtualBox issues, but it also worked fine for 4.20.

**Comment by schmittlauch** [comment]
This should be fixed by PRs #53696 and #53699

**Comment by tbenst** [comment]
wow that was fast! Thanks @makefu

**Comment by tbenst** [comment]
Hm, on one computer this now works, but on the other computer I'm still getting `error: Package ‘exfat-nofuse-2018-04-16-4.19.13’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/os-specific/linux/exfat/default.nix:31 is marked as broken, refusing to evaluate.`. Both are on unstable. @schmittlauch any thoughts by chance?

**Comment by makefu** [comment]
@tbenst it was actually more of an accident. @schmittlauch told me in the IRC and i was somewhat bored ;)

Due to the fact, that the PR just got merged it might be the case that the change has not yet arrived at your channels. you can however override the derivation locally or cherry-pick the commit onto your nixpkgs.

**Comment by tbenst** [comment]
Should this have hit by now?

```
> nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-unstable
> > nixos-rebuild boot
building Nix...
building the system configuration...
error: Package ‘exfat-nofuse-2018-04-16-4.19.13’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/os-specific/linux/exfat/default.nix:31 is marked as broken, refusing to evaluate.
```

**Comment by schmittlauch** [comment]
@makefu ^

**Comment by makefu** [comment]
@tbenst is this still the case? i checked the current channel and the patch is applied to unstable at least.

**Comment by schmittlauch** [comment]
@makefu at least in stable (18.09) the build still fails: 
```
nixos-rebuild switch                                                                                                                                         /home/spiollinux
building Nix...
building the system configuration...
error: Package ‘exfat-nofuse-2018-04-16-4.19.15’ in /nix/store/ydgrdshzbj6xyr86bihhc9zyjyp964k1-nixos-18.09.1922.97e0d53d669/nixos/pkgs/os-specific/linux/exfat/default.nix:31 is marked as broken, refusing to evaluate.
```

channel is at nixos-18.09.1922.97e0d53d669

**Comment by schmittlauch** [comment]
@makefu Looks like this hasn't been backported. Shall I do that?

**Comment by makefu** [comment]
@schmittlauch if you want to, sure. i only checked unstable cause this is what @tbenst was asking for :racehorse:

**Comment by tbenst** [comment]
@makefu I'm still seeing the same issue. Am I forgetting something obvious?

```
> nix-channel --update
unpacking channels...
> nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-unstable
> nixos-rebuild switch
building Nix...
building the system configuration...
error: Package ‘exfat-nofuse-2018-04-16-4.19.13’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/os-specific/linux/exfat/default.nix:31 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Comment by makefu** [comment]
@tbenst can you write your `/nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/os-specific/linux/exfat/default.nix` to a gist? i also checked out the latest unstable channel but for me on line 31 there is nothing which would justify an assertion: https://gist.github.com/makefu/f6638d5df2e025728eec0cb44f7fa14a

**Comment by tbenst** [comment]
@makefu Doh! was not updating channel as root that fixed it, thank you sorry to waste your time!

**Comment by mausch** [comment]
I just got this error trying to upgrade the kernel from 5.4 to 5.10. I had to look it up on github to see that it's not necessary since 5.7: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/exfat/default.nix#L8-L11
Maybe the error message could be improved somehow?
