### ISSUE TITLE
Remaining failures from qt-5.12 upgrade

### ISSUE THREAD

**Issue by hedning** [NixOS/nixpkgs#54107]
## Issue description

Testing out a few simple scripts to grab build logs from hydra and found these failures which I believe comes from the recent qt-5.12 upgrade (though might be other causes):

- [x] [xdg-desktop-portal-kde](https://hydra.nixos.org/build/87208324) https://github.com/NixOS/nixpkgs/issues/54002
- [x] [tora](https://hydra.nixos.org/build/87220952)
- [x] [nextcloud-client](https://hydra.nixos.org/build/87362429)
- [x] [sleepyhead](https://hydra.nixos.org/build/87362328)
- [x] [shotcut](https://hydra.nixos.org/build/87362472)
- [x] [libsForQt511.kpmcore](https://hydra.nixos.org/build/87343060)
- [x] [qtikz](https://hydra.nixos.org/build/87363164)
- [ ] [qmc2](https://hydra.nixos.org/build/87363873)
- [ ] [calligra](https://hydra.nixos.org/build/87362913)
- [x] [pymol](https://hydra.nixos.org/build/87217472)
- [x] [apmplanner2](https://hydra.nixos.org/build/87365008)

<details>
<summary> Tail of logs </summary>

> ==> nixpkgs.xdg-desktop-portal-kde.x86_64-linux <==
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/include/QtPrintSupport/5.12.0/QtPrintSupport/private/qprint_p.h:61:10: fatal error: cups/ppd.h: No such file or directory
>  #include <cups/ppd.h>  // Use for type defs only, don't want to actually link in main module
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/CMakeFiles/xdg-desktop-portal-kde.dir/build.make:214: src/CMakeFiles/xdg-desktop-portal-kde.dir/print.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:280: src/CMakeFiles/xdg-desktop-portal-kde.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> builder for '/nix/store/mbs6paf6m819hz3bi70b1s6pg237s0l7-xdg-desktop-portal-kde-5.14.4.drv' failed with exit code 2

> ==> nixpkgs.tora.x86_64-linux <==
> /build/source/src/tools/tobrowser.cpp:1399:17: note: in expansion of macro 'WARN'
>  #pragma message WARN("TODO: Override roResutSchema::selected(), handle empty")
>                  ^~~~
> make[2]: *** [src/CMakeFiles/tora.dir/build.make:5206: src/CMakeFiles/tora.dir/tools/tobrowser.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:260: src/CMakeFiles/tora.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> builder for '/nix/store/ga4bv18cw09qvqzygfchjr2lw575yhar-tora-3.1.drv' failed with exit code 2

> ==> nixpkgs.nextcloud-client.x86_64-linux <==
>  bool ExternalWebEnginePage::acceptNavigationRequest(const QUrl &url, QWebEnginePage::NavigationType type, bool isMainFrame)
>                                                                                                                 ^~~~~~~~~~~
> At global scope:
> cc1plus: warning: unrecognized command line option '-Wno-gnu-zero-variadic-macro-arguments'
> make[2]: *** [src/gui/CMakeFiles/nextcloud.dir/build.make:1364: src/gui/CMakeFiles/nextcloud.dir/wizard/webview.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:343: src/gui/CMakeFiles/nextcloud.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> builder for '/nix/store/s95vx5w1p6cb1h5p0h8fx1hs9cy0hyci-nextcloud-client-2.5.1.drv' failed with exit code 2

> ==> nixpkgs.sleepyhead.x86_64-linux <==
> Project MESSAGE: Building with QGLWidget gGraphView
> make[1]: Entering directory '/build/sleepyhead-code-9e2329d/sleepyhead'
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic daily.ui -o ui_daily.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic overview.ui -o ui_overview.h
> make[1]: *** No rule to make target 'QtWebKitWidgets/QWebView', needed by 'ui_mainwindow.h'.  Stop.
> make[1]: Leaving directory '/build/sleepyhead-code-9e2329d/sleepyhead'
> make: *** [Makefile:45: sub-sleepyhead-make_first-ordered] Error 2
> builder for '/nix/store/zs4iak7xk2k52h386p799ckz4biw258g-sleepyhead-1.0.0-beta-git.drv' failed with exit code 2

> ==> nixpkgs.shotcut.x86_64-linux <==
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic docks/playlistdock.ui -o ui_playlistdock.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic dialogs/durationdialog.ui -o ui_durationdialog.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic dialogs/customprofiledialog.ui -o ui_customprofiledialog.h
> make[1]: *** No rule to make target 'QtWebKitWidgets/QWebView', needed by 'ui_htmleditor.h'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/build/source/src'
> make: *** [Makefile:72: sub-src-make_first] Error 2
> builder for '/nix/store/nji2a6dhaak250pn50j9xcf0qh2s1ldx-shotcut-18.12.23.drv' failed with exit code 2

> ==> nixpkgs.libsForQt511.kpmcore.x86_64-linux <==
> [ 88%] Linking CXX executable testlist
> /nix/store/1l6rbgbcgdmwyv0cx44j4jj476ihzay7-ki18n-5.53.0/lib/libKF5I18n.so.5.53.0: undefined reference to `qt_version_tag@Qt_5.12'
> /nix/store/9ril2dgxy5wm0gr0dbkacv8f3lx61m43-kwidgetsaddons-5.53.0/lib/libKF5WidgetsAddons.so.5.53.0: undefined reference to `QCoreApplication::sendEvent(QObject*, QEvent*)@Qt_5'
> collect2: error: ld returned 1 exit status
> make[2]: *** [test/CMakeFiles/testlist.dir/build.make:103: test/testlist] Error 1
> make[1]: *** [CMakeFiles/Makefile2:638: test/CMakeFiles/testlist.dir/all] Error 2
> make: *** [Makefile:141: all] Error 2
> builder for '/nix/store/pry58dbb8hngl8k3s2qp6wmg7sycc2yr-kpmcore-3.3.0.drv' failed with exit code 2

> ==> nixpkgs.qtikz.x86_64-linux <==
> lrelease -silent translations/fr/qtikz_fr.ts -qm locale/qtikz_fr.qm
> qcollectiongenerator doc/qtikz.qhcp -o doc/qtikz.qhc
> sed -e "s/assistant\ -collectionFile/assistant\ -collectionFile\ \/nix\/store\/9clzngnpd8qjpc4jgqnq9jl3wlqqyg2p-qtikz-unstable-20161122\/share\/qtikz\/documentation\/qtikz.qhc/" doc/qtikz.1.template > qtikz.1
> sed -e "s/Icon=/Icon=\/nix\/store\/9clzngnpd8qjpc4jgqnq9jl3wlqqyg2p-qtikz-unstable-20161122\/share\/qtikz\/qtikz-128.png/" data/qtikz.desktop.template > qtikz.desktop
> /nix/store/vs6d2fjkl4kb3jb7rwibsd76k9v2n4xy-bash-4.4-p23/bin/bash: qcollectiongenerator: command not found
> make: *** [Makefile:1020: doc/qtikz.qhc] Error 127
> make: *** Waiting for unfinished jobs....
> builder for '/nix/store/ghsnwm0cf3dkgr6c92211r5n5zijld7p-qtikz-unstable-20161122.drv' failed with exit code 2

> ==> nixpkgs.qmc2.x86_64-linux <==
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic visiblecolumnsetup.ui -o ui_visiblecolumnsetup.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic manualscanner.ui -o ui_manualscanner.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic rompathcleaner.ui -o ui_rompathcleaner.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic setupwizard.ui -o ui_setupwizard.h
> make[1]: *** No rule to make target 'QtWebKit/QWebView', needed by 'ui_htmleditor.h'.  Stop.
> make[1]: Leaving directory '/build/qmc2'
> make: *** [Makefile:1043: qmc2-bin] Error 2
> builder for '/nix/store/3188nc93paxrlxhazgnba4ydhfngxljy-qmc2-0.195.drv' failed with exit code 2

> ==> nixpkgs.calligra.x86_64-linux <==
>                                                                                                printf
> /build/calligra-3.1.0/filters/karbon/pdf/PdfImport.cpp:106:13: error: 'memCheck' is not a member of 'Object'
>      Object::memCheck(stderr);
>              ^~~~~~~~
> make[2]: *** [filters/karbon/pdf/CMakeFiles/calligra_filter_pdf2svg.dir/build.make:76: filters/karbon/pdf/CMakeFiles/calligra_filter_pdf2svg.dir/PdfImport.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:18293: filters/karbon/pdf/CMakeFiles/calligra_filter_pdf2svg.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> builder for '/nix/store/4lghwxisckp6rv0bay96dhscdnv6ih9q-calligra-3.1.0.drv' failed with exit code 2

> ==> nixpkgs.pymol.x86_64-linux <==
>                  from layer1/Font.h:37,
>                  from layer1/Text.cpp:21:
> /nix/store/sayl5x32j0dfhivh0fbqf46viwq2fs52-glew-2.1.0-dev/include/GL/glew.h:22688:52: note: previous declaration 'void (* __glewGetFragmentMaterialivSGIX)(GLenum, GLenum, const GLint*)'
>  GLEW_FUN_EXPORT PFNGLGETFRAGMENTMATERIALIVSGIXPROC __glewGetFragmentMaterialivSGIX;
>                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> g++ -std=c++0x -fPIC -D_PYMOL_LIBPNG -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -D_PYMOL_NO_MSGPACKC -D_PYMOL_FREETYPE -DNO_MMLIBS -D_PYMOL_NUMPY -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/include -Icontrib/uiuc/plugins/molfile_plugin/src -I/nix/store/qxi6y00k3plkzj4p2z02k3jf68gly66r-python3.7-numpy-1.15.4/lib/python3.7/site-packages/numpy/core/include -I/nix/store/ydk0mfpvn9smcmn72wc9i20slv1d2b79-python3-3.7.2/include/python3.7m -c ov/src/OVContext.cpp -o build/temp.linux-x86_64-3.7/ov/src/OVContext.o -Wno-write-strings -Wno-unused-function -Wno-char-subscripts -ffast-math -funroll-loops -fcommon -O3
> error: command 'gcc' failed with exit status 1
> builder for '/nix/store/h1qcx0823mx7lf31syx9nxhgah7508m5-pymol-2.1.0.drv' failed with exit code 1

> ==> nixpkgs.plasma5.xdg-desktop-portal-kde.x86_64-linux <==
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/include/QtPrintSupport/5.12.0/QtPrintSupport/private/qprint_p.h:61:10: fatal error: cups/ppd.h: No such file or directory
>  #include <cups/ppd.h>  // Use for type defs only, don't want to actually link in main module
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/CMakeFiles/xdg-desktop-portal-kde.dir/build.make:214: src/CMakeFiles/xdg-desktop-portal-kde.dir/print.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:280: src/CMakeFiles/xdg-desktop-portal-kde.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> builder for '/nix/store/mbs6paf6m819hz3bi70b1s6pg237s0l7-xdg-desktop-portal-kde-5.14.4.drv' failed with exit code 2

> ==> nixpkgs.apmplanner2.x86_64-linux <==
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic src/ui/watchdog/WatchdogControl.ui -o build-release/ui/ui_WatchdogControl.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic src/ui/watchdog/WatchdogProcessView.ui -o build-release/ui/ui_WatchdogProcessView.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic src/ui/watchdog/WatchdogView.ui -o build-release/ui/ui_WatchdogView.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic src/ui/QGCFirmwareUpdate.ui -o build-release/ui/ui_QGCFirmwareUpdate.h
> /nix/store/r8clj7f3dcw7dxnwnyanzmcm462fjms4-qtbase-5.12.0-dev/bin/uic src/ui/QGCPxImuFirmwareUpdate.ui -o build-release/ui/ui_QGCPxImuFirmwareUpdate.h
> make: *** No rule to make target 'QOSGWidget.h', needed by 'build-release/ui/ui_QMap3D.h'.  Stop.
> make: *** Waiting for unfinished jobs....
> builder for '/nix/store/1093xsga7hqmm0j19pljbd2r7lqzq4ic-apmplanner2-2.0.26.drv' failed with exit code 2

</details>

**Comment by Infinisil** [comment]
shotcut was fixed with https://github.com/NixOS/nixpkgs/pull/56875

**Comment by cpages** [comment]
calligra was another issue, still broken for unrelated (I think) reasons: https://github.com/NixOS/nixpkgs/pull/58719

**Comment by mdedetrich** [comment]
Is there any update on this? We have KDE packages that have been broken for a year.

**Comment by Infinisil** [comment]
qmc2 has been marked as broken, hasn't seen an update in ~2 years, so I think that's fine

**Comment by FliegendeWurst** [comment]
calligra was fixed in #95893, and qmc2 is broken for unrelated reasons.
