### ISSUE TITLE
dockerTools buildImage was broken by c88337

### ISSUE THREAD

**Issue by thomasjm** [NixOS/nixpkgs#55290]
## Issue description

Using `dockerTools.buildImage` with a `fromImage` doesn't work right anymore after c88337c9aca9d91804da7d1d05960c88e17455c9 (and the bugfix commit a3c536fcb374387b228c7a270987d6d38d697b86).

I have a simple Docker image I'm using as a `fromImage`, which sets up a user `user` and puts some files in their home directory `/home/user`. (The exact setup doesn't matter.)

When I use `buildImage`, the files that are present in the home folder in the base image are lost. This used to work before the commits above.

### Steps to reproduce

I made this repro derivation:

```
with import <nixpkgs> {};
with dockerTools;

rec {

  baseImage = pullImage {
    imageName = "codedown/nix-base-ubuntu";
    finalImageTag = "latest";
    imageDigest = "sha256:c8b60468bff9f4f1c0ea6e1e3db6cd15a62dec0a0559a5b368b7a87faa1094e1";
    os = "linux";
    arch = "amd64";
    sha256 = "1iz0nhf13qdvyc2h1nsghbbif9y89iff4jx15dp47s9dqkcvsifm";
  };

  test = buildImage {
    name = "repro";

    fromImage = baseImage;
    tag = "latest";
    created = "now";

    config = {
      WorkingDir = "/home/user";
    };
  };
}
```

Try running 

```
nix-build default.nix -A test -o test.tar.gz
docker load test.tar.gz
docker run -u root -it --rm repro bash
ls -lha /home/user
```

and compare that output to the base image:

```
docker pull codedown/nix-base-ubuntu
docker run --rm -it codedown/nix-base-ubuntu
ls -lha /home/user
```

You will see that the repro image is missing files.

CC @grahamc @djahandarie

**Comment by thomasjm** [comment]
(To be clear, it is now broken for a normal `fromImage`, not a layered one.)

**Comment by thomasjm** [comment]
Friendly ping @grahamc , can you tell what broke here?

**Comment by nlewo** [comment]
@thomasjm it seems to be related to the layers ordering. If you `docker inspect` both images, you will see layers are reversed.

@thomasjm Could you check the associated PR fixes this issue?

**Comment by thomasjm** [comment]
Yes, that seems to work! Many thanks @nlewo :)

**Comment by lheckemann** [comment]
Merged #55859 so this should be fixed. Thanks @nlewo !

**Comment by thomasjm** [comment]
Oh no, I found another aspect of this which is still broken :(. I think it's still covered under this issue, so I think we should reopen this one rather than file another, is that okay?

There's still a problem when you have a `runAsRoot` command in the `buildImage` command: the layers from the base image aren't present.

Here's my repro from above with that addition:

```
with import <nixpkgs> {};
with dockerTools;

rec {

  baseImage = pullImage {
    imageName = "codedown/nix-base-ubuntu";
    finalImageTag = "latest";
    imageDigest = "sha256:c8b60468bff9f4f1c0ea6e1e3db6cd15a62dec0a0559a5b368b7a87faa1094e1";
    os = "linux";
    arch = "amd64";
    sha256 = "1iz0nhf13qdvyc2h1nsghbbif9y89iff4jx15dp47s9dqkcvsifm";
  };

  test = buildImage {
    name = "repro";

    fromImage = baseImage;
    tag = "latest";
    created = "now";

    runAsRoot = ''
      #!${stdenv.shell}
      ${shadowSetup}

      # This should show the user "user" present in the fromImage, but it doesn't
      cat /etc/passwd
    '';

    config = {
      WorkingDir = "/home/user";
    };
  };
}
```

If you run `nix-build default.nix -A test -o test.tar.gz` and look at the build output, you'll see the output of the `cat /etc/passwd` command. Because the base image I'm using has an added user named "user", you should see a line like this:

```
user:x:1000:1000:,,,:/home/user:/bin/bash
```

but due to the regression from c88337c9aca9d91804da7d1d05960c88e17455c9 you don't see that line. This is preventing me from doing some extra setup that depends on stuff in the base image.

Any chance you can see a fix @nlewo ? :)

**Comment by nlewo** [comment]
@thomasjm Does #57505 fix this issue?

**Comment by thomasjm** [comment]
Yes @nlewo , that seems to work! Thanks again
