### ISSUE TITLE
meson does not detect boost correctly

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#55409]
## Issue description
meson does not detect boost correctly.
```
Dependency Boost (filesystem, regex, system) found: NO

meson.build:3:0: ERROR:  Dependency "boost" not found

```

### Steps to reproduce
```
# meson-boost.nix
{ nixpkgs ? import <nixpkgs> {} }:
with nixpkgs;
stdenv.mkDerivation {
  name = "meson-boost";
  buildInputs = [
    boost
    meson
  ];
}
```

```
# meson.build
project('meson-boost', 'c', 'cpp')

dep_boost = dependency(
  'boost',
  modules: ['filesystem', 'regex', 'system'],
  static: true,
)
```

Then run `nix-shell meson-boost.nix`, and in the shell, run `meson build`.

## Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.2.0, macOS 10.14.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2`
 - channels(val): `"nixpkgs-19.03pre167858.f2a1a4e93be"`
 - nixpkgs: `/Users/val/.nix-defexpr/channels/nixpkgs`

**Comment by Ptival** [comment]
Essentially, `meson` tries to run:
```
clang++ /var/path/to/testfile.cpp -pipe -o /var/path/to/output.exe -O0 -fpermissive -lboost_system-mt -Wl,-undefined,dynamic_lookup
```
to detect the library.

The `-mt` part is added to `-lboost_system` because it believes it will find the multi-threaded version of the library with said suffix. The way nix packages things, AFAICT, suffixes are not used.
cf. https://github.com/NixOS/nixpkgs/issues/784 

So a potential fix would be to patch the Python code so that it does not add the `-mt` suffix for nix. I will experiment and report.

**Comment by matthewbauer** [comment]
I would report this issue on the meson tracker:

https://github.com/mesonbuild/meson/issues

Issue seems to come from here:

https://github.com/mesonbuild/meson/blob/1eb455f8696643b625b10a85551ff9fd28dd7d2a/mesonbuild/dependencies/boost.py#L304-L313

https://github.com/mesonbuild/meson/blob/1eb455f8696643b625b10a85551ff9fd28dd7d2a/mesonbuild/dependencies/boost.py#L455-L468

**Comment by Ptival** [comment]
Yeah, I investigated, and as you found out, the problem is that they assume that on a darwin system, the multi-threaded libraries will be found with a `-mt` suffix. That is not true for the ones as packaged in nixpkgs, so it fails.

An easy fix is to override the derivation to put symbolic links with the `-mt` suffix next to the original `.dylib`. And indeed I might message them to see if they can make this process less opinionated.

**Comment by djahandarie** [comment]
Hitting this issue on nixpkgs HEAD, from pulseeffects.

**Comment by jtojnar** [comment]
@djahandarie that is a [different issue](https://github.com/NixOS/nixpkgs/issues/86131) and was fixed in https://github.com/NixOS/nixpkgs/commit/61a2045c9a2fd10ce061341209a5b3a649b6cc01.

This one is Darwin specific and unrelated to the Meson's recent rewrite o the `boost` module. Would be nice to check if it fixed this issue.

**Comment by dschrempf** [comment]
Just bumped into this with NixOS with Nixpkgs unstable, it is still an issue.

**Comment by jtojnar** [comment]
@dschrempf did you mean https://github.com/NixOS/nixpkgs/issues/86131? See above https://github.com/NixOS/nixpkgs/issues/55409#issuecomment-621321208

**Comment by jtojnar** [comment]
Yeah, I do not see the code mentioned by Matthew [above](https://github.com/NixOS/nixpkgs/issues/55409#issuecomment-462206297) in the current Meson codebase.

**Comment by dschrempf** [comment]
Yeah, sorry, was not awayre of this other issue!
