### ISSUE TITLE
allowUnfreePredicate steam not working

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#55678]
## Issue description

I want to just allow steam as unfree program, so i set:

```
  nixpkgs.config.allowUnfreePredicate = (pkg: builtins.elem (builtins.parseDrvName pkg.name).name [ "steam" ]);
```

but i still get the error:

```
[root@X230:~]# nixos-rebuild switch
building Nix...
building the system configuration...
error: Package ‘steam’ in /nix/store/x2pp84mzmmg519p54pqvsiy3n5w5vjkr-nixos-18.09.2137.168cbb39691/nixos/pkgs/games/steam/steam.nix:31 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.
```
Maybe i'm doing something wrong, but at least the error message is confusing. I also tried to allow `steam-original` with same result.

### Steps to reproduce

```
  # required for steam https://nixos.wiki/wiki/Steam
  hardware.opengl.driSupport32Bit = true;
  hardware.pulseaudio.support32Bit = true;
  nixpkgs.config.allowUnfreePredicate = (pkg: builtins.elem (builtins.parseDrvName pkg.name).name [ "steam" ]);

  # install packages
  environment.systemPackages = with pkgs; [
    steam
    steam-run
  ];
```

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.98, NixOS, 18.09.2137.168cbb39691 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(davidak): `""`
 - channels(root): `"nixos-18.09.2137.168cbb39691, nixos-hardware, nixos-unstable-19.03pre169108.36f31600749"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by 7c6f434c** [comment]
Could not fully reproduce on master.

```
{pkgs, config, ...}: {
# required for steam https://nixos.wiki/wiki/Steam
hardware.opengl.driSupport32Bit = true;
hardware.pulseaudio.support32Bit = true;
nixpkgs.config.allowUnfreePredicate = (pkg: builtins.elem (builtins.parseDrvName pkg.name).name [ "steam" ]);

# install packages
environment.systemPackages = with pkgs; [
        steam
        steam-run
];
}
```

```
nix-instantiate /home/repos/nixpkgs/nixos -A config.environment.systemPackages -I nixos-config=/tmp/a.nix
```
```
error: Package ‘steam-original-1.0.0.56’ in /home/repos/nixpkgs/pkgs/games/steam/steam.nix:33 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

And adding `steam-original` and `steam-runtime` indeed helps.

**Comment by 7c6f434c** [comment]
… and with `hasPrefix` it would be enough to just say `steam-`

**Comment by Drainful** [comment]
I encountered this same issue (while installing lutris), and I came to the following solution. (Nixos 19.09)
```
nixpkgs.config.allowUnfreePredicate =
	let allowedUnfree = [
				"steam"
				"steam-original"
				"steam-runtime"
			];
	in with builtins;
		(pkg:
			(
				((elem "name" (attrNames pkg)) &&
				 (elem (parseDrvName pkg.name).name allowedUnfree))
				||
				((elem "pname" (attrNames pkg)) &&
				 (elem pkg.pname allowedUnfree))
			)
		);
```
It is my understanding that a name attribute should be created from a pname attribute, but referring to steam-original's name attribute did not solve the problem, and this did. Perhaps  steam-original's name attribute is formatted in an unexpected way. I'm not sure how to check.

**Comment by davidak** [comment]
It still don't work.

@7c6f434c with your example, i get this error where my nixpkgs is current stable at 6a99d5d6485bf29f948bef0127b1a2904e1d7589.

```
[davidak@gaming:~]$ nix-instantiate /home/davidak/code/nixpkgs/nixos/ -A config.environment.systemPackages -I nixos-config=/tmp/a.nix
error: attribute 'name' missing, at /tmp/a.nix:5:82
(use '--show-trace' to show detailed location information)
```

when i change `pkg.name` to `pkg.pname`:

```
[davidak@gaming:~]$ nix-instantiate /home/davidak/code/nixpkgs/nixos/ -A config.environment.systemPackages -I nixos-config=/tmp/a.nix
error: attribute 'pname' missing, at /tmp/a.nix:5:82
```

the documentation is different now, but that also don't work:

```
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
  ];
```

```
[root@gaming:/home/davidak]# nixos-rebuild switch
building Nix...
building the system configuration...
error: Package ‘steam’ in /nix/store/a5inn8qk5sa8dgc0zbb6llprcj4rw16a-nixos-20.03.2141.8b071be7512/nixos/pkgs/games/steam/steam.nix:34 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

but the same works with `nix-instantiate`:

```
[davidak@gaming:~]$ nix-instantiate /home/davidak/code/nixpkgs/nixos/ -A config.environment.systemPackages -I nixos-config=/tmp/a.nix
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/ln6a39335x7qwn2vqdx8zgadhil6jsvs-steam.drv
/nix/store/pmsygkivhy5agw9kz6r1nmbfizkdakfy-steam-run.drv
/nix/store/m7n94rpiswkn8z125rpi5ywm6b3qjcbw-nixos-container.drv
```

```
[davidak@gaming:~]$ cat /tmp/a.nix
{pkgs, lib,  config, ...}: {
# required for steam https://nixos.wiki/wiki/Steam
hardware.opengl.driSupport32Bit = true;
hardware.pulseaudio.support32Bit = true;
#nixpkgs.config.allowUnfreePredicate = (pkg: builtins.elem (builtins.parseDrvName pkg.pname).name [ "steam" ]);
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
  ];

# install packages
environment.systemPackages = with pkgs; [
        steam
        steam-run
];
}
```
that's very strange...

**Comment by 7c6f434c** [comment]
Hm. Maybe different channels and different names? I guess I would trace the package and its `getName` in the `allowUnfreePredicate` in the non-working version.

**Comment by raboof** [comment]
still relevant

**Comment by 7c6f434c** [comment]
I have no ide why it is always hard to reproduce on unstable then.

```nix
{pkgs, config, ...}: {
# required for steam https://nixos.wiki/wiki/Steam
hardware.opengl.driSupport32Bit = true;
hardware.pulseaudio.support32Bit = true;
nixpkgs.config.allowUnfreePredicate = (pkg: let pkgname = (builtins.parseDrvName pkg.name or pkg.pname).name; in (pkgname == "steam" || pkgs.lib.hasPrefix "steam-" pkgname));

# install packages
environment.systemPackages = with pkgs; [
        steam
        steam-run
];
}

```

```sh
nix-instantiate /home/repos/nixpkgs/nixos -A config.environment.systemPackages -I nixos-config=$PWD/steam.nix
```

Somehow works for me just fine with a moderately out of date (a week or two?) unstable checkout.

**Comment by 7c6f434c** [comment]
@raboof and you should post what exactly you tested and what exact error messages you get, this at least creates a chance that someone eventually understands what is even going on…

**Comment by raboof** [comment]
I'm on nixos-unstable (e9158eca70ae59e73fae23be5d13d3fa0cfc78b4)

Adding `steam` to /etc/nixos/configuration.nix's `environment.systemPackages` correctly shows an error telling me to add `steam` to `allowUnfreePredicate`, then `steam-original` and `steam-runtime`. So far so good.

However, even after rebooting into that profile, `nix-shell -p steam` does not work:

```
error: Package ‘steam’ in /home/aengelen/nixpkgs/pkgs/games/steam/steam.nix:34 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

a) To temporarily allow unfree packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNFREE=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

Alternatively you can configure a predicate to whitelist specific packages:
  { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "steam"
    ];
  }

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

(even though running steam works find outside of nix-shell).

**Comment by 7c6f434c** [comment]
>I'm on nixos-unstable (e9158eca70ae59e73fae23be5d13d3fa0cfc78b4)
>
>Adding `steam` to /etc/nixos/configuration.nix's `environment.systemPackages` correctly shows an error telling me to add `steam` to `allowUnfreePredicate`, then `steam-original` and `steam-runtime`. So far so good.
>
>However, even after rebooting into that profile, `nix-shell -p steam` does not work:

`nix-shell` uses a different Nixpkgs config than system-wide NixOS configuration, so that's to be expected.

```
, # Fallback: The contents of the configuration file found at $NIXPKGS_CONFIG or
  # $HOME/.config/nixpkgs/config.nix.
  config ? let
      configFile = getEnv "NIXPKGS_CONFIG";
      configFile2 = homeDir + "/.config/nixpkgs/config.nix";
      configFile3 = homeDir + "/.nixpkgs/config.nix"; # obsolete
    in
      if configFile != "" && pathExists configFile then import configFile
      else if homeDir != "" && pathExists configFile2 then import configFile2
      else if homeDir != "" && pathExists configFile3 then import configFile3
      else {}
```

So you either need to use as Nixpkgs something that import Nixpkgs with your preferred config, or create a Nixpkgs config file either in the default location or in a location referenced via the environment variables.

With flakes it seemed to be a pain untill https://github.com/NixOS/nix/commit/dc4a280318650762a79447dbb299aef887f61d2e as far as I understand, not sure what is the current status of that commit, but I guess eventually it should end up inside some release.

**Comment by raboof** [comment]
> `nix-shell` uses a different Nixpkgs config than system-wide NixOS configuration, so that's to be expected.

Ah, I misunderstood that then. Then AFAICS this is fixed: it works for me in configuration.nix with:

```
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
  ];
```

and in ~/.config/nixpkgs/config.nix with:

```
  allowUnfreePredicate = pkg: builtins.elem ((import <nixpkgs> {}).lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
  ];
```

I guess it's good to keep nix-shell as 'pure' as possible, though, so I'll just allow unfree packages selectively on the command-line or in my `shell.nix`.

Sorry about the noise ;)

**Comment by 7c6f434c** [comment]
@davidak Has consistent behaviour propagated to all the branches you still care about?

**Comment by davidak** [comment]
@7c6f434c i'm on nixos stable and can still reproduce the issue. is there a fix in unstable that can be backported?

my config.:

nixpkgs.config.allowUnfreePredicate = (pkg: let pkgname = (builtins.parseDrvName pkg.name or pkg.pname).name; in (pkgname == "steam" || pkgs.lib.hasPrefix "steam-" pkgname));

programs.steam.enable = true;
hardware.steam-hardware.enable = true;

error:

error: Package ‘steam’ in /nix/store/0kfg4wbw9zbqhljbmq559m5wqp22vqmx-nixos-20.09.2338.3d2d8f281a2/nixos/pkgs/games/steam/steam.nix:34 has an unfree license (‘unfreeRedistributable’), refusing to evaluate.

**Comment by 7c6f434c** [comment]
>@7c6f434c i'm on nixos stable and can still reproduce the issue. is there a fix in unstable that can be backported?

There is no fix, it always just worked for me whenever I tried to reproduce this…

>
>my config.:
>
>nixpkgs.config.allowUnfreePredicate = (pkg: let pkgname = (builtins.parseDrvName pkg.name or pkg.pname).name; in (pkgname == "steam" || pkgs.lib.hasPrefix "steam-" pkgname));
>
>programs.steam.enable = true;
>hardware.steam-hardware.enable = true;

Soooooo:

```
{pkgs, config, ...}: {

boot.isContainer = true;

nixpkgs.config.allowUnfreePredicate = (pkg: let pkgname = (builtins.parseDrvName pkg.name or pkg.pname).name; in (pkgname == "steam" || pkgs.lib.hasPrefix "steam-" pkgname));

programs.steam.enable = true;
hardware.steam-hardware.enable = true;

}
```

```sh
nix-instantiate /home/repos/nixpkgs-whatever/nixos -I nixos-config=/tmp/steam-davidak.nix
```

```
/nix/store/inyq2x16fb1d7gyljp1kh6gwk4v230hf-nixos-system-nixos-20.09pre-git.drv
/nix/store/drnanhn71dc5is2p9cpflhfcr3p3j9ni-nixos-vm.drv
/nix/store/d2gb9sb0qr0lsw1hx4d05m5k63hzqbvd-nixos-vm.drv
```

`release-20.03` lacks `programs.steam`, `master` evaluates fine and of course reports `21.03pre`, I have no idea how to valuate from a checkout to get non-pre version ticker.

`release-20.09`, `nixos-20.09-small`, `nixos-20.09` — they all just work.

Maybe try the same kind of evaluation from under a fresh user account?

**Comment by davidak** [comment]
```
{ config, lib, pkgs, ... }:

{
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "steam"
    "steam-original"
    "steam-runtime"
  ];

  programs.steam.enable = true;
  hardware.steam-hardware.enable = true;
}
```
(this is less code and easier to understand for me)

```
[davidak@gaming:~]$ nix-instantiate ~/code/nixpkgs/ -I nixos-config=/tmp/steam-davidak.nix
error: Please be informed that this pseudo-package is not the only part of
Nixpkgs that fails to evaluate. You should not evaluate entire Nixpkgs
without some special measures to handle failing packages, like those taken
by Hydra.
```

```
[davidak@gaming:~]$ nix-instantiate '<nixos-unstable>' -I nixos-config=/tmp/steam-davidak.nix
error: Please be informed that this pseudo-package is not the only part of
Nixpkgs that fails to evaluate. You should not evaluate entire Nixpkgs
without some special measures to handle failing packages, like those taken
by Hydra.
```

I always get this error. `~/code/nixpkgs/` is on master.

**Comment by 7c6f434c** [comment]
>Nixpkgs that fails to evaluate. You should not evaluate entire Nixpkgs
>without some special measures to handle failing packages, like those taken

Erm, you are evaluating Nixpkgs and not nixpkgs/nixos here.

**Comment by davidak** [comment]
Right, i didn't read carefully enough.

I found the issue. There was `allowUnfreePredicate` in a second file. When i remove the lines (not needed anymore), the error disappears.

https://github.com/davidak/nixos-config/blob/974fb2df09410ff025f815d77e0c1f8af675fb07/profiles/personal.nix#L14-L20

So this issue is resolved for me.
