### ISSUE TITLE
'bower' utility is broken

### ISSUE THREAD

**Issue by bburdette** [NixOS/nixpkgs#5629]
The bower utility installs successfully, but doesn't run.  A sample session:

[bburdette@nixosthe1:~]$ nix-env -i bin-bower
installing ‘bin-bower-1.3.12’
building path(s) ‘/nix/store/f0r368pfxwdl00l5mqxwsxsmyjcyizxh-user-environment’
created 2527 symlinks in user environment

[bburdette@nixosthe1:~]$ bower

module.js:340
    throw err;
          ^
Error: Cannot find module 'es5-ext/object/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/nix/store/39ig3zjd3q67q0m1xac396gdvhmhx5jr-node-d-0.1.1/lib/node_modules/d/index.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

[bburdette@nixosthe1:~]$

**Comment by bburdette** [comment]
BTW this is on the unstable channel:

[bburdette@nixosthe1:~]$ sudo nix-channel --list
[sudo] password for bburdette: 
nixos http://nixos.org/channels/nixos-unstable

[bburdette@nixosthe1:~]$

**Comment by ryantm** [comment]
I was able to reproduce this.

````
[ryantm@rtmnix:~]$ nix-env -i bin-bower
...
...
[ryantm@rtmnix:~]$ bower

module.js:340
    throw err;
          ^
Error: Cannot find module 'es5-ext/object/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/nix/store/ryfv788jsrpv8mww3h9vmxjmm22r8w7i-node-d-0.1.1/lib/node_modules/d/index.js:3:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

[ryantm@rtmnix:~]$ uname -a
Linux rtmnix 3.14.27 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
[ryantm@rtmnix:~]$ nix-channel --list
nixos https://nixos.org/channels/nixpkgs-unstable

````

**Comment by offlinehacker** [comment]
It Works for me on latest master and on latest channel. Make sure that you
update the channel and that you are installing from updated channel, also
make sure you are using correct profile. I fixed node packages recursive
dependencies 10 days ago and channel was updated 2days ago.

**Comment by offlinehacker** [comment]
Also try to install with nix-env -iA nixpkgs.nodePackages.bower

**Comment by bburdette** [comment]
I did a nix-channel --update and also nix-env --upgrade today, bower was still broken.  But after "nix-env -e bin-bower" and then "nix-env -i bin-bower", its working now.  Great!

**Comment by offlinehacker** [comment]
Cool, that's probably because nix detected same version and didn't update
package, despite builder being fixed for recursive dependencies.
