### ISSUE TITLE
python.gevent broken since upgrading to Python 2.7.9

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#5782]
https://github.com/gevent/gevent/issues/477 is the upstream issue. Suggest we apply https://bazaar.launchpad.net/~ubuntu-branches/ubuntu/utopic/python-gevent/utopic/view/head:/debian/patches/sslwrap.py in the meantime.

**Comment by iElectric** [comment]
Fixed.

**Comment by ocharles** [comment]
Woohoo! :raised_hands:

**Comment by ocharles** [comment]
Unfortunately, I have to retract my Woohoo - still not quite there:

```
[root@api-staging:~]# wal-e backup-list
name	last_modified	expanded_size_bytes	wal_segment_backup_start	wal_segment_offset_backup_start	wal_segment_backup_stop	wal_segment_offset_backup_stop
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/nix/store/amhzm30gf3wh6hd6flfp620km849nrsa-wal-e-0.6.10/lib/python2.7/site-packages/wal_e/cmd.py", line 368, in main
            backup_cxt.backup_list(query=args.QUERY, detail=args.detail)
          File "/nix/store/amhzm30gf3wh6hd6flfp620km849nrsa-wal-e-0.6.10/lib/python2.7/site-packages/wal_e/operator/s3_operator.py", line 86, in backup_list
            for backup_info in bl_iter:
          File "/nix/store/amhzm30gf3wh6hd6flfp620km849nrsa-wal-e-0.6.10/lib/python2.7/site-packages/wal_e/worker/s3_worker.py", line 572, in __iter__
            for key in bucket.list(prefix=self.layout.basebackups()):
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/s3/bucket.py", line 472, in get_all_keys
            '', headers, **params)
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/s3/bucket.py", line 398, in _get_all
            query_args=query_args)
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
            retry_handler=retry_handler
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/connection.py", line 1068, in make_request
            retry_handler=retry_handler)
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/connection.py", line 942, in _mexe
            request.body, request.headers)
          File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/httplib.py", line 1001, in request
            self._send_request(method, url, body, headers)
          File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/httplib.py", line 1035, in _send_request
            self.endheaders(body)
          File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
            self._send_output(message_body)
          File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/httplib.py", line 850, in _send_output
            self.send(msg)
          File "/nix/store/nk1hw5c6jzin073difisgi0jfbbrqj7g-python-2.7.9/lib/python2.7/httplib.py", line 812, in send
            self.connect()
          File "/nix/store/lq02nssmwbqpm9qqgyki2kh1yb0jwcgw-python2.7-boto-2.34.0/lib/python2.7/site-packages/boto/https_connection.py", line 131, in connect
            ca_certs=self.ca_certs)
          File "/nix/store/amhzm30gf3wh6hd6flfp620km849nrsa-wal-e-0.6.10/lib/python2.7/site-packages/wal_e/cmd.py", line 63, in wrap_socket_monkey
            return original(*args, **kwargs)
          File "/nix/store/42jbbal3x0f8y2g53qg630dlqlx5db14-python2.7-gevent-1.0.1/lib/python2.7/site-packages/gevent/ssl.py", line 382, in wrap_socket
            ciphers=ciphers)
          File "/nix/store/42jbbal3x0f8y2g53qg630dlqlx5db14-python2.7-gevent-1.0.1/lib/python2.7/site-packages/gevent/ssl.py", line 84, in __init__
            ctx = SSLContext(ssl_version)
        NameError: global name 'SSLContext' is not defined
        
        STRUCTURED: time=2015-01-20T16:10:25.353896-00 pid=10085
```

**Comment by iElectric** [comment]
@ocharles did you manage to fix this?

**Comment by ocharles** [comment]
No, I haven't had time to look into this. It's still broken (I run a nixpkgs with a downgraded Python as a workaround).

**Comment by iElectric** [comment]
@ocharles I've pushed 869393a, could you test again? :)

**Comment by benley** [comment]
I'm seeing what I think is the same failure even with 0e0bc3a (in docker-registry in my case):

```
2015-03-08 15:59:41 [9459] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/wsgi.py", line 20, in <module>
    from .tags import *  # noqa
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/tags.py", line 22, in <module>
    store = storage.load()
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/storage/__init__.py", line 38, in load
    config=cfg)
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 72, in __init__
    super(Storage, self).__init__(path, config)
  File "/nix/store/k7pgfqiiryf1m5wp70yji3sm1fkh3sz4-python2.7-docker-registry-core-2.0.3/lib/python2.7/site-packages/docker_registry/core/boto.py", line 134, in __init__
    self._config.boto_bucket)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/connection.py", line 1070, in make_request
    retry_handler=retry_handler)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/connection.py", line 942, in _mexe
    request.body, request.headers)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
Traceback (most recent call last):
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nix/store/j1i27ibyb65lp3ll6z1lqjgkhi31gvmi-python2.7-gunicorn-19.1.0/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/wsgi.py", line 20, in <module>
    from .tags import *  # noqa
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/tags.py", line 22, in <module>
    store = storage.load()
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/storage/__init__.py", line 38, in load
    config=cfg)
  File "/nix/store/1g8dd8dzk84qvipkq8j6p4fpflmb7zw7-python2.7-docker-registry-0.9.1/lib/python2.7/site-packages/docker_registry/drivers/s3.py", line 72, in __init__
    super(Storage, self).__init__(path, config)
  File "/nix/store/k7pgfqiiryf1m5wp70yji3sm1fkh3sz4-python2.7-docker-registry-core-2.0.3/lib/python2.7/site-packages/docker_registry/core/boto.py", line 134, in __init__
    self._config.boto_bucket)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 521, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/connection.py", line 1070, in make_request
    retry_handler=retry_handler)
  File "/nix/store/v8fjkyj5ww1696n4c3z7gma547vs5xwf-python2.7-boto-2.36.0/lib/python2.7/site-packages/boto/connection.py", line 942, in _mexe
    request.body, request.headers)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/nix/store/mi3k70qyq1qd3cp913vnbwz7f5wbkg9a-python-2.7.9/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
```

**Comment by ocharles** [comment]
For `wal-e`, things seem to be working with a build against 0fd3db4ba1d1d6d3a6108970ef96b24853593414. @benley looks like your error is in gunicorn, so maybe that's something else.

**Comment by iElectric** [comment]
Sigh. Someone should port the whole code back to gevent properly. I'll ping people around, I really don't have the time to do this.

**Comment by benley** [comment]
@ocharles it's coming from gunicorn, but it's using gevent workers and hitting the same codepath. I'll figure something out :)

**Comment by domenkozar** [comment]
42d9fe8b09768b59ac55c2a3aaeea1174eaa393a upgrades gevent, @ocharles could you test again? I'd love to be able to reproduce this, then I can go fix boto if it's still a problem :)

**Comment by domenkozar** [comment]
looks like this is fixed
