### ISSUE TITLE
Kubernetes: control-plane-online-pre-start failed

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#60358]
## Issue description

The issue I'm seeing here is that kubernetes will not start properly with the following error:

```
warning: the following units failed: kube-control-plane-online.service

● kube-control-plane-online.service - Kubernetes control plane is online
   Loaded: loaded (/nix/store/8cisr9kn686c6js5h5knr8ik9wjrdfaw-unit-kube-control-plane-online.service/kube-control-plane-online.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sun 2019-04-28 09:02:22 BST; 36ms ago
  Process: 60385 ExecStartPre=/nix/store/04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start (code=killed, signal=TERM)

Apr 28 09:02:03 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:06 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:09 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:13 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:16 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:19 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:22 home 04ih2w1sky4qzpk5v6x5x3hcyqg5bn6w-unit-script-kube-control-plane-online-pre-start[60385]: Please enter Username: kubectl get --raw=/healthz: exit status 1
Apr 28 09:02:22 home systemd[1]: kube-control-plane-online.service: Start-pre operation timed out. Terminating.
Apr 28 09:02:22 home systemd[1]: kube-control-plane-online.service: Failed with result 'timeout'.
Apr 28 09:02:22 home systemd[1]: Failed to start Kubernetes control plane is online.
warning: error(s) occurred while switching to the new configuration
```

Clearly it's awaiting an interactive input but isn't getting it so eventually times out.

### Steps to reproduce

Using the following nix extract:

```
{ lib, pkgs, ... }:

{
  environment =
  {
    etc."profile".text = lib.mkAfter "export KUBECONFIG=/etc/kubernetes/cluster-admin.kubeconfig";
    systemPackages = with pkgs; [ kubectl ];
  };

services.kubernetes =
  {
    addons.dashboard.enable = true;
    kubelet.extraOpts = "--fail-swap-on=false";
    masterAddress = "localhost";
    roles = [ "master" "node" ];
  };
}
```

## Technical details

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/1gw1mzd1dgxv9jl9292cy89agkn6igcw-bash-interactive-4.4-p23-dev
copying path '/nix/store/1gw1mzd1dgxv9jl9292cy89agkn6igcw-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.0.9, NixOS, 19.09pre177249.dfd8f84aef1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.09pre177249.dfd8f84aef1, nixos-small-19.09pre177262.fc48e74127c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by srhb** [comment]
Fixed by #60415

**Comment by q3k** [comment]
This is still broken in at least two ways:
 - if you specify `cfg.apiserver.advertiseAddress` (which is supposed to be an IP address, not a name or address:port tuple), the curled URL is portless (eg. ends up being `https://ip/healthz`)
 - curl is called without the proper client side certificates or CA bundle

**Comment by q3k** [comment]
CC @johanot

**Comment by azazel75** [comment]
The first point seems to be another bug, different by the one that exposed here.
Your second point has been discussed already

**Comment by srhb** [comment]
Linking related issues, discussed out of band :-)

#60687 #60358
