### ISSUE TITLE
python3.pkgs.scikitlearn build broken

### ISSUE THREAD

**Issue by timokau** [NixOS/nixpkgs#63573]
## Issue description

The testsuite of scikitlearn on python3 was broken by the scipy 1.3.0 update in 1fcf121b62f11b5171e030ca59c722a28ff4f6a3. It fails with the same error that was reported [here](https://github.com/scikit-learn/scikit-learn/issues/13868). It doesn't fail on python2 since we still used scipy 1.2.1 there.

CC @FRidh

**Comment by averelld** [comment]
I think this was succesfully fixed by the above PR, but just not closed yet? @timokau

**Comment by timokau** [comment]
The build is still broken for me. Seems to be some impurity. Only merged the PR above because it didn't make the situation worse and the build works for some.

**Comment by FRidh** [comment]
Builds fine now so closing.
