### ISSUE TITLE
vscode: integrate vscode with libdbusmenu

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#65680]
**Describe the bug**
Allow vscode and firefox support for libdbusmenu,like with libreoffice

**To Reproduce**
1. Install `vscode` in KDE
2. Run `code` with ` "window.titleBarStyle": "native"`

**Expected behavior**
The title bar integrated in KDE's menu button

**Screenshots**
![Desktop 2_001](https://user-images.githubusercontent.com/6931743/62236426-9a931780-b3be-11e9-95d2-7cfbceac6855.png)

**Additional context**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.1.16, NixOS, 19.09pre186408.3d84cffe955 (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3pre20190712_aa82f8b`
 - channels(root): `"nixos-19.09pre186408.3d84cffe955"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
- vscode
- vscode-with-extensions
- vscodium
# a list of nixos modules affected by the problem
module:
```

**Comment by pasqui23** [comment]
According to the AUR,it only need libdbusmenu for this to work properly,but I have added said package to both envieroment.systemPackages and services.dbus.packages to no avail.

**Comment by brcha** [comment]
I managed to get VSCode to have DBusMenu support by running it manually with

$ LD_LIBRARY_PATH=/nix/store/32ghafsr1wd8ghrmcmz308nrx781dvfs-libdbusmenu-gtk3-16.04.0/lib code

as seen in the screenshot:

![Screenshot_20200212_015900](https://user-images.githubusercontent.com/37038/74293718-e8101a00-4d3b-11ea-8bec-75851002f16a.png)

I'm a NixOS newb (installed nixos several days ago when I bought a new computer), but I am guessing that adding libdbusmenu-gtk3 as a dependency for vscode (in the generic.nix file, I guess) would fix the problem with global menus for both vscode and vscodium. That would, theoretically, fix the same problem for other apps that have a similar issue (possibly with -gtk2 or _qt packages instead).

**Comment by pasqui23** [comment]
Still relevant,and https://github.com/NixOS/nixpkgs/pull/79889 still matter

**Comment by pasqui23** [comment]
Still relevant

**Comment by Artturin** [comment]
assuming fixed by https://github.com/NixOS/nixpkgs/pull/100235

**Comment by pasqui23** [comment]
Just built `codium` from master, https://github.com/NixOS/nixpkgs/pull/100235 did not fix this.

**Comment by Artturin** [comment]
Try libdbusmenu-gtk3 and make a pr If it works
