### ISSUE TITLE
firefox-wayland: warnings, quirks

### ISSUE THREAD

**Issue by matthias-t** [NixOS/nixpkgs#66093]
## Issue description

-   ```
    (firefox): GLib-GObject-WARNING **: invalid cast from 'GdkWaylandDisplay' to 'GdkX11Display'
    ```


- the font is weird. it's definitely not my default font

-   one of the cursor icons isn't working, the one when you hover a link
    ```
    Gdk-Message: Unable to load hand2 from the cursor theme
    ```

### Steps to reproduce

Use `firefox-wayland` on `sway`


## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.5, NixOS, 19.09.git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.173238.4b6dd53b90a"`

**Comment by wkral** [comment]
I ran into the font issue as well, but it's not exactly specific to Firefox on Wayland it's less prevalent but on some sites where they didn't properly set a font-family you'll see the same font as what appears for most of firefox on wayland. After debugging the issue I added the following to `~/.config/fontconfig/fonts.conf`

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <match target="pattern">
        <test qual="any" name="family">
            <string>-moz-default</string>
        </test>
        <edit mode="prepend" name="family">
            <string>Noto Sans</string>
        </edit>
    </match>
</fontconfig>
```

You can replace `Noto Sans` with your preferred font of choice and that will get picked up for rendering the Firefox chrome as well as being the default font on a page that hasn't set something.

Obviously this is a workaround, probably the Firefox package should inject this rule using the configured default font of the system into the global fontconfig. Alternatively this might but an issue for Mozilla, I'm not totally sure.

**Comment by matthias-t** [comment]
This seems to have been fixed upstream. I'm closing this, but feel free to reopen as needed

**Comment by All3xJ** [comment]
> This seems to have been fixed upstream. I'm closing this, but feel free to reopen as needed

I still have this issue in Firefox 89

**Comment by a-m-joseph** [comment]
I still have this issue in Firefox 91.4.1esr; please reopen.

**Comment by robbins** [comment]
Also happening here, latest unstable channel. Font has changed and the cursor doesn't change to the 'hand' when hovering over links, etc with the same log message spam: `Unable to load hand2 from the cursor theme`

**Comment by a-m-joseph** [comment]
In case anybody else encounters this, I was able to solve it by installing the `adwaita-icon-theme` derivation.  Having it in your profile (~/.nix-profile/share/icons) fixes the bug.

Unfortunately that derivation drags in all of gnome.  If you want the hand icon without gnome, add this to your `overlays.nix`

```
  (final: prev: { adwaita-icon-theme-without-gnome = prev.gnome.adwaita-icon-theme.overrideAttrs (oldAttrs: { passthru = null; }); })
  (final: prev: { adwaita-icon-theme-without-gnome = prev.gnome.adwaita-icon-theme.override      { gnome = null; gtk3 = null; }; })
```

and then `nix-env -iA adwaita-icon-theme-without-gnome`
