### ISSUE TITLE
keepassxc fails to start due to some Qt error on `unstable`

### ISSUE THREAD

**Issue by gregor-alexandru** [NixOS/nixpkgs#68853]
**Describe the bug**
Starting keepassxc fails with a core dump due to a Qt error. Setting export QT_DEBUG_PLUGINS=1 gives us following trace:
```
QFactoryLoader::QFactoryLoader() checking directory path "/home/earendil/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/run/wrappers/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/earendil/.nix-profile/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/etc/profiles/per-user/earendil/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/var/nix/profiles/default/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/run/current-system/sw/lib/qt-5.12.3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/ryq0biggsg93bj962bkw9mhcrxv92dn7-keepassxc-2.4.3/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**To Reproduce**
1. have keepassxc installed (unstable)
2. start keepassxc
3. watch the world burn

**Expected behavior**
application doesn't crash

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.13, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd, nixpkgs-20.03pre193019.a26445a2ddf"`
 - channels(earendil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/68513

**Comment by dms-cat** [comment]
@worldofpeace That was merged 8 days ago, but is still happening:

```text
$ keepassxc
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.71, NixOS, 19.09pre192418.e19054ab3cd (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09pre192418.e19054ab3cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by worldofpeace** [comment]
Your [channel](e19054ab3cd) doesn't have this commit c6d516dfc49c1d84ef03605e0d2b8aa3ea8ae431.

**Comment by l0b0** [comment]
Where would I find out in general what the sensible next step is once I have that information? Should I manually patch my installation (and how complex/risky is that?), use a different channel (ditto about the risk), or is the best option just to use `keepassxc-cli` until this arrives on unstable (how long should I expect that to take?)?

Thanks a bunch for taking the time to answer a newbie! I'm completely spoiled by Arch Linux.

**Comment by worldofpeace** [comment]
Hi @l0b0, I'd be happy to help you.

Putting this in your `configuration.nix` should work
```nix
nixpkgs.overlays =  [
  (self: super: {
    keepassxc = super.keepassxc.overrideAttrs(old: {
      preFixup = ''
        wrapQtApp $out/bin/keepassxc
      '';
    });
  })
];
```

**Comment by l0b0** [comment]
Fantastic @worldofpeace, thank you again!
