### ISSUE TITLE
NixOS does not start degraded mdadm raid1 arrays from initrd/initramfs

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#72608]
**Describe the bug**
A degraded mdadm raid1 array that is used as rootfs will fail to be assembled and halt the boot.

**To Reproduce**
1. Have mdadm raid1 array as rootfs.
2. Fail one disk
3. Reboot.

**Expected behavior**
Booting should succeed, with degraded array.

**Additional context**
I noticed this issue in 2017 (https://github.com/NixOS/nixpkgs/issues/31840). Since then I've been working around this bug with:

```
  boot.initrd.preLVMCommands = ''
    for dev in /dev/md*; do
        if [ -b "$dev" ]; then
            mdadm --run "$dev"
        fi
    done
  '';
```

Upstream mdadm comes with systemd services to handle this case (degraded arrays), but it assumes running systemd in the initrd/initramfs. So this issue might be automagically fixed if/when https://github.com/NixOS/nixpkgs/issues/72401 is implemented.

I believe running degraded arrays works out of the box on distros that use dracut initramfs (e.g. fedora).

For info about the systemd initrd interface, see here: https://www.freedesktop.org/wiki/Software/systemd/InitrdInterface/

**Comment by erisd** [comment]
I run into the same Issue - thanks for documenting that! Is there any fix available? That should hit people only when they "have other problems" - like a degraded raid...

**Comment by kitor** [comment]
Bump, still a problem.

**Comment by hexadecimal233** [comment]
running nixos on my nas, and still encountered with "missing slot" error.
