### ISSUE TITLE
nixos-unstable channel hasn't updated in over 2 weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#7589]
[nixos-unstable](https://github.com/NixOS/nixpkgs-channels/tree/nixos-unstable) appears to be stuck at 2d8cfe76a9e4f05e391d30f1654d45dee5993b8a from April 13th. [nixos-unstable-small](https://github.com/NixOS/nixpkgs-channels/tree/nixos-unstable-small) is a little more up-to-date, but also lags 7 days by now.

**Comment by domenkozar** [comment]
That's because all installer tests are failing: http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

**Comment by domenkozar** [comment]
For some reason installer tests are building glibc, which shouldn't happen. @wkennington @lethalman @vcunat  thoughts?

**Comment by lethalman** [comment]
@domenkozar why not?

**Comment by domenkozar** [comment]
Because installer doesn't have access to networking as we want to support offline installs.

**Comment by wkennington** [comment]
It definitely shouldnt be building glib

**Comment by vcunat** [comment]
It isn't building glibc but glibc-locales.

**Comment by wizeman** [comment]
> It isn't building glibc but glibc-locales.

Then maybe it's related to 650492c5c87b4a7d4ab2afc3502e3656a4ac4e0a? @edolstra?

**Comment by vcunat** [comment]
Yes, looks likely, although the glib leak must be due to something else.

**Comment by wkennington** [comment]
Oh right yeah, definitely that change

**Comment by wkennington** [comment]
It seems like it would make the most sense for the installer tests not to
install them as well so as not to waste time and temporary space. It does
raise the question about putting them in the iso though, I think that's
probably a good idea for the graphical one. Maybe even the minimal.

**Comment by edolstra** [comment]
It's not entirely obvious why this happens, given that both the installation CD and the target configuration include `modules/profiles/minimal.nix` (and thus should get the same Glibc locales).

**Comment by bluescreen303** [comment]
`nixpkgs-unstable` is stuck at march 22.
should I just switch to nixos-unstable for nixpkgs?

**Comment by vcunat** [comment]
Ah, that seems caused by de0f122b016c, as Hydra claims to miss ``lib.tests``, but I don't yet see what's the problem in there.

**Comment by wizeman** [comment]
nixos-unstable is still stuck at the same commit, despite the fixes done so far... so reopening.

**Comment by vcunat** [comment]
The jobset hasn't even evaluated since the fix was pushed ;-)

**Comment by wizeman** [comment]
What do you mean?

This evaluation: https://hydra.nixos.org/build/21847931
.. contains this fix: 19366a10fcfa33acc1d150e6815cc49bd1a59988

... yet, the installer tests are still failing, right?

**Comment by domenkozar** [comment]
Yes it has, recent `nixos-install` changes broke the tests:

```
machine# setting root password...
machine# Enter new UNIX password: Retype new UNIX password: passwd: Authentication information cannot be recovered
machine# passwd: password unchanged
machine: exit status 10
machine: output: 
error: command `nixos-install < /dev/null >&2' did not succeed (exit code 10)
command `nixos-install < /dev/null >&2' did not succeed (exit code 10)
```

**Comment by wizeman** [comment]
Could it be caused by 7b37a5f168706db5efa33599354f5c1967ac4c51? @Jookia?

**Comment by domenkozar** [comment]
Hopefully fixed in ff88f4bcda606d9a47f807b773749280998e64ac

**Comment by vcunat** [comment]
Ah, I got confused by bluescreen303, thinking this issue is about nix**pkgs**-unstable and not nix**os**-unstable. In nixpkgs the lag is much worse, but it doesn't depend on nixos tests...

**Comment by Jookia** [comment]
On 04/30/2015 02:48 AM, Domen Kožar wrote:
> Hopefully fixed in ff88f4b
> <https://github.com/NixOS/nixpkgs/commit/ff88f4bcda606d9a47f807b773749280998e64ac>

I actually have no recollection of changing that given I wasn't sure 
exactly why it was there. I must've gone over that patch at least a 
dozen times too but only checked the part I intended to change.

Sorry everyone!
Jookia.

**Comment by lethalman** [comment]
The very bad consequence of all this is the fact that most of development has now shifted to the staging branch. We must kick staging I believe. @edolstra ideas?

**Comment by edolstra** [comment]
@lethalman I don't understand. Why would development shift to the staging branch? And what does that have to do with the unstable channel?

**Comment by lethalman** [comment]
@edolstra nothing with the unstable channel but with delayed hydra builds in general. The staging branch is not merged into master since 6 weeks. I've just had a PR against a staging branch because of GNOME instead of master, and that's only a recent contribution.

No wonder there are many other updates in staging that should have gone to master instead but forced by the fact that a dependency has been updated only in staging.

**Comment by vcunat** [comment]
The nixpkgs-unstable channel should update once the last ~4k jobs finish in the evaluation, as the critical ones succeeded http://hydra.nixos.org/build/21861946#tabs-constituents

**Comment by domenkozar** [comment]
Done
