### ISSUE TITLE
gpm: support on darwin

### ISSUE THREAD

**Issue by nomosyn** [NixOS/nixpkgs#7808]
```
error: Package ‘gpm-1.20.7’ in ‘/Users/nomos/Documents/tools/nixpkgs/pkgs/servers/gpm/default.nix:35’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.
For `nix-env` you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)


----


$ cd <path_to>/nixpkgs; git rev-parse HEAD
c206c9cd95811749ec8ee11905422d0ea046470d


----


$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136

```

**Comment by ericbmerritt** [comment]
I am not sure supporting gpm on mac is the correct fix for this (though its a problem in and of its self). Essentially, something is now requiring `vwm` which, through a chain of dependencies, eventually requires `gpm`.  I have been unable to figure out whats trying to call `vwm` be default though. As a temporary work around to those using mac you can comment out the line `vwm = callPackage ../applications/window-managers/vwm { };` and things will build.

**Comment by vcunat** [comment]
Ah, I didn't realize gpm might not make sense on darwin, so it's about making stuff not depend on gpm on darwin.

In the original report I can't even see what package was attempted. (Note that I don't have any darwin myself, so I can't test.)

**Comment by edolstra** [comment]
It's caused by 23f836615d510ba0e7346bb633575727c108353e, which made ncurses depend on gpm. I'm not sure it should do that on *any* platform.

**Comment by edolstra** [comment]
Sorry, meant commit ee78173b213059e6c885dc0c4d3bf4da7d3cb229.

**Comment by vcunat** [comment]
That has been fixed: ncurses no longer needs it as of 82ba13111c72 (on master). I tested the evaluation.

**Comment by vcunat** [comment]
Well, it was pushed only half an hour ago. @nomosyn, can you confirm your case is solved after that commit?

**Comment by nomosyn** [comment]
ok. Doing it now!

**Comment by nomosyn** [comment]
OK it passes. But still cannot `nix-env -u`.  I close this issue, and open an other one.
