### ISSUE TITLE
ghcjs fails to build on master

### ISSUE THREAD

**Issue by purefn** [NixOS/nixpkgs#7881]
```
Build with /nix/store/cgddwzz9hkdgprvbymphv8yprc66zxk7-ghc-7.10.1.
unpacking sources
unpacking source archive /nix/store/3r5nq87phg6414c69hpsg3ar6gih2bjr-ghcjs-d4322c2
source root is ghcjs-d4322c2
patching sources
applying patch /nix/store/52gz6wci2vws1x382rhp1qcmz00x6ssg-ghcjs.patch
patching file src-bin/Boot.hs
patching file src/Compiler/Info.hs
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-ghcjs-0.1.0.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-ghcjs-0.1.0.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/pv193bjn31xxs4jfwgnpfgynw3lvai7h-ghcjs-0.1.0 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-ghcjs-0.1.0.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/pv193bjn31xxs4jfwgnpfgynw3lvai7h-ghcjs-0.1.0/lib/ghc-7.10.1/ghcjs-0.1.0 --ghc-option=-j1 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-lib-dirs=/nix/store/kf1ll233h6yddqk53651g55l3anncx3h-git-2.4.1/lib --extra-include-dirs=/nix/store/q6qy68r2jn577lx43706zcxmf3dk4j87-gnumake-4.1/include --extra-include-dirs=/nix/store/jfxhwznhw4a5qk4b93jrqr11wfv02aw1-libtool-2.4.6/include --extra-lib-dirs=/nix/store/jfxhwznhw4a5qk4b93jrqr11wfv02aw1-libtool-2.4.6/lib --extra-include-dirs=/nix/store/wrwk289fryjq8c42nh5y1fi6lqrjsl16-gmp-5.1.3/include --extra-lib-dirs=/nix/store/wrwk289fryjq8c42nh5y1fi6lqrjsl16-gmp-5.1.3/lib --extra-include-dirs=/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/include --extra-lib-dirs=/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/lib --extra-include-dirs=/nix/store/an70qxr58scmac2w6phh0k3zjy6n0lya-nodejs-0.12.0/include --extra-lib-dirs=/nix/store/an70qxr58scmac2w6phh0k3zjy6n0lya-nodejs-0.12.0/lib
Configuring ghcjs-0.1.0...
Setup: At least the following dependencies are missing:
attoparsec ==0.12.*, lens >=4.0 && <4.10
builder for ‘/nix/store/rm1yp8lms71hm3a3lkha907k8v2lmncy-ghcjs-0.1.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/mw3k20c09lkh7ab9ali4r1wjd3f22f3l-ghcjs-0.1.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/mw3k20c09lkh7ab9ali4r1wjd3f22f3l-ghcjs-0.1.0.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

The attoparsec version in nixpkgs is 0.13 and lens is 4.10.

**Comment by mdorman** [comment]
This particular issue has been addressed in 13e48c8cc9ff9f8bd894cbebc015872071cc6c66, though that just sets it up to fail later because (as far as I can tell), the aeson embedded in ghcjs-boot doesn't like the updated attoparsec?

> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/ghcjs-boot$ [cabal]: /nix/store/w746zfi9rc2qbz7fdjs7xh5vqxshknd3-cabal-install-1.22.4.0/bin/cabal "--config-file" "/nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/cabalBootConfig" "install" "./boot/async" "./boot/aeson" "./boot/attoparsec" "./boot/case-insensitive" "./boot/dlist" "./boot/extensible-exceptions" "./boot/hashable" "./boot/mtl" "./boot/old-time" "./boot/parallel" "./boot/scientific" "./boot/stm" "./boot/syb" "./boot/text" "./boot/unordered-containers" "./boot/vector" "./ghcjs/ghcjs-base" "--global" "--ghcjs" "--one-shot" "--avoid-reinstalls" "--builddir" "dist" "--with-compiler" "/nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs" "--with-gcc" "/nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/cc" "--with-hc-pkg" "/nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs-pkg" "--prefix" "/nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0" "--libdir" "$prefix/lib/$compiler" "--libsubdir" "$pkgid" "--enable-documentation" "--haddock-html" "--haddock-hyperlink-source" "--enable-library-profiling" "--root-cmd" "/nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/run.sh" "-v2" "--dry-run"
> /nix/store/w746zfi9rc2qbz7fdjs7xh5vqxshknd3-cabal-install-1.22.4.0/bin/cabal --config-file /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/cabalBootConfig install ./boot/async ./boot/aeson ./boot/attoparsec ./boot/case-insensitive ./boot/dlist ./boot/extensible-exceptions ./boot/hashable ./boot/mtl ./boot/old-time ./boot/parallel ./boot/scientific ./boot/stm ./boot/syb ./boot/text ./boot/unordered-containers ./boot/vector ./ghcjs/ghcjs-base --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs --with-gcc /nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/cc --with-hc-pkg /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs-pkg --prefix /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0 --libdir $prefix/lib/$compiler --libsubdir $pkgid --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/run.sh -v2 --dry-run
> /nix/store/gw2j0acvkyzv0di2zbyx1yigrb49mhj0-alex-3.1.4/bin/alex --version
> looking for tool c2hs near compiler in
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin
> /nix/store/jvfb0yznafw2s4fr9910jyx9fi821475-haskell-cpphs-1.19/bin/cpphs --version
> /nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/cc -dumpversion
> /nix/store/cgddwzz9hkdgprvbymphv8yprc66zxk7-ghc-7.10.1/bin/ghc --numeric-version
> /nix/store/cgddwzz9hkdgprvbymphv8yprc66zxk7-ghc-7.10.1/bin/ghc-pkg --version
> looking for tool haddock near compiler in
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin
> found haddock in
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/haddock-ghcjs
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/haddock-ghcjs --version
> /nix/store/w9vf6ankhjjxarssawnirkpzc3xwygiy-happy-1.19.5/bin/happy --version
> /nix/store/cgddwzz9hkdgprvbymphv8yprc66zxk7-ghc-7.10.1/bin/hpc version
> looking for tool hsc2hs near compiler in
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin
> found hsc2hs in
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/hsc2hs-ghcjs
> /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/hsc2hs-ghcjs --version
> /nix/store/0yx22y4cl7z7ng0kcjlmghyaxm9wd4hq-hscolour-1.23/bin/HsColour -version
> /nix/store/fd99fvl3paah5cnf825izxpafm3c2xpr-gnutar-1.28/bin/tar --help
> Warning: No remote package servers have been specified. Usually you would have
> one specified in the config file.
> Choosing modular solver.
> Resolving dependencies...
> cabal: Could not resolve dependencies:
> trying: aeson-0.8.1.0 (user goal)
> next goal: attoparsec (user goal)
> rejecting: attoparsec-0.12.1.3 (conflict: aeson => attoparsec>=0.13.0.0)
> Dependency tree exhaustively searched.
> ghcjs-boot: error running: /nix/store/w746zfi9rc2qbz7fdjs7xh5vqxshknd3-cabal-install-1.22.4.0/bin/cabal --config-file /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/cabalBootConfig install ./boot/async ./boot/aeson ./boot/attoparsec ./boot/case-insensitive ./boot/dlist ./boot/extensible-exceptions ./boot/hashable ./boot/mtl ./boot/old-time ./boot/parallel ./boot/scientific ./boot/stm ./boot/syb ./boot/text ./boot/unordered-containers ./boot/vector ./ghcjs/ghcjs-base --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs --with-gcc /nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/cc --with-hc-pkg /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/bin/ghcjs-pkg --prefix /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0 --libdir $prefix/lib/$compiler --libsubdir $pkgid --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /nix/store/wpm9j9k9hi10nqhswwi32nsjxl512rh5-ghcjs-0.1.0/lib/ghcjs-0.1.0/run.sh -v2 --dry-run
> exit status: 1
> stderr: Warning: No remote package servers have been specified. Usually you would have
> one specified in the config file.
> cabal: Could not resolve dependencies:
> trying: aeson-0.8.1.0 (user goal)
> next goal: attoparsec (user goal)
> rejecting: attoparsec-0.12.1.3 (conflict: aeson => attoparsec>=0.13.0.0)
> Dependency tree exhaustively searched.
> 
> builder for ‘/nix/store/n2pg2ljjknv5s2cg8far9c5ijdgrrabk-ghcjs-0.1.0.drv’ failed with exit code 1
> error: build of ‘/nix/store/n2pg2ljjknv5s2cg8far9c5ijdgrrabk-ghcjs-0.1.0.drv’ failed

**Comment by peti** [comment]
@purefn, please report this issue upstream.

**Comment by peti** [comment]
@mdorman, I think we should drop https://github.com/NixOS/nixpkgs/commit/13e48c8cc9ff9f8bd894cbebc015872071cc6c66 again. The jailbreak doesn't achieve anything: the build still fails. The only difference is that now it compiles for 30 minutes before failing instead of failing immediately, which is not an improvement, IMHO.

**Comment by mdorman** [comment]
Yeah, I'm OK with that.  I've made a couple of stabs at resolving it to no success---I am usually able to figure out what needs fixing, and then get you to tell me how to do it right :), but this has proven more intractable.

**Comment by purefn** [comment]
Raised it upstream as https://github.com/ghcjs/ghcjs/issues/345

**Comment by peti** [comment]
Thank you!
