### ISSUE TITLE
i3 build is broken

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#7957]
the i3 test code calls out to git, which
- isn't available since it's not a dep
- doesn't make sense since the build doesn't have access to git info anyway

It seems like the call to git (line 111 of complete-run.pl) has existed since at least 2011 in the i3 codebase, so I don't know why this just crops up now

**Comment by anderspapitto** [comment]
also, even if the git command is removed, there are some perl errors later on. It's probably beyond me to fix at this point. Also, from looking at hydra, it seems that the build started failing some time after the last changes to the i3 package - so maybe some perl infrastructure changes or similar are at fault?

**Comment by domenkozar** [comment]
What channel is this?

**Comment by anderspapitto** [comment]
unstable, at commit 9636001cd3ad2d18341fd9f573c1099596607b54

**Comment by domenkozar** [comment]
According to http://hydra.nixos.org/build/22408864/nixlog/1/raw it fails to build sometimes during tests run

**Comment by jtanguy** [comment]
It seems that `git` is called to create the output directory for the test results. It does not seem to be critical, as [some builds](https://hydra.nixos.org/build/22205123) do not fail.

On my machine, the tests fail because Xephyr could not open a host display and then segfaults.

~~~
running tests
Starting 1 Xephyr instances, starting at :100...
Can't exec "git": No such file or directory at ./complete-run.pl line 111.
Use of uninitialized value in concatenation (.) or string at ./complete-run.pl line 111.
Could not connect to display :100
/nix/store/hjs76xikir4s51wdi21i0k3wc1qx86ca-xvfb-run/bin/.xvfb-run-wrapped: line 170:  7466 Segmentation fault      DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1

Xephyr cannot open host display. Is DISPLAY set?
builder for ‘/nix/store/ch1myzv4nzy2gyk448p6jnizcvcin3fw-i3-4.10.2.drv’ failed with exit code 1
~~~

I'm running nixos "15.06pre62649.f93a8ee" in a virtualbox guest.

**Comment by dmalikov** [comment]
Is it the same error?

https://gist.github.com/dmalikov/d1ef98b039f842c4c143

**Comment by anderspapitto** [comment]
@dmalikov looks like it to me - including the same perl errors even after the call to `git`

**Comment by jtanguy** [comment]
Weird. I didn't have all those errors. Even weirder, now it builds and the tests passes on my machine, on latest unstable (I just cleared the channel cache and `nixos-rebuild` my system).

However, now that I take a look back to my `/etc/nixos/configuration.nix` I have `which` in my `environment.systemPackages`, followed by a comment "Required by i3", but I don't remember why I put that there.
Maybe that could be a part of the problem?

**Comment by anderspapitto** [comment]
@jtanguy `which` was required because it was used by i3-sensible-terminal & co - I fixed that some time ago here https://github.com/NixOS/nixpkgs/pull/6363. This bug looks to be unrelated entirely.

Locally, I've been working around this by just disabling the tests

**Comment by domenkozar** [comment]
This is fixed

**Comment by anderspapitto** [comment]
@domenkozar 
As far as I can tell, it's not completely fixed - the tests have just been disabled until someone fixes it for real - see `doCheck = false` in 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/i3/default.nix

We may want to keep this or some other issue open until the tests are reenabled
