### ISSUE TITLE
Sage build is broken

### ISSUE THREAD

**Issue by fusion809** [NixOS/nixpkgs#81449]
**Describe the bug**
Whenever I run:

```bash
nixos-rebuild switch --upgrade
```

with `sagemath` listed in `systemPackages` the sagemath package is rebuilt, even when the latest version of SageMath available (8.9) is installed on my system. This is very irritating given that SageMath's test suite uses up a lot of CPU and RAM and takes around half an hour to an hour to complete and that's assuming it's successful, it frequently fails to run successfully on my PC. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `sagemath` to /etc/nixos/configuration.nix under systemPackages.
2. Run `nixos-rebuild switch --upgrade`
3. After your system has been successfully upgraded run the above command again and if you're observing this bug you should find that nix-build attempts to build sagemath again, despite SageMath already being installed. 

**Expected behaviour**
I expected SageMath to only be built by Nix when it was a new install (i.e. right after I had added it to systemPackages) or when a new version of SageMath was out.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.22, NixOS, 20.09pre215183.7948e6785b4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(fusion809): `"nixos-20.09pre215183.7948e6785b4, nixos-unstable"`
 - channels(root): `"nixos-20.09pre215183.7948e6785b4, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos-unstable`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sagemath
# a list of nixos modules affected by the problem
module: ?
```
(Not sure what 'module' to list above).

**Comment by FRidh** [comment]
Dependencies have been updated causing a rebuild, that's the whole concept behind Nix. If you want to pin sage or any package to a specific build, you can do that as well.

**Comment by timokau** [comment]
Looks like this is actually caused by some breakage: https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.sageWithDoc.x86_64-linux

It rebuilds every time because unfortunately nix doesn't cache failures. It only notices that sage is not available in the binary caches (since the build fails) and then tries to build it locally.

Do those local builds actually succeed?

**Comment by fusion809** [comment]
Usually not. Not sure if they've ever succeeded but usually they don't.

**Comment by timokau** [comment]
I fixed the build in #82240 and #82239. sage should be available in the binary channels again soon, so no local rebuilds will be necessary. Thanks for the report!

**Comment by fusion809** [comment]
Guessing the fact that tests are still failing is something I should report elsewhere?

**Comment by timokau** [comment]
No, here is fine. Looks like I broke it again while fixing it: https://github.com/NixOS/nixpkgs/pull/81950

Should work after https://github.com/NixOS/nixpkgs/pull/82311. Thanks again!

**Comment by timokau** [comment]
The build should be fixed now. This time I have double checked that it builds on master (a3735dcbd7b2530ae3bcf73fd91e1ca6aa9449e7).
