### ISSUE TITLE
Hash mismatch for jmtpfs

### ISSUE THREAD

**Issue by jcbrand** [NixOS/nixpkgs#8857]
When trying to install jmtpfs (by adding it to .configuration.nix), I get a hash mismatch error.

I ran `nixos-rebuild switch --upgrade`

Here's the error output:

> 100  168k    0  168k    0     0   112k      0 --:--:--  0:00:01 --:--:--  457k
output path ‘/nix/store/xz3rr4rp5w7jgaqba7kpxmyc9lp8ym03-v0.5.zip’ should have sha256 hash ‘09fw4g350mjz1mnga7ws5nvnsnfzs8s7cscl300mas1m9s6vmhz6’, instead has ‘13nwcqzcif0i3l8n3277ram0vjaam5ja5blbrjnifrz3jmvpmynz’
> cannot build derivation ‘/nix/store/4f997pmmmxn39cw1n780axz57azcra74-jmtpfs-0.5.drv’: 1 dependencies couldn't be built

**Comment by cillianderoiste** [comment]
@jcbrand I wonder if you updated just before the new channel was created (15-Jul-2015 03:07). If you try again, or include the output of `nixos-version` we can be sure. The new channel has the binary, which means it shouldn't download a zip file of the source either.

**Comment by vcunat** [comment]
The error you have should have been fixed long ago dda255f938c. Now I pick the fix to 14.12 to be sure.

**Comment by jcbrand** [comment]
Hi guys, thanks but I still get the error.

Here is my version:

> jc@sundew-02:22:~ (master)$ nixos-version
> 14.12.788.9172c7d (Caterpillar)

And here's what happens when I run `nixos-rebuild`:

> [root@sundew:/home/jc]# nixos-rebuild switch --upgrade
> Wide character in print at /nix/store/169sqhprai8bd7apkpisd868sqvb6h1l-nix-1.8/bin/nix-pull line 55.
> fetching list of Nix archives at ‘https://nixos.org/releases/nixos/14.12/nixos-14.12.794.5507250/MANIFEST.bz2’...
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
> 100 5737k  100 5737k    0     0  2066k      0  0:00:02  0:00:02 --:--:-- 2066k

removed

> trying https://github.com/JasonFerrara/jmtpfs/archive/v0.5.zip
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                Dload  Upload   Total   Spent    Left  Speed
> 100   122    0   122    0     0    230      0 --:--:-- --:--:-- --:--:--   257
> 100  168k    0  168k    0     0   120k      0 --:--:--  0:00:01 --:--:--  629k
> output path ‘/nix/store/xz3rr4rp5w7jgaqba7kpxmyc9lp8ym03-v0.5.zip’ should have sha256 hash ‘09fw4g350mjz1mnga7ws5nvnsnfzs8s7cscl300mas1m9s6vmhz6’,+
> cannot build derivation ‘/nix/store/4f997pmmmxn39cw1n780axz57azcra74-jmtpfs-0.5.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/aiv9ls59rj0hqfq27q9la40dgqmfyjgg-system-path.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/7si9272hbhp9gbr7mfmrbp6zakx382dm-nixos-14.12.794.5507250.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/7si9272hbhp9gbr7mfmrbp6zakx382dm-nixos-14.12.794.5507250.drv’ failed

**Comment by vcunat** [comment]
> jc@sundew-02:22:~ (master)$ nixos-version
> 14.12.788.9172c7d (Caterpillar)

Well, of course, as the fix is pushed six commits later to 14.12 branch. On the other hand, the channel updated three hours ago (i.e. *after* your last comment) and nixos-14.12.795.3b8e2f7 exactly contains it.

**Comment by jcbrand** [comment]
@vcunat, yep, works now. Thanks.
