### ISSUE TITLE
No tray icon for electron apps in swaywm.

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#90329]
**Describe the bug**
Discord and Riot-desktop (which I've tested it with) won't show tray icon.

**Additional context**
I'm using Swaywm, Waybar and have libappindicator-gtk3 installed.
Other xwayland apps like obs tray icon works.

**Comment by euank** [comment]
Discord's lack of a tray icon should have been fixed with https://github.com/NixOS/nixpkgs/pull/91375

riot-desktop, in my testing, shows a tray icon with the current nixpkgs.

Interestingly, https://github.com/NixOS/nixpkgs/pull/73058 claims it may be necessary to fix riot-desktop, but in practice that doesn't seem to be the case.

Note, I'm just testing with xmonad / X11, not sway/wayland, so it's possible there's something more to this issue.
Does it still repro for you?
If it does, can you see if #73058 has any bearing on it?

**Comment by Kazimazi** [comment]
Built those packages against master. Yeah, you are right, #91375 really fixed Discord. Riot-desktop still doesn't have tray icon.

**Comment by layus** [comment]
My config is not vanilla anymore, but for some reason element-dektop (riot's new name) has a correct tray icon on sway for me (as of today's nixpkgs-unstable).

@Kazimazi mind trying again ?

**Comment by Kazimazi** [comment]
@layus Alright, stable element-desktop works too. Since thats all the electron apps as of now that I use, I'm closing issue.

**Comment by layus** [comment]
For some reason it is not working anymore... This issue seems to be a huge waste of time because chromium changes the way it handles trays, and electron reverts the changes (a while after) and element (=riot) is sometimes slow to catch changes.

At the moment, I cannot even say who's the culprit for not displaying a status icon.
