### ISSUE TITLE
ripgrep: PCRE2 is not available in this build of ripgrep

### ISSUE THREAD

**Issue by taketwo** [NixOS/nixpkgs#91928]
**Describe the bug**

PCRE2 is not available in ripgrep that is installed with `nix-env -i ripgrep`. This wasn't always the case, i.e. some time ago (not sure how long though, maybe a month) it was available.

**To Reproduce**

1. `nix-env -i repgrep`
2. `rg --pcre2 foobar`

**Expected behavior**

Search using a PCRE2 regex should happen.

**Additional context**

I see that the expression has an option for PCRE2 and it is enabled by default:

https://github.com/NixOS/nixpkgs/blob/2c33e5da9eb9feb82e2b77000e8488fdb8032fbc/pkgs/tools/text/ripgrep/default.nix#L7

**Notify maintainers**

@tailhook @globin @Ma27 @zowoq 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.0-61-generic, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(sergey): `"nixpkgs-20.09pre232692.7db146538e4"`
 - nixpkgs: `/home/sergey/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by zowoq** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/91689

**Comment by taketwo** [comment]
@zowoq I've noticed that the PR that you referenced was merged 9 days ago. However, the current version of `ripgrep` still does not have PCRE2. Do you know what are the steps that we need to take to make sure that `nix-env -i ripgrep` yields a PCRE2-enabled version?

**Comment by taketwo** [comment]
@zowoq ping

**Comment by zowoq** [comment]
This was correctly fixed in #93128 and it's available in `nixpkgs-unstable`.

Updating the `nixpkgs` channel and `nix-env --upgrade --always ripgrep` should get the fixed version.

**Comment by taketwo** [comment]
Thanks for the instructions, works!
