### ISSUE TITLE
HTML5 video display frequently freezes after recent updates

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#9304]
I'm using Firefox from 48f49a730ed8a4759f6780899053e702f1f3945b to play Youtube videos. With that version, the video output freezes every couple of seconds until I move my mouse around a bit -- then video resumes. Audio continues all the while; it's just the video display that doesn't update anymore. This happens in both full-screen and embedded mode. Versions of Firefox prior to @wkennington's gstreamer-1 switch didn't have that issue.

**Comment by wkennington** [comment]
This should be fixed by reverting those changes.
5711761622ceccc1fb2c97c965150fa8495546fc
54dee45402634e06491042edc01c377d08bb589d

**Comment by peti** [comment]
I'm not sure whether the gstreamer update really is the culprit for this issue: I've re-built Firefox after those reverts, and the video problems still exist.

I see that meanwhile Firefox was also updated; I'll try the latest version ASAP.

**Comment by peti** [comment]
Issue still exists in ac8f239, which has Firefox 40.0.2, but it's occurring much more rarely than before. Not sure what this means. I reckon, the reason for these freezes is Firefox's new HTML5 video player; I don't think gstreamer-1 had anything to do with it.

**Comment by wkennington** [comment]
Well, it should be easy enough to unrevert those commits. However I had
reproducible issues with gstreamer-1 and Firefox that went away when I
removed it. Maybe this is a two part issue.

**Comment by deepfire** [comment]
This might be an old bug resurfacing: https://bugzilla.mozilla.org/show_bug.cgi?id=1100000

I haven't seen any signs that it was conclusively resolved.

**Comment by deepfire** [comment]
I have seen manifestations of 1100000 in the range of FFearly3x-FF41, with the following caveats:
- outside of NixOS
- wonky hardware with unstable hardware timers

**Comment by peti** [comment]
This issue is no longer present in recent versions of Firefox as distributed on `master`. If someone else still has it, please re-open.
