### ISSUE TITLE
NixOS broken on master

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#97305]
**Describe the bug**
When i build a test VM from master (a5121f73e3f89556d33e7b1fc9c6d70673b20458), i can't login and many services don't start.

![Screenshot from 2020-09-06 19-30-31](https://user-images.githubusercontent.com/91113/92331528-9cc2ad80-f077-11ea-9a1e-82c1c1d473b4.png)

![Screenshot from 2020-09-06 19-31-06](https://user-images.githubusercontent.com/91113/92331529-9fbd9e00-f077-11ea-8d04-dae0f3cfaf27.png)

![Screenshot from 2020-09-06 19-23-33](https://user-images.githubusercontent.com/91113/92331425-c6c7a000-f076-11ea-888d-84f30561ecf3.png)

https://peertube.social/videos/watch/7b32ecdd-9fcc-4658-9090-89f10978d19e

**To Reproduce**

```
{ config, pkgs, ... }:

{
  users.extraUsers.root.password = "root";
  documentation.enable = false;
}
```

1. `nixos-rebuild build-vm -I nixpkgs=~/code/nixpkgs/ -I nixos-config='/home/davidak/root'`
2. start vm: `/nix/store/js7vf96xzsvj6h23p3jcbixlx0qyvmhq-nixos-vm/bin/run-nixos-vm`

**Expected behavior**
NixOS boots into working system

**Comment by davidak** [comment]
I'm bisecting it right now.

**Comment by davidak** [comment]
The issue is not related to any commit.

It happens when you execute `nixos-rebuild build-vm` a second time without removing the disk image manually.

```
rm ./nixos.qcow2
nixos-rebuild build-vm -I nixpkgs=~/code/nixpkgs/ -I nixos-config='/home/davidak/root
```

issue resolved

**Comment by Mic92** [comment]
should be fixed by https://github.com/NixOS/nixpkgs/pull/98544

**Comment by ElvishJerricco** [comment]
I still get something similar on unstable if I kill the machine while it's booting. Start a blank NixOS VM and kill the VM when systemd takes over in stage 2, and that VM will not have valid users upon reboot.

**Comment by Mic92** [comment]
> I still get something similar on unstable if I kill the machine while it's booting. Start a blank NixOS VM and kill the VM when systemd takes over in stage 2, and that VM will not have valid users upon reboot.

What does the file look like in this case?

**Comment by Melkor333** [comment]
Something like this happened to me on my workstation. It may also have been more like https://github.com/NixOS/nixpkgs/issues/61755 or something completely different, can't tell. But what happened is that I rebuilt my local system multiple times with `nixos-rebuild switch` and after that I couldn't reboot my system anymore. I was playing with `services.xss-lock` and `home-managers` `screen-locker` modules so that definitively shouldn't have any effect.

Initially I had an error saying something like `mv: /bin/sh is already the same as `bin/.sh.tmp`. But in reality `/bin/sh` was a broken symlink pointing to nothing ( `-> ''`) while `/bin/.sh.tmp` was a proper symlink into the nix store. When I removed `/bin/sh` it told me that the same was the case for `/usr/bin/env` and `/usr/bin/.env.tmp`. After removing `(usr/bin/env` too, I got above error. Removing `uid-map`, `gid-map` and lateron also `auto-subuid-map` seems to solve the problem as the machine regenerated the files properly (I actually renamed the whole `/etc/ -> /etc.old` and `/var -> /var.old`  and ran `nixos-install` from a live ISO). Weirdly the `home-manager` service for my user failed with following error for a lot of files:
```
Apr 28 22:05:10 afonil hm-activate-samuelh[1443]: cmp: /home/samuelh/.config/dunst/dunstrc: Is a directory
Apr 28 22:05:10 afonil hm-activate-samuelh[1430]: Existing file '/home/samuelh/.config/dunst/dunstrc' is in the way of '/nix/store/6dszxk7vkdwayk2msir9rgycglwfhyq2-home-manager-files/.config/dunst/dunstrc'
Apr 28 22:05:10 afonil hm-activate-samuelh[1445]: cmp: /home/samuelh/.config/environment.d/10-home-manager.conf: Is a directory
Apr 28 22:05:10 afonil hm-activate-samuelh[1430]: Existing file '/home/samuelh/.config/environment.d/10-home-manager.conf' is in the way of '/nix/store/6dszxk7vkdwayk2msir9rgycglwfhyq2-home-manager-files/.config/environment.d/10-home-manager.conf'
Apr 28 22:05:10 afonil hm-activate-samuelh[1447]: cmp: /home/samuelh/.config/git/config: Is a directory
Apr 28 22:05:10 afonil hm-activate-samuelh[1430]: Existing file '/home/samuelh/.config/git/config' is in the way of '/nix/store/6dszxk7vkdwayk2msir9rgycglwfhyq2-home-manager-files/.config/git/config'
```

I solved this with the following magic. It takes the files from the journal and moves them to the folder `bad`. After that I could restart the service just fine:
```
mkdir bad
mv -t bad/ $(journalctl -u home-manager-samuelh.service | grep 'Existing file' | awk '{ print $8 }' | tr -d "'")
```

The files in the folder `bad` are equally corrupted as the `/bin/sh` and `/usr/bin/en` files were:
```
[samuelh@afonil:~]$ ls -lah bad/
total 4.0K
drwxr-xr-x 1 samuelh users 1.1K Apr 28 22:25 .
drwx------ 1 samuelh users  872 Apr 29 06:51 ..
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 10-home-manager.conf -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 {446900e4-71c2-419f-a6a7-df9c091e268b}.xpi -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 87677a2c52b84ad3a151a4a72f5bd3c4@jetpack.xpi -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 blueman-applet.service -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 config -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 config.nix -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 {d7742d87-e61d-4b78-b8a1-b469842139fa}.xpi -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 dunstrc -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 dunst.service -> ''
lrwxrwxrwx 1 samuelh users    0 Apr 28 12:51 flameshot.service -> ''
```

I assume this is some error during activation, maybe even a problem with `btrfs`?

It might make sense to have some kind of check in the activation which makes sure that such broken symlinks and broken/unreadable `/var/lib/nixos/uid-map`files are properly removed/recreated (Or are the `*-map` files usually never recreated?). Of course fixing the reason this behaviour happens is even better but I can imagine that there is always some edge case where e.g. a cold reset of a system which is activating can cause such broken symlinks which don't get overwritten properly.

**Comment by brianmcgee** [comment]
I had a similar experience as @Melkor333 today, in the end I had to blow away `auto-subuid-map` to get things working again.

**Comment by MakiseKurisu** [comment]
I also encountered this issue. I run NixOS in a VM running multiple podman containers, one of them is qBittorrent, and it filled the entire rootfs. After enlarging the partition I still cannot log into the system, which lead me to investigate and found this issue.

I'm using btrfs single inside and dup outside of the VM disk, so that might be why it was corrupted.

Checking G/UID map shows the same symptom:
```
root@pve11:~# hexdump /mnt/@/var/lib/nixos/uid-map
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0000320 0000 0000 0000 0000 0000 0000          
000032b
root@pve11:~# hexdump /mnt/@/var/lib/nixos/gid-map
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0000200 0000 0000 0000 0000 0000 0000 0000     
000020d
```
which is why `update-users-groups.pl` failed as shown in OP's error message. This script is responsible of creating `/etc/passwd`, and as it failed, the system cannot load the user database.

I restored those 2 files from my backup and was able to log into my system again.

**Comment by Baitinq** [comment]
This is still a problem. I got this today and had to delete the `uid-map`
